### ISSUE TITLE
 [BLK] Scheda AD2_28 Errore 400

### ISSUE THREAD

**Issue by robragu** [anticorruzione/npa#1000]
Buongiorno, 
chiamando il servizio otteniamo la seguente risposta:

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"00672945-af96-11ee-9ec6-0050568e08b3"}

Spero in  un vostro aiuto e intanto ringrazio per l'attenzione.

**Comment by robragu** [comment]
Grazie per la considerazione

**Comment by agrumiecannella** [comment]
Ad oggi pare scomparsa la scheda

**Comment by supportoAnac** [comment]
Salve, si conferma che la [scheda AD2_28](https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/schede/modello-dati-schede-AD2.28.yaml)  è tuttora presente nel repository. 

Qualora si presentassero altre problematiche utilizzando l'ultima versione disponibile dei servizi, si prega di aprire una nuova segnalazione.
