### ISSUE TITLE
Errore ERR2 in creazione S2 su Appalto P1_16

### ISSUE THREAD

**Issue by scalabrese11** [anticorruzione/npa#1003]
Buonasera,

provando la creazione di una scheda S2 per l'appalto con idAppalto "1eb08573-0e32-4b68-8eb3-417cd242fa71" otteniamo il seguente errore:

ErrorResponse {
    class BaseResponse {
        instance: null
        status: 400
        title: KO
        detail: Errore
        type: about:blank
    }
    errori: [class ErroriEnum {
        class TipologicaSchemaErroriType {
            idTipologica: errori
            codice: ERR2
            dettaglio: null
        }
    }]
}

L'appalto in questione era in attesa di riscontro dal TED ed era stato passato a "pubblicato" manualmente in call con Anac.
Potrebbe dipendere da questo l'errore?
In tal caso sarebbe possibile ripristinare lo stato precedente ed avere l'esito da TED?

Grazie.

**Comment by mpizziconi** [comment]
la coerenza dei dati di pubblicazione aggiornati manualmente è stata sanata
