### ISSUE TITLE
Richiesta pubblicazione avviso

### ISSUE THREAD

**Issue by scalabrese11** [anticorruzione/npa#1004]
Buon pomeriggio,

sarebbe possibile sbloccare la pubblicazione di un appalto?

idAvviso: a73ca012-afd2-4ded-92b6-69cf84855ca0
idAppalto: 26aeccd7-72ae-432a-bca1-73d89655de77

Grazie

**Comment by mpizziconi** [comment]
operazione effettuata.
Si rammenta che gli appalti con schede pubblicate manualmente non possono essere presentati in certificazione per incongruenze nella corretta sequenza dell'esito delle operazioni
