### ISSUE TITLE
[ARIA SPA] Manifestazione di interesse

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1007]
Buongiorno,

dato che non è presente alcun riferimento alla Manifestazione di interesse nelle schede della PCP come dobbiamo comportarci in proposito? Possono essere ancora svolte manifestazioni di interesse?
possono essere svolte senza necessità di inviare alcun dato tramite la PCP?

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">Per le procedure con manifestazione di interesse (schede P7_1_1, P7_1_2, P7_1_3 che attribuiscono un CIG) è attualmente prevista la scheda S1 ‘Elenco dei soggetti che hanno manifestato interesse nelle procedure a due fasi’ a cui fa seguito la scheda S2 ‘Elenco offerte ricevute/OE invitati’.</span></span></span></p>

<p style="margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">Entro la metà di Ottobre sarà rilasciata la nuova scheda SIM (scheda S per l'Indagine di Mercato/Manifestazione di interesse) che non attribuisce CIG, utilizzabile a monte per le indagini di mercato relative a tutte le tipologie di affidamento diretto/negoziate, opzionale.</span></span></span></p>

<p style="margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">La SIM non porta all'identificazione di alcun OE aggiudicatario.</span></span></span></p>

<p style="margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">La scheda SIM ha lo stesso contenuto della scheda S1, ad eccezione del campo CIG.</span></span></span></p>

<p style="margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">La SIM potrebbe dare avvio ad un nuovo flusso. Le schede che possono seguire la SIM sono: AD1_29, AD1_30, AD1_31, AD1_32, AD2_29, AD2_30, AD2_31, AD2_32 AD3, AD5, P7_2.</span></span></span></p>

<p style="margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">GdL Dati</span></span></span></p>
