### ISSUE TITLE
[BLK] Servizi conferma-scheda - Scheda AC1: Errore REG74

### ISSUE THREAD

**Issue by cmestergiovanni** [anticorruzione/npa#1010]
Salve
L'esito operazione del conferma-scheda della scheda AC1 continua a restituirci il seguente errore: REG74.

Non riusciamo a capire dove intervenire per correggerlo.

GovWay-Transaction-ID: 9c8ca312-b0ac-11ee-9b99-0050568e9679
GovWay-Message-ID: ab778711-38d9-44d4-b1db-2f2a0ec2267c

**Comment by supportoAnac** [comment]
Sarà corretto il messaggio di errore e modificata la REG74 perché accetti anche lo 0 nel campo oneriDerivanti.
