### ISSUE TITLE
[BLK] [Maggioli] CRITICO: Gestione delega del RP a DRP

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1012]
**Piattaforma:** Appalti & Contratti e-procurement (UUID 8cd6d3b1-9523-5dd8-9b04-b80fa2e0d6da)
**Tipologia di gara:** NA (tutte le fasi, da pianificaizone, appalto a esecuzione)
**Valore Economico dell’Appalto:** NA
**idAppalto:** NA
**Fase Gara/Scheda in errore:** delega a un DRP (metodo aggiungi-soggetto)
**Errore riscontrato:** Vedi sotto
**Govway Transaction id:** NA
**Allegati:** NN

**Siamo in produzione senza poter gestire la delega.** Abbiamo bisogno di sbloccare questa funzionalità.
Nelle [Note di rilascio del 08/02/2024](https://github.com/anticorruzione/npa/blob/main/CHANGELOG.md) non vedo nulla a riguardo.
Riporto sotto in ordine cronologico le issue che ho trovato sulle specifiche e sui servizi per "aggiungi-soggetto" e delega in generale.
**Sono tutte in stato "aperto" senza risposta!**
Se per ora non si può fare, almeno date indicazione che si rinvia questa funzionalità al prossimo futuro. Stiamo avendo forti contestazioni dai nostri clienti su questa funzionalità. Come potete immaginare con la nuova gestione i RP vengono caricati di attività che prima delegavano in toto agli istruttori e ora non hanno modo di delegarle.

1. issue Consip [728](https://github.com/anticorruzione/npa/issues/728) del  Nov 24, 2023
2. issue Maggioli [736](https://github.com/anticorruzione/npa/issues/736) bloccante del Nov 27, 2023
3. Issue [895](https://github.com/anticorruzione/npa/issues/895) del Dic 18, 2023
4. Issue [904](https://github.com/anticorruzione/npa/issues/904) del Dic 18, 2023
5. Issue [933](https://github.com/anticorruzione/npa/issues/933) del Dic 21, 2023
6. Issue [966](https://github.com/anticorruzione/npa/issues/966) del Dic 29, 2023
7. issue Maggioli [988](https://github.com/anticorruzione/npa/issues/988) del Gen 8, 2024
8. issue Maggioli  [989](https://github.com/anticorruzione/npa/issues/989) del Gen 8, 2024
9. Issue L&G Solution [1008](https://github.com/anticorruzione/npa/issues/1008) del Gen 11, 2024

**Comment by paolo-urbanetto** [comment]
Resto un inguaribile ottimista.
Questo è il canale ufficiale per lo sviluppo, con questa issue sto cercando di chiedere ad ANAC prorità su uno dei temi che mi sembra tra i più critici perchè impatta sull'operatività degli utenti.
**Invito tutti i Titolari e Gestori che ritengono che questa sia una priorità ad aggiungere un commetto a questa issue.**
Mi sembra una forma condivisibile di sensibilizzazione.

Credo sia meglio così che mandare mail alla casella supporto.pcp@anticorruzione.it senza dare visibilità al problema.

Invito anche ANAC a riprogrammare i meeting settimanali di condivisione, preferibilmente aggiungendo temi più strategici e metodologici.

**Comment by mariottiDPA** [comment]
assolutamente d'accordo su tutto, ci uniamo anche noi alla richiesta (su questa issue ma non solo).
Importantissimo anche riprendere i meeting settimanali, con i quali qualche risposta almeno riuscivamo ad ottenerla

**Comment by pakozack** [comment]
@paolo-urbanetto noi il meccanismo di delega lo abbiamo implementato e sembra funzionare, almeno in collaudo. Ad esempio (caso testato e funzionante): appalto creato da utente (RP) che delega utente (DRP1). DRP1 conferma scheda. In collaudo questo funziona. 
Ci sarebbe da capire quando usare le deleghe e quando cambiare il RUP ad esempio per la fase di esecuzione in appalti fatti dalla CUC per conto di comuni... ma questa è un altra storia

**Comment by mariottiDPA** [comment]
anche noi come @pakozack, in collaudo sembra funzionare (per quanto l'RP, anche in presenza di un delegato, possa comunque effettuare operazioni, diversamente da quello che ci avevano detto), in produzione non ci hanno fatto segnalazioni ma non so se i clienti lo stiano utilizzando

**Comment by paolo-urbanetto** [comment]
A noi la situazione si presenta immutata. Quando il DRP eseguo un'operazione otteniamo forbidden 403.
Riporto sotto la sequenza di operazioni.

```
request: RP USRRUP22****UNO lancia crea-appalto per una scheda P2_16,
response: 200
	{
		idAppalto: "f2e0d8cc-c3df-4973-9a67-39555b45e407",
		govwayMessageId: "c8dece06-89be-4547-b925-6ca5b1ab0bd6",


		govwayTransactionId: "f4e1fcf8-bb51-11ee-9b99-0050568e9679"
	}
################################################################################
request: RP lancia aggiungi-soggetto con body:
	{
  	 	"ruolo": "DRP1",
    		"dataInizio": "2024-01-15T14:48:37Z",
    		"codiceFiscale": "USRDR14*****DUE",
    		"idAppalto": "f2e0d8cc-c3df-4973-9a67-39555b45e407"
	}
response: 200
	{	
    		"govwayMessageId": "e61f23d4-85b8-4eb7-b10d-1187a02a9b04",
    		"govwayTransactionId": "c9f409b9-bb52-11ee-9ec6-0050568e08b3"
	}	
################################################################################
request: DRP1 USRDR14*****DUE lancia verifica-appalto 
response: 403
	{
    		"govwayMessageId": null,
    		"govwayTransactionId": "354a692a-bb54-11ee-9ec6-0050568e08b3"
	}
################################################################################
request: RP USRRUP22****UNO lancia verifica-appalto 
response: 200
	{
    		"govwayMessageId": "240ee93a-2e5f-466a-9d5d-ae191aa34baf",
    		"govwayTransactionId": "677f31b0-bb54-11ee-9b99-0050568e9679"
	}

```

**Comment by paolo-urbanetto** [comment]
Viste le incoerenze sulla documentazione (vedi sempre issue [736](https://github.com/anticorruzione/npa/issues/736)) abbiamo anche aggiunto sul medesimo idAppalto f2e0d8cc-c3df-4973-9a67-39555b45e407 tutti i ruoli: DRP1, DRP2, DRP3 e pure "DRP".

**Il risultato è sempre una response con 403.**

L'unico che può operare è solo il RP (contrariamente a quanto detto a voce negli incontri di dicembre).

```
Chiamata "esito-operazione"

RP esito operazione 200
"govwayMessageId": "0cc5acc0-3846-4f77-8fa9-ccc85671baac",
"govwayTransactionId": "631ca6d5-bb94-11ee-9ec6-0050568e08b3"

DRP1 esito operazione 403
"govwayMessageId": null,
"govwayTransactionId": "cfe1f54e-bb94-11ee-9b99-0050568e9679"

DRP2 esito operazione 403
"govwayMessageId": null,
"govwayTransactionId": "ddb8e59a-bb94-11ee-9b99-0050568e9679"

DRP3 esito operazione 403
"govwayMessageId": null,
"govwayTransactionId": "3202f64f-bb95-11ee-9b99-0050568e9679"

DRP esito operazione 403
"govwayMessageId": null,
"govwayTransactionId": "587e2f9d-bb95-11ee-9b99-0050568e9679"

```

**Comment by paolo-urbanetto** [comment]
Aggiorno gli interessati.

Grazie al supporto di ANAC abbiamo scoperto che:

1. la specifica JWS è errata, va modificata specificano nell'enumerato il ruolo DRP1, DRP2, DRP3 e non DRP
2. la specifica "4.5 Servizi e ruoli" è errata e pure il servizio; ora prende DRP1 (delegato dal responsabile del progetto per la **fase di Programmazione**) sulle operazioni "comunicaAppalto" al posto di "DRP2" e va permesso al "DRP1" di agire sulle operazioni "pianificazioneAppalto"

Attendiamo fiduciosi da ANAC comunicazione a stretto giro del fix.

**Comment by paolo-urbanetto** [comment]
Buongiorno, questa issue si può chiudere per effetto del [Comunicato ANAC del 6 marzo](https://www.anticorruzione.it/-/comunicato-del-presidente-del-6-marzo-2024-responsabile-di-fase)
