### ISSUE TITLE
[BLK][Fiano Romano] Richiesta aiuto/spiegazione per errore 401

### ISSUE THREAD

**Issue by AndreaClerici** [anticorruzione/npa#1013]
Buongiorno,
avrei bisogno di supporto per un problema. Nell'effettuare una chiamata getBy dal contesto AUSA in ambiente di produzione, riceviamo il seguente messaggo di errore:
{"type":
https://govway.org/handling-errors/401/TokenAuthenticationFailed.html
,"title":"TokenAuthenticationFailed","status":401,"detail":"Invalid token","govway_id":"5490a39e-af9f-11ee-9ec6-0050568e08b3"}

Potete per favore aiutarci a capire come risolvere questo problema? Si tratta di un problema bloccante per noi.

Grazie.

**Comment by supportoAnac** [comment]
Si ricorda che le anomalie per le piattaforme di produzione sono gestite sul canale dedicato.
