### ISSUE TITLE
[BLK][Maggioli] Scheda P2_10 - Incongruenza richiesta codici fiscali diversi nelle s.a.

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1014]
Salve,
in fase di validazione di una scheda P2_10 ottengo  l'errore
REG3: I codici fiscali indicati nella lista delle stazioni appaltanti devono essere diversi
mentre passando lo stesso array delle stazioni appaltanti l'errore non mi compare nella validazione di una P1_16.
Il json viene in entrambi i casi composto con questo array delle stazioni appaltanti:

"stazioniAppaltanti": [
{
"codiceFiscale": "02193950421",
"codiceAusa": "9000000007",
"codiceCentroCosto": "a3f275fa-3f2d-4f19-b9bc-3114b25e94f1",
"funzioniSvolte": [
{
"idTipologica": "funzioniSvolte",
"codice": "2"
}
],
"saTitolare": false
},
{
"codiceFiscale": "01199250158",
"codiceAusa": "0000174139",
"codiceCentroCosto": "01F8BDA1-DAEC-4C79-A58A-BA4E7078E5CF",
"funzioniSvolte": null,
"saTitolare": true
},
{
"codiceFiscale": "00239740905",
"codiceAusa": "0000158078",
"codiceCentroCosto": "7CFD06AC-D22A-4C1A-8A75-B48FBCF2370F",
"funzioniSvolte": null,
"saTitolare": true
},
{
"codiceFiscale": "00239740905",
"codiceAusa": "0000158078",
"codiceCentroCosto": "3220ED53-0C66-46D0-90A2-A47F8E8CB497",
"funzioniSvolte": null,
"saTitolare": true
}
],

Gli ultimi 2 elementi dell'array rappresentano una sa con stesso codice fiscale ma centro di costo diverso.
Qual'e' la situazione valida? Perche' nelle 2 schede succitate il comportamento della validazione e' diverso?
Grazie.Arrivederci.

**Comment by supportoAnac** [comment]
Nell’oggetto stazioniAppaltanti i CF delle SA devono essere diversi. Ai fini del controllo il CdC è ininfluente.
