### ISSUE TITLE
[BLK][Maggioli] Scheda P3_1 Richiesta giustificazione aggiudicazione diretta ,ma non presente l'attributo

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1016]
Salve ,
componendo il json per una scheda P3_1 ottengo il seguente errore/avviso  in validazione:
REG67: il campo giustificazione aggiudicazione diretta è obbligatorio se il tipo di procedura è Negoziata senza previa indizione di gara
ma non mi risulta che nello schema yaml ci sia un attributo che permetta la trasmissione dell'informazione in oggetto.
Come posso procedere a riguardo?
Grazie, arrivederci.

**Comment by supportoAnac** [comment]
Segnalazione corretta, la regola è stata inserita per errore. Verrà eliminata al prossimo rilascio.
