### ISSUE TITLE
[Maggioli] Sincronizzazione pubblicazioni su piattaforme e PVL e vincolo di connessione sui servizi si consultazione del RP

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1017]
Nel caso di procedure ad evidenza pubblica è necessario che il RP si connetta e verifichi periodicamente se lo stato dell'avviso è passato in "pubblicato".
Ottenuto lo stato a pubblicato, il RP può procedere con la pubblicazione in piattaforma.
E' accaduto quindi che il bando sia visibile in PVL (https://pubblicitalegale.anticorruzione.it/) prima che sia visibile in piattaforma.
Ad es. il RP effettua il "pubblica-avviso" venerdì.
ANAC pubblica su PVL martedì.
Se il RP è in malattia o si dimentica di verificare lo stato ogni giorno a ogni ora, il bando sarà visibile in piattaforma giorni dopo la pubblicazione su PVL...

Soluzioni possibili:
1. Già richiesta più volte nei meeting: poter fruire del servizio di esito in modalità automatica (senza sessione del RP), con un processo schedulato che verifichi lo stato di pubblicazione almeno ogni ora
2. In alternativa: cambiare il modello: ogni Gestore espone su PDND un e-service "aggiorna stato pubblicazione" e ANAC lo consuma per notificare lo stato a pubblicato

Anche per questa issue invito i Titolari e Gestori che condividono questo problema a sottoscrivere la presente issue con un commento per dare visibilità della priorità ad ANAC.
Grazie

**Comment by mariottiDPA** [comment]
avere la possibilità di chiamare "in background", senza l'utente in sessione, lo stato-appalto (ma anche l'esito-operazione) sarebbe l'ideale.
Ci uniamo alla richiesta (DigitalPA)

**Comment by pakozack** [comment]
anche secondo noi la possibilità di eseguire chiamate in background sarebbe la soluzione migliore per questo e per altri problemi.

**Comment by paolo-urbanetto** [comment]
Oggi è successo (in produzione) che un ente si trovi con la pubblicazione fatta nella PVL e lo stato dell'appalto ancora in attesa pubblicazione!
Aiutoooo!

**Comment by paolo-urbanetto** [comment]
Il nostro caso specifico è stato risolto stamattina da ANAC (avevamo inviato mail a supporto.pcp con il riferimento a idAppalto).
