### ISSUE TITLE
[TOSCANA/BOLZANO] - Chiarimento invio scheda per la mancata aggiudicazione di un solo lotto - sottosoglia

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1018]
Salve,

Nel caso in cui mi ritrovo a gestire una procedura sottosoglia europea e devo comuniare che solo un lotto dell'intero appalto (multilotto) non risulta aggiudicato oppure è andato deserto, posso comunicarlo con la scheda NAG per i singoli lotti oppure con la scheda A2_XX che però è mancante del campo BT-144 “Not Awarded Reason” ?

Grazie.

**Comment by supportoAnac** [comment]
Per i sottosoglia **deve** essere utilizzata la scheda NAG per comunicare la mancata aggiudicazione dei lotti.
