### ISSUE TITLE
Programmazione Lavori - Servizi e Forniture

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#102]
Buongiorno, ancora nella documentazione non sono riuscito a trovare i tracciati che riguardano la trasmissione della programmazione Triennale Lavori e ex Biennale Servizi e Forniture, attualmente inviati tramite servizi di cooperazione applicativi al MIMS.
Parlo di "Programmazione" non di pianificazione/avvisi preinfo.
Eventualmente chiedo di essere indicato dove trovarli sotto https://github.com/anticorruzione/npa/

**Comment by supportoAnac** [comment]
Non sono previsti nella versione 1.x.x della PCP, questa fase verrà integrata successivamente.

**Comment by OperatoreIT** [comment]
<p>Gentile Utente, </p>

<p data-end="353" data-start="91">a seguito di una verifica condotta a sistema, si evince che la problematica riscontrata — per la quale non risulta visibile il fascicolo SOA nella sezione “I miei contratti” — è riconducibile a un’errata compilazione della richiesta di creazione del fascicolo.</p>

<p data-end="481" data-start="355">In particolare, nel campo <code data-end="393" data-start="381">SOA.codice</code> è stato inserito un codice fiscale anziché il codice identificativo corretto della SOA.</p>

<p data-end="760" data-start="483">A causa di tale incongruenza, il fascicolo non viene visualizzato correttamente.<br data-end="566" data-start="563">
Sarà pertanto necessario procedere con la creazione di una nuova attestazione SOA, assicurandosi di inserire i dati corretti nei relativi campi, al fine di ottenere una corretta visualizzazione.</p>

<p data-end="788" data-start="762">Restiamo a disposizione.</p>

<p><br>
Cordiali Saluti </p>
