### ISSUE TITLE
Scheda P2_16 - Impossibile inviare scheda NAG

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#1021]
Salve,

stiamo provando ad inviare la scheda NAG post S2, come da orchestratore.

Abbiamo inviato una  P2_16, seguita dalla S2.

L'id appalto è il seguente: 4dbdb775-64f4-40b0-90f1-24bcf85f3030, ci aiutate a capire?

Saluti

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione, includendo , oltre alla ID Appalto,  il payload delle schede inviate. Grazie per la Sua collaborazione.
