### ISSUE TITLE
[BLK] URGENTE PRODUZIONE - errore 504 - Gateway timeout

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#1024]
@mpizziconi 
Si sta verificando spesso in ambiente di produzione che le chiamate verso PCP vanno in errore con codice 504 - Gateway timeout.
Nonostante il messaggio di errore però l'operazione viene effettivamente eseguita sui sistemi.
Questo comportamento è disastroso, in quanto fa si che si verifichino inconsistenze tra il nostro sistema e PCP.
Si richiede di intervenire urgentemente per risolvere la problematica.
Chiedo anche ad altri colleghi di commentare se hanno gli stessi problemi

**Comment by paolo-urbanetto** [comment]
Confermiamo anche noi lo stesso problema in produzione!
Abbiamo inviato ieri la mail a supporto.pcp@anticorruzione.it e non abbiamo nemmeno avuto risposta di presa in carico del ticket.
E' urgente avere risposte e risolvere il problema!

**Comment by pakozack** [comment]
si @paolo-urbanetto abbiamo inviato anche noi email, ovviamente nessuna risposta. 
Ancora una volta mi chiedo a cosa serve questo canale dato che le issue aperte vengono puntualmente ignorate
