### ISSUE TITLE
Scheda P7_1_2 - Errore generico

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#1026]
Si ottiene al recupera esito di conferma di P7_1_2 
err41 --> "errore generico durante la validazione dei dati della scheda"
Per cui non si comprende dove si sta sbagliando di seguito i passi:
CreaAppalto:
GovWay-Transaction-ID	eef9c7c9-b459-11ee-9b99-0050568e9679
GovWay-Message-ID	83c9e30f-6327-4a25-abee-71675fc27e12
ConfermaAppalto:
GovWay-Transaction-ID	37b4b4cd-b45a-11ee-9ec6-0050568e08b3
GovWay-Message-ID	d63121a9-bed2-4da2-b636-b2bfc574a4e8
EsitoOperazione:
GovWay-Transaction-ID	3b2c9e17-b45a-11ee-9b99-0050568e9679
GovWay-Message-ID	20ef4365-a33b-4cc4-ba56-b491d2bd2c2a

Si allega anche la scheda trasmessa
[P7_1_2.json](https://github.com/anticorruzione/npa/files/13948986/P7_1_2.json)

**Comment by mariottiDPA** [comment]
Ci uniamo alla issue, anche a noi ha restituito diverse volte sia ieri che oggi, sia in collaudo che in produzione, err41 errore generico, su schede che in passato abbiamo confermato senza problemi.
Attendiamo risposte

**Comment by supportoAnac** [comment]
Il bug che generava ERR41 sulla conferma delle schede P7 è stato risolto in data 19/01/2024, alle 12.30 in qualificazione e alle 13.30 in esercizio.
