### ISSUE TITLE
Scheda P1_16 - Errore REG8

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#1027]
Salve,

per l'appalto in oggetto otteniamo l'errore REG8, nonostante il linkDocumenti sia valorizzato. Non vediamo aggiornamenti sul modello dati, quindi assumiamo che non sia cambiato nulla. Potreste dirci dove è il problema?

L'id appalto è il seguente: cdc37a44-27a6-4bc4-915b-c72841782da2
Saluti

**Comment by supportoAnac** [comment]
Da una verifica sul database il campo _appalto.linkDocumenti_ non sembra esserci per l'id appalto indicato. Si chiede gentilmente di fare un'ulteriore prova per verificare se l'errore persiste.
