### ISSUE TITLE
[BLK] Errore di autorizzazione in ambiente produzione

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#1028]
Ciao,

cercando di chiamare i servizi ci viene restituito un errore "Authorization Failed". Questa è la risposta integrale che otteniamo:
{
    "detail": "Authorization failed",
    "govway_id": "f6f115cc-b467-11ee-a2a9-00505684399c",
    "status": 403,
    "title": "Authorization",
    "type": "https://govway.org/handling-errors/403/Authorization.html"
}

Il problema si presenta in **ambiente di produzione**.

**Comment by supportoAnac** [comment]
Si ricorda che le anomalie per le piattaforme di produzione sono gestite sul canale dedicato.
