### ISSUE TITLE
[BLK] PRODUZIONE URGENTE Schede AD5 e P7_2 (Servizio crea-appalto) - Errore generico

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#1029]
@mpizziconi 
si sta verificando da qualche ora: il sistema ritorna errore generico in fase di crea-appalto. 
L'errore sembra diffuso. Sto vedendo sicuramente su AD5 e P7_2.
E' cambiato qualcosa?
Erorri generici anche in validazione di schede create precedentemente. Sempre "errore generico durante la validazione dei dati della scheda"

Anche qui chiedo anche ad altri se riscontrano lo stesso problema

**Comment by paolo-urbanetto** [comment]
Si, abbiamo "Errore generico" oppure "Timeout". 
Ho ricevuto alle 11:10 questa risposta dal supporto "Buongiorno, abbiamo in carico la segnalazione da altri utenti e stiamo lavorando per risolvere il problema" e poi nessun'altra comunicazione, quindi immagino stiano lavorando per la risoluzione.

**Comment by pakozack** [comment]
mah... secondo me stanno finendo di rompere quel poco che funzionava... vabbè vedremo!

**Comment by mariottiDPA** [comment]
anche noi lo stesso!

**Comment by pakozack** [comment]
@mpizziconi 
ma si può avere qualche aggiornamento? Possibile che abbiamo bloccato gli utenti da ieri? Riceviamo in continuazione lamentele dai nostri clienti per questa situazione. Ci sono anche RUP che hanno finanziamenti in scadenza e non riescono ad avere un CIG. Abbiamo scritto al "supporto dedicato" che ovviamente non ci ha risposto. Scriviamo qui e nessuno ci risponde. A chi di dobbiamo rivolgere?????

**Comment by pakozack** [comment]
Ragazzi ma qualcuno è riuscito a farle funzionare? A noi sono ancora bloccate con errore generico in fase di validazione della scheda. Inviate email al supporto... nessuna risposta!

**Comment by mariottiDPA** [comment]
Anche noi ancora stesso errore sia in collaudo che in produzione...

**Comment by pakozack** [comment]
Io sinceramente sono sconcertato... il supporto ANAC continua a dire agli operatori che loro non hanno nessun problema! Ovviamente poi i clienti si rivolgono a noi.

**Comment by pakozack** [comment]
Dipende dalle schede. Le AD funzionano, le P7_2 ad esempio danno sempre quell'errore

**Comment by paolo-urbanetto** [comment]
Ciao, ho fatto in test pochi istanti fa e la AD5 sono riuscito a completarla. La P_72 invece rimane in stato di errore alla validazione. 
Confermo quindi stessa situazione anche per Maggioli.

**Comment by pakozack** [comment]
@gianlucacuomo ma tu riesci a confermare anche le P7? Tipo P7_2?

**Comment by pakozack** [comment]
@mpizziconi 
In produzione P7_1_3 tutte bloccate
alcuni idAppalto

ff91a8ff-02e3-4531-a3f7-861bc5ccb5c7
ad4294b2-190f-4054-8e43-face3c1b4086
bbb2e44d-0a34-4442-8123-b81532d28915

**Comment by supportoAnac** [comment]
Il bug che generava ERR41 sulla conferma delle schede P7 è stato risolto in data 19/01/2024, alle 12.30 in qualificazione e alle 13.30 in esercizio.
