### ISSUE TITLE
Contesto FVOE - Richiesta documenti specifici ad OE

### ISSUE THREAD

**Issue by sfala** [anticorruzione/npa#103]
Per quanto riusciamo a comprendere, con il servizio /richiedi-documento è possibile richiedere l'acquisizione da parte del FVOE di documentazione relativa agli OE prodotta da soggetti/enti terzi (es. enti certificatori). E' previsto che una SA possa richiedere a un OE il caricamento nel proprio FVOE di documentazione eventualmente auto-prodotta o documentazione prodotta da soggetti/enti terzi che non hanno instaurato un canale verso FVOE?

**Comment by supportoAnac** [comment]
Il servizio consente alla SA di richiedere nuovi documenti o una nuova versione di documenti/Informazioni già presenti in fascicolo. Consente anche di recapitare all'OE una richiesta di inserimento/aggiornamento di documentazione/informazioni, tuttavia si tenga in considerazione quanto previsto dal DPR 445/2000 così come modificato dall'art 15 della L. 183/2011 ed il principio di unico invio (TOOP) emesso dalla Comunità Europea nel gennaio 2017.
