### ISSUE TITLE
[BLK] [Intercent-ER] URGENTE Problema bloccante su schede P7_1_2 e P_7_2 - ERR41 

### ISSUE THREAD

**Issue by AndreaClerici** [anticorruzione/npa#1030]
Buongiorno,
avremmo necessità di aiuto con estrema urgenza per il seguente problema.
Successivamente alle chiamate di crea appalto per le schede P7_1_2 e P7_2 che vanno a buon fine, l'esito operazione del conferma appalto restituisce il seguente errore:
_ERR41- "errore generico durante la validazione dei dati della scheda"_

Chiediamo supporto urgentemente per risolvere il problema.

Grazie

**Comment by supportoAnac** [comment]
Il bug che generava ERR41 sulla conferma delle schede P7 è stato risolto in data 19/01/2024, alle 12.30 in qualificazione e alle 13.30 in esercizio.
