### ISSUE TITLE
"Strumenti per lo svolgimento delle procedure" - Negoziate senza bando

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1031]
Salve,
il campo "Strumenti per lo svolgimento delle procedure" risulta obbligatorio solo per le procedure negoziate s.b. (schede anac previste) e prevede come opzioni ( Asta elettr., Mercato elettr., AQ, Sistema din. Di acquisto) questo presuppone che le negoziate senza bando è possibile farle solo se rientrano in queste casistiche ?

**Comment by UserM21** [comment]
@supportoAnac  è possibile avere un riscontro dopo vari mesi?

**Comment by anac-uscp** [comment]
<p>No, le tecniche di svolgimento della procedura (datiBaseStrumentiProcedura:AQ, Sistema din. Di acquisizione e asta elettronica) devono essere valorizzate a SI solo se utilizzate per lo svolgimento della procedura di gara. </p>

<p>La tipologica ‘strumentiSvolgimentoProcedure’ sarà a breve eliminata perché ridondante e non più attuale.</p>
