### ISSUE TITLE
Schede S1 e S2 - DGUE 

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1033]
Salve,
analizzando le schede :

-	S1 - Elenco di soggetti che hanno presentato manifestazione di interesse o domanda di partecipazione
-	S2 - Elenco di soggetti che hanno presentato offerta e di ulteriori invitati che non hanno presentato offerta.                          

Tra i dati richiesti non è previsto l'invio dell'xml di response da parte dell'operatore economico.
E' corretto?

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;">Nelle schede S1 (manifestazione di interesse o domanda di partecipazione) e S2 (elenco di partecipanti e ulteriori invitati), non è previsto l'invio dell'XML di response da parte dell'operatore economico. Le schede hanno lo scopo di riportare l'elenco dei partecipanti o invitati, ma l'invio di file XML di response non è parte del processo previsto da ANAC.</span></span></span></p>
