### ISSUE TITLE
[BLK] [Maggioli] Scheda P7_2  - Errore incomprensibile in stato esito-verifica 

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1035]
Salve ,
per una scheda P7_2 creata con
 idAppalto: 4e7ef09f-076e-49f8-bdd0-44d9cf72af92
 
in fase di consultazione della verifica (stato_esito) otteniamo il seguente errore:
ERR41 - errore generico durante la validazione dei dati della scheda
con i seguenti indicatori nella response:
govwayTransactionId:d982a55b-b521-11ee-9ec6-0050568e08b3
govwayMessageId:97ebd4e6-9828-4ddb-bff4-93836459d09d
Trattandosi di un errore generico non sappiamo come procedere per la correzione dei dati.
E' possibile avere dei chiarimenti?Grazie

**Comment by supportoAnac** [comment]
Il bug che generava ERR41 sulla conferma delle schede P7 è stato risolto in data 19/01/2024, alle 12.30 in qualificazione e alle 13.30 in esercizio.
