### ISSUE TITLE
Schede P1_23, P1_24, P1_23 e P1_24 - Piccola discrepanza tra settore ordinario e settore speciale

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1038]
si porta all'attenzione che la struttura di P1_23 - P1_24 e P2_23 - P2_24 differiscono esclusivamente per un attributo contrattiDisposizioniParticolari che, pur presente in tutte le schede, lo è a livello di Appalto per il settore ordinario, mentre è a livello di Lotti per quello speciale:
è un refuso oppure è una differenza voluta??

Grazie

**Comment by anac-uscp** [comment]
<p>Risolto con il Changelog del 6/8/2024</p>
