### ISSUE TITLE
[BLK] - Aggiudicazione impossibile in caso di S2 con più partecipanti

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#1039]
Abbiamo riscontrato una grave anomalia,
in caso di invio di una qualsiasi scheda di aggiudicazione, es A2.29,
preceduta da una scheda S2 dove al suo interno erano presenti più partecipanti (idPartecipante),
la conferma della scheda risulta impossibile a causa del seguente errore:
**il partecipante non è valido per il lotto**

Provando su altri appalti e inserendo nella scheda S2 un solo partecipante,
il problema sull'aggiudicazione non si presenta.

Che dobbiamo fare, mettere un solo partecipante nella S2?????

Chiedo anche ad altri colleghi se possono fare delle verifiche nei loro ambienti.

**Comment by pakozack** [comment]
Confermiamo l'errore sengalato

**Comment by mariottiDPA** [comment]
Confermiamo anche noi... no comment

**Comment by fabiovenditti** [comment]
Confermiamo l'errore segnalato

**Comment by CrisMaggioli** [comment]
L'errore continua a ripetersi. Anche per noi rappresenta un problema serio!

**Comment by supportoAnac** [comment]
Si chiede gentilmente di fornire l'ID appalto per una verifica approfondita.

**Comment by mariottiDPA** [comment]
@supportoAnac un esempio tra tanti, in collaudo:
idAppalto: 8f33f1e1-0ef5-4bc3-aac0-c91b349372ee

**Comment by supportoAnac** [comment]
Nella scheda di aggiudicazione sono stati indicati come aggiudicatari 2 partecipanti per lo stesso CIG. Il partecipante aggiudicatario non può essere piu di uno.

**Comment by matteolaltrelli** [comment]
L'anomalia non sembra essere risolta.
Abbiamo una stazione appaltante bloccata in produzione con questo errore:
ID Appalto: ab908971-7e01-493d-9dfe-07ed777a5d47
Scheda S2 inviata e confermata: 14391470-4765-45f5-81d4-253e8b5d7cce con i seguenti id_partecipanti:

8bdb2b92-a4f0-593d-a10f-875421dac34c
db411cd5-abc3-5dbf-a176-c9bb869ec496
95b9269c-4414-5dbc-a536-9e786b0fc7b5

In creazione scheda otteniamo il seguente errore:
CODICE: ERR77
DESCRIZIONE ERRORE: il partecipante non è valido per il lotto
idPartecipante: 8bdb2b92-a4f0-593d-a10f-875421dac34c - cig: XXXXXXX

"govway_message_id": "8e3e9e18-4f00-4898-8bc2-5d60a0e0ac2a",
"govway_transaction_id": "ad643d52-ec15-11ee-852e-005056844885",

Attendiamo urgentemente un riscontro
