### ISSUE TITLE
Contesto FVOE - Notifica di richiesta accesso a FVOE

### ISSUE THREAD

**Issue by sfala** [anticorruzione/npa#104]
A seguito dell'invocazione del servizio /richiesta-accesso-fvoe, NPA invia una notifica agli OOEE destinatari della richiesta?

**Comment by supportoAnac** [comment]
Esatto. NPA notifica all'operatore economico la richiesta di autorizzazione pervenuta mediante il servizio.

**Comment by OperatoreIT** [comment]
<p>Gentile Utente, </p>

<p data-end="251" data-start="91">a seguito di una verifica condotta a sistema, non si riscontrano anomalie: il fascicolo <strong data-end="188" data-start="179">FVQOE</strong> risulta correttamente presente all'interno dei nostri sistemi.</p>

<p data-end="507" data-start="253">Dall’analisi della chiamata d’esempio fornita nella precedente segnalazione, emerge che il path utilizzato fa riferimento all’ambiente di <strong data-end="409" data-start="391">qualificazione</strong>, mentre il fascicolo di interesse risulta presente esclusivamente nell’ambiente di <strong data-end="506" data-start="493">esercizio</strong>.</p>

<p data-end="666" data-start="509">Al fine di poter fornire un supporto adeguato, si chiede cortesemente di condividere maggiori dettagli, riportando la <strong data-end="665" data-start="627">chiamata effettivamente utilizzata</strong>.</p>

<p data-end="694" data-start="668">Restiamo a disposizione<br>
<br>
<br>
Cordiali Saluti  </p>
