### ISSUE TITLE
[mf] - Errore REG74 su scheda Accordo Bonario

### ISSUE THREAD

**Issue by marcofa1985** [anticorruzione/npa#1041]
Gentile supporto, 
la presente per segnalare uno strano errore sulla scheda di Accordo Bonario (AC1): dopo averla correttamente creata e confermata, all'atto dell'esitoOperazione riceviamo il seguente errore:

**REG74 - Non è stato valorizzato il nuovo importo della sicurezza** 

Questo ci risulta bizzarro perchè il campo di cui si parla sembra riguardare la scheda di modifica contrattuale e non quella di accordo bonario, che stiamo trasmettendo. 

E' possibile sapere come sanarlo?

Non avendo alcun govway_id perchè non ci sono di fatto "errori non gestiti" che possano rilasciare questi elementi, indico in sostituzione gli id dell'appalto e della scheda:

"idAppalto": "f3fe5bd6-c1e3-4f4d-b170-7bfdb2a9a3d7"
"idScheda": "247dc0cb-6a2a-427b-ab9b-ba4da7ab1d18"

Grazie, saluti

**Comment by fabiovenditti** [comment]
Anche noi riscontriamo lo stesso problema

**Comment by supportoAnac** [comment]
Fix rilasciata il 9 febbraio a seguito della segnalazione su https://github.com/anticorruzione/npa/issues/1010 .
