### ISSUE TITLE
Schede successive alla scheda CL1

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#1042]
Buongiorno, nel flusso schede successive dell'orchestratore per la scheda CL1 trovo anche la SC1. Chiedo perchè dopo il collaudo di dovrebbe procedere direttamente a una nuova sottoscrizione contrattuale, soprattutto senza passare per la variazione dell'aggiudicatario/società di scopo (S4).

Si tratta di un refuso o di una casistica particolare che a me sfugge? Posso avere maggiori info o magari un esempio?

Grazie

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="font-size:11pt;"><span style="line-height:102%;"><span style="font-family:Calibri,sans-serif;"><span style="color:#0070c0;">La presenza della scheda SC1 dopo la scheda di collaudo CL1 serve nell’eventualità di interruzione anticipata del contratto con l’aggiudicatario individuato e l’eventuale nuova contrattualizzazione con uno degli OE utilmente classificati in graduatoria. Quindi la CL1 servirà a definire il collaudo/regolare esecuzione della prestazione del primo aggiudicatario.</span></span></span></span></p>
