### ISSUE TITLE
Scheda RSU1 - Codici Fiscali OE

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#1043]
Buonasera,
nella scheda RSU1 è possibile inserire più codici fiscali per un subappalto, chiedo dunque se gli altri campi e tra questi quali (impresaestera*, ecc) debbanno essere compilati tante volte quanti sono i codici fiscali inseriti o una sola volta.

Grazie

**Comment by anac-uscp** [comment]
<p>Nella scheda RSU1 va inserito il CF del subappaltatore ovvero i CF degli OE che compongono il raggruppamento di impresa.</p>

<p>In caso di più subappaltatori, per ciascuno di essi sarà inviata una scheda 'subappalto' RSU1.</p>
