### ISSUE TITLE
[TOSCANA/BOLZANO] Scheda S2 - CF impresa ausiliaria

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1044]
Salve,

Nella scheda Partecipanti S2 è corretto che si indica l'avvalimento e la tipologia senza inserire il CF dell'impresa ausiliaria?

**Comment by paolo-urbanetto** [comment]
Noi (Maggioli) abbiamo inteso che va inserita nel "gruppo" dei partecipanti anche l'anagrafica dell'ausiliaria con tutti i dati
