### ISSUE TITLE
Errori TED troncati

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#1046]
Salve,

avendo anche noi lo stesso problema, seguiamo da giorni il ticket [996](https://github.com/anticorruzione/npa/issues/996) senza aver avuto nessun riscontro.

Ci risultano troncati gli errori di ritorno TED, non riusciamo ad andare avanti in questo modo. 

Non credo sia necessario, ma questo è l'idAppalto: cdc37a44-27a6-4bc4-915b-c72841782da2

Questa l'errore rilevabile da esito-operazione: 

`{"idTipologica":"errori","dettaglio":"[400] during [POST] to [http://pcp-qlf-ted-ms.pcp-qlf.svc:8080/validate?language=it] [TedMsClient#validate(String,String)]: [{"code":400,"status":"400 BAD_REQUEST","title":"Validation Error","errori":[{"idTipologica":"errori","dettaglio":"BT-21-Procedure deve essere presente in tutte le lingue ufficiali dell'avviso","codice... (3426 bytes)]","codice":"ERR46"}`

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 12/03/2024.
