### ISSUE TITLE
[Innovapuglia][BLK] Appalto in conferma da 4 giorni (AP_IN_CONF)

### ISSUE THREAD

**Issue by mcgirone** [anticorruzione/npa#1048]
Buongiorno,
in produzione abbiamo un errore bloccante relativo allo stato AP_IN_CONF di un appalto che non transita in stato confermato/errore da 4 giorni dal 2024-01-17 12:56:01.117 al 2024-01-22 15:08:14.717. Di seguito il json di risposta:
`{"listaEsiti":[{"idAppalto":"0b29c1bf-8870-451f-a034-7c63ee868502","idScheda":"6f703352-54d0-4164-91c3-c762f9c106f2","idAvviso":null,"esito":{"idTipologica":"esito","codice":"WT"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AP_CONF"},"dataControllo":"2024-01-17T13:56:00.328+01:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AP_IN_CONF"},"errori":null}],"status":200,"detail":"Esecuzione avvenuta con successo","title":"OK","type":"about:blank","errori":null}`
E' possibile sapere a cosa è dovuto il blocco o se ci sono errori in termini di eFORMS che non vengono restituiti?
Grazie

**Comment by supportoAnac** [comment]
Si ricorda che le anomalie per le piattaforme di produzione sono gestite sul canale dedicato.
