### ISSUE TITLE
Scheda S3 - Incarichi tecnici e prestazioni progettuali - chiarimento obbligatorietà campi 

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1049]
Salve,

Abbiamo provato in ambiente di collaudo ad inviare una scheda S3, ma sembra che questa non contenga nessun campo obbligatorio, tranne il CIG, unico campo obbligatorio.
E' possibile inviare una S3 senza inserire le informazioni?

Grazie.

**Comment by supportoAnac** [comment]
È teoricamente possibile ma non è corretto; verrà inserito un controllo più stringente per verificare che venga inserito almeno uno tra incarichi e prestazioni, oltre al CIG.
