### ISSUE TITLE
Scheda SC1 - Richiesta chiarimento conclusione anticipata

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#1050]
Posso fare un SC1 che contiene più cig con lo stesso idpartecipante (contraente) e poi posso fare una CO1 (conclusione anticipata) collegata a questa SC1 (quindi per tutti i CIG contenuti).
Ma se faccio una conclusione anticipata prima della SC1 posso indicare un solo CIG, quindi in questo caso le conclusioni anticipate precedenti alla SC1 sono una per cig corretto?

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="font-size:11pt;"><span style="line-height:104%;"><span style="font-family:Calibri,sans-serif;"><span style="color:#0070c0;">Corretto, è possibile fare una sottoscrizione del contratto (SC1) per più CIG aggiudicati allo stesso contraente (idpartecipante), seguita da una eventuale scheda CO1 per conclusione anticipata per tutti i CIG facenti parte dell’unico contratto.<br>
In caso di conclusione anticipata di uno dei CIG prima della sottoscrizione del contratto (SC1), deve essere inviata la CO1 per il singolo CIG ed in seguito inviare la sottoscrizione del contratto (SC1) per i restanti CIG. In caso di conclusione anticipata per più CIG prima della sottoscrizione del contratto (SC1), è necessario inviare una scheda CO1 per ciascun CIG.</span></span></span></span></p>
