### ISSUE TITLE
Errore TED bloccante

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#1052]
Salve,

stiamo integrando schede che prevedono in input l'eform TED obbligatoria. Nello specifico abbiamo questo errore, per noi, totalmente bloccante: 

> [400] during [POST] to [http://pcp-qlf-ted-ms.pcp-qlf.svc:8080/validate?language=it] [TedMsClient#validate(String,String)]: [{"code":400,"status":"400 BAD_REQUEST","title":"Validation Error","errori":[{"idTipologica":"errori","dettaglio":"Se 'Natura dell'appalto' (BT-23) è 'Servizi' e 'Tipo di classificazione' è CPV, allora... (2552 bytes)]

Non abbiamo idea di cosa ci sia dopo quell'allora... Abbiamo già aperto un ticket [simile](https://github.com/anticorruzione/npa/issues/1046), senza aver ricevuto alcun riscontro.

Potete, per cortesia, dirci come muoverci? È davvero impossibile lavorare così.

Grazie.

PS: idAppalto 280fc223-d93d-4a9a-8cfb-d43a89b66f84

**Comment by supportoAnac** [comment]
La problematica è stata analizzata, è necessario accertarsi di utilizzare l'ultima versione disponibile dei servizi [1.0.2](https://github.com/anticorruzione/npa/releases/tag/v.1.0.2), se dovesse presentarsi nuovamente si prega di aprire una nuova segnalazione.

**Comment by supportoAnac** [comment]
La anomalia risultante in errori TED troncati è stata risolta con il rilascio del 12/03/2024.
