### ISSUE TITLE
[PRODUZIONE][BLK] Impossibile confermare SC1 per ERR58

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1053]
Salve,
nella conferma della scheda SC1 dopo la AD3, viene restituito l'errore con codice **ERR58**: `operazione non consentita per lo stato della scheda`, tuttavia non sembrano esserci particolari condizioni per cui l'operazione di conferma non dovrebbe essere consentita. 

|  key | value |
| --- | --- |
| govway-message-id | `0d03801b-530e-423b-b1f7-a844e4a65e42`  |
| govway-transaction-id | `6cfa1811-b9c1-11ee-852e-005056844885` | 

Potremmo avere delucidazioni in merito da fornire al cliente?

**Comment by supportoAnac** [comment]
Si ricorda che le anomalie per le piattaforme di produzione sono gestite sul canale dedicato.
