### ISSUE TITLE
[PRODUZIONE][BLK] Response vuota in crea-appalto per AD3 - ERR38

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1054]
Salve, 
durante una **crea-appalto**, a seguito dell'invio della scheda abbiamo ottenuto una response vuota, senza indicazioni sull'avvenuta creazione o successo operazione. Senza questo dato, abbiamo provato nuovamente ad inviare la scheda, ma abbiamo ottenuto un **ERR38**. E' normale che avvenga una creazione con una risposta assente? Come dobbiamo interpretare questo comportamento? Se l'ambiente non ha un comportamento costante non riusciamo a gestire il flusso delle schede.

Dati transazione: 

|  key | value |
| --- | --- |
| govway-message-id | `7f29572c-592b-402f-9e60-13ca45cb7348`  |
| govway-transaction-id | `734ff1d3-b3b7-11ee-a2a9-00505684399c` |

**Comment by mariottiDPA** [comment]
sta succedendo su diversi clienti, la problematica è decisamente urgente

**Comment by collaudo5** [comment]
Confermiamo che anche sulle nostre piattaforme stiamo riscontrando questo tipo di comportamento. In alcuni casi ritentando le SA riescono a completare l'iter fino allo stacco del CIG, in molti altri casi le SA sono bloccate da giorni a causa di questo error38 restituito sul Crea Appalto. Abbiamo inviato una mail al supporto ma non abbiamo avuto riscontro.

**Comment by supportoAnac** [comment]
Si ricorda che le anomalie per le piattaforme di produzione sono gestite sul canale dedicato.
