### ISSUE TITLE
TEAMSYSTEM - Gestione controlli dei cig derivati

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1059]
nella gestione SIMOG, l'acquisizione dei CIG derivati per gli Ordinativi di Fornitura su Convenzione era subordinata alla verifica della caratteristica MODALITA_REALIZZAZIONE che sul CIG collegato (CIG MASTER) doveva assumere il valore "17" Accordo Quadro ovvero "18" Convenzione. 
si richiede se tale controllo è stato riproposto nella PCP è qual è l'attributo utilizzato.
Grazie

**Comment by anac-uscp** [comment]
<p>Si, il controllo è stato confermato nella PCP. Il campo CIG nella scheda di adesione ‘CIG relativo all’accordo quadro/convenzione cui si aderisce ‘ contiene il CIG dell’Accordo Quadro/Convenzione da cui discende l’adesione. </p>
