### ISSUE TITLE
FVOE - Richiesta documenti per più OOEE

### ISSUE THREAD

**Issue by sfala** [anticorruzione/npa#106]
Il servizio /richiedi-documento prevede "chiaveAccesso" (chiave dell'SA necessaria per accedere al FVOE.) e il parametro "codiceFiscaleSoggetti" (la lista dei cf. dei soggetto sui cui si rihiede il documento.) ma non capiamo come sia possibile richiedere documenti su diversi OOEE se la richiesta avviene passando un'unica chiave di accesso (ovvero quella di un'unico OE).

**Comment by supportoAnac** [comment]
NON è possibile richiedere documenti per diversi OE
La lista dei soggetti contiene la lista dei collaboratori dell'OE necessari alla richiesta per il tipo documento scelto.
