### ISSUE TITLE
[Intercent-ER] Richiesta chiarimento su possibilità di multiple istanze di recesso - scheda IR1

### ISSUE THREAD

**Issue by AndreaClerici** [anticorruzione/npa#1063]
Buongiorno,
avrei necessità di un chiarimento riguardo la possibilità di inviare multiple istanze di recesso.

Secondo il file schema-cronologia-schede.xlsx, dopo aver inviato una scheda IR1 (Istanza di recesso), non è possibile inviare una successiva scheda IR1. Ho verificato ed effettivamente il sistema attualmente vieta questa possibilità, ritornando l'errore ERR2 "La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata".

Tuttavia, ho verificato che è possibile inviare due schede IR1 per lo stesso flusso se non sono adiacenti tra di loro. Ad esempio ho verificato che il sistema accetta il seguente invio per lo stesso idAppalto: IR1 -> SA1 -> IR1.
Non sono sicuro di quanto possa avere senso nella realtà una possibilità del genere.

Per come avevo interpretato le regole, la piattaforma a cui lavoro ha vietato l'invio di più schede IR1 per lo stesso idAppalto/idContratto.
La mia domanda è quindi se è corretto lasciare la possibilità di inviare più schede IR1 per lo stesso idAppalto (basta non inviarle successivamente).

Grazie

**Comment by anac-uscp** [comment]
<p>Non è possibile inviare altre schede di IR1 (istanza di recesso) successive alla prima in quanto essa dovrebbe essere collegata alla mancata consegna del cantiere nella tempistica definita dal Codice.  <br>
Pertanto, una volta presentata l’istanza dell’operatore economico e la stazione appaltante abbia risposto si possono avere due casistiche:  <br>
1) l’istanza è fondata ed è accolta dalla stazione appaltante e quindi ha termine l’affidamento dell’appalto;  <br>
2) l’istanza viene rigettata dalla stazione appaltante e si prosegue nell’esecuzione dell’appalto senza ulteriori possibilità di ripresentare istanza di recesso. </p>
