### ISSUE TITLE
[Intercent-ER] Richiesta chiarimento su campo superatoTempo per scheda RI1

### ISSUE THREAD

**Issue by AndreaClerici** [anticorruzione/npa#1065]
Buongiorno,
avrei la necessità di un chiarimento sulla valorizzazione del campo superatoTempo per la scheda RI1. In pratica avrei necessità di capire se questo campo ha valore assoluto o relativo alla sospensione a cui fa riferimento la scheda. Mi spiego con un esempio.

Ipotizziamo una prima sospensione:

- invio la scheda SO1
- invio la scheda SQ1 perché viene superato il quarto del tempo
- invio la scheda RI1 con il campo superatoTempo valorizzato a true

La mia domanda riguarda una ipotetica seconda sospensione successiva alla prima quando nella prima sospensione si è già superato il quarto tempo. Nella secondo sospensione:

- invio la scheda SO1
- non invio la scheda SQ1 (perché si invia solo una volta, al superamento del quarto)
- invio la scheda RI1, ma in questa scheda come devo compilare il campo superatoTempo?

Vedo due possibilità:

1. valorizzo superatoTempo a true perché per questo idAppalto è già stato superato il quarto (quindi il campo ha un valore assoluto)
2. valorizzo superatoTempo a false perché per questa specifica sospensione non c'è stato il superamento (quindi il campo ha valore relativo e riferito alla specifica sospensione a cui fa riferimento)

Come devo valorizzare il campo superatoTempo in questa particolare casistica?

Grazie

**Comment by anac-uscp** [comment]
<p>Non è corretta l’affermazione che la SQ1 vada inviata, in generale, solo una volta per un dato appalto. <br>
Ogni volta che una singola sospensione supera il quarto del tempo, è obbligatorio inviare la SQ1 e, alla ripresa, inviare la RI1 con il valore del campo superatoTempo uguale a true. <br>
 <br>
 </p>
