### ISSUE TITLE
Pratiche P1_16 in attesa di pubblicazione

### ISSUE THREAD

**Issue by scalabrese11** [anticorruzione/npa#1067]
Salve,

è possibile fare un controllo sugli appalti che abbiamo in attesa di pubblicazione su TED da 15 giorni?

Di seguito i dati per la verifica:
- idAvviso: 0787b4e0-e63f-4dc6-ae3a-91de9250fc93 | idAppalto: fa68820d-95d0-4e27-a7f6-1202f756c2c9
- idAvviso: a73ca012-afd2-4ded-92b6-69cf84855ca0 | idAppalto: 26aeccd7-72ae-432a-bca1-73d89655de77

Grazie

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
