### ISSUE TITLE
[Toscana/Bolzano] - Struttura dati schede Post Pubblicazione

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1068]
Salve,

Analizzando la struttura dati delle schede Post Pubblicazione, ci confermate che sono tutte a livello di appalto e non di singolo CIG ?

Esempio: La scheda S3 viene inviata unica volta a livello di appalto e mi viene restituto errore se trasmetto la stessa S3 ma con un CIG diverso dal primo che fa comunque parte dell'appalto.

Grazie

**Comment by supportoAnac** [comment]
Si conferma che è possibile inviare una S3 per ciascun lotto. Sono attualmente in corso verifiche sulle sulle schede ammesse come successive a S3 per risolvere una anomalia.
