### ISSUE TITLE
Consecutio schede

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#107]
Dall'orchestratore supponendo di avviare il processo con una scheda P1.X la scheda successiva da richiamare sarà una scheda cross di tipo S1 o S2, successivamente all'utilizzo della scheda S2 sono riportate tutte le schede di tipo A.X di avviso pubblicazione. 
La domanda è: è necessario invocare la S2 prima di richiamare la A.X oppure è possibile inviare il crea scheda direttamente tramite una A.X in base al flusso definito dalla scheda iniziale P1.X. Nel caso sia necessario qual è il link tra le S2 e le schede A.X? Idem per le schede P1.X che richiedono come scheda successiva solo la S1.
Inoltre nel caso in cui le schede P1.X prevedano come scheda successia sia la S1 che la S2 quale bisogna usare, il flusso di riferimento è * quindi tutti i flussi, uso una scheda a piacere?

**Comment by supportoAnac** [comment]
Ogni flusso viene istanziato dalla trasmissione di una scheda di indizione (colonna N dell'orchestratore). Ogni appalto appartiene al flusso determinato dalla scheda iniziale (colonna Q ). Le schede trasmesse successivamente alla scheda iniziale sono ammesse solo se appartenenti al medesimo flusso o se sono schede cross (contrassegnate dal valore * nella colonna Q), quindi se successivamente ad una scheda cross deve essere inviata una scheda che appartiene ad uno specifico flusso tale scheda deve appartenere al flusso istanziato dalla scheda iniziale del processo.

Vedere anche 
issue #25 - cronologia inoltro anac-form
