### ISSUE TITLE
[Consip] - scheda P1.18 - ERR41

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1070]
in fase di conferma di un appalto con una scheda P1.18 riscontriamo ERR41 - errore generico durante la validazione dei dati della scheda.
Potete verificare? di seguito i riferimento dell'appalto.

"GovWay-Message-ID":["8e1b1f3f-0ca5-4fcc-a11d-7bcbbd4b9b27"]
"GovWay-Transaction-ID":["60b034de-ba04-11ee-9ec6-0050568e08b3"]

**Comment by supportoAnac** [comment]
Si chiede gentilmente di fornire la ID dell'appalto per potere procedere con le verifiche.
