### ISSUE TITLE
[Toscana/Bolzano] Scheda S2 - Avvalimento RTI

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1072]
Salve,

Abbiamo due dubbi da esporre:

1. Se creaiamo un PartecipanteType per ogni impresa ausiliaria, come fa ANAC a capire a quale impresa che fa l'avvalimento è associato quel PartecipanteType? 

2. Nel caso di RTI l'avvalimento viene dichiarato dalla mandataria per tutto il RTI oppure deve dichiaralo ogni singolo membro?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>L’impresa ausiliaria è soggetta alla verifica del possesso dei requisiti generali e speciali; la scheda S2 dovrebbe riportare obbligatoriamente anche il codice fiscale dell'impresa ausiliaria, ai fini dell’attivazione del FVOE.<br>
<br>
1) Tramite l'IdPartecipante l'ausiliaria è riconducibile all'impresa concorrente.<br>
<br>
2) In caso di RTI, va premesso che sia la mandante che la mandataria possono stipulare il contratto di avvalimento per la dimostrazione dei requisiti, e ogni impresa ausiliaria dovrebbe essere abbinata alla propria impresa avvalente. Stiamo verificando il funzionamento del flusso per la corretta gestione dell'informazione. </p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
