### ISSUE TITLE
Scheda Affidamento AD_3

### ISSUE THREAD

**Issue by d3mi2023** [anticorruzione/npa#1075]
Salve ho qualche quesito da porre riguardo la scheda AD3

1) La scheda va usata quando la stazione appaltante procede ad un affidamento diretto di importo superiore a 5000 euro e inferiore ai limiti ammessi per l’affidamento diretto ex art 50 comma 1 lett. a), b).
Pertanto una trattativa diretta o un confronto tra preventivi, per servizi in settore ordinario di importo inferiore ai 40.000€, deve usare questa scheda obbligatoriamente o è possibile usare altre schede? in caso di scelta differente (ad esempio AD2_25) occorre annullare, richiedere nuovamente un cig e rifare la gara?

2) Selezionata la scheda AD_3 procedendo alla compilazione del form che porterà al rilascio del CIG, si incontra la sezione  Aggiudicazioni. La sezione Aggiudicazioni riporta per ciascun Partecipante  il campo obbligatorio "Importo", ma come può essere obbligatorio questo campo se la trattativa non è ancora stata pubblicata e pertanto l'offerta non è ancora stata presentata? per non parlare del CIG che ancora non è stato ottenuto. Cosa va inserito in questo campo se l'aggiudicazione ancora non c'è stata?

3) Il campo in questione è davvero obbligatorio o è un refuso?

4) Mi è stato suggerito l'inserimento nel campo "Importo" dell'importo a base d'asta ma tale suggerimento non mi appare corretto, perché spesso le offerte (e quindi l'importo di aggiudicazione) in trattativa diretta sono inferiori alla base d'asta, per non parlare di un confronto di preventivi in cui si invitano più Partecipanti e ognuno formula una offerta con un importo diverso.
Cosa deve dunque inserirsi in tale campo "Importo" in questo caso?

Grazie in anticipo

**Comment by pg-volpentesta** [comment]
è possibile avere un riscontro?

Grazie

**Comment by anac-uscp** [comment]
<p>La scheda AD3 è deputata all'invio dei dati delle procedure di affidamento diretto che prevedono l'invio alla PCP solo a selezione avvenuta.</p>

<p>A breve sarà rilasciata una nuova scheda SIM (scheda S per l'Indagine di Mercato/Manifestazione di interesse) da usare a monte di tutte le tipologie di affidamento diretto/negoziate, opzionale, che prevede anche una scheda di terminazione qualora i controlli abbiano esito negativo e non si pervenga all'affidamento o si decida di non proseguire nelle procedure di affidamento (STEV - Scheda di terminazione delle verifiche FVOE).<br>
<strong>La SIM non porta all'identificazione di alcun OE aggiudicatario.</strong></p>

<p>La scheda SIM ha lo stesso contenuto della scheda S1 ad eccezione del campo CIG e non attribuisce CIG.</p>

<p>La SA che vuole attivare l’FVOE invia la nuova scheda SIM (Scheda per l’indagine di mercato senza attribuzione del CIG), con l’anagrafica di uno o più OE che hanno risposto alla manifestazione di interesse. Successivamente ai controlli, provvede all’invio della scheda AD1, AD2, AD3, AD5 per l'affidamento diretto o la scheda P7_2 per la negoziata senza bando, con le informazioni già presenti ed ottiene il CIG.</p>

<p>La procedura oggetto della richiesta sembra ricondursi alla comunicazione di una procedura negoziata che va quindi comunicata con la scheda P7_2.</p>

<p>La SIM potrebbe dare avvio ad un nuovo flusso. Le schede che possono seguire la SIM sono: AD1_29, AD1_30, AD1_31, AD1_32, AD2_29, AD2_30, AD2_31, AD2_32 AD3, AD5, P7_2.</p>

<p>La SA che non intende attivare l’FVOE, in sede di indagine di mercato, per i controlli esplorativi, invia direttamente una scheda AD1, AD2, AD3, AD5 o P7_2 ed ottiene il CIG.</p>
