### ISSUE TITLE
[BLK][Maggioli] P1_16 per appalto con ripetizioni: richiesta CIG Collegato in verifica appalto 

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1076]
Salve ,
dopo aver inviato una scheda P1_16 per un appalto che prevede somme ripetizioni , valorizzando il motivo collegamento con codice tipologica=10-No, nessuna ipotesi di collegamento, 
in fase di verifica appalto compare il seguente messaggio:
REG15- il campo CigCollegato e' obbligatorio se il motivo di collegamento CIG e' valorizzato oppure se l'appalto richiede ripetizioni.

A questo punto ricompilando la scheda e valorizzando il motivo collegamento con codice diverso da 10 (8..poi 9....) e valorizzando conseguentemente anche il campo CigCollegato,
in fase di verifica appalto compare il seguente messaggio:
REG14- se l'appalto prevede ripetizioni il motivo collegamento CIG deve essere: No, nessuna ipotesi di collegamento

Il secondo messaggio sembrerebbe contraddire il precedente.

Cosa dobbiamo fare per superare questo blocco?
grazie

**Comment by supportoAnac** [comment]
La segnalazione è corretta: la REG15 verrà modificata.
