### ISSUE TITLE
[BLK] - Anomalia accesso appalti

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#1079]
Abbiamo riscontrato una grave anomalia,
sia in parte web che nella api.
Il sistema sembra fare differenza alle maiuscole e minuscole nel codice fiscale!!!
Questo implica che se un utente crea un appalto e nella chiamata inviamo il codice fiscale in minuscolo,
l'appalto viene creato correttamente su PCP, ma non viene visualizzato sulla parte web di PCP.
Lo stesso utente con il medesimo codice fiscale in maiuscolo se prova ad operare sull'appalto appena creato riceve errore.
Questa anomalia va risolta immediatamente anche perché per questo dato non ha senso fare una distinzione su maiuscole o minuscole.
Ormai sono giorni che apriamo segnalazioni vs la mail di supporto senza ricevere nessun riscontro!!!

**Comment by supportoAnac** [comment]
Si ringrazia della segnalazione, la problematica descritta è stata analizzata ed è in fase di risoluzione.
