### ISSUE TITLE
Quesiti Generali di contesto

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#108]
Salve,
sono interessato al processo di evoluzione delle piattaforme di approvvigionamento pubblico per aderire alla nuova piattaforma messa a disposizione da ANAC.
avrei alcuni quesiti di carattere generale, prima di entrare nello specifico e proporre richieste legate a specifici contesti:

1. esiste un dizionario delle informazioni con la definizione generale delle stesse ed eventuali precisazioni relative ai contesti d'uso?
2. esiste una tipologica (o qualcosa di simile) che enumera tutti gli errori che possono essere presenti  nella response del servizio "esito-appalto" a seguito della richiesta di "verifica-appalto" e "verifica scheda"?
3. è possibile avere l'elenco di json relativi alle request dei servizi esposti (probabilmente swagger lo mette a disposizione, ma io non conosco la funzione relativa!!)??
4. Una domanda più tecnica e, forse, banale: l' "_" prima della variabile indica che la variabile è chiave della scheda??

ringrazio per il supporto e procedo con l'inserimento di altri quesiti più specifici.

Francesco

**Comment by supportoAnac** [comment]
Si prega di fare riferimento alle specifiche contenute nel presente repository.

**Comment by FRASCA57** [comment]
Ringrazio per la risposta, e la interpreto:

1. No, non esiste
2. Si, è errori.json  S.E.&O.
3. Si esistono dei template che possono essere visualizzati in swagger utilizzando il comando "try it out"
4. Non so la risposta perchè nel frattempo non sono riuscito da solo a trovarla!!

Immagino che debba continuare da solo.
