### ISSUE TITLE
strumenti per lo svolgimento delle procedure - negoziate senza bando

### ISSUE THREAD

**Issue by pb14702** [anticorruzione/npa#1080]
Buon pomeriggio,
in riferimento alla issue #1031 chiedo secondo quale  riferimento normativo sia obbligatorio, nelle negoziate  senza bando, dichiarare uno dei 4 strumenti elencati. Dette procedure vengono svolte su piattaforme telematiche certificate secondo i carismi dettati dal Codice e diverse da Aste elettroniche, AQ e non rientranti nel Mercato elettronico o SDA .

Ringrazio anticipatamente

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Nelle procedure negoziate senza bando, l'art. 63 del Codice Appalti stabilisce che la stazione appaltante deve giustificare l'uso di questa procedura, indicando chiaramente le motivazioni specifiche. Riguardo l'obbligo di dichiarare uno dei 4 strumenti previsti (come piattaforme telematiche certificate), la normativa richiede che venga specificato quale strumento viene utilizzato per la procedura. Questi strumenti sono in linea con i requisiti dettati dal Codice e devono essere selezionati correttamente.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
