### ISSUE TITLE
[Maggioli] Aggiornamento non retro-compatibile?

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1081]
Abbiamo visto che in ambiente di test non è stata mantenuta compatibilità con la versione 1.0.
Lo desumiamo dal fatto che le schede in versione 1.0 vengono bloccate (es. il codice ISTAT versione 1.0 non è più compatibile).

**Ci troviamo quindi oggi con dei Gestori autorizzati bloccati nella fase di test.**
Ammesso che adeguiamo il software entro domani, questi si certificano in versione 1.0.1?
E poi devono aspettare che vada in produzione la 1.0.1?

Nel caso di problemi in produzione, **non possiamo fare più fare test** finché non allineate tutto alla versione 1.0.1 (sempre che poi in test non si vada alla 1.0.2)...

Infine dobbiamo sincronizzarci tutti con l'aggiornamento in produzione nello stesso giorno e stesso orario?
Altrimenti gli utenti rimarranno bloccati fino a quando non aggiorneremo il software...

Di questi problemi avevamo parlato in più occasioni, chiedendo un ambiente **dev** diverso da **test** e **prod**.
Ci avete detto che non era possibile perchè PDND non lo prevede, ma che sarebbe stata gestita la **retro-compatibilità**.
Su PDND in realtà si possono esporre più versioni dello stesso e-service, quindi sia per TEST che per PROD si potrebbero gestire v 1.0 e v 1.0.1
Nel caso specifico poi il servizio non sembra cambiato, cambiano solo tracciati e regole DMN.
Non potete gestire solo la logica di backend del servizio perchè accetti anche schede in v 1.0?
Non potete aggiungere un tag "versione" su ciascuna scheda e applicare le regole DMN coerenti con la versione?

Cito inoltre la issue [997](https://github.com/anticorruzione/npa/issues/997) che anticipava questa mia e pone anche altri quesiti in merito alle schede già trasmesse in vari stati.

Perchè non rispondete più alle issue?

Perchè non riconvocate le riunioni con i Titolari e Gestori così riusciamo a lavorare tutti un po' meglio?

**Comment by lucaCorigliano-SA** [comment]
Una situazione a dir poco assurda.
Ignorando l'impossibilità di procedere con i test sulla v1.0.0 (che è enormemente grave di per se) è impensabile che non abbiano nemmeno documentato la procedura corretta per procedere a lavorare su procedure iniziate sulla v1.0.0 dopo l'aggiornamento.

**Comment by paolo-urbanetto** [comment]
Buongiorno. E' ora disponibile l'ambiente di "Attestazione" allineato alla versione dei servizi di "Produzione".
Se si usasse l'ambiente di "Attestazione" al posto di quello di "Qualificazione" (in aggiornamento continuo) il problema qui descritto non ci sarebbe.
Tuttavia, dato che ormai i casi di "dichiarazione di conformità" sono limitati (almeno per quanto ci riguarda), il problema è rientrato.
Potete quindi chiudere la issue.
Grazie
