### ISSUE TITLE
[Maggioli] Scheda di aggiudicazione seguente la P7_2

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1083]
Buonasera,
nella versione aggiornata dell'orchestratore non trovo ancora quale scheda di aggiudicazione va abbinata alla P7_2.
Se cerco il codice 72 in "flussoAppartenenza" ancora trovo solo la P7_2 e la NAG.

Nella issue [496](https://github.com/anticorruzione/npa/issues/496) chiusa il 15/12/23 avete scritto:
_Dopo l'invio della schedap P7_2 per una procedura negoziata sotto soglia bisogna inviare una delle schede di aggiudicazione di appalto, sopra o sotto soglia, settore ordinario, settore speciale, settore difesa e sicurezza. Al momento il flusso 72 non è stato inserito nelle schede di aggiudicazione. **L'orchestratore verrà aggiornato al primo rilascio utile che non avverrà prima dell’esercizio della piattaforma**._

Mi sono perso qualcosa?

Se no potete almeno indicare qui quali schede di aggiudicazione sono ammesse?
Sono accettate tutte? Dobbiamo andare per tentativi e provarle tutte?
A1_29, A1_30, A1_31, A1_32, A1_33, A1_34, A1_35, A1_36, A1_37, A2_29, A2_30, A2_31, A2_32, A2_33, A2_34, A2_35, A2_36, A2_37, A3_1, A3_2, A3_3, A3_4, A3_5, A4_1, A4_2, A4_3, A4_4, A4_5, A4_6, A7_1_1, A7_1_2

**Comment by paolo-urbanetto** [comment]
Buongiorno, sollecito risposta.
Potete indicare almeno in risposta alla issue quale/i sono le schede accettate dall'orchestratore a seguito di una P7_2?
Grazie

**Comment by paolo-urbanetto** [comment]
Si segnala che nell'ultima versione dell'orchestratore, relativamente all'art.76 del codice aggiunto nei riferimenti normativi della P7_2, lo stesso viene riportato nelle schede A7_1_1, A7_1_2.
Potete dare conferma?
Potete rispondere a questa issue e aggiornare l'orchestratore?

Stiamo aspettando da 2 mesi!

**Comment by anac-uscp** [comment]
<p>Sulla base dei seguenti flussi di aggiudicazione legati alla scheda P7_2:</p>

<table cellspacing="0">
	<tbody>
		<tr>
			<td><strong>Importo</strong></td>
			<td><strong>tipo di contratto</strong></td>
			<td><strong>tipo di settore</strong></td>
			<td><strong>tipo di regime</strong></td>
			<td><strong>scheda avvio</strong></td>
			<td><strong>scheda aggiudicazione</strong></td>
			<td><strong>note</strong></td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>appalto </td>
			<td>ordinario </td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_1</td>
			<td>trasmissione al TED dell'eform 25-avviso volontario sulla trasparenza preventiva</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>appalto </td>
			<td>ordinario </td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_2</td>
			<td>Nessuna trasmissione al TED</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>appalto </td>
			<td>speciale</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_1</td>
			<td>trasmissione al TED dell'eform 26-avviso volontario sulla trasparenza preventiva</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>appalto </td>
			<td>speciale</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_2</td>
			<td>Nessuna trasmissione al TED</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>appalto </td>
			<td>difesa e sicurezza (dlgs. 208/11)</td>
			<td>n/a</td>
			<td>P5/P7_2</td>
			<td>n/a/A7_1_1</td>
			<td>contratto escluso : PCP+interfaccia web<br>
			A7_1_1 con trasmissione al TED dell'eform 27-avviso volontario sulla trasparenza preventiva</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>concessione</td>
			<td>n/a</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_1</td>
			<td>trasmissione al TED dell'eform 28-avviso volontario sulla trasparenza preventiva</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>concessione</td>
			<td>n/a</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_2</td>
			<td>Nessuna trasmissione al TED</td>
		</tr>
		<tr>
			<td> </td>
			<td> </td>
			<td> </td>
			<td> </td>
			<td> </td>
			<td> </td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>appalto </td>
			<td>ordinario </td>
			<td>ordinario</td>
			<td>P7_2</td>
			<td>A_2_29</td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>appalto </td>
			<td>ordinario </td>
			<td>alleggerito</td>
			<td>P7_2</td>
			<td>A_2_33</td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>appalto </td>
			<td>speciale</td>
			<td>ordinario</td>
			<td>P7_2</td>
			<td>A_2_30</td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>appalto </td>
			<td>speciale</td>
			<td>alleggerito</td>
			<td>P7_2</td>
			<td>A_2_34</td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>concessione</td>
			<td>n/a</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A_2_32</td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>concessione</td>
			<td>n/a</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A_2_35</td>
			<td> </td>
		</tr>
	</tbody>
</table>

<p>l'orchestratore sarà modificato a breve come segue:</p>

<ul>
	<li>Introdurre nella colonna ‘flussoAppartenenza’ delle schede A7_1_1, A7_1_2, A2_29, A2_30, A2_32, A2_33, A2_34, A2_35, il flusso 72</li>
</ul>
