### ISSUE TITLE
[BLK] Modello dati non coerente - datiBase non presenti nelle openapi ma obbligatori

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1086]
A seguito del rilascio, dopo aver creato una P1_10 ed averla confermata otteniamo nell'`esito-operazione` 2 errori:
- **REG98** - _L'importo indicato nell'oggetto appalto.datiBase.importo deve essere > 0._
- **REG99** - _L'importo indicato nell'oggetto lotti.datiBase.importo deve essere > 0._

Tuttavia navigando l'openapi ed i reference collegati alla [P1_10](https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml) non vi è alcun riferimento a **datiBase** ne obbligatorio ne facoltativo. 

Si richiede quindi che il modello dati venga aggiornato per rendere l'informazione coerente con quella che il vostro sistema si aspetta in ingresso dal momento che allo stato attuale non è possibile inviare nessuna scheda che non contempli realmente datiBase (è stata testata a campione una P1_16 ed il risultato è il medesimo. Otteniamo ERR99 per dati base mancanti sul lotto).

L'aggiornamento di questa specifica sul modello verrà portata in esercizio dopo 30 giorni dal rilascio della stessa? Come indicato nel vostro readme alla sezione [Tempi di adozione delle nuove specifiche](https://github.com/anticorruzione/npa?tab=readme-ov-file#tempi-di-adozione-delle-nuove-specifiche)

Di seguito il json della chiamata a `esito-operazione` ed i dettagli della request:
```json
{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "d5682116-2c28-42b2-b72a-15b9bfb103ea",
      "idScheda": "ea56ac93-f803-4425-97ec-7f3f17d06aba",
      "codiceScheda": "P1_10",
      "esito": {
        "idTipologica": "esito",
        "codice": "KO"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AP_CONF"
      },
      "dataControllo": "2024-02-02T12:16:54.252+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AP_N_CONF"
      },
      "errori": [
        {
          "idTipologica": "errori",
          "dettaglio": "",
          "codice": "REG98"
        },
        {
          "idTipologica": "errori",
          "dettaglio": "",
          "codice": "REG99"
        }
      ]
    }
  ]
}
```

| key | value |
| --- | --- | 
| idAppalto | `d5682116-2c28-42b2-b72a-15b9bfb103ea` |
| gowvay-message-id | `e6ff8252-241e-4a83-91d6-b035236eff24` | 
| gowvay-transaction-id | `3cbd34a8-c1b8-11ee-9ec6-0050568e08b3` |

**Comment by masko82** [comment]
Mi accodo anche io alla issue.
Noi, in ambiente di collaudo, stiamo tentando di creare e confermare una P1_16 inserendo anche l'importo come indicato negli errori REG98 e REG99

{
    "codice":"REG98",
    "descrizione": {
		"it": "L'importo indicato nell'oggetto appalto.datiBase.importo deve essere > 0.",
		"en": "L'importo indicato nell'oggetto appalto.datiBase.importo deve essere > 0."
	},
    "dataInizio":null,
    "dataFine":null
},
{
    "codice":"REG99",
    "descrizione": {
		"it": "L'importo indicato nell'oggetto lotti.datiBase.importo deve essere > 0.",
		"en": "L'importo indicato nell'oggetto lotti.datiBase.importo deve essere > 0."
	},
    "dataInizio":null,
    "dataFine":null
}

Ma nonostante ciò ci viene restituito lo stesso errore.
Qualcuno sa darci una soluzione?

**Comment by scalabrese11** [comment]
Incorriamo anche noi nella stessa problematica di errori REG98 e REG99 su P1_16;
ci sono novità in merito?

**Comment by supportoAnac** [comment]
La regola citata è relativa all’obbligatorietà dell’importo. Per le schede soprasoglia la regola controlla il campo presente nell’eForm come BT-27.
Il 09/02/2024 è stato aggiornato il messaggio di errore della regola citata inserendo, per maggiore chiarezza, il riferimento al campo eForm.
Si riporta a seguito il messaggio: _“L'importo indicato nell'oggetto appalto.datiBase.importo deve essere > 0. In presenza di eForm verificare l'importo inserito nel campo EstimatedOverallContractAmount (BT-27).”_
Per non far scattare la regola occorre modificare l’eForm inserendo il campo BT-27 sia a livello di appalto che di lotto.

**Comment by gfalce** [comment]
Salve, sulla scheda P1_23 (concorso di progettazione sopra soglia) escono gli errori BT-27 relativi agli importi di appalto e lotto ma  sull'eform i campi non sono presenti. Perché è un concorso di progettazione?
