### ISSUE TITLE
[PDND] e-service produzione in fase di approvazione

### ISSUE THREAD

**Issue by argomauro** [anticorruzione/npa#1088]
Salve, siamo in attesa di abilitazione degli e-service su PDND in ambiente di produzione. 
Le finalità dei servizi avviati come Gestore di piattaforme di eProcurement 
(PUBLISYS SPA - P.IVA 00975860768) risultano ancora in fase di approvazione (come da allegato).
Potreste darci indicazioni in merito?

Grazie
Maurizio

**Comment by argomauro** [comment]
Allego l'immagine di riferimento:
![Uploading Schermata 2024-02-05 alle 09.36.34.png…]()

**Comment by supportoAnac** [comment]
Buongiorno, si raccomanda di utilizzare il seguente form https://supportcenter.anticorruzione.it/ e si ricorda che le anomalie per le piattaforme di produzione sono gestite sul canale dedicato.
