### ISSUE TITLE
[BLK] - CO2 non funzionante

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#1089]
Con la nuova versione, la scheda CO2 continua a non funzionare.
Nello specifico, otteniamo il seguente errore:
ERR40 - errore generico durante l'estrazione dei dati della scheda

Ovviamente come al solito errori generici che non ci permettono di capire nulla.
Chiedo anche agli altri colleghi di fare un po' test.

**Comment by lucaCorigliano-SA** [comment]
Persiste nella v1.0.2...

**Comment by DemontisAndrea** [comment]
Il problema persiste:
govWayTransactionID: `7c3aad5d-d190-11ee-9ec6-0050568e08b3`

Rimaniamo in attesa di novità a riguardo, grazie.

**Comment by fabiovenditti** [comment]
Confermiamo anche di ARIA riscontriamo il problema

**Comment by supportoAnac** [comment]
Si chiede gentilmente di fornire maggiori informazioni (idAppalto, payload delle schede trasmesse, etc) allo scopo di effettuare verifiche.

**Comment by fabiovenditti** [comment]
> Si chiede gentilmente di fornire maggiori informazioni (idAppalto, payload delle schede trasmesse, etc) allo scopo di effettuare verifiche.

La scheda CO2 viene creata correttamente ma al conferma ci restituisce
"codice": "ERR40" - errore generico durante l'estrazione dei dati della scheda
GovWay-Transaction-ID	f9a43d8d-d1ff-11ee-9b99-0050568e9679
GovWay-Message-ID	5031e7df-c4d3-411d-9408-76efbf4ed970

**Comment by matteolaltrelli** [comment]
La scheda CO2 viene creata correttamente ma al conferma ci restituisce
"codice": "ERR40" - errore generico durante l'estrazione dei dati della scheda
idAppalto: f93408fa-74b6-4aa5-bb5e-39d79e446a93
"govway_message_id": "c4786bd0-4468-4a18-a58a-721261cae679",
"govway_transaction_id": "9c1a9b6d-d560-11ee-9b99-0050568e9679"

Vedendo la diffusione del problema credo ci sia un bug generale nella conferma di questa scheda.

**Comment by supportoAnac** [comment]
Si conferma la risoluzione della problematica con l’ultimo rilascio.
