### ISSUE TITLE
Innesco dei servizi pubblicaAvviso

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#109]
salve,
non mi è chiaro se i servizi di pubblicaAvviso debbano essere innescati dalla SA oppure vengono automaticamente richiamati alla conferma della scheda che li richiede (es. conferma-appalto, conferma-scheda (tipo aggiudicazione) etc. etc.).
Nella documentazione non è scritto nulla circa il conferma-appalto (a meno che mi sia sfuggito), mentre per il conferma-scheda c'è scritto:
_**Nel caso in cui si tratti di una scheda che prevede la pubblicazione sulla Piattaforma nazionale o sul TED il sistema invocherà il servizio pubblica-avviso per completare la transizione allo stato successivo dell’Appalto o per poter confermare la scheda successiva in lavorazione e, mediante la successiva invocazione al servizio esito-operazione sarà possibile recuperare l'idAvviso assegnato**_

grazie per il supporto.

Francesco

**Comment by supportoAnac** [comment]
1. Con soluzione di continuità, la SA richiama il servizio pubblica-avviso in maniera esplicita per pubblicare la scheda confermata tramite il servizio conferma-appalto 
2. Senza soluzione di continuità, il back-end NPA richiama il servizio pubblica-avviso in maniera implicita per pubblicare le schede che lo richiedono, confermate tramite i servizi di conferma-scheda, conferma-piano, modifica-avviso, rettifica-avviso.
