### ISSUE TITLE
Aggiornamento tipologiche

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1093]
Salve,

- non è chiaro se è stato aggiornato il json relativo al Ruolo OE, prima presente nel changelog e poi eliminato dalla lista
- quali sono le categorie eliminate rispetto all'aggiornamento del relativo json?

**Comment by glastra-digitalpa** [comment]
Sembra che abbiano semplicemente rimosso la riga dal CHANGELOG: https://github.com/anticorruzione/npa/commit/0b6b48af80c71260b6304935b31a03d779dde821 il file ruoloOE.json invece è rimasto modificato come si vede dal diff: https://github.com/anticorruzione/npa/commit/a92a33d9b21365416ae6c666f8009019b96213cf#diff-d7df1bbbd1cad88f7f9141deb4b73f6f1866f6650a8942bf9e582766bbe9f3d1

**Comment by UserM21** [comment]
Si lo credo anche io, ma meglio avere conferma scritta da ANAC

**Comment by supportoAnac** [comment]
Si conferma che era stata erroneamente rimossa la riga dal Changelog e che è corretto fare riferimento al  differenziale [a92a33d](https://github.com/anticorruzione/npa/commit/a92a33d9b21365416ae6c666f8009019b96213cf#diff-d7df1bbbd1cad88f7f9141deb4b73f6f1866f6650a8942bf9e582766bbe9f3d1) citato.

**Comment by obigno77** [comment]
Le voci rimosse dalla tipologica Categoria sono

- OG1
- OG10
- OG11
- OG12
- OG13
- OG2
- OG3
- OG4
- OG5
- OG6
- OG7
- OG8
- OG9
- OS1
- OS10
- OS11
- OS12
- OS13
- OS14
- OS15
- OS16
- OS17
- OS18
- OS19
- OS2
- OS20
- OS21
- OS22
- OS23
- OS24
- OS25
- OS26
- OS27
- OS28
- OS29
- OS3
- OS30
- OS31
- OS32
- OS33
- OS34
- OS4
- OS5
- OS6
- OS7
- OS8
- OS9
- 

che hanno le corrispondenti con lo spazio tra OG/OS e il numero della categoria

OG 1
OG 10
….
