### ISSUE TITLE
[BLK] Problematiche su elementi scheda ottenuti dall'eform

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1097]
A seguito dell'issue #1086 abbiamo notato che in alcuni casi è possibile "bypassare" la mancanza di datiBase nelle api, andando a compilare il campo **facoltativo** dell'eform `EstimatedOverallContractAmount`. 

Ci sono quindi le seguenti problematiche:
- l'errore fa riferimento all'anacForm e non all'eform rendendo di fatto impossibile per l'utente finale capire quale sia il problema.
- Il campo EstimatedOverallContractAmount non è necessariamente obbligatorio (ad esempio nell'eform relativo alla P1_16 non lo è), di conseguenza la StazioneAppaltante non è tenuta ad inviare questo dato e non si aspetta di doverlo compilare (dato che nemmeno nell'anac form è presente).
- Come per datiBase.importo ci sono altri campi che vengono letti dall'eform? Se sì quali?

**Comment by supportoAnac** [comment]
Si conferma che il comportamento è previsto ed atteso: la descrizione dell'errore è stata migliorata indicando i campi corrispondenti dell'eForm, che sono quelli individuati da ANAC come campi in comune col TED. Pur essendo campi facoltativi nell'eForm, sono obbligatori a livello di pubblicazione nazionale.
