### ISSUE TITLE
Chiarimenti su eform nella scheda  P4_1

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1099]
Come dobbiamo interpretare i due eform presenti in corrispondenza della P4_1 all'interno dell'orchestratore?
Sono entrambi permessi o soltanto il primo?

Poiché se compiliamo un eform 19 e lo alleghiamo alla scheda P4_1 otteniamo: `ERR2 - Notice non coerente con la scheda in input`
![image](https://github.com/anticorruzione/npa/assets/147037233/d4f1f241-afd4-4a47-b0f8-85de2e586865)

**Comment by anac-uscp** [comment]
<p>Buongiorno, entrambi gli eForm sono ammessi, in modalità mutuamente esclusiva. <br>
 </p>
