### ISSUE TITLE
FVA e connessione servizi  NPA

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#11]
Che ruolo gioca il FVA in relazione agli altri servizi? Ad  esempio, è indispensabile che esista una istanza del FVA per poter invocare il conferma appalto?

**Comment by supportoAnac** [comment]
La creazione del FVA è gestita dalla piattaforma NPA ed è trasparente alle logiche delle piattaforme telematiche delle SA. Pertanto l'invocazione del servizio di conferma-appalto non necessita di sapere se esiste o meno il corrispondente FVA già creato.
