### ISSUE TITLE
Gestione dell'idScheda

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#110]
Buongiorno,
nella documentazione è specificato che l'idScheda è un campo prodotto da ANAC e restituito nella response di ogni servizio di creazione.
Nel crea-scheda, ciò accade, mentre nel crea-appalto viene restituito esclusivamente l'idAppalto.
La domanda è se e come valorizzare l'idScheda in questa casistica.

Grazie per l'aiuto.

Francesco

**Comment by supportoAnac** [comment]
Le operazioni del contesto comunicaAppalto nella request di input richiedono solo l'idAppalto. L'attributo  _idScheda è invece un campo generato da ANAC il cui valore se inserito in input viene ignorato dal sistema. Invece, le operazioni del contesto comunicaPostPubblicazione richiedono in input anche l'idScheda, che sarà pertanto restituito dallo specifico servizio di creazione.
