### ISSUE TITLE
Richiesta chiarimenti - Nomina DRP2 DRP3

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1101]
Salve,
dalle specifiche leggo quanto riporto di seguito:

Modulo NPA | comunicaPostPubblicazione | crea-scheda | RP, DRP2, DRP3
Modulo NPA | comunicaPostPubblicazione | modifica-scheda | RP, DRP2, DRP3
Modulo NPA | comunicaPostPubblicazione | cancella-scheda | RP, DRP2, DRP3
Modulo NPA | comunicaPostPubblicazione | ricerca-scheda | RP, DRP2, DRP3
Modulo NPA | comunicaPostPubblicazione | consulta-scheda | RP, DRP2, DRP3
Modulo NPA | comunicaPostPubblicazione | verifica-scheda | RP, DRP2, DRP3
Modulo NPA | comunicaPostPubblicazione | conferma-scheda | RP, DRP2, DRP3

dato l'assunto che si legge sempre nello stesso documento:
 **Il DRP ha accesso esclusivamente alle operazioni per le quali ha ricevuto delega.** 

In caso di nomina di entrambi i DRP chi può richiamare i servizi sopra elencati?

Grazie.

**Comment by supportoAnac** [comment]
In caso di nomina di DRP2 e DRP3, entrambi possono richiamare i servizi elencati, come da tabella di riferimento dei Ruoli.
