### ISSUE TITLE
RIchiesta chiarimenti - nomina DRP1 e DRP3 

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1102]
Salve,
è possibile nominare la stessa persona come delegato per più fasi?

esempio:

Mario Rossi DRP1 
Mario Rossi DRP3

Grazie.

**Comment by supportoAnac** [comment]
Si conferma che è possibile associare la stessa persona a ruoli differenti.
Come informazione aggiuntiva si precisa che non è invece possibile associare persone differenti ad uno stesso ruolo.
