### ISSUE TITLE
Ambiente di collaudo - Tipo scheda: P2_16

### ISSUE THREAD

**Issue by MatteoNetaComge** [anticorruzione/npa#1104]
Buongiorno, mi ricollego all'issue #1092 per segnalare lo stesso problema per il Comune di Genova. Ad oggi, per questo blocco non riusciamo a terminare i test nell'ambiente di collaudo. 
Riuscite cortesemente a darci supporto ?

**Comment by supportoAnac** [comment]
La segnalazione è corretta, le regole saranno corrette al prossimo rilascio.

**Comment by MatteoNetaComge** [comment]
Buongiorno, grazie per il riscontro. 
Sarebbe possibile avere una data prevista per il rilascio della correzione? 
Grazie mille
