### ISSUE TITLE
Chiarimenti P7_3

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#1105]
La scheda è da utilizzare per comunicare un avviso per la costituzione di un elenco fornitori, da cui poter attingere per individuare operatori economici da invitare in successive procedure negoziate.

Tra i dati richiesti sono presenti "oggetto della gara", "oggetto del lotto" e altre informazioni proprie della procedura e non dell'elenco fornitori. Inoltre, l'elenco potrebbe essere utilizzato per più di una procedura. Come occorre valorizzare tali dati?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Nella piattaforma PCP, per un avviso relativo alla costituzione di un elenco fornitori, i dati come "oggetto della gara" e "oggetto del lotto" devono essere valorizzati con riferimenti generici e inclusivi che descrivano lo scopo dell'elenco, ad esempio: "Costituzione di elenco fornitori per [settore/ambito]", evitando dettagli specifici relativi a singole procedure, che saranno definiti solo al momento del loro avvio.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
