### ISSUE TITLE
Aggiornamento Tipologica Ruolo OE - Gestione del pregresso

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1106]
Salve,
il rilascio previsto in esercizio il 01/03/2024, vede anche l'aggiornamento della tipologica relativa al RUOLO OE. 

1. Cosa accade per le procedure pre rilascio aventi le precedenti tipologiche?
2. Verranno ancora accettate?

Grazie

**Comment by obigno77** [comment]
L'aggiornamento della tipologica prevede l'aggiunta di nuove voci quindi le precedenti continueranno a essere valide e accettate
