### ISSUE TITLE
[Toscana/bolzano] - Appalto soprasoglia deserto

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1107]
Salve,

E' possibile sapere qual'è il flusso successivo ad una scheda di pubblicazione soprasoglia con eForm che non presenta alcun partecipante?

Con quale scheda posso comunicare l'appalto deserto?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Per annullare appalti sopra soglia europea è necessario pubblicare schede di aggiudicazione (schede A1*) corredate da relativo eForm, dove specificare la "mancata aggiudicazione".</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>

<p> </p>
