### ISSUE TITLE
[BLK] Codice NUTS ITF65 (Reggio Calabria) non presente in codNUTS.json

### ISSUE THREAD

**Issue by lucaCorigliano-SA** [anticorruzione/npa#1108]
Come segnalato da alcuni clienti bloccati in fase di compilazione, in codNUTS.json è mancante il codice ITF65 riferito a Reggio Calabria. 

Questo chiaramente porta in compilazione all'ERR63 quando si usa un database NUTS completo ed aggiornato.

Porto come riferimento dati il sito europeo: https://ec.europa.eu/eurostat/web/nuts/history . ITF65 è ancora presente in NUTS2024.

È stato eliminato nel commit `a92a33d9b21365416ae6c666f8009019b96213cf` in quanto la sua data di scadenza era (erroneamente) riportata come 1900-01-01.

Si chiede una veloce verifica e correzione del file.

**Comment by supportoAnac** [comment]
Segnalazione corretta, la tipologica verrà integrata della voce mancante al prossimo rilascio utile.
