### ISSUE TITLE
[Toscana/Bolzano] - Flusso AD3

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1109]
Salve,
Avevamo un dubbio in fase di test, si può inviare una scheda S3 dopo una AD3 oppure è necessario inviare prima SC1 ?

In ambiente di test ci viene restituito l'errore:
"ERR2 - scheda non ammessa in questa fase dell'appalto”

**Comment by supportoAnac** [comment]
Si prega gentilmente  di effettuare un nuovo test. Se viene restituito il medesimo errore, si chiede di aprire una nuova issue e fornire la ID Appalto e il payload in ingresso, allo scopo di effettuare una verifica.
