### ISSUE TITLE
[BLK] ERR63 - "Tipologica Non valida"

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1110]
Dal rilascio del **09/02/2024** (in cui sono avvenute correzioni e modifiche senza nessun preavviso) risultano esserci sia in esercizio che in collaudo delle tipologiche non valide. In particolare, sembrano essere indicate non valide le tipologiche che hanno una `dataFine` antecedente alla data attuale. Si chiede un urgente riscontro, dal momento che risulta impossibile inserire tipologiche come `"Procedure svolte attraverso piattaforme telematiche di negoziazione "` per la tipologica `strumentiSvolgimentoProcedure`. 

A titolo esemplificativo abbiamo inoltre provato ad utilizzare la tipologica con `"codice": "4"` per `strumentiSvolgimentoProcedure`, ottenendo lo stesso risultato

**Comment by gianlucacuomo** [comment]
Ci uniamo anche noi alla segnalazione, ma più in generale si richiede maggiore trasparenza e documentazione puntuale sull'allineamento dei vari ambienti e il rilascio degli aggiornamenti.

Ogni volta si bloccano migliaia di utenti

**Comment by sfala** [comment]
Buongiorno,
anche i nostri utenti sono bloccati.

**Comment by claudiocarotenuto** [comment]
Buongiorno
Anche noi di Invitalia riscontriamo la stessa problematica.
Grazie

**Comment by lucaCorigliano-SA** [comment]
Notate bene che le tipologiche vanno filtrate in base alla loro dataInizio e dataFine. Nella tua fattispecie concreta "Procedure svolte attraverso piattaforme telematiche di negoziazione" con codice 5 risulta scaduto al 31-12-2023 e quindi non può essere utilizzato.

**Comment by anac-uscp** [comment]
<p>Risolta dal Changelog del 12/03/2024</p>
