### ISSUE TITLE
[BLK] Impossibile individuare nel repository differenze fra collaudo ed esercizio

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1111]
A seguito dell'ultimo rilascio del **09/02/2024** (in cui sono avvenute correzioni e modifiche senza nessun preavviso), non è possibile capire quali regole DMN, tipologiche, e strutture dati siano presenti in esercizio e quali soltanto in collaudo.

Sarebbe bello se nel repository questa informazione apparisse più chiara e puntuale, ad esempio mantenendo il main con tutte le modifiche in collaudo, e gestendo un branch che rifletta lo stato dell'ambiente in produzione.

Allo stato attuale, quando arriva una segnalazione di un cliente non riusciamo a capire consultando il repository se gli errori che ricevono dalle chiamate siano quelle che visualizziamo sul repository oppure facciano riferimento ad una versione precedente dello stesso. Al contempo, con l'ultimo rilascio la situazione si è complicata ulteriormente con l'inserimento/aggiornamento di tipologiche che sono approdate direttamente in esercizio.

Come richiesto altre volte, inoltre, sarebbe per noi molto importante avere un ulteriore ambiente di collaudo allineato alla versione in esercizio, in modo da poter verificare e replicare problematiche segnalate dai clienti.

**Comment by gianlucacuomo** [comment]
Ci uniamo anche noi alla segnalazione

**Comment by supportoAnac** [comment]
Al momento in ambiente di esercizio viene utilizzata  la v 1.0.0,  su cui sono state implementate le fix indicate  nelle note di rilascio del 09/02/2024, mentre in ambiente di qualificazione viene utilizzata la v1.0.2.
La segnalazione verrà utilizzata per rendere più informativo e dettagliato il changelog per i prossimi rilasci.

**Comment by gianlucacuomo** [comment]
Potrei suggerire una modalità diversa di gestione della repository? Magari utilizzando i branch al posto dei tag?

Si potrebbe avere il master allineato all'esercizio, un altro branch allineato all'ambiente di qualificazione e poi i singoli branch per la pubblicazione delle varie versioni.

In questo modo penso che sarebbe più chiaro per tutti capire cosa c'è su quale ambiente in un determinato momento.

I tag poi si creerebbero al momento dei singoli rilasci in esercizio.
