### ISSUE TITLE
Richiesta chiarimenti su partecipanti AD*

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1112]
Vorremmo sapere se nelle schede di tipo AD, nella sezione aggiudicazioni, partecipanti sia necessario inserire il solo partecipante aggiudicatario oppure vanno inseriti tutti i partecipanti alla procedura. In quest'ultimo caso tuttavia non abbiamo modo di identificare l'aggiudicatario, diversamente da ciò che accade nelle schede di tipo A.

Vorremmo inoltre sapere se per la regola di validazione ERR100 venga considerata la somma degli importi dei partecipanti.

Grazie!

**Comment by anac-uscp** [comment]
<p>Buongiorno,<br>
<br>
Nelle schede in questione va inserito l'aggiudicatario. Qualora l'aggiudicatario sia un Raggruppamento Temporaneo di Imprese (RTI), vanno inseriti tutti i partecipanti al RTI, con l'indicazione del rispettivo ruolo all'interno della RTI.<br>
<br>
 </p>
