### ISSUE TITLE
[Toscana/bolzano] - REG37 - Non è stato indicato il valore relativo alle somme per opzioni e rinnovi

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1113]
Salve,

Abbiamo provato ad effettuare un test in collaudo in cui si voleva confermare l'appalto per la scheda P1.12 (riscontrato però anche in altre schede di pubblicazione), ma ci viene restituito errore:

- REG37 - Non è stato indicato il valore relativo alle somme per opzioni e rinnovi

Nel nostro caso l'appalto è valorizzato in questo modo:
- L’appalto prevede ripetizioni o altre opzioni? = N
-  Somme opzioni e rinnovi = 0

Non ci è chiaro il messaggio di errore. Riuscite a darci un riscontro per capire se stiamo sbagliando qualcosa ?

**Comment by paolo-urbanetto** [comment]
Ci associamo anche noi (Maggioli); abbiamo lo stesso errore.

**Comment by gianlucacuomo** [comment]
Anche noi lo stesso problema. In realtà si risolve inserendo NULL al posto di zero. Ma fino a qualche giorno fa il comportamento era differente e l'intervento comporta dover modificare non solo l'applicativo ma anche le schede già compilate

**Comment by lucaCorigliano-SA** [comment]
Issue correlata: https://github.com/anticorruzione/npa/issues/1092

**Comment by supportoAnac** [comment]
La regola è stata aggiornata. Se si indica _L’appalto prevede ripetizioni o altre opzioni? = N_
si può indicare sia 0 che omettere il campo.
