### ISSUE TITLE
BLK [Maggioli] errore in pubblicazione P2_16 (per conto Comune di Genova)

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1114]
Buongiorno,
nella pubblicazione di una P2_16 otteniamo dalla response il seguente messaggio di errore:
ERR94: [403 Forbidden] during [POST] to [https://testpubblicitalegale.anticorruzione.it/api/v0/pcp/avvisi] [PVLClient#pubblicaAvviso(String,PubblicaAvvisoRequest)]: [{"timestamp":"2024-02-12T14:18:38.402+00:00","status":403,"error":"Forbidden","path":"/api/v0/pcp/avvisi"}]

Stiamo operando in ambiente di test supportando il Comune di Genova che è bloccato nei test ai fini della dichiarazione di conformità della piattaforma (vedi anche issue [1104](https://github.com/anticorruzione/npa/issues/1104)).

Sembra quindi che il vostro servizio abbia problemi di autorizzazione (403) chiamando il vostro servizio PVL in https://testpubblicitalegale.anticorruzione.it/api/v0/pcp/avvisi

Attendiamo riscontro.
Grazie

Riferimenti:
idAppalto=b0af8b41-8d0e-4dd7-ac14-25a4cb85f01f
idAvviso=166287a6-1efd-4486-b027-068aa35f940b

govway-message-id 4f0233c0-1dd5-4e59-9abc-9df4723da5f0
govway-transaction-id 299668e9-c99f-11ee-9b99-0050568e9679"

**Comment by gianlucacuomo** [comment]
Si segnala che un errore simile si è riscontrato anche in esercizio

**Comment by mariottiDPA** [comment]
Ciao a tutti, stesso problema anche per noi, abbiamo tentato la segnalazione via email, speriamo che uno dei due sistemi funzioni 🥲
