### ISSUE TITLE
Richiesta chiarimenti campo "Motivazione CIG"

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1116]
Salve,
sembrerebbe che il campo Motivazione CIG sia sempre obbligatorio mentre nello swagger risulta facoltativo:
<img width="440" alt="image" src="https://github.com/anticorruzione/npa/assets/144692899/6293c514-b8bd-4650-b7fa-4f1180716ce6">

Potete fornire un chiarimento?

**Comment by supportoAnac** [comment]
È stata inserita per errore l’obbligatorietà sulle schede P7_1_1, P7_1_2, P7_1_3 e P7_2; verrà corretta al prossimo rilascio. L’obbligatorietà del campo è condizionata dal valore del campo categorieMerceologiche, come indicato nelle regole REG4_1 e REG4_2.
