### ISSUE TITLE
[Toscana/bolzano] - ERR94: [403 Forbidden] - Errore richiamando il servizio esito-operazione

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1117]
Salve,
mi ricollego alla issues aperta #1114 in quanto stiamo riscontrando la stessa problematica in ambiente di collaudo.
Provando a richiamare il servizio esito-operazione dopo il pubblica avviso, ci viene restituto il seguente errore:

- ERR94: [403 Forbidden] during [POST] to [https://testpubblicitalegale.anticorruzione.it/api/v0/pcp/avvisi] [PVLClient#pubblicaAvviso(String,PubblicaAvvisoRequest)]: [{"timestamp":"2024-02-10T09:40:18.919+00:00","status":403,"error":"Forbidden","path":"/api/v0/pcp/avvisi"}].

Abbiamo notato che c'è una differenza di 1 ora tra la data trasmissione (data sulla nostra piattaforma) e la data restituita nel messaggio di errore.
Il servizio è stato richiamato dalla nostra piattaforma alle 10.40, invece ci viene restituito l'errore con il timestamp: "2024-02-10T09:40:18.919+00:00"

Attendiamo riscontro.

**Comment by supportoAnac** [comment]
La problematica segnalata è stata causata da un disservizio temporaneo nel funzionamento di PVL, che è stato risolto nel pomeriggio di ieri.
