### ISSUE TITLE
Aggiornamento tipologiche #1093

### ISSUE THREAD

**Issue by pb14702** [anticorruzione/npa#1118]
Urgente: Chiediamo risposta urgente su quali siano le categorie eliminate e/o  relativi aggiornamenti. Prego informarci solo sul delta.

**Comment by supportoAnac** [comment]
Si prega di fare riferimento a [a92a33d](https://github.com/anticorruzione/npa/commit/a92a33d9b21365416ae6c666f8009019b96213cf#diff-d7df1bbbd1cad88f7f9141deb4b73f6f1866f6650a8942bf9e582766bbe9f3d1).
