### ISSUE TITLE
Gestione delle informazioni nelle schede

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#112]
Buongiorno,
siamo stati abituati, con la documentazione SIMOG, ad avere informazioni, per ciascun campo presente nella scheda, circa:

1. obbligatorietà, 
2. opzionalità 
3. obbligatorietà condizionata (con indicazione delle condizioni relative)

queste informazione dove possono essere reperite nella documentazione dell'NPA??

Grazie per il supporto 
Francesco

**Comment by supportoAnac** [comment]
Le obbligatorietà sono espresse nei file YAML delle schede. Dove non espresse il campo è opzionale. Le condizioni di obbligatorietà condizionata sono contenute nelle regole rappresentate con il linguaggio DMN, che saranno pubblicate nei prossimi rilasci.
