### ISSUE TITLE
[BLK] ERR63 - "Tipologica Non valida"

### ISSUE THREAD

**Issue by pb14702** [anticorruzione/npa#1120]
Vi chiediamo urgente risposta in merito alla scelta nella tipologica strumentiSvolgimentoProcedure, attualmente non coerente per "Procedure svolte attraverso piattaforme telematiche di negoziazione "

**Comment by lucaCorigliano-SA** [comment]
Nota bene che le tipologiche vanno filtrate in base alla loro dataInizio e dataFine. Nella tua fattispecie concreta "Procedure svolte attraverso piattaforme telematiche di negoziazione" con codice 5 risulta scaduto al 31-12-2023 e quindi non può essere utilizzato.

**Comment by claudiocarotenuto** [comment]
Il problema è che i valori validi non coprono la pletora delle casistiche, per cui si rende necessaria una risposta da ANAC poiché questo impedisce alle SA di creare le schede di indizione ove tale è campo è obbligatorio (es P7_2)

**Comment by anac-uscp** [comment]
<p>Risolta dal Changelog del 12/03/2024</p>
