### ISSUE TITLE
Problematica relativa al campo BT-27 (datiBase.importo)

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1122]
@supportoAnac 

In riferimento all'issue #1086, nelle specifiche dell'eform (SDK 1.9) BT-27 non risulta essere obbligatorio nella compilazione dei notice.  State gestendo un campo facoltativo come obbligatorio? 

Questo potrebbe comportare per il cliente la necessità di compilare l'eform una seconda volta, dopo aver scoperto che il campo che non ha inserito è di fatto obbligatorio per l'ANAC.

**Comment by gfalce** [comment]
Salve, sulla scheda P1_23 (P1_23 - Avviso o bando di concorso di progettazione — direttiva generale, progettazione concorso progettazione - settori ordinari pari /sopra soglia - indipendente dal regime) escono gli errori BT-27 relativi agli importi di appalto e lotto ma sull'eform i campi non sono presenti.
Come è possibile risolvere? Grazie

**Comment by anac-uscp** [comment]
<p>Si conferma l’obbligatorietà del campo BT-27, anche per la scheda P1_23. <br>
Abbiamo preso in carico la segnalazione e sarà reso obbligatorio nelle Schede P1_23 e P1_24 in uno dei prossimi rilasci. </p>
