### ISSUE TITLE
[BLK][Maggioli] P6_1 negoziata con verifica negativa erronea

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1125]
Salve,
per idAppalto: 37d39749-4aaa-44d2-befa-7debe74024ef
dopo aver inviato una scheda P6_1  con procedura Negoziata senza previa indizione di gara, in fase di verifica, anac risponde con il seguente msg:
REG67: il campo giustificazione aggiudicazione diretta è obbligatorio se il tipo di procedura è Negoziata senza previa indizione di gara.

Premesso che il campo con la descrizione suddetta non esiste nello schema, tuttavia guardando nelle regole dmn si evince che si tratta dell'attributo appalto.datiBaseProcedura.giustificazioneProceduraAccelerata che pero' risulta valorizzato nel json trasmesso
["appalto"]  {
"codiceAppalto": "TSO00629-daaf7606-66fd-4778-9b9f-8500f3231f9b",
"cigAccordoQuadro": "0350507F82",
["strumentiSvolgimentoProcedure"]  {
"idTipologica": "strumentiSvolgimentoProcedure",
"codice": "7"
},
"idPianificazione": null,
"termineRidottoAvvisoPreinformazione": true,
["datiBaseProcedura"]  {
["tipoProcedura"]  {
"idTipologica": "tipoProcedura",
"codice": "neg-wo-call"
},
"proceduraAccelerata": true,
"giustificazioneProceduraAccelerata": "concessione in scadenza",
"giustificazioneProceduraAccelerataMl": null
},
["datiBaseStrumentiProcedura"]  {
["accordoQuadro"]  {
"idTipologica": "accordoQuadro",
"codice": "none"
},
"astaElettronica": false
},
["datiBase"]  {
"oggetto": "P6_1 CONCESSIONI-adesione AQ/convenzione con successivo confronto competitivo ",
"oggettoMl": null,
"importo": 4900
}
},

...cosa dobbiamo fare per superare il blocco? 
grazie

**Comment by supportoAnac** [comment]
L'intervento da effettuare per risolvere la anomalia segnalata è stato individuato e la fix sarà rilasciata quanto prima.
