### ISSUE TITLE
Parametro del servizio pubblica-avviso

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#113]
Il parametro per l'esecuzione del pubblica-avviso è l'idAppalto e non l'idAvviso come scritto nella documentazione.
Giusto??

Francesco

![image](https://github.com/anticorruzione/npa/assets/137269683/4e127f23-970e-40bf-823b-49bfbd5986ca)

![image](https://github.com/anticorruzione/npa/assets/137269683/c9b2c02a-8f64-4482-a90f-6941a4fc9455)

**Comment by supportoAnac** [comment]
Il file aggiornato di riferimento delle specifiche per i servizi dell'appalto è lo yaml specifiche-servizi-appalto.yaml. Il servizio /esito-operazione, se previsto, restituisce in risposta anche l'idAvviso.
