### ISSUE TITLE
Numerosità delle Stazioni Appaltanti in un Appalto

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1132]
si richiede se è possibile che il numero delle stazioni appaltanti inserite nel campo complesso "stazioniAppaltanti" può essere superiore a due (che rappresenta il caso di SA "delegante" SA "delegata" ampiamente utilizzato nel sistema).
In caso affermativo si richiede quale sia il ruolo che le stesse possano avere nello svolgimento degli Appalti, oltre quello appena descritto che ne richiede esclusivamente due.
La domanda nasce anche dalla consuetudine in atto presso alcune CUC di raccogliere le richieste di più SA  (SA "deleganti") svolgere una sola gara (SA "delegata") e stipulare più contratti uno per ciascuna SA "delegante" (modalità più volte discussa e che trova come unica risposta nella piattaforma l'indizione di un Appalto di tipo AQ / Convenzione.
Grazie

**Comment by anac-uscp** [comment]
<p>La sezione StazioneAppaltante può accogliere più deleganti per un'unica Titolare (delegata). <br>
<br>
Tuttavia, il subentro automatico nelle comunicazioni fra delegante e delegata ha effetto solo in modalità 1 a 1.</p>

<p>In caso di presenza di più deleganti, il caso ricade nella fattispecie tipica dell' Accordo Quadro.</p>
