### ISSUE TITLE
[BLK][Maggioli] A2_32 Aggiudicazione impossibile in caso di S2 con più partecipanti 

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1134]
Dopo aver inviato una scheda A2_32 ,
preceduta da una scheda S2 dove al suo interno erano presenti più partecipanti (idPartecipante),
compare il seguente errore bloccante
ERR77: il partecipante non è valido per il lotto: idPartecipante: 921d677e-8521-41b6-ae5b-147aeb17d55a - cig: I0015E3729
In realtà nella scheda S2  tale partecipante era presente nel json per quel cig.
Nel json della scheda A2_32 invece per le offerte presentate e' presente il flag aggiudicatario valorizzato a true una volta sola come si puo' vedere qui sotto.
Come si puo' procedere per proseguire nell'iter della scheda? 
Il problema era già stato segnalato nella issue 1039, chiusa a mio avviso troppo frettolosamente.
In alternativa a cosa serve il flag aggiudicatario nelle offerte?

Qui i riferimenti necessari alla verifica:

Id Appalto: c91b7193-7db8-4421-acbe-33f090b97dfb

json S2:

{
["elencoSoggetti"] : [
{
"cig": "I0015E3729",
"invitatiCheNonHannoPresentatoOfferta": null,
["partecipanti"] : [
{
"codiceFiscale": "00954500062",
"denominazione": "ITINERA",
["ruoloOE"] : {
"idTipologica": "ruoloOE",
"codice": "3"
},
["tipoOE"] : {
"idTipologica": "tipoOE",
"codice": "1"
},
"idPartecipante": "921d677e-8521-41b6-ae5b-147aeb17d55a",
"paeseOperatoreEconomico": "IT",
"paeseOperatoreEconomicoMl": null,
"avvalimento": false,
"tipologiaAvvalimento": null
},
{
"codiceFiscale": "93036730013",
"denominazione": "MISCELA",
["ruoloOE"] : {
"idTipologica": "ruoloOE",
"codice": "3"
},
["tipoOE"] : {
"idTipologica": "tipoOE",
"codice": "1"
},
"idPartecipante": "fcd97133-2c4d-4849-8692-f9ec475632ad",
"paeseOperatoreEconomico": "IT",
"paeseOperatoreEconomicoMl": null,
"avvalimento": false,
"tipologiaAvvalimento": null
}
],
"dataInvito": null,
"dataScadenzaPresentazioneOfferta": "2024-03-08T12:00:00Z"
}
]
}

offerte presentate nel json A2_32

"offertePresentate": [
{
"idPartecipante": "921d677e-8521-41b6-ae5b-147aeb17d55a",
"importo": 4775.74002,
"aggiudicatario": true,
"ccnl": "ATY1",
"posizioneGraduatoria": 1,
"offertaEconomica": 2.34,
"offertaQualitativa": null,
"offertaInAumento": null,
"offertaMaggioreSogliaAnomalia": null,
"impresaEsclusaAutomaticamente": false,
"offertaAnomala": false
},
{
"idPartecipante": "fcd97133-2c4d-4849-8692-f9ec475632ad",
"importo": 4807.03711,
"aggiudicatario": false,
"ccnl": "BTY2",
"posizioneGraduatoria": null,
"offertaEconomica": 1.7,
"offertaQualitativa": null,
"offertaInAumento": null,
"offertaMaggioreSogliaAnomalia": null,
"impresaEsclusaAutomaticamente": false,
"offertaAnomala": false
}
],

IdScheda: caba8831-833c-4328-9c74-a1455e89f464
ERR77: il partecipante non è valido per il lotto: idPartecipante: 921d677e-8521-41b6-ae5b-147aeb17d55a - cig: I0015E3729
Data evento: 15/02/2024 08:48:12
Govway Transaction Id: f5d4a0d3-cbd1-11ee-9ec6-0050568e08b3

**Comment by supportoAnac** [comment]
Segnalazione in corso di verifica.

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 12/03/2024.

**Comment by matteolaltrelli** [comment]
L'anomalia non sembra essere risolta.
Abbiamo una stazione appaltante bloccata in produzione con questo errore:
ID Appalto: ab908971-7e01-493d-9dfe-07ed777a5d47
Scheda S2 inviata e confermata: 14391470-4765-45f5-81d4-253e8b5d7cce con i seguenti id_partecipanti:

8bdb2b92-a4f0-593d-a10f-875421dac34c
db411cd5-abc3-5dbf-a176-c9bb869ec496
95b9269c-4414-5dbc-a536-9e786b0fc7b5

In creazione scheda otteniamo il seguente errore:
CODICE: ERR77
DESCRIZIONE ERRORE: il partecipante non è valido per il lotto
idPartecipante: 8bdb2b92-a4f0-593d-a10f-875421dac34c - cig: XXXXXXX

"govway_message_id": "8e3e9e18-4f00-4898-8bc2-5d60a0e0ac2a",
"govway_transaction_id": "ad643d52-ec15-11ee-852e-005056844885",

Attendiamo urgentemente un riscontro

**Comment by laurapavan** [comment]
anche noi abbiamo diverse situazioni di questo tipo in produzione....aperti ticket ma nessuna risposta. Nel nostro caso pare si verifichi quando la S2 è stata fatta prima l'aggiornamento dello scorso 12/03, mentre la A* dopo l'aggiornamento.
