### ISSUE TITLE
[ARIA SPA] eFORMS - E16 - Pubblicazione di una procedura RISTRETTA e problema versione SDK

### ISSUE THREAD

**Issue by AnrivaDeloitte** [anticorruzione/npa#1137]
Riporto l'errore riscontrato da ANAC sul formulario E16 sottomesso per una procedura ristretta:

**"codice":"REG96",
    "descrizione": {
"it": "E' obbligatorio inserire almeno uno dei due campi tra oraScadenzaPresentazioneOfferte e scadenzaPresentazioneInvito. In presenza di eForm verificare i campi EndDate (BT-131, BT-1311, BT-630)."**

Abbiamo importato il file xml  in eNotice e alla convalida non si riscontrano errori.
Abbiamo verificato che è stata inserita la data relativa al campo BT-1311 + ora - Termine per il ricevimento delle domande di partecipazione (BT-1311(d)-Lot)
Tale dato sembra in alternativa alla data BT-131 +ora - Termine per il ricevimento delle offerte (BT-131(d)-Lot).
Il campo **BT-630** NON è stato valorizzato in quanto NON presente su TED per la versione SDK 1.9.0

Infatti, il campo **BT-630** risulta essere riferito alla versione SDK 1.10.0. ANAC aveva però dichiarato di basarsi sulla versione SDK 1.9.0 fino ad ottobre 2024.

Come è possibile risolvere il problema?

**Comment by mcgirone** [comment]
Anche noi abbiamo avuto lo stesso problema in merito ad una P1_16 ristretta con eForm CN-16.

**Comment by matteolaltrelli** [comment]
Indipendentemente dal problema riscontrato, però sembra che il campo BT-630 sia presente nell'SDK già dalla versione 1.9.0 nel file fields.json (riga 26756 e riga 26807)

**Comment by AnrivaDeloitte** [comment]
Il campo BT-630 è però indicato come "always FORBIDDEN in notice sub-type 16". Infatti, in eNotice2 NON è presente con la versione SDK 1.9.0

**Comment by supportoAnac** [comment]
Si chiede gentilmente di indicare l’ID appalto, così da potere verificare l’eForm inviato e fare un test con gli stessi dati.

**Comment by AnrivaDeloitte** [comment]
[ARIA_test ristretta_errore_REG96.zip](https://github.com/anticorruzione/npa/files/14512617/ARIA_test.ristretta_errore_REG96.zip)
Buonasera,

alleghiamo il file .zip contenente E16 ed anacform P1_16 in quanto, a causa dell'errore **REG96**, non era appunto stato possibile generare l'appalto.

**Comment by supportoAnac** [comment]
Salve, la segnalazione ha evidenziato un’anomalia software per cui il BT-1311 arrivava vuoto in validazione e faceva scattare la regola. La fix è stata rilasciata in qualificazione ed esercizio in data 12 Marzo.
Sono stati fatti ulteriori test in ambiente di qualificazione e l’errore risulta risolto, i.e. la regola non scatta.
