### ISSUE TITLE
Richiesta inserimento “attributi certificati” per verifica del possesso effettuata automaticamente da PDND Interoperabilità-PAGO PA

### ISSUE THREAD

**Issue by Bettascorpio** [anticorruzione/npa#1140]
Per poter effettuare l’integrazione con PCP – FVA, la piattaforma PNDN Interoperabiltà di PAGO P.A. prevede degli Attributi Certificati - Ovvero attributi certificati da una fonte autoritativa riconosciuta, che classifichi l’ente come “Gestore che ha sottomesso una richiesta di certificazione per una o più componenti con accesso all'ambiente di qualificazione” (Id dell'attributo (attributeId) a0e480a0-252e-46d1-baaa-25bac81227bd)
Per gli Attributi Certificati, alla specifica “fonte autoritativa riconosciuta” il manuale operativo di PDND (https://docs.pagopa.it/interoperabilita-1/manuale-operativo/attributi) cita testualmente:
Per le pubbliche amministrazioni e i gestori di pubblici servizi gli attributi certificati vengono attribuiti automaticamente all'aderente in base alle informazioni presenti nei database delle fonti autoritative a disposizione di PDND Interoperabilità. In questo momento l'unica fonte presente è il catalogo IPA. La verifica del possesso di questi attributi da parte del fruitore viene effettuata automaticamente da PDND Interoperabilità e non è suscettibile di correttivi da parte di PagoPA. Se il fruitore ritiene che IPA gli abbia erroneamente non riconosciuto un attributo, dovrà contattare autonomamente il gestore del servizio per richiedere una modifica.
Abbiamo richiesto ad IPA, ma ci hanno risposto di non conoscere le info richieste da PagoPa, e ci hanno consigliamo di rivolgerci a PagoPa, che a sua volta a fornito come risposta che l'ente erogatore per gli e-services risulta essere ANAC, a cui dobbiamo rivolgerci per la risoluzione delle problematiche; ci hanno consigliamo di aprire un issue su Github.
Con la presente siamo quindi a richiedere come poter procedere con il processo di integrazione e quindi concludere la qualificazione della piattaforma, che risulta ad ora bloccato.

**Comment by obigno77** [comment]
Issue aperta da troppo tempo. Si prega di rivolgere il quesito alla casella supporto.pdnd@anticorruzione.it laddove ancora necessario supporto
