### ISSUE TITLE
Rettifiche (ancora) bloccate in "WT"

### ISSUE THREAD

**Issue by lucaCorigliano-SA** [anticorruzione/npa#1141]
Odio aprire issue duplicate ma questo ticket è vecchio di due settimane: https://github.com/anticorruzione/npa/issues/1077

Risulta impossibile testare le rettifiche se l'iter non viene mai completato in collaudo.

**Comment by supportoAnac** [comment]
Sono in corso adeguamenti sul servizio di rettifica per risolvere questa problematica, la modifica verrà rilasciata quanto prima.
