### ISSUE TITLE
[BLK][Produzione] Stazione appaltante bloccata per response vuote - Impossibile creare schede

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1142]
In ambiente di esercizio un cliente ha problemi relativamente all'invio delle schede di creazione-appalto, in particolare qualunque invio questi effettui dall'ANAC non viene inviato alcun dato nella response.

Da controlli effettuati con la SA abbiamo potuto verificare che non vi sono dati generati su PCP, differentemente per quanto è già avvenuto con altre SA dove in corrispondenza di una response vuota veniva comunque generata la scheda (vedi per esempio issue #1054).

A titolo non esaustivo si inviano gli identificativi govway di 2 schede:

## P7_2

| key | value |
| --- | --- | 
| govway-message-id | `d2af0e2f-f4b5-465d-898b-ed861c441e49` | 
| govway-transaction-id | `d15a55d3-ccb1-11ee-852e-005056844885` | 

## P7_1_3

| key | value |
| --- | --- | 
| govway-message-id | `4c73d6d2-72aa-4835-b169-979b1eb588e0` | 
| govway-transaction-id | `1d3a17f1-c517-11ee-852e-005056844885` |

**Comment by supportoAnac** [comment]
Salve, si ricorda che le anomalie per le piattaforme di produzione sono gestite sul canale dedicato, su cui riceverà riscontro per la problematica segnalata.
