### ISSUE TITLE
[BLK] - ERR2 invio Scheda S1 dopo scheda P7_1_3

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1143]
Salve,
Dopo aver pubblicato la scheda P7_1_3, abbiamo inviato la S1 cosi come da flusso indicato nell'orchestratore:
<img width="882" alt="image" src="https://github.com/anticorruzione/npa/assets/144692899/ba96bcb5-1b7a-47f7-b5eb-50e1bb8702fe">

Tuttavia, riscontriamo il seguente errore :

**ERR2 - scheda non ammessa in questa fase dell'appalto: La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata**

In allegato i due json con i relativi dati.

[S1-crea_scheda.json](https://github.com/anticorruzione/npa/files/14311972/S1-crea_scheda.json)
[P7_1_3-crea_appalto.json](https://github.com/anticorruzione/npa/files/14311973/P7_1_3-crea_appalto.json)

**Comment by supportoAnac** [comment]
Per l’appalto indicato ci sono già le schede S1 e S2 confermate. Pertanto, l’errore segnalato è corretto.
