### ISSUE TITLE
[BLK] - REG67 per scheda P3_1

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1144]
Salve,
viene restituito "Appalto non confermato" per una negoziata senza bando a causa dell'errore REG67:

 <description>REG67: il campo giustificazione aggiudicazione diretta è obbligatorio se il tipo di procedura è Negoziata senza previa indizione di gara</description>

Nonostante il campo in questione sia stato correttamente popolato, tra i dati richiesti nell'ANACFORMP3_1Type, non esiste questo campo.

Si richiede riscontro.

**Comment by laurapavan** [comment]
Abbiamo rilevato lo stesso problema.

**Comment by lucaCorigliano-SA** [comment]
Questo è il codice DMN/Feel che va a verificare questa regola:
```
appalto.datiBaseProcedura != null and appalto.datiBaseProcedura.tipoProcedura != null and appalto.datiBaseProcedura.tipoProcedura.codice = \"neg-wo-call\" and (appalto.datiBaseProcedura.giustificazioneProceduraAccelerata = null or appalto.datiBaseProcedura.giustificazioneProceduraAccelerata=\"\")
```

Potete verificare in autonomia la logica di (alcune) regole usando i file DMN presenti in repository.

**Comment by supportoAnac** [comment]
Segnalazione corretta; la regola è stata inserita per errore. Verrà eliminata al prossimo rilascio
.
