### ISSUE TITLE
[BLK][Maggioli] interpretazione REG13: L’appalto prevede ripetizioni di servizi/forniture/lavori analoghi e consegne complementari?

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1145]
Salve,
alla verifica di una scheda P1_17 compare l'errore bloccante seguente

REG13: L’appalto prevede ripetizioni di servizi/forniture/lavori analoghi e consegne complementari? se sì deve essere valorizzato a sì anche il campo 'L'appalto prevede opzioni/rinnovi?'

dove nel json abbiamo inviato questi valori:
....
"ripetizioniEConsegneComplementari": true,
"opzioniRinnovi": false,
....
"sommeOpzioniRinnovi": null,
"sommeRipetizioni": 112.33,
....

Ne scaturisce quindi il dubbio:
le ripetizioni sono incluse nelle somme Opzioni Rinnovi?
alternativamente perche',valorizzando le  ripetizioni, occorre valorizzare il flag 'L'appalto prevede opzioni/rinnovi?' a true? (oltretutto poi, in questo caso, non accetta il valore 0 o nullo per sommeOpzioniRinnovi ).

Non sappiamo come comportarci , potreste darci una risposta esauriente?

Facciamo presente inoltre che i campi importi relativi a opzioni e rinnovi sono presenti in molte schede,
fino ad oggi  siamo stati costretti a precedere per tentativi mettendo i campi importo a volte a zero a volte nulli.

grazie

**Comment by supportoAnac** [comment]
La segnalazione è stata verificata e la regola verrà eliminata.
