### ISSUE TITLE
Scheda S3 - ERR9999 - errore generico

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1146]
Salve, 

Stiamo riscontrando ERR9999 - errore generico all'invio della scheda S3 in cui vengono compilati tutti i campi anche quelli facoltativi.

[P2_16.json](https://github.com/anticorruzione/npa/files/14345288/P2_16.json)
[S3.json](https://github.com/anticorruzione/npa/files/14345291/S3.json)

Riuscite a darci un riscontro?

**Comment by supportoAnac** [comment]
Sono ammesse le seguenti schede come successive alla P2_16: S2,S2 e NAG ; non è corretto mandare la S3. 
Si prega di fare riferimento al file dell’orchestratore: https://github.com/anticorruzione/npa/blob/main/docs/orchestratore/schema-cronologia-schede.xlsx
