### ISSUE TITLE
Assenza del campo datiBaseStrumentiProcedura nelle schede di tipo P7_x_x

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1147]
INTERCENTER
A seguito di approfondimenti sulla gestione dei CIG derivati, si è assunto che la gara "madre" dovrebbe avere:

1. il campo BT-765 valorizzato opportunamente nell'eForm relativo per gli Appalti che lo prevedono
2. Il campo accordoQuadro nel campo complesso datiBaseStrumentiProcedura per gli Appalti senza eForm.

La prassi prevede che spesso Appalti specifici (discendenti da SDA) prevedano l'operatività tramite convenzioni/accordi quadro. Per questi le schede utilizzate sono le P7_x_x che sono sprovviste del campo datiBaseStrumentiProcedura.
Si richiede se quanto esposto corrisponde alla interpretazione corretta dei processi e, in caso positivo, se è necessario aggiungere il campo datiBaseStrumentiProcedura alle schede di tipo P7_x_x.

**Comment by anac-uscp** [comment]
<p>I bandi esecutivi degli SDA devono essere trasmessi attraverso la scheda P7_2.<br>
Nella P7_2 il campo accordoQuadro è presente nel campo complesso datiBaseStrumentiProcedura per gli Appalti.<br>
Nella stessa scheda, a livello di lotto, è necessario valorizzare il campo ‘condizione negoziata’ specificando la voce ‘appalto specifico nel Sistema Dinamico di Acquisizione’ quando questo discende da uno SDA. </p>

<p> </p>
