### ISSUE TITLE
[BLK] [Maggioli] Errore in conferma scheda (nuovo ambiente test pubblicita legale)

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1148]
Salve ,
invocando i ws per verificare la conferma scheda , nello specifico una scheda A2_32
ottengo il seguente errore bloccante:
{
    "codice":"ERR94",
    "descrizione": {
		"it": "errore generico durante la comunicazione con PVL",
		"en": "errore generico durante la comunicazione con PVL"
	},
    "dataInizio":null,
    "dataFine":null
},

che sembra derivare dalla presenza di un nuovo ambiente di test per la pubblicità legale

"[502 Bad Gateway] during [POST] to [https://testpubblicitalegale.anticorruzione.it/api/v0/pcp/avvisi] [PVLClient#pubblicaAvviso(String,PubblicaAvvisoRequest)]: [<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>
]"

Data evento: 19/02/2024 10:19:28
Govway Transaction Id: 42a93c25-cf04-11ee-9b99-0050568e9679

Come possiamo procedere? abbiamo una certa urgenza,grazie

**Comment by supportoAnac** [comment]
L’errore è dovuto alla temporanea indisponibilità del sistema di test di Pubblicità a Valore Legale. Si raccomanda di riprovare e, qualora il problema si ripresentasse, di aprire una nuova segnalazione con le indicazioni dell’idAppalto di riferimento.
