### ISSUE TITLE
Quesiti su comunicaAppalto

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#115]
Buongiorno,
avrei bisogno di alcune conferme utili all'impostazione della piattaforma degli approvigianamenti e dei punti di innesco delle chiamate a NPA. Dalla documentazione desumo che:

1. I CIG relativi ai Lotti di una Gara sono disponibili solo alla conferma di tutti i dati dell'appalto con il servizio conferma-appalto
2. La pubblicazione su TED e PPL può avvenire solo alla conferma dell'Appalto e, quindi, dopo il perfezionamento dello stesso.

Non ho compreso bene il flusso oppure è così. Nel caso le due affermazioni siano vere, dobbiamo modificare radicalmente la piattaforma poichè:

1. I CIG venivano presi prima della pubblicazione e trascritti negli atti di Gara
2. La pubblicazione della Gara (perfezionamento dei CIG) poteva avvenire solo dopo aver ricevuto "protocollo" e data di ricezione della richiesta di pubblicazione al TED.

Grazie per l'aiuto che spero sia sollecito poichè, nel caso vengano confermate le mie riflessioni, dobbiamo procedere ad una radicale ristrutturazione sia tecnica sia organizzativa della piattaforma.

Grazie

Francesco

**Comment by supportoAnac** [comment]
Si rimanda alle seguenti Issues: 
https://github.com/anticorruzione/npa/issues/3
https://github.com/anticorruzione/npa/issues/20
https://github.com/anticorruzione/npa/issues/27
https://github.com/anticorruzione/npa/issues/137

**Comment by OperatoreIT** [comment]
<p>Gentile Utente, </p>

<p data-end="353" data-start="91">a seguito di una verifica condotta a sistema, si evince che la problematica riscontrata — per la quale non risulta visibile il fascicolo SOA nella sezione “I miei contratti” — è riconducibile a un’errata compilazione della richiesta di creazione del fascicolo.</p>

<p data-end="481" data-start="355">In particolare, nel campo <code data-end="393" data-start="381">SOA.codice</code> è stato inserito un codice fiscale anziché il codice identificativo corretto della SOA.</p>

<p data-end="760" data-start="483">A causa di tale incongruenza, il fascicolo non viene visualizzato correttamente.<br data-end="566" data-start="563">
Sarà pertanto necessario procedere con la creazione di una nuova attestazione SOA, assicurandosi di inserire i dati corretti nei relativi campi, al fine di ottenere una corretta visualizzazione.</p>

<p data-end="788" data-start="762">Restiamo a disposizione.</p>

<p><br>
Cordiali Saluti </p>
