### ISSUE TITLE
[BLK][Maggioli] Impossibile inviare scheda NAG dopo conferma scheda S3

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1152]
Salve,
nell'orchestratore , in corrispondenza della scheda 'S3' e' presente l'asterisco nella colonna schedaSuccessiva: si evince pertanto che a seguito della scheda S3 e' possibile fare una scheda NAG.
Ma ,contrariamente a quanto indicato dall'orchestratore, dopo aver confermato la scheda S3, non è possibile procedere con la scheda NAG. Compare il msg 'Scheda non ammessa in questa fase dell'appalto'.

Data evento 20/02/2024
Govway Transaction Id: 3db397a7-cfc9-11ee-9b99-0050568e9679

Come possiamo procedere? grazie

**Comment by supportoAnac** [comment]
Sono in corso verifiche sulle schede ammesse come successive a S3.
