### ISSUE TITLE
[Toscana/Bolzano] -Invio di più aggiudicazione sullo stesso lotto

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1154]
Salve

in riferimento alla #938 
chiedo conferma che per uno stesso lotto in cui è già stata inviata la scheda di aggiudicazione, non è possibile inviarne una nuova aggiudicazione?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Una volta inviata la scheda di aggiudicazione per un determinato lotto, non è possibile trasmettere una nuova scheda di aggiudicazione per lo stesso lotto.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>

<p> </p>
