### ISSUE TITLE
[Toscana/bolzano] - ER77: Il partecipante non è valido per il lotto

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1156]
salve,
Stiamo riscontrando "ER77: Il partecipante non è valido per il lotto" all'invio della scheda di aggiudicazione A2_30.

- [A2_30.json](https://github.com/anticorruzione/npa/files/14343390/A2_30.json)
- [S2.json](https://github.com/anticorruzione/npa/files/14343396/S2.json)

Consultando i json inviati, l’idPartecipante relativo all’aggiudicatario nella scheda di aggiudicazione combacia con quello presente tra i partecipanti inviati con la scheda S2, quindi lato nostro sembra che i dati che stiamo mandando siano corretti.
Potete darci supporto?

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 12/03/2024.

**Comment by matteolaltrelli** [comment]
L'anomalia non sembra essere risolta.
Abbiamo una stazione appaltante bloccata in produzione con questo errore:
ID Appalto: ab908971-7e01-493d-9dfe-07ed777a5d47
Scheda S2 inviata e confermata: 14391470-4765-45f5-81d4-253e8b5d7cce con i seguenti id_partecipanti:

8bdb2b92-a4f0-593d-a10f-875421dac34c
db411cd5-abc3-5dbf-a176-c9bb869ec496
95b9269c-4414-5dbc-a536-9e786b0fc7b5

In creazione scheda otteniamo il seguente errore:
CODICE: ERR77
DESCRIZIONE ERRORE: il partecipante non è valido per il lotto
idPartecipante: 8bdb2b92-a4f0-593d-a10f-875421dac34c - cig: XXXXXXX

"govway_message_id": "8e3e9e18-4f00-4898-8bc2-5d60a0e0ac2a",
"govway_transaction_id": "ad643d52-ec15-11ee-852e-005056844885",

Attendiamo urgentemente un riscontro
