### ISSUE TITLE
[Toscana/bolzano] - S3 - "ERR2 - scheda non ammessa in questa fase dell'appalto” 

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1157]
Salve,
apriamo una nuova issues in riferimento alla #1109 poichè riscontriamo lo stesso errore per una S3 dopo AD3:

di seguito inserisco l’id appalto e il json input chiesti:

084275D4-4D38-4173-97BB-A0B1C1964558

{"idAppalto":"084275d4-4d38-4173-97bb-a0b1c1964558","scheda":{"codice":{"idTipologica":"codiceScheda","codice":"S3"},"versione":"1.0","body":{"anacForm":{"elencoIncarichi":[{"cig":"I001AD7D8A"}]}}}}

**Comment by anac-uscp** [comment]
<p>Va chiarito che per le concessioni – in generale – non è ammesso l’affidamento diretto.</p>

<p>Nell’orchestratore sono state previste le schede per le aggiudicazioni senza pubblicazione del bando (sia sopra che sotto soglia con o senza pubblicazione nel TED), nello specifico le schede AD1_28 e AD2_28 le quali, nate per quei casi in cui  c’è sostanzialmente un solo operatore possibile, possono essere utilizzate anche nel caso di normative speciali che consentono l’affidamento diretto di concessioni. <br>
Le schede saranno integrate con l’inserimento del campo che identifica la deroga (il presupposto normativo) e l’orchestratore sarà conseguentemente aggiornato</p>
