### ISSUE TITLE
Schede Pianificazione con pubblicazione avviso

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#1159]
Il servizio di conferma-piano, qualora il tipo di scheda lo consente, avvia la fase di pubblicazione dell'avviso. Chiedo quali sono le schede di pianificazione (area A_1) che prevedono la pubblicazione di un avviso e in che modo è possibile intercettare questa specifica?

Grazie

**Comment by supportoAnac** [comment]
Si prega di fare riferimento al file dell'Orchestratore: https://github.com/anticorruzione/npa/blob/main/docs/orchestratore/schema-cronologia-schede.xlsx ; in particolare alle colonne J (pubblicazione TED) e N (pubblicazione Nazionale).

**Comment by ffinpaa** [comment]
Posso avere un chiarimento rispetto alla valorizzazione di tali colonne rispetto alla restituzione di un idavviso? In particolare, se le schede PL1_17 e PL2_7 (avvisi di preinformazione utilizzati per abbreviare i termini per la ricezione delle offerte) dovessero portare alla generazione di un idavviso, chiedo se tale idavviso sia distinto o meno rispetto all'id avviso generato dalle successive procedure di gara pubblicate con le schede P1_16 e P2_16.

Grazie
