### ISSUE TITLE
Errori specifiche-servizi-appalto

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#116]
Segnalo errori nella definizione delle specifiche https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/specifiche-servizi-appalto.yaml

Dato il numero di schema sarebbe necessario definire i tipi in modo tale da generare i modelli tramite l'openapi.
Colgo inoltre l'occasione per domandare se gli schema (che attualmente sono intorno ai 500) verranno validati con degli strict sulle property aggiuntive. Per intenderci ci sono molti schema che si differenziano per l'assenza o presenza di campi. Con politiche restrittive sulle additional property si costringe la gestione di tutti e 500 le casistiche diverse. Nel caso invece non venga utilizzata una politica restrittiva di questo tipo si possono intraprendere strade diverse, sicuramente più efficienti.

- property lotIdentifier type non definito #/components/schemas/CigType [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml)
- property importo type non definito #/components/schemas/DatiBaseAppaltoP2.12Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseAppaltoP2.13Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseAppaltoP2.14Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseAppaltoP2.20Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseAppaltoP2.21Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseAppaltoP2.23Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseAppaltoP2.24Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseAppaltoP3.5Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseAppaltoP4.1Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseAppaltoType [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseLottoP2.12Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseLottoP2.13Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseLottoP2.14Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseLottoP2.20Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseLottoP2.21Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseLottoP2.23Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseLottoP2.24Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseLottoP3.5Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseLottoP4.1Type [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property importo type non definito #/components/schemas/DatiBaseLottoType [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml)
- property idPianificazione type non definito #/components/schemas/DatiPianoType [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml)
- property lotIdentifier type non definito #/components/schemas/LottoType [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml)
- property dataControllo type non definito #/components/schemas/StatoAppaltoType [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml)
- property dataControllo type non definito #/components/schemas/StatoAvvisoType [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml)
- property dataControllo type non definito #/components/schemas/StatoContrattoType [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml)
- property dataControllo type non definito #/components/schemas/StatoLottoType [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml)
- property descrizione type non definito #/components/schemas/TipologicaBaseType [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml)
- property descrizione type non definito #/components/schemas/TipologicaType [link](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml)

**Comment by mladuDPA** [comment]
Chiudo dopo apertura https://github.com/anticorruzione/npa/issues/134

**Comment by OperatoreIT** [comment]
<p>Gentile Utente, </p>

<p data-end="353" data-start="91">a seguito di una verifica condotta a sistema, si evince che la problematica riscontrata — per la quale non risulta visibile il fascicolo SOA nella sezione “I miei contratti” — è riconducibile a un’errata compilazione della richiesta di creazione del fascicolo.</p>

<p data-end="481" data-start="355">In particolare, nel campo <code data-end="393" data-start="381">SOA.codice</code> è stato inserito un codice fiscale anziché il codice identificativo corretto della SOA.</p>

<p data-end="760" data-start="483">A causa di tale incongruenza, il fascicolo non viene visualizzato correttamente.<br data-end="566" data-start="563">
Sarà pertanto necessario procedere con la creazione di una nuova attestazione SOA, assicurandosi di inserire i dati corretti nei relativi campi, al fine di ottenere una corretta visualizzazione.</p>

<p data-end="788" data-start="762">Restiamo a disposizione.</p>

<p><br>
Cordiali Saluti <br>
 </p>
