### ISSUE TITLE
P7_2 bloccata in fase succesive 

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#1161]
Buongiorno 

Abbiamo creato e confermato la scheda P7_2 con ID_appalto: 28baff4d-8dc5-41dc-a38f-9dc835898752. Tuttavia, abbiamo riscontrato un problema durante il tentativo di inviare la scheda S2, poiché il sistema ANAC restituisce un errore con codice 2 e goway_ID: 7c833e97-cfff-11ee-9b99-0050568e9679.

Abbiamo anche provato a cancellare l'appalto, ma il tentativo è risultato infruttuoso. sempre errore 2  ,  impossibile cancellare l'appalto in questa fase. 
Inoltre, non siamo in grado di procedere con la cancellazione dell'avviso poiché il sistema PCP_NPA non restituisce alcun avviso per questa scheda.

Aggiungo che il flusso 72 non è completo per quanto riguarda le schede di cronologia.

Abbiamo già aperto un ticket di supporto presso il PCP per una situazione simile in ambiente di produzione, ma non abbiamo ancora ricevuto alcun riscontro. Di conseguenza, abbiamo ripetuto il processo di gara sull'ambiente di collaudo al fine di registrare un nuovo ticket.

Resto in attesa di un riscontro e di eventuali istruzioni su come procedere.

Saluti

**Comment by supportoAnac** [comment]
Tramite un controllo basato sulla ID Appalto è stato verificato  che la scheda S2  è pervenuta al sistema PCP senza indicazione dei partecipanti, questa è verosimilmente la causa della anomalia(flusso non completo).  L’appalto risulta concluso con una NAG.
