### ISSUE TITLE
[ARIA] BLK - ERR 9999 per scheda S2

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1162]
Buongiorno,

in ambiente di produzione, all'invio della scheda S2 si riscontra l'errore generico ERR 9999 che non permette l'invio della scheda. Dato che l'invio della scheda S2 è propedeutico all'accesso al FVOE 2.0 da parte della SA per verificare i requisiti e procedere con gli atti formali per l'aggiudicazione risulta **urgente risolvere l'errrore riscontrato**.

L'appalto per cui si è provato ad inviare la scheda S2 è: IdAppalto: 2d9903d7-b6aa-4202-8db5-9ca6fbdfa2ae. 
Il tentativo di invio è stato fatto oggi 21/02/2024 dall'utente intorno alle 10.

in attesa di celere riscontro
grazie

**Comment by mpizziconi** [comment]
le anomalie per le piattaforme di produzione sono gestite sul canale dedicato
