### ISSUE TITLE
[BLK] Conferma appalto errore REG67 - scheda P2_16 - pianificazione rilascio fix

### ISSUE THREAD

**Issue by collaudo5** [anticorruzione/npa#1164]
Ciao, 

in relazione a quanto riferito nella issue https://github.com/anticorruzione/npa/issues/1144 è possibile sapere se la fix verrà rilasciata con le attività previste per il 1 Marzo o se verrà rilasciata prima ?  

In produzione abbiamo gare bloccate a causa di questo errore.

es idappalto: f7c498c3-9dcf-4a91-b7da-64cf8d889a3d

Grazie.

**Comment by supportoAnac** [comment]
Nel caso specifico di questo appalto, il controllo è scattato correttamente in quanto nella scheda è stata indicata una procedura negoziata,  ma da database risulta che non è stato valorizzato a true il campo boolean proceduraAccelerata.
