### ISSUE TITLE
Tipologiche - data inizio e data fine

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#1165]
Per valutare se il valore di una tipologica è valido con che data della gara dobbiamo confrontarla:
data creazione gara? data pubblicazione gara?
data pubblicazione cig? 
In che scheda si può recuperare?

**Comment by supportoAnac** [comment]
dataInizio e dataFine delimitano il periodo di validità della tipologica, è importante che la tipologica sia attiva(valida)  nel momento in cui vengono utilizzati i servizi di creazione e modifica.
