### ISSUE TITLE
[Toscana/bolzano] - (A2_29) restituisce l’errore: ERR2 - scheda non ammessa in questa fase dell'appalto: La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata.

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1167]
salve,

stiamo riscontrando errore per l'invio di una scheda aggiudicazione (A2_29) la quale restituisce l’errore: 
- ERR2 - scheda non ammessa in questa fase dell'appalto: La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata.

Le schede inviate sono le seguenti:

[P2_16 (1).json](https://github.com/anticorruzione/npa/files/14371993/P2_16.1.json)
[S2 (2).json](https://github.com/anticorruzione/npa/files/14371994/S2.2.json)
[A2_29.json](https://github.com/anticorruzione/npa/files/14371995/A2_29.json)

Ci potete dare supporto?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>a seguito delle varie fix rilasciate, controllando sui nostri sistemi, risulta che la scheda A2_29 é stata correttamente creata e confermata in data 11/04/2024.<br>
<br>
Restiamo a disposzione.</p>

<p>Cordiali saluti<br>
<br>
 </p>
