### ISSUE TITLE
Affidamento diretto sopra 40.000€ e sotto 140.000€

### ISSUE THREAD

**Issue by d3mi2023** [anticorruzione/npa#1171]
La semplificazione nella verifica dei requisiti dell’art.52 del d.lgs 36/2023 permette la verifica dei requisiti dopo l’aggiudicazione anche a campione per gli affidamenti diretti sotto i 40000€ . Per gli affidamenti diretti sopra i 40000€ e sotto le soglie comunitarie vale invece l’art. 17 comma 5 del d.lgs 36/2023 per cui l’aggiudicazione è successiva alla verifica dei requisiti. Si chiede a questo punto, per un affidamento diretto sopra i 40k€ e sotto le soglie comunitarie (art 50 comma 1 lettera b) ad esempio sotto i 140000€, tramite una scheda AD3, come si possano verificare i requisiti dell’oe prima di aver ottenuto il CIG, ovvero comunicato con PCP l’indizione della procedura? Tale scheda AD3 richiede per essere trasmessa la data e l’importo di aggiudicazione che sono successivi alla FASE di verifica dei requisiti e che invece nella scheda AD3 vengono richiesti prima di tale FASE . Come è possibile?
In attesa di cortese riscontro
Cordiali saluti

**Comment by d3mi2023** [comment]
Ovviamente mi riferisco come da titolo ad una scheda AD3 per un affidamento diretto sopra i 40k€ e sotto le soglie comunitarie: art 50 comma 1 lettera b)

**Comment by anac-uscp** [comment]
<p>A breve sarà rilasciata una nuova scheda SIM (scheda S per l'Indagine di Mercato/Manifestazione di interesse) da usare a monte di tutte le tipologie di affidamento diretto/negoziate, opzionale, che prevede anche una scheda di terminazione qualora i controlli abbiano esito negativo e non si pervenga all'affidamento o si decida di non proseguire nelle procedure di affidamento (STEV - Scheda di terminazione delle verifiche FVOE).<br>
<strong>La SIM non porta all'identificazione di alcun OE aggiudicatario.</strong></p>

<p>La scheda SIM ha lo stesso contenuto della scheda S1 ad eccezione del campo CIG e non attribuisce CIG.</p>

<p>In linea generale, la SA che vuole attivare l’FVOE invia la nuova scheda SIM (Scheda per l’indagine di mercato senza attribuzione del CIG), con l’anagrafica di uno o più OE individuati o che hanno risposto alla manifestazione di interesse. Successivamente ai controlli, provvede all’invio della scheda AD1, AD2, AD3, AD5 per l'affidamento diretto o la scheda P7_2 per la negoziata senza bando, con le informazioni già presenti ed ottiene il CIG.</p>

<p>La SIM potrebbe dare avvio ad un nuovo flusso. Le schede che possono seguire la SIM sono: AD1_29, AD1_30, AD1_31, AD1_32, AD2_29, AD2_30, AD2_31, AD2_32 AD3, AD5, P7_2.</p>

<p>La SA che non intende attivare l’FVOE, in sede di indagine di mercato, per i controlli esplorativi, invia direttamente una scheda AD1, AD2, AD3, AD5 o P7_2 ed ottiene il CIG.</p>
