### ISSUE TITLE
Procedura ristretta

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#1172]
Quale tipologia di scheda che deve essere inviata in BDNCP in fase di indizione di una procedura ristretta sotto o sopra soglia. Ulteriormente, si richiede in quale fase deve essere inviata la scheda S_1 relativa all'elenco delle ditte ammesse e invitate alla seconda fase.

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;">Per l’indizione del bando vanno utilizzate le schede delle famiglie P1 (per l'invio al TED) e P2 (senza l'invio al TED): la specifica scheda va scelta a seconda delle condizioni (settori speciali o ordinari, regime etc…). Ad esse segue la scheda S1 che costituisce l’elenco dei soggetti che hanno manifestato interesse a partecipare alla procedura ristretta.<br>
Con riferimento agli ammessi/invitati alla seconda fase occorre utilizzare la scheda S2.</span></span></span></p>

<p style="margin-bottom:11px;"> </p>
