### ISSUE TITLE
[Toscana/bolzano] - Scheda S3 - ERR9999  errore generico

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1173]
Salve,
Riapro nuova issue in riferimento alla #1146 

Stiamo riscontrando ERR9999 - errore generico all'invio della scheda S3 in cui vengono compilati tutti i campi anche quelli facoltativi.

La scheda S3 viene inviata dopo la S2, questo è l'ordine:

P2_16
S2
S3 - [S3(1).json](https://github.com/anticorruzione/npa/files/14376514/S3.1.json)

Nella S3 sono stati valorizzati anche i campi facoltativi e ci restitutisce l'errore generico ERR9999
Ci potete dare supporto?

**Comment by supportoAnac** [comment]
Salve, la scheda S3 risulta già essere confermata. Non è possibile rettificare la scheda S3 già inviata inviandone un'altra.
