### ISSUE TITLE
[Teamsystem] - ERR 77 - Il partecipante non è valido per il lotto

### ISSUE THREAD

**Issue by mcgirone** [anticorruzione/npa#1174]
Buonasera,
Stiamo riscontrando "ER77: Il partecipante non è valido per il lotto" all'invio della scheda di aggiudicazione A2_29.

Analizzando il Json S2 e A2_29 inviati, confermiamo che nell'aggiudicazione stiamo inviando i dati di tutti gli offerenti valorizzando correttamente il boolean "aggiudicatario" per identificarlo correttamente. Dunque l’idPartecipante relativo all’aggiudicatario nella scheda di aggiudicazione combacia con quello presente tra i partecipanti inviati con la scheda S2.

Potreste fornirci supporto per questo tipo di errore?
Grazie

**Comment by matteolaltrelli** [comment]
Abbiamo segnalato questo bug con la issue #1039 in data 17 gennaio 2024, chiusa dal supporto senza risolvere ma soprattutto senza riscontrare l'errore.

**Comment by supportoAnac** [comment]
Si chiede gentilmente di fornire maggiori informazioni (ID Appalto, payload delle schede trasmesse, etc) allo scopo di effettuare le verifiche necessarie.

**Comment by matteolaltrelli** [comment]
Abbiamo una stazione appaltante bloccata in produzione con questo errore:
ID Appalto: ab908971-7e01-493d-9dfe-07ed777a5d47
Scheda S2 inviata e confermata: 14391470-4765-45f5-81d4-253e8b5d7cce con i seguenti id_partecipanti:

- 8bdb2b92-a4f0-593d-a10f-875421dac34c
- db411cd5-abc3-5dbf-a176-c9bb869ec496
- 95b9269c-4414-5dbc-a536-9e786b0fc7b5

Creata la scheda A2_29: 86f4f36f-132a-4822-82ad-a73ddf0b618c

In conferma scheda otteniamo il seguente errore:
CODICE: ERR77
DESCRIZIONE ERRORE: il partecipante non è valido per il lotto
idPartecipante: 8bdb2b92-a4f0-593d-a10f-875421dac34c - cig: XXXXXXX

Attendiamo urgentemente un riscontro

**Comment by mcgirone** [comment]
Id appalto: bfe6e69c-a69d-4e4f-b151-c790463d13b1
S2-> "idScheda":"facbecb6-2e8d-49d2-9942-98405bf9b8fb"
A2_29 -> "idScheda":"d28385c4-6789-4c10-b17f-02cafc7313de"

Response conferma scheda A2_29:
{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","dettaglio":"idPartecipante: ef4f8924-bd69-4970-8e78-b81c205af068 - cig: I001B9F299","codice":"ERR77"}]}

**Comment by dpagliari** [comment]
stesso problema riscontrato anche da noi, in attesa di Vs. risoluzione

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 12/03/2024.

**Comment by matteolaltrelli** [comment]
L'anomalia non sembra essere risolta.
Abbiamo una stazione appaltante bloccata in produzione con questo errore:
ID Appalto: ab908971-7e01-493d-9dfe-07ed777a5d47
Scheda S2 inviata e confermata: 14391470-4765-45f5-81d4-253e8b5d7cce con i seguenti id_partecipanti:

8bdb2b92-a4f0-593d-a10f-875421dac34c
db411cd5-abc3-5dbf-a176-c9bb869ec496
95b9269c-4414-5dbc-a536-9e786b0fc7b5

In creazione scheda otteniamo il seguente errore:
CODICE: ERR77
DESCRIZIONE ERRORE: il partecipante non è valido per il lotto
idPartecipante: 8bdb2b92-a4f0-593d-a10f-875421dac34c - cig: XXXXXXX

"govway_message_id": "8e3e9e18-4f00-4898-8bc2-5d60a0e0ac2a",
"govway_transaction_id": "ad643d52-ec15-11ee-852e-005056844885",

Attendiamo urgentemente un riscontro

**Comment by mcgirone** [comment]
Anche a noi non sembra risolto l'errore, continuiamo a riscontrarlo
