### ISSUE TITLE
comportamento scheda NAG per adeguamento 01/03/2024

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1175]
Buongiorno,

a fronte del nuovo orchestratore rilasciato il 31/01 per adeguamento in produzione del 01/03/2024, è segnato il possibile invio della scheda NAG dopo le schede P6_2, P7_1_2, P7_1_3, P7_2.

a fronte di test effettuati tuttavia si riscontra l'erroe che la scheda non è ammessa in questa fase dell'appalto se si prova ad inviare la scheda NAG dopo la scheda P6_2, P7_1_2, P7_1_3, P7_2 :
![image](https://github.com/anticorruzione/npa/assets/135005848/44094395-dd18-4410-83ec-3c214f24b5b9)

è possibile avere dei chiarimenti?

**Comment by LucaMaggioni1** [comment]
a seguito di nuova prova siamo riusciti ad inviare la NAG dopo la scheda P7_2. rimane ancor anon possibile l'invio per la scheda P6_2, P7_1_2 e P7_1_3. di seguito i dettagli dei tentativi fatti per le opportune verifiche:

1.	P6_2
•	id_appalto: 4ff113d5-311b-4362-8751-5d51817f05ed

•	Payload scheda appalto: 
{"scheda":{"type":"SchedaComunicaAppaltoType","codice":{"idTipologica":"codiceScheda","codice":"P6_2"},"versione":"1.0","body":{"type":"SchedaP62Type","anacForm":{"stazioniAppaltanti":[{"codiceFiscale":"05017630152","codiceAusa":"9000000010","codiceCentroCosto":"f481feb8-2d8f-46be-bb14-a950234559d6","saTitolare":true}],"appalto":{"codiceAppalto":"P6_2_TEST AQ001","cigAccordoQuadro":"I00093A49B","datiBaseProcedura":{"tipoProcedura":{"idTipologica":"tipoProcedura","codice":"open"}},"datiBase":{"oggetto":"OGETTO GARA"}},"lotti":[{"servizioPubblicoLocale":false,"lotIdentifier":"LOTTO001","codIstat":{"idTipologica":"codIstat","codice":"3015146"},"contrattiDisposizioniParticolari":{"idTipologica":"contrattiDisposizioniParticolari","codice":"1"},"opzioniRinnovi":false,"afferenteInvestimentiPNRR":false,"modalitaAcquisizione":{"idTipologica":"modalitaAcquisizione","codice":"1"},"categoria":{"idTipologica":"categoria","codice":"FB"},"ripetizioniEConsegneComplementari":false,"quadroEconomicoStandard":{"impForniture":10000.0,"sommeADisposizione":10000.0},"datiBase":{"oggettoContratto":{"idTipologica":"oggettoContratto","codice":"supplies"},"oggetto":"OGGETTO LOTTO"}}]}}}}

•	payload NAG:  
{"idAppalto":"4ff113d5-311b-4362-8751-5d51817f05ed","scheda":{"type":"SchedaPostPubblicazioneType","codice":{"idTipologica":"codiceScheda","codice":"NAG"},"versione":"1.0","body":{"type":"SchedaNAGType","anacForm":{"lotti":[{"cig":"I000B1B18B"}]}}}}

2.	P7_1_3
•	id_appalto: 4e52e362-4622-4248-b1d1-dfa83c20294b

•	Payload scheda appalto: 
{"scheda":{"type":"SchedaComunicaAppaltoType","codice":{"idTipologica":"codiceScheda","codice":"P7_1_3"},"versione":"1.0","body":{"type":"SchedaP713Type","anacForm":{"stazioniAppaltanti":[{"codiceFiscale":"05017630152","codiceAusa":"9000000010","codiceCentroCosto":"f481feb8-2d8f-46be-bb14-a950234559d6","saTitolare":true}],"appalto":{"codiceAppalto":"P713","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"1"}],"motivazioneCIG":{"idTipologica":"motivazioneCIG","codice":"1"},"strumentiSvolgimentoProcedure":{"idTipologica":"strumentiSvolgimentoProcedure","codice":"2"},"datiBase":{"oggetto":"OGGETTO GARA","importo":10000.0},"datiBaseProcedura":{"tipoProcedura":{"idTipologica":"tipoProcedura","codice":"neg-wo-call"}}},"lotti":[{"lotIdentifier":"LOTTO001","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"1"}],"saNonSoggettaObblighi24Dicembre2015":false,"iniziativeNonSoddisfacenti":false,"condizioniNegoziata":[{"idTipologica":"condizioniNegoziata","codice":"38"}],"codIstat":{"idTipologica":"codIstat","codice":"001001001"},"servizioPubblicoLocale":false,"lavoroOAcquistoPrevistoInProgrammazione":false,"ipotesiCollegamento":{"motivoCollegamento":{"idTipologica":"motivoCollegamento","codice":"10"}},"afferenteInvestimentiPNRR":false,"ccnl":"NON APPLICABILE","categoria":{"idTipologica":"categoria","codice":"FB"},"prestazioniComprese":{"idTipologica":"prestazioniComprese","codice":"1"},"finanziamenti":[{"tipoFinanziamento":{"idTipologica":"tipoFinanziamento","codice":"C02"},"importo":10000.0}],"tipoRealizzazione":{"idTipologica":"tipoRealizzazione","codice":"1"},"datiBase":{"oggettoContratto":{"idTipologica":"oggettoContratto","codice":"supplies"},"oggetto":"OGGETTO LOTTO","importo":10000.0},"datiBaseDocumenti":{"url":"http://www.ariaspa.it/"},"datiBaseTerminiInvio":{"scadenzaPresentazioneInvito":"2024-02-28T00:00:00Z"}}]}}}}

•	paylload scheda NAG:  
{"idAppalto":"4e52e362-4622-4248-b1d1-dfa83c20294b","scheda":{"type":"SchedaPostPubblicazioneType","codice":{"idTipologica":"codiceScheda","codice":"NAG"},"versione":"1.0","body":{"type":"SchedaNAGType","anacForm":{"lotti":[{"cig":"I001CC6609"}]}}}}

3.	P7_1_2
•	ia_appalto: 6839a1b6-f9cb-41c2-8658-66be974d8ba2

•	payload scheda appalto:  
{"scheda":{"type":"SchedaComunicaAppaltoType","codice":{"idTipologica":"codiceScheda","codice":"P7_1_2"},"versione":"1.0","body":{"type":"SchedaP712Type","anacForm":{"stazioniAppaltanti":[{"codiceFiscale":"05017630152","codiceAusa":"9000000010","codiceCentroCosto":"f481feb8-2d8f-46be-bb14-a950234559d6","saTitolare":true}],"appalto":{"codiceAppalto":"P7_1_2_CHANGELOGG","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"1"}],"motivazioneCIG":{"idTipologica":"motivazioneCIG","codice":"1"},"strumentiSvolgimentoProcedure":{"idTipologica":"strumentiSvolgimentoProcedure","codice":"6"},"datiBase":{"oggetto":"OGGETTO GARA","importo":10000.0},"datiBaseProcedura":{"tipoProcedura":{"idTipologica":"tipoProcedura","codice":"open"}}},"lotti":[{"lotIdentifier":"LOTTO001","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"1"}],"saNonSoggettaObblighi24Dicembre2015":false,"iniziativeNonSoddisfacenti":false,"condizioniNegoziata":[{"idTipologica":"condizioniNegoziata","codice":"33"}],"codIstat":{"idTipologica":"codIstat","codice":"001001001"},"servizioPubblicoLocale":false,"lavoroOAcquistoPrevistoInProgrammazione":false,"ipotesiCollegamento":{"motivoCollegamento":{"idTipologica":"motivoCollegamento","codice":"1"}},"afferenteInvestimentiPNRR":false,"ccnl":"NON APPLICABILE","categoria":{"idTipologica":"categoria","codice":"999"},"prestazioniComprese":{"idTipologica":"prestazioniComprese","codice":"1"},"finanziamenti":[{"tipoFinanziamento":{"idTipologica":"tipoFinanziamento","codice":"D"},"importo":10.0}],"tipoRealizzazione":{"idTipologica":"tipoRealizzazione","codice":"1"},"datiBase":{"oggettoContratto":{"idTipologica":"oggettoContratto","codice":"supplies"},"oggetto":"OGGETTO LOTTO","importo":10000.0},"datiBaseDocumenti":{"url":"http://www.ariaspa.it/"},"datiBaseTerminiInvio":{"scadenzaPresentazioneInvito":"2024-02-29T00:00:00Z"}}]}}}}

•	payload scheda NAG: 
{"idAppalto":"6839a1b6-f9cb-41c2-8658-66be974d8ba2","scheda":{"type":"SchedaPostPubblicazioneType","codice":{"idTipologica":"codiceScheda","codice":"NAG"},"versione":"1.0","body":{"type":"SchedaNAGType","anacForm":{"lotti":[{"cig":"I001D36277"}]}}}}

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Siamo a conoscenza della situazione e abbiamo già avviato le procedure necessarie per risolvere la problematica che verrà fixata orientativamente nel mese di Dicembre.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
