### ISSUE TITLE
invio scheda S3 più volte per un lotto

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1176]
Buongiorno,

da test effettuati, se dopo la scheda A proviamo ad inviare la scheda S3 per un lotto più di una volta, otteniamo al secondo tentativol'errore che la scheda non è ammessa in questa fase dell'appalto:
![image](https://github.com/anticorruzione/npa/assets/135005848/4621e4bf-4979-46ac-9892-7c5ff91d2ba5)

non era possibile inviare la scheda S3 più volte? se l'utente deve comunicare la modifica degli incarichi per un lotto come deve procedere?

**Comment by supportoAnac** [comment]
Si chiede gentilmente di fornire l'identificativo univoco e il payload della scheda trasmessa, allo scopo di effettuare una verifica.

**Comment by LucaMaggioni1** [comment]
di seguito quanto richiesto. attenziono solo che la problematica si presenta in tutte le prove che abbiamo fatto (anche per schede di publbicazione diverse):

  id_appalto: ec58c9c1-a07c-4337-ac01-ab74dd621b36

•	Payload scheda appalto:
{"scheda":{"type":"SchedaComunicaAppaltoType","codice":{"idTipologica":"codiceScheda","codice":"P2_10"},"versione":"1.0","body":{"type":"SchedaP210Type","anacForm":{"stazioniAppaltanti":[{"codiceFiscale":"05017630152","codiceAusa":"9000000010","codiceCentroCosto":"f481feb8-2d8f-46be-bb14-a950234559d6","saTitolare":false}],"appalto":{"codiceAppalto":"AppaltoP2_10_obbligatori-20231206-01","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"17"}],"motivoUrgenza":{"idTipologica":"motivoUrgenza","codice":"5"},"datiBase":{"oggetto":"scheda P2_10(ESI_OPE)"},"datiBaseProcedura":{"tipoProcedura":{"idTipologica":"tipoProcedura","codice":"comp-tend"}}},"lotti":[{"lotIdentifier":"lot1","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"17"}],"contrattiDisposizioniParticolari":{"idTipologica":"contrattiDisposizioniParticolari","codice":"1"},"codIstat":{"idTipologica":"codIstat","codice":"3015146"},"afferenteInvestimentiPNRR":false,"prestazioniComprese":{"idTipologica":"prestazioni","codice":"1"},"ripetizioniEConsegneComplementari":false,"ccnl":"Non applicabile","modalitaAcquisizione":{"idTipologica":"modalitaAcquisizione","codice":"1"},"opzioniRinnovi":false,"categoria":{"idTipologica":"categoria","codice":"FB"},"quadroEconomicoStandard":{"impForniture":10000.0,"sommeADisposizione":10000.0},"datiBase":{"oggettoContratto":{"idTipologica":"oggettoContratto","codice":"supplies"},"oggetto":"immobili"}}]},"espd":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjxwaXBwbz5waXBwbzwvcGlwcG8+"}}}

•	paylload scheda S3:
{"idAppalto":"ec58c9c1-a07c-4337-ac01-ab74dd621b36","scheda":{"type":"SchedaPostPubblicazioneType","codice":{"idTipologica":"codiceScheda","codice":"S3"},"versione":"1.0","body":{"type":"SchedaS3Type","anacForm":{"elencoIncarichi":[{"cig":"E000060358"}]}}}}
