### ISSUE TITLE
[Maggioli] Quadro economico concessioni NON alternativo a quadro economico standard

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1177]
Si segnala che nelle schede A1_28 e A2_28 il quadro economico standard è obbligatorio.
Non può essere trasmesso quello per concessioni in alternativa a quello standard (come invece avviene nella AD4, così come ci è stato indicato di fare).

**Comment by paolo-urbanetto** [comment]
Scusate, rettifico: AD1_28 e AD2_28

**Comment by anac-uscp** [comment]
<p><span style="font-size:12.0pt;"><span style="line-height:107%;"><span style='font-family:"Aptos",sans-serif;'>L’anomalia è stata già risolta nello yaml delle schede AD1_28 e AD2_28 </span></span></span></p>
