### ISSUE TITLE
Chiarimenti invio Scheda SC1

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1178]
Salve,
abbiamo necessità di chiarire due OP:
in merito alle varie issue sull'impossibilità di inviare una scheda di Aggiudicazione con più partecipanti,

- E' possibile l'invio della SC1 per una multiaggiudicazione?
- In caso di accordo quadro (in cui è prevista la multiaggiudicazione), è possibile inviare una scheda di Aggiudicazione con più partecipanti con flag aggiudicatario=true?

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="font-size:11pt;"><span style="line-height:104%;"><span style="font-family:Calibri,sans-serif;"><span style="color:#0070c0;">In caso di AQ multiaggiudicatario, è possibile inviare una scheda di aggiudicazione con più di un aggiudicatario (flag aggiudicatario = true).<br>
Non è invece possibile inviare la scheda SC1 per una multiaggiudicazione. La scheda SC1 deve essere inviata per ciascun OE a seguito dell’acquisizione di un CIG di adesione per il singolo OE che esegue la prestazione.</span></span></span></span></p>
