### ISSUE TITLE
[Intercent-ER][BLK] Errore generico Err40 in conferma scheda CO2

### ISSUE THREAD

**Issue by AndreaClerici** [anticorruzione/npa#1184]
Buongiorno,
purtroppo nonostante svariati tentativi siamo sempre bloccati sull'invio della scheda CO2.
Il crea-scheda risponde positivamente, ma il conferma scheda restituisce ERR40 ("errore generico durante l'estrazione dei dati della scheda").
Chiediamo delucidazioni al più presto perché l'invio di questa scheda risulta impossibile da molto tempo e abbiamo necessità che sia possibile inviarla al più presto.
Per completezza, sia l'AD5 che la CO2 sono state create oggi seguendo le ultime specifiche disponibili.

Grazie.

**Comment by fabiovenditti** [comment]
Ci sono collegata già altre issue (1089 e la 1090) sia per la CO2 che per la CO1 il problema è evidentemente urgente

**Comment by AndreaClerici** [comment]
> Ci sono collegata già altre issue (1089 e la 1090) sia per la CO2 che per la CO1 il problema è evidentemente urgente

Ho aperto la segnalazione perché per noi sta diventando sempre più urgente.
Ho dato un'occhiata alle issue segnalate ma non vedo riscontri da parte di ANAC.
Spero ci facciano sapere qualcosa al più presto.

**Comment by supportoAnac** [comment]
Si chiede gentilmente di fornire maggiori informazioni (idAppalto, payload delle schede trasmesse, etc) allo scopo di effettuare verifiche.

**Comment by AndreaClerici** [comment]
> Si chiede gentilmente di fornire maggiori informazioni (idAppalto, payload delle schede trasmesse, etc) allo scopo di effettuare verifiche.

Buongiorno,
prima di tutto grazie per la pronta risposta.

IdAppalto: 8028a1b9-3682-4bc9-8e96-eaf02da7e270
idScheda AD5: 49a386ae-7342-45d6-8e42-ca601a506944
idScheda CO2: 9de33dd0-6125-4956-b311-6f94db193c88

Payload CO2:

`{
   "idAppalto":"8028a1b9-3682-4bc9-8e96-eaf02da7e270",
   "scheda": {
      "codice": {
        "idTipologica": "codiceScheda",
        "codice": "CO2"
      },
      "versione":"1.0",
      "body":{
         "anacForm":{
            "cig": "I001F0B57E",
            "conclusione": {
               "dataInizio":"2022-01-23T12:02:05Z",
               "dataUltimazione":"2022-01-23T12:02:05Z",
               "importo": 1000
            }
         }
      }
   }
}`

Payload AD5:
`{
   "scheda":{
      "codice":{
         "idTipologica":"codiceScheda",
         "codice":"AD5"
      },
      "versione":"1.0",
      "body":{
         "anacForm":{
            "stazioniAppaltanti":[
               {
                  "codiceFiscale":"91252510374",
                  "codiceAusa":"9000000006",
                  "codiceCentroCosto":"058f6af5-eee0-4121-ac28-7a3723ceddcf",
                  "funzioniSvolte":[
                     {
                        "idTipologica":"funzioniSvolte",
                        "codice":"2"
                     }
                  ],
                  "saTitolare":true
               }
            ],
            "appalto":{
               "codiceAppalto":"dc3db971-d574-4d7a-be08-035f70b95bad",
               "datiBase":{
                  "oggetto":"GARA 50"
               }
            },
            "aggiudicazioni":[
               {
                  "lotIdentifier":"LOT-0001",
                  "cup":"string",
                  "partecipanti":[
                     {
                        "idPartecipante":"63A8A119-E3A8-4F93-8519-CA7E873AF4D3",
                        "codiceFiscale":"00427620XXX",
                        "denominazione":"Fornitore Test 242",
                        "importo":4000
                     }
                  ],
                  "ccnl":"non-applicabile",
                  "categoria":{
                     "idTipologica":"categoria",
                     "codice":"FS"
                  },
                  "codIstat":{
                     "idTipologica":"codIstat",
                     "codice":"015065116"
                  },
                  "datiBase":{
                     "oggettoContratto":{
                        "idTipologica":"oggettoContratto",
                        "codice":"services"
                     },
                     "oggetto":"AD5 con CO2"
                  },
                  "datiBaseDocumenti":{
                     "url":"https://www.google.com"
                  }
               }
            ]
         },
         "espd":"troppo grande per la lunghezza massima del commento"
      }
   }
}
`

Fatemi sapere se devo fornirvi ulteriori informazioni.

Grazie.

**Comment by matteolaltrelli** [comment]
La scheda CO2 viene creata correttamente ma al conferma ci restituisce
"codice": "ERR40" - errore generico durante l'estrazione dei dati della scheda
idAppalto: f93408fa-74b6-4aa5-bb5e-39d79e446a93
"govway_message_id": "c4786bd0-4468-4a18-a58a-721261cae679",
"govway_transaction_id": "9c1a9b6d-d560-11ee-9b99-0050568e9679"

Vedendo la diffusione del problema credo ci sia un bug generale nella conferma di questa scheda.

**Comment by fabiovenditti** [comment]
Provate questa mattina io ho provato e sembra che vada

**Comment by AndreaClerici** [comment]
Confermo che la CO2 ora sembra funzionare. Per la CO1 non ho ancora verificato.

Grazie @fabiovenditti per la segnalazione!

E grazie anche a chi ha risolto il problema. :)

**Comment by supportoAnac** [comment]
Si conferma la risoluzione della problematica con l’ultimo rilascio.
