### ISSUE TITLE
[BLK] Scheda P5 impossibile da compilare per via di regole errate REG98 e REG99

### ISSUE THREAD

**Issue by lucaCorigliano-SA** [anticorruzione/npa#1185]
I server anac validano le seguenti regole sulla scheda P5: `REG98` e `REG99`

`REG98` fa riferimento a `appalto.datiBase.importo`, che è disponibile solo a partire dallo schema v1.0.1
`REG99` fa riferimento a `lotti.datiBase.importo` che è disponibile solo a partire dallo schema v1.0.1

Questo rende impossibile compilare questa scheda (e tante altre in realtà). Si richiede risoluzione rapida.

**Comment by supportoAnac** [comment]
Si segnala che è disponibile la versione 1.0.2 della scheda,  si chiede di accertarsi di utilizzare in ambiente di qualificazione l'ultima versione disponibile.

**Comment by lucaCorigliano-SA** [comment]
Perdonatemi, con questo messaggio mi volete far capire che l'esercizio è già alla versione 1.0.2? Questo problema è presente in produzione.
