### ISSUE TITLE
[Maggioli] - Richiesta pubblicazione avviso

### ISSUE THREAD

**Issue by albertosaturno** [anticorruzione/npa#1186]
Buongiorno,

sarebbe possibile sbloccare la pubblicazione in ambiente di collaudo di un avviso dai aggiudicazione (scheda AD3) ai fini della certificazione di uno tra i seguenti?

IdAppalto: 2e14d65c-de09-45b9-9af9-93ce85cdbb9b
IdAppalto: 1342a25d-4652-475f-92c4-016079e35706
IdAppalto: 62c6653f-2083-4c60-b045-728e2e18272d

Grazie

**Comment by supportoAnac** [comment]
Per poter procedere, occorre effettuare l’operazione di pubblicazione attraverso l’apposito servizio.
