### ISSUE TITLE
[Maggioli] [BLK] Scheda CL1 - ERR40

### ISSUE THREAD

**Issue by alessioiezzi96** [anticorruzione/npa#1192]
Buongiorno,
dopo aver eseguito l'operazione di "conferma-scheda" per una scheda CL1 viene restituito "ERR40 - errore generico durante l'estrazione dei dati della scheda". il crea-scheda invece va a buon fine.
Abbiamo notato che se creiamo la scheda passando modalitaDefinizione = null la conferma va a buon fine, mentre se l'oggetto è valorizzato, va in errore.

di seguito i riferimenti:

idAppalto: 4502f08f-a61a-41bf-9f3c-3ca5ce070b9d
idScheda: 482219da-75cb-4183-960e-911a8e416416
GovwayMessageId: 730025ec-45df-49be-befe-bdbd00263008
GovwayTransactionId: 68b2fb40-d53f-11ee-9b99-0050568e9679

Grazie

**Comment by supportoAnac** [comment]
Segnalazione presa in carico, regole in corso di verifica.

**Comment by lelio-raffaelli** [comment]
Buongiorno, cortesemente possiamo avere un aggiornamento per una issue segnalata come bloccante 5 mesi fa?

**Comment by fabiovenditti** [comment]
Anche noi riscontriamo lo stesso problema

**Comment by anac-uscp** [comment]
<p>Gentile Utente,<br>
<br>
da controlli effettuati sui nostri sistemi l'ultimo tentativo di conferma-scheda con errore ERR40 é stato effettuato in data 2024-02-27.<br>
<br>
Inoltre l'ultimo esito é stato restituito in data 2024-03-07, in particolare si tratta dell'operazione di cancella-scheda. Pertanto riteniamo la problematica risolta.<br>
<br>
<br>
Restiamo a disposizione per ulteriori chiarimenti.<br>
<br>
<br>
Saluti</p>

**Comment by anac-uscp** [comment]
<p>Il ticket era stato chiuso, poichè l'utente ha cancellato la scheda CL1 che voleva confermare e non ha più riprovato.<br>
<br>
E' stato fatto un test su postman, riportando la scheda in stato "IN_LAV" e cancellando tutti i campi relativi alla cancellazione.<br>
<br>
Il risultato restituito è il medesimo che l'utente riscontrava, ovvero ERR40.<br>
<br>
Log restituito:<br>
<br>
 </p>
