### ISSUE TITLE
[BLK] [Maggioli] Scheda P3_1 - Incoerenza regola 67 e modello scheda

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1194]
Come si fa a procedere con l'invio della scheda se la regola 67 verifica degli attributi che non ci sono nel modello scheda?
Nel caso specifico in validazione si ottiene il seguente messaggio:
REG67: il campo giustificazione aggiudicazione diretta è obbligatorio se il tipo di procedura è Negoziata senza previa indizione di gara
La regola verifica il campo appalto.datiBaseProcedura.giustificazioneProceduraAccelerata non presente nel modello.
Grazie.

**Comment by supportoAnac** [comment]
Problematica in corso di risoluzione, la fix verrà inclusa nei prossimi rilasci.
