### ISSUE TITLE
[BLK] Gestione Affidamenti diretti in house A3_6

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#1196]
Per gli Affidamenti diretti in house viene utilizzata la relativa scheda: A3_6
La scheda, come da orchestratore, attribuisce il CIG ed effettuando un test tutto funziona regolarmente.
Molte stazioni appaltanti però ci sollevano il problema che queste tipologie di affidamento **non dovrebbero avere un codice CIG** associato.

Riprendendo le FAQ:
https://www.anticorruzione.it/-/tracciabilit%C3%A0-dei-flussi-finanziari
nello specifico:
C3. Gli obblighi di tracciabilità trovano applicazione nel caso di prestazioni eseguite in favore di pubbliche amministrazioni da soggetti, giuridicamente distinti dalle stesse, ma sottoposti ad un controllo analogo a quello che le medesime esercitano sulle proprie strutture (cd. affidamenti in house)?
No, gli obblighi di tracciabilità non trovano applicazione in quanto non risultano integrati gli elementi costitutivi del contratto d’appalto (per difetto del requisito della terzietà). Nel caso in cui invece tali elementi dovessero sussistere, rimarrebbe l’obbligo di adeguamento alla normativa sulla tracciabilità (vedi par. 2.5 della [Determinazione n. 4 del 7 luglio 2011](https://www.anticorruzione.it/-/determinazione-n.-4-del-7-luglio-2011) aggiornata con [Delibera n. 585 del 19 dicembre 2023](https://www.anticorruzione.it/-/delibera-n.-585-del-19-dicembre-2023-linee-guida-sulla-tracciabilit%C3%A0-dei-flussi-finanziari)).

Resta ferma l’osservanza della normativa sulla tracciabilità per le società in house quando le stesse affidano appalti a terzi, rivestendo in tal caso la qualifica di stazione appaltante. Resta ferma, altresì, l’osservanza degli obblighi di comunicazione in favore dell’Autorità, ai sensi dell’articolo 23, comma 5, del codice.

Quindi per queste tipologie di affidamenti cosa deve fare la stazione appaltante? Utilizzare la scheda A3_6 che attribuisce il CIG, o in alternativa non comunicare niente a PCP?

Restiamo in attesa di delucidazioni in merito.
Chiedo anche ad altri colleghi se hanno riscontrato la stessa problematica con le loro stazioni appaltanti.

**Comment by anac-uscp** [comment]
<p class="MsoPlainText"><span style="font-size:10.5pt;"><span style="font-family:Consolas;"><span style="font-size:12.0pt;"><span style='font-family:"Aptos",sans-serif;'>L’art. 23, co. 5, del D.Lgs. 36/2023, chiarisce che  “con </span></span><span style="font-size:12.0pt;"><span style='font-family:"Aptos",sans-serif;'>proprio provvedimento l’ANAC individua le informazioni che le stazioni appaltanti e gli enti concedenti sono tenuti a trasmettere alla Banca dati nazionale dei contratti pubblici attraverso le piattaforme telematiche di cui all’</span></span><a href="https://www.bosettiegatti.eu/info/norme/statali/2023_0036.htm#025"><span style="font-size:12.0pt;"><span style='font-family:"Aptos",sans-serif;'><span style="text-decoration:none;"><span>articolo 25</span></span></span></span></a><span style="font-size:12.0pt;"><span style='font-family:"Aptos",sans-serif;'>. Gli obblighi informativi di cui al primo periodo riguardano anche gli affidamenti diretti a società in house di cui all’</span></span><a href="https://www.bosettiegatti.eu/info/norme/statali/2023_0036.htm#007"><span style="font-size:12.0pt;"><span style='font-family:"Aptos",sans-serif;'><span style="text-decoration:none;"><span>articolo 7, comma 2”.</span></span></span></span></a><span style="font-size:12.0pt;"><span style='font-family:"Aptos",sans-serif;'> Per l’obbligo di acquisizione del CIG per l’affidamento in house vedi FAQ D.7 sulla </span></span> <span style="font-size:12.0pt;"><span style='font-family:"Aptos",sans-serif;'>“Digitalizzazione dei contratti pubblici”.</span></span></span></span></p>

<p class="MsoPlainText"><span style="font-size:10.5pt;"><span style="font-family:Consolas;"><span style="font-size:12.0pt;"><span style='font-family:"Aptos",sans-serif;'>In definitiva, l’Amministrazione che affida un contratto in house deve comunicare la fattispecie con la scheda A3_6 appositamente delegata ad ospitare le informazioni ritenute necessarie dall’ANAC (vedi anche FAQ B.11 che stabiliva anche il regime transitorio).</span></span></span></span></p>

<p class="MsoPlainText"> </p>
