### ISSUE TITLE
Errore invio scheda CO2 [ERR40][errore generico durante l'estrazione dei dati della scheda][

### ISSUE THREAD

**Issue by FrancescaBrindisiL** [anticorruzione/npa#1198]
Salve,
mi dispiace comunicare che, nonostante numerosi tentativi, riscontriamo ancora delle difficoltà nell'inoltrare la scheda CO2. L'operazione di invio scheda continua a restituire l'errore ERR40 ("errore generico durante l'estrazione dei dati della scheda").

Chiediamo gentilmente chiarimenti al più presto in merito a questa problematica, poiché l'invio della suddetta scheda si presenta al momento impraticabile e la necessità di poterla trasmettere quanto prima è fondamentale. Per agevolare l'analisi della situazione, forniamo di seguito i dettagli identificativi della chiamata e della scheda.

- govway-message-id:       ce64ebd4-2018-4281-a602-9bf942de81b4
- govway-transaction-id:   13d5d0a6-d555-11ee-9ec6-0050568e08b3
- idAppalto:                        0138e5e0-720e-42fe-9dea-fdb8ca59ceb5 
- idScheda:                         c93759d2-0339-407c-90b1-421b7236ae86
- rifContratto:                     36099
- CIG:                                  I001A34709
- Payload CO2:                       
{"cig":"I001A34709","dataInizio":"2024-03-15T00:00:00Z","dataUltimazione":"2024-03-15T00:00:00Z","importo":1000.0}

Ringraziamo anticipatamente per la pronta risoluzione del problema.
Cordiali saluti

**Comment by fabiovenditti** [comment]
Provate questa mattina io ho provato e sembra che vada

**Comment by supportoAnac** [comment]
Si conferma la risoluzione della problematica con l’ultimo rilascio.
