### ISSUE TITLE
scheda A7_1_2 - campi ANACFORM

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1199]
Buongiorno,

dall'orchestratore si evince che la scheda A7_1_2 presenti molti più campi rispetto alle schede A1... e A2..., deducibilmente per tracciare ulteriori informazioni per l'effettiva procedura negoziata senza bando tramite indagine di mercato (che non prevede una scheda di indizione dato che la P7_1_2 dà avvio all'indagine di mercato). 
Avremmo necessità di alcuni chiarimenti:

- ID partecipante della scheda A7_1_2, devono essere riutilizzati gli stessi IDPartecipanti generati nelle schede S1 e S2? Dato che la scheda A7_1_2 chiede ancora di inserire le informazioni sui partecipanti (denominazione, ruoloOE ecc) che invece sono assenti nelle schede A1... e A2... è sorta la perprlessità su IDPartecipante da inserire (l'associazione IDPartecipante/OE non viene fatta anche per il flusso P7_1_2 già con la scheda S2, perchè chiedere nuovamente le info sui partecipanti?
- Come mai non è prevista una scheda analoga per il flusso della P7_1_3 e invece si usano le schede A2... che presentano informazioni limitate?

**Comment by anac-uscp** [comment]
<p>C'è effettivamente un'anomalia nelle schede A7_1_1 e A7_1_2.</p>

<p>Le schede presentano la struttura dati 'partecipanti' tipica delle schede di affidamento diretto che non si manifesta adeguata alla tipologia di affidamento prevista (P7_1_1 e P7_1_2) per la funzione che tali schede devono assolvere.<br>
Si sta provvedendo ad apportare i necessari correttivi.</p>

<p> </p>

<p> </p>

<p> </p>
