### ISSUE TITLE
A1.30 - Gara deserta soprasoglia: impossibile inviare scheda di aggiudicazione

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1202]
Salve,

E' presente una procedura soprasoglia deserta. E' stata compilata la scheda di aggiudicazione con relativo eForm.
All'invio della scheda anac restituisce errore ERR9999.
Visto che la gara è deserta, non ho offerte presentate da indicare nella scheda.

Abbiamo provato ad inviare la scheda con offerte presentate come lista vuota ma ANAC restituisce ERR9999.
Se, invece, invio la scheda con una lista con un oggetto vuoto all’interno, ANAC restituisce errore di campi obbligatori su idPartecipante, importo, ccnl, aggiudicatario (campi che non ho per una gara deserta)

All'interno dell'avviso di avvenuta aggiudicazione sono stati indicati e valorizzati i campi BT-144 e BT-142.

Come possiamo valorizzare i dati offertePresentate* se non ho nessun idPartecipante da inserire?

[A1_30.json](https://github.com/anticorruzione/npa/files/14423476/A1_30.json)

**Comment by collaudo5** [comment]
Buongiorno,

ci sono aggiornamenti su come vada gestito il flusso di comunicazione di una mancata aggiudicazione di una gara deserta?

Grazie.

**Comment by laurapavan** [comment]
Integro la domanda chiedendo di considerare anche il caso di gare multilotto con uno o più lotti deserti/non aggiudicati. Ove sia prevista la NAG, abbiamo visto che è possibile inviarla. Ma nei casi in cui la NAG non è prevista, cosa dobbiamo fare con i lotti che non sono e non saranno aggiudicati? Rimarranno "aperti"? La cosa è da chiarire anche ai fini della verifica dei tempi massimi di espletamento della procedura previsti dalla normativa.

**Comment by obigno77** [comment]
Fix prevista nel changelog-03
