### ISSUE TITLE
[TOSCANA/BOLZANO] - ESITO OPERAZIONE per un AVVISO di RETTIFICA

### ISSUE THREAD

**Issue by user6330** [anticorruzione/npa#1203]
E' stato pubblicato la rettifica dell'avviso '**8f9aaf29-aa8c-4c71-a27f-37890207deeb**' con una scheda P1_16.

Per recuperare l'esito tramite il servizio 'esito-operazione', passo come parametro **tipoOperazione = AV_RETT_EU** ma il risulato è una listaEsiti vuota

> {
   "status": 200,
   "title": "OK",
   "detail": "Esecuzione avvenuta con successo",
   "type": "about:blank",
   "listaEsiti": []
}

Se come parametro invece passo **tipoOperazione = AV_RETT** allora viene restituito l'esito

>{
   "status": 200,
   "title": "OK",
   "detail": "Esecuzione avvenuta con successo",
   "type": "about:blank",
   "listaEsiti": [   {
      "idAppalto": "2f0b2a64-66c7-4ff5-83ed-f25517b89c61",
      "idScheda": "dd5d2715-355e-4f26-92b7-366647caf5b5",
      "codiceScheda": "P1_16",
      "idAvviso": "8f9aaf29-aa8c-4c71-a27f-37890207deeb",
      "esito":       {
         "idTipologica": "esito",
         "codice": "WT"
      },
      "tipoOperazione":       {
         "idTipologica": "tipoOperazione",
         "codice": "AV_RETT"
      },
      "dataControllo": "2024-02-28T09:27:16.347+00:00",
      "dettaglio":       {
         "idTipologica": "esitoOperazione",
         "codice": "AV_RICHIESTA_RETT_IN_CORSO"
      }
   }]
}

E' quindi possibile utilizzare sempre il tipoOperazione "AV_RETT" per qualsiasi tipo di rettifica (che sia europeo o nazionale)?

**Comment by obigno77** [comment]
Si
