### ISSUE TITLE
[BLK] - ERR9999 scheda A7_1_2

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1204]
Buongiorno,

A seguito di diversi tentativi di compilazione della scheda A7_1_2 in ambiente di test, otteniamo sempre ERR9999 – errore generico in fase di conferma della scheda. Dato l’errore generico non si riesce a capire qual è il problema. Indichiamo che l’errore lo riscontriamo sia compilando i soli campi obbligatori che compilando i campi facoltativi. Ci sono dei problemi nell’invio di questa scheda?

In allegato, informato json, un esempio di compilazione dei campi per l’invio della scheda per cui si ottiene errore generico ERR9999:
[A7_1_2.json](https://github.com/anticorruzione/npa/files/14431873/A7_1_2.json)

Grazie

**Comment by mcgirone** [comment]
Anche noi abbiamo riscontrato lo stesso problema e non abbiamo ancora ricevuto risposta.

**Comment by matteolaltrelli** [comment]
Anche noi abbiamo lo stesso errore id_appalto:  b2782e93-e14c-4ed1-928a-599d5586690c

**Comment by LucaMaggioni1** [comment]
riportiamo un ID-Appalto di esempio: 9822dd01-b65c-40e4-a13a-51c7277195b2

**Comment by obigno77** [comment]
Da verifiche sul db sembra che ci fosse un problema in quel periodo che è stato superato intorno alla metà di aprile.
E' possibile ritentare?
