### ISSUE TITLE
[Consip][BLK] - ERR40 su CO2

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1205]
la scheda CO2 non viene confermata (conferma-scheda) per il seguente errore:
**ERR40 - errore generico durante l'estrazione dei dati della scheda**

**id appalto:** d2347e88-726d-4c91-9c87-d297eb34516e
**id scheda:** 732fbb95-7f11-4741-9264-d1860ae9cf01
**GovWay-Message-ID:**"28b0e83a-01eb-4e8c-b8f3-eca2243159a5"
**GovWay-Transaction-ID:**"444ab871-d627-11ee-9ec6-0050568e08b3"

potete verificare?

**Comment by fabiovenditti** [comment]
Provate questa mattina io ho provato e sembra che vada
