### ISSUE TITLE
Quadro economico concessioni in AD4

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#1208]
Buongiorno, si chiede come mai nella scheda AD4 ci sia il quadro economico delle concessioni dal momento che tale scheda è relativa ai soli appalti

**Comment by pietropalermoIT** [comment]
Buongiorno non sono d'accordo con l'interpretazione proposta, posso avere i riferimenti normativi delle convenzioni e degli AQ per le concessioni? non mi sembra che sia fattispecie a cui si faccia riferimento nel LIBRO IV - DEL PARTENARIATO PUBBLICO-PRIVATO E DELLE CONCESSIONI

**Comment by anac-uscp** [comment]
<p>Nella colonna 'Settore-Regime' dell'orchestratore che individua il settore e il regime per i quali è possibile utilizzare la scheda AD4, è riportata la seguente descrizione:</p>

<p><em>appalti e concessioni tutti i settori - tutti i regimi</em></p>
