### ISSUE TITLE
Errore TED Bloccante

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#1209]
Salve,

riapro ticket in coda alla vostra risposta, come da vostra richiesta nel [1130](https://github.com/anticorruzione/npa/issues/1130).

L'id appalto citato, 002fb292-4f1d-4361-be57-efea0ca14430, è stato creato il 19/02. Il rilascio è del 09/02, assumo sia stato staccato con la nuova versione.

Potete verificare se la versione è corretta e darci riscontro per favore?

**Comment by supportoAnac** [comment]
La anomalia relativa agli errori TED troncati è stata risolta con il rilascio del 12/03/2024.
