### ISSUE TITLE
[BLK] Importazione appalti - consulta appalto 403

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#1216]
Un RP ha creato un affidamento diretto direttamente da PCP applicazione web.
Lo stesso ci richiede di importare l'appalto nel nostro applicativo per poi proseguire con l'invio delle schede successive attraverso la nostra piattaforma.
Quando proviamo ad invocare il consulta_appalto ovviamente con le credenziali del RP (con i medesimi dati della SA), otteniamo un 403.
esempio:
"type": "https://govway.org/handling-errors/403/AuthorizationContentDeny.html",
"title": "AuthorizationContentDeny",
"status": 403,
"detail": "Unauthorized request content",
"govway_id": "1f455063-d6f2-11ee-a2a9-00505684399c"

Prima di tutto è possibile effettuare questa operazione?
Ad ogni modo sarebbe utile prevedere questi meccanismi di importazione.

**Comment by mpizziconi** [comment]
si è trattato di un problema dovuto all'assenza del claim userRole nel token JWS

'${securityToken:audit.payloadClaim(userRole)}' with unexpected value 'null') Il chiamante non è autorizzato ad invocare l'API
