### ISSUE TITLE
[BLK] Null response ed appalto non creato

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1219]
Stiamo provando a generare una scheda di `crea-appalto` **P1_16** con 93 lotti per simulare una richiesta di un cliente.
Abbiamo compilato l'eform con 93 lotti e tutti i dati facoltativi da voi richiesti, inserito correttamente il base64 di eform ed espd e tutti i dati necessari a rendere la scheda valida.

A seguito della chiamata otteniamo una response vuota senza nemmeno gli header di **gov-way**

Nella speranza che possano essere d'aiuto questi sono gli header che abbiamo ricevuto:

```json
{
  "server": [
    "nginx"
  ],
  "date": [
    "Fri, 01 Mar 2024 11:53:28 GMT"
  ],
  "content-type": [
    "text/html"
  ],
  "content-length": [
    "176"
  ],
  "strict-transport-security": [
    "max-age=63072000"
  ]
}
```

Codice appalto: `af-tender://giulioprovacose/id/1234`
Il Peso del json della request è: 1,38 MB (1.453.457 byte)

**Comment by supportoAnac** [comment]
Si chiede gentilmente di provare a chiamare nuovamente il servizio e verificare se la problematica si ripresenta.

**Comment by glastra-digitalpa** [comment]
La problematica resta la stessa.

Sono state effettuate svariate prove nelle due settimane successive alla segnalazione, modificando dati e variando il numero di lotti, tuttavia la problematica si ripresenta uguale: **response totalmente assente** (`null`) ed header in cui sono assenti anche  le chiavi di gov-way:


Questo è quello che arriva negli header:
```json
{
  "server": [
    "nginx"
  ],
  "date": [
    "Wed, 13 Mar 2024 08:09:40 GMT"
  ],
  "content-type": [
    "text/html"
  ],
  "content-length": [
    "176"
  ],
  "strict-transport-security": [
    "max-age=63072000"
  ]
}
```
