### ISSUE TITLE
Errore TED in fase di pubblica avviso

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#1222]
Salve,

abbiamo confermato un appalto, riscontrando un primo errore TED in fase di pubblica avviso.

Mettendo a posto il dato in errore nell'eform e tentando il reinvio della scheda ci troviamo di fronte al seguente errore:

> ERR64: [400] during [POST] to [http://pcp-qlf-ted-ms.pcp-qlf.svc:8080/submit?language=it&authorEmail=ufficio.uscp%40anticorruzione.it] [TedMsClient#submit(String,String,String)]: [{"code":400,"status":"400 BAD_REQUEST","title":"Error","detail":"{\"code\":\"notice.NOTICE_IMPORT_VALUE_EXCEPTION\",\"message\":\"A notice with the same id and version id already exists.\",\"showDetails\":true}","links":null}]

Ovviamente abbiamo avanzato il VersionID dell'eform, continua a non fungere. Abbiamo provato a mettere un nuovo notice id ma il sistema, giustamente, ci dice che si aspetta il vecchio. Cosa è successo? 

Siamo bloccati sul punto da giorni ormai.

Grazie,
Rossano

**Comment by supportoAnac** [comment]
Si chiede gentilmente di provare a creare da zero una nuova procedura di gara.
