### ISSUE TITLE
[ARIA SPA] scheda da utilizzare per i rinnovi

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1226]
Buongiorno,

mi collego alla issue #1009 dato che non risulta ancora ufficializzata la scheda da utilizzare in caso di rinnovo contrattuale.

Ci è stato segnalata qualche settimana fa tramite altri canali di utilizzare la scheda AD2_25 per un rinnovo (settore ordinario). questa indicazione può ritenersi ancora attuale e possiamo ufficializzarla?

stanno arrivando diverse richieste dagli utenti di come muoversi per ottenere il CIG per rinnovo e dalle varie documentazioni (in particolare GitHub) non è specificato l'uso di alcuna scheda per effettuare un rinnovo.

Grazie

**Comment by matteolaltrelli** [comment]
Buonasera,
tramite quale canale vi è stata segnalata la scheda AD2_25?
Noi ci troviamo con un appalto che deve essere rinnovato senza rinegoziare con l'operatore,
la procedura utilizzata 2 anni fa prevedeva già un rinnovo di altri 2 anni.
Ora il punto è, se utilizziamo la AD2_25 il cig che ne deriverà potrà essere utilizzato per essere collegato a delle AD4 per le future adesioni in accordo quadro?
Qualcuno si è già trovato in questa situazione?
Come l'avete gestita?
Grazie

**Comment by anac-uscp** [comment]
<p>Buongiorno,<br>
<br>
Innazitutto è bene ribadire la distinzione fra ripetizione e rinnovo. <br>
<br>
<br>
Come chiarito dalla giurisprudenza, "<em>mentre il rinnovo del contratto si sostanzia nella riedizione del rapporto pregresso (generalmente in virtù di una clausola già contenuta nella relativa disciplina), la ripetizione di servizi analoghi […] postula una nuova aggiudicazione (sia pure in forma negoziata) alla stregua di un progetto di base".</em><br>
<br>
<br>
Di conseguenza, in caso di rinnovo si utilizzano le schede relative alla comunicazione di modifiche contrattuali (M*), mentre in caso di ripetizione di prestazioni analoghe va richiesto un nuovo cig attraverso una delle schede AD*.</p>
