### ISSUE TITLE
[BLK] Schede famiglia P2/P3 - REG67 incoerente con il modello scheda

### ISSUE THREAD

**Issue by lucaCorigliano-SA** [anticorruzione/npa#1230]
La seguente issue è presente sia in esercizio che in ambiente di collaudo.

La seguente regola:

```
"REG67: il campo giustificazione aggiudicazione diretta \u00e8 obbligatorio se il tipo di procedura \u00e8 Negoziata senza previa indizione di gara"
```

con il seguente sorgente:
```
appalto.datiBaseProcedura != null and appalto.datiBaseProcedura.tipoProcedura != null and appalto.datiBaseProcedura.tipoProcedura.codice = \"neg-wo-call\" and (appalto.datiBaseProcedura.giustificazioneProceduraAccelerata = null or appalto.datiBaseProcedura.giustificazioneProceduraAccelerata=\"\")
```

Fa riferimento al seguente campo
```
"appalto.datiBaseProcedura.giustificazioneProceduraAccelerata"
```

Questo è vero per tutte le schede P2/P3  che **non** hanno il campo `giustificazioneProceduraAccelerata`, rendendo quindi impossibile la compilazione di procedure `Negoziata senza previa indizione di gara`. Queste schede sono altresì **non** dotate di `eform` dal quale potenzialmente ricavare l'informazione mancante.

Il problema è potenzialmente presente anche in alcune P1/P4, ma non ho modo di verificarlo in quanto ANAC non fornisce documentazione su come i dati `eform` vengono aggregati ai campi `anacForm`.

**Comment by supportoAnac** [comment]
Segnalazione corretta.  Col prossimo rilascio del modello dati la regola verrà eliminata dalle schede dove non è presente il campo _giustificazioneProceduraAccelerata_.
