### ISSUE TITLE
Tipologica strumentiSvolgimentoProcedure non aggiornata

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1232]
Salve, la tipologica strumentiSvolgimentoProcedure, in particolare codice 5 risulta non essere aggiornata. Infatti `dataFine` dovrebbe essere `null` mentre è ancora `"2023-12-31T00:00:00Z"`

https://github.com/anticorruzione/npa/blob/f1ac8cb5339162382b3325da3553bb57a8ea266f/docs/modello-dati/tipologiche/strumentiSvolgimentoProcedure.json#L44

E' possibile aggiornare la tipologica anche nel repo?

**Comment by supportoAnac** [comment]
Tipologica strumentiSvolgimentoProcedure.json aggiornata col rilascio del 12/03/2024.
