### ISSUE TITLE
[ARIA SPA] Richiesta di supporto ipotesi workaround RETTIFICA EFORMS - aggiornamento PCP

### ISSUE THREAD

**Issue by AnrivaDeloitte** [anticorruzione/npa#1234]
Buongiorno,
 
Nelle more di ultimare gli sviluppi e rendere disponibile quanto prima la funzionalità dedicata alla RETTIFICA di un avviso all'interno della Piattaforma di ARIA S.p.A., come è possibile procedere per modificare un dato inserito in un eFORM di pubblicazione di un bando, regime ordinario (E16) che risulta pubblicato sulla G.U.U.E.?
 
Abbiamo verificato che è possibile procedere utilizzando eNotice2 avvalendosi della funzionalità "IMPORTA DA TED", tramite la quale è possibile importare un formulario pubblicato sulla G.U.U.E. e rettificarlo, richiedendone la pubblicazione direttamente tramite TED.
 
Tuttavia, chiediamo vostro supporto per confermare il workaround e capire come poter allineare la PVL manutenuta da ANAC se si procede con la rettifica direttamente su eNotice2.
 
Grazie

**Comment by supportoAnac** [comment]
Il servizio di rettifica-avviso, per poter modificare avvisi già pubblicati, è disponibile sia in ambiente di qualificazione che di produzione.
