### ISSUE TITLE
Issue su REG97 - su scheda P2.19 che non prevede Eform

### ISSUE THREAD

**Issue by paolastoroni** [anticorruzione/npa#1236]
Gara_BT131 - 83782/Scheda P2.19
riscontriamo sulla scheda P2.19 la issue REG97 (REG97 - Inserire solo uno tra i campi oraScadenzaPresentazioneOfferte e scadenzaPresentazioneInvito. In presenza di eForm verificare i campi EndDate (BT-131, BT-1311, BT-630).). l'errore si presenta nel momento in cui si stacca il CIG (la P2.19 non prevede l'Eform ma solo l'AnacForm ed il messaggio dice di andare a modificare i campi all'interno dell'Eform).

![3_p](https://github.com/anticorruzione/npa/assets/25659835/20e9098f-4bff-45b9-ae40-75af420ad700)

**Comment by supportoAnac** [comment]
L'errore comprende le informazioni sia per le schede con eForm che senza eForm. 
Nel caso della P2_19, senza eForm, i campi da verificare sono: _lotti.datiBaseTerminiInvio.
oraScadenzaPresentazioneOfferte_ e _lotti.datiBaseTerminiInvio.scadenzaPresentazioneInvito_.
