### ISSUE TITLE
Scheda CO1 - Scheda di conclusione - mancanza regola dmn per CIG / idContratto 

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1239]
Originariamente per la scheda CO1 era previsto come obbligatorio il campo idContratto.
Successivamente sono state introdotte delle modifiche prevedendo nell'orchestratore che si possa inserire una scheda CO1 anche in assenza di una scheda SC1 e, di conseguenza, senza idContratto.
Tali modifiche hanno portato ad inserire nella scheda CO1 sia il CIG sia l'idContratto, entrambi facoltativi, consentendo di fatto la possibilità di inserire la CO1 sia in presenza sia in assenza di contratto.
Ho notato che, correttamente, nella scheda i due campi sono facoltativi, ma mi aspettavo che nelle regole DMN fosse presente la richiesta di obbligatorietà di almeno uno dei due. Tale regola non esiste e, quindi, per quello che mi risulta è possibile inserire una CO1 in assenza sia del CIG sia dell'idContratto  creando una situazione che ritengo non gestibile.
In sintesi ritengo che vada inserita nelle regole per la CO1 la regola che almeno uno dei campi CIG e idContratto debba essere valorizzato.

**Comment by obigno77** [comment]
Problema risolto il 20/03 con apposita fix
