### ISSUE TITLE
[BLK] Avvisi rimasti in stato "In attesa di pubblicazione"

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1243]
Dalla nostra piattaforma di eprocurement  in ambiente di collaudo sono stati creati in questi giorni, più precisamente dal 29 Febbraio fino al 5 marzo, una serie di procedure di gara.
Per ognuna di queste è stata fatta richiesta di pubblicazione ma, ad oggi, risultano ancora in attesa di pubblicazione.
Per ognuna abbiamo indicato la data in cui è stata richiesta la pubblicazione.

idAppalto: 64ce0e0f-dbe6-43bd-8c59-41baa7adb8a5
idAvviso: 1c96b8c4-7c13-42d7-a1fb-d6efa6a489a4
data: 2024-02-29

idAppalto: e368c203-790c-497f-8641-ab039a91d1c5
idAvviso: aa68b213-cefa-4283-bdda-a7b7dec299d3
data: 2024-03-01

idAppalto: c664bb1e-7d50-4bb7-85ca-3e24f035bf4b
idAvviso: 786519e4-ed49-4795-a4bc-caf2575f4fa9
data: 2024-03-05

Si chiedono informazioni su quali siano i tempi di processamento delle richieste di pubblicazione da parte degli scheduler
e come mai lo stato di pubblicazione di questi appalti non sia ancora cambiato.

Questa situazione non ci consente di chiudere alcuni collaudi e rallenta altre attività di sviluppo e test.
Fino a poco tempo fa i ritorni per le richieste di pubblicazione in ambiente di collaudo avvenivano grosso modo in 24 ore, ora ci paiono bloccati.
Stante tale situazione in ambiente di collaudo,  si chiede quale sia la situazione dei ritorni delle richieste di pubblicazione in ambiente di produzione, atteso che nella prossima settimana dovremo avviare delle procedure di gara tramite la piattaforma.
In altri termini, possiamo confermare l'avvio dei procedimenti o è necessario ripianificarli?

**Comment by supportoAnac** [comment]
L’anomalia è stata segnalata al TED e  dipende dal sistema di preview.
La traccia della issue è
[14. The Publications Office may provide a testing environment (currently called the Preview environment) with a similar configuration to the production environment but with no guarantee of features, data or availability.](https://enotices2.preview.ted.europa.eu/cookies-legal-notice#:~:text=14.%20The%20Publications%20Office%20may%20provide%20a%20testing%20environment%20(currently%20called%20the%20Preview%20environment)%20with%20a%20similar%20configuration%20to%20the%20production%20environment%20but%20with%20no%20gurantee%20of%20features%2C%20data%20or%20availability.)
