### ISSUE TITLE
[BLK][Maggioli] Rettifiche successive alla prima

### ISSUE THREAD

**Issue by ManuelBridda** [anticorruzione/npa#1246]
Buongiorno, in riferimento alla chiamata di "rettifica-avviso", abbiamo riscontrato un'incongruenza nel sistema di servizio PCP. Al momento, il sistema restituisce l'errore **ERR4: errore nella conversione della scheda secondo il json schema definito** durante il tentativo di effettuare una **seconda rettifica** dell'avviso.

Tale errore sembra essere slegato dalla struttura json, poiché il body della seconda rettifica risulta identico a quello della prima, ad eccezione dei campi "idAvviso" (popolato con 'idNuovoAvviso", ottenuto dalla precedente operazione di rettifica) e "oraScadenzaPresentazioneOfferte" (il dato da rettificare).

L'errore è del servizio o c'è effettivamente una differenza nella costruzione della richiesta di una rettifica successiva alla prima rispetto a quanto sopra illustrato? 

Allego id della transazione di riferimento
"govwayTransactionId": "e7e795da-df91-11ee-9b99-0050568e9679"

**Comment by supportoAnac** [comment]
Si chiede gentilmente di fornire maggiori informazioni (idScheda, idAppalto, etc ) per effettuare una verifica.

**Comment by ManuelBridda** [comment]
"idAppalto": "f91a57ba-a081-4fbf-87e8-cf8334cfd2a9"
"idAvviso" (originale): "a2482253-b5fe-4e26-8242-ccc42e16e3af"
"idAvviso" (post-rettifica): "cbacba98-a0e5-4ff4-bb94-3a1115a577e7"

"idScheda" (originale): "d3b500f2-fa15-43c4-8168-77367a1d61e3"
"idScheda" (post-rettifica): "93324a46-cb46-411a-b95e-a6d20698e920"

scheda P2_16

**Comment by ManuelBridda** [comment]
Aggiornamento del 21/03/2024:
Da oggi l'errore ERR4 è stato sostituito dall'**ERR99: popolare in modo alternativo idContratto o cig nel body della scheda** 
Probabilmente è correlato alla [fix](https://github.com/anticorruzione/npa/issues/1239#issuecomment-2012319107) rilasciata in data 20/03/2024

La prima rettifica continua a funzionare, mentre le rettifiche successive alla prima generano errori.

Allego id della transazione di riferimento della rettifica successiva alla prima che va in errore
govwayTransactionId":  "0798589a-e792-11ee-9ec6-0050568e08b3"
