### ISSUE TITLE
[BLK][Maggioli] Mancata valorizzazione del campo "idAvviso"

### ISSUE THREAD

**Issue by ManuelBridda** [anticorruzione/npa#1247]
Buongiorno, come da titolo segnalo la mancata valorizzazione del campo "idAvviso" nella response della chiamata "esito-operazione" con "tipoOperazione": "SC_CONF". La chiamata è inererente a una scheda A2_29 e la response ha "esito": "OK"

```
"data": {
        "listaEsiti": [
            {
                "idNuovoAvviso": null,
                "dataControllo": "2024-03-11T14:09:37.669Z",
                "idPianificazione": null,
                "idContratto": null,
                "codiceScheda": "A2_29",
                "esito": {
                    "codice": "OK",
                    "idTipologica": "esito"
                },
                "idAvviso": null,
                "errori": null,
                "idScheda": "ccf6d39a-44a7-4cbc-9dae-f5b7f90d3d5b",
                "dettaglio": {
                    "codice": "SC_CONF",
                    "idTipologica": "esitoOperazione"
                },
                "idNuovaScheda": null,
                "codiceNuovaScheda": null,
                "tipoOperazione": {
                    "codice": "SC_CONF",
                    "idTipologica": "tipoOperazione"
                },
                "idAppalto": "9bc03958-b549-4f20-9813-71897c1c92c3"
            }
        ]
}
```
Riporto l'id della transazione
"govwayTransactionId": "c1748c7f-dfa6-11ee-9b99-0050568e9679"

Nota: anche la chiamata AV_PUBB non fornisce risultati riferiti alla scheda A2_29 all'interno dell'array "listaEsiti"

**Comment by supportoAnac** [comment]
È stata effettuata una operazione di conferma-scheda, che ha restituito correttamente un'idScheda. 
Si ricorda che la operazione di pubblica-avviso, che restituisce un'idAvviso (differente da idScheda), deve essere invocata in maniera indipendente dalla operazione di conferma-scheda. Solo così si genera un avviso associato alla scheda di aggiudicazione appena confermata, che a sua volta transiterà inizialmente nello stato IN_ATT_PUB e successivamente, una volta pubblicato su PVL, nello stato PUBB. 
Si ricorda altresì che tutti questi stati possono essere verificati con il servizio stato-avviso per gli avvisi, stato-appalto per gli appalti, lotti e contratti.

**Comment by ManuelBridda** [comment]
Ho un paio di domande: 
1. da quando per una scheda di aggiudicazione (A2_29) sarebbe necessario invocare manualmente la 'pubblica-avviso'? 
2. Anche il punto 1. fosse superato, con quale idAvviso dovrei effettuare la chiamata 'pubblica-avviso' che richiede in input  un idAvviso?

![image](https://github.com/anticorruzione/npa/assets/49234039/bf4bcf99-3b5b-49eb-841f-f42abd6b8aae)

**Comment by ManuelBridda** [comment]
Aggiornamento: 
Il problema sembra essere legato al popolamento a **null** del campo 'aggiudicazioni' nell'oggetto 'anacForm' inviato
