### ISSUE TITLE
/recupera-elenco-tipologiche - Status 400, "Received request is not conform to the required interoperability profile."

### ISSUE THREAD

**Issue by gelso** [anticorruzione/npa#1252]
Buongiorno, sulla piattaforma di collaudo la chiamata a /recupera-elenco-tipologiche, restituisce l'errore

```json

{'detail': 'Received request is not conform to the required interoperability '
           'profile',
 'govway_id': "58924976-12b4-11ef-9ec6-0050568e08b3",
 'status': 400,
 'title': 'InteroperabilityInvalidRequest',
 'type': 'https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html'}

```

Ho cercato di fare il possibile per individuare il problema ma senza un messaggio di errore più preciso purtroppo non riesco a procedere.

Grazie mille per l'aiuto e buona giornata
Andrea

N.B. 
1. Seguo la procedura indicata nel manuale operativo di interoperabilità (https://docs.pagopa.it/interoperabilita-1/) e sintetizzata in questo [commento](https://github.com/anticorruzione/npa/issues/352#issuecomment-1765975709): preparo la client-assertion, includendovi purpose_id e l'hashing del JWS (nel digest.value); il debugger non rileva errori. Dall'endpoint di PDND, a cui passo la client assertion, ottengo il Bearer token.

**Comment by obigno77** [comment]
Questi gli errori nel contenuto del token
[GOVWAY-661] [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2024-05-15_14:41:48.000')
[GOVWAY-814] [Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido
[GOVWAY-1367] [Header 'Authorization'] Token non contiene il claim 'purposeId'
[GOVWAY-1367] [Header 'Agid-JWT-TrackingEvidence'] Token non contiene il claim 'purposeId'
