### ISSUE TITLE
Avvisi appesi in stato CREATO

### ISSUE THREAD

**Issue by scalabrese11** [anticorruzione/npa#1263]
Buongiorno,

stiamo riscontrando diversi problemi in fase di pubblicazione di appalti P2_16;
nello specifico notiamo che lo stato dell'avviso permane in "CREATO" nonostante la pubblicazione sia avvenuta da diversi giorni, di seguito un esempio:

StatoAvvisoResponse {
    class BaseResponse {
        instance: null
        status: 200
        title: OK
        detail: Operazione Effettuata
        type: about:blank
    }
    statoAvviso: class StatoAvvisoType {
        idAvviso: c0282b32-e9fd-4d25-b4e5-46506e181452
        idAppalto: 5e3b6ea7-65dd-4198-bf34-2808bf5a91f3
        idPianificazione: null
        dataControllo: 2024-03-08T11:12:30.584Z
        stato: class StatoAvvisoEnum {
            class TipologicaSchemaType {
                idTipologica: statoAvviso
                codice: CREATO
            }
        }
    }
}

Grazie.

**Comment by supportoAnac** [comment]
Da verifiche effettuate, l'appalto è nello stato confermato. L'avviso è stato predisposto ma per una P2_16 è necessario effettuare l'operazione di pubblica-avviso.
