### ISSUE TITLE
SC1 - Impossibile confermare per ERR9999

### ISSUE THREAD

**Issue by ctav8** [anticorruzione/npa#1264]
Buongiorno,
oggi non riusciamo più a confermare schede SC1 per ERR9999 anche inviando gli stessi dati usati per confermare schede SC1 nei giorni scorsi con successo.

Di seguito alcuni dettagli sulle chiamate:

idAppalto: d48af674-07ce-4c93-b35e-40270ac564fd
idScheda SC1: db911824-07d6-49f6-ab4b-a2962a08d8ce
Dettagli esito operazione:
GovWay-Message-ID: 50bb877a-5699-4557-a833-1dbf52d6b41d
GovWay-Transaction-ID: fa9c91ef-e142-11ee-9ec6-0050568e08b3

idAppalto: 6683655c-29ed-406f-8607-0f3c2f1d413f
idScheda SC1: fab8877e-250d-4e27-a16d-a01331235cd4
Dettagli esito operazione:
GovWay-Message-ID: 8cf829bb-7e8e-4622-8a0e-bd8fd60ee9a5
GovWay-Transaction-ID: 5c72e9db-e142-11ee-9ec6-0050568e08b3

Potete verificare? È capitato anche a qualcun altro?
Grazie.

**Comment by mariottiDPA** [comment]
confermo, anche noi stessa cosa (DigitalPA)

**Comment by fabiovenditti** [comment]
anche noi riscontriamo lo stesso problema.
Avendo un rilascio in produzione questa settimana vorrà dire che faremo rilascio senza poter fare i test di regressione, visto che in produzione sembra che funzioni

**Comment by supportoAnac** [comment]
Fix in qualificazione ed esercizio.
