### ISSUE TITLE
[Consip][BLK] A7_1_1 - errore notice type non coerente

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1266]
salve,
abbiamo provato a trasmettere una A7_1_1 passando in input un eForm 25.
l'orchestratore mostra che per questa scheda si possono mandare i seguenti eform: 25, 26, 27, 28.
Tuttavia, il servizio restituisce **ERR2 - Notice non coerente con la scheda in input**.
Successivamente, abbiamo provato anche con eForm 26, 27 e 28 e riscontriamo lo stesso errore; in pratica, non è possibile inviare questa scheda in alcun modo.
potete verificare?

GovWay-Message-ID=[7a80b409-091a-4229-8e13-787d2d405640]
GovWay-Transaction-ID=[f2d9a1d7-e156-11ee-9b99-0050568e9679]
grazie

**Comment by obigno77** [comment]
Problema risolto il 20/03 con apposita fix
