### ISSUE TITLE
Richiesta urgente analisi per appalti non pubblicati

### ISSUE THREAD

**Issue by scalabrese11** [anticorruzione/npa#1268]
Buongiorno,

chiediamo supporto per i seguenti appalti che non passano in stato "pubblicato" ma restano "in attesa di pubblicazione" o addirittura in stato "creato".
Le tipologie impattate sono P1_16 e P2_16.

ID_APPALTO						 | ID_AVVISO					   | STATO_AVVISO| TIPO_SCHEDA | DATA_CREAZIONE

1. bbb32682-0bf8-4491-80fb-55c7f3f671c9 | e7ccf4c2-2999-4286-8fef-ea79758626bf | IN_ATT_PUBB | P1_16 | 2024-03-13 15:29:49
2. f15a72fe-f380-40a0-b8f6-347226887b67 | 99e8963d-2bf9-4298-b8b6-77fee30cbdbb | IN_ATT_PUBB | P1_16 | 2024-03-13 15:14:36
3. 97187031-cf1a-441f-b4e6-1510d4f93f81 | 7f402703-d019-44e7-b311-25db9c0717b5 | IN_ATT_PUBB | P1_16 | 2024-03-13 12:57:55
4. 35d3253a-832f-4398-a2fe-f8762aeb11e5 | ae3c048b-a902-4723-b5fa-74bf5ec7c995 | IN_ATT_PUBB | P1_16 | 2024-03-13 10:57:39
5. e8ab50d0-eab5-4605-a754-489634273e3b | 8e858616-afb4-47da-9dd5-2960bdf15913 | IN_ATT_PUBB | P1_16 | 2024-03-12 17:32:5
6. 9e26ce3b-3a7f-4eb9-943f-5b34aa734a12 | c1c05b55-b0bd-44c2-a44e-30e61443a673 | IN_ATT_PUBB | P1_16 | 2024-03-12 12:35:05
7. df97ffe2-085d-47e5-bc67-d11d2f443dc3 | 217d5064-7142-4a85-9c70-08a66999b4f0 | IN_ATT_PUBB | P1_16 | 2024-03-11 11:24:43
8. be389824-4970-48aa-b4a9-0117adee0016 | 669cea32-9e5f-4e0e-b81b-e086d6223f8e | IN_ATT_PUBB | P1_16 | 2024-03-08 13:19:10
9. 5e3b6ea7-65dd-4198-bf34-2808bf5a91f3 | c0282b32-e9fd-4d25-b4e5-46506e181452 | CREATO    | P2_16 | 2024-03-08 10:57:29
10. 4b0fd30b-0a4a-472f-afb2-a3a68e25e172 | d97859c5-158a-428d-b56c-ff0a547494af | IN_ATT_PUBB | P1_16 | 2024-03-07 15:52:11
11. 837b7ce4-4fd1-432a-b361-aa8d59f1b099 | 919dbd6a-ef53-44b3-8958-7046c0de8e6c | CREATO  | P2_16 | 2024-03-06 10:08:52
12. e20ff5dd-7a17-49bf-8cb5-7e32059b2595 | 4899fd12-52b2-4980-92f0-61b379483bf7 | IN_ATT_PUBB | P1_16 | 2024-03-05 18:43:28
13. 8a18fe84-4d5a-4f68-a51b-ddb370f734d9 | e2decced-bd94-4762-80b9-2fbcae6dff9d | CREATO	  | P2_16 | 2024-03-05 17:17:26
14. 3b5497ff-33a1-4c5f-8fee-d4ca21304d1e | ea71ca45-cbb6-46e3-af87-7f25a26ce689 | IN_ATT_PUBB | P1_16 | 2024-03-05 15:25:00
15. a58677d8-8942-40fa-9ee6-1595aaca2837 | 46d3c4d5-997e-4cb3-8ed9-e1b88d6bb583 | CREATO  | P2_16 | 2024-03-01 17:28:17
16. c9511558-4cff-41ca-b952-80b6491db5ca | 3fe1c235-3c05-4e73-9bca-1d5a6a8a8933 | IN_ATT_PUBB | P1_16 | 2024-02-26 12:27:02

In attesa di riscontro per poter risolvere.
Grazie.

**Comment by supportoAnac** [comment]
L’anomalia è stata segnalata al TED e  dipende dal sistema di preview.
La traccia della issue è
[14. The Publications Office may provide a testing environment (currently called the Preview environment) with a similar configuration to the production environment but with no guarantee of features, data or availability.](https://enotices2.preview.ted.europa.eu/cookies-legal-notice#:~:text=14.%20The%20Publications%20Office%20may%20provide%20a%20testing%20environment%20(currently%20called%20the%20Preview%20environment)%20with%20a%20similar%20configuration%20to%20the%20production%20environment%20but%20with%20no%20gurantee%20of%20features%2C%20data%20or%20availability.)

**Comment by scalabrese11** [comment]
Non tutti gli appalti segnalati sono di Ted, alcuni sono P2_16 che non vanno a Ted
