### ISSUE TITLE
[TOSCANA/BOLZANO] Servizi FVOE

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#1269]
Buongiorno,
chiedo gentilmente un riscontro per i seguenti quesiti

1) Il servizio richiedi accesso sembra che sia a livello di gara dato che viene richiesto solo l'ID Appalto. Confermate? 
2) All'interno del contesto dei servizi FVOE esiste un servizio utilizzabile per scaricare tutti i documenti del OE per una singola gara?
3) Il servizio recupera-documento-fvoe come da paragrafo 11 del documento https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md, con una unica chiamata consente di recuperare sia i dati che il documento in formato digitale?

Grazie

**Comment by supportoAnac** [comment]
1) ESATTO La richiesta di accesso è a livello di Appalto. 
2) Non esiste un operazione massiva che permetta lo scarico di tutti I documenti.
3) ESATTO. Come da documentazione é presente l'operazione recupera-documento che permette lo scarico dei metadati e del binario.
