### ISSUE TITLE
Contesto APPALTO - Modifica avviso

### ISSUE THREAD

**Issue by sfala** [anticorruzione/npa#127]
Non potendo modificare l'appalto dopo aver invocato il servizio di /conferma-appalto ma potentdo invocare il servizio /modifica-avviso, si chiede se l'invocazione del servizio /modifica-avviso determina in un sol colpo:
- l'aggiornamento delle infromazioni detenute da ANAC in merito all'appalto
- l'aggiornamento delle informazioni presenti sulla piattaforma di pubblicità nazionale
- l'aggiornamento delle informazioni presenti su TED (se previsto per il tipo di appalto)

**Comment by supportoAnac** [comment]
Si rimanda alla seguente Issue: 
https://github.com/anticorruzione/npa/issues/5
