### ISSUE TITLE
Tipologica codiceScheda non aggiornata all'orchestratore in vigore

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#1270]
Buongiorno, si segnala che la tipologica https://github.com/anticorruzione/npa/blob/9b24eb41eec2271cc0928362a325f00e244ba352/docs/modello-dati/tipologiche/codiceScheda.json non è aggiornata rispetto all'ultimo orchestratore in vigore. Infatti, ad esempio, la scheda P7_2 è ora utilizzabile sia sopra che sottosoglia, ma la tipologica di cui sopra indica ancora esclusivamente "Scheda di procedura negoziata senza bando sottosoglia".
Sarebbe possibile aggiornare la tipologica all'ultimo orchestratore?

**Comment by supportoAnac** [comment]
Si ringrazia per la segnalazione, e si invita nel frattempo a fare riferimento all'orchestratore.
