### ISSUE TITLE
rettifica avviso per schede di post pubblicazione (scheda A2_29)

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1272]
Buongiorno,

se un utente invia per errore dei dati con la scheda di aggiudicazione è possibile fare una rettifica dell'avviso inerente la scheda A?

in particolare, ci è stato segnalato da un utente che per errore nella scheda A2_29 è stato indicato un aggiudicatario sbagliato. sarebbe possibile per l'utente fare la rettifica dell'avviso della scheda A?

come dovrebbe procedere altrimenti l'utente?

Grazie

**Comment by supportoAnac** [comment]
Se è stato pubblicato l'avviso relativo alla scheda A2_29, è sicuramente possibile invocare il servizio rettifica-avviso. In caso di dubbi sulla natura dei campi modificabili, si invita ad aprire una nuova segnalazione.
