### ISSUE TITLE
[Consip] A2_30 - ERR2 - La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1273]
Abbiamo inviato una scheda P2_17 e successivamente S2. 
la scheda S2 non necessita di pubblicazione per cui si dovrebbe poter mandare la A2_30 senza problemi, tuttavia, riscontriamo sul crea-scheda il seguente errore:
**ERR2 - La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata**

potete verificare?

"idAppalto":"60e852b8-d5d9-4166-a531-0a8acb3e1e20"
GovWay-Message-ID=[adf4d244-788d-4ab6-9ce4-9ee9aacd9b18]
GovWay-Transaction-ID=[6cf4939c-e221-11ee-9b99-0050568e9679]

**Comment by supportoAnac** [comment]
Si prega gentilmente di fornire il payload della scheda A2_30 oggetto della segnalazione.

**Comment by lauralu1993** [comment]
di seguito il payload:
{
   "idAppalto":"60e852b8-d5d9-4166-a531-0a8acb3e1e20",
   "scheda":{
      "codice":{
         "idTipologica":"codiceScheda",
         "codice":"A2_30"
      },
      "versione":"1.0",
      "body":{
         "type":"SchedaA230Type",
         "anacForm":{
            "appalto":{
               "motivoUrgenza":{
                  "idTipologica":"motivoUrgenza",
                  "codice":"1"
               },
               "relazioneUnicaSulleProcedure":false,
               "opereUrbanizzazioneScomputo":false,
               "datiBaseProcedura":{
                  
               }
            },
            "aggiudicazioni":[
               {
                  "cig":"I0029682D2",
                  "offertePresentate":[
                     {
                        "idPartecipante":"e06c7db3-ec23-4ae4-99a5-7944bd207fbe",
                        "importo":2.0,
                        "aggiudicatario":false,
                        "ccnl":"22222",
                        "offertaMaggioreSogliaAnomalia":false,
                        "impresaEsclusaAutomaticamente":false,
                        "offertaAnomala":false
                     }
                  ],
                  "numeroOfferteAmmesse":2
               },
               {
                  "cig":"I00296A478",
                  "offertePresentate":[
                     {
                        "idPartecipante":"e06c7db3-ec23-4ae4-99a5-7944bd207fbe",
                        "importo":2.0,
                        "aggiudicatario":false,
                        "ccnl":"22222",
                        "offertaMaggioreSogliaAnomalia":false,
                        "impresaEsclusaAutomaticamente":false,
                        "offertaAnomala":false
                     }
                  ],
                  "numeroOfferteAmmesse":2
               },
               {
                  "cig":"I0029693A5",
                  "offertePresentate":[
                     {
                        "idPartecipante":"e06c7db3-ec23-4ae4-99a5-7944bd207fbe",
                        "importo":2.0,
                        "aggiudicatario":false,
                        "ccnl":"22222",
                        "offertaMaggioreSogliaAnomalia":false,
                        "impresaEsclusaAutomaticamente":false,
                        "offertaAnomala":false
                     }
                  ],
                  "numeroOfferteAmmesse":2
               }
            ]
         }
      }
   }
}
