### ISSUE TITLE
[Toscana/Bolzano] - SC1 - ERR9999

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1278]
Salve,
Mi accodo alla issue #1264 . 
Anche noi stiamo riscontrando problemi in ambiente di test per l'esito-operazione della scheda SC1 la quale restituisce ERR9999

Di seguito i json:

[SC1_esito-operazione_output.json](https://github.com/anticorruzione/npa/files/14634392/SC1_esito-operazione_output.json)
[SC1_crea-scheda_output.json](https://github.com/anticorruzione/npa/files/14634393/SC1_crea-scheda_output.json)
[SC1_crea-scheda_input.json](https://github.com/anticorruzione/npa/files/14634394/SC1_crea-scheda_input.json)

Ci potreste dare supporto?

**Comment by supportoAnac** [comment]
La fix è in linea in qualificazione ed esercizio.
