### ISSUE TITLE
ERR41 - Errore generico per P1_16

### ISSUE THREAD

**Issue by teslb** [anticorruzione/npa#1279]
Buongiorno,

     per la scheda P1_16, nella conferma dell'appalto con Id 89e6bc03-0e6b-4db4-bbf3-4a0ad74d8fb3 riceviamo un "ERR41 - Errore generico"

Si chiede una verifica urgente poiché l'errore è bloccante per collaudi in corso.

Grazie e saluti,

**Comment by supportoAnac** [comment]
Da verifiche effettuate in data odierna il servizio conferma-appalto risulta funzionare correttamente per la tipologia di scheda indicata.  Si invita quindi gentilmente a controllare di nuovo i campi dell'eForm e dell'AnacForm compilati, ed invocare di nuovo  eventualmente il servizio di modifica-appalto qualora si riscontrassero incongruenze.

**Comment by teslb** [comment]
Come è possibile risalire alla causa dell'errore se la risposta è solo quella di **Errore generico** ?

**Comment by supportoAnac** [comment]
In corso di verifica.
