### ISSUE TITLE
scheda AD4

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#128]
La scheda AD4 presenta sul file xls dell'orchestratore il valore SI su ESPD richiesto, mentre sulla documentazione aperta con swagger in occorrenza dell'ESPD non c'è l'asterisco che indica di solito l'obbligatorietà. Per AD4 l'ESPD è obbligatorio o no?

**Comment by supportoAnac** [comment]
l'ESPD è obbligatorio per ogni procedura visto che è indispensabile per l'accesso a FVOE.
