### ISSUE TITLE
[ARIA SPA] campi modificabili con la rettifica

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1280]
Buongiorno,

a seguito del riscontro dato alla #1272, si richiede se è disponibile un elenco di campi che possono essere rettificati tramite il servizio di rettifica avviso (sia per schede di indizione es P2_16 che per schede post pubblicazione es A2_29).
Sia per ANACFORM che per eventuale eFORM.

Grazie

**Comment by SoricchioHRS** [comment]
Salve, 
sarei interessato a comprendere la questione della Rettifica Avviso sia in ANACFORM, sia in EFORM.
La possibilità di una rettificia di avviso è demandata sempre alla PAD certificata?

**Comment by obigno77** [comment]
Non sono sicuramente modificabili il tipo di avviso, il numero dei lotti e l'elenco delle organizzazioni coinvolte.
Sono sicuramente modificabili gli importi e la data di scadenza per la presentazione delle offerte.
E' stato chiesto al TeD di avere un maggiore dettaglio in merito ma siamo stati rinviati ai gruppi di discussione dove non abbiamo trovato una risposta univoca.

@SoricchioHRS la risposta alla domanda è SI
