### ISSUE TITLE
[BLK][Maggioli] Scheda A1_32 incongruenza errore segnalato rispetto al json

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1284]
Salve,
inviando una A1_32 mi viene segnalato un errore bloccante incongruente rispetto allo schema
 e al json inviato di cui allego la parte significativa
  (anche valorizzando l'unico attributo presente nella struttura appalto il risultato non cambia).
 Come posso procedere? grazie

IdAppalto:7dd42119-1988-4a00-96b7-211b66923cf0
ERR4: errore nella conversione della scheda secondo il json schema definito: $.anacForm.appalto: is missing but it is required
Data evento: 19/03/2024 12:47:23
Govway Transaction Id: 9437247b-e5e4-11ee-9ec6-0050568e08b3

json:
{
"appalto": {
"modalitaRiaggiudicazioneAffidamento": null
},
"aggiudicazioni": [
{
"cig": "I00274D605",
"offertePresentate": [
{
"idPartecipante": "1c724624-3ed4-4cc1-9a01-32cbbfe88f1c",
"importo": 285095.29667,
"aggiudicatario": true,
"ccnl": "SFTR",
"posizioneGraduatoria": 1,
"offertaEconomica": 0.89,
"offertaQualitativa": null,
"offertaInAumento": null,
"offertaMaggioreSogliaAnomalia": null,
"impresaEsclusaAutomaticamente": false,
"offertaAnomala": false
}
],
"numeroOfferteAmmesse": 1,
"nImpreseEscluseInsufficientiGiustificazioni": null,
"quadroEconomicoConcessioni": {
....

**Comment by supportoAnac** [comment]
Segnalazione in corso di verifica.

**Comment by sfala** [comment]
Riscontriamo la medesima problematica

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>abbiamo effettuato dei test e la scheda è stata creata correttamente senza errori di json schema.</p>

<p>La invitiamo quindi a riprovare nuovamente.</p>

<p>Restiamo a disposizione per qualsiasi necessità.</p>

<p>Cordiali saluti</p>
