### ISSUE TITLE
[CONSIP] BLK-SC1- ERR9999 -ERRORE GENERICO 

### ISSUE THREAD

**Issue by LucariniPaola** [anticorruzione/npa#1285]
Abbiamo creato un appalto e inviato in ordine le seguenti schede : P2_10,S2, A2_29. 
Abbiamo tentato di trasmettere la SC1 ma abbiamo riscontato il seguente errore : ERRR 9999 .ERRORE GENERICO 
Di seguito i dettagli : 
"GovWay-Message-ID":["75d23582-3472-4055-9a1b-9234e1aea3bf"]
"GovWay-Transaction-ID":["d277f322-e5e2-11ee-9b99-0050568e9679"]
 
ID APPALTO : e9383002-5973-48c1-b23e-d82b08c74811

**Comment by supportoAnac** [comment]
Fix in qualificazione ed esercizio.
