### ISSUE TITLE
SC1 - ERR9999 -ERRORE GENERICO - URGENTE / BLOCCANTE

### ISSUE THREAD

**Issue by teslb** [anticorruzione/npa#1288]
Buongiorno,

    ci associamo alle issue che sono state aperte in questi giorni poiché il problema necessita un' URGENTE risoluzione visto l'impatto sui collaudi in corso.

idAppalto 'bb4fe461-c2d2-41c0-94f4-993206f979dc'

govway-message-id:'a21b24a5-35f7-4452-a921-90f601fd32f9'
govway-transaction-id:'a37118cc-e6ae-11ee-9b99-0050568e9679'

Si chiede una risoluzione del problema quanto prima possibile.

Grazie e saluti

**Comment by SoricchioHRS** [comment]
Mi aggancio, come Amministratore della PAD in uso alla CUc del Gruppo Sistemi Salerno (PAD certificata Traspare - L. & G. Solution s.r.l.) che l'errore 9999 mostrato dal modulo interoperabilità, ad esempio all'invio di un avviso di rettifica, se il file xml generato viene direttamente inviato come rettifica dell'avviso dalla piattaforma TED (enotices 2.0), esso non viene restiuito ed, anzi, l'avviso viene anche pubblicato.

**Comment by SoricchioHRS** [comment]
Confermo che dalla piattaforma TED l'avviso di rettifica viene correttamente pubblicato, invece, tramite pcp l'avviso non viene pubblicato per errore generico. La domanda è la seguente : perché il file xml se è caricato direttamente su TED funziona se è caricato con l'interoperabilità di PCP, ESSO viene pubblicato?

**Comment by supportoAnac** [comment]
La problematica è stata corretta, la fix è in linea.
