### ISSUE TITLE
Servizio "Modifica Avviso"

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#129]
Buongiorno,

Il servizio di "Modifica avviso" dovrebbe permettere la modifica dei dati dell'appalto.
Quali campi dell'appalto è possibile modificare tramite il servizio di "Modifica avviso"?

Grazie

**Comment by supportoAnac** [comment]
Si rimanda alla seguente Issue: 
https://github.com/anticorruzione/npa/issues/64
