### ISSUE TITLE
[ARIA SPA] Possibilità di rettifica - momento in cui è disponibile

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1290]
Buongiorno,

rispetto alla possibilità di rettificare gli avvisi, sono presenti dei vincoli/controlli rispetto alla possibilità dei momenti in cui fare la rettifica?

ad esempio:
- sarebbe possibile per gli utenti inviare una rettifica dell'avviso di pubblicazione gara anche dopo il termine ultimo per la presentazione delle offerte?
- sarebbe possibile inviare per gli utenti una rettifica dell'avviso di pubblicazione quando è già stato pubblicato l'avviso di un aggiudicazione per un lotto?

Sono stati previsti dei controlli bloccanti in tal senso o la correttezza del momento in cui inviare una rettifica è demandata alla SA? Sia per schede che prevedono eFORM sia per schede senza.

Grazie

**Comment by obigno77** [comment]
Da specifiche TeD non è possibile rettificare gli avvisi dopo la scadenza del termine della presentazione delle offerte, a maggior ragione dopo l'avviso di aggiudicazione che non può avvenire prima della scadenza.
Non abbiamo verificato se il TeD implementi un controllo bloccante. Facciamo un test.

**Comment by obigno77** [comment]
Il TeD accetta l'avviso di rettifica anche oltre il termine della presentazione ma in questo caso il termine deve essere posticipato a data futura rispetto a quella della richiesta
