### ISSUE TITLE
Discrepanza tra scheda M1 e relative regole 

### ISSUE THREAD

**Issue by claudiocarotenuto** [anticorruzione/npa#1292]
Segnaliamo che nelle regole DMN relative alla scheda M1 si fa riferimento all'oggetto datiBaseModificaContrattuale che tuttavia non fa parte del data model della scheda.

**Comment by supportoAnac** [comment]
La regola in questione fa riferimento ai seguenti campi del TED:
BT-145 - Contract Conclusion Date 
BT-200 - Modification Reason Code 
BT-201 Modification Reason Description 
Poichè sono dati necessari anche per la pubblicazione nazionale, il servizio estrae, per i soprasoglia, questi dati dall’eForm e applica le regole citate.
Questa considerazione vale per tutti i dati in comune con il TED, che vengono esplicitamente inseriti in anacForm per tutte le schede che non prevedono eForm e, come in questo caso specifico, nell’eForm per quelle che prevedono pubblicazione TED.
