### ISSUE TITLE
Validazione campi eform TED in caso di incoerenza con dati scheda

### ISSUE THREAD

**Issue by teslb** [anticorruzione/npa#1295]
Buonasera,
     potete indicare se a fronte di dati discordanti tra quelli imputati nella scheda i-esima, ad esempio P1_16, e i dati imputati nell' eform per il TED si attivano cross-check di validazione oppure si assume sia interamente responsabilità dell'utente avere cura dei dati durante la compilazione?

Grazie e saluti

**Comment by supportoAnac** [comment]
In presenza di eForm non c'è sovrapposizione tra i dati inseriti in input nell'eForm e nella scheda. Le regole DMN scattano sui campi richiesti per la pubblicazione nazionale che hanno obbligatorietà condizionate.
