### ISSUE TITLE
Maggioli - Scheda A7_1_2 - ERR2

### ISSUE THREAD

**Issue by LucaVannoni** [anticorruzione/npa#1298]
Buongiorno, dobbiamo inviare la scheda di aggiudicazione A7_1_2 su piattaforma Maggioli, ma la piattaforma segnala il seguente errore bloccante segnalato dai servizi ANAC: **ERR2: scheda non ammessa in questa fase dell'appalto: La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata.**
Govway Transaction Id: 8af1b927-e827-11ee-852e-005056844885
L'ultima scheda confermata è S3. Prima dell'invio di questa scheda, la piattaforma all'invio della scheda A7_1_2 segnalava il seguente errore generico segnalato dai servizi ANAC: ERR9999.
L'identificativo dell'appalto ANAC è il seguente: 5bd010c7-e9da-4cb3-ab30-f531ae2a3cef
Potere aiutarci a sbloccare l'invio della scheda A_7_1_2?
Grazie.
Luca Vannoni
Comune di Rimini - Settore Sistemi Culturali di Città

**Comment by supportoAnac** [comment]
Si ringrazia della segnalazione, la problematica è nota e in corso di risoluzione, la modifica verrà rilasciata col primo rilascio utile.
