### ISSUE TITLE
[DGSIA] URGENTE Scheda P2_16 ERR9999

### ISSUE THREAD

**Issue by eslaSN** [anticorruzione/npa#1299]
Buongiorno,

stiamo cercando di inviare la Scheda P2_16
govway-transaction-id: 1edea984-e815-11ee-ae43-0050568b0b28
govway-message-id: aed425d3-e815-11ee-ae43-0050568b0b28

riceviamo sempre la seguente risposta:
{"status":500,"title":"KO","detail":"Errore Generico","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}

Sembra che il problema sia con il parametro GovWay-AuditPCP-userCodiceFiscale. Potete verificare qual è il problema e/o fornirci un'utenza con la quale possiamo fare le chiamate?

**Comment by supportoAnac** [comment]
Si chiede gentilmente di inviare una nuova scheda, e nel caso si riscontrasse lo stesso problema, di fornire maggiori informazioni allo scopo di effettuare analisi approfondite: payload relativi alla chiamata, tipologia di errore riscontrato, response e tutte le altre informazioni utili per risalire alla problematica.

**Comment by eslaSN** [comment]
Headers
Content-Type:application/json
Accept:application/json
GovWay-AuditPCP-userLoa:3
GovWay-AuditPCP-userCodiceFiscale:RSSMRA80L05F593A
GovWay-AuditPCP-userIdpType:SPID
GovWay-AuditPCP-userRole:RP
GovWay-AuditPCP-SACodiceFiscale: 80184430587
GovWay-AuditPCP-SACodiceAUSA: 0000247758
GovWay-AuditPCP-regCodicePiattaforma:0000001
GovWay-AuditPCP-regCodiceComponente:0000001
GovWay-AuditPCP-businessFlowID:00000000-0000-0000-0000-000000000000
GovWay-AuditPCP-traceID:TEST-SN-CERT
GovWay-AuditPCP-spanID:TEST-SN-CERT

JSON:
[testJSON.txt](https://github.com/anticorruzione/npa/files/14907300/testJSON.txt)
