### ISSUE TITLE
chiarimenti Servizi esposti

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#13]
Si chiede di esplicitare la differenza tra eForm e anacForm: sull’eForm dovrebbero finirci i dati generici di un appalto mentre su anacForm i dati relativi solo al contesto italiano che non andranno inviati al TED. Attendiamo documentazione completa sul tema (es. dati, anagrafiche…).

**Comment by supportoAnac** [comment]
Nell'eForm sono presenti le informazioni richieste per la pubblicazione sul TED mentre, nell'anacForm, quelle non presenti nell'eForm ma necessarie alla pubblicazione nazionale.
