### ISSUE TITLE
Servizio "Cancella Avviso"

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#130]
Buongiorno,

il servizio di "Cancella avviso" comporta anche la cancellazione dell'appalto in NPA?

Grazie

**Comment by supportoAnac** [comment]
L'operazione cancella-avviso effettua la cancellazione logica dell'avviso indicato. La cancellazione dell'intero appalto si effettua tramite l'operazione cancella-appalto. In entrambi i casi le operazioni non sono eseguite se sono state invocate rispettivamente le operazioni conferma-avviso o conferma-appalto.
