### ISSUE TITLE
[BLK- TOSCANA/BOLZANO] ERR44 "chiamata al servizio non ammessa: è in corso una richiesta di pubblicazione per l'avviso"

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1308]
Abbiamo riscontrato il seguente errore:

Codice errore: ERR44
Descrizione:
"chiamata al servizio non ammessa: è in corso una richiesta di pubblicazione per l'avviso"

**Questo problema si verifica quando si tenta di richiedere una rettifica successiva alla prima utilizzando il nuovo idAvviso restituito da ANAC alla precedente richiesta di rettifica.**

**json_input primo idAvviso ->** 
{"**idAvviso":"4a693fc5-16f7-4482-8008-f1ed01055e54"**,"idAppalto":"fc5f67fb-aa48-4f7a-95d2-9b0e07515c1a","idPianificazione":null,"scheda":{"codice":{"idTipologica":"codiceScheda","codice":"P2_16"},"versione":"1.0","body":{"anacForm":{"stazioniAppaltanti":[{"codiceFiscale":"11244750961","codiceAusa":"9000000003","codiceCentroCosto":"174a8a58-ef23-46e8-94e3-4c8915317d2a","saTitolare":true}],"appalto":{"codiceAppalto":"bolzano_15/03/2024 14:34:47_000336/2024","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"3"}],"motivoUrgenza":{"idTipologica":"motivoUrgenza","codice":"7"},"datiBase":{"oggetto":"test ristretta","importo":10000.0},"datiBaseProcedura":{"tipoProcedura":{"idTipologica":"tipoProcedura","codice":"restricted"},"proceduraAccelerata":false},"datiBaseStrumentiProcedura":{"accordoQuadro":{"idTipologica":"accordoQuadro","codice":"fa-w-rc"},"sistemaDinamicoAcquisizione":{"idTipologica":"sistemaDinamicoAcquisizione","codice":"dps-nlist"},"astaElettronica":false}},"lotti":[{"lotIdentifier":"LOT-0001","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"3"}],"contrattiDisposizioniParticolari":{"idTipologica":"contrattiDisposizioniParticolari","codice":"1"},"codIstat":{"idTipologica":"codIstat","codice":"015062002"},"afferenteInvestimentiPNRR":false,"prestazioniComprese":{"idTipologica":"prestazioniComprese","codice":"1"},"servizioPubblicoLocale":false,"ripetizioniEConsegneComplementari":false,"lavoroOAcquistoPrevistoInProgrammazione":false,"saNonSoggettaObblighi24Dicembre2015":false,"iniziativeNonSoddisfacenti":false,"strumentiElettroniciSpecifici":false,"ccnl":"78654665","opzioniRinnovi":false,"ipotesiCollegamento":{"motivoCollegamento":{"idTipologica":"motivoCollegamento","codice":"10"}},"categoria":{"idTipologica":"categoria","codice":"FS"},"modalitaAcquisizione":{"idTipologica":"modalitaAcquisizione","codice":"2"},"quadroEconomicoStandard":{"impServizi":10000.0,"impTotaleSicurezza":0.0,"ulterioriSommeNoRibasso":0.0,"sommeOpzioniRinnovi":0.0,"sommeADisposizione":2000.0},"datiBase":{"oggettoContratto":{"idTipologica":"oggettoContratto","codice":"services"},"oggetto":"1","importo":10000.0},"datiBaseAggiuntivi":{"affidamentiRiservati":[{"idTipologica":"affidamentiRiservati","codice":"none"}]},"datiBaseAggiudicazione":{"criteriAggiudicazione":{"idTipologica":"criteriAggiudicazione","codice":"quality"}},"datiBaseTerminiInvio":{"scadenzaPresentazioneInvito":"2024-03-23T12:00:00Z"},"datiBaseCPV":{"tipoClassificazione":{"idTipologica":"tipoClassificazione","codice":"cpv"},"cpvPrevalente":{"idTipologica":"CPV","codice":"50110000"}},"datiBaseAccessibilita":{"accessibilita":{"idTipologica":"accessibilita","codice":"n-inc"}},"datiBaseDocumenti":{"url":"[https://pleiade-pab-manual-mm.test.i-faber.host/simog/cig-request/cig/394/3/506/edit/false"}}]},"espd":""}](https://pleiade-pab-manual-mm.test.i-faber.host/simog/cig-request/cig/394/3/506/edit/false%22%7D%7D]%7D,%22espd%22:%22%22%7D)

**son_output di anac con nuovo idAvviso ->**
{"instance":null,"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"fc5f67fb-aa48-4f7a-95d2-9b0e07515c1a","idPianificazione":null,"idScheda":"59423ebc-ca5d-430f-a124-dac4edbf74ac","idNuovaScheda":"2de95201-dae4-41fa-ad21-b0d5c59254b1","idAvviso":"4a693fc5-16f7-4482-8008-f1ed01055e54","idNuovoAvviso":"2b731ed6-8251-4679-8d1b-fcc3791db9a0","idContratto":null,"esito":{"idTipologica":"esito","codice":"WT"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AV_RETT"},"dettaglio":{"idTipologica":"esitoOperazione","codice":"AV_IN_PUBB"},"dataControllo":"2024-03-19T17:11:59.570+00:00","errori":null}]}

**json_input nuova rettifica con idNuovoAvviso al posto di idAvviso ->**
{"idAvviso":"2b731ed6-8251-4679-8d1b-fcc3791db9a0","idAppalto":"fc5f67fb-aa48-4f7a-95d2-9b0e07515c1a","idPianificazione":null,"scheda":{"codice":{"idTipologica":"codiceScheda","codice":"P2_16"},"versione":"1.0","body":{"anacForm":{"stazioniAppaltanti":[{"codiceFiscale":"11244750961","codiceAusa":"9000000003","codiceCentroCosto":"174a8a58-ef23-46e8-94e3-4c8915317d2a","saTitolare":true}],"appalto":{"codiceAppalto":"bolzano_15/03/2024 14:34:47_000336/2024","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"3"}],"motivazioneCIG":{"idTipologica":"motivazioneCIG","codice":"2"},"strumentiSvolgimentoProcedure":{"idTipologica":"strumentiSvolgimentoProcedure","codice":"2"},"termineRidottoAvvisoPreinformazione":false,"motivoUrgenza":{"idTipologica":"motivoUrgenza","codice":"7"},"datiBase":{"oggetto":"test ristretta","importo":10000.0},"datiBaseProcedura":{"tipoProcedura":{"idTipologica":"tipoProcedura","codice":"restricted"},"proceduraAccelerata":false},"datiBaseStrumentiProcedura":{"accordoQuadro":{"idTipologica":"accordoQuadro","codice":"fa-w-rc"},"sistemaDinamicoAcquisizione":{"idTipologica":"sistemaDinamicoAcquisizione","codice":"dps-nlist"},"astaElettronica":false}},"lotti":[{"lotIdentifier":"LOT-0001","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"3"}],"contrattiDisposizioniParticolari":{"idTipologica":"contrattiDisposizioniParticolari","codice":"1"},"codIstat":{"idTipologica":"codIstat","codice":"015062002"},"afferenteInvestimentiPNRR":false,"finanziamenti":[{"tipoFinanziamento":{"idTipologica":"tipoFinanziamento","codice":"C03"},"importo":3333.0}],"prestazioniComprese":{"idTipologica":"prestazioniComprese","codice":"1"},"servizioPubblicoLocale":false,"ripetizioniEConsegneComplementari":false,"lavoroOAcquistoPrevistoInProgrammazione":false,"saNonSoggettaObblighi24Dicembre2015":false,"iniziativeNonSoddisfacenti":false,"strumentiElettroniciSpecifici":false,"ccnl":"78654665","opzioniRinnovi":false,"ipotesiCollegamento":{"motivoCollegamento":{"idTipologica":"motivoCollegamento","codice":"10"}},"categoria":{"idTipologica":"categoria","codice":"FS"},"modalitaAcquisizione":{"idTipologica":"modalitaAcquisizione","codice":"2"},"quadroEconomicoStandard":{"impServizi":10000.0,"impTotaleSicurezza":0.0,"ulterioriSommeNoRibasso":0.0,"sommeOpzioniRinnovi":0.0,"sommeADisposizione":2000.0},"datiBase":{"oggettoContratto":{"idTipologica":"oggettoContratto","codice":"services"},"oggetto":"1","importo":10000.0},"datiBaseAggiuntivi":{"affidamentiRiservati":[{"idTipologica":"affidamentiRiservati","codice":"none"}]},"datiBaseAggiudicazione":{"criteriAggiudicazione":{"idTipologica":"criteriAggiudicazione","codice":"quality"}},"datiBaseTerminiInvio":{"scadenzaPresentazioneInvito":"2024-03-24T12:00:00Z"},"datiBaseCPV":{"tipoClassificazione":{"idTipologica":"tipoClassificazione","codice":"cpv"},"cpvPrevalente":{"idTipologica":"CPV","codice":"50110000"}},"datiBaseAccessibilita":{"accessibilita":{"idTipologica":"accessibilita","codice":"n-inc"}},"datiBaseDocumenti":{"url":"[https://pleiade-pab-manual-mm.test.i-faber.host/simog/cig-request/cig/394/3/506/edit/false"}}]},"espd":""}](https://pleiade-pab-manual-mm.test.i-faber.host/simog/cig-request/cig/394/3/506/edit/false%22%7D%7D]%7D,%22espd%22:%22%22%7D)

**json_output con errore da parte di anac ->**
{"instance":null,"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR44","dettaglio":null}]}

**risposta primo avviso rettificato ->**
{"instance":null,"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"fc5f67fb-aa48-4f7a-95d2-9b0e07515c1a","idPianificazione":null,"idScheda":"59423ebc-ca5d-430f-a124-dac4edbf74ac","idNuovaScheda":null,"idAvviso":"4a693fc5-16f7-4482-8008-f1ed01055e54","idNuovoAvviso":null,"idContratto":null,"esito":{"idTipologica":"esito","codice":"OK"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AV_RETT"},"dettaglio":{"idTipologica":"esitoOperazione","codice":"AV_RETT"},"dataControllo":"2024-03-20T21:07:28.013+00:00","errori":null}]}

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Da un test di replica condotto sui nostri sistemi, confermiamo che il servizio di rettifica avviso funziona correttamente.</p>

<p>Dal momento che l'ultimo tentativo di rettifica risale in data 2024-03-21, consigliamo di riprovare tale procedura.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
