### ISSUE TITLE
[BLK -TOSCANA/BOLZANO] - ERRORE REG 37

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1309]
Salve, 
nella compilazione dei dati per l'invio di una scheda P3_1, riscontriamo il seguente errore :

**REG 37 - Non è stato indicato il valore relativo alle somme per opzioni e rinnovi**

Tuttavia, nell'anacform relativo a questa scheda NON esiste tale campo!

<img width="646" alt="image" src="https://github.com/anticorruzione/npa/assets/144692899/9a6afeae-d82a-49be-a2b3-fc2b16ea1f5c">

Si richiede una risoluzione perchè bloccante.

**Comment by supportoAnac** [comment]
Segnalazione corretta, la regola verrà modificata col prossimo rilascio.
