### ISSUE TITLE
P2_16: Verifica coerenza modello dati per errore REG67

### ISSUE THREAD

**Issue by teslb** [anticorruzione/npa#1310]
Buonasera,
     ci associamo alla issue [1230 ](https://github.com/anticorruzione/npa/issues/1230) dove nella compilazione della P2_16 per il campo "tipo procedura" andando a selezionare il valore in giallo

![image](https://github.com/anticorruzione/npa/assets/124814399/65602a1d-cdd8-4902-9326-058ffc36781f)

viene restituito un errore REG67

![image](https://github.com/anticorruzione/npa/assets/124814399/8d84829f-ae33-4ad3-9e87-0987065b21ea)

sebbene il campo non sia censito nel modello dati documentato.

In attesa di un Vostro sollecito riscontro.

Grazie e saluti,

**Comment by supportoAnac** [comment]
Segnalazione corretta, il disallineamento verrà risolto con il prossimo rilascio del modello dati.
