### ISSUE TITLE
[Toscana/Bolzano] Scheda I1- REG57 non funzionante

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1319]
Salve,
Voglio segnalare che in ambiente di collaudo per la scheda I1 non funziona il controllo indicato nel file .dmn riguardante la REG57:Data approvazione del progetto Esecutivo: se digitata deve essere superiore alla data di disposizione dell’inizio della prog. Esecutiva.

Grazie.

**Comment by supportoAnac** [comment]
Segnalazione presa in carico, verranno effettuate le verifiche richieste.
