### ISSUE TITLE
Errori property required

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#132]
Nella scheda p1.10 (e non solo) sono stati inseriti dei required non esistenti nel modello. Questo giustamente farà fallire la validazione. 
Ad esempio https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-P1.10.yaml
L'AnacFormP1.10Type ha come required [categoria, finanziamenti, opzioni/rinnovi, appalto,lotti], ma nè l' AnacFormBaseType da cui eredita la sola property stazioniAppaltanti nè la definizione delle property nel modello AnacFormP1.10Type specificano i campi categoria, finanziamenti, opzioni/rinnovi ma solo lotti e appalto.
Segnalo anche che ad esempio l'AnacFormBaseType ha come required finanziamenti quando in realtà espone solo la property stazioniAppaltanti

**Comment by supportoAnac** [comment]
Molti degli errori segnalati sui campi required sono stati risolti con il rilascio del 3 luglio. Saranno comunque revisionati tutti gli oggetti di tutte le schede al fine di eliminare ogni residuo di property required non presente.
