### ISSUE TITLE
[CONSIP] BLK -A7.1.1 - ERR9999

### ISSUE THREAD

**Issue by LucariniPaola** [anticorruzione/npa#1320]
l'err9999 è attualmente presente per la scheda A7_1_1, siamo impossibilitati a trasmetterla

GovWay-Message-ID=[604ac554-00b1-456f-910f-5aba366c9ce5]
GovWay-Transaction-ID=[24413a5a-e831-11ee-9b99-0050568e9679]

id appalto :ab7106c5-bebf-4c14-bc89-c4f0e6b6fe6e

**Comment by lauralu1993** [comment]
salve, ci sono aggiornamenti?
sono diversi giorni che proviamo a trasmettere la A7_1_1 ma riscontriamo ancora errore generico - 99999

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>da repliche effettuate su postman é stato riscontrato ERR64, il problema dell'errore ERR9999 potrebbe essere stato risolto con delle fix.<br>
<br>
Pertanto si consiglia di:</p>

<p>rincontrollare l'eform ,(in particolare il noticeId e vesionId e anche la dispatch date), dopodiché modificare la scheda se necessario, procedere alla conferma di essa ed infine pubblicarla.<br>
<br>
Restiamo a disposizione per ulteriori chiarimenti.<br>
<br>
Cordiali saluti</p>
