### ISSUE TITLE
Schede con pubblicazione GUUE - eForm Notice Dispatch Date must be between 0 and 24 hours before the current date

### ISSUE THREAD

**Issue by lucaCorigliano-SA** [anticorruzione/npa#1321]
Buongiorno,
come ben sapete, alcune pubblicazioni richiedono una scheda GUUE, che viene trasmessa in fase di creazione. Ogni scheda/avviso richiede varie fasi prima di giungere alla pubblicazione, alcune delle quali asincrone. Per questo motivo è possibile che dal momento della trasmissione fino al momento dell'inizio della pubblicazione, passino più di 24 ore.

Questo fa sì che sia possibile che un form GUUE trasmesso diventi invalido e blocchi il flusso di pubblicazione, costringendo l'utente a dover modificare l'avviso con una nuova trasmissione del form GUUE.

Ritengo invece sia opportuno che sia cura di ANAC aggiornare l'eForm Notice Dispatch Date `BT-05` subito prima dell'effettivo invio verso il TED, sia per semplificare la vita all'utente, sia per rendere più corretto il dato, in quanto l'effettivo invio al TED viene effettuato da ANAC.

**Comment by lucaCorigliano-SA** [comment]
Aggiungo anche che questo problema è più grave del previsto.
Correggetemi se sbaglio, ma se questo accade, la pubblicazione viene interrotta pertanto è addirittura impossibile invocare `modifica-avviso` perchè risponderebbe ERR50 ed altrettanto impossibile invocare `rettifica-avviso` perchè la pubblicazione non è ultimata.

@supportoAnac urge un modo di modificare gli avvisi con pubblicazione interrotta, se non è già previsto

**Comment by lucaCorigliano-SA** [comment]
Questo problema è ancora esistente, sia in produzione che in ambienti di test e collaudo

@supportoAnac @obigno77 è possibile che problemi così gravi vengano ignorati per mesi?

**Comment by obigno77** [comment]
ANAC non può alterare il contenuto delle buste ricevute dalla piattaforma, in questo caso l'eform. Per ovviare  a questo problema 
è stato consentito di operare il modifica-avviso anche in caso di rifiuto del Ted. In questo caso è necessario modificare, oltre alla issueDate, anche il noticeId o incrementare la versione del noticeId precedente

**Comment by lucaCorigliano-SA** [comment]
In tal caso vi chiedo di verificare l'effettivo funzionamento del modifica-avviso in questo caso perchè dal nostro lato questo non funziona. Per esperienza attuale una pubblicazione fallita con questo errore è irrecuperabile.

In più sottolineo che "non possiamo modificare il contenuto" non è una giustificazione valida per un problema così grave. La problematica avviene regolarmente, quindi una soluzione concreta va trovata dal Vs. lato.
