### ISSUE TITLE
ERR41 Verifica appalto P7_2

### ISSUE THREAD

**Issue by scalabrese11** [anticorruzione/npa#1324]
Buongiorno,

abbiamo riscontrato l'errore seguente in ambiente di test alla verifica di una P7_2:

class EsitoOperazioneListaResponse {
    class BaseResponse {
        instance: null
        status: 200
        title: OK
        detail: Esecuzione avvenuta con successo
        type: about:blank
    }
    listaEsiti: [class EsitoOperazioneType {
        idAppalto: 773f80e3-3dd0-40da-88e0-6751d61f8e01
        idPianificazione: null
        idScheda: a4a990ad-495b-4abe-b86d-7d5f1ea19bce
        idNuovaScheda: null
        idAvviso: null
        idNuovoAvviso: null
        idContratto: null
        esito: class EsitoEnum {
            class TipologicaSchemaType {
                idTipologica: esito
                codice: KO
            }
        }
        tipoOperazione: class TipoOperazioneEnum {
            class TipologicaSchemaType {
                idTipologica: tipoOperazione
                codice: AP_VERIF
            }
        }
        dettaglio: class DettaglioEsitoOperazioneEnum {
            class TipologicaSchemaType {
                idTipologica: esitoOperazione
                codice: AP_N_VERIF
            }
        }
        dataControllo: 2024-03-26T12:28:39.389Z
        errori: [class ErroriEnum2 {
            class TipologicaSchemaErroriType {
                idTipologica: errori
                codice: ERR41
                dettaglio: 
            }
        }]
    }]
}

è possibile fare un controllo per verificare cosa non sia corretto nella request?

Grazie.

**Comment by CrisMaggioli** [comment]
Salve,
mi unisco, nella segnalazione, per confermare che anche noi abbiamo un errore uguale.
Anzi inviando lo stesso json per la P7_2 che mi ha consentito la pubblicazione il 06/03/2024 
(idappalto: 6e357a1a-1054-478c-9d9c-e8bbdb851c97,cig:I0025E2A75)
 ora ottengo l'errore suddetto in fase di verifica:
 ERR41: errore generico durante la validazione dei dati della scheda
 Data evento: 26/03/2024 17:32:29
Govway Transaction Id: 40c5d61e-eb8c-11ee-9ec6-0050568e08b3
E'possibile che cisia stata un regressione?
grazie

**Comment by supportoAnac** [comment]
È stata rilasciata una fix in data odierna, si chiede gentilmente di riprovare ed aprire una nuova issue qualora l'errore dovesse ripresentarsi.
