### ISSUE TITLE
[CONSIP] BLK-P2.18- ERR41 -ERRORE GENERICO DURANTE LA VALIDAZIONE DEI DATI DELLA SCHEDA 

### ISSUE THREAD

**Issue by LucariniPaola** [anticorruzione/npa#1325]
Stiamo riscontrando l'err41 nella scheda P2.18.

"GovWay-Message-ID":["b2309956-136f-449a-9440-506384d6f822"]
"GovWay-Transaction-ID":["0d909fc4-eb65-11ee-9b99-0050568e9679"]

ID APPALTO : 6008ae96-8436-4452-a251-6b73671522

**Comment by lauralu1993** [comment]
lo stesso problema si verifica sulla P7_2:

ID_APPALTO_NPA: 75f4e16b-eb81-4d33-aa25-5ff7360d1120
 
"GovWay-Message-ID":["f971571b-9b73-411b-8dd1-a5a5685924e7"]
"GovWay-Transaction-ID":["da7a91ef-eb54-11ee-9b99-0050568e9679"]

**Comment by supportoAnac** [comment]
È stata rilasciata una fix in data odierna, si chiede gentilmente di riprovare ed aprire una nuova issue qualora l'errore dovesse ripresentarsi.
