### ISSUE TITLE
ERR41 -schede di indizione

### ISSUE THREAD

**Issue by iacopus** [anticorruzione/npa#1326]
salve,

l'errore riscontrato nell'issue #1325 oltre che alla P2.18 risulta coinvolgere anche altre schede. 
Lo abbiamo riscontrato anche per la P7.2 e per le P7.1.1/3.

grazie

**Comment by supportoAnac** [comment]
È stata rilasciata una fix in data odierna, si chiede gentilmente di riprovare ed aprire una nuova issue qualora l'errore dovesse ripresentarsi.
