### ISSUE TITLE
[Toscana/Bolzano] - P7.2 - ERR4: somme.Ripetizioni: is missing but it is required

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1327]
Salve,

Voglio segnalare una problematica riscontrata in collaudo nel momento in cui Confermo l'appalto per una scheda P7.2
La scheda P7.2 è così valorizzata:

1) ripetizioniEConsegneComplementari* : NO
[data (6).json](https://github.com/anticorruzione/npa/files/14761998/data.6.json)

Le somme.Ripetizioni non vengono trasmesse nel json ad ANAC, ma al conferma appalto viene restitutito l'ERR4: somme.Ripetizioni: is missing but it is required

In base alla issues #158 noi non trasmettiamo somme.Ripetizioni in quanto abbiamo indicato "NO" per il campo ripetizioniEConsegneComplementari

Come mai ci vengono richieste le somme ripetizioni se l'utente indica che l'appalto non prevede ripetizioni?

**Comment by supportoAnac** [comment]
Occorre inserire il campo nel json in quanto obbligatorio, ma è possibile indicare 0 visto che non sono previste ripetizioni.
