### ISSUE TITLE
[BLK- TOSCANA/BOLZANO] - Errore scheda SC1

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1329]
Salve,
dopo aver correttamente inviato la scheda di aggiudicazione e avendo ricevuto esito positivo, all'invio della scheda SC1 riceviamo il seguente errore:

**ERR2 - scheda non ammessa in questa fase dell'appalto**

{
  "idAppalto": "5cc2358a-0449-4c23-a864-c2f15309ac4c",
  "scheda": {
    "codice": {
      "idTipologica": "codiceScheda",
      "codice": "SC1"
    },
    "versione": "1.0",
    "body": {
      "anacForm": {
        "datiContratto": {
          "codiceAusa": [
            "9000000003"
          ],
          "idPartecipante": "fcc320f3-159b-37f9-9dfd-3de1071fc5d6",
          "cig": [
            "I00319E970"
          ],
          "dataDecorrenza": "2024-03-26T12:00:00Z",
          "dataScadenza": "2024-03-28T12:00:00Z",
          "importoCauzione": 2000
        }
      }
    }
  }
}
{
  "instance": null,
  "status": 400,
  "title": "KO",
  "detail": "Errore",
  "type": "about:blank",
  "errori": [
    {
      "idTipologica": "errori",
      "codice": "ERR2",
      "dettaglio": null
    }
  ]
}

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Da controlli sui nostri sistemi è emerso che l'ERR2 riscontrato conferma il funzionamento dell'applicazione in quanto dopo la conferma della scheda M1, la scheda SC1 non è ammessa.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
