### ISSUE TITLE
Impossibile fare gare con Opzioni e/ o rinnovi per REG37 (test su P3_1)

### ISSUE THREAD

**Issue by laurapavan** [anticorruzione/npa#1330]
Segnalo che la REG37 sta bloccando una qualsiasi gara che preveda opzioni e/o rinnovi.
Ci risulta che la normativa preveda ancora la possibilità di opzioni e/o rinnovi, come fanno le SA a usufruirne ?

Questa la regola in specifica:

some lotto in lotti
satisfies lotto.opzioniRinnovi and (lotto.quadroEconomicoStandard.sommeOpzioniRinnovi = null or lotto.quadroEconomicoStandard.sommeOpzioniRinnovi = 0)

Descrizione: REG37: Somme opzioni e rinnovi: se l’appalto prevede opzioni/rinnovi deve essere indicato un importo maggiore di 0.

Riporto alcuni esempi estratti da una P3_1:

Caso 1: Rinnovi = sì, Opzioni = no

**"opzioniRinnovi": true,**
"quadroEconomicoStandard": {
"impLavori": 0,
"impServizi": 15000,
"impForniture": 0,
"impTotaleSicurezza": null,
"ulterioriSommeNoRibasso": null,
"impProgettazione": null,
"**sommeOpzioniRinnovi": 12500,**
"sommeRipetizioni": null,
"sommeADisposizione": 12

----------

Caso 2: Rinnovi = sì, Opzioni = sì

**"opzioniRinnovi": true,**
"quadroEconomicoStandard": {
"impLavori": 0,
"impServizi": 15000,
"impForniture": 0,
"impTotaleSicurezza": null,
"ulterioriSommeNoRibasso": null,
"impProgettazione": null,
**"sommeOpzioniRinnovi": 12502,**
"sommeRipetizioni": 1,
"sommeADisposizione": 12

**NESSUNO dei due casi passa, per la REG37 appunto.**

Grazie e saluti.

**Comment by laurapavan** [comment]
buongiorno, ecco i dati di un caso tipo 1 simulato oggi in ambiente di collaudo (corrispondente a un caso reale di produzione per altro).

Govway Transaction Id: 917dcae7-0bae-11ef-9b99-0050568e9679
IdAppalto: 4f56d459-abdd-421a-aa48-47fd4965864c

in allegato il json completo.

**Comment by laurapavan** [comment]
Questo problema persiste ancora oggi sia in collaudo che in produzione. 
Cosa dobbiamo dire ai clienti? di non prevedere opzioni o rinnovi?

NOTA: la prova di oggi è stata fatta sui servizi aggiornati al 21/05.


[P3_1.json](https://github.com/anticorruzione/npa/files/15404046/P3_1.json)

Scheda P3_1 (json allegato)
IdAppalto : a48535a5-15a6-422d-a249-ffb3a9bcfaaf
Data evento: 22/05/2024 15:32:34
Govway Transaction Id: 767c59f3-183c-11ef-9ec6-0050568e08b3

**Comment by laurapavan** [comment]
si sollecita un riscontro. Grazie.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>abbiamo verificato che in ambiente di qualificazione, utilizzando i dati forniti, l’appalto viene confermato correttamente senza errori.<br>
<br>
Pertanto la invitiamo a riprovare.<br>
<br>
Cordiali saluti.</p>
