### ISSUE TITLE
CRO Aviano - notice  - errore PVL

### ISSUE THREAD

**Issue by FavaroInsiel** [anticorruzione/npa#1335]
[76054-2024 - Competition - TED.pdf](https://github.com/anticorruzione/npa/files/14775904/76054-2024.-.Competition.-.TED.pdf)
[Piattaforma Contratti Pubblici _ Portale Servizi A.N.AC_ (1).pdf](https://github.com/anticorruzione/npa/files/14775907/Piattaforma.Contratti.Pubblici._.Portale.Servizi.A.N.AC_.1.pdf)

Per il seguente Appalto la pubblicazione sul TED è (oppure era) riuscita (vedi allegato) mentre ora sulla PVL viene restituito un errore 

ID Appalto:  b97198c2-b52f-4963-a22c-7ffd0b4b68ed
Codice Appalto: 630910_27386 
ID Avviso Pubblicato: 6b66ad27-5bfe-4188-9980-e0c4072be760 
Cig   B0369A2377

630910_27386/CENTRO DI RIFERIMENTO ONCOLOGICO - APPROVVIGIONAMENTI, ECONOMATO E LOGISTICA/2024

Si chiede di conoscere lo stato effettivo di questa pubblicazione, il problema che ha generato l'errore e quali indicazioni dobbiamo fornire ora all'utente.
Grazie

**Comment by obigno77** [comment]
La richiesta di pubblicazione su TeD di questo avviso non è mai andata a buon fine. Le motivazioni sono disponibili consultando l'esito della pubblicazione. E' possibile utilizzare il modifica-avviso per risolvere il problema. Per il supporto in esercizio si invita a usare la casella mail dedicata
