### ISSUE TITLE
[CONSIP] chiarimenti - errore pubblicazione PVL

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1336]
salve,
quando va in errore la pubblicazione di una scheda con solo la pubblicazione nazionale è corretto ritentare la pubblicazione chiamando di nuovo il PUBBLICA-AVVISO?

grazie

**Comment by obigno77** [comment]
Si, è corretto

**Comment by lauralu1993** [comment]
[labruno](https://github.com/labruno)
