### ISSUE TITLE
[Intercenter] + [LazioCrea] + [altri] Problemi nei Lotti deserti per appalti sopra soglia

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1337]
nel caso di Lotto deserto su gare sopra soglia si incontra una difficoltà di uso delle schede A1_xx.
Pur avendo la possibilità di costruire la CANxx, nel compilare l'anacForm incontriamo il problema legato all'obbligatorietà del campo complesso offertePresentate che nel caso di Lotto deserto non si sa come valorizzare (vedi documentazione)
![image](https://github.com/anticorruzione/npa/assets/137269683/474c5305-aec9-44c6-86b9-f1f56547374a)
si richiede con urgenza la modalità attraverso la quale superare la difficoltà illustrata.
Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>L'attività è stata pianificata ed inserita nel piano dei changelog.</p>

<p>Vi ringraziamo per la segnalazione.</p>

<p>Cordiali saluti</p>
