### ISSUE TITLE
[BOLZANO] Invio eForm rettifica gara aperta: ERR53 operazione non consentita per lo stato dell'avviso sulla PVL

### ISSUE THREAD

**Issue by GGr8l** [anticorruzione/npa#1339]
Buongiorno,

si segnala incongruenza tipo di procedura (aperta! direttiva generale, regime alleggerito) con l'errore mostrato a seguito del tentativo di invio della rettifica (menzione a "PVL").

ERR53 operazione non consentita per lo stato dell'avviso sulla PVL.

Si chiede gentilmente analisi e risoluzione.

Grazie

**Comment by obigno77** [comment]
Si chiede di indicare l'idAppalto

**Comment by GGr8l** [comment]
ID Appalto: fa2c09b3-4b16-4f17-a4e3-b945f7cb0d8b
CIG: B0F9F2B966

Grazie

**Comment by GGr8l** [comment]
Stesso problema riscontrato anche con un'altra aperta per un avviso di rettifica per un bando di gara – direttiva generale, regime ordinario (eForm16)

ID Appalto c0d4903d-e705-4217-9047-77e7d6baa58a
CIG B1129311F7

Grazie

**Comment by GGr8l** [comment]
Buonasera,

1) ci sono novità per caso sull'errore?
2) perché è stata richiamata PVL e non PCP?

Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>L'ERR53 sulla chiamata di rettifica-avviso era dovuto al fatto che l'avviso era in corso di pubblicazione.</p>

<p>Infatti la chiamata al rettifica-avviso è stata eseguita la mattina del 28/03, mentre la pirma pubblicazione (a seguito di conferma dell'appalto) è stata completata nel pomeriggio del 28/03.</p>

<p> </p>

<p>Restiamo a disposizione.</p>

<p> </p>

<p>Cordiali Saluti</p>
