### ISSUE TITLE
idPartecipante diverso per stesso OE

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1340]
Buongiorno,

in caso di invio di scheda S2, in cui lo stesso OE che ha partecipato a più lotti della procedura sia indicato per ogni lotto con IDpartecipante diverso, potrebbe creare problemi? o si può ritenere un comportamento accettabile?

Grazie,
Luca

**Comment by anac-uscp** [comment]
<p>Buongiorno, L'ID partecipante è un identificatore univoco assegnato a ciascun partecipante per ogni singolo lotto. Non ci sono problemi se uno stesso operatore economico (OE) decide di utilizzare diversi ID partecipante per lotti differenti. Tuttavia, è importante notare che non è possibile utilizzare lo stesso ID partecipante per più lotti associati allo stesso CIG.</p>
