### ISSUE TITLE
[ARIA SPA] rettifica dati presenti in ANACFORM per appalti con pubblicazione TED

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1341]
Buongiorno,

non risulta chiaro come gestire xml eFORM in caso di rettifica per cui vengono cambiati solo dati presenti nel ANACFORM.

in particolare, per la sottomissione della richiesta di rettifica và inviata nuovamente la scheda (ANACFORM, eFORM, ESPD).
nel caso la rettifica riguardi solo dati presenti nell'anacform, il formulario xml E16 (in caso di P1_16) deve comunque essere costruito come xml di rettifica per agganciarsi ad uno già pubblicato? se di fatto non si modifica alcun dato è corretto che il TED pubblichi una rettifica di un avviso che lato loro è rimasto lo stesso?

altrimenti, è sufficiente allegare lo stesso file xml (eFORm, DGUE) e l'anacform rettificato nelle parti di interesse e solo queste vengono recepite da ANAC/PCP mentre per il TED non cambia null dato che i dati presenti nell'avviso del formulario E16 non sono cambiati?

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">In caso di rettifica per cui vengono cambiati solo dati presenti nel ANACFORM è comunque necessario inviare un avviso di richiesta di rettifica reinviando la stessa scheda <em>(ANACFORM, eFORM, </em>ESPD) rettificata solo nell’ANACform, con versione differente dell’eForm. La scheda sarà ripubblicata sia in PVL che sul TED il quale pubblicherà un avviso contenente le stesse informazioni del bando originale.</span></span></span></p>

<p style="margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">GdL Dati</span></span></span></p>
