### ISSUE TITLE
[BLK][Maggioli] Scheda PL2_7 incongruenza errore REG99

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#1344]
Salve,
riscontriamo il seguente errore segnalato riguardo un eForm che l'orchestratore non prevede per la scheda suddetta:

REG99: L'importo indicato nell'oggetto lotti.datiBase.importo deve essere > 0. In presenza di eForm verificare l'importo inserito nel campo EstimatedOverallContractAmount (BT-27).

Data evento: 29/03/2024 09:10:01

id pianificazione: 767144b0-f348-4c0e-bd46-d3561aee1af8

govway: d4368616-ed9f-11ee-9ec6-0050568e08b3

Peraltro gli importi  lotti.datiBase.importo risultano congruenti (>0) nell'anac form per tutti i lotti del json.

Oltretutto segnalo che con lo stesso json eravamo riusciti a pubblicare in passato:
IdPianificazione: 582e2ff7-79dd-49b8-9f14-6f05bb4abf0f

C'e' stata una regressione? Cosa centra la presenza dell' eForm in una scheda che non lo prevede?
Grazie.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Sono state eseguite diverse fix dalla data di segnalazione dell'errore. Si consiglia di ripetere l'operazione sul piano.</p>

<p>Restiamo a disposizione per ulteriori chiarimenti.</p>

<p>Cordiali saluti</p>
