### ISSUE TITLE
[Teamsystem][BLK] - ERR77  Il partecipante non è valido per il lotto

### ISSUE THREAD

**Issue by mcgirone** [anticorruzione/npa#1345]
Riapro la medesima issue già segnalata nella:
https://github.com/anticorruzione/npa/issues/1174
in quanto il problema non risulta ancora risolto.

Id appalto: bfe6e69c-a69d-4e4f-b151-c790463d13b1
S2-> "idScheda":"facbecb6-2e8d-49d2-9942-98405bf9b8fb"
S2 JSON
{"idAppalto":"bfe6e69c-a69d-4e4f-b151-c790463d13b1","scheda":{"codice":{"idTipologica":"codiceScheda","codice":"S2"},"versione":"1.0","body":{"anacForm":{"elencoSoggetti":[{"cig":"I001B9F299","partecipanti":[{"codiceFiscale":"01035310414","denominazione":"TEAMSYSTEM S.P.A.","ruoloOE":{"idTipologica":"ruoloOE","codice":"1"},"tipoOE":{"idTipologica":"tipoOE","codice":"1"},"idPartecipante":"8cffee47-f61a-481e-bd08-1ec095a360de","paeseOperatoreEconomico":"Pesaro","avvalimento":false},{"codiceFiscale":"TTNVLR54D16G482H","denominazione":"3T DI TATONI VALERIO","ruoloOE":{"idTipologica":"ruoloOE","codice":"1"},"tipoOE":{"idTipologica":"tipoOE","codice":"1"},"idPartecipante":"ef4f8924-bd69-4970-8e78-b81c205af068","paeseOperatoreEconomico":"Città Sant'Angelo","avvalimento":false}],"dataInvito":"2024-02-20T10:59:30Z","dataScadenzaPresentazioneOfferta":"2024-02-22T11:29:31Z"}]}}}}

A2_29 -> "idScheda":"d28385c4-6789-4c10-b17f-02cafc7313de"

Response conferma scheda A2_29:
{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","dettaglio":"idPartecipante: ef4f8924-bd69-4970-8e78-b81c205af068 - cig: I001B9F299","codice":"ERR77"}]}

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>la problematica è stata superata con rilasci precedenti. si prega di riprovare e riaprire un nuovo ticket con i riferimenti aggiornati qualora fosse ancora presente.</p>

<p>Restiamo a disposizione per ulteriori chiarimenti.<br>
<br>
Cordiali Saluti</p>
