### ISSUE TITLE
[BLK] [Teamsystem] - ERR2 - Scheda non  aggiudicazione A1_29

### ISSUE THREAD

**Issue by mcgirone** [anticorruzione/npa#1346]
In seguito alla creazione di una procedura, revocando uno dei 5 lotti otteniamo ERR2 sebbene la procedura P1_16 sia pubblicata sia a livello nazionale che su TED, di seguito i dettagli:
idAppalto: 0caf4136-51a8-4c08-927e-d9959b751b74
[crea-scheda_Response (3) (1).json](https://github.com/anticorruzione/npa/files/14835180/crea-scheda_Response.3.1.json)
[crea-scheda_Request (1) (1).json](https://github.com/anticorruzione/npa/files/14835182/crea-scheda_Request.1.1.json)

In attesa di supporto

**Comment by obigno77** [comment]
Dall'orchestratore dopo la scheda P1_16 sono previste solo la S1 e la S2

**Comment by gianlucacuomo** [comment]
Vorrei però riaprire la issue, come si può trasmettere la non aggiudicazione in caso di procedure soprasoglia deserte o annullate se non è possibile inviare l'avviso di esito che include anche la mancata aggiudicazione? E' impossibile inviare la S2 senza partecipanti

**Comment by mcgirone** [comment]
La issue non risulta chiusa in quanto è possibile revocare un lotto prima della partecipazione degli Operatori economici ed è necessario inviare l'avviso di mancata aggiudicazione ma riceviamo errore.

**Comment by anac-uscp** [comment]
<p>Gentile utente</p>

<p>testando nei nostri ambienti il caso in oggetto è risultato ERR46,quindi una non presenza di campi obbligatori per la scheda A1_29.</p>

<p>la inivitiamo a prendere visione della documentazione ufficiale</p>

**Comment by obigno77** [comment]
Risolta da note di rilascio del 06/08/2024 (Changelog-03)
