### ISSUE TITLE
[Toscana/Bolzano] - ERR25 all'invio scheda di Aggiudicazione

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1347]
Salve,
In ambiente di collaudo abbiamo inviato una scheda P1.21 (multilotto). E' già stata inviata e confermata la scheda S2

All'invio della scheda di aggiudicazione A1_34 per il solo lotto aggiudicato riscontriamo errore "ERR25 - lotIdentifier non trovato"

Riuscite a darci supporto sulla natura dell'errore?
Allego i json:

[ERR25 - jsonInput creaAppalto P1_21.txt](https://github.com/anticorruzione/npa/files/14836941/ERR25.-.jsonInput.creaAppalto.P1_21.txt)
[ERR25 - jsonOutput creaAppalto P1_21.txt](https://github.com/anticorruzione/npa/files/14836942/ERR25.-.jsonOutput.creaAppalto.P1_21.txt)
[ERR25 - jsonInput creaScheda A1_34.txt](https://github.com/anticorruzione/npa/files/14836943/ERR25.-.jsonInput.creaScheda.A1_34.txt)
[ERR25 - jsonOutput creaScheda A1_34.txt](https://github.com/anticorruzione/npa/files/14836944/ERR25.-.jsonOutput.creaScheda.A1_34.txt)

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Non vi è corrispondenza tra l'identificativo dei lotti dichiarati sulla scheda e quelli presenti nell'eform.</p>

<p>Nell'eform allegata alla A1_24 il cig I00323560D corrisponde al lotto "LOT-002" della scheda di indizione, mentre nel CIG I00323560D viene inserito nel lotto: (LOT-0001).</p>

<p>Saluti</p>
