### ISSUE TITLE
tipologiche di riferimento

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#135]
All'interno dell'AnacForm, i campi che prevedono l'uso di tipologiche di riferimento prevedono in input i tag idTipologica e codice.
Dove possiamo reperire l'informazione per poter popolare il tag idTipologica? Inoltre,i campi dataInizio e dataFine presenti nelle tipologiche vanno usati per filtrare tra gli oggetti presenti nel JSON?

**Comment by supportoAnac** [comment]
Le tipologiche sono mantenute in una sezione separata del repository ed esterne allo schema openAPI per gestire con maggiore flessibilità le variazioni. Ogni referenza è soddisfatta dal link presente nello YAML.
