### ISSUE TITLE
funzionamento Modifica Avviso

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1351]
Buongiorno,

avremmo alcune questioni aperte nel funzionamento del modifica avviso:

- dato che è previsto solo per avvisi con pubblicazione europea, se un utente si accorge di aver inserito nei dati sbagliati nella scheda (dopo averla confermata) deve comunque procedere con la pubblicazione dell'avviso e poi rettificare? 
- è disponibile sia per avvisi in stato creato che in attesa di pubblicazione?
- viene generato come per la rettifica un nuovo IDavviso e quello vecchio transita in stato modoficiato?
- nel caso la modifica dei dati riguardi solo campi presenti nell'anacform, è possibile risottomettere lo stesso EFORM? sono previste delle particolarità nel xml del EFORM per fare una modifica?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>in merito alle sue domande, le rispondiamo di seguito:</p>

<ol>
	<li>Si, occore procedere prima alla pubblicazione e poi alla rettifica. </li>
	<li>Il modifica avviso funziona solo per avvisi in attesa di pubblicazione e per avvisi creati.</li>
	<li>SI e vengono anche modificati i CIG (generati nuovi CIG)</li>
	<li>Si aggiornando i campi dell'eform (sia noticeID che version-ID, in caso di modifica solo il version-ID)</li>
	<li>Rispetto ad un eForm normale, occorre che il notice-Id debba avere una version successiva a quella mandata in precedenza.</li>
</ol>

<p>Il modifica avviso quindi può essere inviato anche con lo stesso eForm, ovviamente deve essere coerente anche con la data di trasmissione, in quanto se cambia deve essere cambiato anche il campo della data per non andare incontro ad un errore.</p>

<p>Sperando di essere stati chiari ed esaustivi,</p>

<p>si porgono cordiali saluti.</p>
