### ISSUE TITLE
[ERRORE BLOCCANTE PRODUZIONE] Pubblicazione avviso appalto bloccata

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1356]
Piattaforma SISGAP

In ambiente di produzione è stato creato e confermato l'appalto con id 31479b7f-dd8f-4368-90f1-c38bb37574cf
In data 04/04/2024 è stata richiesta la pubblicazione dell'avviso con id 5361ad3c-fc44-4563-bb94-82d36ead629a per l'appalto con id 31479b7f-dd8f-4368-90f1-c38bb37574cf

in base allo scenario di esempio pubblicato nel vostro repository (https://github.com/anticorruzione/npa/blob/main/docs/scenari-di-esempio/appalto_ordinario_sopra_soglia.md) la sequenza di operazioni indica di controllare la pubblicazione dell'avviso con l'api "stato-avviso".
L'api in produzione non ha mai restituito lo stato dell'avviso "IN_ATT_PUBB" al contrario di tutti gli appalti creati correttamente in collaudo.
Controllando le chiamate di esito-operazione abbiamo notato uno scenario differente rispetto all'ambiente di collaudo. 
Interrogando il servizio ci veniva restituito un esito operazione "AV_RICHIESTA_PUBB_IN_CORSO"

chiamata al servizio esito-operazione su appalto 31479b7f-dd8f-4368-90f1-c38bb37574cf con tipoOperazione AV_PUBB

govway-message-id: b65d19ab-5f30-4ea4-a8d5-606fe65dbecc
govway-transaction-id: dc64371f-f273-11ee-a2a9-00505684399c

response:
{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"31479b7f-dd8f-4368-90f1-c38bb37574cf","idScheda":"3688e769-f7f4-4330-963a-cf64e5f42ee7","codiceScheda":"P1_16","idAvviso":"5361ad3c-fc44-4563-bb94-82d36ead629a","esito":{"idTipologica":"esito","codice":"WT"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AV_PUBB"},"dataControllo":"2024-04-04T13:11:05.713+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AV_RICHIESTA_PUBB_IN_CORSO"}}]}

Richiamando ulteriormente il servizio esito-operazione in data 05/04/2024 abbiamo ottenuto il seguente esito con questo dettaglio "Errore generico durante l'operazione asincrona. Si prega di riprovare." e con esitoOperazione "AV_N_PUBB"

chiamata al servizio esito-operazione su appalto 31479b7f-dd8f-4368-90f1-c38bb37574cf con tipoOperazione AV_PUBB

govway-message-id: b773b58f-0c63-472a-b8ff-fda7f9bd0edd,
govway-transaction-id: f26ded06-f31f-11ee-a2a9-00505684399c

response:
{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"31479b7f-dd8f-4368-90f1-c38bb37574cf","idScheda":"3688e769-f7f4-4330-963a-cf64e5f42ee7","codiceScheda":"P1_16","idAvviso":"5361ad3c-fc44-4563-bb94-82d36ead629a","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AV_PUBB"},"dataControllo":"2024-04-04T13:11:05.713+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AV_N_PUBB"},"errori":[{"idTipologica":"errori","dettaglio":"Errore generico durante l'operazione asincrona. Si prega di riprovare.","codice":"ERR9999"}]}]}

Come consigliato dal messaggio in esito operazione, abbiamo dunque ritentanto la pubblicazione dell'avviso ma, richiamando ora esito-operazione, otteniamo la seguente response con esitoOperazione AV_N_PUBB

govway-message-id: c8479ae1-4ac9-49f5-8bee-e65798361bbe
govway-transaction-id: 6a0f8bd6-f324-11ee-852e-005056844885

response:
{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"31479b7f-dd8f-4368-90f1-c38bb37574cf","idScheda":"3688e769-f7f4-4330-963a-cf64e5f42ee7","codiceScheda":"P1_16","idAvviso":"5361ad3c-fc44-4563-bb94-82d36ead629a","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AV_PUBB"},"dataControllo":"2024-04-05T10:13:35.636+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AV_N_PUBB"},"errori":[]}]}

Questo è un appalto che ha urgenza di partire in produzione. 
Ci servirebbe capire quali sono stati i problemi che hanno portato all'errore non parlante generico "ERR9999".
Quali sono ora i passi da effettuare per avere l'appalto con un avviso pubblicato?

**Comment by RiccardoRiccardi** [comment]
Si sollecita urgente riscontro in quanto trattasi di gara avviata in ambiente di produzione per la quale è stato generato un cig.
Regione Calabria

**Comment by obigno77** [comment]
In questo caso la transazione asincrona di pubblicazione è fallita e, come suggerito dal messaggio di errore, è necessario ritentare la pubblicazione. Si ricorda di utilizzare il canale mail dedicato per le problematiche in ambiente di esercizio

**Comment by masko82** [comment]
Come descritto nella issue è stata ritentata la pubblicazione dell'avviso ma, richiamando esito-operazione, abbiamo ottenuto la seguente response con esitoOperazione AV_N_PUBB

{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"31479b7f-dd8f-4368-90f1-c38bb37574cf","idScheda":"3688e769-f7f4-4330-963a-cf64e5f42ee7","codiceScheda":"P1_16","idAvviso":"5361ad3c-fc44-4563-bb94-82d36ead629a","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AV_PUBB"},"dataControllo":"2024-04-05T10:13:35.636+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AV_N_PUBB"},"errori":[]}]}

**Comment by obigno77** [comment]
Ok abbiamo messo la segnalazione in priorità

**Comment by RiccardoRiccardi** [comment]
Segnalo che, per ogni segnalazione aperta su github, è stata contestualmente inviata un'email a supporto.pcp@anticorruzione.it
dalla quale, tuttavia, non abbiamo mai ricevuto riscontro, a parte la generica risposta che di seguito si riporta:

"Salve, 
la richiesta è stata presa in carico e il nostro gruppo di lavoro sta analizzando la situazione.   
Le verranno inviate ulteriori comunicazioni tramite il canale GitHub.  
Apprezziamo la sua pazienza, mentre lavoriamo per fornirle riscontro.  
Saluti, 
Team Supporto PCP."

Riccardo Riccardi  -  DEC piattaforma sisgap - Regione Calabria

**Comment by obigno77** [comment]
Salve, la notice è stata rifiutata dal Ted perchè al momento della richiesta di pubblicazione erano trascorse oltre 24 ore dalla issueDate indicata nell'eForm. In questi casi è possibile utilizzare il modifica-avviso aggiornando la issueDate e innalzando la versione del noticeID.

**Comment by gianlucacuomo** [comment]
Scusate vorrei riaprire anche segnalazione, perché è capitato anche a noi, sia in collaudo che in produzione l'errore relativo alle 24 ore e purtroppo il WS di modifica-avviso non è più invocabile dopo l'errore del TED. Il flusso si blocca e rifiuta la richiesta per lo stato dell'appalto.

**Comment by masko82** [comment]
Aggiungo che esiste anche una issue in merito al problema sollevato anche da @gianlucacuomo che è la seguente: [https://github.com/anticorruzione/npa/issues/1189](url)
