### ISSUE TITLE
[ Maggioli-BLOCCANTE ] Codice NUTS ITF65 (Reggio Calabria) ancora non funzionante!

### ISSUE THREAD

**Issue by laurapavan** [anticorruzione/npa#1359]
Mi ricollego alla issue #1108.

Ora il codice è presente nella tipologia ma non viene comunque accettato dal sistema:

{"govwayMessageId":"33c2d128-55b6-44ed-831e-5414c1617f67","anacErrors":[{"dettaglio":"tipologica non valida: 'codNUTS' : {'codNUTS' : 'ITF65'}","codice":"ERR63","idTipologica":"errori"}],"done":"N","internalErrors":[],"govwayTransactionId":"e581a6fe-f65b-11ee-9b99-0050568e9679","timestamp":"09/04/2024 12:44:41"}

Vale sia per collaudo che per PRODUZIONE!

Ovviamente è BLOCCANTE.

**Comment by claudiocarotenuto** [comment]
Si sollecita riscontro.
Grazie

**Comment by obigno77** [comment]
Fixato il 30/04

**Comment by laurapavan** [comment]
grazie per la risposta, ma il problema è che non sembra funzionare ancora 
![image](https://github.com/anticorruzione/npa/assets/147838313/fc69d902-140c-4a16-84a7-c269fb259f6c)

Prova di un minuto fa in collaudo:
Data evento: 20/05/2024 08:42:56
Govway Transaction Id: e6ac2aad-1667-11ef-9ec6-0050568e08b3
