### ISSUE TITLE
variazione aggiudicazione

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#136]
Come va gestito lo scenario in cui a seguito dell’aggiudicazione della gara l’utente decide di annullare l’aggiudicazione e procedere ad una nuova aggiudicazione? Occorre inviare una nuova scheda di aggiudicazione?

**Comment by supportoAnac** [comment]
Nel caso di rescissione contrattuale con l'aggiudicatario la piattaforma comunica la chiusura del contratto in corso e la successiva sottoscrizione di un nuovo contratto. La scheda di aggiudicazione NON deve/può essere ritrasmessa.
