### ISSUE TITLE
Errato invio seconda rettifica (ERR50 - operazione non consentita per lo stato dell'avviso)

### ISSUE THREAD

**Issue by CorradoVersolato** [anticorruzione/npa#1361]
Buongiorno, segnaliamo un problema relativo all'invio da piattaforma GGAP di  una seconda rettifica dell'avviso n. 1D96602C-93EE-4CFF-87D3-23C49A097BAC per una procedura P1_16 con 35 lotti (id appalto c8492f30-59c7-4c77-9bc3-6045f6cf805f).

Il codice errore restituito è **ERR50 - operazione non consentita per lo stato dell'avviso**.
Attualmente c'è un disallineamento tra gli importi presenti in PVL e TED (modificato manualmente dall'utente) e la committenza ha urgenza di risolvere il problema.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Da controlli effettuati sui nostri sistemi è emerso che l'ERR50 si manifesta sull'avviso e499bed8-cb93-4ceb-8b37-db16fbef6b72. Mentre si segnala che si vuole fare una rettifica sull'avviso <span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;">1d96602c-93ee-4cff-87d3-23c49a097bac.</span></span></span><br>
<br>
Controllando sui nostri sistmeti non risultano avvisi con idAvviso: <span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;">1d96602c-93ee-4cff-87d3-23c49a097bac.</span></span></span></p>

<p><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;">Gli unici avvisi presenti per l'appalto </span></span></span>c8492f30-59c7-4c77-9bc3-6045f6cf805f, sono:</p>

<ul>
	<li>002da9a3-6762-43a9-a5f4-0edc788ca673 pubblicato in data: 2024-04-03</li>
	<li>e499bed8-cb93-4ceb-8b37-db16fbef6b72 pubblicato in data: 2024-03-05</li>
</ul>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>

<p> </p>
