### ISSUE TITLE
CIG derivato e servizi ANAC

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#137]
Qual è il servizio NPA da richiamare per ottenere il CIG derivato?

**Comment by supportoAnac** [comment]
I CIG derivati non si distinguono dagli altri. Deve essere utilizzato il servizio comunicaAppalto inviando la scheda relativa ad un contratto derivato da AQ/convenzione.

**Comment by supportoAnac** [comment]
I CIG derivati non si distinguono dagli altri CIG; se si intende inviare la adesione ad un accordo quadro esistono le schede specifiche AD4, P6_1, P6_2, P3_3.
