### ISSUE TITLE
[ARIA SPA] indagini di mercato e Negoziata - partecipanti

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1372]
Buongiorno,

in caso di uso scheda P7_1_3 per dare avvio all'indagine di mercato, è possibile poi fare la relativa negoziata invitando anche soggetti che non hanno partecipato all'indagine di mercato?

in particolare, ad un'indagine di mercato ha risposto un OE ma il RUP vorrebbe invitare anche altri 2 OE che presentano i requisiti. come si devono gestire le schede S1 e S2?

si potrebbe comunicare nella S1 solo l'OE che effettivamente ha risposto all'indagine di mercato e poi con la S2 aggiungere anche gli altri due OE effettivamente invitati? può ritenersi corretto muoversi in questo modo o potrebbe presentare delle problematiche l discordanza fra OE nella S1 e nella S2?

**Comment by obigno77** [comment]
La soluzione proposta funziona ma ci riserviamo comunque un approfondimento

**Comment by anac-uscp** [comment]
<p>Dal punto di vista tecnico, ovvero della gestione delle schede, non sussistono elementi ostativi ad una mancata corrispondenza del numero degli operatori fra la scheda S1 e la scheda S2. <br>
<br>
Rimane ferma la necessità di assicurare il rispetto della par conditio fra i concorrenti e di motivare adeguatamente i criteri di scelta degli OE invitati nei successivi atti  per l'avvio della gara.</p>
