### ISSUE TITLE
[Bolzano] - SC1 - chiarimento campo "importo cauzione definitiva in €"

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1376]
Salve,

Un chiarimento sulla scheda SC1 per il campo "importo cauzione definitiva in €" 
Ci chiediamo come mai se il campo viene valorizzato con 0 il sistema da errore in fase di invio della scheda, invece se si inserisce un importo diverso da 0 l'invio va a buon fine ?

Grazie.

**Comment by FedericoSaveri** [comment]
Salve,
il problema sulla scheda SC1 persiste e non è possibile valorizzare il campo con l'importo "0" riceviamo numerose segnalazioni in tal senso, è possibile avere un riscontro sulla problematica e su eventuali tempistiche di risoluzione? 

Grazie

**Comment by anac-uscp** [comment]
<p>Nel prossimo changelog la regola sarà modificata prevedendo che il valore del campo importoCauzione della scheda SC1 sia &gt;=0 e non strettamente &gt;0</p>
