### ISSUE TITLE
Difformità tra P1_16 e P1_23

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1377]
Si chiede conferma della correttezza della presenza del campo "contrattiDisposizioniParticolari" nel campo "appalto" anzichè (come nelle altre schede ad es. P1_16) nel campo "lotti" per ciascun Lotto per la scheda P1_23 relativa ai concorsi di idee e progettazione.

Grazie

**Comment by anac-uscp** [comment]
<p>Risolto con il Changelog del 6/8/2024</p>
