### ISSUE TITLE
 impossibile pubblicare una gara confermata con E-FORM 

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#1379]
Buongiorno
 
Abbiamo problema a pubblicare una gara confermata, in ambiente di produzione 

abbiamo scritto varie segnalazioni all' email dedicato  al ambiente di produzione  (Supporto PCP <supporto.pcp@anticorruzione.it>) man non abbiamo ricevuto nessun riscontro 

Più detagli del caso 
dopo il primo tentativo di pubblicazione in data "dataControllo": "2024-04-03T08:30:29.306+00:00", il primo esito di pubblicazione è “ERR9999" - "Errore generico durante l'operazione asincrona. Si prega di riprovare."
E successivamente tutti i tentativi di pubblicazione sempre hanno un errore di pubblicazione ma non è specificato l’errore da parte della banca dati “Err []”
 
  
•	Piattaforma: PRO-Q 
•	Valore Economico dell’Appalto: 1662500 euro 
•	idAppalto: "0f3937ed-1a6f-45b8-bf7f-ffef401b17a7", 
•	Fase Gara/Scheda : Pubblica_avviso / P1_16. 
•	Errore riscontrato: errore non segnalato dalla banca dati. 
•	Govway Transaction id: "26682da3-f68c-11ee-852e-005056844885". 
•	Allegati: esempio di risposta esito pubblicazione.

  
Per una vostra comodità vi allego una risposta per esito pubblicazione restituito dalla banca dati 
 
   {
            "idAppalto": "0f3937ed-1a6f-45b8-bf7f-ffef401b17a7",
            "idScheda": "9035010c-341f-4a76-a717-ab7783b2e4f4",
            "codiceScheda": "P1_16",
            "idAvviso": "75bb62b1-295d-4056-97ec-f058f0c99ab0",
            "esito": {
                "idTipologica": "esito",
                "codice": "KO"
            },
            "tipoOperazione": {
                "idTipologica": "tipoOperazione",
                "codice": "AV_PUBB"
            },
            "dataControllo": "2024-04-09T18:17:46.069+00:00",
            "dettaglio": {
                "idTipologica": "esitoOperazione",
                "codice": "AV_N_PUBB"
            },
            "errori": []
        },
 
 
 Saluti

**Comment by obigno77** [comment]
In carico al supporto in esercizio

**Comment by obigno77** [comment]
In carico al supporto in esercizio
