### ISSUE TITLE
[Consip][high priority] - cambio dei CIG dopo modifica-avviso

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1381]
Salve,
abbiamo constatato che dopo aver chiamato il servizio **modifica-avviso** i CIG non sono più quelli precedentemente recuperati ma c'è una riassegnazione dei CIG.
si tratta di un errore? non troviamo riscontro nella documentazione che ci sia un cambio dei cig dopo la chiamata del modifica-avviso. 

Grazie

**Comment by obigno77** [comment]
Non è un errore. E' stata aggiornata la documentazione del servizio modifica-avviso
