### ISSUE TITLE
[ARIA SPA] campo importo per le schede A

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1386]
Buongiorno,

nella schede A, in riferimento alle offerte presentate viene richiesto il campo "importo" riferito all'offerta. questa deve essere sempre indicata al netto dei costi? quindi offerta riferita alla base d'asta soggetta al ribasso e al netto, ad esempio, dei costi della sicurezza derivanti da interferenza?

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">Il campo "importo" riferito all'offerta è comprensivo dei costi della manodopera e della sicurezza e di altri eventuali costi non soggetti al ribasso.</span></span></span></p>

<p style="margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">GdL Dati</span></span></span></p>
