### ISSUE TITLE
[Consip] Ambiente di Collaudo_ INCONGRUENZA TRA RESPONSE INOLTRATA E DATA MODEL DEFINITO

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1388]
Abbiamo riscontrato un'incongruenza tra la response inoltrata (ConsultaSchedaResponse) e il data model utilizzato. 
Nel dettaglio, dai log abbiamo evidenza che in response ci viene inoltrato un attributo "dataModifica" non previsto nel modello dati definito. 
![MicrosoftTeams-image (42)](https://github.com/anticorruzione/npa/assets/163398500/af2946d0-3f0a-4954-9d55-c11b91086e80)
![MicrosoftTeams-image (41)](https://github.com/anticorruzione/npa/assets/163398500/0dac8b40-800d-4d49-8f96-c4d4f6d0e6f1)

Sono in corso aggiornamenti del data model in ambiente di collaudo?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>é stata effettuata una modifica al modello dati introducendo per l'oggetto SchedaPostPubblicazioneType l'attributo dataModifca.<br>
<br>
Restiamo a disposizione.<br>
<br>
Cordiali saluti</p>
