### ISSUE TITLE
identificativo stazione appaltante

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#139]
All'interno delle schede di indizione come è identificata la Stazione Appaltante si usa un dizionario comune, si può indicare Il CF della SA, vi è una tipologica di riferimento? Qual è il claim di riferimento all'interno del payload. Oppure l'RP si registra preventivamente su ANAC con l'id della stazione appaltante e quindi preventivamente si crrea questo link?

**Comment by supportoAnac** [comment]
Lo schema dati prevede il codice fiscale dell'amministrazione. Il RP deve essere preventivamente registrato sui nostri sistemi e associato all'amministrazione indicata nel payload per essere autorizzato all'accesso.
