### ISSUE TITLE
[ARIA SPA] concessioni fra 5k e limite affidamento diretto

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1391]
Buogiorno,

non risulta chiaro dall'orchestratore (dato che le descrizioni non combaciano con lo swagger) se per le concessioni fra i 5k e i limiti per l'affidamento diretto debba essere usata la scheda AD3 o AD2_28.

Grazie

**Comment by anac-uscp** [comment]
<p>Si precisa che al di fuori dei casi previsti dall'art. 182 comma 7, per i quali si deve utilizzare la scheda AD2_28, per l'affidamento dei contratti di concessione al di sotto della soglia comunitaria non è ammesso ricorrere all'affidamento diretto ma alla procedura negoziata di cui all'art. 187.</p>

<p> </p>
