### ISSUE TITLE
Casi di Test FVOE non più validi - Errore FVX32 su richiedi-documento

### ISSUE THREAD

**Issue by FrancescaBrindisiL** [anticorruzione/npa#1394]
Salve,
a seguito del rilascio di giorno 05-04-24 riguardante l'accesso al Fascicolo Virtuale dell'Operatore Economico i Codici Fiscali rilasciati per i test non risultano più validi.

In particolare:

- La richiesta di accesso FVOE (**richiesta-accesso-fvoe**) con i dati forniti ora produce un errore **HTTP 400 - Dato non trovato**.

I dettagli della chiamata sono:
CF: 11111111114
GovWay-Message-ID: ec10aec8-0c6d-4ade-bd1d-871e552dd3cb
GovWay-Transaction-ID: d07a5bd3-f645-11ee-9ec6-0050568e08b3

- La richiesta di documento (**richiedi-documento**) effettuata a partire dall'ultima richiesta di accesso approvata su un Fascicolo Virtuale Operatore Economico, restituisce un messaggio di errore **HTTP 500 - Operazione terminata con Errore**, segnalando come tipologica errore “**FVX32**”.
 
I dettagli della chiamata sono:
CF: 11111111113
Chiave di accesso: 1c9242b6-1cea-4d70-8a31-8bbbe1c5723c
GovWay-Message-ID: e06b4030-0603-4806-b58e-7ec53edc780c
GovWay-Transaction-ID: ead29741-f645-11ee-9b99-0050568e9679

Ringrazio per l'attenzione e resto a vostra disposizione per eventuali ulteriori dettagli che possano portare alla risoluzione del problema.
Cordiali Saluti

**Comment by stalex1** [comment]
Gentile Utente,


I log del microservizio non sono più presenti per un'analisi di dettaglio.

1)Il 404 viene restituito quando il fascicolo su cui si richiede l'autorizzazione non esiste, il 400 quando la richiesta è malformattata. Esempio: idAppalto passato non valido. Dal 01/07/2024 la propagazione dei documenti verso il fascicolo del concorrente è stata riabilitata.
Esempio request

{
  "dataInizioAutorizzazione": "2024-01-23T12:02:05Z",
  "dataFineAutorizzazione": "2024-12-23T12:02:05Z",
  "operatoriEconomici": [
    {
      "codiceFiscale": "11111111113"
    },
    {
      "codiceFiscale": "11111111114"
    }
  ],
  "appalto": {
    "idAppalto": "930e3a70-7b19-4f50-b78f-2bc2891f816d"  (un uuid di un appalto confermato proveniente dalla vostra stazione appaltante)
  }
}

2) L'FVX32 è stato lanciato per un errore temporaneo del servizio interno che controlla il token di govWay. Si prega di ripetere l'operazione.


Restiamo a disposizione,

 

Cordiali Saluti
