### ISSUE TITLE
[ARIA SPA] Annullamento aggiudicazione

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1395]
Buongiorno,

a seguito di richiesta degli  utenti che utilizzano la piattaforma, non risulta chiaro come gestire correttamente l'annullamento di una aggiudicazione.

in particolare, in caso di annullamento aggiudicazione è necessario effettuare una rettifica dell'aggiudicazione?
la casistica si presenta sia in caso di appalti con sola pubblicazione nazionale sia con appalti con pubblicazione a livello anche europeo. Se è previsto l'eFORM come va correttamente compilato per dare indicazione dell'annullamento?
Inoltre, in caso l'annullamento si debba gestire con la rettifica dell'avviso deve essere inviata dopo la scheda A anche la scheda SC1 per concludere il ciclo di vita del lotto?

Grazie

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">No, per annullare l’aggiudicazione, sia in caso di appalti con sola pubblicazione nazionale sia per appalti con pubblicazione a livello europeo, non si può inviare una richiesta di rettifica dell’avviso ma bisogna inviare una scheda di conclusione CO1, valorizzando il campo <strong>causaInterruzioneAnticipata </strong>che prevede la voce ‘Revoca dell'aggiudicazione definitiva’ la quale dà la possibilità di chiudere definitivamente la procedura oppure eventualmente di proseguire con la stipula del contratto con un nuovo aggiudicatario.</span></span></span></p>
