### ISSUE TITLE
[ARIA SPA] Variazione soggettiva

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1396]
buongiorno,

per gestire una variazione soggettiva di un aggiudicatario deve essere inviata la scheda S4?

Grazie

**Comment by anac-uscp** [comment]
<p>Si, la scheda S4 'Variazione Aggiudicatari/Costituzione della società di scopo' è utilizzata per gestire la variazione della composizione dell'aggiudicatario.</p>
