### ISSUE TITLE
Gestione FVC (oppure FVOE come si deve chiamare!!??!!) servizio richiedi-documenti

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1397]
Anche se il nome del servizio indica una pluralità di documenti, la documentazione precede l'inserimento di una richiesta per un singolo documento.
Inoltre non è chiaro se i datiRichiesta siano obbligatori per le tipologie di documento che li richiedono (nella documentazione sono opzionali) e quali controlli sono previsti (non mi pare esistano regole dmn per l'FVOE). In ogni caso per in casellario giudiziario (tipoDocumento= 00004) vengono richiesti i dati anagrafici del soggetto di cui si richiede il certificato e il campo AltriDati (perchè l'"A" è maiuscola? :-)) che contiene un campo dal significato poco chiaro. Allego una screen shoot per chiarire
![image](https://github.com/anticorruzione/npa/assets/137269683/c6bc8129-a1d1-492b-b555-26bf2b74215f)
Non mi è chiaro il collegamento tra l'etichetta e la descrizione del campo. è un refuso??

P.S. credo che ci sia una importante differenza tra la documentazione della PCP e quella dell'FVOE / FVA il gap esistente andrebbe colmato.

**Comment by stalex1** [comment]
Gentile Utente,


1) Nell'attuale versione il servizio permette la richiesta di una sola tipologia di documento alla volta.


2) Per la definizione del modello dati e delle regole, si rimanda alla documentazione presente su questo url: https://github.com/anticorruzione/npa/blob/main/CHANGELOG.md#modello-dati-8  " note di rilascio 05/04/2024",

   nel documento principale è stato aggiunto il paragrafo (11.3) : https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md#113tipi-documento-richiedibili-agli-enti-certificanti

   che riporta ad una pagina specifica che dettaglia la mappatura del tipo documento richiedibile, quale modello dati valorizzare.  

   https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md .


3) Per identificare il modello dati da passare è necessario valorizzare l'attributo "Type" (segnato in grassetto senza " Underscore _ " ).   

Scenario di esempio: 

{
  "chiaveAccesso": "f209a5fc-99f0-4764-98ae-464f8cd7596a",
  "tipoDocumento": {
    "codice": "00005"
  },
  "type": "DatiSA00020", 
  "datiRichiesta": {
    "DatiNominativo": {
      "DenominazioneSociale": "Fuoco & C",
      "CodiceFormaGiuridica": "AG",
      "PIVA": "22222222222",
      "DatiSedeSociale": {
        "Indirizzo": "Via del Fuoco",
        "CodiceCatastoStato": "Z200"
      }
    },
    "AltriDati": {
      "LinguaTedesca": false
    }
  }
}

4) AtriDati.LinguaTedesca indica la lingua con cui produrre il documento. L'attuale descrizione è un refuso.

E' previsto in futuro l'aggiornamento della documentazione con gli scenari d'esempio, data da definire. 
la dismissione del vecchio servizio sarà comunicato sul sito github di ANAC.  


Restiamo a disposizione.
