### ISSUE TITLE
Variazioni aggiudicatari e variazione soggettiva - richiesta chiarimenti

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1399]
Buongiorno,

riprendo la issue #820 in quanto non risulta chiaro come gestire correttamente le casistiche per la riaggiudicazione:

- in caso di scheda A già inviato in cui è stato indicato un OE come aggiudicatario, in caso di riaggiudicazione del lotto deve essere rettificata la scheda A o è sufficiente inviare la SC1 con indicazione di un altro OE con cui si è firmato il contratto?

Dato che in eFORM non è necessario specificare l'aggiudicatario non si dovrebbero presentare casistiche differenti fra pubblicazione anche al TED o solo nazionale.

**Comment by obigno77** [comment]
E' sufficiente inviare la nuova SC1
