### ISSUE TITLE
Tipologie di chiamate al TED

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#14]
Quali tipologie di gare devono essere inviate al TED? Esiste un attributo dell’appalto o dell’avviso da passare ai servizi (per esempio pubblicaAvviso) per definire se quell’appalto va pubblicato o no sul TED (ad esempio un flag)?

**Comment by supportoAnac** [comment]
Lo schema delle regole di orchestrazione delle schede è consultabile nella cartella "orchestratore". In particolare la colonna "pubblicazioneTED" indica se per una specifica scheda è prevista la pubblicazione sul TED.

**Comment by OperatoreIT** [comment]
<p>Gentile Utente, <br>
<br>
in data 11/07 è stata rilasciata una fix che risolve le incompatibilità rilevate nella richiesta documenti verso AdE e Ministero della Giustizia.<br>
<br>
La problematica risulta essere stata sanata. <br>
<br>
Si chiede di riprovare. <br>
<br>
Restiamo a disposizione<br>
<br>
Cordiali Saluti </p>
