### ISSUE TITLE
Invio eForm aggiudicazione (ContractAwardNotice) via eSender su bandi pubblicati a mezzo eNotice2

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#140]
Buongiorno, 
attualmente non è possibile inviare via eSender avvisi di aggiudicazione (F03) su bandi (F02) pubblicati a mezzo eNotice, ci si domanda se tale vincolo persisterà anche dal 25 ottobre 2023 con l'obbligo di utilizzo degli eForm perché, in considerazione del fatto che le stazioni appaltanti dovranno obbligatoriamente utilizzare eNotice2 per la pubblicazione di bandi dal 25 ottobre 2023 (non essendo disponibili i servizi di eSender ANAC) ci si chiede se dal 1° gennio 2024 potranno inviare le  Contract Award Notices a mezzo ANAC anche se il relativo bando è stato pubblicato utilizzando eNotice2 o se invece per le procedure bandite dal 25 ottobre al 31 dicembre l'invio delle stesse dovrà avvenire a mezzo eNotice2.

**Comment by supportoAnac** [comment]
Se è confermata la impostazione del TED indicata in premessa, non sarà possibile inviare avvisi di aggiudicazione per bandi non pubblicati su PCP.

**Comment by pietropalermoIT** [comment]
Non vedo la relazione tra quanto fa il TED e l'utilizzo dei servizi di PCP.
Cerco di proporre il quesito in modo differente:
- per i bandi non pubblicati in interoperabilità a mezzo PCP sarà possibile inviare l'aggiudicazione a mezzo PCP? 
- per i bandi aggiudicati a cui si è data pubblicità non in interoperabilità a mezzo PCP, sarà possibile poi ottenere CIG derivati in interoperabilità o inviare schede della fase di esecuzione?
