### ISSUE TITLE
[BLK][Teamsystem]- Scheda A1_33 - ERR2 - Scheda non ammessa in questa fase dell'appalto

### ISSUE THREAD

**Issue by mcgirone** [anticorruzione/npa#1401]
In ambiente di collaudo, in seguito alla pubblicazione di una P1_20 ed all'invio corretto della scheda S2, ANAC non accetta la scheda di aggiudicazione A1_33. In allegato i json di riferimento.

[crea-scheda_A1_33_Request.json](https://github.com/anticorruzione/npa/files/15149762/crea-scheda_A1_33_Request.json)
[crea-scheda_S2_Request (3).json](https://github.com/anticorruzione/npa/files/15149763/crea-scheda_S2_Request.3.json)
[crea-appalto_P1_20_Request (1).json](https://github.com/anticorruzione/npa/files/15149764/crea-appalto_P1_20_Request.1.json)

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Da controlli effettuati sui nostri sistemi è emerso che la scheda S2 inviata non contiene alcun dato: per poter proseguire nel processo di invio schede occorre prima inviare una Scheda S2 con l'elenco dei soggetti: in particolare va indicato il CIG e l'elenco dei partecipanti. Una volta creata e confermata la scheda S2 con cig associato si può procedere con l'invio della scheda A1_33.</p>

<p>Cordiali saluti.</p>
