### ISSUE TITLE
Probabile errore su orchestratore per fase esecutiva con le schede RSU1 - ES1 - CS1

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#1402]
Scenario: Utente ha correttamente confermato la SC1:
Lo stesso utente ha poi correttamente confermato RSU1 e ES1 come previsto da orchestratore
Ora sta provando a mandare la I1 ma il sistema anac mi risponde:
“La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata”
In effetti da orchestratore dopo la ES1 sono previste solo:M1,M1_40,M2,M2_40,SA1,RSU1,SO1,AC1,IR1,CO1, CS1, ES1,RI1,CL1,S4,S3 
quindi non la I1 ma credo sia un errore – NOTA: Lo stesso errore credo ci sia per la RSU1 e la CS1 che non prevedono la I1
Ma se dopo la SC1 posso fare la RSU1 dovrei dopo poter fare la I1 dopo il subappalto altrimenti non ho più modo di farla.

**Comment by anac-uscp** [comment]
<p>Non è esclusa la possibilità di fare una richiesta di subappalto tra la firma del contratto e l’effettivo avvio delle prestazioni per cui l'orchestratore sarà modificato in modo da prevedere l'invio della scheda I1 'Avvio dell'esecuzione' dopo una scheda RSU1 'Comunicazione richiesta di subappalto per qualunque procedura'.</p>

<p>E' esclusa la possibilità di avviare un subappalto prima della consegna dei lavori all'impresa ovvero prima dell'avvio dell'appalto. Per tale motivo è quindi esclusa la possibilità di inviare una scheda 'Avvio dell'esecuzione' I1 dopo una scheda ES1 'Esito Richiesta subappalto Autorizzazione/diniego subappalto' o dopo una scheda SC1 'conclusione subappalto' o dopo una scheda di 'conclusione', scheda CO1 o dopo il 'collaudo', scheda CL1.</p>

<p>E' da tenere in conto la tempistica della consegna dei lavori che deve avvenire entro 45 giorni dopo la firma del contratto.</p>
