### ISSUE TITLE
FVC : Servizio richiedi-documenti - tipo documento 00899 - Documento generico OE

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1403]
non è chiaro quale processo viene innescato per l'ottenimento del documento richiesto nè chi sia il soggetto a cui viene inviata la richiesta dello stesso.
Sarebbe utile conoscere tali informazioni per utilizzare al meglio il servizio richiedi-documenti

P.S. ma il servizio richiedi-documento (quello in GET) verrà dismesso oppure no??

**Comment by obigno77** [comment]
Sarà pubblicata la mappa di corrispondenza tra documento ed ente certificante.
Il servizio in get sarà dismesso,
