### ISSUE TITLE
[CONSIP] -BLK- A2.29 rimane in WT dopo conferma-scheda

### ISSUE THREAD

**Issue by LucariniPaola** [anticorruzione/npa#1405]
inviando la scheda A2.29 dopo aver chiamato il CONFERMA_SCHEDA, lo stato della scheda rimane IN_LAV e l'esito operazione è sempre il seguente:
  "listaEsiti": [
    {
      "idAppalto": "ce3dddec-7464-47e0-a987-7d08d756e9ad",
      "idScheda": "1201f073-5b98-4961-9166-6fd075f16339",
      "codiceScheda": "A2_29",
      "esito": {
        "idTipologica": "esito",
        "codice": "WT"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "SC_CONF"
      },
      "dataControllo": "2024-04-30T11:25:29.925+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "SC_IN_CONF"
      }
    }

govway message = [8477e930-0944-41f8-9cd1-7b8eb035613a]
govway transaction = [f024e17d-06e9-11ef-9ec6-0050568e08b3]

**Comment by obigno77** [comment]
Si prega di risottomettere la conferma
