### ISSUE TITLE
[ARIA SPA] Consorzio stabile - compilazione scheda S

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1407]
Buongiorno,

un utente ci chiede riscontro per il corretto modo di compilare un consorzio stabile con l'invio della scheda S2.

in particolare, dovrà inserire tutte le società esecutrici del consorzio stabile che invia l'offerta, oppure soltanto la capofila del consorzio stabile?

è corretto presupporre che gli OE che devono essere verificate tramite fascicolo devono in qualche modo essere inseriti nella scheda S2?

Grazie

**Comment by obigno77** [comment]
E' corretto. Vanno indicati tutti i soggetti che devono essere verificati sul FVOE.
