### ISSUE TITLE
[CONSIP] AD1.28 - ERR41 al click su Verifica - Errore generico

### ISSUE THREAD

**Issue by LucariniPaola** [anticorruzione/npa#1408]
per la scheda ad1.28 dopo aver chiamato conferma-al click su VERIFICA il sistema mostra l'ERR41 "Errore generico durante la validazione dei dati della scheda"

"GovWay-Message-ID":["8ca24be2-9d88-4416-98ba-0a8cf8f526d4"]
"GovWay-Transaction-ID":["c0e19c70-06f5-11ef-9b99-0050568e9679"]

ID APPALTO : d044f14c-95a2-405d-a289-d99491bb7fbc

**Comment by anac-uscp** [comment]
<p>Gentile Utente</p>

<p>Replicando la sua situazone nei nostri sistemi risulta l'errore 4 derivante da un codice appalto con lunghezza minore di 8 caratteri.</p>

<p>Pertanto la invitiamo ad inserire un codice appalto valido e ritentare con la conferma.</p>

<p> </p>

<p>Restiamo a disposizione</p>

<p> </p>

<p>Cordiali Saluti</p>
