### ISSUE TITLE
chiarimenti elenco errori

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#141]
Riguardo la tipologica errori.json ci sembra di evincere che :
tutti gli errori per i quali il codice presenta il prefisso "ERR" vengono restituiti in modo SINCRONO (response 400 ad esempio)
tutti gli errori per i quali il codice presenta il prefisso "REG" vengono restituiti in modo ASINCRONO
è corretto? per trovare la descrizione di un errore dobbiamo chiamare un servizio ad hoc (es. recupera-valore-tipologica) che va ad erodere il numero di chiamate giornaliere.
è corretto?

**Comment by supportoAnac** [comment]
Il prefisso non è significativo. Il codice di errore non ha nessun significato. Il significato dell'errore è contenuto nel messaggio di errore. 
La tabella degli errori è pubblicata sul repository ed è invocabile tramite il servizio servizi-comuni.recupera-tipologica. 
Al momento PDND non applica nessun blocco al superamento della soglia di chiamate giornaliere. ANAC non prevede tale limite.
