### ISSUE TITLE
ARIA SPA - FVOE - IMPOSSIBILITA' DI PRESTARE AUTORIZZAZIONE FVOE 2.0

### ISSUE THREAD

**Issue by RiccardoCarelli** [anticorruzione/npa#1410]
Buongiorno,
vi segnaliamo che un nostro operatore economico nell'utilizzo dell'applicativo FVOE 2.0 ha riscontrato la seguente problematica:
inserendo una P.iva diversa dal Codice Fiscale, ossia non univoci, l'operatore economico non riesce a visualizzare le richieste di accesso al fascicolo da parte di ARIA.

L'assistenza ANAC conferma la presenza di un bug nel sistema FVOE 2.0, in quanto inserendo P.iva e Codice Fiscale non univoci  il sistema non li riconosce e non li aggancia. Pertanto, l'operatore economico è impossibilitato a visualizzare la richiesta.

Vi chiediamo pertanto come poter procedere in tale circostanza e quando tale bug verrà risolto.
Grazie

**Comment by obigno77** [comment]
Non si tratta di un bug. Il sistema riconosce gli operatori economici esclusivamente per codice fiscale.
