### ISSUE TITLE
Tipologica codNUTS - Problema Extra-Regio NUTS

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1411]
Abbiamo notato che nella tipologica codNUTS ci sono molti codici che condividono la stessa descrizione, rendendo difficile identificare la regione di appartenenza della zona Extra-Regio. Per esempio su **BEZ** o **CYZ**:

```json
{
    "codice": "BEZ",
    "descrizione": {
      "it": "Extra-Regio NUTS 1",
      "en": "Extra-Regio NUTS 1"
    },
    "dataInizio": null,
    "dataFine": null
  }
```

```json
{
    "codice": "CYZ",
    "descrizione": {
      "it": "Extra-Regio NUTS 1",
      "en": "Extra-Regio NUTS 1"
    },
    "dataInizio": null,
    "dataFine": null
  }
``` 

Sarebbe molto comodo se le descrizioni venissero modificate indicando la regione di appartenenza, in modo da poter fornire all'utente finale una definizione più leggibile.

Grazie mille!

**Comment by anac-uscp** [comment]
<p>La tipologica eredita direttamente le specifiche della classificazione NUTS di Eurostat (vedi https://ec.europa.eu/eurostat/web/nuts/overview) e non può essere unilateralmente modificata da ANAC.</p>
