### ISSUE TITLE
[Consip] chiarimenti - aggiudicazione dopo P7_2

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1414]
dopo aver inviato la scheda P7_2 non è previsto l'invio di una scheda di aggiudicazione?
stesso dubbio per le schede P6_1 e P6_2.

Grazie

**Comment by paolo-urbanetto** [comment]
Buongiorno, 
anche noi [Maggioli] saremmo interessati...  uniamo a questa le precedenti identiche richieste  [496](https://github.com/anticorruzione/npa/issues/496) del 30/10/2023 e successiva del 1/2/2024 [1083](https://github.com/anticorruzione/npa/issues/1083).

Grazie

**Comment by pg-volpentesta** [comment]
è possibile avere un aggiornamento sul tema?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Come indicato sull'orchestratore, dopo aver inviato la scheda P7_2, è possibile inviare la scheda di aggiudicazione S2.</p>

<p>Situazione analoga per le schede P6_1 e P6_2 le quali prevedono l'invio della scheda di aggiudicazione S2.</p>

<p>Cordiali saluti.</p>

<p> </p>

<p> </p>

**Comment by anac-uscp** [comment]
<p>Sulla base dei seguenti flussi di aggiudicazione legati alla scheda P7_2:</p>

<table cellspacing="0">
	<tbody>
		<tr>
			<td><strong>Importo</strong></td>
			<td><strong>tipo di contratto</strong></td>
			<td><strong>tipo di settore</strong></td>
			<td><strong>tipo di regime</strong></td>
			<td><strong>scheda avvio</strong></td>
			<td><strong>scheda aggiudicazione</strong></td>
			<td><strong>note</strong></td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>appalto </td>
			<td>ordinario </td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_1</td>
			<td>trasmissione al TED dell'eform 25-avviso volontario sulla trasparenza preventiva</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>appalto </td>
			<td>ordinario </td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_2</td>
			<td>Nessuna trasmissione al TED</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>appalto </td>
			<td>speciale</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_1</td>
			<td>trasmissione al TED dell'eform 26-avviso volontario sulla trasparenza preventiva</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>appalto </td>
			<td>speciale</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_2</td>
			<td>Nessuna trasmissione al TED</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>appalto </td>
			<td>difesa e sicurezza (dlgs. 208/11)</td>
			<td>n/a</td>
			<td>P5/P7_2</td>
			<td>n/a/A7_1_1</td>
			<td>contratto escluso : PCP+interfaccia web<br>
			A7_1_1 con trasmissione al TED dell'eform 27-avviso volontario sulla trasparenza preventiva</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>concessione</td>
			<td>n/a</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_1</td>
			<td>trasmissione al TED dell'eform 28-avviso volontario sulla trasparenza preventiva</td>
		</tr>
		<tr>
			<td>pari o sopra soglia</td>
			<td>concessione</td>
			<td>n/a</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A7_1_2</td>
			<td>Nessuna trasmissione al TED</td>
		</tr>
		<tr>
			<td> </td>
			<td> </td>
			<td> </td>
			<td> </td>
			<td> </td>
			<td> </td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>appalto </td>
			<td>ordinario </td>
			<td>ordinario</td>
			<td>P7_2</td>
			<td>A_2_29</td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>appalto </td>
			<td>ordinario </td>
			<td>alleggerito</td>
			<td>P7_2</td>
			<td>A_2_33</td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>appalto </td>
			<td>speciale</td>
			<td>ordinario</td>
			<td>P7_2</td>
			<td>A_2_30</td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>appalto </td>
			<td>speciale</td>
			<td>alleggerito</td>
			<td>P7_2</td>
			<td>A_2_34</td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>concessione</td>
			<td>n/a</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A_2_32</td>
			<td> </td>
		</tr>
		<tr>
			<td>sotto soglia</td>
			<td>concessione</td>
			<td>n/a</td>
			<td>ordinario/alleggerito</td>
			<td>P7_2</td>
			<td>A_2_35</td>
			<td> </td>
		</tr>
	</tbody>
</table>

<p>l'orchestratore sarà modificato a breve come segue:</p>

<ul>
	<li>Introdurre nella colonna ‘flussoAppartenenza’ delle schede A7_1_1, A7_1_2, A2_29, A2_30, A2_32, A2_33, A2_34, A2_35, il flusso 72</li>
</ul>
