### ISSUE TITLE
[Toscana/Bolzano] - Scheda NAG ERR2 - scheda non ammessa in questa fase dell'appalto 

### ISSUE THREAD

**Issue by CecereAnto** [anticorruzione/npa#1417]
Salve, 
stiamo riscontrando il seguente errore: ERR2 - scheda non ammessa in questa fase dell'appalto nel momento in cui si trasmette una scheda NAG dopo l'invio della scheda P7_1_3 che è andata deserta. 
In allegato il json di input. 
[NAG.json](https://github.com/anticorruzione/npa/files/15247061/NAG.json)
[P7_1_3.json](https://github.com/anticorruzione/npa/files/15247062/P7_1_3.json)

Riuscite a darci supporto?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Siamo a conoscenza della situazione e abbiamo già avviato le procedure necessarie per risolvere la problematica che verrà fixata orientativamente nel mese di Dicembre.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
