### ISSUE TITLE
Cancellazione appalto e avviso in ambiente di produzione

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1419]
Con riferimento a quanto accaduto e segnalato nella issue https://github.com/anticorruzione/npa/issues/1356 stiamo tentando di cancellare l'appalto con id 31479b7f-dd8f-4368-90f1-c38bb37574cf  e il relativo avviso con id 5361ad3c-fc44-4563-bb94-82d36ead629a

Abbiamo provato inizialmente la cancellazione dell'appalto ma ci è stato restituito il seguente errore:

ERR16: operazione non consentita per lo stato dell'appalto
govway-message-id: 3d3984b1-665a-4456-b255-79241aa18b6e
govway-transaction-id: c7c1df72-0d49-11ef-a2a9-00505684399c

Da una rapida ricerca nelle issues abbiamo appurato che una volta che si è richiamato il servizio "pubblica-avviso" non è più possibile utilizzare la cancellazione dell'appalto.

A questo punto per poter far transitare l'appalto in uno stato finale abbiamo tentato la cancellazione dell'avviso ma abbiamo ottenuto il seguente errore:

ERR51: operazione non consentita per lo stato dell'avviso sul TED
govway-message-id: c13474bd-81d7-4102-9b67-0c6c8fd94474
govway-transaction-id: 3b175391-0d4a-11ef-852e-005056844885

Attualmente l'appalto in questione risulta nello stato "CONF" tramite il servizio di consulta-appalto e tramite stato-appalto risulta in "IN_ATT_PUBB", mentre l'avviso nello stato "NON_PUBB".

Dato che questo appalto si può ritenere "errato", in quanto ci è stato consigliato di crearne uno nuovo, vorremo sapere qual è la procedura corretta per poterlo cancellare logicamente, così da non lasciare nulla di appeso o in sospeso.

**Comment by anac-uscp** [comment]
<p>Gentile utente,<br>
 </p>

<p>Un appalto confermato non può più essere cancellato, nè fisicamente nè logicamente. in questa fase soltanto l'avviso è l'entità interessata.<br>
Tuttavia essendo l'avviso non pubblicato, il problema non persiste: in questa fase, la pcp offre i servizi di sospensione se l'avviso è attualmente pubblicato oppure di cancellazione se l'avviso è in coda per la pubblicazione, ma dal momento che l'avviso è stato scartato dal ted per altri motivi non sono necessari ulteriori step, l'appalto può essere lasciato cosi com'è in quanto non è utilizzabile da nessuno salvo la SA che può comunque soltanto riprovare la pubblicazione.</p>

<p>Restiamo a disposizione.</p>

<p>Cordiali saluti</p>
