### ISSUE TITLE
verifica esito operazione - time to process

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#142]
Vorremmo sapere ogni quanto permettere (da parte del sistema o dell'utente) la verifica dell'esito di una operazione (ad esempio dopo aver eseguito il conferma-appalto).
Che criterio dobbiamo utilizzare?
è lecito permettere ad esempio una richiesta ogni x minuti? Oppure, visto che dopo le 18 non vengono processate le operazioni asincrone, è lecito non permettere chiamate dopo le 18?
Ci serve un driver per questa operazione.

**Comment by supportoAnac** [comment]
L'operation servizi-comuni.esito-operazione è realizzato in modo da sostenere elevate frequenze di accesso. ANAC, al momento, non pone limiti di chiamate. 
Nel sistema a regime potranno essere imposti limiti di accesso nel caso di uso improprio dei servizi.
Il limite delle 18.00 è amministrativo, e riguarda solo alcune operazioni.
