### ISSUE TITLE
[Consip][BLK] Pubblicazione in errore

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1420]
Salve, 
ci siamo accorti che quando la pubblicazione va in errore (pubblica-avviso) alcune volte lo stato dell'avviso permane in CREATO, altre volte è NON_PUBB.
quando rimane in CREATO e quando è NON_PUBB?
inoltre, se la scheda prevede Eform, si può chiamare il modifica-avviso in entrambi i casi per ritentare la pubblicazione?
sono in corso degli sviluppi per la gestione della pubblicazione in errore, pertanto, avremmo bisogno di una risposta.
grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Per la prima domanda: lo stato rimane in "creato" quando no si è ancora inoltrata la pubblicazione o si è inoltrata ma ci sono stati problemi con il servizio. lo stato "non_pubb" indica che presso il TED l'avviso è stato scartato per qualche ragione esterna ai servizi PCP e quindi non è un errore dovuto al servizio.</p>

<p>Per la seconda domanda: in entrambi i casi si può invocare il servizio "modifica avviso" che è invocaible solo per avvisi che prevedono pubblicazione sul ted e di cui è stato effettuato un primo inoltro ma non risultano pubblicati o risultano in coda per la pubblicazione.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
