### ISSUE TITLE
Contesto FVOE (FVC) Servizio recupera-documenti campo datiRichiesta sottocampo DatiSA_00020

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1425]
Nel campo descritto (vedi immagine) è presente un campo PIVA che come descrizione ha codice fiscale soggetto e come espressione regolare quella che fa riferimento ad un campo di 11 caratteri (codice fiscale di soggetto giuridico a meno di casi particolari quali ditte individuali, artigiani, etc. etc.)
![image](https://github.com/anticorruzione/npa/assets/137269683/e48fb1e6-5c8d-4e0a-9337-8613eaff8a8e)

Si richiede la correzione del nome del campo allo scopo di fugare ogni dubbio sulle informazioni richieste e, se necessario, aggiungere alla espressione regolare anche la forma a 16 caratteri per gli artigiani e le imprese individuali.

**Comment by obigno77** [comment]
Il nome è corretto. Dobbiamo correggere la descrizione
