### ISSUE TITLE
[BLK] - pubblicazioni nazionali in WT

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#1426]
In ambiente di qualificazione, tutte le pubblicazioni nazionali restituiscono esito WT e non vanno in attesa di pubblicazione.
è possibile risolvere tale problematica per permetterci di proseguire nei test?
Grazie

**Comment by LucaMaggioni1** [comment]
anche noi riscontriamo lo stesso problema

**Comment by AlfredoIsweb** [comment]
stiamo riscontrando anche noi il problema

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Le chiediamo cortesemente di fornirci tutti i riferimenti: idAppalto e CIG,  degli appalti relativi alla sua richiesta cosi da poter analizzare al meglio la problematica.</p>

<p>Al riguardo, si richiede gentilmente di aprire una nuova segnalazione tramite il canale GitHub riportando tutti i riferimenti richiesti.</p>

<p>Cordiali saluti</p>
