### ISSUE TITLE
codNuts - ERR63 Tipologica non valida

### ISSUE THREAD

**Issue by glastra-digitalpa** [anticorruzione/npa#1433]
In ambiente di collaudo abbiamo notato che, relativamente alla tipologica **codNuts**, alcuni valori sembrano non essere validi pur essendo presenti nel [JSON](https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/tipologiche/codNUTS.json) da voi fornito in questo repo. Per esempio utilizzando la chiave `AL03` in una scheda AD4 si ha il seguente errore:

```json
{
  "status": 400,
  "title": "KO",
  "detail": "AP_N_MOD",
  "type": "about:blank",
  "errori": [
    {
      "idTipologica": "errori",
      "dettaglio": "'codNUTS' : {'codNUTS' : 'AL03'}",
      "codice": "ERR63"
    }
  ]
}
```

| key | value | 
| --- | --- | 
| codiceAppalto | `tender://test13/id/881.4` | 
| govway-message-id | `16261e68-c3f9-4c62-80f7-855c9df67487` |
| govway-transaction-id | `03f1d8a0-1103-11ef-9b99-0050568e9679` |

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Vi ringraziamo per la segnalazione. </p>

<p>La tipologica è stata bonificata eliminando i campi dataInizio e dataFine impostati a null per errore.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
