### ISSUE TITLE
[Consip] - Scheda indizione: P1.10 - Schede S2, S1 - Invio di schede multiple post pubblicazione

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1434]
Abbiamo creato una negoziazione con tre lotti, ognuno associato ad un cig. 
Siamo riusciti a trasmettere tre volte la scheda S1, compilando l'anac form  con un cig diverso per per ogni scheda  trasmessa.
Siamo riusciti a trasmettere due volte la scheda S2, compilando l'anac form  con un cig diverso per per ogni scheda  trasmessa.

Vorremmo capire se è corretto poter trasmettere più volte le schede S1-S2 ?
Se si, in quali casi è possibile trasmetterle? 

"GovWay-Message-ID":["027e3a10-3b56-44a1-91d6-ff432ef1b142"
"GovWay-Transaction-ID":["05c9191a-10f2-11ef-9b99-0050568e9679"
 
log:
 
2024-05-13 09:15:50,077 INFO  (AbstractAnacUnhandledIntegrationService.java:219)
[[ACTIVE] ExecuteThread: '10' for queue: 'weblogic.kernel.Default (self-tuning)']: RequestBody = null
requestUrl = https://apigw-test.anticorruzione.it/modi/rest/ServiziComuni/v2/esito-operazione?idAppalto=bf94c144-e0af-4e7c-9506-d89eb3c30b82&tipoOperazione=SC_CONF&tipoRicerca=TUTTI_ESITI
headers = {Authorization=[Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L1NlcnZpemlDb211bmkvdjIiLCJzdWIiOiIwMWUyZWZjNC1mMmNkLTQwZjQtYmFjMS0wNWU3YzZkY2VmYmEiLCJuYmYiOjE3MTU1ODQ1NDksImRpZ2VzdCI6eyJhbGciOiJTSEEyNTYiLCJ2YWx1ZSI6ImVhNmRmZTRmM2NhODg1NDZlMjljYzdkM2QxNWZkOGNkNzNiOWIyYzhiYjBlZmJiNWJiOTM4YTU3ODM1ODhjOWEifSwicHVycG9zZUlkIjoiNDk5NTZmYWMtZjc2Ni00NTYwLWI5OTctMDkwYzg4NzUzOTUxIiwiaXNzIjoidWF0LmludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzE1NjcwOTQ5LCJpYXQiOjE3MTU1ODQ1NDksImNsaWVudF9pZCI6IjAxZTJlZmM0LWYyY2QtNDBmNC1iYWMxLTA1ZTdjNmRjZWZiYSIsImp0aSI6IjAyN2UzYTEwLTNiNTYtNDRhMS05MWQ2LWZmNDMyZWYxYjE0MiJ9.FiK5P_A8NSMTT7IXoid2QVAjfukt0pwKJanNrrgU4HzAGls-0nIjlvIXqiN6wxY80o34jkum5K66P9FIREK_dlGKEMS2wiiU4KzJkbcpGRsLc9xz7bhjQoPPtvplti9defdUr2aMfSS5Tjn9IZI0AatDQiGpIMRbSN_GCTxnl18uxgznZtpHGvihGLAoUZmGOArLTEL0uEYeE8OhVKdrOxmHIEjO52dY2qrMvfx2Mu7u63Bak8KFXoI9Dgi4RHt7hbT-PLJxD5fhWx_oRY_TAWqG25vrzDN9Y_Hh-iCRJnNiuh7cJGdiAbVIhpf5KL_x6YVhaSbPHM60_yWIw_Y-1g], Agid-JWT-TrackingEvidence=[eyJraWQiOiJvbjJVTmFCbGxQSlhaZDV4amdPMXoxV2QyeFVRYUItRHFtRFhaZEFiUlRBIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJqdGkiOiJkNzU5NDVjNC1jNTg3LTQ1MTEtOGRhOS1iM2I3NzA2OWVlZWQiLCJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L1NlcnZpemlDb211bmkvdjIiLCJ1c2VyQ29kaWNlRmlzY2FsZSI6Ik1SVENMRDk2QjUyQjY5NkYiLCJ1c2VyUm9sZSI6IlJQIiwidXNlckxvYSI6IjMiLCJ1c2VySWRwVHlwZSI6IlNQSUQiLCJTQUNvZGljZUZpc2NhbGUiOiIwNTM1OTY4MTAwMyIsIlNBY29kaWNlQVVTQSI6IjkwMDAwMDAwMDgiLCJyZWdDb2RpY2VQaWF0dGFmb3JtYSI6IjAwMDAwMDkiLCJyZWdDb2RpY2VDb21wb25lbnRlIjoiMDAwMDAxMCIsImJ1c2luZXNzRmxvd0lEIjoiYmY5NGMxNDQtZTBhZi00ZTdjLTk1MDYtZDg5ZWIzYzMwYjgyIiwidHJhY2VJRCI6ImU2MzRmM2NjLTczYmEtNGM0ZS04YTU1LWY2Zjk0MDdhNzAxNyIsInNwYW5JRCI6IjY4NjU5ZTA0LTNmOTktNDEyNi1hZDQzLTA0YTk2NGEzYjBhZiIsInB1cnBvc2VJZCI6IjQ5OTU2ZmFjLWY3NjYtNDU2MC1iOTk3LTA5MGM4ODc1Mzk1MSIsImlhdCI6MTcxNTU4NDU0OSwiZXhwIjoxNzE1NTg4MTQ5LCJuYmYiOjE3MTU1ODQ1NDl9.1BQ24FGg5AczQhrPKco9j-QawqiSvvJ4oRro-05AH8To7tOxU7dl8nOuw9TwJN3fWXa1O60Be_9cfMDOAC5WBY0Kzm8oenvb-xgr1LHWzS9JHyfnCnSYvDbc6uQx84gp0c6FsdF14rQqmv5e0cxigGvUHVgww8gkigZ0N_yHc_yuvy8RiHpNF3tF6y2eqEnL6aAB1lKunKk7SkVGlVYKB8sDXYKway46wbD5m-_JZ5JXbpxhVjqbfWUh1woFZH1MWndDydhaPpHhSMvpnP02Pd1yaLrwQFiCas0l_JOIlAk5zh6cKl-MlKYElqM6dQv0PPXzKyAwH9skS8s46jMGxQ], }
method = GET
Response = 
{"body":"
{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "bf94c144-e0af-4e7c-9506-d89eb3c30b82",
      "idScheda": "525af50d-4777-4bc0-8b38-078314ef1863",
      "codiceScheda": "S2",
      "esito": {
        "idTipologica": "esito",
        "codice": "OK"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "SC_CONF"
      },
      "dataControllo": "2024-05-13T09:15:48.154+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "SC_CONF"
      }
    },
    {
      "idAppalto": "bf94c144-e0af-4e7c-9506-d89eb3c30b82",
      "idScheda": "96695143-4fae-4a73-a374-ff77028f55ee",
      "codiceScheda": "S2",
      "esito": {
        "idTipologica": "esito",
        "codice": "OK"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "SC_CONF"
      },
      "dataControllo": "2024-05-13T09:14:33.257+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "SC_CONF"
      }
    },
    {
      "idAppalto": "bf94c144-e0af-4e7c-9506-d89eb3c30b82",
      "idScheda": "27bf2309-374f-4ec2-bbf9-fe80f62ee76b",
      "codiceScheda": "S1",
      "esito": {
        "idTipologica": "esito",
        "codice": "OK"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "SC_CONF"
      },
      "dataControllo": "2024-05-13T09:13:21.162+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "SC_CONF"
      }
    },
    {
      "idAppalto": "bf94c144-e0af-4e7c-9506-d89eb3c30b82",
      "idScheda": "c4b52f08-b638-4ff9-81c0-4753eda40aec",
      "codiceScheda": "S1",
      "esito": {
        "idTipologica": "esito",
        "codice": "OK"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "SC_CONF"
      },
      "dataControllo": "2024-05-13T09:12:35.313+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "SC_CONF"
      }
    },
    {
      "idAppalto": "bf94c144-e0af-4e7c-9506-d89eb3c30b82",
      "idScheda": "99fc3598-1c0f-4048-8466-521c574f8613",
      "codiceScheda": "S1",
      "esito": {
        "idTipologica": "esito",
        "codice": "OK"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "SC_CONF"
      },
      "dataControllo": "2024-05-13T09:11:55.944+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "SC_CONF"
      }
    }
  ]
}"
,"headers":{"Server":["nginx"],"Date":["Mon, 13 May 2024 07:15:50 GMT"],"Content-Type":["application/json"],"Transfer-Encoding":["chunked"],"Connection":["keep-alive"],"expires":["0"],"cache-control":["no-cache, no-store, max-age=0, must-revalidate"],"x-xss-protection":["1; mode=block"],"pragma":["no-cache"],"GovWay-Message-ID":["027e3a10-3b56-44a1-91d6-ff432ef1b142"],"x-frame-options":["DENY"],"GovWay-Transaction-ID":["05c9191a-10f2-11ef-9b99-0050568e9679"],"vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"],"x-content-type-options":["nosniff"],"strict-transport-security":["max-age=31536000 ; includeSubDomains","max-age=63072000"]},"statusCode":"200","statusCodeValue":200}
Timestamp=1715584549993
Taken=84 ms 
Thread=85

**Comment by obigno77** [comment]
E' corretto e funziona solo per gli affidamenti multilotto
