### ISSUE TITLE
[MAGGIOLI] URGENTE E BLOCCANTE: ERR111 http executing POST http://http://pcp-pre-pcp-verifica-ms.pcp-pre.svc:8080/verifica/qualificazione-sa?id=66437a06b5929714584fd544

### ISSUE THREAD

**Issue by laurapavan** [anticorruzione/npa#1438]
Buongiorno
da ieri **_in produzione_** stiamo ricevendo l'errore in oggetto, su diverse schede sembra senza un criterio (ma stiamo indagando).

In ambiente di collaudo non siamo ancora riusciti a replicare.

ERR111 NON è nemmeno nella tipologica degli errori. 

Aperto anche il ticket a supportopcp, ma visto che a quella mail non rispondete da mesi intanto segnalo anche qui perchè è un problema BLOCCANTE!

**Comment by laurapavan** [comment]
@obigno77

**Comment by matteolaltrelli** [comment]
Anche noi abbiamo lo stesso errore, può essere un problema di qualificazione della SA?
Ovviamente l'errore non è presente nella lista di quelli conosciuti e possiamo solo inventare una spiegazione.

**Comment by matteolaltrelli** [comment]
Ormai tutto può essere, nel dettaglio dell'errore vediamo che probabilmente fallisce una loro chiamata interna:
[http executing POST http://http://pcp-pre-pcp-verifica-ms.pcp-pre.svc:8080/verifica/qualificazione-sa?id=664378cc5c9e905e5151398f]

A tutto questo ora si aggiunge che molte operazioni di conferma vanno in esito WT e quindi di conseguenza perse.

**Comment by laurapavan** [comment]
infatti anche a me quella url lì sa da errore in configurazione di qualche re-indirizzamento interno...speriamo che qualcuno ci badi in fretta..

**Comment by matteolaltrelli** [comment]
possiamo sempre invitare i nostri clienti a chiamare il supporto ANAC per poi fargli dire che il problema è della piattaforma certificata :-D

**Comment by laurapavan** [comment]
alcuni miei clienti hanno già chiamato, infatti la risposta ANAC è stata: "lato nostro tutto ok". Quindi questo ERR111 in realtà non esiste, infatti nella tipologica  non c'è. Abbiamo risolto no?

**Comment by dellattiDPA** [comment]
Ci uniamo anche noi alla segnalazione e  confermiamo che la problematica delle schede che rimangono in WT e che dunque
risulta impossibile confermare.

**Comment by collaudo5** [comment]
Seguiamo con attenzione anche noi la tematica date le segnalazioni che ci stanno arrivando da parte delle SA

**Comment by gianlucacuomo** [comment]
Confermiamo il verificarsi del problema anche noi, Studio Amica

**Comment by obigno77** [comment]
Il problema segnalato è un problema interno legato all'impossibilità, per cause tecniche, di verificare se la stazione appaltante è qualificata per l'affidamento. Stiamo provvedendo ad aggiornare la specifica degli errori ma precisiamo che si è trattato di un problema temporaneo.
Tuttavia è in corso un ritardo generalizzato nel servizio di conferma-appalto per le richieste acquisite a partire dalle 8.25 circa di questa mattina. Lo stesso è attualmente in gestione per elaborare le richieste nel più breve tempo possibile.

**Comment by laurapavan** [comment]
Buongiorno, il codice errore è stato inserito nella specifica. 
**MA** il problema ci risulta persistere in produzione quindi abbiamo ancora svariate gare bloccate....
