### ISSUE TITLE
[BLK - PRODUZIONE] - esito WT

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#1439]
Da ieri pomeriggio in ambiente di produzione stiamo riscontrando molte operazioni con esito WT,
risultando impossibile confermare schede etc.
Mi confermate che è un problema diffuso?

**Comment by dellattiDPA** [comment]
Confermiamo anche noi la problematica. Le schede rimangono in lavorazione e non è possibile confemarle.

"Operazione non consentita, è in corso una richiesta di conferma appalto"

**Comment by laurapavan** [comment]
a me invece capita che vadano in errore sulla conferma. Ovvero: la fase di verifica rimane in WT per un po', poi passa (AP_VERIF), quindi parte la richiesta di conferma (che viene acquisita senza errori) ma poi va in errore 16 operazione non consentita per lo stato (quindi non conferma). Avete casi simili?

**Comment by obigno77** [comment]
E' in corso un ritardo generalizzato nel servizio di conferma-appalto per le richieste acquisite a partire dalle 8.25 circa di questa mattina. Lo stesso è attualmente in gestione per elaborare le richieste nel più breve tempo possibile.
@dellattiDPA non risultano analoghi problemi sul servizio di conferma-scheda. Tuttavia le schede possono essere rigettare qualora l'appalto non risulti confermato per il problema precedente.

**Comment by GGr8l** [comment]
@obigno77 è successo anche con gare aperte con eForm. Se le stazioni appaltanti non pubblicano oggi stesso, le procedure saranno da rifare per errore TED: NOTICE DISPATCH DATE > 24H.

Grazie

**Comment by matteolaltrelli** [comment]
@obigno77 ma le operazioni di conferma-appalto in WT verranno evase o dobbiamo consigliare alle stazioni appaltanti di generare un nuovo appalto quando la situazione si stabilizza?

**Comment by GGr8l** [comment]
@matteolaltrelli NO NESSUNA GENERAZIONE DI NUOVO APPALTO PER FAVORE! Ci sono troppe richieste entrate questa mattina

**Comment by obigno77** [comment]
Le AP-CONF arrivate a partire dalle 14.00 circa hanno ripreso a essere lavorate correttamente.
Per quelle della mattina è in corso il recupero e si completerà nell'arco delle prossime ore.
