### ISSUE TITLE
test comnica appalto - APIunavailable - Errore 503.

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#144]
Seguendo i passi indicate dalle specifiche di integrazione al PDND è stato esegutio quanto segue rispetto ad una finalità

-	Associazione di un client
-	Generazione chiavi pubbliche/private ed associazione al client.
-	Per la chiave generata è stata richiesta attraverso uno script la generazione di una client assertion (primo token da staccare).
-	Una volta generata la suddetta client assertion è stato richiesto il voucher (access token). 
![image](https://github.com/anticorruzione/npa/assets/107458324/5b29ccbe-550a-45af-82d8-40d3ea0c7d77)

Il suddetto voucher è il token da impostare nell’header come Bearer quando si richiamano i servizi esposti da ANAC.  
richiamando il servizio del crea appalto si è ottenuto il seguente errore:
![image](https://github.com/anticorruzione/npa/assets/107458324/d48f1067-2687-45d9-9dbc-a9305bdb62e9)
APIUnavailable Errore 503.

**Comment by supportoAnac** [comment]
Abbiamo avuto una temporanea indisponibilità in fase di rilascio di una nuova release. Abbiamo adottato gli accorgimenti necessari ad evitare il problema in futuro.
