### ISSUE TITLE
[SISGAP] STATUS UPDATE 28/05/2024 | Errore bloccante in ambiente di attestazione 

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1440]
Buongiorno,
come indicato in questa issue https://github.com/anticorruzione/npa/issues/1438 , è da ieri (15/05/2024) che non riusciamo a confermare gli appalti in ambiente di attestazione.

Ci ritorna sempre un errore ERR111
govway-message-id: 2129b0bb-9c6d-494c-9f71-4729d3b04e31
govway-transaction-id: ff633680-1353-11ef-b339-0050568e7535

{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"6c052ec2-54cd-47f1-a80a-8766ae4b238d","idScheda":"b4ebc2e6-bcb2-4371-b015-7103b9c47618","codiceScheda":"P1_16","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AP_CONF"},"dataControllo":"2024-05-16T10:44:01.664+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AP_N_CONF"},"errori":[{"idTipologica":"errori","dettaglio":"[500] during [POST] to [http://pcp-pre-pcp-verifica-ms.pcp-pre.svc:8080/verifica/qualificazione-sa?id=6645c747a2094505b89d709d] [QualificazioneSAClient#verificaSAQualificata(String)]: [{\"timestamp\":1715849041660,\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/verifica/qualificazione-sa\"}]","codice":"ERR111"}]}]}
{"server":"nginx","date":"Thu, 16 May 2024 08:44:55 GMT","content-type":"application/json","transfer-encoding":"chunked","connection":"close","expires":"0","cache-control":"no-cache, no-store, max-age=0, must-revalidate","set-cookie":["29c447faecc35da9894a493a643d33f7=9aa105b7c7cb57a7486fd11c1f4f99d8; path=/; HttpOnly; Secure; SameSite=None"],"x-xss-protection":"1; mode=block","pragma":"no-cache","govway-message-id":"2129b0bb-9c6d-494c-9f71-4729d3b04e31","x-frame-options":"DENY","govway-transaction-id":"ff633680-1353-11ef-b339-0050568e7535","vary":"Access-Control-Request-Headers, Access-Control-Request-Method, Origin","x-content-type-options":"nosniff","strict-transport-security":"max-age=31536000 ; includeSubDomains, max-age=63072000"}

Attendiamo un riscontro per capire se il problema è rientrato in tutti gli ambienti

**Comment by obigno77** [comment]
In ambiente di qualificazione questo errore si è verificato una sola volta sull'appalto indicato.
Allo stato il problema è risolto in tutti gli ambienti

**Comment by masko82** [comment]
Abbiamo appena creato un appalto in ambiente di attestazione e alla conferma abbiamo ricevuto il medesimo errore.

govway-message-id: 58f14a06-0d87-46b5-95ea-8907dd7d0423
govway-transaction-id: f740de9f-138b-11ef-b339-0050568e7535

{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"431a38ea-ce87-4b0e-be64-5afde42948f7","idScheda":"eda2836f-c611-4d85-8938-9e36eb59cf29","codiceScheda":"P1_16","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AP_CONF"},"dataControllo":"2024-05-16T17:35:02.729+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AP_N_CONF"},"errori":[{"idTipologica":"errori","dettaglio":"[500] during [POST] to [http://pcp-pre-pcp-verifica-ms.pcp-pre.svc:8080/verifica/qualificazione-sa?id=6646279ca2094505b89d709e] [QualificazioneSAClient#verificaSAQualificata(String)]: [{\"timestamp\":1715873702706,\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/verifica/qualificazione-sa\"}]","codice":"ERR111"}]}]}

{"server":"nginx","date":"Thu, 16 May 2024 15:37:10 GMT","content-type":"application/json","transfer-encoding":"chunked","connection":"close","expires":"0","cache-control":"no-cache, no-store, max-age=0, must-revalidate","set-cookie":["29c447faecc35da9894a493a643d33f7=9aa105b7c7cb57a7486fd11c1f4f99d8; path=/; HttpOnly; Secure; SameSite=None"],"x-xss-protection":"1; mode=block","pragma":"no-cache","govway-message-id":"58f14a06-0d87-46b5-95ea-8907dd7d0423","x-frame-options":"DENY","govway-transaction-id":"f740de9f-138b-11ef-b339-0050568e7535","vary":"Access-Control-Request-Headers, Access-Control-Request-Method, Origin","x-content-type-options":"nosniff","strict-transport-security":"max-age=31536000 ; includeSubDomains, max-age=63072000"}

**Comment by obigno77** [comment]
Verifichiamo subito

**Comment by POLIDORO1968** [comment]
Buongiorno, è dal (15/05/2024) che non riusciamo a confermare gli appalti in ambiente di attestazione.

Ci ritorna sempre un errore ERR111

ERR111: [500] during [POST] to [http://pcp-prod-pcp-verifica-ms.pcp-prod.svc:8080/verifica/qualificazione-sa?id=6644887dedeef52693fb32c8] [QualificazioneSAClient#verificaSAQualificata(String)]: [{"timestamp":1715783565809,"status":500,"error":"Internal Server Error","path":"/verifica/qualificazione-sa"}]

Data evento: 17/05/2024 09:36:48
Govway Transaction Id: 13e7ecb9-1420-11ef-852e-005056844885

Attendiamo un riscontro per capire se il problema è rientrato in tutti gli ambienti

**Comment by masko82** [comment]
Ci sono novità in merito?

**Comment by masko82** [comment]
Ad oggi non è ancora possibile utilizzare l'ambiente di attestazione perchè, a seguito della creazione di un appalto, l'esito dell'operazione di conferma appalto restituisce ancora il medesimo errore ERR111 con status 500

idAppalto (APPENA CREATO) : bec28cc2-2a8b-4ea6-9a28-3363311c7781
govway-message-id:c2be3db0-b9cd-4e9a-a3bd-76e0c4595018
govway-transaction-id":"1549b2fd-18c5-11ef-b339-0050568e7535


{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"bec28cc2-2a8b-4ea6-9a28-3363311c7781","idScheda":"3936fef0-f744-4fe1-8813-829eb41bbb3c","codiceScheda":"P1_16","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AP_CONF"},"dataControllo":"2024-05-23T09:21:07.700+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AP_N_CONF"},"errori":[{"idTipologica":"errori","dettaglio":"{\"timestamp\":1716448867635,\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/verifica/qualificazione-sa\"}","codice":"ERR111"}]}]}

**Comment by masko82** [comment]
Ad oggi (28/05/2024) non è ancora possibile utilizzare l'ambiente di attestazione perchè, a seguito della creazione di un appalto, l'esito dell'operazione di conferma appalto restituisce ancora il medesimo errore ERR111 con status 500

idAppalto (APPENA CREATO) : 1d0cf58d-45e2-4181-a85c-31bae2c67212
govway-message-id: ba4ec2ac-6edf-48ce-9df1-ac583b97d84c
govway-transaction-id: cd1933b7-1cd4-11ef-b339-0050568e7535

{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"1d0cf58d-45e2-4181-a85c-31bae2c67212","idScheda":"82c690a6-3f7d-4be4-9e43-eb9a814ffd33","codiceScheda":"P1_16","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AP_CONF"},"dataControllo":"2024-05-28T12:30:44.493+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AP_N_CONF"},"errori":[{"idTipologica":"errori","dettaglio":"{\"timestamp\":1716892244479,\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/verifica/qualificazione-sa\"}","codice":"ERR111"}]}]}

**Comment by masko82** [comment]
Ad oggi (31/05/2024) non è ancora possibile utilizzare l'ambiente di attestazione perchè, a seguito della creazione di un appalto, l'esito dell'operazione di conferma appalto restituisce ancora il medesimo errore ERR111 con status 500

idAppalto (APPENA CREATO) : 143e72e1-2962-491f-bb9e-0dc6a25e6f0d
govway-message-id: 80292c90-4592-49de-9b16-8ba51be6d675
govway-transaction-id: 7d268dbb-1f2e-11ef-b339-0050568e7535

{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"143e72e1-2962-491f-bb9e-0dc6a25e6f0d","idScheda":"ddeebafe-2f42-4d0f-9b0c-bc05850339df","codiceScheda":"P1_16","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AP_CONF"},"dataControllo":"2024-05-31T12:30:44.127+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AP_N_CONF"},"errori":[{"idTipologica":"errori","dettaglio":"{\"timestamp\":1717151444103,\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/verifica/qualificazione-sa\"}","codice":"ERR111"}]}]}

**Comment by obigno77** [comment]
Buongiorno, a quanto pare siete gli unici a segnalare il problema. Probabilmente è l'errore notificato ad essere incoerente. Abbiamo fatto un analisi su entrambe le segnalazioni di oggi e di 3 giorni fa e per gli idAppalto indicati è tracciato esclusivamente il tentativo di conferma mentre non abbiamo traccia della creazione dell'appalto. Potete darci i riferimenti della transazione di creazione dell'appalto e confermarci che l'ambiente in uso è quello di collaudo/qualificazione e non quello nuovo di attestazione?

**Comment by obigno77** [comment]
Abbiamo individuato la chiamata di creazione dell'appalto in ambiente di attestazione e la chiamata di conferma sia in ambiente di attestazione che in ambiente di qualificazione. Probabilmente l'esito errato è legato a questa seconda chiamata per un idAppalto che in quell'ambiente non esiste, Vi chiediamo di verificare le configurazioni e riprovare. Grazie
