### ISSUE TITLE
Errore di sintassi in motivoEsclusioneOrdinarioSpeciale.json

### ISSUE THREAD

**Issue by lucaCorigliano-SA** [anticorruzione/npa#1441]
Commit: https://github.com/anticorruzione/npa/commit/9b60aadb9d28f2732b79e5eec98facfdf6f8bc6c?diff=split&w=0

File: https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/tipologiche/motivoEsclusioneOrdinarioSpeciale.json

Linea: 215

Errato:

```json
    "dataFine":"null
```

Correzione:

```json
    "dataFine":null
```

**Comment by supportoAnac** [comment]
Gentile Utente,

La casistica segnalata è stata risolta.

Grazie della segnalazione.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>L'errore è stato corretto nei rilasci precedenti.</p>

<p>Cordiali saluti.</p>
