### ISSUE TITLE
[Consip] conferma-appalto in WT

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1444]
Salve,
da stamattina riscontriamo problemi sulla conferma degli appalti. 
abbiamo provato con diverse schede e dopo aver chiamato il conferma-appalto otteniamo che l'operazione resta in WT. Potete verificare?

govway message= [51b47f46-e252-42bf-9222-f186c58f9907]
govway transaction= [3d4f1ac0-1453-11ef-9ec6-0050568e08b3]

{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "14c55012-0ffe-4a6b-99e1-ae1e812f2780",
      "idScheda": "ada72743-1296-4293-9f16-f3c23db7e2e7",
      "codiceScheda": "AD3",
      "esito": {
        "idTipologica": "esito",
        "codice": "WT"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AP_CONF"
      },
      "dataControllo": "2024-05-17T16:11:28.589+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AP_IN_CONF"
      }
    }
  ]
}

**Comment by sfala** [comment]
Buona sera,
anche noi riscontriamo lo stesso problema che speravamo fosse temporaneo. Alcune schede di appalto bloccate:

P1_19 - cf99bd12-9cf2-4deb-a01b-efd4961b7a7b
P2_10 - 05731450-6625-4ba1-9557-dd25b3b481ec
P2_10 - fd1f1f80-1156-4be4-a7cd-f70da82c7e40
P7_1_3 - 7e647c3a-9d85-4d59-970f-9983ebdb33ab

**Comment by obigno77** [comment]
Il problema è stato temporaneo. La conferma è un'operazione asincrona.
