### ISSUE TITLE
[Bolzano/Toscana] - esito operazione: l'appalto resta in conferma

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1445]
Salve,

stiamo riscontriamo un problema sugli appalti alla loro conferma in ambiente di collaudo.
All'esito operazione del conferma appalto, ci viene restituito "Appalto in conferma" il quale resta in questo stato senza aggiornarsi.

di seguito un esempio :
{"idAppalto":"50d55665-5291-496f-9bef-3883fd1d704f"}
[data (4) (1).json](https://github.com/anticorruzione/npa/files/15351505/data.4.1.json)
[data (3) (1).json](https://github.com/anticorruzione/npa/files/15351507/data.3.1.json)
[data.json](https://github.com/anticorruzione/npa/files/15351508/data.json)
[data (1).json](https://github.com/anticorruzione/npa/files/15351509/data.1.json)
[data (2).json](https://github.com/anticorruzione/npa/files/15351510/data.2.json)

Potreste darci supporto?
Grazie.

**Comment by obigno77** [comment]
Il problema è stato risolto.
Le poche transazioni rimaste appese in questo stato stato state mandate in KO.
