### ISSUE TITLE
[MAGGIOLI] URGENTE E BLOCCANTE: persistenza ERR111 su schede generate oggi 20/05/2024

### ISSUE THREAD

**Issue by laurapavan** [anticorruzione/npa#1446]
Buongiorno ,
segnalo che il problema della issue #1438 IN PRODUZIONE è cambiato **ma non risolto**.

Adesso nella tipologica errori è inserito questo:
{
    "codice":"ERR111",
    "descrizione": {
		"it": "errore durante la comunicazione con il servizio di qualificazione delle stazioni appaltanti.",
		"en": "errore durante la comunicazione con il servizio di qualificazione delle stazioni appaltanti."
	}

Mentre la response da questo messaggio:

{
    "anacErrors": [
        {
            "codice": "ERR111",
            "dettaglio": "CodiceFiscaleSA non valorizzato",
            "idTipologica": "errori"
        }

Ovviamente il CF della SA è valorizzato e viene correttamente inviato nel JSON della scheda (vedi allegato).

ID APPALTO di esempio (IN PRODUZIONE): 0aaaf803-3617-47f2-b3bc-a993e81d9923

   "govwayTransactionId": "3933c36e-1690-11ef-a2a9-00505684399c",
    "timestamp": "20/05/2024 12:04:32"

Questa è solo 1 delle centinaia di segnalazioni che stiamo ricevendo, non mi pare risolto.

**Comment by laurapavan** [comment]
[ERR111-Response.json](https://github.com/anticorruzione/npa/files/15375825/ERR111-Response.json)
[Uploading ERR111- Copia.txt…]()

**Comment by obigno77** [comment]
Problema risolto. Le conferme in ERR111 possono ora essere risottomesse
