### ISSUE TITLE
[Consip] [chiarimenti] cancella-appalto dopo 90 GG

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1448]
salve, 
dopo aver confermato un appalto (conferma-appalto) se non si procede alla pubblicazione (pubblica-avviso) entro 90 gg l'appalto viene cancellato automaticamente da ANAC oppure ci sono tempistiche differenti? se si, quali?

**Comment by obigno77** [comment]
La specifica prevede la cancellazione dopo 90 giorni
