### ISSUE TITLE
[Consip] [BLK] A2.29 - ERR94

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1449]
Salve,
dopo aver chiamato il servizio conferma-scheda sulla A2.29 otteniamo il seguente errore:
ERR94 - errore generico durante la comunicazione con PVL

"GovWay-Message-ID":["657eff76-9bb8-46d8-b466-fb27ca6ad43e"]
"GovWay-Transaction-ID":["6a1b0618-176b-11ef-9b99-0050568e9679"]

facciamo notare che i servizi esito-operazione e ricerca-scheda restituiscono informazioni non congruenti:- se l'operazione di conferma è andata in errore non è chiaro come mai la scheda sia in stato CONF.
ESITO-OPERAZIONE
{
      "idAppalto": "ef583c9f-29ed-482f-974f-d4de566e36a5",
      "idScheda": "2635e96c-e48d-4bb5-84a6-45cd061f415f",
      "codiceScheda": "A2_29",
      "esito": {
        "idTipologica": "esito",
        "codice": "KO"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "SC_CONF"
      },
      "dataControllo": "2024-05-21T14:51:32.193+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "SC_N_CONF"
      },
      "errori": [
        {
          "idTipologica": "errori",
          "dettaglio": "JSONObject[\"tipologica\"] is not a JSONObject (class org.json.JSONObject$Null : null).",
          "codice": "ERR94"
        }

RICERCA-SCHEDA (stato -> CONF)
{
  "status": 200,
  "title": "OK",
  "detail": "Operazione eseguita con successo",
  "type": "about:blank",
  "scheda": {
    "_idScheda": "2635e96c-e48d-4bb5-84a6-45cd061f415f",
    "stato": {
      "idTipologica": "statoScheda",
      "codice": "CONF"
    },
    "codice": {
      "idTipologica": "codiceScheda",
      "codice": "A2_29"
    },
    "versione": "1.0",
    "dataCreazione": "2024-05-21T14:51:31.632+00:00",
    "dataModifica": "2024-05-21T14:51:32.116+00:00",
    "body": {
      "type": "SchedaA229Type",
      "anacForm": {
        "appalto": {
          "motivoUrgenza": {
            "idTipologica": "motivoUrgenza",
            "codice": "1"
          },
          "relazioneUnicaSulleProcedure": false,
          "opereUrbanizzazioneScomputo": false,
          "datiBaseProcedura": {}
        },
        "aggiudicazioni": [
          {
            "cig": "I00509BBF4",
            "offertePresentate": [
              {
                "idPartecipante": "faf04912-f99d-49a9-b326-d9c4cdb241fc",
                "importo": 3.0,
                "aggiudicatario": false,
                "ccnl": "CCNL",
                "offertaMaggioreSogliaAnomalia": false,
                "impresaEsclusaAutomaticamente": false,
                "offertaAnomala": false
              }
            ],
            "numeroOfferteAmmesse": 1
          }
        ]
      }
    }
  }
}

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>La fix è stata individuata è nella settimana corrente verrà rilasciato l'aggiornamento che risolve la problematica riscontrata.</p>

<p>Restiamo a disposizione per eventuali chiarimenti</p>

<p>Cordiali saluti</p>

<p> </p>
