### ISSUE TITLE
Regole dmn

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#145]
Provando ad importare diverse schede.dmn della directory https://github.com/anticorruzione/npa/tree/main/docs/modello-dati/regole nel reader online definito nel readme https://demo.bpmn.io/ si riceve l'errore 
```
nparsable content <definitions> detected
	line: 1
	column: 0
	nested error: unexpected element <definitions>
```

**Comment by supportoAnac** [comment]
Sono stati aperti tutti i file di regole DMN rilasciati e non risulta l'errore segnalato. È possibile riprovare ed essere più specifici su quale file dà l'errore, in modo da fare ulteriori verifiche?

**Comment by nicadeddu** [comment]
Salve, da quello che noto, l'issue è stato aperto il 25 luglio e le ultime modifiche apportate risultano all'8 di agosto. Probabilmente è stato risolto a cui si riferiva @mladuDPA
