### ISSUE TITLE
errore di sintassi in fattispecieTracciabilita.json

### ISSUE THREAD

**Issue by lucaCorigliano-SA** [anticorruzione/npa#1450]
Ed eccoci ancora qua...

Commit: https://github.com/anticorruzione/npa/commit/fb4dacff522a0e6e41f11e9169abf2b7b1980e6c

File: docs/modello-dati/tipologiche/fattispecieTracciabilita.json

Linea: 100

Errore:
```
}	
{
```

Fix:
```
},
{
```

Posso chiedere gentilmente ai responsabili di rileggere il codice prima di mandarlo in master?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Grazie per la segnalazione.</p>

<p>La tipologica è stata aggiornata sul github di sviluppo (anticorruzione-test) in modo da essere inclusa nel prossimo rilascio.</p>

<p>Cordiali saluti</p>
