### ISSUE TITLE
[TOSCANA/BOLZANO] - Richiesta chiarimenti scheda ANN

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1451]
Salve,
avremmo dei punti da smarcare per interpretare correttamente la nuova scheda:

1. **Scheda ANN** - Scheda di annullamento procedura --> può essere trasmessa per le sole schede di pubblicazione (che consentono l'acquisizione del CIG)? 
2. Ci confermate che la scheda sopra citata **NON impatta** le schede di esecuzione?
3. **La scheda ANN** vale sia per le **sottosoglia che soprasoglia?**

**Comment by anac-uscp** [comment]
<p>Buongiorno,<br>
<br>
In relazione ai quesiti posti, rispondiamo seguendo la numerazione.<br>
<br>
1) La scheda in questione deve essere utilizzate per le schede non soggette a pubblicità a valore legale<br>
<br>
2) La scheda in questione comporta l'annullamento dell'intera procedura, quando questa non è ancora stata avviata.<br>
<br>
3) Si ribadisce quanto affermanto nella risposta al punto 1.<br>
<br>
<br>
Saluti.</p>
