### ISSUE TITLE
[TOSCANA/BOLZANO] - Richiesta chiarimenti schede CM1,CM2 

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1452]
Salve,
avremmo dei punti da smarcare per interpretare correttamente le nuove schede:

1. Le schede CM1 e CM2 - Scheda di comunicazione modifica dati della procedura per appalti sopra e sotto i 5K, **Fino a quale momento** del ciclo di vita dell'appalto possono essere inviate tali schede?
3. Le schede sopra citate sono **propedeutiche alla rettifica**?

**Comment by obigno77** [comment]
Le schede consentono di operare rettifiche nei casi in cui non è previsto l'avviso di rettifica.
Possono essere utilizzate solo una volta entro la trasmissione della scheda successiva.
