### ISSUE TITLE
[Consip] minLenght su codiceAppalto - retrocompatibilità

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1453]
Salve, 
come ci si deve comportare sugli appalti già trasmessi ad ANAC che presentano meno di 8 caratteri? è retrocompatibile la modifica (ad esempio nel caso si vogliano richiamare i servizi modifica-appalto/modifica-avviso/rettifica-avviso)?
a partire da quando (data e ora) sarà valido il nuovo vincolo?
il controllo sulla leght del codiceAppalto avverrà solo a valle della chiamata crea-appalto? 

Grazie

**Comment by pg-volpentesta** [comment]
è possibile avere un feedback sul tema?

Grazie

**Comment by obigno77** [comment]
Buongiorno, avendo verificato che il controllo non sarebbe retrocompatibile con i servizi di modifica e rettifica abbiamo deciso di rinviarne l'enforcement a settembre, allorchè non dovrebbero esserci più avvisi con possibilità di modifica o rettifica se lato vostro intervenite comunque subito sulla piattaforma
