### ISSUE TITLE
[Consip] installazione Changelog

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#1454]
In merito a "Note di rilascio del 21/05/2024 (in Esercizio il 30/05/2024)" quando saranno rilasciate le modifiche nei vostri ambienti di qualificazione?

Al momento non ci sembra ci siano cambiamenti (ES: riusciamo a confermare delle AD4 senza compilare datiBaseCPV e con codiceAppalto a 7 caratteri)

Grazie

**Comment by obigno77** [comment]
L'aggiornamento è stato rilasciato in qualificazione ieri 28/05. Il changelog è stato aggiornato per ripianificare la data di rilascio in esercizio
