### ISSUE TITLE
Problemi con pubblicazioni scheda P1_19

### ISSUE THREAD

**Issue by AlfredoIsweb** [anticorruzione/npa#1456]
Salve,
stiamo riscontrando dei problemi con la pubblicazione di diversi appalti P1_19 creati e confermati che rimangono nello stato IN_LAV.

GovWay-Message-ID: 28fe9927-4e5d-49dc-89b4-778a5a2629e8
GovWay-Transaction-ID: 9868e9cf-1392-11ef-9b99-0050568e9679

Potreste darci qualche indicazione?

**Comment by obigno77** [comment]
Risolto

**Comment by AlfredoIsweb** [comment]
Salve,
gli appalti P1_19 che abbiamo creato e confermato risultano ancora nello stato P1_19.
Con risolto intendete che bisogna creare nuovi appalti?
