### ISSUE TITLE
AD4 - stato WT

### ISSUE THREAD

**Issue by tommaso-gobbato** [anticorruzione/npa#1457]
Salve sto provando a chiudere un paio di schede AD4 in ambiente di collaudo con id appalto:

- aa5d0b77-fed2-41e5-bb2c-83f83b17ef96
- 8b42e158-3269-4b02-9f01-e4f197cadfd1

Le operazioni di creazione / modifica funzionano correttamente, così come l'operazione di conferma; solo che, tentando di recuperare l'esito dell'operazione per recupere poi il CIG, l'esito rimane sempre in "WT" = "IN ATTESA" (se non, ogni tanto va in errore)

Potreste per cortesia darmi indicazioni al riguardo?
Saluti

**Comment by obigno77** [comment]
Problema temporaneo. Risolto
