### ISSUE TITLE
Rettifica Avviso

### ISSUE THREAD

**Issue by evalentip** [anticorruzione/npa#146]
Fino a quando è possibile chiamare il rettifica-avviso con conseguente ritrasmissione della scheda di indizione? In particolare, si può chiamare il servizio rettifica-avviso anche dopo aver trasmesso una scheda di comunicaPostPubblicazione (es. S1) ?

**Comment by supportoAnac** [comment]
Fino alla scadenza del termine per la presentazione delle offerte. Entro questa data non possono essere inviate schede post pubblicazione perchè non possono essere disponibili.
