### ISSUE TITLE
[Consip] - ambiente di attestazione - 401

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1462]
salve, 
abbiamo provato ad effettuare delle chiamate in ambiente di attestazione ma otteniamo sempre l'errore 401. potete verificare?
il RP è abilitato nell'ambiente di qualificazione. 
**crea-appalto**
govway message=0c318647-2326-40ed-8100-9cc5d01d937f
govway transaction=20ecdf8a-1905-11ef-b339-0050568e7535

grazie

**Comment by obigno77** [comment]
Risolto
