### ISSUE TITLE
[BLK] AD1_28 impossibile confermare per ERR41

### ISSUE THREAD

**Issue by ctav8** [anticorruzione/npa#1464]
Buongiorno,
mi ricollego alla issue #1459, in quanto anche noi non riusciamo a confermare le AD1_28 per ERR41.

Abbiamo creato un secondo appalto stamattina, ma senza risultati.

idAppalto 1: e5cc550e-5d26-406e-9c83-a55abb7bf936

ESITO OPERAZIONE CONFERMA CON ERR41
GovWay-Transaction-ID: 24bb924c-19a7-11ef-8d77-0050568e9679
GovWay-Message-ID: 87c4007f-ab4e-41aa-885a-c3f78a446462

_______________________________________________________________
idAppalto 2: 2ebcef02-141c-4b2a-887d-280ec8c345c9

ESITO OPERAZIONE CONFERMA CON ERR41
GovWay-Transaction-ID: f7d66ebb-19a8-11ef-8d77-0050568e9679
GovWay-Message-ID: ed76e1e2-4c25-44d0-93eb-531e147bff41

Non riusciamo a capire dove sia il problema.
Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>E' stata individuata la problematica e risolto attraverso il rilascio di una fix.</p>

<p>Si può procedere con la modifica dell'appalto assicurandosi di aggiornare i dati presenti nell'Eform e quindi proseguire con le azioni desiderate.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
