### ISSUE TITLE
Nuove schede CM1-CM2-ANN: C'è un motivo per cui nella nuova versione dell'orchestratore non è stata modificata la colonna "scheda successiva" per la scheda AD3?

### ISSUE THREAD

**Issue by bondvaleria** [anticorruzione/npa#1466]
Ho notato che nella nuova versione dell'Orchestratore non è stata aggiornata la colonna scheda successiva per includere le nuove schede CM1, ANN per gli affidamenti diretti sopra i 5k euro (scheda di indizione AD3). C'è un motivo? Sarebbe utile...

P.S.: Per l'AD4 (adesione ad accordo quadro) non è prevista la scheda CM2 (modifiche per appalti sotto 5k euro) come scheda successiva. C'è un motivo anche per questo? È l'importo dell'appalto originario che è considerato per fare la differenza fra CM1 e CM2, o del contratto attuativo? Perché il contratto attuativo potrebbe essere sotto 5k euro.

**Comment by anac-uscp** [comment]
<p><span style="font-size:11pt;"><span style="font-family:Calibri,sans-serif;"><span style="color:#1f497d;">Di seguito la lista delle schede (affidamenti non soggetti a pubblicità a valore legale ) alle quali può seguire una CM1 (per la modifica dei dati) o una ANN (per l'annullamento della procedura).<br>
La scheda CM2 'Scheda di comunicazione modifica dati della procedura per appalti sotto i 5K euro' può seguire solo ad una scheda AD5 Affidamento diretto &lt; 5k €)</span></span></span></p>

<p><span style="font-size:11pt;"><span style="font-family:Calibri,sans-serif;"><strong><span style="color:#1f497d;">P5 </span></strong><span style="color:#1f497d;">(appalti soggetti a sola tracciabilità)</span></span></span></p>

<p><span style="font-size:11pt;"><span style="font-family:Calibri,sans-serif;"><strong><span style="color:#1f497d;">AD4</span></strong><span style="color:#1f497d;"> (Adesione ad accordo quadro/convenzione senza successivo confronto competitivo),</span></span></span></p>

<p><span style="font-size:11pt;"><span style="font-family:Calibri,sans-serif;"><strong><span style="color:#1f497d;">P3_1, P3_2, P3_3</span></strong><span style="color:#1f497d;"> (Contratti Esclusi)</span></span></span></p>

<p><span style="font-size:11pt;"><span style="font-family:Calibri,sans-serif;"><strong><span style="color:#1f497d;">P6_1, P6_2</span></strong><span style="color:#1f497d;"> (adesione AQ/convenzione con successivo confronto competitivo)</span></span></span></p>

<p>Gli uffici competenti stanno valutando la possibilità di integrazione della lista con ulteriori schede</p>

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;margin-left:7px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">Per le procedure, a prescindere dall’importo, che non prevedono la pubblicazione al TED che hanno pubblicità a valore legale, non è possibile modificarne i dati poiché la pubblicazione nazionale (PVL) è contestuale all’invio della scheda. Idem per le procedure che non sono ad evidenza pubblica ma che prevedono pubblicità a valore legale come la scheda AD3.</span></span></span></span></p>

<p style="margin-bottom:11px;margin-left:7px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">Per l'AD4 viene considerato l'importo dell'appalto originario per cui è corretto utilizzare una CM1 in caso di modifica dei dati.</span></span></span></span></p>
