### ISSUE TITLE
URL della documentazione relativa alle varianti

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#1467]
Buongiorno, la delibera ANAC 582/2023 prevede che debba essere comunicata la URL del luogo dove è conservata la documentazione relativa alle varianti (urlDocumentazione nella schede M*).

Tale URL però non dovrebbe essere pubblica, non rientrando nella trasparenza.
Chiediamo pertanto cortesemente un chiarimento su come generare questa URL, e soprattutto su come comunicare ad ANAC le modalità per accedervi.

**Comment by anac-uscp** [comment]
<p><span style="font-size:12.0pt;"><span style="font-family:Aptos;">Nella delibera n. 582/2023 viene esplicitato </span></span><span style="font-size:11pt;"><span style="font-family:Aptos;"><span style="font-size:12.0pt;">che la documentazione relativa alle varianti non va più trasmessa all’Anac in allegato ad un modulo (come era in precedenza) ma che è sufficiente che la SA fornisca all’Anac un link per accedere al luogo in cui la documentazione è consultabile.</span></span></span></p>

<p>Tale link va indicato nelle schede M1.* e M2.* (modifica contrattuale) nel campo 'URLDocumentazione' (facoltativo).  </p>
