### ISSUE TITLE
SCHEDA P7.1.1 ERR4 e P2* nessun cig ottenuto

### ISSUE THREAD

**Issue by iacopus** [anticorruzione/npa#1472]
Si riscontra la seguente problematica:
un utente intendendo inviare la scheda P7.1.1 senza previamente popolare il campo MOTIVAZIONE CIG riscontra alla trasmissione verso PCP (prima del VERIFICA) la restituzione di un ERR#4.

Grazie

**Comment by obigno77** [comment]
Si chiede conferma che il problema sia in ambiente di qualificazione e di indicare l'idAppalto o altro riferimento utile

**Comment by iacopus** [comment]
si conferma ambiente qualificazione
codice appalto: CONSIP_GARE_87678

grazie
![err4](https://github.com/anticorruzione/npa/assets/165040874/b8f6e00c-86ae-42bf-b55f-8cbbc796c565)

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>il campo da lei citato è effettivamente obbligatorio per la scheda P7_1_1,l errore quindi da lei riscontrato è lecito.</p>

<p>Saluti</p>
