### ISSUE TITLE
Errore 400 - InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by VincenzoISWEB** [anticorruzione/npa#1474]
Buonasera,

da questo pomeriggio otteniamo il seguente errore:
```
{
            "type": "https:\/\/govway.org\/handling-errors\/400\/InteroperabilityInvalidRequest.html",
            "title": "InteroperabilityInvalidRequest",
            "status": 400,
            "detail": "Received request is not conform to the required interoperability profile",
            "govway_id": "6bbf098a-1c39-11ef-bd08-0050568e9679"
}
```

Di seguito i codici GovWay:
```
            "GovWay-Transaction-ErrorType: InteroperabilityInvalidRequest\r",
            "GovWay-Transaction-ID: 6bbf098a-1c39-11ef-bd08-0050568e9679\r",
```

L'errore è stato riscontrato improvvisamente senza alcuna modifica sul codice.

Chiediamo inoltre di ottenere, in Collaudo, degli errori descrittivi e più verbosi al fine di essere autonomi nella risoluzione di eventuali problematiche.

**Comment by lucaCorigliano-SA** [comment]
Confermo anche qui la stessa problematica.

> Chiediamo inoltre di ottenere, in Collaudo, degli errori descrittivi e più verbosi al fine di essere autonomi nella risoluzione di eventuali problematiche.
_Magari..._

**Comment by obigno77** [comment]
Il problema è dovuto al mancato rispetto del formato dell'attributo userLoa del token jws. Il formato dell'attributo deve essere di tipo stringa. In questo caso il controllo è stato applicato automaticamente in corrispondenza di un innalzamento di versione dell'api gateway di ANAC. Si invita in ogni caso a verificare la corretta valorizzazione degli attributi del token poichè l'enforcement delle regole sarà oggetto di progressivi raffinamenti.

**Comment by lucaCorigliano-SA** [comment]
> Il problema è dovuto al mancato rispetto del formato dell'attributo userLoa del token jws. Il formato dell'attributo deve essere di tipo stringa. In questo caso il controllo è stato applicato automaticamente in corrispondenza di un innalzamento di versione dell'api gateway di ANAC. Si invita in ogni caso a verificare la corretta valorizzazione degli attributi del token poichè l'enforcement delle regole sarà oggetto di progressivi raffinamenti.

Grazie per la risposta, in futuro però queste cose segnatele nel changelog, in quanto possono avere impatti non senza conseguenze. In alternativa sarebbe utile che questo, almeno in ambiente di collaudo, venga riportato all'interno dell'errore stesso.

**Comment by obigno77** [comment]
Gli errori derivanti dal mancato rispetto delle specifiche di interoperabilità sono generati dall'api gateway e non sono personalizzabili.
Come detto questo controllo è stato applicato automaticamente dalla nuova versione dell'api gateway e pertanto non era prevedibile in un changelog.
