### ISSUE TITLE
[Ambiente di Collaudo] ERR4 su CM1/CM2/ANN

### ISSUE THREAD

**Issue by lucaCorigliano-SA** [anticorruzione/npa#1475]
Buongiorno,
all'invio delle nuove schede CM1 / CM2 / ANN in ambiente di collaudo riceviamo sempre ERR9999

```
  "status" => 400
  "title" => "KO"
  "detail" => "SC_N_CRE"
  "type" => "about:blank"
  "errori" => array:1 [
    0 => array:2 [
      "idTipologica" => "errori"
      "codice" => "ERR9999"
    ]
  ]
```

```
 GovWay-Message-ID: 5d53414c-508d-4dcd-a9ba-dd4deec89e7d
 GovWay-Transaction-ID: b7ee32e3-1cee-11ef-bd08-0050568e9679
```

Chiediamo se date schede siano già attive in ambiente di collaudo o se saranno attive solo nella stessa data dell'ambiente di esercizio.

**Comment by obigno77** [comment]
Le nuove schede non erano ancora disponibili al momento dell'apertura della issue. Si prega di riprovare e nel caso aprirne una nuova.
