### ISSUE TITLE
[MAGGIOLI-GRAVE] AD3 IN ERRORE9999 presenti lo stesso in PVL!

### ISSUE THREAD

**Issue by laurapavan** [anticorruzione/npa#1477]
Buongiorno,
si segnalano schede AD3 andate stato AV_N_PUBB per ERR9999 che poi però, (**a posteriori!!**), sono state pubblicate comunque su PVL.
Il RUP, essendo andata in errore la prima scheda, ne aveva creato una seconda acquisendo un nuovo CIG. Dato che anche la seconda scheda è andata in errore, ne ha poi creata una terza (3° cig acquisito), che finalmente è andata a buon fine (stato = AVV_PUBB).

**Tuttavia ad oggi risultano tutti e tre i CIG risultano pubblicati su PVL.**
Quindi a tutti gli effetti sembra che siano stati fatti 3 affidamenti uguali allo stesso soggetto!!
E fortunatamente il cliente ha usato il CIG giusto per le schede di esecuzione…

Il tutto si è verificato tra il 19 e il 25 maggio (perchè le AD3 ci mettevano almeno una giornatina prima di andare in AVV_N_PUBB) , senza alcun intervento lato nostro.
Ovviamente ho aperto un ticket anche via mail, ma visto che non rispondete mai condivido anche qui.

Attendiamo illuminazione, il cliente è un po' agitato. 

Questi i riferimenti:
--------------------------------------------------------
1° AD3 in errore – Cig acquisito B1573C988C
--------------------------------------------------------
Dati identificativi:
IdAppalto: 422fa42b-a52d-48cf-8442-c7513970b9d9
IdAvviso: 282f47c1-40c6-40c5-9a58-ed9af7689d19

ERRORE SEGNALATO (vedi dettaglio response): 

Errori bloccanti segnalati dai servizi ANAC:
    Errore generico durante l'operazione asincrona. Si prega di riprovare.
La pubblicazione dell'avviso ha avuto esito negativo.
ATTENZIONE: È necessario creare nuovamente la scheda correggendo gli errori.

Data evento: 22/04/2024 09:04:52
Govway Transaction Id: 61280c11-0076-11ef-a2a9-00505684399c

------------------------------------------------------------
2° AD3 in errore – CIG acquisito: B15EA0C047
------------------------------------------------------------
Dati identificativi:
IdAppalto: b817ed01-b8c2-4707-853c-72dc5a3f8dc6
IdAvviso: 26b572fd-b4cb-4d8a-af22-d93572e88fbc

ERRORE SEGNALATO (vedi dettaglio response): 
Errore generico durante l'operazione asincrona. Si prega di riprovare.
La pubblicazione dell'avviso ha avuto esito negativo.
ATTENZIONE: È necessario creare nuovamente la scheda correggendo gli errori.

Data evento: 23/04/2024 09:42:22
Govway Transaction Id: d98301ed-0144-11ef-a2a9-00505684399c

-----------------------------------------------------------
3° AD3 PUBBLICATA – CIG acquisito: B1613D3A0F
-----------------------------------------------------------
Dati identificativi:
IdAppalto: 7afeb8a0-a1b7-4bbf-af8f-c58c327f05bb
IdAvviso: d73033cb-b4d3-4087-b524-b3ed53ce0fd2

Pubblicazione completata con successo:
govwayTransactionId":"15cde03b-08ae-11ef-852e-005056844885
timestamp":"02/05/2024 20:15:57

ALLEGATI:
[AD3 - B15EA0C047 (KO).txt](https://github.com/anticorruzione/npa/files/15471788/AD3.-.B15EA0C047.KO.txt)
[AD3 - B1573C988C (KO).txt](https://github.com/anticorruzione/npa/files/15471789/AD3.-.B1573C988C.KO.txt)
[AD3 - B1613D3A0F (OK).txt](https://github.com/anticorruzione/npa/files/15471790/AD3.-.B1613D3A0F.OK.txt)
[response KO cig B15EA0C047.json](https://github.com/anticorruzione/npa/files/15471791/response.KO.cig.B15EA0C047.json)
[response KO cig B1573C988C.json](https://github.com/anticorruzione/npa/files/15471792/response.KO.cig.B1573C988C.json)
[response OK cig B1613D3A0F.json](https://github.com/anticorruzione/npa/files/15471793/response.OK.cig.B1613D3A0F.json)

**Comment by obigno77** [comment]
Si chiude la issue, già presa in carico dal supporto mail dedicato all'esercizio, pregando di non utilizzare molteplici canali per la segnalazione della stessa anomalia e di utilizzare il canale github esclusivamente per le anomalie in ambiente di qualificazione.
