### ISSUE TITLE
BOLZANO/TOSCANA - tempi di attesa per verifica conferma appalto/scheda

### ISSUE THREAD

**Issue by collaudo5** [anticorruzione/npa#1478]
Salve,

in ambiente di collaudo stiamo registrando che i tempi per avere in stato confermato un appalto si sono allungati fino a 1h e 30 min (ID Appalto 8503d041-f007-48d4-82eb-b72788159203), rispetto ai pochi minuti che registravamo in passato. Si tratta di una problematica momentanea o queste tempistiche vanno considerate uno standard per l'ambiente in questione?

Queste tempistiche (attesa conferma appalto, attesa verifica pubblicazione dell'appalto, verifca conferma scheda) stanno rallentando molto la fase di collaudo delle nuove funzionalità che si andranno a rilasciare in esercizio oltre ad impattare gli script dei tool di test automatici utilizzati per i test di No-regression.

Grazie.

**Comment by obigno77** [comment]
Confermiamo il ritardo e stiamo risolvendo il problema
