### ISSUE TITLE
ERR2 - scheda non ammessa in questa fase dell'appalto 

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1480]
Salve,
abbiamo riscontrato il seguente errore:

**ERR2 - scheda non ammessa in questa fase dell'appalto: La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata**

provando ad inviare la **scheda S1** dopo la Scheda **P1_15_2** (**confermata**) per una procedura **bifasica**.

in allegato il json:
[P1_15_2.json](https://github.com/anticorruzione/npa/files/15499967/P1_15_2.json)

**Comment by obigno77** [comment]
Qual è l'idAppalto?

**Comment by UserM21** [comment]
Salve,
id Appalto: 9ff48737-06dc-4991-9b62-52cdc025564d

**Comment by obigno77** [comment]
L'appalto è ancora in attesa di "pubblicazione nazionale"

**Comment by obigno77** [comment]
Duplicato issue 1484
