### ISSUE TITLE
[ARIA S.P.A.] - [BLK] Conferma appalto/scheda bloccato in WT

### ISSUE THREAD

**Issue by sfala** [anticorruzione/npa#1482]
Buongiorno,
segnalo che le richieste di "conferma appalto" e "conferma scheda" rimangono in attesa di elaborazione non consentendoci le attività di testing sugli adeguamenti necessari per allineare la piattafoma al changelog del 21/05/2024.

**Comment by obigno77** [comment]
Il problema segnalato non risulta allo stato presente in ambiente di qualificazione
