### ISSUE TITLE
[Consip] Change log - disallinementi fra change log e swagghere relativamente a campi obbligatori della P7.2

### ISSUE THREAD

**Issue by paolastoroni** [anticorruzione/npa#1483]
stiamo trovando dei disallineamenti tra il change log e lo swaggher relatiovamente alla P7.2
sul changelog non si fa rifeimento ai campi obbligatori datiBaseCPV e il campo cpvPrevalente
mentre sullo swagger comunque è mostrato come obbligatorio

**Comment by anac-uscp** [comment]
<p>I campi  datiBaseCPV e cpvPrevalente sono stati resi obbligatori su tutte le schede. Abbiamo integrato la nota di rilascio inserendo nell’elenco anche il file modello-dati-schede-dati-comuni.yaml dal quale la scheda P7_2 eredita i campi suddetti.</p>
