### ISSUE TITLE
[A2A] - Gestione Flusso P1_15_2 - Impossibile inviare la scheda di aggiudicazione A1_30

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1484]
Salve,
Stiamo riscorntrando errore generico ERR9999 - errore generico per la trasmissione di una scheda A1_30. La scheda di pubblicazione utilizzata è la  P1_15_2.

L'id appalto è il seguente: 9ff48737-06dc-4991-9b62-52cdc025564d

Di seguito i json della scheda A1_30:

[json_input_A1_30_ERR9999_segueP1_15_2 (2).json](https://github.com/user-attachments/files/15512563/json_input_A1_30_ERR9999_segueP1_15_2.2.json)
[json_input_A1_30_ERR9999_segueP1_15_2 (1).json](https://github.com/user-attachments/files/15512564/json_input_A1_30_ERR9999_segueP1_15_2.1.json)

Riuscite a darci un riscontro?
Grazie.

**Comment by obigno77** [comment]
L'appalto è ancora in attesa della "pubblicazione nazionale"

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>da controlli effettuati sui nostri sistemi risulta che in data 2024-06-06 , sia stata tentata la creazione di una scheda con il seguente esito :<br>
<br>
{<br>
      "idTipologica": "errori",<br>
      "dettaglio": "$.eform: null found, string expected",<br>
      "codice": "ERR4" }<br>
}</p>

<p>In particolare non é stato inserito il campo eform nella scheda, pertanto si prega di riprovare con l'operazione inserendo i dati mancanti.<br>
<br>
Restiamo a disposizione per ulteriori chiarimenti.</p>

<p><br>
<br>
Cordiali saluti<br>
<br>
<br>
<br>
<br>
 </p>
