### ISSUE TITLE
[TOSCANA/BOLZANO] - Richiesta chiarimenti e contesto d'uso schede CM1/CM2

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1485]
Salve,
in merito alla issue  **https://github.com/anticorruzione/npa/issues/1452:**

1. Quali sono le schede per cui **non** è previsto l'avviso di rettifica? com'è stato indicato nella risposta alla issue sopra citata.

- Per le **procedure** che **prevedono l’eForm, esiste l'eForm specifico.**
- Per le procedure che **non** provedono l'eForm è previsto **il servizio /rettifica avviso**
come indicato nel file --> https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/specifiche-servizi-appalto.yaml 

3. A cosa fa riferimento il campo "**importo**"? 
4. La **modifica dell'importo** comporta la **variazione del CIG**?
5. Cosa succede se la modifica dell'importo comporta una **variazione della scheda**?
6. Nell'orchestratore, la fase indicata è **AFFIDAMENTO**, ma si rilevano le seguenti incongruenze:

- L'area funzionale **indicata è A_5**
- Tra i flussi di appartenenza (colonna S) si fa riferimento anche ai flussi **40,5,31,32,33,61,62** (Per la Scheda **CM1**) e **50** (Per la scheda **CM2**). Questi flussi riguardano le schede relative alla fase di **Pubblicazione, aggiudicazione** e se si considera nella colonna S, FLusso appartenenza anche " *" allora rientrano anche tutte le schede della fase di esecuzione.
7. Per quale motivo la scheda **AD3** **non è stata inclusa**?
8. La scheda CM1, secondo quanto riportato nello swagger, accetta **un solo CUP**. Come si procede nel caso di **più CUP** 
(Scheda AD4)?

<img width="324" alt="image" src="https://github.com/anticorruzione/npa/assets/144692899/83a8dd58-deb8-4ba4-970e-189465dddc87">

**Si chiedono chiarimenti.**

**Comment by anac-uscp** [comment]
<p>Di seguito le risposte per punto:</p>

<ol>
	<li style="margin-bottom:11px;"><span style="font-size:12pt;"><span><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">Quali sono le schede per cui <strong>non</strong> è previsto l'avviso di rettifica? </span></span></span></span></li>
</ol>

<p style="margin-bottom:11px;margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">Le schede per le quali è previsto l’uso della CM1 sono:<br>
P5 (appalti soggetti a sola tracciabilità)<br>
AD4 (Adesione ad accordo quadro/convenzione senza successivo confronto competitivo),<br>
P3_1, P3_2, P3_3 (Contratti Esclusi)<br>
P6_1, P6_2 (adesione AQ/convenzione con successivo confronto competitivo)</span></span></span></span></p>

<p style="margin-bottom:11px;margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">L’unica scheda per cui è previsto l’uso della scheda CM2 è l’AD5</span></span></span></span></p>

<ul>
	<li style="margin-left:31px;margin-bottom:11px;"><span style="font-size:12pt;"><span><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">Per le <strong>procedure</strong> che <strong>prevedono l’eForm, esiste l'eForm specifico (procedure, a prescindere dall’importo, con invio al TED)</strong><br>
	<u><span style="color:#0070c0;">Servizio modifica appalto</span></u><span style="color:#0070c0;">: ll servizio permette di inviare la scheda per sostituire la precedente istanza dell’Appalto in lavorazione.<br>
	<u>E’ possibile modificare tutti i dati della gara fino a prima della pubblicazione (stato publishing)  dell’avviso </u>da parte del TED.</span></span></span></span></span></li>
</ul>

<p style="margin-bottom:11px;margin-left:71px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><u><span style="color:#0070c0;">Servizio cancella avviso</span></u><span style="color:#0070c0;">: con tale servizio è possibile l’eliminazione di una specifica Scheda dati in lavorazione nelle fasi successive alla pubblicazione</span></span></span></span></p>

<p style="margin-left:71px;text-align:justify;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><u><span style="color:#0070c0;">Servizio rettifica</span></u><span style="color:#0070c0;">: L'avviso rettifica il precedente già pubblicato. </span></span></span></span></p>

<p style="margin-left:71px;text-align:justify;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">Dopo la sottomissione al TED dell’avviso da pubblicare (dallo stato publishing in poi), per richiedere la rettifica sia a livello nazionale sia europeo al fine di rettificare i dati, è necessario inviare la richiesta di pubblicazione di un avviso di rettifica con riferimento all’avviso precedente da rettificare.</span></span></span></span></p>

<p style="margin-left:71px;text-align:justify;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><u><span style="color:#0070c0;">E’ possibile inviare un avviso di rettifica solo entro la data di scadenza della presentazione dell’offerta.</span></u></span></span></span></p>

<ul>
	<li style="margin-left:7px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">Per le procedure che <strong>non</strong> prevedono l'eForm è previsto <strong>il servizio /rettifica avviso</strong><br>
	come indicato nel file --&gt; <a href="https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/specifiche-servizi-appalto.yaml" style="color:#467886;text-decoration:underline;">https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/specifiche-servizi-appalto.yaml</a><br>
	<span style="color:#0070c0;">Per le procedure, a prescindere dall’importo, che non prevedono la pubblicazione al TED che hanno pubblicità a valore legale, non è possibile modificarne i dati poiché la pubblicazione nazionale (PVL) è contestuale all’invio della scheda. Idem per le procedure che non sono ad evidenza pubblica ma che prevedono pubblicità a valore legale.</span></span></span></span></li>
</ul>

<p style="margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><u><span style="color:#0070c0;">Servizio cancella avviso</span></u><span style="color:#0070c0;">: con tale servizio è possibile l’eliminazione di una specifica Scheda dati in lavorazione nelle fasi successive alla pubblicazione</span></span></span></span></p>

<p style="margin-left:48px;text-align:justify;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><u><span style="color:#0070c0;">Servizio rettifica</span></u><span style="color:#0070c0;">: L'avviso rettifica il precedente avviso già pubblicato.<br>
Dopo la pubblicazione in PVL, per richiedere la rettifica a livello nazionale, è necessario inviare la richiesta di pubblicazione di un avviso di rettifica con riferimento all’avviso precedente da rettificare.</span></span></span></span></p>

<p style="margin-left:48px;text-align:justify;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><u><span style="color:#0070c0;">E’ possibile inviare un avviso di rettifica solo entro la data di scadenza della presentazione dell’offerta.</span></u></span></span></span></p>

<ol start="3">
	<li style="text-align:justify;margin-left:8px;"><span style="font-size:12pt;"><span><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><strong>A cosa fa riferimento il campo "importo"?</strong></span></span></span></span></li>
</ol>

<p style="margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">Con le schede CM1 e CM2 è possibile modificare l’importo a base di gara o dell’affidamento.</span></span></span></span></p>

<p style="margin-left:48px;"> </p>

<ol start="4">
	<li style="margin-left:8px;"><span style="font-size:12pt;"><span><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">La <strong>modifica dell'importo</strong> comporta la <strong>variazione del CIG</strong>?</span></span></span></span></li>
</ol>

<p style="margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">Dopo la sottoscrizione del contratto non è possibile inviare la CM1, è necessario inviare una scheda di modifica contrattuale.</span></span></span></span></p>

<ol start="5">
	<li style="margin-left:8px;"><span style="font-size:12pt;"><span><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">Cosa succede se la modifica dell'importo comporta una <strong>variazione della scheda</strong>?</span></span></span></span></li>
</ol>

<p style="margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">Qualora, a seguito della variazione apportata all’importo, si ricada nell’ambito di una scheda differente, è’ necessario cancellare la scheda con la quale è stata avviata la procedura di affidamento ed inviare la scheda corretta, congruentemente al nuovo importo.</span></span></span></span></p>

<ol start="6">
	<li style="margin-left:8px;"><span style="font-size:12pt;"><span><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">Nell'orchestratore, la fase indicata è <strong>AFFIDAMENTO</strong>, ma si rilevano le seguenti incongruenze:</span></span></span></span></li>
</ol>

<p style="margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">L'area funzionale <strong>indicata è A_5</strong></span></span></span></p>

<p style="margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">Stiamo valutando la modifica dell’orchestratore con l’inserimento delle schede CM1, CM2 e ANN, nella fase di ‘pubblicazione’ A3. </span></span></span></span></p>

<p style="margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">Tra i flussi di appartenenza (colonna S) si fa riferimento anche ai flussi <strong>40,5,31,32,33,61,62</strong> (Per la Scheda <strong>CM1</strong>) e <strong>50</strong> (Per la scheda <strong>CM2</strong>). Questi flussi riguardano le schede relative alla fase di <strong>Pubblicazione, aggiudicazione</strong> e se si considera nella colonna S, FLusso appartenenza anche " *" allora rientrano anche tutte le schede della fase di esecuzione.</span></span></span></p>

<p style="margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">Le schede per le quali è previsto l’uso della CM1 sono:<br>
P5 (appalti soggetti a sola tracciabilità)<br>
AD4 (Adesione ad accordo quadro/convenzione senza successivo confronto competitivo),<br>
P3_1, P3_2, P3_3 (Contratti Esclusi)<br>
P6_1, P6_2 (adesione AQ/convenzione con successivo confronto competitivo)</span></span></span></span></p>

<p style="margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">i cui flussi sono riportati nella colonna ‘flussi di appartenenza’.</span></span></span></span></p>

<p style="margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">L’unica scheda per cui è previsto l’uso della scheda CM2 è l’AD5</span></span></span></span></p>

<ol start="7">
	<li style="margin-left:8px;"><span style="font-size:12pt;"><span><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">Per quale motivo la scheda <strong>AD3</strong> <strong>non è stata inclusa</strong>?<br>
	<span style="color:#0070c0;">Perché tale scheda prevede la pubblicità a valore legale</span> </span></span></span></span></li>
	<li style="margin-left:8px;"><span style="font-size:12pt;"><span><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">La scheda CM1, secondo quanto riportato nello swagger, accetta <strong>un solo CUP</strong>. Come si procede nel caso di <strong>più CUP</strong><br>
	(Scheda AD4)?</span></span></span></span></li>
</ol>

<p style="margin-bottom:11px;margin-left:48px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="color:#0070c0;">Le schede CM1 e CM2 saranno modificate al fine di prevedere la modifica di uno o più CUP</span></span></span></span></p>
