### ISSUE TITLE
[A2A] - Gestione Flusso P1_15_2 - ERR9999 per A1_30

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1486]
Salve,

In merito al flusso 115, abbiamo provveduto a pubblicare la scheda P1_15_2 **la quale risulta già pubblicata sulla PVL,**  con id Appalto: 64290eb9-6507-4386-88d0-529d64b263dc

[P1_15_2 64290eb9-6507-4386-88d0-529d64b263dc .json](https://github.com/user-attachments/files/15551539/P1_15_2.64290eb9-6507-4386-88d0-529d64b263dc.json)

Dal file orchestratore, come scheda successiva è prevista direttamente la scheda A1_30.

Quindi proviamo a trasmettere la scheda A1_30 ma stiamo riscontrando problemi nella trasmissione:
[A1_30 64290eb9-6507-4386-88d0-529d64b263dc .json](https://github.com/user-attachments/files/15551558/A1_30.64290eb9-6507-4386-88d0-529d64b263dc.json)

ANAC ci restituisce l'errore ERR9999 - errore generico

- E' corretto che successivamente alla P1_15_2 ci sia direttamente la scheda A1_30 (senza S1/S2)
- Se il primo punto è corretto, come mai riscontriamo l'errore generico indicato sopra?

Grazie.

**Comment by anac-uscp** [comment]
<p>Salve,<br>
<br>
il ticket in questione è da girare a gruppo dati ANAC per effettuare verifiche e confermare che il flusso descritto nell'orchestratore è corretto per le schede di tipo P1_15_2, in quanto si tratta dell'unico caso in cui dalla fase di indizione si passa direttamente alla fase di aggiudicazione senza comunicare prima le schede di tipo S2, che raccolgono gli id dei partecipanti.</p>

<p>Saluti</p>
