### ISSUE TITLE
[BLK] FVOE - Errore nelle chiamate ai servizi

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#1488]
id appalto: f5936c3e-4e92-4fee-80be-dc35358b94ed
codice fiscale fornitore: 05801240150
cig dell'unico lotto di gara: I00206EA71
Chiave di accesso chiamando il servizio /verifica-richiesta-accesso-fvoe: 60d0b443-14fe-4f2a-96e5-2725116ce611

Chiamando il servizio di /ricerca-documenti-fvoe filtrando il meno possibile, ossia compilando solo i dati della chiave d'accesso = 60d0b443-14fe-4f2a-96e5-2725116ce611, page=1 e perPage=20 (come da esempio sullo YAML) la risposta va in errore 404:

{"status":404,"title":"Dato non trovato","errori":[{"id":"errori","codice":"FVX03"}]}

Abbiamo provato a chiamare il servizio /richiedi-documenti (metodo POST) compilando i dati di richiesta come da esempio sullo YAML:

{
  "chiaveAccesso": "60d0b443-14fe-4f2a-96e5-2725116ce611",
  "tipoDocumento": {
    "idTipologica": "tipoDocumento",
    "codice": "00004"
  },
  "datiRichiesta": {
    "annoRiferimento": "2024",
    "domicilioFiscale": {
      "codicecatastale": "I345"
    }
  }
}

La risposta è:

{"type":https://govway.org/handling-errors/404/UndefinedOperation.html,"title":"UndefinedOperation","status":404,"detail":"Operation undefined in the API specification","govway_id":"530dab98-1cce-11ef-8dc0-0050568e08b3"}

**Comment by obigno77** [comment]
Risposto nella issue #1495
