### ISSUE TITLE
Appalto aggiudicato più di una volta

### ISSUE THREAD

**Issue by evalentip** [anticorruzione/npa#149]
Come gestire il caso in cui una scheda di aggiudicazione (es. A1.30) viene trasmessa con il conferma-scheda ma successivamente l'aggiudicazione viene revocata e si procede ad una nuova aggiudicazione?

**Comment by supportoAnac** [comment]
Si tratta di una interruzione anticipata del flusso che può essere trasmessa con la scheda di conclusione. Il TED non prevede questa comunicazione quindi è previsto che in questo caso si trasmetta un nuovo contratto se si procede con lo scorrimento della graduatoria.
