### ISSUE TITLE
Richiesta consultazione servizi appalto

### ISSUE THREAD

**Issue by LorenzograzianiLDO** [anticorruzione/npa#1491]
Avremmo bisogno di un chiarimento circa la necessità dell'operazione di presa in carico per  all'utilizzo  dei servizi per la ricerca e consultazione di appalti e schede, nello specifico:
- ricerca appalto
- consulta appalto
- stato appalto
- ricerca scheda
- consulta schede
Per tali servizi è sempre necessario che il soggetto utilizzatore abbia precedentemente effettuato l'operazione di presa in carico?
In caso affermativo esiste una modalità alternativa di consultazione delle informazioni di un appalto, che sia aperta anche a chi non abbia effettuato precedentemente la presa in carico?
Vi ringrazio per la diponibilità,

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>per la visualizzazione dei dati, l'RP deve utilizzare il metodo di presa-carico per autorizzarsi a vedere i dati dell'appalto, ed il servizio aggiungi-soggetto per abilitare altri delegati alla visualizzazione dei dati.</p>

<p>Se non sono state effettuate modifiche in tal senso, l'unico autorizzato a vedere i dati dell'appalto è l'RP che ha invocato il servizio di crea-appalto in origine ed è lui che deve almeno invocare il servizio di aggiunta del soggetto per assegnare dei delegati all'appalto, mentre il servizio di presa-carico deve essere invocato dal nuovo RP che deve prendere in carico l'appalto per effettuare la modifica.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
