### ISSUE TITLE
Gestione accordi quadro (art. 59 del Codice degli Appalti)

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1492]
si chiede conferma delle schede da utilizzare nelle diverse fasi del processo relativo ad un AQ:

1. P1_16 o P2_16 (sopra e sotto soglia) con l'indicazione del valore "6" nel campo "strumentiSvolgimentoProcedure"
2. AD4 per gli ordini derivanti da AQ ad una fase con indicazione nel campo "cig" del CIG dell'AQ da cui deriva
3. P6_2 per i confronti competitivi successivi all'AQ con indicazione nel campo "cigAccordoQuadro" del CIG dell'AQ

per quanto concerne i passi successivi si procede come indicato dall'orchestratore.

**Comment by anac-uscp** [comment]
<p>Di seguito le risposte ai vari punti:</p>

<p style="margin-bottom:20px;"><span style="font-size:12pt;"><span style="line-height:normal;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.5pt;"><span style='font-family:"Segoe UI",sans-serif;'><span style="color:#1f2328;">1 - L’Accordo Quadro/Convenzione è uno strumento presente in tutte le schede che possono prevedere contratti di tipo accordo quadro/ convenzione ed è selezionabile indicando la voce 6 ‘Accordo quadro’ del campo ‘DatiBaseStrumentoProcedura’.</span></span></span></span></span></span></p>

<p style="margin-bottom:20px;"><span style="font-size:12pt;"><span style="line-height:normal;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.5pt;"><span style='font-family:"Segoe UI",sans-serif;'><span style="color:#1f2328;">2 – Esatto, nella scheda AD4 è possibile indicare il CIG padre (CIG dell’AQ/Convenzione a cui si aderisce) nel campo CIG dell’oggetto ‘AppaltoAD4Type’</span></span></span></span></span></span></p>

<p><span style="font-size:10.5pt;"><span style="line-height:115%;"><span style='font-family:"Segoe UI",sans-serif;'><span style="color:#1f2328;">3 – Vedi il punto 2</span></span></span></span><br>
 </p>
