### ISSUE TITLE
[Consip] RETTIFICA - ERR4 su codiceAppalto

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1494]
Salve,
da changelog si legge: 
**Impostata la minLength a 8 sul codiceAppalto (si raccomanda l'adozione immediata per consentire l'enforcement rinviato a settembre)**

dai test effettuati in ambiente di qualificazione l'enforcement risulta presente.
In particolare, abbiamo provato ad effettuare una rettifica su un appalto avente codiceAppalto con minLenght < 8 e riscontriamo l'errore seguente:
**ERR4 - $.anacForm.appalto.codiceAppalto: must be at least 8 characters long**

GovWay-Message-ID=[c15b66f9-c4e0-4873-b3a0-3c389e0ea401]
GovWay-Transaction-ID=[3bf468e2-24d2-11ef-bd08-0050568e9679]

prevedete di apportare una correzione oppure possiamo presumere che l'enforcement sia presente in qualificazione ma non lo sarà in ambiente di produzione? 
Grazie

**Comment by obigno77** [comment]
L'enforcemente è rimasto in qualificazione per sollecitarne l'adozione ma non sarà immediatamente in esercizio
