### ISSUE TITLE
[BLK] - FVOE utilizzo dei nuovi scenari di esempio

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#1495]
Buongiorno,
durante l'ultimo incontro (06/06/2024) è stato comunicato il rilascio dei nuovi scenari di esempio per accedere ai fascicoli FVOE.
Prima della pubblicazione di questi scenari riuscivamo, utilizzando l'utenza RUP con CF: USRRUP12A01A102A ad  invocare correttamente i seguenti servizi (vedere issue #1488 non ancora chiusa):

- /richiesta-accesso-fvoe
- /verifica-richiesta-accesso-fvoe ottenendo la chiaveAccesso: 60d0b443-14fe-4f2a-96e5-2725116ce611
- /ricerca-documenti-fvoe con chiaveAccesso precedentemente ottenuta avevamo la **risposta 404 con il seguente errore**:

{"status":404,"title":"Dato non trovato","errori":[{"id":"errori","codice":"FVX03"}]}

Abbiamo fatto una prova utilizzando, con lo stesso utente RUP (CF: USRRUP12A01A102A) i **nuovi scenari di esempio** documentati all'url:
https://github.com/anticorruzione/npa/blob/main/docs/scenari-di-esempio/gestione_fascicolo.md
con: 

codiceFiscaleOE=11111111113
uuidAppalto=4f8f5660-87e8-4dbb-b325-17e216f4a519

Ora richiamando il servizio:

- /richiesta-accesso-fvoe viene restituito **errore 401 Unauthorized**

di seguito i transaction-id per quest'ultima operazione:

GovWay-Message-ID: ed288d0e-ec50-45c3-aadd-c76c05373946
GovWay-Transaction-ID: 289ea417-2710-11ef-8dc0-0050568e08b3

Il RUP indicato ha associato il nuovo idAppalto? Da cosa potrebbe dipendere l'errore riportato?

Grazie

**Comment by anac-uscp** [comment]
<p>Gentile Utente,<br>
<br>
si chiede di riprovare ad eseguire la richiesta, per poter analizzare nel dettaglio l'anomalia riscontrata,<br>
In quanto la richiesta non è recente e non abbiamo la possibilità di analizzare i dati inseriti.<br>
<br>
Si chiede di riprovare e di fornire il transaction id del nuovo tentativo.<br>
<br>
Restiamo a disposizione<br>
<br>
Cordiali Saluti </p>
