### ISSUE TITLE
[FVOE] ricerca-documenti-fvoe errore FVX03

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1496]
Dopo aver aggiornato la richiesta su PDND, per poter sfruttare la versione 4 dell'eService "PCP - FVC", abbiamo tentato nuovamente alcune chiamate per poter verificare gli scenari di esempio pubblicati a questo link (https://github.com/anticorruzione/npa/blob/main/docs/scenari-di-esempio/gestione_fascicolo.md).

In data 07/06/2024 Abbiamo inviato una scheda S2 correttamente per l'appalto con idAppalto ef9f8f80-a5a8-446f-9ad0-528e6e3a01c7
govway-message-id: 8f2509c3-b935-4830-92dc-d5a5b68223a3
govway-transaction-id: ce7acf3e-24da-11ef-bd08-0050568e9679

Di seguito il payload della richiesta

{
	"idAppalto": "ef9f8f80-a5a8-446f-9ad0-528e6e3a01c7",
	"scheda": {
		"body": {
			"anacForm": {
				"elencoSoggetti": [
					{
						"cig": "I005F76E49",
						"invitatiCheNonHannoPresentatoOfferta": [],
						"partecipanti": [
							{
								"paeseOperatoreEconomico": "Italia",
								"avvalimento": false,
								"idPartecipante": "166128a8-ae9b-0b17-e063-0806020a67fb",
								"codiceFiscale": "11111111113",
								"denominazione": "Catanzaro_Supplier",
								"ruoloOE": {
									"idTipologica": "ruoloOE",
									"codice": "3"
								},
								"tipoOE": {
									"idTipologica": "tipoOE",
									"codice": "1"
								}
							},
							{
								"paeseOperatoreEconomico": "Italia",
								"avvalimento": false,
								"idPartecipante": "166128a8-ae98-0b17-e063-0806020a67fb",
								"codiceFiscale": "11111111114",
								"denominazione": "Catanzaro Supplier 04",
								"ruoloOE": {
									"idTipologica": "ruoloOE",
									"codice": "3"
								},
								"tipoOE": {
									"idTipologica": "tipoOE",
									"codice": "1"
								}
							}
						],
						"dataScadenzaPresentazioneOfferta": "2024-06-07T16:45:00+02:00"
					}
				]
			}
		},
		"codice": {
			"idTipologica": "codiceScheda",
			"codice": "S2"
		},
		"versione": "1.0"
	}
}

La scheda è stata correttamente confermata
govway-message-id: b8720e1b-7b6c-4a21-a509-0a864bccfe4b
govway-transaction-id: d0bb97a7-24da-11ef-bd08-0050568e9679

Dopo di che è stata fatta una richiesta di accesso FVOE per il seguente codice fiscale 11111111114 ed abbiamo ottenuto correttamente la chiave di accesso 3ae41111-b9b7-41cd-a78e-2faf0a4a404b

A questo punto abbiamo richiamato l'api ricerca-documenti-fvoe utilizzando la chiave d'accesso in questione ma otteniamo sempre lo stesso errore

status: 404,
title: 'Dato non trovato',
errori: [ { id: 'errori', codice: 'FVX03' } ]

govway-message-id: b358071a-4174-4f7b-9d2c-30cd81e64d0b
govway-transaction-id: bc228c7f-2712-11ef-bd08-0050568e9679

Cosa stiamo sbagliando? 
Non dovremmo trovare dei documenti per questo codice fiscale ora che ci sono gli scenari d'esempio e siamo allineati con la versione 4 del servizio?

**Comment by obigno77** [comment]
Buongiorno, il problema è stato individuato e sarà fixato entro domani 14/06. Ala rilascio della soluzione si procederà alla chiusura della issue. Sarà necessario ripetere la richiesta di accesso al fascicolo.

**Comment by anac-uscp** [comment]
<p>In attesa di fix</p>
