### ISSUE TITLE
info su comunicazione alla banca dati del Collegio Consultivo Tecnico

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#1497]
Spett.le Anac,
con riferimento al Collegio Consultivo Tecnico disciplinato dall'art. 215 D.lg 36/2023, non abbiamo trovato riferimenti nelle schede da inviare ad ANAC.

I nostri dubbi sono i seguenti:
-	Quando viene costituito il CCT seguendo le modalità disciplinate dall’art. Art. 2 - Costituzione e insediamento del Collegio dell’All. V.2, la stessa costituzione va comunicata in qualche modo (tramite scheda o comunque tramite piattaforma) all’ANAC dalla SA?
-	Quando viene attivato il CCT per prevenire eventuali controversie, per cui le sue determine assumono valore di lodo contrattuale ai sensi dell’art. 808 ter c.p.c., la SA ha l’obbligo di comunicare ad ANAC le determine del CCT che hanno modificato l’esecuzione del contratto?

In attesa di riscontro, si ringrazia anticipatamente.

**Comment by anac-uscp** [comment]
<p>Attualmente non è prevista una scheda per la trasmissione dei dati alla BDNCP. I relativi obblighi di trasparenza vanno assolti secondo le modalità indicate dall’Autorità con le delibere 261, 263 e 264 del 2023. <br>
 </p>
