### ISSUE TITLE
[CONSIP] scheda I1 errore REG60

### ISSUE THREAD

**Issue by LorenzograzianiLDO** [anticorruzione/npa#1498]
Inviando in ambiente di collaudo una scheda I1 con il seguente tracciato:

{"avvioPerFasi":true,"dataAvvioPrimaFase":"2024-05-21T00:00:00Z","consegnaSottoRiserva":false,"dataEffettivoInizio":"2024-05-21T00:00:00Z","dataFinePrevista":"2025-05-21T00:00:00Z","idContratto":"dbfbe694-1e0d-46a7-8233-e0d93fe63899"}

riceviamo sul servizio di conferma-scheda l'errore REG 60 . "indicare la data del verbale di consegna definitiva".

teoricamente  la REG 60 dovrebbe attivarsi nel momento in cui la consegna frazionata risulti diversa da null o false , ma noi non la mandiamo essendo il CIG servizi e forniture.

sarebbe necessario un chiarimento in tal senso.

CIG: I004B46587
idAppalto: 6740d5b5-dc03-4397-8e2a-5926eb9829a0

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Da requisiti ANAC il campo data verbale consegna definitiva è obbligatorio quando il campo consegna frazionata è false, non è esplicitato un legame con l'oggetto del contratto lavori, per cui la regola è in linea con quanto richiesto.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
