### ISSUE TITLE
Fascicolo virtuale operatore economico

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#15]
Dalla documentazione fornita non esiste un servizio/flusso che istanzia un oggetto di tipo FVOE. Come viene istanziato l'oggetto di tipo FVOE?

Inoltre dai documenti di pianificazione, non si evince da quando saranno disponibili i servizi di interoperabilità per il test pubblico sul tema FVOE (la «Delibera numero 464 del 27 luglio 2022» definisce che Le SA e gli OE per ottenere il «PASSOE» possono avvalersi della piattaforma esterna creata ad hoc del FVOE)

**Comment by supportoAnac** [comment]
Il payload non prevede più come obbligatori gli oggetti.
