### ISSUE TITLE
Errore validazione eForm su scheda P1_23

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#1501]

**Comment by FRASCA57** [comment]
[TeamSystem] BLK
in ambiente di qualificazione l'invio della scheda P1_23 (all'invio dell'esito operazione) genera il seguente errore durante la validazione dell'eForm:

AP_N_CONF : ERR46 - [500] during [POST] to [http://pcp-qlf-ted-ms.pcp-qlf.svc:8080/validate?language=it] [TedMsClient#validate(String,String)]: [{"code":500,"status":"500 INTERNAL_SERVER_ERROR","title":"Unrecognized field \"status\" (class it.anticorruzione.ms.ted.tedms.dto.TedCVSViewerErrorResponse), not marked as ignorable (5 known propertie... (587 bytes)];
 
Di seguito GovWayMessageId":" f27ba8ad-9afd-4fa6-a8a2-b05f1fed6971","GovWayTransactionId":" b541de37-270f-11ef-bd08-0050568e9679

**Comment by FRASCA57** [comment]
Lo stesso errore ricorre anche per questi altri idAppalto:
bfa67b1b-8b5f-4cc2-99a9-f4e54500bc94, "GovWayMessageId":" f27ba8ad-9afd-4fa6-a8a2-b05f1fed6971","GovWayTransactionId":" b541de37-270f-11ef-bd08-0050568e9679"
 
7a96f56f-ab28-4d88-9521-00700a1caf33, "GovWayMessageId":" 63c4bbb0-ce3d-4a62-a3c3-742dc00c3de2","GovWayTransactionId":" c4ba5c6b-2417-11ef-8dc0-0050568e08b3"

**Comment by anac-uscp** [comment]
<p>Gentile utente,<br>
<br>
da controlli effettuati sui nostri sistemi l'appalto risulta in stato "CANC" ovvero cacellato, pertanto la problematica si ritiene risolta.<br>
<br>
Restiamo a disposizione per ulteriori chiarimenti.<br>
<br>
<br>
Cordiali saluti.<br>
 </p>
