### ISSUE TITLE
[FVOE] - Richiesta Accesso FVOE non più disponibile

### ISSUE THREAD

**Issue by LuigiScortichino** [anticorruzione/npa#1502]
Buon pomeriggio
da diverso tempo riscontriamo sempre un errore quando si invoca l' endpoint /richiesta-accesso-fvoe in ambiente di qualificazione https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiesta-accesso-fvoe

Di fatto utilizzando (come sempre fatto in passato) il cf 11111111114 viene sempre restituito l'errore  SCH01 

Il codice fiscale dell'utente che invoca il servizio è LBAMRC71L29H501

Visto che l'errore di codice SCH01 da' come messaggio: "Soggetto Non Presente Nelle Schede Inviate", sembra che l'utente con CF LBAMRC71L29H501P (ed il relativo fascicolo ad esso associato) non sia più censito correttamente nelle schede.

Di seguito vi riportiamo anche una serie di coordinate di uno degli ultimi esempi di invio
agli header vengono aggiunti:

Token(header={kid=FmqelZd1-6U-M4_-7Ea0YGY2sOIk1FXpZBonh7kAnug, typ=JWT, alg=RS256}, 
      payload={traceID=cb0fde1d-269d-456a-ba16-9ee781b670d9, 
				userIdpType=SPID, regCodiceComponente=0000010, 
				purposeId=eb7feaef-0ac0-4460-84fa-1de53adb764d, 
				userLoa=3, regCodicePiattaforma=0000009, 
				SACodiceFiscale=05359681003, 
				spanID=90aca30c-39d6-43df-90c5-e1fa8756c943, 
				aud=https://apigw-test.anticorruzione.it/modi/rest/FVC/v2, 
				businessFlowID=7b53d66f-afa2-4f30-8eea-39d2e84665af, 
				userRole=RP, 
				SAcodiceAUSA=9000000008, 
				jti=ffd951c3-1c9f-4435-9398-a1b6df72d49b, 
				userCodiceFiscale=LBAMRC71L29H501P})

Il servizio invocato
https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiesta-accesso-fvoe

Il payload dell'invocazione

{
	"dataInizioAutorizzazione": "2024-06-13T11:46:04Z",
	"operatoriEconomici": [
		{
			"codiceFiscale": "11111111114"
		}
	],
	"appalto": {
		"idAppalto": "0db87ce4-acdf-4b42-b4fa-94264c1cf228"
	}
}

le coordinate GovWay:
GovWay-Message-ID: 9a5d85d2-81ee-4dc5-a894-e4a8b77791fc
GovWay-Transaction-ID: c1a7e254-2967-11ef-8dc0-0050568e08b3

La response ottenuta:
{
	"detail": ">11111111114<",
	"status": 404,
	"title": "Dato non trovato",
	"errori": [
		{
			"id": "errori",
			"codice": "SCH01"
		}
	]
}

Rimaniamo in attesa di ricevere aggiornamenti in merito.

**Comment by obigno77** [comment]
Il CF dell'OE per il quale si chiede l'accesso al fascicolo DEVE essere stato precedentemente inviato come Partecipante/Aggiudicatario in una delle seguenti schede: S1, S2, S4, RSU1, AD1_25, AD1_26, AD1_27, AD1_28, AD2_25, AD2_26, AD2_27, AD2_28, AD2_29, AD3, AD4 e AD5. Nel caso specifico si tratta di una scheda AD5 dove il codice fiscale del caso di test non corrisponde a quello dell'aggiudicatario dell'AD5 1111111111111111
