### ISSUE TITLE
Errore PCPCode List v4 errore Get Status

### ISSUE THREAD

**Issue by petromanco** [anticorruzione/npa#1504]
Abbiamo effettuato le ulteriori prove seguendo le varie issue indicate ma continuiamo a ricevere il seguente errore:

{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "018e20c6-2a4b-11ef-bd08-0050568e9679"
}

possiamo sapere il dettaglio?

C'è un modo per risalire al dettaglio dell'errore senza aprire nuove issue?

Possiamo avere un contatto diretto a cui far riferimento così da poter scambiare i dati utilizzati per la creazione dei vari JWS / client_assertion?

Grazie

**Comment by obigno77** [comment]
Non riusciamo a risalire a questo transaction id. E' possibile fare un nuovo tentativo? Una volta verificato questo potete utilizzare la casella suppporto.pdnd@anticorruzione.it per ulteriori approfondimenti

**Comment by petromanco** [comment]
@obigno77 oltre da inviare la mail al supporto le fornisco la mia mail, p.manco@imperiumsolution.it, in tal modo da poter avere un suo contatto diretto così da inviarle, nella necessità, il test nella sua interezza in quanto contiene dati sensibili.

Grazie

**Comment by obigno77** [comment]
non è necessario inviare la traccia completa perchè la intercettiamo noi sugli apparati. Avete fatto un nuovo tentativo?

**Comment by petromanco** [comment]
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "459f1e90-2eec-11ef-bd08-0050568e9679"
}
questa la response della chiamata appena eseguita.

**Comment by obigno77** [comment]
Recuperata ultima transazione del 17 giugno. Il token è carente dei claim obbligatori del blocco di tracing.
[GOVWAY-101] [Header 'Agid-JWT-TrackingEvidence'] Token senza claim 'businessFlowID'
[GOVWAY-101] [Header 'Agid-JWT-TrackingEvidence'] Token senza claim 'traceID'
[GOVWAY-101] [Header 'Agid-JWT-TrackingEvidence'] Token senza claim 'spanID'

**Comment by petromanco** [comment]
businessFlowID dobbiamo richiamare prima l'e-service 'ComunicaAppalto'? (Richiesta in attesa di approvazione)
traceID e spanID sono di tipo UUID v4 da generare autonomamente?

**Comment by obigno77** [comment]
Il businessFlowID può essere 00000000-0000-0000-0000-000000000000 per tutti i servizi che non sono direttamente collegati a uno specifico appalto.
traceID e spanId sono codici interni generati dalla piattaforma per identificare rispettivamente la singola transazione e la catena di transazioni collegate
Tutti e tre sono UUID v4.

**Comment by petromanco** [comment]
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "48474b97-2fb6-11ef-bd08-0050568e9679"
}

nonostante l'aggiunta dei parametri indicati mi ritorna il seguente errore.

Dove sbagliamo?

**Comment by obigno77** [comment]
Il token jws ha una vadlità di 10 secondi. Ci sta arrivando già scaduto.
Un caso simile è stato gestito nella issue 889

**Comment by obigno77** [comment]
Riapro la issue in attesa di conferma della soluzione

**Comment by petromanco** [comment]
JWS1:
{
  "iss": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "sub": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "aud": "https://apigw-test.anticorruzione.it/modi/rest/CodeList/v2",
  "purposeId": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "jti": "5ec896f6-4a0c-4f72-bd49-9792d9f2c6f8",
  "iat": 1718977604,
  "exp": 1721569604,
  "userCodiceFiscale": "AAAAAA00A01H501Z",
  "userRole": "RP",
  "userLoa": "3",
  "userIdpType": "SPID",
  "SACodiceFiscale": "80184430587",
  "SAcodiceAUSA": "0000247758",
  "regCodicePiattaforma": "0000001",
  "regCodiceComponente": "0000001",
  "businessFlowID": "00000000-0000-0000-0000-000000000000",
  "traceID": "b936c5c0-e6a6-4fb8-9db0-b065fcfb7344",
  "spanID": "df315ce4-3f77-4edd-bff5-f6d43d7ff0cc"
}

JWS 2:
{
  "iss": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "sub": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "aud": "auth.uat.interop.pagopa.it/client-assertion",
  "purposeId": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "jti": "5ec896f6-4a0c-4f72-bd49-9792d9f2c6f8",
  "iat": 1718977604,
  "exp": 1721569604,
  "userCodiceFiscale": "AAAAAA00A01H501Z",
  "userRole": "RP",
  "userLoa": "3",
  "userIdpType": "SPID",
  "SACodiceFiscale": "80184430587",
  "SAcodiceAUSA": "0000247758",
  "regCodicePiattaforma": "0000001",
  "regCodiceComponente": "0000001",
  "businessFlowID": "00000000-0000-0000-0000-000000000000",
  "traceID": "b936c5c0-e6a6-4fb8-9db0-b065fcfb7344",
  "spanID": "df315ce4-3f77-4edd-bff5-f6d43d7ff0cc",
  "digest": {
    "alg": "SHA256",
    "value": "e271efd94f797c13da87935453d3cb8bd4affe41d52dfb5799c0fee25fcb4c4d"
  }
}

ACCESS_TOKEN:
{
  "aud": "https://apigw-test.anticorruzione.it/modi/rest/CodeList/v2",
  "sub": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "nbf": 1718977604,
  "digest": {
    "alg": "SHA256",
    "value": "e40a80815fb71a223aab9ad3dc4360e3775b26926daf06fcade7efc1a5789616"
  },
  "purposeId": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "iss": "uat.interop.pagopa.it",
  "exp": 1718981204,
  "iat": 1718977604,
  "client_id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "jti": "05a4b055-643b-484d-bd3b-c4061daac0c1"
}

Response associata a questi token:
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "ca55ac18-2fd0-11ef-bd08-0050568e9679"
}

Qual è il dettaglio dell'errore in questo caso considerando che nell'access_token  i parametri iat e nbf coincidono e sono "venerdì 21 giugno 2024 15:46:44" mentre exp è impostato a "venerdì 21 giugno 2024 16:46:44", invece per JWS iat è impostato "venerdì 21 giugno 2024 15:46:44" mentre exp è impostato a "domenica 21 luglio 2024 15:46:44"

Non riusciamo a capire come risolvere l'errore.

Grazie

**Comment by obigno77** [comment]
A noi la richiesta è arrivata alle 15:47:42 quindi il token era scaduto da quasi un minuto. Se state facendo richieste manualmente da soapui o client similari dubito che riusciate a rimanere nei 10 secondi di validità del token.
