### ISSUE TITLE
Errore tipologica PCP Scheda P3_1 'motivoEsclusioneOrdinarioSpeciale'

### ISSUE THREAD

**Issue by ChiumeraChristian** [anticorruzione/npa#1505]
Nella tipologica della P3_1 da piattaforma web PCP sono presenti valori con data fine decorsa, come riportato nel json di cui al link di seguito. Infatti selezionando quello riferito ai servizi legali, viene restituito l'errore "tipologica non valida - 'motivoEsclusioneOrdinarioSpeciale' : {'motivoEsclusioneOrdinarioSpeciale' : '18'}"

https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/tipologiche/motivoEsclusioneOrdinarioSpeciale.json

![Tipologica Motivo Esclusione Ordinario Speciale P3_1](https://github.com/anticorruzione/npa/assets/143389061/26348e8a-b534-42a3-9d7b-fcd4034aca81)

    "codice":"18",
    "descrizione": {
		"it": "Servizi legali (rappresentanza legale in un arbitrato o in una conciliazione, rappresentanza legale in giudizio, consulenza legale in vista di un giudizio, servizi di certificazione e autenticazione di documenti prestati da notai, servizi legali prestati da fiduciari o tutori designati da organi giurisdizionali o per legge, altri servizi legali connessi all’esercizio di pubblici poteri).",
		"en": "Servizi legali (rappresentanza legale in un arbitrato o in una conciliazione, rappresentanza legale in giudizio, consulenza legale in vista di un giudizio, servizi di certificazione e autenticazione di documenti prestati da notai, servizi legali prestati da fiduciari o tutori designati da organi giurisdizionali o per legge, altri servizi legali connessi all’esercizio di pubblici poteri)."
		},
    "dataInizio":"1970-01-01T00:00:00Z",
    **"dataFine":"2024-05-28T00:00:00Z"**

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>La problematica è stata risolta con la fix rilasciata giorno 01-07-2024.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
