### ISSUE TITLE
[FVOE] - Richiedi documenti - Codice catastale comune, regole di validazione 

### ISSUE THREAD

**Issue by LuigiScortichino** [anticorruzione/npa#1509]
Buongiorno,
vi contattiamo per segnalare una incongruenza che abbiamo riscontrato nelle specifiche del nuovo endpoint /richiedi-documenti in ambiente di qualificazione (https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti)

in particolare nello swagger https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/specifiche-servizi-fvoe-fva.yaml

Su quattro tipi di richiesta, tra i vari campi da inviare, c'è il codice-catastrale-comune che anche se definito con nomi differenti fa riferimento sempre allo stesso tipo di dato (almeno questa è la nostra interpretazione).

Il pattern di validazione di questo campo, però, risulta differente nelle varie descrizioni, di seguito il riepilogo di quanto riscontrato:

DatiSA_00004 CodiceCatastoComuneItaliano pattern: ^[A-Z]\d{3}$
DatiSA_00020 CodiceCatastoComuneItaliano pattern: ^[A-Z]\d{3}$
DatiSA_00036 CodiceCatastoComuneItaliano pattern: ^[A-M]\d{3}$
DatiSA_00050 CodiceCatastoComuneItaliano pattern: nessun pattern definito

Per consentire di avere uniformità di trattamento del dato sulla nostra applicazione, vorremmo sapere quale pattern applicare, o se è necessario adottare per ognuno dei codici suddetti regole diverse.

Grazie mille

[pattern-codice-catastale-comune.docx](https://github.com/user-attachments/files/15865741/pattern-codice-catastale-comune.docx)

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Ogni tipo Documento ha una propria logica di validazione dipendente in parte dalle regole espresse dall'ente certificante.</p>

<p>Come riportato nello yaml del modello dati <strong><a href="https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/modello-dati-fvoe-fva.yaml">https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/modello-dati-fvoe-fva.yaml</a></strong></p>

<p><strong> DatiSA_00050</strong> nell'attributo <strong>LuogoNascita_soggetto</strong> - codice catastale del comune di nascita/stato di nascita estero</p>

<p>definisce il pattern come :<strong> ^(([A-M]\d{3}$)|Z\d{2}[1-9])</strong></p>

<p>Vi anticipo che verrà a breve rilasciata una modifica per il modello dati <strong>DatiSA_00050</strong></p>

<p>Sono state aggiunte<strong> due proprietà obbligatorie</strong>.<strong> il codicePrefettura </strong>che la SA dovrà popolare tra una lista definita (tipoPrefettura.json) e un booleano <strong>altrisoggetti </strong>che viene popolato a true solo se si richiede il documento anche per altri soggetti<strong> .</strong>Si ricorda che per default viene richiesto il documento per<strong> </strong>l'OE</p>

<p><strong>Se altrisoggetti  = false </strong>allora <strong>soggetto_da_verificare non viene considerato</strong></p>

<p><strong>Se altrisoggetti  = true</strong> allora <strong>soggetto_da_verificare</strong> deve essere presente e con almento un soggetto.</p>

<p>Un estratto del modello dati</p>

<p>    DatiSA_00050:<br>
      description: &gt;-<br>
        Oggetto che riporta i dati per richiedere il documento COMUNICAZIONE ANTIMAFIA<br>
      type: object<br>
      additionalProperties: false<br>
      required:<br>
        - altrisoggetti<br>
        - prefettura<br>
      properties:<br>
        prefettura:<br>
          description: Prefettura. Fare riferimento ai valori contenuti nel file [tipoPrefettura.json](<a href="https://raw.githubusercontent.com/anticorruzione-test/npa/main/docs/modello-dati/tipologiche/tipoPrefettura.json">https://raw.githubusercontent.com/anticorruzione-test/npa/main/docs/modello-dati/tipologiche/tipoPrefettura.json</a>)<br>
          pattern: IT-(AG|AL|AN|AO|AR|AP|AT|AV|BA|BT|BL|BN|BG|BI|BO|BZ|BS|BR|CA|CL|CB|CI|CE|CT|CZ|CH|CO|CS|CR|KR|CN|EN|FM|FE|FI|FG|FC|FR|GE|GO|GR|IM|IS|SP|AQ|LT|LE|LC|LI|LO|LU|MC|MN|MS|MT|ME|MI|MO|MB|NA|NO|NU|OR|PD|PA|PR|PV|PG|PU|PE|PC|PI|PT|PN|PZ|PO|RG|RA|RC|RE|RI|RN|RM|RO|SA|SS|SV|SI|SR|SO|SU|TA|TE|TR|TO|TP|TN|TV|TS|UD|VA|VE|VB|VC|VR|VV|VI|VT)$<br>
          type: string<br>
        altrisoggetti:<br>
          type: boolean<br>
          description: Presenza di soggetti da verificare<br>
        soggetto_da_verificare:<br>
          description: Lista dei nominativi<br>
          type: array<br>
          minItems: 1<br>
          items:<br>
            $ref: '#/components/schemas/Soggetto_00050'</p>

<p> </p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
