### ISSUE TITLE
[FVOE] - Richiedi Documenti - Codici errori non presenti nella documentazione

### ISSUE THREAD

**Issue by LuigiScortichino** [anticorruzione/npa#1510]
Buongiorno,

vi contattiamo per un problema nell'invio di alcune richieste verso il nuovo endpoint /richiedi-documenti in ambiente di qualificazione
(https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti)

In particolare abbiamo riscontrato il fatto che in alcuni casi (di seguito dettagliati) sono stati restituiti dei codici-errore **(FVC02, FVX55**) non censiti sulla risorsa 
https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/tipologiche/errori.json

da voi indicata nello swagger
https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/specifiche-servizi-fvoe-fva.yaml

E' possibile avere una decodifica dei codici di errore su citati?

Grazie mille 

-----------------------------------------------------------------------

URL:https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/verifica-stato-richiesta-documento?idRichiesta=4a0d97e0-6463-4cd4-9c57-2ca096d645d2

GovWay-Message-ID: 813af87c-7742-4d20-b52c-f0967b8ea254
GovWay-Transaction-ID: 69b38ae2-2963-11ef-8dc0-0050568e08b3

2024-06-13 11:22:33 DEBUG ApiClient:1005 - Response body FVOE:
{"status":404,"title":"Dato non trovato","errori":[{"id":"errori","codice":"FVC02"}]}

-----------------------------------------------------------------------

URL:https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti

{
	"chiaveAccesso": "7bc81909-2fe9-44a1-8285-d2e8fdd52c7e",
	"tipoDocumento": {
		"idTipologica": "4",
		"codice": "00004"
	},
	"datiRichiesta": {
		"datiSoggetti": [
			{
				"DatiNominativo": {
					"Nome": "Carlo",
					"Cognome": "Magno",
					"Sesso": "M",
					"CF": "RSSCRL67E41C351E",
					"DatiNascita": {
						"Giorno": "31",
						"Mese": "03",
						"Anno": "25",
						"CodiceCatastoStato": "Z000",
						"CodiceCatastoComuneItaliano": "H501"
					}
				},
				"AltriDati": {
					"LinguaTedesca": true
				}
			}
		],
		"type": "DatiSA00004"
	}
}

GovWay-Message-ID: 93886f7f-2740-4250-841c-99193c7f41fe
GovWay-Transaction-ID: ff622726-2b5d-11ef-bd08-0050568e9679

Response body FVOE:
{"status":400,"title":"Richiesta malformattata","errori":[{"id":"errori","codice":"FVX55"}]}

-----------------------------------------------------------------------

**Comment by stalex1** [comment]
Gentile Utente,

In allegato sono riportati i codici di errore mancanti.
La trascodifica degli errori potrà subire delle variazioni. La documentazione nel sito ANAC verrà aggiornata a breve.

di seguito una breve sintesi delle cause che possono generare gli errori

FVX53 - restituito nel caso la ricerca delle notifiche non possa essere eseguita (uso Interno del FE)
FVX54 - restituito nel caso la notifica non possa essere aggiornata (uso Interno del FE)
FVX55 - restituito nel caso in cui nel servizio /richiedi-documenti siano passati dei dati non coerenti con la struttura attesa per il tipo documento . *
FVX56 - restituito nel caso in cui nel servizio /richiedi-documenti sia passato un tipo documento di cui  non si possa richiedere la documentazione. *
FVX57 - restituito nel caso in cui nel servizio /richiedi-documenti non vengano passati i dati per il tipo documento richiesto. *
FVX59 - restituito nel caso siano presenti 2 FVOE appartenente allo stesso OE (uso Interno per gestione anomalia SW non più presente)
FVC01 - restituito nel caso in cui nel servizio /verifica-stato-richiesta-documento non sia presente nessuna richiesta interna verso gli enti esterni
FVC02 - restituito nel caso in cui nel servizio /verifica-stato-richiesta-documento non sia presente nessuna richiesta utente verso gli enti esterni

*Per la lista dei tipi documento richiedibili si rimanda alla documentazione

https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md

Restiamo a dispisizione per eventuali chiarimenti.

Cordiali Saluti
