### ISSUE TITLE
Ref: [FVOE] ricerca-documenti-fvoe errore FVX03

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1511]
In riferimento alla issue https://github.com/anticorruzione/npa/issues/1496 riportiamo la risposta ricevuta:

"**_Buongiorno, il problema è stato individuato e sarà fixato entro domani 14/06. Ala rilascio della soluzione si procederà alla chiusura della issue. Sarà necessario ripetere la richiesta di accesso al fascicolo._**"

Oggi 18/06/2024 abbiamo effettuato una richiesta di accesso al fascicolo per lo stesso idAppalto ef9f8f80-a5a8-446f-9ad0-528e6e3a01c7, per il cf operatore 11111111113, ottenendo la chiave d'accesso 0a4f6c52-7582-4f9a-9c4a-e0d3b995f640.

Poi abbiamo richiamato l'api ricerca-documenti-fvoe utilizzando la chiave d'accesso in questione ma otteniamo sempre lo stesso errore

status: 404,
title: 'Dato non trovato',
errori: [ { id: 'errori', codice: 'FVX03' } ]

govway-message-id: 3ae5c648-f2a9-41d0-bb5b-683ffa4c10c9
govway-transaction-id: d5436af5-2d55-11ef-bd08-0050568e9679

Il problema è stato fixato? Dobbiamo aspettare il rilascio della soluzione? Se si, quando sarà effettuato il rilascio di questo fix?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>La propagazione dei documenti del FVOE verso il Fascicolo autorizzato avviene durante il cambio di stato.</p>

<p>La chiave accesso é associato a un Fascicolo già autorizzato con la richiesta eseguita in data 18/06/2024. Le richieste di accesso successive non cambiando lo stato non attivano la propagazione</p>

<p>Necessario inviare un nuovo appalto e su questo chiedere l'accesso per l'OE con il CF 11111111113 o 11111111114.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
