### ISSUE TITLE
[FVOE]- RIchiedi Documenti - Chiarimento campo LinguaTedesca

### ISSUE THREAD

**Issue by LuigiScortichino** [anticorruzione/npa#1512]
Buongiorno,
vi contattiamo per una richiesta di chiarimento in relazione al nuovo endpoint /richiedi-documenti in ambiente di qualificazione 
(https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti)
 
In particolare nell'invio di una richiesta di tipo **DatiSA_00004** e di tipo **DatiSA_00020** si richiede un chiarimento sul campo **LinguaTedesca** (da impostare a true) in quanto notiamo incongruenza tra etichetta e descrizione del campo.
 
Grazie mille

**Comment by obigno77** [comment]
Il campo va impostato a true per ottenere la risposta in lingua tedesca e a false per la risposta in lingua italiana.
Verifichiamo la descrizione
