### ISSUE TITLE
[Toscana/Bolzano] Rettifica avviso shcede P2_x P7_1_x - non viene restituito idAvviso di rettifica ( idNuovoAvviso )

### ISSUE THREAD

**Issue by DiMiloMichele** [anticorruzione/npa#1514]
Buongiorno
per le operazioni di **rettifica avviso** schede P2_x, P7_1_x
nel messaggio di esito_operazione non viene restituito idNuovoAvviso

{
  "instance": null,
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "24e77e78-4a65-4d2f-822b-a5ff6699123b",
      "idPianificazione": null,
      "idScheda": "f34579d6-bae1-46c2-9657-8e9a6eed2980",
      "idNuovaScheda": null,
      "idAvviso": "cd1aff04-58b0-4426-aa24-848afea0b2de",
      "idNuovoAvviso": null,
      "idContratto": null,
      "esito": {
        "idTipologica": "esito",
        "codice": "OK"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AV_RETT"
      },
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AV_RETT"
      },
      "dataControllo": "2024-06-12T14:24:29.127+00:00",
      "errori": null
    }
  ]
}

non avendo il nuovo idAvviso, la successiva rettifica va in ERR50

stiamo aprendo segnalazioni al supporto per farci restituire l'ultimo idAvviso pubblicato
esempio: [START] TKT-59567- ERR50  - 019715/2024

Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,<br>
<br>
da controllii effettuati sui nostri sistemi, risulta un primo esito di rettifica avviso andato a buon fine e correttamente compilato con idNuovoAvviso,<br>
<br>
di seguito riporto l'id in questione: UUID('0775b56a-3686-4f00-9eb3-7193ea422c91').<br>
<br>
<br>
Restiamo disponibili per ulteriori chiarimenti.</p>

<p><br>
<br>
Cordiali saluti</p>
