### ISSUE TITLE
[Consip] - "ERR9999": scheda CM2 - errore su CONFERMA-SCHEDA

### ISSUE THREAD

**Issue by carcesa** [anticorruzione/npa#1515]
Salve,
si richiede verifica lato ANAC sul codice di errore ERR9999 restituito sulla scheda CM2.
Di seguito riporto i dati per le opportune verifiche del caso:
GovWay-Message-ID:"2b6fc6a0-ff72-4201-95e4-66d6dcea54c5"  
GovWay-Transaction-ID:"a1d832d1-2e4b-11ef-bd08-0050568e9679"

"{"status":400,"title":"KO","detail":"SC_N_CONF","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}"

Riporto di seguito payload di input:
payload:
{
  "status": 200,
  "title": "OK",
  "detail": "Operazione eseguita con successo",
  "type": "about:blank",
  "scheda": {
    "_idScheda": "5218834a-0a14-4b3f-a054-14a4c61f8f70",
    "stato": {
      "idTipologica": "statoScheda",
      "codice": "IN_LAV"
    },
    "codice": {
      "idTipologica": "codiceScheda",
      "codice": "CM2"
    },
    "versione": "1.0",
    "dataModifica": "2024-06-19T17:15:40.268+00:00",
    "body": {
      "type": "SchedaCM2Type",
      "anacForm": {
        "cig": "I0066E9401",
        "comunicazione": {
          "motivoRichiestaModifica": {
            "idTipologica": "motivoRichiestaModifica",
            "codice": "1"
          },
          "importo": 1.0
        }
      }
    }
  }

**Comment by lauralu1993** [comment]
abbiamo appurato che l'errore si riscontra quando nell'AD5 vengono inviate piu "Aggiudicazioni". potete verificare?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>a seguito di vari tentantivi, e varie fix rilasciate, risulta che la scheda CM2, con idScheda: "bf8467b4-718a-4369-8dda-672d63524ec5", sia stata correttamente confermata in data 2024-09-10.</p>

<p>Restiamo a disposizione.<br>
<br>
Cordiali saluti<br>
<br>
 </p>

<p> </p>

<p> </p>
