### ISSUE TITLE
[eForms - scheda di aggiudicazione] Termini nazionali discordanti da normativa UE rendono quasi impossibile la pubblicazione entro i termini

### ISSUE THREAD

**Issue by GGr8l** [anticorruzione/npa#1516]
Buongiorno,

i termini per la pubblicazione della scheda di aggiudicazione (che deve partire assieme a relativo eForm) non concordano con i termini dell'eForm:
- sono troppo stringenti
- non considerano il fatto che la SA deve aver stipulato il contratto e che la SA debba inserire relative informazioni nell'eForm. --> per cui è impossibile che la SA firmi il contratto con l'OE entro 30 gg dall'aggiudicazione e faccia pure scheda + eForm

Si chiede gentilmente come si intende procedere per fare in modo che le SA rispettino il vincolo nazionale troppo stingente e si chiede revisione di quanto comunicato a livello nazionale in modo da aderire a normativa UE (art. 11 Cost.).

Grazie.

Ecco degli estratti:
1.  FONTE: FAQ ANAC https://www.anticorruzione.it/-/obblighi-informativi-verso-l-autorit%C3%A0

> B1. Qual è la data da cui far decorrere il termine di 30 giorni per l'invio della scheda di aggiudicazione?
> Il termine di 30 giorni di cui sopra deve decorrere dalla data desumibile dal provvedimento amministrativo che accerta l’intervenuta efficacia dell’aggiudicazione, a seguito dell’esito positivo della verifica del possesso dei prescritti requisiti di legge da parte dell’offerente.
> 
> Nel caso di procedure negoziate, per le quali non risultino agevolmente individuabili i provvedimenti amministrativi predetti, per l’individuazione della data di decorrenza occorre riferirsi al primo atto utile con il quale la stazione appaltante manifesta all’appaltatore la volontà di accettare l’offerta, ovvero di affidare l’appalto.

2. FONTE: direttiva UE 2014/24/UE
Articolo 50 "Avvisi relativi agli appalti aggiudicati", c.1

> Entro trenta giorni dalla conclusione di un contratto o di 
> un accordo quadro che faccia seguito alla relativa decisione di 
> aggiudicazione o di conclusione, le amministrazioni aggiudicatrici inviano un avviso di aggiudicazione che riporta i risultati 
> della procedura di aggiudicazione di appalto.
>

**Comment by FabioCassanelli** [comment]
Ci sono aggiornamenti su quanto richiesto?

**Comment by obigno77** [comment]
Corretto. L'avviso di aggiudicazione soprasoglia deve essere inviato a valle della stipula del contratto (contract conclusion di enotices2)
