### ISSUE TITLE
MEPA [Problemi con invio scheda RSU1]

### ISSUE THREAD

**Issue by alberto-purpi** [anticorruzione/npa#1517]
E' stata compilata e inviata la scheda I1 e successivamente volevo compilare la scheda in oggetto ma non mi da la possibilità della trasmissione dopo che ho messo la spunta su MEPA pronta alla trasmissione. Ho cancellato e rifatto la scheda ma rimane la stessa problematica nelle schede fornite ho compilato i campi obbligatori unico dubbio che mi viene quando chiedete Codici fiscali operatori economici se è da indicare solo il subappaltatore o anche quello dell'aggiudicatario?

Grazie

**Comment by obigno77** [comment]
Questo supporto è dedicato alle piattaforme in sede di certificazione. Si prega di rivolgersi a MEPA per la verifica dell'anomalia
