### ISSUE TITLE
Invio scheda A1_29 con eform errato

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1518]
Come da titolo, abbiamo inviato una scheda A1_29 per l'aggiudicazione di un lotto inserendo erroneamente un eForm già utilizzato.
Le api di creazione scheda e di conferma inizialmente ci hanno risposto correttamente. 

"govwayMessageId": "9a665c15-d69f-43c3-85df-2ad9f27841d8",
"govwayTransactionId": "f9ff6f61-2ee5-11ef-bd08-0050568e9679",
"ID_APPALTO": "e93f71d6-a343-41a9-8136-e5ba96ebd3ad",
"ENDPOINT": "https://apigw-test.anticorruzione.it/modi/rest/ComunicaPostPubblicazione/v2/crea-scheda"

"govwayMessageId": "d3a91ac2-b05b-4829-a799-03be20460263",
"govwayTransactionId": "0c1a990f-2ee6-11ef-8dc0-0050568e08b3",
"ID_APPALTO": "e93f71d6-a343-41a9-8136-e5ba96ebd3ad",
"ENDPOINT": "https://apigw-test.anticorruzione.it/modi/rest/ComunicaPostPubblicazione/v2/conferma-scheda"

Successivamente, richiamando esito operazione abbiamo ottenuto l'errore 

"errori": [
              {
                "idTipologica": "errori",
                "dettaglio": {
                  "code": "notice.NOTICE_IMPORT_VALUE_EXCEPTION",
                  "message": "Anoticewiththesameidandversionidalreadyexists.",
                  "showDetails": true
                },
                "codice": "ERR64"
              }

con il dettaglio della scheda non confermata

"dettaglio": {
              "idTipologica": "esitoOperazione",
              "codice": "SC_N_CONF"
            },

"govwayMessageId": "2f949801-965c-4c33-8fc9-091c3b137194",
"govwayTransactionId": "1438ff69-2ee6-11ef-8dc0-0050568e08b3",
"ID_APPALTO": "e93f71d6-a343-41a9-8136-e5ba96ebd3ad",
"ENDPOINT": "https://apigw-test.anticorruzione.it/modi/rest/ServiziComuni/v2/esito-operazione?idAppalto=e93f71d6-a343-41a9-8136-e5ba96ebd3ad&tipoRicerca=TUTTI_ESITI&tipoOperazione=SC_CONF"

A questo punto abbiamo tentato di modificare la scheda per poterla inviare correttamente ma abbiamo ottenuto il seguente errore

        "errori": [
          {
            "idTipologica": "errori",
            "codice": "ERR58"
          }
        ]
      },
"HTTPSTATUS": 400,
"govwayMessageId": "52adaa50-9dbb-485e-9f25-c4186ac25837",
"govwayTransactionId": "35135574-2ee6-11ef-8dc0-0050568e08b3",
"ID_APPALTO": "e93f71d6-a343-41a9-8136-e5ba96ebd3ad",
"ENDPOINT": "https://apigw-test.anticorruzione.it/modi/rest/ComunicaPostPubblicazione/v2/modifica-scheda"

Nonostante esito operazione ci risponda con "Scheda non confermata" lo stato della scheda rimane CONFERMATO.
Abbiamo tentato anche una cancellazione ma il risultato è identico alla modifica.

Quali sono le operazioni da eseguire in questo caso?
Come possiamo inviare di nuovo la scheda di aggiudicazione?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>l'anomalia è stata risolta riportando lo stato della scheda in lavorazione.</p>

<p>La invitiamo pertanto a modificare tale scheda</p>

<p>    - idScheda: 0411b12a-1fba-4042-8e23-4a687f8c1b31</p>

<p>e successivamente a procedere con la conferma della stessa, oppure alla sua cancellazione.</p>

<p>Restiamo a disposizione.</p>

<p>Cordiali saluti</p>
