### ISSUE TITLE
[CONSIP] ERR 4 invio ES1

### ISSUE THREAD

**Issue by LorenzograzianiLDO** [anticorruzione/npa#1519]
Inviando una scheda ES1 con il seguente body:

{"dataAutorizzazione":"2024-05-20T00:00:00Z","idScheda":"3352c10d-8c06-449f-aa4e-cbab8f577c6c"}

riceviamo un risposta un ERR4 con descrizione:

{"idTipologica":"errori","dettaglio":"$.anacForm.subappalto.motivoMancatoSubappalto.codice: is missing but it is required","codice":"ERR4"},{"idTipologica":"errori","dettaglio":"$.anacForm.subappalto.motivoMancatoSubappalto.idTipologica: is missing but it is required","codice":"ERR4"}]}

Tuttavia, controllando lo swagger i campi:
idTipologica motivoMancatoSubbappalto
Codice motivoMancatoSubbappalto
non sono obbligatori.
idAppalto: c64b48f0-aceb-4787-9ff9-065d9e1d438f
CIG: I004F55EED
__

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>controllando lo swagger per il tipo scheda ES1 abbiamo verificato che il campo da lei citato è effettivamente obbligatorio.</p>

<p>Rimaniamo a disposizione per ulteriori chiarimenti</p>
