### ISSUE TITLE
Piattaforma di test

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#152]
Leggendo l'issue https://github.com/anticorruzione/npa/issues/144 mi sembra di capire ci sia un servizio di test che si può iniziare ad interrogare.
Il servizio è già disponibile a tutti o è riservato ad una sorta di beta per determinati client?
Nel caso sia per ora riservato, quale sarà il canale scelto per pubblicare la release della piattaforma di test e delle sue linee guida? (endpoint, utenze per l'auth ecc)
Verrà aggiornato il readme di questa repo o verrà creato un annuncio su qualche sito?

**Comment by supportoAnac** [comment]
Il servizio è disponibile a tutti i soggetti che possono accedere tramite PDND, abilitati secondo la normativa AgID.
