### ISSUE TITLE
[Teamsystem] - Scheda CM1 - Definizione schede per inviare la comunicazione di modifica

### ISSUE THREAD

**Issue by mcgirone** [anticorruzione/npa#1523]
Buongiorno,

da orchestratore abbiamo verificato che la scheda CM1 può essere inviata solo per le schede AD4.
Per quanto riguarda le schede AD3, A3_6 e AD2_25, quale scheda dovremmo inviare per la modifica?

Grazie

**Comment by anac-uscp** [comment]
<ul>
	<li style="list-style-type:none;">La CM1 è prevista per le modifiche ai dati delle schede di seguito riportate:
	<ul style="list-style-type:circle;">
		<li style="margin-left:16px;"><span style="font-size:12pt;"><span style="background-color:white;"><span style="line-height:normal;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style='font-family:"Arial",sans-serif;'><span style="color:black;">P5 (appalti soggetti a sola tracciabilità)</span></span></span></span></span></span></span></li>
		<li style="margin-left:16px;"><span style="font-size:12pt;"><span style="background-color:white;"><span style="line-height:normal;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style='font-family:"Arial",sans-serif;'><span style="color:black;">AD4 (Adesione ad accordo quadro/convenzione senza successivo confronto competitivo),</span></span></span></span></span></span></span></li>
		<li style="margin-left:16px;"><span style="font-size:12pt;"><span style="background-color:white;"><span style="line-height:normal;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style='font-family:"Arial",sans-serif;'><span style="color:black;">P3_1, P3_2, P3_3 (Contratti Esclusi)</span></span></span></span></span></span></span></li>
		<li style="margin-left:16px;"><span style="font-size:12pt;"><span style="background-color:white;"><span style="line-height:normal;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style='font-family:"Arial",sans-serif;'><span style="color:black;">P6_1, P6_2 (adesione AQ/convenzione con successivo confronto competitivo)</span></span></span></span></span></span></span></li>
		<li style="margin-left:16px;margin-bottom:11px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style="line-height:115%;"><span style='font-family:"Arial",sans-serif;'><span style="color:black;">AD5 (CM2)</span></span></span></span></span></span></span></li>
	</ul>
	</li>
</ul>

<p style="margin-bottom:11px;margin-left:16px;">Per quanto riguarda le schede A3_6 e AD2_25 ed in generale  per le procedure che hanno pubblicità a valore legale, semza invio al TED, n<span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">on è possibile annullare o  modificarne i dati poiché la pubblicazione nazionale (PVL) è contestuale all’invio della scheda.</span></span></span></p>

<p style="margin-bottom:11px;margin-left:16px;"><span style="font-size:12pt;"><span style="line-height:115%;"><span style="font-family:Aptos,sans-serif;">Idem per le procedure che prevedono pubblicità a valore legale ma non sono procedure ad evidenza pubblica (scheda AD3).</span></span></span></p>

<p style="margin-bottom:11px;margin-left:16px;"><br>
 </p>
