### ISSUE TITLE
[CONSIP - FVOE] -  DatiSA_00050 per il tipo documento COMUNICAZIONE ANTIMAFIA  - DataNascita_Soggetto mai accettata

### ISSUE THREAD

**Issue by LuigiScortichino** [anticorruzione/npa#1524]
buon pomeriggio,

in ambiente di qualificazione (https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti) 
nell'invio di una richiesta di tipo DatiSA_00050 per il tipo documento
**COMUNICAZIONE ANTIMAFIA** quando viene valorizzato 
"DataNascita_Soggetto":"1980-02-01T00:00:00+01:00"
riceviamo sempre l'errore
{
	"detail": "Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module \"com.fasterxml.jackson.datatype:jackson-datatype-jsr310\" to enable handling (through reference chain: it.anticorruzione.ms.fvc.fvcms.dto.dati_sa_documento.DatiSA00050[\"soggetto_da_verificare\"]->java.util.ArrayList[0]->it.anticorruzione.ms.fvc.fvcms.dto.dati_sa_documento.Soggetto00050[\"DataNascita_Soggetto\"])",
	"status": 500,
	"title": "Operazione terminata con errore",
	"errori": [
		{
			"id": "errori",
			"codice": "ERR9999"
		}
	]
}
**La situazione è BLOCCANTE** e non ci consente di procedere! Vi prego di darci indicazioni o suggerimenti nel caso effettuassimo operazioni non corrette.

Vi saluto in attesa di un vostro riscontro.

Di seguito alcune coordinate di invio fallite:  
GovWay-Message-ID: 6d33006e-609e-4619-b525-65c2ed110875
GovWay-Transaction-ID: c1406d73-2f0d-11ef-8dc0-0050568e08b3

GovWay-Message-ID: 248e479b-641e-4399-a35c-180aae7bb7f6
GovWay-Transaction-ID: b6fb17a5-31e7-11ef-8dc0-0050568e08b3

GovWay-Message-ID: fff95519-97a0-49ad-9011-18d70b588d8a
GovWay-Transaction-ID: 5d8c7ff1-31e7-11ef-8dc0-0050568e08b3

GovWay-Message-ID: d498c0ce-4a72-4d88-ac2f-c5e238bbdc3a
GovWay-Transaction-ID: ee1c1952-31e7-11ef-bd08-0050568e9679

**Comment by masko82** [comment]
Ci accodiamo alla issue per avere aggiornamenti sulle possibili risoluzioni

**Comment by stalex1** [comment]
Gentile Utente,

Alla data del 24/06, data in cui è stato aperto il TT su github, era  presente un'anomalia legata all'assenza della libreria di java che permetteva la trascodifica dell'OffsetDateTime in ingresso.

La nuova versione SW che risolve l'anomalia è stata pubblicata in ambiente di qualificazione l'08/07/2024.

Restiamo a disposizione,

Cordiali Saluti
