### ISSUE TITLE
[Consip] P1_10 - l'avviso resta IN_ATT_PUBB dopo modifica-avviso 

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1525]
salve, 
abbiamo ricreato uno scenario di pubblicazione non andata a buon fine per testare il modifica-avviso.
tuttavia, lo stato dell'avviso resta IN_ATT_PUBB senza mai transitare in pubblicato. 
Potete verificare?
govway message= [ebca7636-db72-4503-bf75-10b306f6084f]
govway transaction= [e536417b-322d-11ef-bd08-0050568e9679]

ESITO-OPERAZIONE
{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "6db7864d-0ab1-46ea-964c-ad75635b450a",
      "idScheda": "1746acea-0baf-4f0d-8c1c-1618d9f0eb92",
      "codiceScheda": "P1_10",
      "idAvviso": "1ec770ff-b0eb-414a-bfb8-a15637d26f9a",
      "esito": {
        "idTipologica": "esito",
        "codice": "OK"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AV_PUBB"
      },
      "dataControllo": "2024-06-17T12:15:55.688+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AV_MOD"
      }
    },
    {
      "idAppalto": "6db7864d-0ab1-46ea-964c-ad75635b450a",
      "idScheda": "b41dbf21-e533-4ea7-9892-f3fb2bcdd89d",
      "codiceScheda": "P1_10",
      "idAvviso": "35f58f17-bb5e-4757-924d-1499e77d205a",
      "esito": {
        "idTipologica": "esito",
        "codice": "OK"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AV_PUBB"
      },
      "dataControllo": "2024-06-17T12:15:55.660+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AV_IN_PUBB"
      }
    },
    {
      "idAppalto": "6db7864d-0ab1-46ea-964c-ad75635b450a",
      "idScheda": "1746acea-0baf-4f0d-8c1c-1618d9f0eb92",
      "codiceScheda": "P1_10",
      "idAvviso": "1ec770ff-b0eb-414a-bfb8-a15637d26f9a",
      "esito": {
        "idTipologica": "esito",
        "codice": "KO"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AV_PUBB"
      },
      "dataControllo": "2024-06-17T12:02:35.186+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AV_N_PUBB"
      },
      "errori": [
        {
          "idTipologica": "errori",
          "dettaglio": "\n\t\tNotice Dispatch Date must be between 0 and 24 hours before the current date.\n\t",
          "codice": "ERR46"
        }
      ]
    }
  ]
}

**Comment by pg-volpentesta** [comment]
per favore ci fornite un aggiornamento sul tema?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Da un controllo sui nostri sistemi l'azione di modifica (primo esito) è andata a buon fine, tuttavia controllando sul TED l'avviso non è mai stato pubblicato, il problema però non dipende dal servizio di PCP ma da ragioni esterne del TED.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
