### ISSUE TITLE
Nuova API richiedi-documenti (POST) documentazione swagger non aggiornata

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1526]
Dopo  aver scoperto che "La nuova operazione /richiedi-documenti è utilizzabile in ambiente di qualificazione a partire dal 6 giugno" abbiamo iniziato le implementazioni del servizio in questione... purtroppo con pochi risultati positivi.

I problemi principali sono i seguenti
- nella documentazione swagger manca la specifica di un campo FONDAMENTALE che definisce il tipo dell'oggetto "datiRichiesta"
- per il tipo DatiSA_0004, nell'oggetto "AltriDati" vi è un campo "LinguaTedesca" con una descrizione parecchio ambigua 
![image](https://github.com/anticorruzione/npa/assets/8038758/acbdcfea-d74c-4db9-8368-c204ca13e25e)
- Ambiguità all'interno della tipologica tipoDocumento (es: per i codici 00038 e 00040 quale dei due è quello valido? Entrambi hanno data fine a null)
- La lista dei tipi documento è ben più lunga dei possibili "datiRichiesta" associabili. Esiste un mapping ben preciso che possa fare chiarezza?
- In generale c'è poca chiarezza su come utilizzare il modello per le richieste dei documenti

In ogni caso "AD INTUITO" (e non grazie alla documentazione) siamo riusciti a creare una richiesta ottenendo l'idRichiesta 8cc18b97-ce1b-4947-acdd-a0afb2abaaed
Ad ogni modo si brancola nel buio e sarebbe utile avere più chiarezza per poter offrire alle stazioni appaltanti dei servizi funzionanti al 100%

PS: il vecchio servizio GET  "richiedi-documento" quando verrà dismesso? Ci sarà un periodo di convivenza dei due servizi?

**Comment by anac-uscp** [comment]
<p>Gentile Utente,<br>
<br>
1) la documentazione è presente su questo url: https://github.com/anticorruzione/npa/blob/main/CHANGELOG.md#modello-dati-8  " note di rilascio 05/04/2024",<br>
<br>
nel documento principale è stato aggiunto il paragrafo (11.3) : https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md#113tipi-documento-richiedibili-agli-enti-certificanti<br>
<br>
che riporta ad una pagina specifica che dettaglia la mappatura del tipo documento richiedibile, quale modello dati valorizzare.  <br>
<br>
https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md .<br>
<br>
<br>
2) Per identificare il modello dati da passare è necessario valorizzare l'attributo "Type" (segnato in grassetto senza " Underscore _ " ).   <br>
<br>
Scenario di esempio: <br>
<br>
{<br>
  "chiaveAccesso": "f209a5fc-99f0-4764-98ae-464f8cd7596a",<br>
  "tipoDocumento": {<br>
    "codice": "00005"<br>
  },<br>
  <strong>"type": "DatiSA00020", </strong><br>
  "datiRichiesta": {<br>
    "DatiNominativo": {<br>
      "DenominazioneSociale": "Fuoco &amp; C",<br>
      "CodiceFormaGiuridica": "AG",<br>
      "PIVA": "22222222222",<br>
      "DatiSedeSociale": {<br>
        "Indirizzo": "Via del Fuoco",<br>
        "CodiceCatastoStato": "Z200"<br>
      }<br>
    },<br>
    "AltriDati": {<br>
      "LinguaTedesca": false<br>
    }<br>
  }<br>
}<br>
<br>
3) AtriDati.LinguaTedesca indica la lingua con cui produrre il documento.<br>
<br>
E' previsto in futuro l'aggiornamento della documentazione con gli scenari d'esempio, data da definire. <br>
la dismissione del vecchio servizio sarà comunicato sul sito github di ANAC.  <br>
<br>
Restiamo a disposizione.<br>
<br>
Cordiali Saluti</p>
