### ISSUE TITLE
Censimento nuovo Centro di costo in ambiente qualificazione e relative utenze

### ISSUE THREAD

**Issue by collaudo5** [anticorruzione/npa#1529]
Per poter eseguire i test di UAT con un nostro cliente avremo bisogno che venisse censito un nuovo CDC legato ad una SA già presente a sistema in ambiente di qualifica PCP.

Tale richiesta nasce dall'esigenza del cliente di verificare che gli use-case di Presa carico tra gli utenti della medesima SA , ma differente CDC, vadano a buon fine permettendo la gestione degli appalti ad autenti dislocati su più centri di costo all'interno della medesima organizzazione.

Riporto a seguire i dati della SA già a nostra disposizione a cui associare il nuovo CDC:

SA -->  IPSV
CF -->  01716880214
Codice AUSA --> 9100000003

Grazie.

**Comment by obigno77** [comment]
Si prega di inviare la richiesta via mail a ufficio.uscp@anticorruzione.it
