### ISSUE TITLE
Consultazione Appalto in fasi diverse

### ISSUE THREAD

**Issue by sfala** [anticorruzione/npa#153]
Devo certificare un componente che copre la fase di ESECUZIONE del ciclo di vita dell'appalto e avendo esigenza di recuperare i dettagli dell'appalto inviati nella fasi precedenti (esempio AFFIDAMENTO), vorremmo sapere se è possibile utilizzare (in funzione dei dati da recuperare) indifferentemente i servizi del Modulo NPA o i servizi Modulo FVA. E' sempre possibile utilizzare i servizi di entrambe i moduli? Oppure trattandosisi di fasi differenti dobbiamo considerare preferibile/possibile usare solo un set e se sì quale?

**Comment by supportoAnac** [comment]
I servizi FVA sono utilizzabili da qualunque modulo, ma a nostro avviso non sono sufficIenti ad avere informazioni complete sull'appalto in fase di esecuzione. ANAC non gestisce e non disciplina l'interoperabilità tra piattaforme che gestiscono fasi diverse dell'appalto.
