### ISSUE TITLE
campo Importo in caso di RTI

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1532]
Buongiorno,

per le schede AD e A, in caso di RTI il campo per indicare l'importo di aggiudicazione va indicato per tutti i componenti della RTI con il valore dell'aggiudicazione (uguale per tutti)? o l'importo di aggiudicazione deve essere scomposto fra i membri del raggruppamento?

Nell'ambiente di collaudo non abbiamo individuato vincoli nella compilazione (il sistema accetta entrambe le tipologie di compilazione), ci chiedevamo se in ambiente di produzione ci siano dei vincoli e come ci si aspetti di ricevere il dato lato vostro.

grazie

**Comment by paolo-urbanetto** [comment]
Ci associamo anche noi [Maggioli] al quesito.

**Comment by obigno77** [comment]
Stesso importo (totale) per tutti i membri del raggruppamento
