### ISSUE TITLE
[Toscana/Bolzano] - Indisponibilità momentanea

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1534]
Salve,

Volevamo segnalare che qualsiasi chiamata effettuiamo, riceviamo il seguente errore:
{
   "type": "[https://govway.org/handling-errors/503/APIUnavailable.html"](https://govway.org/handling-errors/503/APIUnavailable.html%22),
   "title": "APIUnavailable",
   "status": 503,
   "detail": "The API Implementation is temporary unavailable",
   "cart_id": "9b7ebf0f-33a5-11ef-a308-005056865883"
}

Potreste verificare?

**Comment by obigno77** [comment]
Nelle ultime 24 ore non tracciamo nessun errore 503 in nessuno dei tre ambienti
