### ISSUE TITLE
affidamenti diretti in accordo quadro

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1535]
Buongiorno,

come possono procedere gli utenti per svolgere in accordo quadro in affidamento diretto?

si attenziona che il comunicato ANAC del 05706/2024 riporta: 
"Ai fini dell’acquisizione del CIG e di trasmissione dei dati concernenti affidamenti diretti di Accordi Quadro di importo complessivo inferiore a 150.000 (per i lavori) e a 140.000 (per i servizi e le forniture), potrà essere compilata la scheda AD3 (Affidamento diretto) dove – nelle more dell’introduzione di un flag specifico – può essere valorizzato il campo generale attualmente esistente “strumenti per lo svolgimento della procedura” inserendo l’espressa indicazione“ Accordo Quadro”. Per quanto concerne i successivi contratti applicativi a valle dell’accordo quadro dovrà essere compilata la scheda AD4 (Adesione senza confronto competitivo settori ordinari e speciali)."

Consultando tuttavia i campi della scheda AD3 il campo "strumenti per lo svolgimento della procedura" non risulta presente.

**Comment by obigno77** [comment]
Con Comunicato del Presidente del 10 luglio 2024 l’ANAC ha preannunciato la prossima modifica della richiamata scheda AD3 ai fini dell’acquisizione del CIG e della trasmissione dei dati concernenti affidamenti diretti di Accordi Quadro. 
Nel medesimo comunicato l’Autorità ha indicato - in via transitoria - le schede attualmente trasmissibili per la medesima finalità ossia la scheda AD2_25 per i settori ordinari, la scheda AD2_26 per i settori speciali e AD2_27 per difesa e sicurezza. Per quanto concerne i successivi contratti applicativi a valle dell’accordo quadro dovrà essere compilata la scheda AD4 (Adesione senza confronto competitivo). 
Anche per l’affidamento diretto degli accordi quadro - da comunicare in futuro attraverso la medesima scheda AD3 - valgono ovviamente le modifiche di cui sopra, cui ANAC sta lavorando ai fini della semplificazione, accesso al FVOE per le verifiche da parte delle stazioni appaltanti  e riduzione dei tempi per pervenire all’affidamento.
