### ISSUE TITLE
[CONSIP] P1_20 - ERR50 su modifica-avviso

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1536]
salve, 
a seguito di un errore in fase di pubblicazione abbiamo chiamato il servizio **modifica-avviso** ma otteniamo l'errore:
{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR50"}]}" 

potete verificare? 

GovWay-Message-ID=[c237243b-9aa2-4569-bef5-136d924a7050]
GovWay-Transaction-ID=[4b22a420-33a0-11ef-bd08-0050568e9679], 
idAppalto":"2ccd9d22-e544-4a1d-9aa7-fbf4f688fc3d"

**Comment by anac-uscp** [comment]
<p>Gentile Utente,</p>

<p>L'errore che si sta ottenendo sul modfica avviso è l'errore 4 e segnala l'assenza dell'ESPD obbligatorio.</p>

<p>La invitiamo ad inserire ESPD e a riprovare.</p>

<p> </p>

<p>Restiamo a disposizione.</p>

<p> </p>

<p>Cordiali Saluti</p>
