### ISSUE TITLE
[Toscana/Bolzano] - Trasmissione OE in caso di raggruppamenti RTI nelle schede "Aggiudicazioni"

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1537]
Buon pomeriggio,

Ci confermate che nel caso di raggruppamento di operatori economici (OE) per una procedura di gara, i membri del raggruppamento vengono trasmessi nelle schede S2 con lo stesso ID partecipante, il quale identifica il raggruppamento come un'entità unica durante la fase di gara ?

Invece per le schede di Aggiudicazione, ci confermate che viene trasmesso un solo ID partecipante nelle "offerte presentate" rappresentando l'intero raggruppamento e che quindi, non è necessario trasmettere l'ID partecipante uguale N volte per ciascun membro del raggruppamento ?

Grazie.

**Comment by obigno77** [comment]
Si, la stessa regola va applicata anche nella scheda di aggiudicazione in caso di RTI.

**Comment by LucaMaggioni1** [comment]
Buongiorno,

riprendo la issue perchè non mi è chiara la risposta. nelle schede A, in caso di RTI, non è sufficiente compilare solo le info per uno stesso IDPartecipante?
mi spiego meglio:
nella scheda S2 è cirretto comunicare tutto il raggruppamento per verificare gli OE coinvolti un'offerta e sbloccare anche FVOE.
nella scheda A di aggiudicazione perchè si dovrebbero ricomunicare le info per tutti i membri? non chiedendo più le info rispetto a codice fiscale, denominaione ecc OE ma avendo solo il riferimento a IDPArtecipante come potrebbe ANAC distinguere di quale membro della RTI si stanno comunicando i dati? inoltre, i dati offerte presentate sarebbero uguale per tutto il raggruppamento (importo, aggiudicatario ecc).

Forse ho interpretato male la risposta fornita.

**Comment by obigno77** [comment]
Corretto. E' previsto solo l'idPartecipante
