### ISSUE TITLE
[Consip] - Scheda AD5 - CUP - ERR4- $.anacForm.aggiudicazioni[0].cupLotto[0]: does not match the regex pattern ^[a-zA-Z0-9]{15}$

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1538]
A seguito della trasmissione della scheda AD5 riscontriamo ''ERR4 - $.anacForm.aggiudicazioni[0].cupLotto[0]: does not match the regex pattern ^[a-zA-Z0-9]{15}$''

Riceviamo il messaggio di errore quando proviamo ad inserire un doppio valore all'interno del campo CUP (J82C23000310001, J82C23000320001) ed effettuiamo la trasmissione della scheda.

Per quale motivo prima riuscivamo a trasmettere la scheda con due valori inseriti all'interno del campo CUP lotto (separati dalla virgola) e adesso non è più possibile? 

GovWay-Message-ID=[e9a41239-6ecf-4090-96fd-b9b5ce54562a]
GovWay-Transaction-ID=[6fba86e1-33bf-11ef-bd08-0050568e9679]

Di seguito i log:
2024-06-26 15:48:56,109 ERROR (AbstractAnacUnhandledIntegrationService.java:217) - [[ACTIVE] ExecuteThread: '4' for queue: 'weblogic.kernel.Default (self-tuning)']: RequestBody = {"scheda":{"type":"SchedaComunicaAppaltoType","codice":{"idTipologica":"codiceScheda","codice":"AD5"},"versione":"1.0","body":{"type":"SchedaAD5Type","anacForm":{"stazioniAppaltanti":[{"codiceFiscale":"05359681003","codiceAusa":"9000000008","codiceCentroCosto":"f237c494-bae6-47e4-8c32-f15a5228b948","saTitolare":true}],"appalto":{"codiceAppalto":"CONSIP_RDO_2613986","datiBase":{"oggetto":"Test x Log Issue Anac CUP"}},"aggiudicazioni":[{"lotIdentifier":"LOT-0001","cup":"12345690892, 12345678999","partecipanti":[{"idPartecipante":"ef75471d-5f9c-47ee-be58-8371d9c2b062","codiceFiscale":"BCCBRN98M16H501I","denominazione":"Test","importo":100.0}],"ccnl":"0","categoria":{"idTipologica":"categoria","codice":"999"},"codIstat":{"idTipologica":"codIstat","codice":"999991201"},"datiBase":{"oggettoContratto":{"idTipologica":"oggettoContratto","codice":"works"},"oggetto":"TEST"},"datiBaseCPV":{"tipoClassificazione":{"idTipologica":"tipoClassificazione","codice":"cpv"},"cpvPrevalente":{"idTipologica":"CPV","codice":"15880000"}},"datiBaseDocumenti":{"url":"
[https://pre.acquistinretepa.it/npa/#!/formAnac"}}]}}}}](https://pre.acquistinretepa.it/npa/#!/formAnac%22%7D%7D]%7D%7D%7D%7D)
- requestUrl =
https://apigw-test.anticorruzione.it/modi/rest/ComunicaAppalto/v2/crea-appalto
- headers = {Authorization=[Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L0NvbXVuaWNhQXBwYWx0by92MiIsInN1YiI6IjAxZTJlZmM0LWYyY2QtNDBmNC1iYWMxLTA1ZTdjNmRjZWZiYSIsIm5iZiI6MTcxOTQwOTczNSwiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiZmZkODcwNjJhNzE5OGVjMGY0MjM4MWI5ZjNlMmM5Y2JhYzk2NTgxZDg0NGM2YjYwZDQ0ZGUwNjc1OGFmYzk3ZSJ9LCJwdXJwb3NlSWQiOiI2MjE4MzhlMy1lNmRlLTQzZDItYmQ4OC0xYTBlYjBmOTM5ZDQiLCJpc3MiOiJ1YXQuaW50ZXJvcC5wYWdvcGEuaXQiLCJleHAiOjE3MTk0MTMzMzUsImlhdCI6MTcxOTQwOTczNSwiY2xpZW50X2lkIjoiMDFlMmVmYzQtZjJjZC00MGY0LWJhYzEtMDVlN2M2ZGNlZmJhIiwianRpIjoiZTlhNDEyMzktNmVjZi00MDkwLTk2ZmQtYjliNWNlNTQ1NjJhIn0.iSbxK6kXb2mIZhf255RGs64NyTOqnTRNNK5sBIqyFPjfxLGE3faZIiiF9NivPdsCSji-ND16T6P_kOemXuo1Fh9oU4rnUrU76mdGHltlOrwoeCBXfwm1Ze3bXleDEwvJNLhHkGqqRXE_A4jT7pLNcct2SqMW8dbPTeI0dYuAGs1XSKHErvGGKgHPOtUDYPZPoEgq19HuM9kiNltUq2YdqRzxNsCEECtNKPRepAFCrkSYOgKyrRveO5hxuVk-fOxv8v9tme6tFURIvvGCMKniqzYWGJfBHpARHjQFv58v8WRtsPcPPDaVITjKRVi8zbkakbV8E-ylv5oXxG0qAPl10A], Agid-JWT-TrackingEvidence=[eyJraWQiOiJvbjJVTmFCbGxQSlhaZDV4amdPMXoxV2QyeFVRYUItRHFtRFhaZEFiUlRBIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJqdGkiOiJkNzdhYTIyNC1iZDg1LTQwMDgtYjFjOC01YTU0ZjFiNzc1OGUiLCJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L0NvbXVuaWNhQXBwYWx0by92MiIsInVzZXJDb2RpY2VGaXNjYWxlIjoiTVJUQ0xEOTZCNTJCNjk2RiIsInVzZXJSb2xlIjoiUlAiLCJ1c2VyTG9hIjoiMyIsInVzZXJJZHBUeXBlIjoiU1BJRCIsIlNBQ29kaWNlRmlzY2FsZSI6IjA1MzU5NjgxMDAzIiwiU0Fjb2RpY2VBVVNBIjoiOTAwMDAwMDAwOCIsInJlZ0NvZGljZVBpYXR0YWZvcm1hIjoiMDAwMDAwOSIsInJlZ0NvZGljZUNvbXBvbmVudGUiOiIwMDAwMDEwIiwiYnVzaW5lc3NGbG93SUQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJ0cmFjZUlEIjoiZGZkYzlhYWMtYjZhZi00MzQ3LWJkYzctMmU3OWQ2YTc2M2MwIiwic3BhbklEIjoiZmVhMGY2ODktMmFiNy00MDg0LWI4YjctZGQ0MDRlNjE5ZDAzIiwicHVycG9zZUlkIjoiNjIxODM4ZTMtZTZkZS00M2QyLWJkODgtMWEwZWIwZjkzOWQ0IiwiaWF0IjoxNzE5NDA5NzM1LCJleHAiOjE3MTk0MTMzMzUsIm5iZiI6MTcxOTQwOTczNX0.bifnczHJgbNL7V8qq9c2xerFhJWS4dN__vdoQiFgtuSMAJt4vgc26Lqii3enxh8BKwDUBsSsLD5KCPjzW7IUGYdgmG8ZmGnJtXRM-A8K_ywY_uG-56QNY-kfITENnIew8TMyG5NMxICakrfm84NGAloUR6wFXnXbeiwJJo7P4fUPIhv_5UfztwFsjCerZtRYDdcuH5mfJIECt4VtBordYdHihtVzEIt46HbU4QK9nl2s-T8zlzQNjvZ3fMO7fJYDcFD4k7ZLadTXG-jT-6H3Wmis-asc807BSI1yu39M73neUioyUsTEBRIWRfBS_rGqsjNNogul6Ox0mqVFK8_8Xw], Content-Type=[application/json;charset=UTF-8], } - method = POST - Timestamp=1719409736016 - Taken=93 ms  - Thread=48 - StatusCode =  - 400 - ResponseFoundFromException =  - {"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","dettaglio":"$.anacForm.aggiudicazioni[0].cup: does not match the regex pattern ^[a-zA-Z0-9]{15}$","codice":"ERR4"}]} - ResponseHeaders - {Server=[nginx], Date=[Wed, 26 Jun 2024 13:48:56 GMT], Content-Type=[application/json], Transfer-Encoding=[chunked], Connection=[keep-alive], expires=[0], cache-control=[no-cache, no-store, max-age=0, must-revalidate], x-xss-protection=[1; mode=block], pragma=[no-cache], GovWay-Message-ID=[e9a41239-6ecf-4090-96fd-b9b5ce54562a], x-frame-options=[DENY], GovWay-Transaction-ID=[6fba86e1-33bf-11ef-bd08-0050568e9679], vary=[Access-Control-Request-Headers, Access-Control-Request-Method, Origin], x-content-type-options=[nosniff], strict-transport-security=[max-age=31536000 ; includeSubDomains, max-age=63072000], } - 

org.springframework.web.client.HttpClientErrorException: 400 Bad Request

**Comment by obigno77** [comment]
Non è possibile inserire due CUP. Nel prossimo changelog sarà previsata la possibilità di indicare più di un CUP
