### ISSUE TITLE
Differenze tra Orchestratore, il file codiceScheda.json e la descrizione delle schede nello swagger

### ISSUE THREAD

**Issue by lmanc77** [anticorruzione/npa#154]
abbiamo verificato alcune differenze importanti tra l'Orchestratore, il file codiceScheda.json e la descrizione delle schede nello swagger.
Ad esempio: 
la scheda P4_3:
è presente nello swagger con la seguente descrizione 'Scheda relativa ai contratti di Partenariato Pubblico Privato - Contratto di disponibilità'
NON è presente nello'orchestratore
la scheda P6.1:
nell'orchestratore è indicato come 'PPP - Finanza di progetto'
nello swagger è indicato come 'Scheda relativa alle adesioni AQ/convenzione con successivo confronto competitivo (concessioni)'
la scheda A1_29:
nel file json è indicato come 'Scheda di pubblicazione avviso di aggiudicazione soprasoglia con invio al TED dell'eform 29'
nella descrizione dello swagger la descrizione è la seguente: 'Contiene tutti i dati relativi all'aggiudicazione soprasoglia e sottosoglia con invio al TED - Avviso relativo all’appalto aggiudicato — direttiva generale, regime ordinario. Articolo 50 della direttiva 2014/24/UE'

Si richiede pertanto qual'è il documento a cui far riferimento tra i tre visto che la descrizione dovrà essere riportata nell'applicativo e in base a questa sarà effettuata la scelta dell'utente.

Grazie

**Comment by supportoAnac** [comment]
Il documento a cui fare riferimento è il file Excel "schema-cronologia-schede.xlsx". I refusi negli altri documenti (swagger e file json) verranno corretti col prossimo rilascio, previsto per settembre.
