### ISSUE TITLE
Gestione RTI per schede aggiudicazione

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1541]
Buongiorno,

riprendo la issue #1537  perchè non mi è chiara la risposta. Nelle schede A, in caso di RTI, non è sufficiente compilare solo le info per uno stesso IDPartecipante?
mi spiego meglio:
nella scheda S2 è corretto comunicare tutto il raggruppamento per comunicare gli OE coinvolti in un'offerta e sbloccare anche FVOE.
nella scheda A di aggiudicazione perchè si dovrebbero ricomunicare le info per tutti i membri? non chiedendo più le info rispetto a codice fiscale, denominaione ecc OE ma avendo solo il riferimento a IDPArtecipante, come potrebbe ANAC distinguere di quale membro della RTI si stanno comunicando i dati? inoltre, i dati offerte presentate sarebbero uguali per tutto il raggruppamento (importo, aggiudicatario ecc).

Forse ho interpretato male la risposta fornita a quella issue. Non mi risulta che l'offerta può essere cambiata una volta che sono scaduti i termini (non dovrebbe poter cambiare il raggruppamento quindi perchè far mandare i dati per tutti i membri quando sia ha già l'IDPartecipante che identifica l'offerta?)

**Comment by obigno77** [comment]
Corretto. E' previsto solo l'idPartecipante.
