### ISSUE TITLE
[Toscana/Bolzano] - Schede Aggiudicazione - membri RTI

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1545]
Buon pomeriggio,

Riprendo anche io la issue #1537 che risulta chiusa.

Il dubbio è se nelle schede di Aggiudicazione, bisogna trasmettere nel JSON tutti i membri del raggruppamento? Oppure è necessario trasmettere il solo IDPartecipante che comprende il raggruppamento ?

Inoltre abbiamo provato ad eseguire un test, nelle schede A indicando lo stesso IDPartecipante n volte per quanti sono i membri del raggruppamento e ci viene restituito l'errore:

"codice": "ERR87",
"descrizione": {
    "it": "idPartecipante duplicato per lo stesso lotto",
    "en": "idPartecipante duplicato per lo stesso lotto"
}

Vi chiedo una delucidazione definitiva su quale sia la modalità corretta di trasmissione dei dati per i membri di un raggruppamento nelle schede A.

Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente, i membri dell'RTI vengono comunicati come elenco nella scheda S2, indicando un unico id partecipante che li raggruppa. Quando viene trasmessa la scheda di aggiudicazione deve essere comunicato solo una volta l'idPartecipante di raggruppamento con l'importo di aggiudicazione.  Restiamo a disposizione. Cordiali saluti</p>
