### ISSUE TITLE
Accordo quadro campi con campo "Strumenti SvolgimentoProcedura"

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1547]
Buongiorno,

riprendo la issue #1492 per un chiarimento rispetto alle schede che possono essere utilizzate per lanciare una gara in accordo quadro.
Nella issue citata è indicato che per fare una gara in accordo quadro: "selezionabile indicando la voce 6 ‘Accordo quadro’ del campo ‘DatiBaseStrumentoProcedura’".

visionando alcune schede, in particolare P7_1_2, P7_1_3 e P7_2 non risulta presente il campo "DatiBaseStrumentoProcedura"  ma è invece presente il campo "Strumenti SvolgimentoProcedura" in cui è possibile selezionare accordo quadro.

Sarebbe corretto quindi fare un accordo quadro con queste schede?

**Comment by obigno77** [comment]
Nelle prossime versioni sarà introdotto il blocco DatiBaseStrumentoProcedura nelle schede dove è necessario.
Nel frattempo è necessario e sufficiente valorizzare la voce "Accordo quadro" di "Strumenti SvolgimentoProcedura"
