### ISSUE TITLE
[Consip] errore su A1_30 dopo P1_15_2

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1549]
dopo aver pubblicato l'appalto con scheda P1_15_2 proviamo a trasmettere la A1_30 ma riscontriamo l'errore:
{"status":400,"title":"KO","detail":"SC_N_CRE","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}" 

potete verificare?
 GovWay-Message-ID:"40b9f063-ace5-4d37-8990-ee9aef732861"
GovWay-Transaction-ID:"2aeaa987-3537-11ef-8dc0-0050568e08b3"
"idAppalto":"72fda443-a52f-46d0-bf33-7f7dc5451736"

**Comment by anac-uscp** [comment]
<p>Gentile Utente,</p>

<p>per poter procedere all'analisi della problematica necessitiamo del payload della chiamata.</p>

<p>La invitiamo a creare una nuova issue contenente il payload della chiamata.</p>

<p> </p>

<p>Restiamo a disposizione.</p>

<p> </p>

<p>Cordiali Saluti</p>
