### ISSUE TITLE
Accessibilità Ambiente di Test

### ISSUE THREAD

**Issue by produttorepiattaformaquellobravo** [anticorruzione/npa#155]
Non è chiaro come sia possibile per un operatore privato accedere all'ambiente di test.
Senza questo ambiente è davvero complicato  poter adempiere agli obblighi normativi richiesti per aggiornare le piattaforme. E' possibile avere un chiarimento al rigurdo?
Grazie

**Comment by supportoAnac** [comment]
Il servizio è disponibile a tutti i soggetti che possono accedere tramite PDND, abilitati secondo la normativa AgID.

**Comment by federicodemarco** [comment]
Buongiorno, 
confermate che al momento per i privati non è disponibile ancora la checklist necessaria alla certificazione alla PDND.
In caso di risposta affermativa quando è prevista la pubblicazione della checklist? 
Ad ogni modo sarà possibile per i privati accedere alla PDND anche prima della certificazione, per poter sostenere la fase di test delle integrazioni?

Grazie
