### ISSUE TITLE
[TOSCANA/BOLZANO] - Richiesta annullamento (Scheda ANN) 

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1552]
Salve,

a seguito della scheda **AD4**, abbiamo inviato la scheda **ANN.**

- Dov'è possibile **visualizzare** la richiesta di **annullamento**?

Infatti, richiamando la funzione di "Consulta-appalto" per l'AD4, **non ritroviamo** tale modifica e lo **statoScheda** resta sempre **CONF**.
Inoltre, nelle **tipologiche** previste https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/tipologiche/statoScheda.json **non c'è alcun riferimento all'annullamento.** 

(In allegato tutti i JSON di riferimento):

[postANN_consulta-appalto.txt](https://github.com/user-attachments/files/16051488/postANN_consulta-appalto.txt)
[ANN_jsonInput.txt](https://github.com/user-attachments/files/16051489/ANN_jsonInput.txt)
[preANN_consulta-appalto.txt](https://github.com/user-attachments/files/16051490/preANN_consulta-appalto.txt)
[ANN_jsonOutput.txt](https://github.com/user-attachments/files/16051491/ANN_jsonOutput.txt)
[ANN_esito-operazione.txt](https://github.com/user-attachments/files/16051492/ANN_esito-operazione.txt)

**Comment by obigno77** [comment]
La scheda di annullamento non altera lo stato della precedente scheda confermata ma traccia solo l'operazione di annullamento. Quindi è sufficiente che l'esito della SC_CONF della scheda ANN sia OK
