### ISSUE TITLE
[Toscana/Bolzano] - Rettifica - ERR63 - tipologica non valida: 'contrattiDisposizioniParticolari': 2

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1554]
Salve,

Stiamo procedendo con la rettifica dei formulari, pubblicati prima del changelog di ANAC, stiamo riscontrando il seguente errore: ERR63 - tipologica non valida: 'contrattiDisposizioniParticolari': {'contrattiDisposizioniParticolari': '2'}. 

L'errore si verifica poiché il campo Contratto disposizioni particolare è valorizzato con la voce dismessa - "Servizi sociali e altri servizi specifici di cui all’allegato XIV della direttiva 24/2014/UE, compresi servizi alla persona".

Questa voce è stata dismessa a seguito del rilascio in produzione del nuovo changelog di ANAC del 10/06/2024.

Chiediamo supporto su come procedere con la rettifica dei formulari, pubblicati prima del changelog di ANAC con le voci attualmente dismesse.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Deve essere sostituita la voce 2 dismessa con la nuova voce "Servizi sociali e assimilati" con codice 8.<br>
<br>
Restiamo  a disposizione.<br>
<br>
Cordiali saluti</p>
