### ISSUE TITLE
variazioni soggettivi e subappalti in caso di adesioni

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1556]
Buongiorno,

in caso di gare gestite da un soggetto da cui poi acquistano altri enti, come devono essere gestite le variazioni soggettive/subappalti?

in particolare, il soggetto che fa la gara e che firma il contratto dovrà gestire le variazioni soggettive (S4) e subappalti (RSU1, ES1) direttamente con le schede dedicate. i soggetti che aderiscono e acquistano da queste convenzioni con schede AD4 come devono compilare la scheda rispetto a variazioni soggettive e subappalti? in caso di adesione successiva come aggiudicatari devono inserire l'originale/la nuova composizione da variazione soggettiva/anche eventuali subappaltatori? 
inoltre, in caso di AD4 già inviata ad ANAC e confermata devono fare qualche modifica se subentra un subappalto/variazione soggettiva (questa sarebbe un onere ulteriore per le singole SA che aderiscono per acquisti)?

infine, per AD4 in cui è previsto eDGUE deve essere utilizzato quello originale della SA che ha fatto la gara e la convenzione? devono essere riverificati anche subappaltatori ecc?

la casistica si pone principalmente per le gare dei soggetti aggregatori

**Comment by obigno77** [comment]
I subappalti vanno gestiti da chi stipula l'accordo quadro
