### ISSUE TITLE
[TEAMSYSTEM] Date presenti nella risposta del servizio di consulta-avviso

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1557]
le date presenti nella risposta del consulta avviso non  sono corrette.
Di seguito un esempio di invocazione con la relativa risposta:
<img width="926" alt="immagine" src="https://github.com/anticorruzione/npa/assets/44367854/51494c0b-0364-4a27-a083-210e6393819e">
La richiesta è stata prodotta alle 09:55:59
la request è la seguente:
https://apigw-test.anticorruzione.it/modi/rest/PubblicaAvviso/v2/consulta-avviso?idAvviso=ab5627b9-7c64-49e4-9246-c721c62ded25
la response è la seguente:
{
    "avviso": {
        "datiPubblicazioneEU": null,
        "datiPubblicazioneIT": {
            **"dataControllo": "2024-07-03T11:52:14.659+02:00",**
            **"dataInoltroPubblicazione": "2024-07-03T11:41:49.897+02:00",**
            "dataPubblicazione": null,
            "idAvvisoPVL": "f2eec7a8-1770-41b7-82f7-d10d84512217",
            "stato": {
                "codice": "IN_ATT_PUBB",
                "idTipologica": "statoAvviso"
            },
            "tipo": {
                "codice": "IT",
                "idTipologica": "tipoAvviso"
            }
        }
    },
    "detail": "Operazione Effettuata",
    "GovWayMessageId": " 09027738-623b-4d01-802e-c9284a9d5765",
    "GovWayTransactionId": " 0913ff0b-3910-11ef-bd08-0050568e9679",
    "status": 200,
    "title": "OK",
    "type": "about:blank"
}

Spero che l'errore nelle date (viene sommato 2 alla data anzichè sottrarlo) non infici i tempi di pubblicazione che al momento BLOCCANO dei nostri test interni sulla fase di esecuzione.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>abbiamo replicato la chiamata di consulta-avviso con idAvviso: "ab5627b9-7c64-49e4-9246-c721c62ded25"<br>
e la response é stata la seguente: </p>

<p>{<br>
    "instance": null,<br>
    "status": 200,<br>
    "title": "OK",<br>
    "detail": "Operazione Effettuata",<br>
    "type": "about:blank",<br>
    "avviso": {<br>
        "idAvviso": "ab5627b9-7c64-49e4-9246-c721c62ded25",<br>
        "idAppalto": "c3dac993-0a4c-44a1-aa70-ed837ddb92a6",<br>
        "idPianificazione": null,<br>
        "dataCreazione": "2024-07-03T09:41:49.611+00:00",<br>
        "dataPubblicazione": "2024-07-04T20:00:00.000+00:00",<br>
        "stato": {<br>
            "idTipologica": "statoAvviso",<br>
            "codice": "PUBB"<br>
        },<br>
        "dataControllo": "2024-07-04T21:07:12.258+00:00",<br>
        "azione": {<br>
            "idTipologica": "tipoAzioneAvviso",<br>
            "codice": "AZ_PUBB"<br>
        },<br>
        "datiPubblicazioneEU": null,<br>
        "datiPubblicazioneIT": {<br>
            "idAvvisoPVL": "f2eec7a8-1770-41b7-82f7-d10d84512217",<br>
            "tipo": {<br>
                "idTipologica": "tipoAvviso",<br>
                "codice": "IT"<br>
            },<br>
            "stato": {<br>
                "idTipologica": "statoAvviso",<br>
                "codice": "PUBB"<br>
            },<br>
            "dataControllo": "2024-07-04T21:07:12.258+00:00",<br>
            "dataInoltroPubblicazione": "2024-07-03T09:41:49.897+00:00",<br>
            "dataPubblicazione": "2024-07-04T20:00:00.000+00:00"<br>
        }<br>
    },<br>
    "scheda": null,<br>
    "appalto": null,<br>
    "piano": null<br>
}</p>

<p><br>
come si nota la data di inoltro pubblicazione é stata effettuata alle ore 9 e 41.</p>

<p>Pertanto vi initiamo a riutilizzare la chiamata perché potrebbe esserci stato un malfunzionamento nel servizio.</p>

<p>Restiamo a disposizione.</p>

<p>Cordiali saluti</p>
