### ISSUE TITLE
Gestione dell'esito operazione per i servizi CM1, CM2 e ANN

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1558]
si richiede quale valore è necessario inserire nel campo tipoOperazione, non essendoci un valore nella tipologica di tipo specifico.
Gli unici con una certa attinenza sono i seguenti:
{
    "codice":"SC_MOD",
    "descrizione": {
        "it": "Modifica scheda",
        "en": "Modifica scheda"
    },
    "dataInizio":null,
    "dataFine":null
},
{
    "codice":"SC_CANC",
    "descrizione": {
        "it": "Cancella scheda",
        "en": "Cancella scheda"
    },
    "dataInizio":null,
    "dataFine":null
},

ma si riferiscono ovviamente ai servizi relativi (modifica-scheda e cancella-scheda).
In attesa di un rapido riscontro per proseguire nei test

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Si ricorda che tutta la documentazione è disponibile sul canale github dell'autorità <a href="https://github.com/anticorruzione">Autorità Nazionale Anticorruzione · GitHub</a>. Per una maggiore visibilità dei servizi coinvolti si può anche utilizzare lo swagger per visualizzare graficamente le specifiche dei servizi.</p>

<p>In particolare il servizio di esito-operazione accetta in ingresso per il parametro "tipoOperazione"i valori censiti della relativa tipologica <a href="https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/tipologiche/tipoOperazione.json">npa/docs/modello-dati/tipologiche/tipoOperazione.json at main · anticorruzione/npa · GitHub</a>. Il discorso è analogo per tutti gli altri parametri.</p>

<p>Si invita a non aprire ticket senza aver preliminarmente consultato le fonti pubblicate e disponibili.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
