### ISSUE TITLE
eForms sdk 1.8.0

### ISSUE THREAD

**Issue by vincennamo** [anticorruzione/npa#156]
L'ultima versione di eForms SDK è la 1.8.0, e anche eNotice2 è stato aggiornato a questa versione, 
ma nella documentazione ANAC, come Standard Adottati, è riportata ancora la "eForms sdk versione 1.7.0".
E' previsto l'upgrade alla versione 1.8.0 e quando sarà effettuato?

**Comment by paolo-urbanetto** [comment]
Buongiorno, mi aggiungo alla segnalazione. La versione SDK 1.8.0 apporta varie modifiche e correzioni al contenuto dei metadati degli eForms (https://github.com/OP-TED/eForms-SDK/blob/develop/CHANGELOG.md)
Stiamo lavorando anche noi sulla 1.8.0. Se dobbiamo fare un downgrade, visti i tempi ridottissimi, necessitiamo di averne riscontro rapidamente.
Grazie
