### ISSUE TITLE
[TOSCANA/BOLZANO] Richiesta chiarimenti CM1/CM2

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1560]
Salve,

- Scheda CM1: Scheda di comunicazione modifica dati della procedura per appalti **sopra i 5K euro**
- Scheda CM2: Scheda di comunicazione modifica dati della procedura per appalti **sotto i 5K euro**

**qual è la scheda da utilizzare per appalti = 5k?**

**Comment by AFSOLUZIONI** [comment]
In uniformità con le altre schede della PCP il valore "5k" andrebbe associato al "maggiore di 5k" (vedi AD3), quindi, si presume che gli appalti con importo = 5k siano da gestire con la scheda CM1.
Comunque attendiamo la risposta formale di ANAC (e possibilmente la rettifica della descrizione della scheda CM1!!)

**Comment by anac-uscp** [comment]
<p>La Scheda CM1 è valida per la comunicazione della modifica dati di una procedura per appalti **pari o sopra i 5K euro**</p>

<p>Nel prossimo changelog sarà modificato l'orchestratore come di seguito:</p>

<table cellspacing="0" style="border-collapse:collapse;width:1297px;">
	<tbody>
		<tr>
			<td class="xl65" style="border-bottom:none;border-left:none;border-right:none;border-top:none;height:103px;padding-left:1px;padding-right:1px;padding-top:1px;vertical-align:bottom;white-space:normal;width:106px;"><span style="font-size:16px;"><span style="color:black;"><span style="font-weight:400;"><span style="font-style:normal;"><span style="text-decoration:none;"><span style="font-family:Arial;">A_5</span></span></span></span></span></span></td>
			<td class="xl65" style="border-bottom:none;border-left:none;border-right:none;border-top:none;padding-left:1px;padding-right:1px;padding-top:1px;vertical-align:bottom;white-space:normal;width:127px;"><span style="font-size:16px;"><span style="color:black;"><span style="font-weight:400;"><span style="font-style:normal;"><span style="text-decoration:none;"><span style="font-family:Arial;">CM1</span></span></span></span></span></span></td>
			<td class="xl63" style="background-color:yellow;border-bottom:none;border-left:none;border-right:none;border-top:none;padding-left:1px;padding-right:1px;padding-top:1px;vertical-align:bottom;white-space:nowrap;width:148px;"><span style="font-size:16px;"><span style="color:black;"><span style="font-weight:400;"><span style="font-style:normal;"><span style="text-decoration:none;"><span style="font-family:Arial;">appalti &gt; = 5k</span></span></span></span></span></span></td>
			<td class="xl65" style="border-bottom:none;border-left:none;border-right:none;border-top:none;padding-left:1px;padding-right:1px;padding-top:1px;vertical-align:bottom;white-space:normal;width:116px;"><span style="font-size:16px;"><span style="color:black;"><span style="font-weight:400;"><span style="font-style:normal;"><span style="text-decoration:none;"><span style="font-family:Arial;">affidamento</span></span></span></span></span></span></td>
			<td class="xl67" style="border-bottom:none;border-left:none;border-right:none;border-top:none;padding-left:1px;padding-right:1px;padding-top:1px;text-align:left;vertical-align:bottom;white-space:nowrap;width:105px;"><span style="font-size:16px;"><span style="color:black;"><span style="font-weight:400;"><span style="font-style:normal;"><span style="text-decoration:none;"><span style="font-family:Arial;">Comunicazione modifica dati della procedura per appalti sopra i 5K euro</span></span></span></span></span></span></td>
			<td class="xl66" style="border-bottom:none;border-left:none;border-right:none;border-top:none;padding-left:1px;padding-right:1px;padding-top:1px;vertical-align:bottom;white-space:nowrap;width:117px;"><span style="font-size:16px;"><span style="color:black;"><span style="font-weight:400;"><span style="font-style:normal;"><span style="text-decoration:none;"><span style="font-family:Arial;">CM1</span></span></span></span></span></span></td>
			<td class="xl65" style="border-bottom:none;border-left:none;border-right:none;border-top:none;padding-left:1px;padding-right:1px;padding-top:1px;vertical-align:bottom;white-space:normal;width:73px;"><span style="font-size:16px;"><span style="color:black;"><span style="font-weight:400;"><span style="font-style:normal;"><span style="text-decoration:none;"><span style="font-family:Arial;">1.0</span></span></span></span></span></span></td>
			<td class="xl64" style="background-color:yellow;border-bottom:none;border-left:none;border-right:none;border-top:none;padding-left:1px;padding-right:1px;padding-top:1px;vertical-align:bottom;white-space:normal;width:173px;"><span style="font-size:16px;"><span style="color:black;"><span style="font-weight:400;"><span style="font-style:normal;"><span style="text-decoration:none;"><span style="font-family:Arial;">Scheda di comunicazione modifica dati della procedura per appalti pari o sopra i 5K euro</span></span></span></span></span></span></td>
			<td class="xl65" style="border-bottom:none;border-left:none;border-right:none;border-top:none;padding-left:1px;padding-right:1px;padding-top:1px;vertical-align:bottom;white-space:normal;width:197px;"> </td>
			<td class="xl65" style="border-bottom:none;border-left:none;border-right:none;border-top:none;padding-left:1px;padding-right:1px;padding-top:1px;vertical-align:bottom;white-space:normal;width:131px;"><span style="font-size:16px;"><span style="color:black;"><span style="font-weight:400;"><span style="font-style:normal;"><span style="text-decoration:none;"><span style="font-family:Arial;">NO</span></span></span></span></span></span></td>
		</tr>
	</tbody>
</table>
