### ISSUE TITLE
401 - Errore SEC05 - ComunicaAppalto

### ISSUE THREAD

**Issue by petromanco** [anticorruzione/npa#1561]
Salve,
come da titolo qualsiasi chiamata tentiamo di fare verso l'endpoint di ComunicaAppalto riceviamo la risposta seguente:

`{
  "status": 401,
  "title": "KO",
  "detail": "Non Autorizzato",
  "type": "about:blank",
  "errori": [
    {
      "idTipologica": "errori",
      "codice": "SEC05"
    }
  ]
}`

Gli stessi parametri tranne audience e purposeId vengono utilizzati anche per PCP Code List che, invece, funziona regolarmente.

Cosa sbagliamo?

**Comment by petromanco** [comment]
È il codice fiscale inserito nella jws errato?
Se deve essere creato un utente fittizio con ruolo di RUP / DEC etc... dove occorre crearlo?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>per effettuare un'analisi più approfondita, chiediamo gentilmente di fornire gli headers della chiamata, l'utente che sta chiamando i servizi, i parametri in ingresso e quali servizi sta invocando.<br>
<br>
Cordiali saluti</p>
