### ISSUE TITLE
[Consip][BLK] i DMN referenziano campi non presenti nel modello dati

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1562]
Salve, 
abbiamo notato che i file DMN non sono aggiornati rispetto al modello dati delle schede: sono presenti regole che coinvolgono campi non presenti all'interno della scheda.

Poiché abbiamo implementato un validatore che si basa sulle regole definite nei DMN stiamo riscontrando dei problemi. Come mai sono presenti queste incongruenze?

esempio 1)
P1_10 (**appalto.datiBase.importo** non presente nella scheda)
(sum(for i in 1..count(lotti) return lotti[i].datiBase.importo) &lt; (appalto.datiBase.importo * 0.8)) or (sum(for i in 1..count(lotti) return lotti[i].datiBase.importo) &gt; appalto.datiBase.importo)

esempio 2)
AD1_26 (**aggiudicazione.datiBaseAccessibilita.giustificazione** non presente nella scheda)
some aggiudicazione in aggiudicazioni
satisfies aggiudicazione.datiBaseAccessibilita.accessibilita.codice = "n-inc-just" and (aggiudicazione.datiBaseAccessibilita.giustificazione = null or aggiudicazione.datiBaseAccessibilita.giustificazione ="")

esempio 3)
P1_18 (lotto.datiBaseTerminiInvio.oraScadenzaPresentazioneOfferte e lotto.datiBaseTerminiInvio.scadenzaPresentazioneInvito non presenti nella scheda)
REG96
some lotto in lotti 
satisfies (lotto.datiBaseTerminiInvio.oraScadenzaPresentazioneOfferte = null or lotto.datiBaseTerminiInvio.oraScadenzaPresentazioneOfferte="") and
(lotto.datiBaseTerminiInvio.scadenzaPresentazioneInvito = null or lotto.datiBaseTerminiInvio.scadenzaPresentazioneInvito = "")

P1_18 (appalto.datiBase.importo non presente nella scheda)
REG98
appalto.datiBase.importo = null or appalto.datiBase.importo &lt;= 0

P1_18 (lotto.datiBase.importo non presente nella scheda) 
REG99
some lotto in lotti
satisfies lotto.datiBase.importo = null or lotto.datiBase.importo &lt;= 0

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Il parametro di ingresso è denominato come l’analogo campo di $.anacForm e deve essere valorizzato con il dato proveniente dal medesimo campo anacForm in caso di schede non contenenti eform o dal tag xml equivalente in caso di presenza della eForm.</p>

<p>Cordiali saluti</p>
