### ISSUE TITLE
[Maggioli] Utilizzo della scheda CM1 per rettificare i CUP

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#1563]
Supponiamo di avere creato un appalto, ad esempio con una P3_1, specificando 2 CUP.
Come va utilizzata la scheda CM1 nei seguenti casi?
- Entrambi i CUP sono errati, e ne devo specificare altri 2
- Devo rettificare solo uno dei 2 CUP
- Devo aggiungere un terzo CUP

Probabilmente sarebbe più intuitivo l'utilizzo se la CM1 prevedesse la possibilità di inserire più di un CUP.

**Comment by UserM21** [comment]
Ciao,
analizzando i flussi previsti da ANAC per l'utilizzo delle schede CM1/CM2, non rientra la scheda P2_16. 
Voi avete provato ad inviare una CM1 dopo la P2_16? 
E non avete riscontrato alcun errore?

**Comment by lelio-raffaelli** [comment]
Ciao, hai ragione, a dir la verità la domanda era del tutto teorica, ed ho preso un esempio sbagliato.
Supponiamo quindi che l'appalto sia creato con una P3_1, il senso della domanda è lo stesso: se in creazione posso specificare n CUP, come gestisco il fatto che in rettifica posso specificarne uno solo?

Correggo la issue iniziale, grazie per la segnalazione.

**Comment by UserM21** [comment]
Nessun problema.
Ad ogni modo il dubbio è condiviso. Speriamo che ANAC risponda presto e fornisca maggiori dettagli sull'uso di queste schede.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Vi ringraziamo per la segnalazione.</p>

<p>La scheda CM1 è oggetto di evolutiva: la cardinalità del cup verrà modificata e reso array. Le modifiche saranno rilasciate con i prossimi changelog.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
