### ISSUE TITLE
[Consip] P1_10 - l'avviso resta IN_ATT_PUBB dopo modifica-avviso - incongruenza response esito operazione tipo operazione AV_MOD

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1565]
Salve,
abbiamo ricreato uno scenario di pubblicazione non andata a buon fine per testare il modifica-avviso.
Tuttavia, lo stato dell'avviso resta IN_ATT_PUBB senza mai transitare in pubblicato (vedi issue #1525).

Da un'ulteriore analisi abbiamo notato che chiamando il servizio di esito operazione con tipo operazione AV_MOD l'ultimo stato riportato è AV_IN_PUBB. Tuttavia cambiando il tipo operazione in AV_PUBB oppure consultando il servizio di stato avviso, l'avviso risulta PUBBLICATO. 
La data controllo relativa all’esito operazione con tipo operazione AV_MOD risulta precedente rispetto a quella relativa allo stato avviso, per cui è come se non fosse aggiornata.

Potreste verificare questa incongruenza? 

Di seguito le evidenze

**ESITO OPERAZIONE (tipoOperazione=AV_MOD&tipoRicerca=TUTTI_ESITI)**
GovWay-Message-ID [e828b0e3-78ae-464b-898b-79409c44c9c5]
GovWay-Transaction-ID [196d90c7-3d30-11ef-bd08-0050568e9679]

{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "b5e1bdac-86db-42d2-ac6e-5e5669c022a7",
      "idScheda": "9f4ef960-eff8-4106-9234-6e54c184e275",
      "codiceScheda": "P1_10",
      "idNuovaScheda": "459a32b1-1967-4d1a-9fe2-e98adb469374",
      "codiceNuovaScheda": "P1_10",
      "idAvviso": "5452902b-1ba6-4a8d-8e23-5c7dd621a4e1",
      "idNuovoAvviso": "f922ecf7-e87e-4122-a1fd-2a85a567f733",
      "esito": {
        "idTipologica": "esito",
        "codice": "OK"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AV_MOD"
      },
      "dataControllo": "2024-07-02T11:28:03.976+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AV_IN_PUBB"
      }
    },
    {
      "idAppalto": "b5e1bdac-86db-42d2-ac6e-5e5669c022a7",
      "idScheda": "9f4ef960-eff8-4106-9234-6e54c184e275",
      "codiceScheda": "P1_10",
      "idAvviso": "5452902b-1ba6-4a8d-8e23-5c7dd621a4e1",
      "esito": {
        "idTipologica": "esito",
        "codice": "KO"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AV_MOD"
      },
      "dataControllo": "2024-07-01T17:54:02.507+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AV_N_PUBB"
      },
      "errori": [
        {
          "idTipologica": "errori",
          "codice": "ERR15"
        }
      ]
    },
    {
      "idAppalto": "b5e1bdac-86db-42d2-ac6e-5e5669c022a7",
      "idScheda": "9f4ef960-eff8-4106-9234-6e54c184e275",
      "codiceScheda": "P1_10",
      "idAvviso": "5452902b-1ba6-4a8d-8e23-5c7dd621a4e1",
      "esito": {
        "idTipologica": "esito",
        "codice": "KO"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AV_MOD"
      },
      "dataControllo": "2024-07-01T17:52:53.561+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AV_N_PUBB"
      },
      "errori": [
        {
          "idTipologica": "errori",
          "codice": "ERR72"
        }
      ]
    },
    {
      "idAppalto": "b5e1bdac-86db-42d2-ac6e-5e5669c022a7",
      "idScheda": "9f4ef960-eff8-4106-9234-6e54c184e275",
      "codiceScheda": "P1_10",
      "idAvviso": "5452902b-1ba6-4a8d-8e23-5c7dd621a4e1",
      "esito": {
        "idTipologica": "esito",
        "codice": "KO"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AV_MOD"
      },
      "dataControllo": "2024-07-01T17:52:24.647+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AV_N_PUBB"
      },
      "errori": [
        {
          "idTipologica": "errori",
          "codice": "ERR71"
        }
      ]
    }
  ]
}

**STATO AVVISO**
GovWay-Message-ID [1e1e4af5-5034-46d5-8524-0b76a6355de3]
GovWay-Transaction-ID  [785cd9b1-3d30-11ef-8dc0-0050568e08b3]

{
  "status": 200,
  "title": "OK",
  "detail": "Operazione Effettuata",
  "type": "about:blank",
  "statoAvviso": {
    "idAvviso": "f922ecf7-e87e-4122-a1fd-2a85a567f733",
    "idAppalto": "b5e1bdac-86db-42d2-ac6e-5e5669c022a7",
    "dataControllo": "2024-07-02T16:15:09.237+00:00",
    "stato": {
      "idTipologica": "statoAvviso",
      "codice": "PUBB"
    }
  }
}

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>se si invoca il servizio di modifica avviso e successivamente si controllano gli esiti, l'unico stato in cui transita a seguito dell' operazione eseguita con successo è "AV_IN_PUBB", poichè per esigenze di processo il servizio di modifica non fa altro che invocare il servizio di pubblicazione a cui trasmette un nuovo payload da pubblicare.Quindi dagli esiti operazione filtrati per tipo "AV_PUBB", compariranno per l'idAvviso "vecchio" i codici esito del tipo operazione "AV_PUBB" intermedi e il finale (codice esito="AV_MOD") , mentre per l'idAvviso "nuovo" compariranno analogamente i codici esito del tipo operazione "AV_PUBB" intermedi e il finale (codice esito="AV_PUBB")</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
