### ISSUE TITLE
Comunica Appalto crea-appalto

### ISSUE THREAD

**Issue by petromanco** [anticorruzione/npa#1566]
Invocando l'e-service crea-appalto la response restituisce 401 - Non Autorizzato ma il body della stessa è vuoto mentre nell'header sono presenti le seguenti informazioni:

'GovWay-Message-ID': '405a6bdb-1687-42ac-8d9e-3c22bbe5064d'
'GovWay-Transaction-ID': 'dd08c695-3dcb-11ef-8dc0-0050568e08b3'

@mpizziconi  e @obigno77  potete fornirmi riscontro cortesemente considerando che il 14 c.m. scade il termine per il completamento dei test.

@supportoAnac esiste un'utenza di test da associare al JWS?

Grazie

**Comment by obigno77** [comment]
Qual è la piattaforma? Non avete chiesto le utenze di test?

**Comment by petromanco** [comment]
Dove occorre chiedere l'utenza di test per invocare gli e-service dell'ANAC?

**Comment by obigno77** [comment]
uscp@anticorruzione.it

**Comment by petromanco** [comment]
Ho appena inviato la richiesta di un'utenza all'indirizzo indicato.

Approfittando della disponibilità volevo chiedere se per quanto riguarda la scheda AD2_25 occorre inviare sia l'appalto che l'aggiudicazione, mentre come occorre valorizzare la proprietà **ESPD**?

Faccio presente inoltre che nel file yaml della suddetta scheda nella schema **AppaltoAD2_25Type** si fa riferimento a **AppaltoAD1_25Type** ma quest'ultima prevede l'invio al TED, è un errore?

**Comment by obigno77** [comment]
La scheda AD2_25 è una scheda di affidamento diretto e va inviata contestualmente all'aggiudicazione.
La proprietà espd va riempito con l'XML della espd-requestmin formato base64.
La scheda AD2_25 ha delle sezioni in comune con l'AD1_25 che sono richiamate nello yaml.

**Comment by petromanco** [comment]
Grazie. Per compilare l'XML della espd-requestmin dobbiamo seguire la definizione del espdRequestType a questa [url](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml#/components/schemas/EspdRequestType) ?
