### ISSUE TITLE
[CONSIP] - P2_16 - REG 20 - La regola non viene intercettata

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1567]
Compilando la scheda scheda P2_16 con le regole sottostanti

REG20 - some lotto in lotti satisfies lotto.acquisizioneCup=false and lotto.datiBase.oggettoContratto.codice="works" and lotto.tipologiaLavoro.codice!="12" and lotto.cupLotto = null
**riscontriamo tale anomalia: la regola non viene intercettata.**

scheda: P2_16
idappalto: a8763ce4-bb57-4579-8f8b-99cc6c29daa9
 
BLOB
{"lotIdentifier":"LOT-0001","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"2"}],"contrattiDisposizioniParticolari":{"idTipologica":"contrattiDisposizioniParticolari","codice":"1"},"codIstat":{"idTipologica":"codIstat","codice":"999991201"},"afferenteInvestimentiPNRR":false,"acquisizioneCup":false,"prestazioniComprese":{"idTipologica":"prestazioniComprese","codice":"1"},"servizioPubblicoLocale":false,"ripetizioniEConsegneComplementari":false,"lavoroOAcquistoPrevistoInProgrammazione":false,"saNonSoggettaObblighi24Dicembre2015":false,"iniziativeNonSoddisfacenti":false,"strumentiElettroniciSpecifici":false,"ccnl":"0","tipologiaLavoro":[{"idTipologica":"tipologiaLavoro","codice":"13"}],"opzioniRinnovi":false,"categoria":{"idTipologica":"categoria","codice":"999"},"quadroEconomicoStandard":{"impLavori":10000000,"impServizi":1000000,"impForniture":100000000,"impTotaleSicurezza":10000000,"ulterioriSommeNoRibasso":100000000,"impProgettazione":100000000,"sommeOpzioniRinnovi":100000000,"sommeRipetizioni":1000000000,"sommeADisposizione":10000000000},"datiBase":{"oggettoContratto":{"idTipologica":"oggettoContratto","codice":"works"},"oggetto":"TEST","importo":10000},"datiBaseTerminiInvio":{"oraScadenzaPresentazioneOfferte":"2024-07-12T14:47:00Z"},"datiBaseCPV":{"tipoClassificazione":{"idTipologica":"tipoClassificazione","codice":"cpv"},"cpvPrevalente"{"idTipologica":"CPV","codice":"03311230"}},"datiBaseDocumenti":{"url":"[https://pre.acquistinretepa.it/npa/#!/formAnac"}}](https://pre.acquistinretepa.it/npa/#!/formAnac%22%7D%7D)

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>La segnalazione è corretta, la fix della regola è stata implementata.</p>

<p>La fix verrà inserita nel rilascio del changelog ed andrà in produzione con il primo rilascio utile.</p>

<p>Saluti</p>
