### ISSUE TITLE
Importo CO1/CO2 netto o lordo

### ISSUE THREAD

**Issue by stibium-51** [anticorruzione/npa#1568]
Il campo "importo" delle schede CO1 e CO2 con quale valore va implementato? L'importo netto o l'importo lordo comprensivo di IVA, contributi integrativi, eventuali altre somme a disposizione effettivamente spese?

Grazie mille in anticipo

**Comment by obigno77** [comment]
Valgono le stesse regole in uso da sempre. Gli importi sono esclusi IVA e somme a disposizione
