### ISSUE TITLE
CM1, CM2 e ANN - Molteplicità delle informazioni presenti

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1569]
Dalla documentazione le schede CM1, CM2 e ANN possono essere inviate indicando il CIG (leggasi Lotto) a cui far riferimento.
Da una analisi di maggior dettaglio sembra che la struttura sia correttamente utilizzabile solo nel caso dell'AD5.
Negli altri casi previsti si creano delle potenziali situazioni di errore / incongruenza.
Nel seguito una tabellina che riporta le diverse situazioni. Si richiede conferma di quanto analizzato e la proposta di possibili soluzioni.
![image](https://github.com/anticorruzione/npa/assets/44367854/82a4e1b5-650a-46ff-ba9d-7d004995406e)

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Vi ringraziamo per la segnalazione.</p>

<p>La scheda CM1 è oggetto di evolutiva: la cardinalità del cup verrà modificata e reso array. Le modifiche saranno rilasciate con i prossimi changelog.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
