### ISSUE TITLE
Stacco CIG propedeutico alla compilazione eDGUE per  servizio "CONFERMA APPALTO"

### ISSUE THREAD

**Issue by lmanc77** [anticorruzione/npa#157]
Guardando le specifiche  per la creazione dell'espd (DGUE), (dal documento AGID "edgue-it_specifiche_tecniche_v1.0.0_0.pdf") osserviamo che è richiesto il codice CIG di almeno un lotto dell'appalto come dato obbligatorio.
Sappiamo che lo stacco dei CIG avviene alla chiamata del servizio di Conferma appalto.
Sulla base di queste informazioni, chiediamo quindi, per una scheda appalto che necessita l'inserimento dei dati espd, come possiamo procedere visto che per avere l'espd serve il CIG che otteniamo solo dopo aver confermato l'appalto?"

Grazie

**Comment by supportoAnac** [comment]
Il problema è stato segnalato ad AgID al fine di sostituire il CIG con il Lot Identifier nel DGUE.
