### ISSUE TITLE
schede P6 e P7_2 - schede aggiudicazione

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1572]
Buongiorno,

si richiede una conferma in merito alle schede P6.. e P7_2 che dall'orchestratore non presentano schede di aggiudicazione rispetto ai flussi di appartenenza.

in particolare, da test effettuati è stato possibile inviare anche le schede di aggiudicazione con eFORM (es A1_29) perciò si è attivata per gli utenti la possibilità di usare per l'aggiudicazione sia A1_29 che A2_29 in base alla soglia e necessità di fare eFORM.

Ci è arrivata però una segnalazione che in fase di invio della A1_29 non è possibile procedere perchè il LOTIDentifier non corrisponde fra eFORM e ANACFORM. Dato che in fase di indizione ad es della P7_2 non c'è eFORM l'utente come identificativo lotto ha usato una descrizione e non il formato LOT-000X previsto da eFORM.

Chiediamo quindi se è corretto poter indicare all'utente di procedere con scheda di aggiudicazioen A2_29 anche se la procedura è sopra soglia (o altrimenti come è possibile risolvere questa problematica dei lotidentifier ato che oramai i termini sono scaduti e non si possono fare neanche rettifiche, sempre che il lotidentifiere sia un dato rettificabile).

Grazie

**Comment by obigno77** [comment]
La prossima versione dell'orchestratore prevederà unicamente la scheda A2_29
