### ISSUE TITLE
Comunica Appalto Response 401 - Non Autorizzato

### ISSUE THREAD

**Issue by petromanco** [anticorruzione/npa#1575]
La response del e-service crea-appalto è null mentre dall'Headers ricavo le seguenti informazioni:
{
    "GovWay-Message-ID": "1000f20d-7bd4-4c44-99c0-a0f577b0a48f",
    "GovWay-Transaction-ID": "24485692-3f87-11ef-bd08-0050568e9679"
}

come posso sapere il dettaglio?

**Comment by obigno77** [comment]
L'errore 401 è un errore di utenza JWS non autorizzata
