### ISSUE TITLE
[CONSIP] Scheda A1_32/A1_37 REG_47 - La regola presenta un errore sintattico

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1576]
Salve,
è stata compilata la scheda A1_32/A1_37 con le condizioni necessarie a far scattare la regola REG_47:
some aggiudicazione in aggiudicazioni satisfies (count(aggiudicazione.offertePresentate) &gt; aggiudicazione.numeroOfferteAmmesse)

Tuttavia, la regola non viene riscontrata e vengono staccati i CIG.

Dalle verifiche eseguite ci risulta che la regola non venga attivata poichè c'è un errore nel file DMN.

In particolare manca un apice sul tag text della regola sul file DMN. Nel dettaglio:

<text>{\"idTipologica\":\"errori\",\"codice\":\"REG47\"}"</text>

Dovrebbe invece essere  <text>"

{\"idTipologica\":\"errori\",\"codice\":\"REG47\"}
"</text>

Questo genera un errore di parsing che non fa applicare la regola.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>La segnalazione è corretta, la regola verrà corretta in tutte le schede coinvolte.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
