### ISSUE TITLE
ARIA SpA - FVOE - Richiesta accesso Fascicolo Operatore Economico

### ISSUE THREAD

**Issue by paolomariobardi** [anticorruzione/npa#1577]
Buongiorno, 
rispetto a quanto indicato nella gestione fascicolo (rif 6 Giugno 2024):
"La SA può richiedere l'accesso al fascicolo se non ha mai eseguito la richiesta o se questa é stata NEGATA o REVOCATA dall'OE o se é in stato SCADUTA. Non vengono accettate più richieste di autorizzazione per uno stesso fascicolo già autorizzato o su cui é in attesa di risposta da parte dell'OE"
La richiesta del servizio è sempre invocabile non è presente nessun vincolo e restituisce sempre identificativi diversi.

Vi chiediamo se tale comportamento è coretto.

**Comment by obigno77** [comment]
Il virgolettato è corretto

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Quanto descritto è corretto, inoltre si riporta nel link di seguito https://github.com/anticorruzione-test/npa/blob/main/docs/scenari-di-esempio/gestione_fascicolo.md la documentazione che spiega in dettaglio la casistica segnalata.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
