### ISSUE TITLE
Crea Appalto errore 400

### ISSUE THREAD

**Issue by petromanco** [anticorruzione/npa#1579]
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "7af51b4c-4036-11ef-8dc0-0050568e08b3"
}

**Comment by obigno77** [comment]
Verifica ModI della richiesta fallita: [GOVWAY-661] [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2024-07-12_12:33:15.000')
