### ISSUE TITLE
Formato coppia chiave:valore nel JSON per i Campi opzionali con valore non indicato dall'utente

### ISSUE THREAD

**Issue by labruno** [anticorruzione/npa#158]
Potreste confermare sia corretto NON inviare nel JSON una coppia "chiave":"valore" SE la chiave è OPZIONALE  ed il valore non è specificato dall'utente ? Rispetto a questa ipotesi è equivalente inviare il campo chiave con valore vuoto ? Quale è  la soluzione indicata per NPA?

Ad esempio :

Se nel servizio   **/crea-appalto** di comunica appalto (API Rest per la creazione di un Appalto. SINCRONO ) avendo il JSON sotto ( estratto )  lo user non dovesse  specificare alcun valore per il campo scheda-->body-->anacForm-->appalto-->**linkDocumenti** , questultimo campo non deve essere inviato ? Oppure ci si aspetta che tale chiave venga inviata con valore vuoto ?

{
"scheda": {
    "codice": {
      "idTipologica": "codiceScheda",
      "codice": "P1_10"
    },
    "versione": "1.0",
			
    "body": {
      "anacForm": {
        "stazioniAppaltanti": [
          {
            "codiceFiscale": "RSSMRA80L05F593A",
            "codiceAusa": "aGGDS45",
            "codiceCentroCosto": "string",
            "saTitolare": true
          }
        ],
        "appalto": {
          "codiceAppalto": "test_ACN__{{$timestamp}}",/* CAMBIARE */
          "motivoUrgenza": {
            "idTipologica": "string",
            "codice": "string"
					  
          },
          **"linkDocumenti": "http://test.che.dovrebbeesserevuoto.com"**  _/* DOMANDA : QUESTO CAMPO NON VA INVIATO e/o VA INVIATO CON VALORE VUOTO ? */_
        },
        "lotti": [
          {
_....omissis ..._

**Comment by supportoAnac** [comment]
Corretto. Se il campo è facoltativo e non si ha intenzione di trasmetterlo non deve essere presente nel json. In caso contrario sarebbe soggetto a validazione.
