### ISSUE TITLE
scadenza presentazione offerte per negoziata senza bando con indagine di mercato (P7_1_2; P7_2)

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1581]
Buongiorno,

non risulta chiaro in campo deve essere indicata la data di scadenza di presentazione delle offerte dell'effettiva negoziata senza bando  per le schede P7_1_2 e P7_1_3 (dato che queste riguardano l'indagine di mercato).

gli utenti ci segnalano diverse criticità di incongruenza fra la data per pagare il contributo ANAC da parte degli OE rispetto alla tempistica di scadenza di presentazione delle offerte.

Grazie

**Comment by anac-uscp** [comment]
<p>Nelle Schede P7_1_2 e P7_1_3 è presente la data di scadenza per la presentazione della richiesta di invito.<br>
La data di scadenza di presentazione delle offerte è presente nella scheda S2.<br>
Il contributo è a carico delle imprese invitate, comunicate tramite S2.</p>
