### ISSUE TITLE
[BLK] Impossibile procedere con A1_29 per gara deserta

### ISSUE THREAD

**Issue by ctav8** [anticorruzione/npa#1582]
Buongiorno,
mi ricollego alla issue #1346, in quanto da alcuni giorni inviando una scheda S2 vuota, questa viene respinta con ERR4.

Avendo però necessità di inviare una A1_29 per indicare che la gara è deserta,  come procedere se non ci sono soggetti da indicare nella S2 e la scheda è obbligatoria prima della A1_29?

Come procedere in questi casi? State già lavorando per risolvere anche questo problema?

es. ID APPALTO P1_16: f8880c82-45fc-4829-8988-367f0bf8b7ac

S2 non acquisita:
GovWay-Transaction-ID: 58a95f54-4270-11ef-8dc0-0050568e08b3
GovWay-Message-ID: a8b1da40-aae9-4039-8a2c-cd000894f3bd

Grazie.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Il processo di comunicazione di gara deserta per i bandi soprasoglia è oggetto di evolutiva e verrà rilasciato con i prossimi changelog.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
