### ISSUE TITLE
ComunicaAppalto crea-appalto Errore 400

### ISSUE THREAD

**Issue by petromanco** [anticorruzione/npa#1583]
Quando viene richiamato l'e-service per creare l'appalto ricevo il seguente messaggio
{
    "status": 400,
    "title": "KO",
    "detail": "Argomenti di input non validi",
    "type": "about:blank"
}

di seguito il json che viene inoltrato all'e-service
{
    "_idScheda": "1bc589e1-6548-47bc-b540-af67292b4eaa",
    "codice": {
        "idTipologica": "codiceScheda",
        "codice": "AD2_25"
    },
    "versione": "1.0",
    "_stato": {
        "idTipologica": "statoScheda",
        "codice": "CONF"
    },
    "_dataCreazione": "2024-07-15T13:16:26.060822+02:00",
    "body": {
        "anacForm": {
            "stazioniAppaltanti": [
                {
                    "codiceFiscale": "12345678901",
                    "codiceAusa": "12345678901",
                    "codiceCentroCosto": "12345678901",
                    "funzioniSvolte": [
                        {
                            "idTipologica": "funzioniSvolte",
                            "codice": "3"
                        }
                    ],
                    "saTitolare": true
                }
            ],
            "appalto": {
                "codiceAppalto": "12345678901",
                "motivoUrgenza": {
                    "idTipologica": "motivoUrgenza",
                    "codice": "7"
                },
                "linkDocumenti": "",
                "relazioneUnicaSulleProcedure": false,
                "opereUrbanizzazioneScomputo": false,
                "datiBase": {
                    "oggetto": "Oggetto",
                    "oggettoMl": null
                },
                "datiBaseProcedura": {
                    "tipoProcedura": {
                        "idTipologica": "tipoProcedura",
                        "codice": "neg-wo-call"
                    },
                    "giustificazioniAggiudicazioneDiretta": null
                },
                "datiBaseStrumentiProcedura": null,
                "datiBaseSubappalti": null
            },
            "aggiudicazioni": [
                {
                    "lotIdentifier": "lotto-1asd",
                    "afferenteInvestimentiPNRR": false,
                    "acquisizioneCup": false,
                    "cupLotto": null,
                    "ccnl": "ccnl",
                    "categoria": {
                        "idTipologica": "categoria",
                        "codice": "FS"
                    },
                    "categoriaScorporabile": null,
                    "codIstat": {
                        "idTipologica": "codIstat",
                        "codice": "015063049"
                    },
                    "paritaDiGenereGenerazionale": null,
                    "quadroEconomicoStandard": {
                        "impLavori": 0.0,
                        "impServizi": 10000.25,
                        "impForniture": 0.0,
                        "impTotaleSicurezza": 0.0,
                        "ulterioriSommeNoRibasso": 0.0,
                        "impProgettazione": 0.0,
                        "sommeOpzioniRinnovi": 0.0,
                        "sommeRipetizioni": 0.0,
                        "sommeADisposizione": 10000.25
                    },
                    "quadroEconomicoConcessioni": null,
                    "partecipanti": [
                        {
                            "codiceFiscale": "11111111113",
                            "denominazione": "Imperium Solution Srls",
                            "ruoloOE": {
                                "idTipologica": "ruoloOE",
                                "codice": "3"
                            },
                            "tipoOE": {
                                "idTipologica": "tipoOE",
                                "codice": "1"
                            },
                            "idPartecipante": "f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
                            "paeseOperatoreEconomico": "ITALIA",
                            "paeseOperatoreEconomicoMl": null,
                            "avvalimento": false,
                            "importo": 10000.25,
                            "tipologiaAvvalimento": null
                        }
                    ],
                    "finanziamenti": null,
                    "datiBase": {
                        "oggettoContratto": {
                            "idTipologica": "oggettoContratto",
                            "codice": "services"
                        },
                        "oggetto": "OGGETTO DI TEST DEL CONTRATTO",
                        "oggettoMl": null
                    },
                    "datiBaseCPV": {
                        "tipoClassificazione": {
                            "idTipologica": "tipoClassificazione",
                            "codice": "cpv"
                        },
                        "cpvPrevalente": {
                            "idTipologica": "CPV",
                            "codice": "98341140"
                        },
                        "cpvSecondarie": null
                    },
                    "datiBaseContratto": null,
                    "datiBaseAggiudicazioneAppalto": {
                        "dataAggiudicazione": "2024-07-15T13:16:26.0618169+02:00"
                    },
                    "datiBaseAccessibilita": null,
                    "datiBaseDocumenti": {
                        "url": "https://sigeg.giustizia.it/Trasparenza",
                        "lingue": null
                    }
                }
            ]
        },
        "espd": ""
    }
}

C'è qualche campo che non è formattato correttamente?

Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>da un'analisi sui nostri sistemi il json inviato risulta formattato in maniera errata.</p>

<p> </p>

<p>A seguito di un test effettuato sul payload fornito, abbiamo riscontrato diversi campi obbligatori vuoti.</p>

<p>In allegato i file con il json formttato ed i dati vuoti ottenuti.</p>

<p> </p>

<p>Restiamo a disposizione</p>

<p>Cordiali saluti</p>
