### ISSUE TITLE
[TOSCANA/BOLZANO] - Errore Servizio esterno. Ricerca Documenti - Non Disponibile

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1584]
Salve,
abbiamo provato a richiamare il servizio "Richiesta-accesso-fvoe" e "verifica-richiesta-accesso-fvoe" per ottenere la chiaveAccesso, purtroppo senza successo, **abbiamo ricevuto semplicemente una pagina vuota**.

Quindi, abbiamo effettuato un tentativo utilizzando la **chiave accesso presente nello swagger,** per invocare il servizio **/ricerca-documenti-fvoe :**
<img width="530" alt="image" src="https://github.com/user-attachments/assets/4d072595-8862-41cd-a947-cc6a226229b2">
ma il servizio ha restituito il seguente errore:

**Risposta servizio /ricerca-documenti-fvoe**
 
{
   "status": 500,
   "title": "Operazione terminata con errore",
   "errori": [   {
      "id": "errori",
      "codice": "FVX15"
   }]
}

{
   "tipologica":    {
      "codice": "
FVX15
",
      "descrizione":       {
"it": "Errore Servizio esterno. Ricerca Documenti - Non Disponibile",

         "en": "Errore Servizio esterno. Ricerca Documenti - Non Disponibile"
      },
      "dataInizio": null,
      "dataFine": null
   },
   "instance": null,
   "status": 200,
   "title": "OK",
   "detail": "Operazione effettuata con successo",
   "type": "about:blank"
}

**1. Esistono scenari di test funzionanti?
2. Qual è la natura degli errori?**

**Comment by obigno77** [comment]
Potete indicare il CIG?

**Comment by UserM21** [comment]
Ecco:
{
  "dataInizioAutorizzazione": "2022-01-23T12:02:05Z",
  "operatoriEconomici": [
    {
      "codiceFiscale": "MFNFRC87D04H501C"
    },
    {
      "codiceFiscale": "80140110588"
    }
  ],
  "appalto": {
    "idAppalto": "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
  }
}

**Comment by obigno77** [comment]
Gli scenari di test funzionanti sono disponibili su https://github.com/anticorruzione/npa/blob/main/docs/scenari-di-esempio/gestione_fascicolo.md
Questo codice fiscale di operatore economico non è supportato per i test

**Comment by laurapavan** [comment]
Mi collego alla issue #1555, relativa appunto agli scenari disponibili su github che risultavano non funzionanti.
Quindi ora possiamo riprovare perchè sono stati sistemati? Grazie.
