### ISSUE TITLE
[CONSIP] Schede P2_XX REG106 - La regola non viene intercettata

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1585]
Salve,
è stata compilata la scheda P2_10 (la problematica è presente su tutte le schede P2 che prevedono la REG106) con le condizioni necessarie a far scattare la regola REG106:
some lotto in lotti satisfies lotto.datiBaseTerminiInvio.scadenzaPresentazioneInvito != null and lotto.datiBaseTerminiInvio.scadenzaPresentazioneInvito != "" and date and time(substring before(lotto.datiBaseTerminiInvio.scadenzaPresentazioneInvito, "Z")) &lt;= date and time(string(today()))
Nel dettaglio: "scadenzaPresentazioneInvito":"2024-07-15T15:00:00Z" > data corrente con orario antecedente

Tuttavia, la regola non viene riscontrata e vengono staccati i CIG.
Nel caso in cui si indica una data precedente a quella attuale, la regola viene riscontrata

In allegato il JSON trasmesso.
[P2_10REG106.txt](https://github.com/user-attachments/files/16236744/P2_10REG106.txt)

**Comment by anac-uscp** [comment]
<p>Salve,<br>
<br>
la regola è stata corretta in tutte le schede in cui è presente.</p>

<p>Alla fine della prossima settimana verrá rilasciata una fix risolutiva, pertanto invitiamo l'utente a riprovare dopo tale data.<br>
<br>
Saluti</p>
