### ISSUE TITLE
[CONSIP] Scheda P2_17 - REG1 - incoerenza tra la regola impostata sul DMN e il messaggio ricevuto. 

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1586]
Abbiamo notato la seguente incongruenza tra la regola descritta all'interno del DMN e la regola che riceviamo tramite REG1.

Dalle analisi eseguite risulta che:

**1) sul DMN per la scheda P2_17 è definita la seguente regola sull'attributo categorieMerceologiche:** 

<rule id="DecisionRule_P2_17_0018">
        <description>REG1: categoria merceologica: controllo di coerenza tra quelle indicate nei lotti e quelle indicate nell'appalto</description>
        <inputEntry id="UnaryTests_P2_17_0055">
          <text></text>
        </inputEntry>
        <inputEntry id="UnaryTests_P2_17_0056">
          <text>some lotto in lotti
satisfies (some categoria in lotto.categorieMerceologiche
satisfies list contains(appalto.categorieMerceologiche, categoria))</text>
        </inputEntry>
        <inputEntry id="UnaryTests_P2_17_0057">
          <text></text>
        </inputEntry>
        <outputEntry id="LiteralExpression_P2_17_0019">
          <text>"{\"idTipologica\":\"errori\",\"codice\":\"REG1\"}"</text>
        </outputEntry>
      </rule> 
      
      **La regola si applica quando almeno una CatMer nel lotto appartiene anche alla CatMer indicata nell'appalto.**
      Per questo motivo viene riscontrato il problema

**Per questo motivo viene riscontrato il problema

2) Nel file errori.json da cui viene recuperata la descrizione per REG1 viene invece indicato** 
{
    "codice":"REG1",
    "descrizione": {
        "it": "La categoria merceologica indicata nei lotti non e' compresa tra quelle indicate nell'appalto",
        "en": "La categoria merceologica indicata nei lotti non e' compresa tra quelle indicate nell'appalto"
    },
    "dataInizio":null,
    "dataFine":null
}

**Di conseguenza non c'è coerenza tra la regola impostata sul DMN e il messaggio ricevuto.** 

è possibile avere un riscontro in merito a tale analisi, grazie.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>è stata rilasciata una fix risolutiva per la problematica riscontrata.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p> </p>

<p>Cordiali saluti.</p>
