### ISSUE TITLE
Quadro economico schede A

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1587]
Buongiorno,

non è chiaro se il quadro economico richiesto in fase di aggiudicazione dovrebbe essere riferito agli importi i aggiudicazione o deve essere riferito ai valori del lotto indicati dalla SA (in questo caso non sarebbero sempre gli stessi mandati con la scheda di indizione della procedura?.

Grazie

**Comment by obigno77** [comment]
E' riferito ai valori di aggiudicazione
