### ISSUE TITLE
[CONSIP] Scheda S1 - REG0 - Dati non presenti

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1588]
Salve,
volendo intercettare eventuali validazioni dei campi prima della sottomissione della scheda, sono state applicate le regole previste per ciascuna scheda all'interno dei dmn.
Nel dettaglio, per la scheda S1 scatta la regola bloccante **REG0 - Dati non presenti**.

La condizione per cui scatta la regola è che soggettiInteressati sia null.
La regola valuta soggettiInteressati come variabile di contesto (cioè il padre di tutto l'oggetto), ma siccome il padre dell'oggetto è elencoSoggettiRichiedenti per la regola soggettiInteressati è null.

E' possibile una verifica sulla correttezza sintattica della regola? 
Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>PCP utilizza un estrattore che prende i dati della scheda e li mappa in variabili di input per la regola.</p>

<p>Nel caso della scheda S1 estrae come oggetto di input alla regola dmn l'elenco contenuto in soggettiInteressati e non il padre.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
