### ISSUE TITLE
[CONSIP] - Schede P7_1_*    Non viene intercettata nessuna regola di validazione per le schede di indizione P7_1_*

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1590]
Ciao,
abbiamo notato la seguente anomalia.
Non viene intercettata nessuna regola di validazione quando si effettua la richiesta del cig per le schede di indizione P7_1_*

Esempio di la regola non intercettata per la scheda P7_1_1 :
 **REG_4** <description>REG4_2: Tipologica motivazioneCIG: la motivazione è richiesta solo se la categoria merceologica è diversa dal valore "Lavori oppure beni e servizi non elencati nell'art. 1 dPCM 24 dicembre 2015". Se la categoria merceologica è "Lavori oppure beni e servizi non elencati nell'art. 1 dPCM 24 dicembre 2015" allora Motivazione Richiesta Cig è null.</description>
        <inputEntry id="UnaryTests_07qrgaw">
          <text>is defined(appalto.motivazioneCIG) and ((appalto.motivazioneCIG.codice != null) and (some categoriaMerceologica in appalto.categorieMerceologiche satisfies categoriaMerceologica.codice = "999"))</text>

**Rispettando tutte le condizioni la regola non viene intercettata quando si effettua la richiesta del Cig**
**Tale anomalia avviene per tutte le regole delle schede P7_1_***

Di seguito i dati della segnalazione:
Id_appalto: 3b9640e2-5637-467b-94af-d163670faf9d
 
[blob_anac_form_90947.txt](https://github.com/user-attachments/files/16269292/blob_anac_form_90947.txt)

Potete verificare per piacere?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Grazie per la segnalazione. </p>

<p>Abbiamo provveduto ad inserire la fix nel changelog 02 che andrà in esercizio in data 24-10.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
