### ISSUE TITLE
[CONSIP] - Schede M2*    Non viene intercettata nessuna regola di validazione per le schede M2*

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1591]
Ciao,
abbiamo notato la seguente anomalia.
Non viene intercettata nessuna regola di validazione quando si effettua la richiesta del cig per le schede di post pubblicazione M2*

Esempio di la regola non intercettata per la scheda M2
 REG_54:
'' Selezionare un motivo di revisione prezzi''

modificaContrattuale.datiBaseModificaContrattuale != null and modificaContrattuale.datiBaseModificaContrattuale != "" and modificaContrattuale.datiBaseModificaContrattuale.motiviModifica.codice = "mod-rev" and (modificaContrattuale.motivoRevisionePrezzi = null or modificaContrattuale.motivoRevisionePrezzi = "" or modificaContrattuale.motivoRevisionePrezzi.codice = null or modificaContrattuale.motivoRevisionePrezzi.codice = ""

Rispettando tutte le condizioni la regola non viene intercettata quando si effettua la richiesta del Cig
Tale anomalia avviene per tutte le regole delle schede M2

Di seguito i dati della segnalazione:
4449d2c6-e45b-49bf-a86b-af866c97d20f
[blob_anac_form_83521.txt](https://github.com/user-attachments/files/16269403/blob_anac_form_83521.txt)

Potete verificare per piacere?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>le riferiamo che saranno migliorate le regole DMN relative alle schede M, e sarà rilasciata una fix successivamente.<br>
<br>
Restiamo a disposizione.<br>
<br>
Cordiali saluti</p>
