### ISSUE TITLE
Centro di costo non coerente con anagrafe AUSA

### ISSUE THREAD

**Issue by giovanni-caprilli** [anticorruzione/npa#1592]
Salve,
siamo riusciti ad effettuare delle chiamate all'e-service PCP - Comunica appalto e stiamo effettuando dei test sfruttando l'esempio pubblicato [qui](https://github.com/anticorruzione/npa/blob/main/docs/scenari-di-esempio/appalto_ordinario_sopra_soglia.md).

Abbiamo inserito i dati della SA che ci è stata fornita via e-mail con i dati di test (codice fiscale e codice AUSA).

Al momento riceviamo un errore **ERR69** relativo al fatto che "il centro di costo SA presente nella lista delle stazioni appaltanti non è coerente con l'anagrafe AUSA".

Come dobbiamo procedere?
Ci dovete fornire voi questo dato aggiuntivo o dobbiamo inserirlo/ottenerlo noi tramite delle operazioni specifiche?

Grazie

**Comment by jcapri** [comment]
Salve, siamo impossibilitati a proseguire i test.

Abbiamo attivato la fruizione dell'e-service "AUSA - Anagrafe Unica delle Stazioni Appaltanti" per cercare di renderci autonomi nel reperimento dei centri di costo associati all'anagrafica della SA di test, ma non c'è stata approvata ancora la richiesta relativa alla finalità da collegare al client.

Potreste comunicarci il dato mancante o permetterci di recuperarlo in autonomia abilitando la finalità specifica?

Grazie

**Comment by giovanni-caprilli** [comment]
Salve, siamo impossibilitati a proseguire i test.

Abbiamo attivato la fruizione dell'e-service "AUSA - Anagrafe Unica delle Stazioni Appaltanti" per cercare di renderci autonomi nel reperimento dei centri di costo associati all'anagrafica della SA di test, ma non c'è stata approvata ancora la richiesta relativa alla finalità da collegare al client.

Potreste comunicarci il dato mancante o permetterci di recuperarlo in autonomia abilitando la finalità specifica?

Grazie

**Comment by giovanni-caprilli** [comment]
Salve, a seguito dell'attivazione della finalità relativa all'e-service "AUSA - Anagrafe Unica delle Stazioni Appaltanti" abbiamo reperito il dato tramite le API in ambiente di collaudo.
Grazie
