### ISSUE TITLE
FVOE ConsultaStoricoOEResponse - modello non coerente con le risposte effettive delle API

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1593]
Le specifiche (recuperabili a questo url https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/specifiche-servizi-fvoe-fva.yaml) del modello in oggetto non sono coerenti con le risposte che si ottengono dai servizi online (sia produzione che sviluppo).

Nello specifico la response in questione riporta queste specifiche:
![image](https://github.com/user-attachments/assets/2a5a52ea-c209-4934-995f-25440159e4da)

mentre i servizi rispondono con un modello molto più scarno e con properties differenti. 
Riportiamo di seguito un esempio del modello in questione:

```
{
  "status": 200,
  "title": "Operazione terminata correttamente",
  "documenti": [
    {
      "idDocumento": "60b91ada-5a4c-XXXXXXXX",
      "azione": {
        "codice": "01"
      },
      "utenteCreazione": "12345678",
      "dataCreazione": "9999-06-21T14:01:11.070Z",
      "statoComprova": {
        "id": "statoComprova",
        "codice": "001"
      },
      "statoUtilizzo": {
        "id": "statoUtilizzo",
        "codice": "001"
      }
    }
  ]
}
```

Qual è il modello corretto? La documentazione verrà aggiornata?
Come possiamo implementare questi servizi se la documentazione a supporto è così carente?

**Comment by anac-uscp** [comment]
<p>Gentile Utente,</p>

<p> </p>

<p>Il modello corretto da seguire è presente sul sito istituzionale NPA/anticorruzione di ANAC, nelle specifiche-interfacce sono definite le operazioni. </p>

<p>Le informazioni ricevute possono cambiare a seconda del servizio richiamato, cambiando anche la struttura del modello. </p>

<p>La documentazione verrà aggiornata in futuro, con gli ultimi aggiornamenti. </p>

<p> </p>

<p> </p>

<p>Restiamo a disposizione</p>

<p> </p>

<p>Cordiali Saluti</p>
