### ISSUE TITLE
FVOE a seguito di modifiche e ripristino Funzionalità - Mancato Funzionamento per delegati RP

### ISSUE THREAD

**Issue by SoricchioHRS** [anticorruzione/npa#1594]
Con riferimento al paragrafo 5 del documento Specifiche Servizi, [https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md] dal modulo PCP, in caso di delega di funzioni, non si riesce a visualizzare nella propria interfaccia di RP, l'appalto di cui ci si deve occupare per la relativa fase dell'affidamento.
Si rammenta che in base all'estratto della tabella che segue:
 
![DRPFVOE](https://github.com/user-attachments/assets/2c263a89-7c19-4564-a98c-b2bd1fc0af1d)
i responsabili di Fase dovrebbero poter effettuare le proprie attività durante tutta la durata dell'affidamento, sopratutto quando la essi seguono la fase esecutiva dell'appalto stesso.

Si prega, pertanto, di ripristinare le funzioni di delega di funzioni così come disciplinate anche dal vigente codice (art. 15 del d. lgs. n. 36/2023) e dall'allegato I.2.
Cordiali saluti.

**Comment by obigno77** [comment]
Si rinvia al comunicato https://www.anticorruzione.it/-/indicazioni-transitorie-sulla-profilazione-dei-responsabili-di-fase-nei-sistemi-informatici-anac

**Comment by SoricchioHRS** [comment]
Nel ringraziare per la risposta si segnala, tuttavia, che pur essendo il sottoscritto afferente al medesimo centro di costo dei Responsabili di Progetto delle Stazioni Appaltanti deleganti le funzioni di Responsabili Fase, non riesce ad operare, nè riesce più a visualizzare i fascicoli per le fasi successive dell'affidamento, disattendendo la delibera ANAC di cui al link https://www.anticorruzione.it/-/delibera-n.-262-del-20-giugno-2023-provvedimento-art.-24-fvoe di attuazione dell'art. 24.

In attesa di cortese riscontro, sono a porgere cordiali saluti.
