### ISSUE TITLE
[CONSIP] - Scheda CM2 - La REG103 referenzia un campo non previsto dal modello dati della scheda

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1595]
Salve,
al fine di far scattare la REG103 sulla scheda CM2 è necessario rispettare le seguenti condizioni:
comunicazione.importo != null and comunicazione.importo > 0
nuovoImportoTotale > 5000

Tuttavia, il campo nuovoImportoTotale non è previsto dal modello dati della scheda CM2
![image](https://github.com/user-attachments/assets/2bda8122-5d9e-47ad-b8d8-a5791ac2adbd)

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>il campo nuovoImportoTotale è un campo che PCP calcola e invia al motore DMN per verificare il requisito che l'importo totale della scheda non superi i 5000 euro.</p>

<p>Si conferma che non è un campo presente nel modello dati ma calcolato per la verifica della regola.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
