### ISSUE TITLE
[CONSIP] - Scheda P3_3, P3_4 - REG37 e REG38 referenzia un campo non previsto dal modello dati della scheda 

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1597]
Salve,
1. al fine di far scattare la REG37 sulla scheda P3_3/P3_4 è necessario rispettare le seguenti condizioni:
some lotto in lotti
satisfies lotto.opzioniRinnovi and (lotto.quadroEconomicoStandard.sommeOpzioniRinnovi = null or lotto.quadroEconomicoStandard.sommeOpzioniRinnovi = 0)

Tuttavia, i campi lotto.opzioniRinnovi e lotto.quadroEconomicoStandard.sommeOpzioniRinnovinon non sono previsti dal modello dati della scheda

2.al fine di far scattare la REG38 sulla scheda P3_3/P3_4 è necessario rispettare le seguenti condizioni:
some lotto in lotti
some lotto in lotti
satisfies lotto.ripetizioniEConsegneComplementari and (lotto.quadroEconomicoStandard.sommeRipetizioni = null or lotto.quadroEconomicoStandard.sommeRipetizioni = 0)

Tuttavia, il campo lotto.ripetizioniEConsegneComplementari non è previsto dal modello dati della scheda

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>La segnalazione è corretta, la regola verrà eliminata da entrambe le schede.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
