### ISSUE TITLE
[CONSIP] - Scheda A1_30/31/32/ 33/ 34/35/A2.29/35 - La REG68 referenzia un campo non previsto dal modello dati della scheda 

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1598]
Salve,
al fine di far scattare la REG68 sulla scheda A1_32 è necessario rispettare le seguenti condizioni:
appalto.datiBaseProcedura != null and appalto.datiBaseProcedura.tipoProcedura != null and (appalto.datiBaseProcedura.tipoProcedura.codice != "neg-wo-call" and appalto.datiBaseProcedura.tipoProcedura.codice != "" ) and (appalto.datiBaseProcedura.giustificazioniAggiudicazioneDiretta!= null and appalto.datiBaseProcedura.giustificazioniAggiudicazioneDiretta!= "")

Tuttavia, i campi non sono previsti dal modello dati della scheda

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Il parametro di ingresso è denominato come l’analogo campo di $.anacForm e deve essere valorizzato con il dato proveniente dal medesimo campo anacForm in caso di schede non contenenti eform o dal tag xml equivalente in caso di presenza della eForm.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
