### ISSUE TITLE
[CONSIP] - Scheda A1.30/31/32/33/34/35/36 - La REG33 referenzia un campo non previsto dal modello dati della scheda #1596

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1599]
Salve,
al fine di far scattare la REG33 sulla scheda A1_32 è necessario rispettare le seguenti condizioni:
some aggiudicazione in aggiudicazioni
satisfies aggiudicazione.datiBaseAccessibilita.accessibilita.codice = "n-inc-just" and (aggiudicazione.datiBaseAccessibilita.giustificazione = null or aggiudicazione.datiBaseAccessibilita.giustificazione ="")

Tuttavia, i campi non sono previsti dal modello dati della scheda

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Il parametro di ingresso è denominato come l’analogo campo di $.anacForm e deve essere valorizzato con il dato proveniente dal medesimo campo anacForm in caso di schede non contenenti eform o dal tag xml equivalente in caso di presenza della eForm.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
