### ISSUE TITLE
Crea-appalto

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#16]
il servizio crea-appalto prevede come obbligatorio eform e ESPD, ma in realtà essi saranno disponibili solo in un momento successivo, si ritiene che debbano essere opzionali e che l'ANAC form debba contenere un set minimale di dati perché siamo nelle fasi iniziali della creazione della gara

**Comment by supportoAnac** [comment]
Con l'aggiornamento rilasciato in data 8/6/2023 la scheda in input al servizio crea-appalto diventa facoltativa. Qualora però la scheda fosse passata in input, il servizio verificherà l'obbligatorietà degli attributi interni (anacForm, eform, espd) secono lo schema delle regole di orchestrazione delle schede consultabile nella cartella "orchestratore".
