### ISSUE TITLE
Quesiti ambiente di prequalifica

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#160]
Buongiorno,
avrei due quesiti sull'argomento:

1. Esiste un WADL da caricare negli strumenti di test per i servizi di NPA
2. è necessario comunque acquisire voucher PDND anche nella fase di prequalifica

Grazie per il supporto

Francesco

**Comment by supportoAnac** [comment]
1) Esistono specifiche OpenAPI 3.0.x  da cui è possibile generare server e client per i servizi pubblicati.
2) L'unico modo per accedere ai servizi di test è attraverso PDND.

**Comment by federicodemarco** [comment]
Buongiorno in merito al punto 2, fino a quando la checklist non verrà pubblicata, il privato non potrà qualificarsi e pertanto non avrà accesso agli ambienti di test. 

Ne consegue: 

- confermate che al momento per i privati non è disponibile ancora la checklist necessaria alla certificazione alla PDND.
In caso di risposta affermativa quando è prevista la pubblicazione della checklist?
