### ISSUE TITLE
[CONSIP] - Scheda AD1_25 - La REG32/33/35/36 referenzia un campo non previsto dal modello dati della scheda

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1600]
Salve, 
1. al fine di far scattare la REG32 sulla scheda AD1_25 è necessario rispettare le seguenti condizioni: 
some aggiudicazione in aggiudicazioni
satisfies aggiudicazione.datiBase.oggettoContratto.codice = "services" and (aggiudicazione.quadroEconomicoStandard.impServizi = null or aggiudicazione.quadroEconomicoStandard.impServizi = 0)
Tuttavia, il campo  non è previsto dal modello dati della scheda

2. al fine di far scattare la REG33 sulla scheda AD1_25 è necessario rispettare le seguenti condizioni: 
some aggiudicazione in aggiudicazioni
satisfies aggiudicazione.datiBaseAccessibilita.accessibilita.codice = "n-inc-just" and (aggiudicazione.datiBaseAccessibilita.giustificazione = null or aggiudicazione.datiBaseAccessibilita.giustificazione ="")
Tuttavia, il campo  non è previsto dal modello dati della scheda

3. al fine di far scattare la REG35 sulla scheda AD1_25 è necessario rispettare le seguenti condizioni: 
some aggiudicazione in aggiudicazioni
satisfies aggiudicazione.datiBase.oggettoContratto.codice = "services" and (aggiudicazione.quadroEconomicoStandard.impServizi = null or aggiudicazione.quadroEconomicoStandard.impServizi = 0)
Tuttavia, il campo  non è previsto dal modello dati della scheda

4. al fine di far scattare la REG36 sulla scheda AD1_25 è necessario rispettare le seguenti condizioni: 
some aggiudicazione in aggiudicazioni
satisfies aggiudicazione.datiBase.oggettoContratto.codice = "supplies" and (aggiudicazione.quadroEconomicoStandard.impForniture = null or aggiudicazione.quadroEconomicoStandard.impForniture = 0)
Tuttavia, il campo  non è previsto dal modello dati della scheda

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Il parametro di ingresso è denominato come l’analogo campo di $.anacForm e deve essere valorizzato con il dato proveniente dal medesimo campo anacForm in caso di schede non contenenti eform o dal tag xml equivalente in caso di presenza della eForm.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
