### ISSUE TITLE
Servizio modifica avviso - schede di postpubblicazione

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1602]
Buongiorno,

per le schede di aggiudicazione con avvisi a livello europeo è utilizzabile la funzione di modifica avviso (es A1_29)?

Grazie

**Comment by anac-uscp** [comment]
<p>Salve,<br>
<br>
la funzione di modifica avviso é utilizzabile per tutti i tipi di avviso, purché quest'ultimo si trovi in attesa di pubblicazione.</p>

<p>Saluti</p>
