### ISSUE TITLE
[Maggioli] AD3 : Affidamento diretto Accordo Quadro "MULTI-AGGIUDICATARIO"

### ISSUE THREAD

**Issue by laurapavan** [anticorruzione/npa#1603]
Facendo riferimento al Comunicato ANAC del 5 giugno 2024, si pongono i seguenti quesiti inerenti la gestione di accordi quadro multiaggiudicati mediante affidamento diretto (si prenda, ad esempio, la scheda AD3)

- riferendoci alla Issue #1535, si segnala che l'informazione "Strumenti per lo svolgimento della procedura", seppur valorizzata nei nostri gestionali, non è prevista nell'XML della scheda AD3 e di fatto non viene trasferita in fase di richiesta CIG. Come dev'essere inviata?

- come previsto da normativa e ripreso nel vostro comunicato, l'accordo quadro può prevedere un confronto competitivo ed una pletora di aggiudicatari: come è possibile trasferire l'informazione di più partecipanti e/o più aggiudicatari nella scheda AD3 dato che esiste il vincolo tale per cui deve essere presente un solo tag IdPartecipante (che dev'essere anche l'aggiudicatario)?

la REG100 associata alla scheda prevede infatti questa regola:

some aggiudicazione in aggiudicazioni satisfies count(distinct values(aggiudicazione.partecipanti.idPartecipante))>1

Rimaniamo in attesa di indicazioni.
Grazie e saluti.

**Comment by laurapavan** [comment]
Buongiorno, 
integriamo quanto detto ieri dopo aver preso visione dell'ultimo comunicato aggiornato ANAC su questo tema, datato 10 luglio e pubblicato negli ultimissimi giorni.

Le schede AD2_25/26/27 citate nel comunicato prevedono il campo datiBaseStrumentiProcedura in cui indicare che si tratta di un AQ, **ma NON permettono comunque di gestire la multi-aggiudicazione i**n quanto prevedono tutte la REG100.

Si rinnova quindi la domanda come segue: quale/i schede vanno usate per un accordo quadro in affidamento diretto a più aggiudicatari?

Restiamo in attesa di indicazioni.
Grazie e saluti.

**Comment by anac-uscp** [comment]
<p><span style="font-size:11.0pt;"><span style='font-family:"Calibri",sans-serif;'><span style="color:#1f497d;">Al momento, nelle schede AD1, AD2 e AD3 non è possibile comunicare multiaggiudicatari in quanto è stata considerata, quale ipotesi ordinaria, la possibilità di affidare in via diretta Accordi Quadro ad un solo operatore.</span></span></span></p>

<p><span style="font-size:11.0pt;"><span style='font-family:"Calibri",sans-serif;'><span style="color:#1f497d;">Con l'occasione, al fine di poter effettuare una più completa disamina, si chiede di rappresentare eventuali specifiche fattispecie che possano comportare l'affidamento diretto di Accordi quadro a più soggetti, ovviamente senza successivo confronto competitivo.</span></span></span><br>
<span style="font-size:11.0pt;"><span style='font-family:"Calibri",sans-serif;'><span style="color:#1f497d;">Successivamente al riscontro, potrà essere valutata la possibilità di modificare le schede prevedendo i multiaggiudicatari.</span></span></span></p>

<p> </p>
