### ISSUE TITLE
[BLK] - Centri di costo non allineati con Ricerca AUSA

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#1605]
Invocando il servizio di ricerca ausa con il metodo get_by_codice_fiscale non otteniamo nel risultato tutti i centri di costi che invece vengono mostrati attraverso la ricerca con il seguente portale:
https://servizi.anticorruzione.it/portal/classic/Servizi/RicercaVerificaAttestatoAUSA

Di solito dopo che una SA aggiunge un nuovo centro di costo questo non è immediatamente disponibile attraverso il servizio di ricerca ma di solito nel giro di una giornata lavorativa il tutto viene allineato.

Ora ci troviamo con alcuni centri di costo che non vengono allineati e quindi non sono mai disponibili dall'api.

Le altre piattaforme hanno riscontrato questa anomalia?

**Comment by obigno77** [comment]
Parliamo di esercizio? E' possibile avere dei casi?

**Comment by matteolaltrelli** [comment]
Ho aperto un ticket al supporto: richiesta di assistenza n°[##55960] 
il codice fiscale che stiamo utilizzando è 90138150736

**Comment by matteolaltrelli** [comment]
@obigno77, verificato ora ed il centro di costo che serviva alla Stazione Appaltante ora è comparso, ad ogni modo è possibile sapere i tempi di allineamento min/max del servizio in modo da dare delle tempistiche alle SA quando i centri di costo creati sono disponibili alla consultazione attraverso l'api?
Grazie

**Comment by obigno77** [comment]
L'anagrafe AUSA viene allineata entro 15 minuti. Il ritardo è derivato da un disservizio temporaneo
