### ISSUE TITLE
Gestione S4 - Sembra che una volta confermata se c'è un contratto sia obbligatorio fare la CO1

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#1606]
La scheda S4 può essere fatta 
1.	prima della SC1 
2.	dopo la SC1
Nel primo caso non c’è problema ma mi chiedo nel secondo caso il seguente scenario come deve essere gestito:

Faccio una SC1 con tre CIG (SC1 accetta un array di CIG)
Poi faccio una S4 con un CIG dei tre (S4 accetta solo il singolo CIG)
Come devo procedere con il contratto che ho staccato con la SC1 che ha tre CIG e solo di uno ho variato gli aggiudicatari (idpartecipante).

Devo fare la CO1 e poi rifare due SC1:
1 con i due CIG con il primo partecipante
1 con il CIG con il nuovo partecipante

Oppure devo rifare solo una SC1 con il CIG con il nuovo partecipante e la vecchia SC1 continua normalmente?

**Comment by anac-uscp** [comment]
<p>Buongiorno,<br>
<br>
La scheda S4 è utilizzabile per le variazioni anagrafiche dell'aggiudicatario in qualunque momento successivo all'aggiudicazione e fino al momento della conclusione del contratto.<br>
Prima della sottoscrizione del contratto è possibile che i componenti di un raggruppamento aggiudicatario costituiscano una unica società di scopo o consortile.<br>
Dopo la sottoscrizione del contratto, la scheda può essere utilizzata anche per notificare le variazioni dei soggetti che fanno parte del raggruppamento.<br>
<br>
La scheda SC1 può essere collegata a più CIG, solo nei casi in cui sono stati assegnati più lotti della stessa gara al medesimo operatore economico.<br>
In questo caso, il sistema prevede la possibilità di eleggere il cosiddetto CIG "Master",  che potrà essere utilizzato come riferimento unico per i flussi delle schede successive.<br>
<br>
<br>
<br>
<br>
 </p>
