### ISSUE TITLE
[CONSIP - FVOE] - Regular expression codici catastali nazioni - Tipo_richiesta DatiSA00050

### ISSUE THREAD

**Issue by LuigiScortichino** [anticorruzione/npa#1608]
Buon pomeriggio,

vi contattiamo per segnalare una incongruenza che abbiamo riscontrato nelle specifiche del nuovo endpoint /richiedi-documenti 
in ambiente di qualificazione (https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti).

In particolare sulla validazione che viene applicata al campo LuogoNascitaSoggetto del tipo_richiesta DatiSA00050, viene applicato il seguente pattern ^(([A-M]\d{3}$)|Z\d{2}[1-9]) che dovrebbe contemplare i codici catastali dei comuni italiani ed i codici catastali degli stati esteri. Questo pattern, però, scarta tutti le nazioni il cui il codice catastale termina per 0: in totale abbiamo contato 25 stati, tra cui Albania (Z100), Afghanistan (Z200), Argentina (Z600), Francia (Z110), che però sono compresi nel json indicato nelle specifiche con l'elenco delle possibili nazioni da utilizzare raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/tipologiche/tipoCatastoStato.json

Quale tra l'elenco delle nazioni fornito in documentazione e la regular expression deve ritenersi valida? 

Grazie mille.

**Comment by obigno77** [comment]
Lo yaml è stato fixato. L'aggiornamento sarà disponibile sui 3 ambienti PDND entro la giornata di oggi
