### ISSUE TITLE
[SOGEI] COLLAUDO - Servizi comuni - Errore 400

### ISSUE THREAD

**Issue by NicolaOrritos** [anticorruzione/npa#1609]
Alla chiamata dell'endpoint "/esito-operazione" con i seguenti parametri riceviamo un errore **400 Bad Request**.
Questo il dettaglio della request:
`GET https://apigw-test.anticorruzione.it/modi/rest/ServiziComuni/v2/esito-operazione?idAppalto=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&tipoOperazione=AP_CREA&tipoRicerca=TUTTI_ESITI`

Questo il dettaglio della response:
```JSON
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    
    "govway_id": "221b63e0-49c5-11ef-8dc0-0050568e08b3"
}
```

Questi i parametri utilizzati per la creazione del token (alcuni sono stati oscurati per motivi di privacy/sicurezza):
```JSON
{
  "userCodiceFiscale":    "RxxxxxxxxxxxxxW",
  "userRole":             "RP",
  "userLoa":              3,
  "userIdpType":          "SPID",

  "businessFlowID":       "945e5712-810b-4d10-ae3e-c0f242b33517",

  "SAcodiceAUSA":         "9000000008",
  "SACodiceFiscale":      "05359681003",

  "regCodicePiattaforma": "0000008",
  "regCodiceComponente":  "0000001"
}
```

**Comment by matteolaltrelli** [comment]
Credo che l'errore ci sia anche in esercizio sul crea_appalto etc.

**Comment by lucaCorigliano-SA** [comment]
Ciao, per assurdo `userLoa` deve essere una stringa contenente un numero.

**Comment by obigno77** [comment]
Validazione security token ModI 'AUDIT' della richiesta fallita: [GOVWAY-101] [Header 'Agid-JWT-TrackingEvidence'] Token con claim 'userLoa' non valido: Invalid format value '3'; expected string type, found 'com.fasterxml.jackson.databind.node.IntNode'
