### ISSUE TITLE
Cancellazione Appalto in caso di multilotto

### ISSUE THREAD

**Issue by ferdinandjmaddela** [anticorruzione/npa#161]
Dopo aver creato un appalto con più di un lotto, ho la necessità di cancellarne uno.

Con il WSDL di Simog esiste il servizio "cancellaLotto", ora come avviene? Essendo una modifica, deve essere invocato il "modifica-appalto"?

**Comment by supportoAnac** [comment]
Fino a quando non viene confermato, l'appalto è modificabile tramite il sevizio /modifica-appalto. Una volta confermato, può essere annullato o rettificato tramite la procedura prevista dal TED.
