### ISSUE TITLE
[Toscana/Bolzano] - Richiesta chiarimenti su partecipanti A3_6 e AD5

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1613]
Salve,
in merito alla issues #1112 volevo chiedere chiarimenti sulle A3_6 e AD5 le quali nel modello dati attuale di queste schede
non sono previsti i campi RuoloOE e TipoOE.

E' corretto? In caso di raggruppamenti di partecipanti non è possibile specificare i ruoli? 

Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Per la scheda A3_6 sembrerebbe difficile ipotizzare un raggruppamento di partecipanti. </p>

<p>Per la scheda AD5, è in pianificazione il rilascio di una nuova scheda SIM (scheda S per l'Indagine di Mercato/Manifestazione di interesse), da usare a monte di tutte le tipologie di affidamento diretto/negoziate, opzionale, che preveda anche una scheda di terminazione qualora i controlli abbiano esito negativo e non si pervenga all'affidamento o si decida di non proseguire nelle procedure di affidamento (STEV - Scheda di terminazione delle verifiche FVOE)<br>
<strong>La SIM non porta all'identificazione di alcun OE aggiudicatario.</strong></p>

<p>La scheda SIM ha lo stesso contenuto della scheda S1 ad eccezione del campo CIG e non attribuisce CIG.</p>

<p>La SA che vuole attivare l’FVOE invia la nuova scheda SIM (Scheda per l’indagine di mercato senza attribuzione del CIG), con l’anagrafica di uno o più OE che hanno risposto alla manifestazione di interesse. Successivamente ai controlli, provvede all’invio della scheda AD1, AD2, AD3, AD5 per l'affidamento diretto o la scheda P7_2 per la negoziata senza bando, con le informazioni già presenti ed ottiene il CIG.</p>

<p>La SIM potrebbe dare avvio ad un nuovo flusso. Le schede che possono seguire la SIM sono: AD1_29, AD1_30, AD1_31, AD1_32, AD2_29, AD2_30, AD2_31, AD2_32 AD3, AD5, P7_2.</p>

<p>La SA che non intende attivare l’FVOE, in sede di indagine di mercato, per i controlli esplorativi, invia direttamente una scheda AD1, AD2, AD3, AD5 o P7_2 ed ottiene il CIG. </p>

<p>Qualora si comunicasse direttamente l'AD5, si sta valutando l'opportunità di introdurre i dati mancanti.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
