### ISSUE TITLE
[Consip][BLK] 400 - argomenti di input non validi

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1614]
Salve,
da questa mattina riscontriamo l'errore seguente sulla chiamata crea-appalto (abbiamo provato su diverse schede):
400 Bad Request: "{"status":400,"title":"KO","detail":"Argomenti di input non validi","type":"about:blank"}" 

potete verificare?
GovWay-Message-ID:"c2dfd023-5c7b-4776-a6ec-641b5ba35ba2"
GovWay-Transaction-ID:"184e5bfc-4b50-11ef-8dc0-0050568e08b3"

**Comment by obigno77** [comment]
Il problema è stato risolto
