### ISSUE TITLE
[Maggioli] Data stipula e data esecutività contratto

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#1615]
La data stipula e la data di esecutività di un contratto sono nella scheda SC1, ma anche nella CO1.
Come mai questa duplicazione? In quale caso vanno valorizzate nella CO1?

Grazie

**Comment by anac-uscp** [comment]
<p>Le informazioni sulla data stipula e la data di esecutività vanno comunicate appena disponibili, e quindi indicativamente tramite la SC1.</p>

<p>Vi sono alcuni casi specifici in cui tali date possono non essere note al momento della sottoscrizione: in questi casi è possibile differire la comunicazione di tali date al momento della conclusione dei lavori, quindi tramite la CO1.<br>
 <br>
 </p>
