### ISSUE TITLE
[ARIA SpA] "ERR94: errore generico durante la comunicazione con PVL" in fase di aggiudicazione

### ISSUE THREAD

**Issue by lmanc77** [anticorruzione/npa#1621]
Si segnalano problemi in fase di aggiudicazione, in quanto viene restituito errore "ERR94: errore generico durante la comunicazione con PVL".

idAppalto su cui si riscontra l'errore: 650db387-dcc0-4ace-bc98-e1bd86d01db6

Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>In data 06-09-24 verrà rilasciata la fix che risolve la problematica riscontrata.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>

<p> </p>

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>In data 06-09-24 verrà rilasciata la fix che risolve la problematica riscontrata.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>

<p> </p>
