### ISSUE TITLE
[BLK][Maggioli][Riapertura #1543] Problemi nell'operazione 'ricerca-appalto': record assenti

### ISSUE THREAD

**Issue by ManuelBridda** [anticorruzione/npa#1623]
Come da titolo, riapro la segnalazione della issue #1543 

In merito alla stessa, non abbiamo alcuna evidenza che il comportamento della 'ricerca-appalto' sia cambiato rispetto al 27 giugno (data di apertura della precedente issue). 
Metto cioè in discussione la vostra affermazione "_Da un test effettuato nei nostri ambienti il ricerca-appalto funziona correttamente._": un test andato a buon fine non è sintomo del corretto funzionamento del servizio.

Vi fornisco, a dimostrazione della persistenza dell'errore, un caso appena generato in cui la chiamata restituisce 12/20 risultati ("totRows": 39,"totPages": 2, "currentPage": 1,  "elementPage": 12): "govwayTransactionId": "cc415fa2-4f32-11ef-bd08-0050568e9679",

Aggiungo inoltre un caso eclatante della 'ricerca-appalto' per codice CIG (I00032608F) che restituisce "totRows": 1 e "result": []
```json
{
    "done": "Y",
    "validationErrors": null,
    "internalErrors": null,
    "anacErrors": null,
    "govwayMessageId": "0b68d1b3-2e7e-4bee-beb4-b75a7e4f0889",
    "govwayTransactionId": "b8ab4078-4f30-11ef-8dc0-0050568e08b3",
    "cartId": null,
    "data": {
        "instance": null,
        "status": 200,
        "title": "OK",
        "detail": "Operazione eseguita con successo",
        "type": "about:blank",
        "totRows": 1,
        "totPages": 1,
        "currentPage": 1,
        "elementPage": 0,
        "result": []
    }
}
```

Nella issue precedente sono comunque elencati tutti i govwayTransactionId necessari per i vostri controlli, vi invito quindi a eseguire le opportune verifiche senza chiudere frettolosamente le issue.

Grazie

**Comment by lelio-raffaelli** [comment]
Buongiorno, faccio notare che la stessa cosa è stata segnalata innumerevoli altre volte.
Ad esempio issue  #1066, chiusa senza avere risolto il problema, e #1200, ancora aperta.
La cosa è stata segnalata più volte anche personalmente in incontri one to one e via mail, fornendo svariati esempi.

Non capisco come si possa adesso chiudere una issue ( #1543) dicendo che tutto funziona.
**Chiedo cortesemente di rivolgere alla problematica la dovuta attenzione.**

**Comment by obigno77** [comment]
E' stata rilasciata venerdi un fix in ambiente di qualificazione. La stessa fix sarà rilasciata oggi in ambiente di esercizio. Si chiede conferma dell'avvenuta soluzione del problema.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p> </p>

<p>il giorno 05/08 è stata rilascita una fix riguardante la problematica da lei riscontrata.</p>

<p>Pertanto la invitiamo a riprovare.</p>

<p> </p>

<p>Restiamo a disposizione</p>

<p> </p>

<p>Cordiali saluti</p>
