### ISSUE TITLE
[Maggioli] Creazione scheda SA1 dopo la SC1

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#1624]
Da orchestratore, è possibile creare la SA1 direttamente dopo la SC1. Tra l'altro, con questa sequenza, poi non è più possibile creare la I1

In quale circostanza ha senso creare l'avanzamento senza avere creato l'inizio esecuzione contratto?

Grazie

**Comment by anac-uscp** [comment]
<p>L'ipotesi per cui è possibile inviare una scheda di avanzamento SA1 senza l'invio di una scheda di Inizio Prestazione I1, è la possibilità di effettuare il SAL sulle anticipazioni.</p>

<p>Al momento non è possibile inviare una scheda I1 dopo la scheda di avanzamento, stiamo procedendo con la correzione del flusso per prevedere questa possibilità.</p>

**Comment by anac-uscp** [comment]
<p>A totale rettifica delle precedente risposta si comunica che:</p>

<p><span style="font-size:11pt;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:13.0pt;"><span style="background-color:white;"><span style='font-family:"Titillium Web";'><span style="color:#001e3c;">Non è possibile inviare una scheda di avanzamento SA1, anche nel caso sia redatta ai fini dell'anticipazione, se prima non è stata effettuata la consegna dei lavori o l'avvio dell' esecuzione in via d'urgenza e quindi sia stata inviata una scheda di inizio prestazione, I1.</span></span></span></span></span></span></p>
