### ISSUE TITLE
Trasmissione OE in caso di raggruppamenti RTI nelle schede di aggiudicazione

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1625]
Buon pomeriggio, 
facendo riferimento alla risposta di @obigno77 alla issue https://github.com/anticorruzione/npa/issues/1537

              Si, la stessa regola va applicata anche nella scheda di aggiudicazione in caso di RTI.

_Originally posted by @obigno77 in https://github.com/anticorruzione/npa/issues/1537#issuecomment-2192546128_

Abbiamo provato ad inviare, in ambiente di QUALIFICAZIONE, una scheda A1_29 per l'aggiudicazione di un lotto, con cig I008232834, appartenente all'appalto con id e95ecc7e-c634-4008-a9f1-2023f02f0346.

In fase di creazione scheda otteniamo però questo errore:

`{
    "codice":"ERR87",
    "descrizione": {
		"it": "idPartecipante duplicato per lo stesso lotto",
		"en": "idPartecipante duplicato per lo stesso lotto"
	},
    "dataInizio":null,
    "dataFine":null
}`

GovWay-Message-ID: 6a8a6a63-6e1c-4d1b-b73d-0e17df612664
GovWay-Transaction-ID: 716b9485-4f48-11ef-8dc0-0050568e08b3

La scheda di aggiudicazione (e anche la scheda S2) è stata "compilata" seguendo le indicazioni della issue citata, potremmo sapere cosa abbiamo sbagliato?
In ogni caso potremmo avere più specifiche in merito a quanto in oggetto?
Abbiamo in produzione una gara, per la quale vi è una RTI, per la quale presto dovrà essere inviata la scheda di aggiudicazione e ci servirebbe sapere al più presto quale sia il modo corretto di farlo.

**Comment by obigno77** [comment]
Errore mio nella precedente risposta. Nella scheda di aggiudicazione non va riportata l'intera composizione dell'aggiudicatario ma solo citato l'idPartecipante una sola volta
