### ISSUE TITLE
Errore Orchestratore SA1 - I1

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#1626]
Scenario: Utente ha correttamente confermato la SC1:
Lo stesso utente ha poi correttamente confermato SA1 come previsto da orchestratore
Ora sta provando a mandare la I1 ma il sistema anac mi risponde:
“La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata”
In effetti da orchestratore dopo la SA1 non è possibile I1
Ma se dopo la SC1 posso fare la SA1 dovrei dopo poter fare la I1 dopo il subappalto altrimenti non ho più modo di farla.

**Comment by anac-uscp** [comment]
<p>Non è possibile inviare una scheda di avanzamento SA1, anche nel caso sia redatta ai fini dell'anticipazione, se prima non è stata effettuata la consegna dei lavori o l'avvio dell' esecuzione in via d'urgenza e quindi sia stata inviata una scheda di inizio prestazione, I1.</p>

<p>E' da tenere in conto la tempistica della consegna dei lavori che deve avvenire entro 45 giorni dopo la firma del contratto.</p>

<p>L'orchestratore sarà modificato per evitare l'invio della SA1 prima dell'invio della scheda I1.</p>
