### ISSUE TITLE
[TOSCANA/BOLZANO]  Chiarimenti servizio /recupera-storico-documento-fvoe

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1627]
Salve,
vorrei cortesemente avere chiarimenti sul servizio **/recupera-storico-documento-fvoe**. 
In particolare, analizzando il json di input e output del servizio, ho notato che dato un  **idDocumento** in input, in risposta viene restituita una **lista di documenti**, al cui interno è presente una **lista di fascicoli** e la relativa **lista di documenti**.

E' possibile avere maggiori dettagli?

<img width="327" alt="image" src="https://github.com/user-attachments/assets/f31f5719-13c4-46eb-9115-b203dee0ac97">

**Comment by anac-uscp** [comment]
<p>Gentile Utente,<br>
<br>
attraverso l’invocazione di tale servizio sarà possibile recuperare la history e tutte le operazioni effettuate su quel documento.<br>
La response del servizio è una lista dei documenti di questo tipo.<br>
Si tratta di una lista di documenti in cui in ogni elemento è presente l'idDocumento di cui si richiede lo storico e le azioni fatte su quel documento.<br>
<br>
Il allegato uno scenario di esempio di response. <br>
<br>
Restiamo a disposizione.<br>
<br>
Cordiali Saluti </p>
