### ISSUE TITLE
Riapertura issue 1414

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1628]
Buongiorno,
con riferimento alla vostra risposta alla issue [1414](https://github.com/anticorruzione/npa/issues/1414#issuecomment-2265080566) credo abbiate sbagliato qualcosa...  da quando la scheda S2 è diventata una scheda di aggiudicazione?

Daalle specifiche la S2 risulta ancora "Modello Dati - Scheda S2 - La scheda è valida sia per raccogliere l'elenco dei partecipanti che hanno presentato offerta e degli invitati che non hanno presentato offerta per le procedure a doppia fase, che l'elenco dei partecipanti per le procedure a fase unica".

Sono mesi che chiediamo chiarimenti sul flusso 72 (che se non lo sapete riguarda le schede seguenti la P7_2) e la risposta è basta mandare la scheda S2?

Siete davvero sicuri?

**Comment by obigno77** [comment]
La scheda di aggiudicazione per il flusso 72 è stata individuata nella A2_29. In attesa dell'aggiornamento dell'orchestratore la scheda è già accettata dal sistema,
