### ISSUE TITLE
Post-Pubblicazione controllo schede s1-s2-nag

### ISSUE THREAD

**Issue by Marcolin97** [anticorruzione/npa#1630]
Salve, in fase di Test per il post pubblicazione stiamo riscontrando problemi per quanto riguarda le schede s1 s2 e nag, con errore in stacktrace ERR2. 

Esempi di appalto su cui sono stati effettuati i test sono:

idAppalto: fda785fc-e257-4877-ae1b-f7d9cd6aad87 
cig: I0082500F8

idAppalto: 2f475fde-ed88-4dc0-9a65-df02c2667817
cig: I00823C077

idAppalto: a36a9896-39fc-46cd-b5ac-fe83f685b57e
cig: I0082E9F36

attendiamo un vostro riscontro e se necessitate anche del json delle seguenti schede

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Per condurre analisi approfondite chiediamo gentilmente di fornirci i payload delle schede inviate.</p>

<p>Chiediamo quindi di aprire una nuova segnalazione avendo cura di riportare anche le informazioni presenti in questa issue.</p>

<p>Restiamo in attesa di un suo riscontro.</p>

<p>Cordili saluti.</p>
