### ISSUE TITLE
[TOSCANA/BOLZANO] - Richiesta chiarimenti CM1/CM2

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1631]
Salve,
grazie per il riscontro fornito alla issue: https://github.com/anticorruzione/npa/issues/1485 

Tuttavia, al punto 1 è stato risposto quanto segue:

Servizio cancella avviso: con tale servizio è possibile l’eliminazione di una specifica **Scheda dati in lavorazione nelle fasi successive alla pubblicazione**

Ma nel documento https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md

è riportato quanto segue:

cancella-avviso: servizio di sospensione di una richiesta di pubblicazione, sia nazionale sia europea, **di un avviso non ancora pubblicato.** L’Appalto transita nello stato “STOP PUBBLICAZIONE” e l’Avviso in “ANNULLA PUBBLICAZIONE”;

- E' possibile avere ulteriori dettagli sul servizio **cancella-avviso?**

In merito alla risposta al punto 4 -->  La modifica dell'importo comporta la variazione del CIG?
**Dopo la sottoscrizione del contratto non è possibile inviare la CM1, è necessario inviare una scheda di modifica contrattuale.**

La domanda riguarda la modifica dell'importo attraverso le schede CM1/CM2.

- È possibile avere chiarimenti sulla possibile variazione di un CIG a seguito di una modifica dell'importo con CM1/CM2?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Il servizio "cancella-avviso" è progettato per sospendere una richiesta di pubblicazione di un avviso, sia a livello nazionale che europeo, che non è ancora stato pubblicato. Quando questo servizio viene invocato, lo stato dell'appalto passa a "STOP PUBBLICAZIONE" e l'avviso viene contrassegnato come "ANNULLA PUBBLICAZIONE".<br>
 <br>
Per quanto riguarda le schede CM1 e CM2, queste sono utilizzate per comunicare modifiche ai dati della procedura per appalti rispettivamente sopra e sotto i 5.000 euro. È importante notare che l'utilizzo di queste schede è limitato a determinate procedure e casistiche. <br>
Acquisti Telematici<br>
 <br>
In merito alla variazione del Codice Identificativo Gara (CIG) a seguito di una modifica dell'importo tramite le schede CM1/CM2, è fondamentale comprendere che il CIG è un identificativo univoco assegnato a una specifica procedura di gara. Modifiche all'importo dell'appalto non comportano la variazione del CIG già assegnato. Tuttavia, è necessario comunicare tali modifiche all'ANAC attraverso le schede appropriate per garantire la trasparenza e la tracciabilità della procedura. <br>
 <br>
In sintesi, il servizio "cancella-avviso" consente di sospendere la pubblicazione di un avviso non ancora pubblicato, mentre le schede CM1/CM2 permettono di comunicare modifiche ai dati della procedura, inclusi gli importi, senza alterare il CIG assegnato.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.<br>
 </p>
