### ISSUE TITLE
[CONSIP] - Scheda S2 - Trasmessa -''Dati generali di gara - elenco soggetti'' 

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1632]
Buongiorno,
contrariamente a quanto ci aspettavamo, siamo riusciti a trasmettere la scheda S2 aventi 2 sezioni ''Dati generali di gara - elenco soggetti'' con partecipanti diversi ma con lo stesso Cig. 
Di seguito il file json della scheda S2 
[json S2.txt](https://github.com/user-attachments/files/16498951/json.S2.txt)

Tale comportamento è errato in quanto l'utente rimane bloccato successivamente provando a trasmettere la scheda A3_1 nei seguenti modi.

Provando a trasmettere la scheda di Aggiudicazione A3_1 con 2 sezioni ''Aggiudicazioni'' con partecipanti diversi ma con lo stesso Cig. - si riceve ERR61 
[JSON ERR61.txt](https://github.com/user-attachments/files/16499090/JSON.ERR61.txt)

400 Bad Request: "{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR61"}]}"
 
GovWay-Message-ID
[58db6347-0b13-4b6d-ade0-53ff47dafba1]
GovWay-Transaction-ID
[4ca40698-5333-11ef-bd08-0050568e9679]

Provando a trasmettere la scheda di Aggiudicazione A3_1 con una sezione ''Aggiudicazioni'' con un partecipante della scheda S2 si riceve ERR77
[json err77.txt](https://github.com/user-attachments/files/16499124/json.err77.txt)

400 Bad Request: "{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","dettaglio":"idPartecipante: 05a9ac43-90ec-4e10-b33a-8db2ad5d6339 - cig: I008399078","codice":"ERR77"}]}"
 
GovWay-Message-ID
[58db6347-0b13-4b6d-ade0-53ff47dafba1]
GovWay-Transaction-ID
[4ca40698-5333-11ef-bd08-0050568e9679]

L'utente in questo modo rimane bloccato, in quanto non può procedere con la trasmissione della scheda di Aggiudicazione.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>é stata effettuata una bonifica dati che ha aggiunto, all'interno del lotto, il partecipante, con id: "05a9ac43-90ec-4e10-b33a-8db2ad5d6339", che non era presente e scatenava ERR77.<br>
<br>
La invitiamo a riprovare ed andare avanti con la trasmissione della scheda di aggiudicazione.</p>

<p><br>
<br>
Restiamo a disposizione.</p>

<p><br>
<br>
Cordiali saluti</p>

<p> </p>
