### ISSUE TITLE
Issue collegata a Errore Orchestratore SA1 - I1 #1626

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#1633]
Quando sarà corretto l'orchestratore in produzione? (C'è anche l'errore sulle schede di subappalto segnalato da mesi)
Se un utente in produzione ha fatto una SA1 senza I1 visto che orchestratore lo consentiva come può risolvere?

**Comment by anac-uscp** [comment]
<p>Non è possibile inviare una scheda di avanzamento SA1, anche nel caso sia redatta ai fini dell'anticipazione, se prima non è stata effettuata la consegna dei lavori o l'avvio dell' esecuzione in via d'urgenza e quindi sia stata inviata una scheda di inizio prestazione, I1.</p>

<p>E' da tenere in conto la tempistica della consegna dei lavori che deve avvenire entro 45 giorni dopo la firma del contratto.</p>

<p>L'orchestratore sarà modificato per evitare l'invio della SA1 prima dell'invio della scheda I1.</p>
