### ISSUE TITLE
[CONSIP - FVOE] - Nominativi per il download dei documenti (Tutte le tipologie)

### ISSUE THREAD

**Issue by LuigiScortichino** [anticorruzione/npa#1634]
Buongiorno,

in modo da chiudere il giro delle completo delle funzionalità, per qualsiasi tipo di documento, potete indicare se esistono dei nominativi (Operatori economici etc) per cui la richiesta di download vada a buon fine e venga messo a disposizione il file (file di test) per il download.

Grazie mille

**Comment by obigno77** [comment]
Buongiorno, l'ambiente di qualificazione è integrato con gli ambienti omologhi degli enti certificanti. Provvediamo a pubblicare sulla documentazione i dati utilizzabili per i casi in cui gli enti certificanti ci hanno messo a disposizione un ambiente di collaudo funzionante e relativi casi di test
