### ISSUE TITLE
[Consip - FVOE] - Tipo Richiesta Documenti DatiSA_00036 - Validità anno su richiesta  DATI REDDITUALI SOCIETA DI PERSONE e DATI REDDITUALI IMPRESA INDIVIDUALE

### ISSUE THREAD

**Issue by LuigiScortichino** [anticorruzione/npa#1635]
Buongiorno,
voi contattiamo per sapere se è corretto quanto segnalato nello swagger in merito al tipo richiesta **DatiSA_00036.**
In particolare vorremmo sapere se realmente l'anno per cui è possibile richiedere il documento
DATI REDDITUALI SOCIETA DI PERSONE o DATI REDDITUALI IMPRESA INDIVIDUALE
deve esser compreso tra il 2016 ed il 2022, come si desume dal **pattern: ^(201[6-9]|202[0-2])$**

In questa maniera **verrebbero escluse le domande che fanno riferimento agli anni fuori dal range in particolare quelle successive al 2022**, confermate che sia così?

Grazie mille

**Comment by obigno77** [comment]
Al momento questo è il range di date supporto dall'Agenzia delle Entrate
