### ISSUE TITLE
 [Consip - FVOE] - Tipo Richiesta Documenti DatiSA_00020 - Validità campo PARTITA IVA su richiesta  CERTIFICATO DELL'ANAGRAFE DELLE SANZIONI AMMINISTRATIVE DIPENDENTI DA REATO

### ISSUE THREAD

**Issue by LuigiScortichino** [anticorruzione/npa#1636]
Buongiorno,

sulla richiesta CERTIFICATO DELL'ANAGRAFE DELLE SANZIONI AMMINISTRATIVE DIPENDENTI DA REATO è previsto 
il campo PARTITA_IVA la cui validazione sullo swagger viene indicato con il pattern: ^([0-9]){11}$

Il pattern include anche le P. IVA degli stati esteri?

Grazie mille

**Comment by obigno77** [comment]
No. Non è disponibile quel tipo di certificazione per OE esteri
