### ISSUE TITLE
[Consip - FVOE ] - Richiesta tipi documento presenti nel fascicolo virtuale

### ISSUE THREAD

**Issue by LuigiScortichino** [anticorruzione/npa#1637]
Buongiorno,
abbiamo notato che nell'elenco dei documenti presenti nel fascicolo virtuale di un Operatore Economico,
che viene restituito invocando l'endpoint "/ricerca-documenti-fvoe"
sono presenti alcuni tipi di documenti (ad esempio COMUNICAZIONE ANTIMAFIA) che possono essere richiesti esplicitamente
con la nuova funzionalità, usando l'endpoint  "/richiedi-documenti" ed il successivo "/verifica-stato-richiesta-documento"

Volevamo avere una conferma se le due liste risultanti possono condividere gli stessi documenti, pur se non richiesti esplicitamente e se presenti nel Fascicolo Virtuale.

Grazie mille

**Comment by obigno77** [comment]
Il fascicolo viene prepopolato con tutti i documenti disponibili e in corso di validità. La verifica dello stato richiesta riguarda solo i documenti esplicitamente richiesti dalla stazione appaltante nell'ambito di quel FVC.
