### ISSUE TITLE
Supporto testing schede S1, S2, NAG

### ISSUE THREAD

**Issue by Marcolin97** [anticorruzione/npa#1639]
Salve, necessitiamo supporto per quanto riguarda lo stato di appalto e/o lotto durante la fase di testing per le schede S1,S2 e NAG, in quanto in qualunque situazione, con o senza Partecipanti all'appalto il risultato ottenuto è un ERR2.
La ringrazio per il supporto
Cordiali Saluti

**Comment by obigno77** [comment]
Le schede S1, S2 e NAG possono essere utilizzate solo nei casi previsti e documentati dall'orchestratore
