### ISSUE TITLE
Sistemi di controllo e validazione ESPD e eForms

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#164]
Si richiede se ANAC intende pubblicare ulteriori servizi di controllo e validazione specifica dei componenti ESPD e eForms.
Tali servizi consentirebbero all'Ente Appaltante di procedere gradualmente alla verifica della correttezza dei diversi oggetti prodotti, evitando di concentrarli tutti nel momento finale di pubblicazione della Gara.

**Comment by supportoAnac** [comment]
Il servizio /verifica-appalto fa riferimento agli schemas XSD e ai servizi TED per la verifica di ESPD ed eForms, che applicano schema XSD e grammatiche di controllo all'interno del documento.

Vedere anche https://github.com/anticorruzione/npa/issues/18
