### ISSUE TITLE
[Consip] - Problemi invio schede con  tipologica fattispecieTracciabilita - post rilascio ANAC 08/08/24

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#1641]
Stiamo riscontrando problemi nell’inviare schede contenenti la tipologiche fattispecieTracciabilità.json Riceviamo error63

Le scheda è stata inviata tenedendo in considerazione gli aggiornamenti rilasciati oggi 08/08/2024

Codice appalto CONSIP_RDO_2631713 
 
Di seguito i log

RequestBody = {"scheda":{"type":"SchedaComunicaAppaltoType","codice":{"idTipologica":"codiceScheda","codice":"P5"},"versione":"1.0","body":{"type":"SchedaP5Type","anacForm":{"stazioniAppaltanti":[{"codiceFiscale":"05359681003","codiceAusa":"9000000008","codiceCentroCosto":"f237c494-bae6-47e4-8c32-f15a5228b948","saTitolare":true}],"appalto":{"codiceAppalto":"CONSIP_RDO_2631713","datiBase":{"oggetto":"TEST P5","importo":123123.0}},"lotti":[{"lotIdentifier":"LOT-0001","fattispecieTracciabilita":{"idTipologica":"fattispecieTracciabilita","codice":"24"},"datiBase":{"oggettoContratto":{"idTipologica":"oggettoContratto","codice":"works"},"oggetto":"og","importo":123123.0},"sceltaContraente":{"idTipologica":"sceltaContraente","codice":"1"}}]}}}} - requestUrl = https://apigw-test.anticorruzione.it/modi/rest/ComunicaAppalto/v2/crea-appalto - headers = {Authorization=[Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L0NvbXVuaWNhQXBwYWx0by92MiIsInN1YiI6IjAxZTJlZmM0LWYyY2QtNDBmNC1iYWMxLTA1ZTdjNmRjZWZiYSIsIm5iZiI6MTcyMzEyMTI4MywiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiZjc5NWRkMmE1ZjQ5OWJlNGJjOTJhMjE3MWEzYmVjN2VhN2VhMjU5YzgzMWRlYWFkMzcyNDQwMzlkNDQ0ZDAxMiJ9LCJwdXJwb3NlSWQiOiI2MjE4MzhlMy1lNmRlLTQzZDItYmQ4OC0xYTBlYjBmOTM5ZDQiLCJpc3MiOiJ1YXQuaW50ZXJvcC5wYWdvcGEuaXQiLCJleHAiOjE3MjMxMjQ4ODMsImlhdCI6MTcyMzEyMTI4MywiY2xpZW50X2lkIjoiMDFlMmVmYzQtZjJjZC00MGY0LWJhYzEtMDVlN2M2ZGNlZmJhIiwianRpIjoiOGY2MWUxNjEtZjA2Mi00YmRiLTk2MmQtZWI4OTQ0NmZhZjUwIn0.fNoHvxHW1VxcoQadlJLuls-Ra8oMxSu9cqX7vzxtBQAHqaivDZOaRMHquw6NzQS4V3TnMllawgztiF_1Jf7VKHLqNIcbD11xwdaurYxzVh3Vc59GuM98pcGXSbMw9Sz7aGqM0nk3uxjfbsW1Mmj0Tc2lV4chLsTRK_H-TB21ZNn5RWg9JUp2ufAWiS7zoCkT4fjymhDpptH01iwOHkOhvjvRADMcgsb3VvYFBViVsIcPq8wZ59QxJYXDzbOVWLtrobe6oTvJE0aXFoUkSw2P94qq3APPZj3aDCAJsLYiNOfCl_u6BFr-IYYgsRJ6zUGJ4dUgPmJALaNjZqMtcB5YtA], Agid-JWT-TrackingEvidence=[eyJraWQiOiJvbjJVTmFCbGxQSlhaZDV4amdPMXoxV2QyeFVRYUItRHFtRFhaZEFiUlRBIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJqdGkiOiI1ZTQwZmQzNy05YjJmLTQ2OGEtOTZmZC1mMTY3M2QzNWMyYzkiLCJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L0NvbXVuaWNhQXBwYWx0by92MiIsInVzZXJDb2RpY2VGaXNjYWxlIjoiRlJOTkxEOThBMjhINTAxTCIsInVzZXJSb2xlIjoiUlAiLCJ1c2VyTG9hIjoiMyIsInVzZXJJZHBUeXBlIjoiU1BJRCIsIlNBQ29kaWNlRmlzY2FsZSI6IjA1MzU5NjgxMDAzIiwiU0Fjb2RpY2VBVVNBIjoiOTAwMDAwMDAwOCIsInJlZ0NvZGljZVBpYXR0YWZvcm1hIjoiMDAwMDAwOSIsInJlZ0NvZGljZUNvbXBvbmVudGUiOiIwMDAwMDEwIiwiYnVzaW5lc3NGbG93SUQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJ0cmFjZUlEIjoiZmYxZjBjZmItMDExNi00N2I1LTk0M2UtNDYwYjI3MjVhYzliIiwic3BhbklEIjoiODQ4MGFmMjAtNjExZS00ZDgyLTk5YzctNzk0ZjE1NGE0ZGNmIiwicHVycG9zZUlkIjoiNjIxODM4ZTMtZTZkZS00M2QyLWJkODgtMWEwZWIwZjkzOWQ0IiwiaWF0IjoxNzIzMTIxMjgyLCJleHAiOjE3MjMxMjQ4ODIsIm5iZiI6MTcyMzEyMTI4Mn0.W_2OGpJI7JJwOP3mrt2thOWF3hwU6vZeqbaExDNPMOiYzXtRVlalAe7eNG6u9h3Sj9dJU59fPzcjqRSWdSOnOk8HLcdq0vwAb2Z_7zPzCyz-oM3Os6xTQLDOWoQKHiSZB5Qi0hEOdAzVmemK5oQzlstt1J1tXbDme-HLSRKY2gQRz0PKPkcCynrcnlCNbiVPGaS3DvPa4ZnJNdYKWd7VbVoWUwaWyd05rs7dmxqRNQVGsPlpndYpir_0lbWGnm1tc-9rxko0U17LCNJFah6EaaK9VDPUPAOfCfdNuNUOTmlrqSw06Uxt-AMRzCfwCKCSNUoJuqlq8I95OTwqYZW7IA], Content-Type=[application/json;charset=UTF-8], } - method = POST - Timestamp=1723121283059 - Taken=52 ms  - Thread=80 - StatusCode =  - 400 - ResponseFoundFromException =  - {"status":400,"title":"KO","detail":"Errore Validazione Tipologiche","type":"about:blank","errori":[{"idTipologica":"errori","dettaglio":"'fattispecieTracciabilita' : {'fattispecieTracciabilita' : '24'}","codice":"ERR63"}]} - ResponseHeaders - {Server=[nginx], Date=[Thu, 08 Aug 2024 12:48:03 GMT], Content-Type=[application/json], Transfer-Encoding=[chunked], Connection=[keep-alive], expires=[0], cache-control=[no-cache, no-store, max-age=0, must-revalidate], x-xss-protection=[1; mode=block], pragma=[no-cache], GovWay-Message-ID=[8f61e161-f062-4bdb-962d-eb89446faf50], x-frame-options=[DENY], GovWay-Transaction-ID=[f56b5670-557d-11ef-bd08-0050568e9679], vary=[Access-Control-Request-Headers, Access-Control-Request-Method, Origin], x-content-type-options=[nosniff], strict-transport-security=[max-age=31536000 ; includeSubDomains, max-age=63072000], } - 
org.springframework.web.client.HttpClientErrorException: 400 Bad Request

**Comment by obigno77** [comment]
Problema risolto
