### ISSUE TITLE
Ambiente di ATTESTAZIONE | Richieste accesso FVOE MAI autorizzate

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1643]
Buongiorno,
abbiamo effettuato alcune richieste di accesso al FVOE in ambiente di ATTESTAZIONE ma sono trascorse ormai quasi 3 settimane e lo stato autorizzazione non è mai variato. 
Riportiamo di seguito tutte le info delle richieste di accesso effettuate:

**_P7_2 Ambiente di ATTESTAZIONE_**
idAppalto: e08c9ef3-a182-489d-b792-493f5140dde6
s2 inviata
**richiesta effettuata il 2024-07-18 - idRichiesta: 0ee10a09-3ca4-4616-b8b3-5b4a136fbfb9 - piva: 11111111114**
**richiesta effettuata il 2024-07-19 - idRichiesta: f3e3862a-9b31-48c1-816e-fd96019be41a - piva: 11111111113**

**_P1_16 Ambiente di ATTESTAZIONE_**
idAppalto: 9d25afa5-d64a-42f5-8fff-d32e0a78117e
idAvviso: 1ee2e975-5ae8-4eae-9b4c-d5c2820cf51c
s2 inviata
**richiesta effettuata il 2024-07-24 - idRichiesta: 83ccb716-e175-4b7b-89e6-d96da8dcfa14 - piva: 11111111114**

Sarebbe possibile autorizzarle così da farci effettuare dei test per il FVOE anche in questo ambiente?
Come mai non vengono autorizzate? 
C'è qualcosa di differente da fare nell'ambiente di attestazione?
L'ambiente di ATTESTAZIONE possiede degli scenari d'esempio?

**Comment by obigno77** [comment]
Il problema è stato risolto automatizzando l'autorizzazione
