### ISSUE TITLE
FVC - Servizio richiedi-documenti campo datiRichiesti

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1644]
nel servizio richiedi-documenti nel campo datiRichiesti non è presente in documentazione il campo "type" che invece risulta indispensabile alla corretta esecuzione del servizio.
La documentazione prevede:
![image](https://github.com/user-attachments/assets/a761da7f-a17e-40a7-8979-0350a4a186c5)
mentre il json accettato per l'esecuzione del servizio è il seguente:
{
  "chiaveAccesso": "5ded1cba-ac4a-47ef-bdda-86c7d5b843f8",
  "tipoDocumento": {
    "idTipologica": "tipoDocumento",
    "codice": "00899"
  },
  "datiRichiesta": {
		"tipoDocumentoOE": "Fatturato specifico dell'ultimo triennio",
		"dettaglioDocumentoOE": "Fatturato specifico realizzato nell'ultimo triennio (2021 - 2023) nella fornitura di piattaforme di eProcurement alla Pubblica Amministrazione",
		**"type": "DatiSA00899"**
	}
  }

**Comment by stalex1** [comment]
Gentile Utente

La ringraziamo per la segnalazione.

Confermiamo che, come da sua osservazione, nel servizio "richiedi-documenti", il campo "type" risulta essenziale per la corretta esecuzione del servizio, ma non è attualmente presente nella documentazione.

Il JSON corretto, accettato per l'esecuzione, è quello da lei indicato, con il campo "type" valorizzato come "DatiSA00899".

Provvederemo ad aggiornare la documentazione ufficiale per includere tale informazione, al fine di garantire maggiore chiarezza e allineamento con quanto previsto dal sistema.

Restiamo a disposizione per eventuali ulteriori necessità.

 

Cordiali Saluti
