### ISSUE TITLE
[CONSIP] - Scheda NAG - ERR2: La scheda in ingresso non è ammessa a fronte del flusso di schede già presenti

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1646]
Buongiorno, 
riscontriamo la seguente anomalia:
E' stata trasmessa una scheda di indizione P7_1_3. 
Viene selezionata una scheda di post-pubblicazione NAG. Tale scheda è prevista dal flusso dell'orchestratore. Quando si prova a trasmettere tale scheda, compare il seguente errore:
ERR2 - La scheda in ingresso non è ammessa a fronte del flusso di schede già presenti
 
 idAppalto: 724b29b8-ef63-4f10-be93-02644839df19
GovWay-Message-ID: 17485530-3075-4c28-bfa5-818b07287437
GovWay-Transaction-ID: 64fea947-562e-11ef-8dc0-0050568e08b3

Di seguito i log:
2024-08-09 11:37:49,041 ERROR (AbstractAnacUnhandledIntegrationService.java:215) - [[ACTIVE] ExecuteThread: '22' for queue: 'weblogic.kernel.Default (self-tuning)']: RequestBody = {"idAppalto":"724b29b8-ef63-4f10-be93-02644839df19","scheda":{"codice":

{"idTipologica":"codiceScheda","codice":"NAG"}
,"versione":"1.0","body":{"type":"SchedaNAGType","anacForm":{"lotti":[{"cig":"I003DEB016","datiBaseRisultatoProcedura":{"giustificazione":

{"idTipologica":"giustificazione","codice":"all-rej"}
}}]}}}} - requestUrl = https://apigw-test.anticorruzione.it/modi/rest/ComunicaPostPubblicazione/v2/crea-scheda - headers = {Authorization=[Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L0NvbXVuaWNhUG9zdFB1YmJsaWNhemlvbmUvdjIiLCJzdWIiOiIwMWUyZWZjNC1mMmNkLTQwZjQtYmFjMS0wNWU3YzZkY2VmYmEiLCJuYmYiOjE3MjMxOTYyNjgsImRpZ2VzdCI6eyJhbGciOiJTSEEyNTYiLCJ2YWx1ZSI6IjM0NTYwNTllNDcxOTQyYWIzMGRjYjk2NTg3YjBhN2ZkN2FkNDU2ZmQ5YTI0MGY1ZjQ3NDVlODNmYzZlYzdkODEifSwicHVycG9zZUlkIjoiNmMyZmFlZTYtNDRmMy00ZjM0LThhOGEtMGY4ZWNhNzNhNjQwIiwiaXNzIjoidWF0LmludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzIzMTk5ODY4LCJpYXQiOjE3MjMxOTYyNjgsImNsaWVudF9pZCI6IjAxZTJlZmM0LWYyY2QtNDBmNC1iYWMxLTA1ZTdjNmRjZWZiYSIsImp0aSI6IjE3NDg1NTMwLTMwNzUtNGMyOC1iZmE1LTgxOGIwNzI4NzQzNyJ9.p-oqwYIlmTnL6DQc1iiTrHeNe45-iK4gIvyx36U7ZaCjum9PZn_PYBXhzO8M1xDwTFPc6TasnDvD4Q_1-gIhTKlFG7B12xW3DuB06Mz5QVBM0ZhOwWTRNiyp_1rujT10LMNn-TWVFJcWWtDJZsfmUtC4jm1vRLC24lam4eLm5mZuKc9dy0U5VjMYzDZtN07sLhgEvNccNBYqRPatVByJBUyZuIUKJhCkZpRK9w28L_tjq8zEqnt3a8qVCEIlvfRMUlJQ9GOnacMnw-rzfUZgN4NHWtVOJmCkewM8E8mqphzfvNwV12FD9gZSKwkH2QAbj0Pk8Hk0TNdl48cxyhzNvQ], Agid-JWT-TrackingEvidence=[eyJraWQiOiJvbjJVTmFCbGxQSlhaZDV4amdPMXoxV2QyeFVRYUItRHFtRFhaZEFiUlRBIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJqdGkiOiI5NDZlN2Q0NC03NGZmLTQxZmUtODAxMS1lZDY1YjQ3NTdiNzYiLCJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L0NvbXVuaWNhUG9zdFB1YmJsaWNhemlvbmUvdjIiLCJ1c2VyQ29kaWNlRmlzY2FsZSI6IlZUTkNMRDk0VDYwSDUwMVUiLCJ1c2VyUm9sZSI6IlJQIiwidXNlckxvYSI6IjMiLCJ1c2VySWRwVHlwZSI6IlNQSUQiLCJTQUNvZGljZUZpc2NhbGUiOiIwNTM1OTY4MTAwMyIsIlNBY29kaWNlQVVTQSI6IjkwMDAwMDAwMDgiLCJyZWdDb2RpY2VQaWF0dGFmb3JtYSI6IjAwMDAwMDkiLCJyZWdDb2RpY2VDb21wb25lbnRlIjoiMDAwMDAxMCIsImJ1c2luZXNzRmxvd0lEIjoiNzI0YjI5YjgtZWY2My00ZjEwLWJlOTMtMDI2NDQ4MzlkZjE5IiwidHJhY2VJRCI6IjNlODllZmViLTc5NmQtNDFhNi1hOWE2LWQ2ZmY0MzJiM2M4ZCIsInNwYW5JRCI6IjczZjc2NTk5LTU3MDAtNDJmMC05MzM2LWJjMjI5YzAwNWQyNCIsInB1cnBvc2VJZCI6IjZjMmZhZWU2LTQ0ZjMtNGYzNC04YThhLTBmOGVjYTczYTY0MCIsImlhdCI6MTcyMzE5NjI2OCwiZXhwIjoxNzIzMTk5ODY4LCJuYmYiOjE3MjMxOTYyNjh9.dEGy0UwT4xfKvO8el0OEaEJtxtTYQ_4N1OqAZ4aKjhJIomcuYe7LfwDT4SweBJpxHE7A3tNT5kvatoAgPj3PGPHWl0NC1ke5EB2yNBQBjIL7o1g_atv1_iLw79n3A4Nczb9XuXNHNYCe9t4bBnDW-m6sgXYV9wt0hA8OEpkezkMY772Koiv9OTorrLEJFR0pyevz3l9TJhuzdxd7u9CsKGC6hm6lGw8Sbp28TxOC0MfFGWOCx_UrZvuwA_wOgDhy1Tg7WKlup_53MH38u8Jc2fVCJkZzvLYMPBNSSXBt0sUj2BAdo0EpsYC0eteFchWsyTJGQpeZTnB-D4pyZ-BbRg], Content-Type=[application/json;charset=UTF-8], } - method = POST - Timestamp=1723196268926 - Taken=115 ms - Thread=108 - StatusCode = - 400 - ResponseFoundFromException = - {"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[

{"idTipologica":"errori","dettaglio":"La scheda in ingresso non Ã¨ ammessa a fronte del flusso di schede giÃ  presenti","codice":"ERR2"}
]} - ResponseHeaders - {Server=[nginx], Date=[Fri, 09 Aug 2024 09:37:49 GMT], Content-Type=[application/json], Transfer-Encoding=[chunked], Connection=[keep-alive], expires=[0], cache-control=[no-cache, no-store, max-age=0, must-revalidate], x-xss-protection=[1; mode=block], pragma=[no-cache], GovWay-Message-ID=[17485530-3075-4c28-bfa5-818b07287437], x-frame-options=[DENY], GovWay-Transaction-ID=[64fea947-562e-11ef-8dc0-0050568e08b3], vary=[Access-Control-Request-Headers, Access-Control-Request-Method, Origin], x-content-type-options=[nosniff], strict-transport-security=[max-age=31536000 ; includeSubDomains, max-age=63072000], } -

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p><br>
Siamo a conoscenza della situazione e abbiamo già avviato le procedure necessarie per risolvere la problematica che verrà fixata nel mese di Dicembre.</p>

<p><br>
Restiamo a disposizione per eventuali chiarimenti.<br>
Cordiali saluti.<br>
 </p>
