### ISSUE TITLE
[TeamSystem]- [BLK]- P7_1_3 invio NAG non ammesso ERR2

### ISSUE THREAD

**Issue by mcgirone** [anticorruzione/npa#1647]
Buongiorno,

in seguito alla creazione di una scheda P7_1_3 e l'invio della NAG , il sistema restituisce un ERR2.

[crea-appalto_P7_1_3_Request (1).json](https://github.com/user-attachments/files/16582041/crea-appalto_P7_1_3_Request.1.json)
[crea-scheda_NAG_Response.json](https://github.com/user-attachments/files/16582049/crea-scheda_NAG_Response.json)

Non è stata inviata una scheda S1 in quanto la procedura è deserta. 
Da orchestratore è riportata la possibilità di inviare una NAG, potreste darci informazioni in merito a questa anomalia?

Grazie.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Siamo a conoscenza della situazione e abbiamo già avviato le procedure necessarie per risolvere la problematica che verrà fixata orientativamente nel mese di Dicembre.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
