### ISSUE TITLE
valore CIG Affidamento diretto

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1648]
Buongiorno,

risultano necessari dei chiarimenti rispetto ai valori economici da in serire nelle schede Ad.

in particolare:
- il valore del CIG staccato a quale campo corrisponde non essendoci il campo "importo lotto" come per le altre schede?"
- il quadro economico standard deve essere compilato rispetto ai valori di aggiudicazione? 
- non viene previsto in nessun campo di inserire il valore a base d'asta originario?
- la sommatoria del quadro economico non viene inserita da nessuna parte? in particolare, se  ad es ho un importo di aggiudicazione di 9.000€ un valore di opzioni/rinnovi di 5.000€, non viene previsto in nessun campo di inserire i 14.000€ come valore totale?

Grazie

**Comment by anac-uscp** [comment]
<p>E' necessario compilare il quadro economico della scheda per poter comunicare  il valore del CIG staccato.</p>

<p>ll quadro economico standard deve essere compilato rispetto ai valori di adesione.</p>

<p> <em>non viene previsto in nessun campo di inserire il valore a base d'asta originario?</em> No</p>

<p><em>la sommatoria del quadro economico non viene inserita da nessuna parte? in particolare, se ad es ho un importo di aggiudicazione di 9.000€ un valore di opzioni/rinnovi di 5.000€, non viene previsto in nessun campo di inserire i 14.000€ come valore totale? </em></p>

<p>Nell'esempio specifico sarà compilato uno dei campi relativi all'importo Lavori/Servizi/Forniture (9.000 euro) ed il campo 'somme opzioni rinnovi' valorizzato a 5.000 euro. Non è presente un campo che riporta la somma totale.</p>
