### ISSUE TITLE
Rimozione richiesta di ESPD per la scheda P3_1

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#1649]
Buongiorno,
all’interno della scheda RSU1 viene richiesto obbligatoriamente l’invio del DGUE. Nel caso in cui la gara venga pubblicata con una P3_1, come va gestita questa fattispecie con riferimento al flusso 31?

Grazie

**Comment by obigno77** [comment]
In uno dei changelog a venire sarà reintrodotto il DGUE sulla P3_1 come facoltativo e tolta l'obbligatorietà dalla RSU1
