### ISSUE TITLE
 Avviso di aggiudicazione: Flusso pubblicazione

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#165]
Si chiede di indicare il processo ideale per arrivare alla pubblicazione di un avviso di aggiudicazione.
Interpretando la documentazione a disposizione (vedi paragrafo 9.1 del documento **documento-specifiche-servizi-npa.md**) sembra che per pubblicare l'avviso di aggiudicazione sia necessario inviare la **scheda di aggiudicazione**. 
A sua volta prima ancora di inviare la scheda di aggiudicazione viene indicato l'invio della **scheda acquisizione partecipanti**.

Confermate che:

1) Per 'invio al TED dell'avviso di aggiudicazione è necessario inviare a PCP la scheda di aggiudicazione?

2) l'invio della **scheda aggiudicazione** deve essere obbligatoriamente preceduto dall' invio della **scheda acquisizione parteciapanti**?

**Comment by supportoAnac** [comment]
La PCP è il sistema di monitoraggio della attività delle piattaforme di approvvigionamento digitale. In questo ambito l'interazione con la PCP prevede la gestione dell'intero ciclo di vita dell'appalto. Il ruolo di eSender a livello nazionale è collaterale a questa attività principale, pertanto le piattaforme non si connettono a PCP per inviare le eForms ma ne usano i servizi ed inviano le informazioni nell'ambito del processo di gestione di un appalto ai fini della agilità di monitoraggio e pubblicità dei dati previsti dal codice.

**Comment by federicodemarco** [comment]
Buongiorno, la risposta fornita rimane ad un livello troppo alto. il quesito posto chiede di esplicitare un flusso tra quelli documentati nella documentazione fornita.
Il quesito è di tipo funzionale, pertanto chiedo cortesemente un riscontro dello stesso tipo.
Occorre conoscere la sequenza delle attività per essere in grado di verificare gli impatti che l'integrazione con la PCP avrà sugli attuali flussi in essere sulle piattaforme di eproc
