### ISSUE TITLE
Chanegelog2

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#1651]
Buongiorno,
faccio riferiemento alla seguente modifica introdotta con il chagelog: 

_modello-dati-schede-A2_29.yaml,modello-dati-schede-A2_30.yaml,modello-dati-schede-A2_31.yaml:
revisione schede: resi obbligatori gli oggetti datiBaseAggiudicazioneAppalto,datiBaseSubappalti, datiBaseRisultatoProcedura. aggiunti i campi offertaMinimoRibasso, proceduraAccelerata_

In merito ai campi da aggiungere, come verrà gestito il pregresso? Per i CIG staccati prima del rilascio in esercizio del Chanelog2, la scheda di aggiudicazione dovrà prevedere i nuovi campi?

**Comment by obigno77** [comment]
Si
