### ISSUE TITLE
Changelog2 - CUP

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#1652]
Buongiorno,
faccio riferiemento alla seguente modifica introdotta con il chagelog:

_modello-dati-schede-CM1.yaml,modello-dati-schede-CM2.yaml,modello-dati-schede-AD5.yaml,modello-dati-schede-P5.yaml: modificata la cardinalità del campo cupLotto_

In merito alla scheda AD5, l'intervento prevede che si possa passare a pcp più di un CUP? Ad oggi PCP per le AD5 recepisce un solo CUP

Grazie

**Comment by obigno77** [comment]
Nello stesso changelog è previsto il contestuale incremento della cardinalità del CUP anche sulla scheda AD5
