### ISSUE TITLE
crea-appalto InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by LDAV** [anticorruzione/npa#1653]
l'accesso al servizio ComunicaAppalto/v2/crea-appalto non sembra avere, nelle specifiche, le stesse regole di autenticazione di altri servizi PDND (apiAuthKey invece di bearerAuth).

È possibile avere qualche delucidazione rispetto a questo codice di errore? grazie.
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"ee1a341e-5fc7-11ef-8dc0-0050568e08b3"}

**Comment by obigno77** [comment]
Il messaggio fa riferimento all'invalidità del token jwt. Per la transazione specifica gli errori rilevati sono i seguenti:
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
[GOVWAY-661] [Header 'Agid-JWT-TrackingEvidence'] Token scaduto in data '2024-08-21_16:48:09.000'
[GOVWAY-661] [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2024-08-21_16:47:59.000')
