### ISSUE TITLE
[CONSIP] - Scheda A2_29 - ERR94 - [500] during [POST] to http://pcp-qlf-codelist-ms.pcp-qlf.svc:8080/recupera-valore-tipologiche 

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1654]
Buongiorno,
durante la trasmissione della scheda A2_29 riceviamo il seguente messaggio di errore: 

''[500] during [POST] to http://pcp-qlf-codelist-ms.pcp-qlf.svc:8080/recupera-valore-tipologiche [CodelistMsClient#recuperaValoreTipologiche(Map)](https://adtjira.accenture.com/browse/EPROC2-15113#recuperaValoreTipologiche(Map)): [\{"timestamp":"2024-08-21T13:56:54.559+00:00","status":500,"error":"Internal Server Error","path":"/recupera-valore-tipologiche"}]'' 

ID_APPALTO: 1bb87c34-ed64-4818-9cc0-38e583093a6c

Per quale motivo riceviamo tale errore durante il tentativo di trasmissione della scheda A2_29?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>stiamo lavorando ad un fix integrativa che risolve in maniera definitiva la problematica riscontrata.</p>

<p>Le chiediamo gentilmente di riprovare la procedura da giorno 20-09.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>

<p> </p>
