### ISSUE TITLE
ERR79 - scheda SC1 problema id partecipante

### ISSUE THREAD

**Issue by ufftecbud** [anticorruzione/npa#1655]
Non si riesce a trasmettere la scheda SC1 alla PCP per l'errore ERR79 dal MEPA. Non si capisce quale sia il problema legato all'id partecipante. Ho sentito che è stato dismesso da ANAC ma MEPA non si è ancora adeguato

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Senza informazioni aggiuntive non possiamo procedere ad effettuare analisi approfondite, per cui chiediamo di comunicare un CIG o un idAppalto ed il payload inviato.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
