### ISSUE TITLE
Venicecom: Richiesta conferma payload a causa di errore nel modello dati YAML dei servizi "Richiedi-documenti (POST)"

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#1656]
Salve,

Non siamo riusciti a implementare il servizio "Richiedi-documenti (POST)" seguendo le indicazioni fornite nei vari YAML. Siamo comunque riusciti a far funzionare il servizio con uno sforzo aggiuntivo, ma non conformemente al modello dati da voi proposto. Per questo motivo, siamo incerti sulla possibilità di renderlo disponibile ai nostri clienti.
Vi chiediamo gentilmente di confermare se possiamo utilizzare il seguente payload per questo servizio (vedi payload in calce).

**Payload.**
{{     "serviceName": "SA_14_richiedi-documenti", 
"records": {
		"chiaveAccesso": "202F7B3E-AA37-4C2B-8109-196B584806D7",
		"tipoDocumento": {
			"codice": "00005"
		},
		"datiRichiesta": {
			"type": "DatiSA00020",
			"DatiNominativo": {
				"DenominazioneSociale": "",
				"CodiceFormaGiuridica": "",
				"PIVA": "11111111114",
				"DatiSedeSociale": {
					"Indirizzo": "",
					"CodiceCatastoStato": ""
				}
			},
			"AltriDati": {
				"LinguaTedesca": false
			}
		}
	}
}

Cordiali saluti,
Venicecom

**Comment by stalex1** [comment]
Gentile Utente,



La struttura riportata è corretta, ma tutti gli attributi devono essere popolati in base alla tipologia definita nello YAML del modello dati.

Nello specifico non solo la P.iva ma anche DatiNominativo/DenominazioneSociale deve essere popolato.

La struttura generica d'esempio corretta è la seguente: 

{
         "chiaveAccesso":"UUID del Fascicolo su cui si sta eseguendo la richiesta di documentazione",
         "tipoDocumento":{
            "codice":"TipoDocumento come riportato in https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md "
         },
         "datiRichiesta":{
            "type":"Nome del modello dati definito in [https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/modello-dati-fvoe-fva.yaml"](https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/modello-dati-fvoe-fva.yaml%22),
            JSON Modello dati definito in https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/modello-dati-fvoe-fva.yaml
         }
      }

 

Restiamo a disposizione

 

Cordiali Saluti
