### ISSUE TITLE
[CONSIP - FVOE] -  Issue sulla richiesta DatiSA_00036, codici di errore apparentemente non coerenti

### ISSUE THREAD

**Issue by LuigiScortichino** [anticorruzione/npa#1657]
Buongiorno,

per descrivere e riprodurre la issue sulla richiesta DatiSA_00036, si distinguono i seguenti casi:

**Caso 1)** OE che nella richiesta di accesso al Fascicolo Virtuale
ha utilizzato un codice fiscale di tipo individuale, di 16 caratteri
es: CHNWHG37P21E892D
-	Quando si effettua una richiesta di tipoDocumento 00035
"documento di tipo DATI REDDITUALI IMPRESA INDIVIDUALE"
![issue-1638-da-rimandare-01-A](https://github.com/user-attachments/assets/8fdb2058-3a70-4abf-996d-05d11f0a59d4)

{
	"chiaveAccesso": "d912e467-2fd9-44c1-a06e-9c4db0e7b2cc",
	"tipoDocumento": {
		"idTipologica": "35",
		"codice": "00035"
	},
	"datiRichiesta": {
		"annoRiferimento": "2020",
		"domicilioFiscale": {
			"codiceCatastale": "H501"
		},
		"type": "DatiSA00036"
	}
}

Viene restituito uno specifico messaggio di errore che sembra però riferirsi all’altra tipologia di impresa (immagine in allegato) 
![issue-1638-da-rimandare-01-B](https://github.com/user-attachments/assets/3cc21dfc-8629-4af7-9929-cfd24d20ec46)

Di contro, se viene richiesto da parte della stessa azienda individuale
un documento di tipo DATI REDDITUALI SOCIETÀ DI PERSONE (che ci aspettiamo fallisca)
la richiesta viene accolta con successo
![issue-1638-da-rimandare-01-C](https://github.com/user-attachments/assets/8d9a72a1-ef89-44c5-9613-6a4c1927c413)

**Caso 2)** OE con richiesta di accesso al Fascicolo Virtuale
con codice fiscale di 11 caratteri (uguale alla P.IVA)
es: 01014660417
-	Se effettua una richiesta di 
"documento di tipo DATI REDDITUALI IMPRESA INDIVIDUALE" (che ci aspettiamo fallisca)
la richiesta viene accolta con successo
![issue-1638-da-rimandare-02-A](https://github.com/user-attachments/assets/1d48e03f-5482-4237-8f0e-3c17a5cb078d)

-	Se invece effettua una richiesta di 
un documento di tipo DATI REDDITUALI SOCIETÀ DI PERSONE
La richiesta fallisce, ma con un messaggio di errore che sembra però riferirsi all’altra tipologia di impresa (immagine in allegato) 
![issue-1638-da-rimandare-02-B](https://github.com/user-attachments/assets/b65b9a88-8a36-4076-9ed7-95aa1b4cacff)

Il messaggio di errore sembra riferirsi al tipo di società opposta a quella che dovrebbe poter effettuare il tipo di richiesta documento.
![issue-1638-da-rimandare-02-C](https://github.com/user-attachments/assets/fc0b7560-bcdd-4067-be7b-da72d5ab930b)

**Comment by obigno77** [comment]
Gentile Utente,
per il tipoDocumento 00035 - DATI REDDITUALI IMPRESA INDIVIDUALE il formato del CF OE corretto é un numerico di 11 caratteri.
In caso di inserimento di un CF in formato alfanumerico viene sollevato l'errore FVX50 - Codice Fiscale Persona Non Fisica non valido;  

per il tipoDocumento 00041 - DATI REDDITUALI SOCIETÀ DI PERSONE il CF OE corretto é alfanumerico di persona fisica.
In caso di inserimento di un CF numerico viene sollevato l'errore FVX49 Codice Fiscale Persona Fisica non valido.

in ambiente di qualificazione il cf forniti sono numerici (1013-1014) quindi l'unico test possibile è per il tipoDocumento 00035.
