### ISSUE TITLE
Errore invio S4 dopo S2 prima di SC1

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#1658]
Buongiorno, test effettuato da SATER il 21 agosto., IdAppalto a07fd827-1946-4d7c-846e-c0b6209016b6
A seguito della scheda confermata S2 per il lotto 4 inviata scheda S4 lasciando lo stesso IdPartecipante dell’OE “France Auto” presente nella S2 e ricevuto ERR2 "La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata".

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Da specifiche indicate sull'orchestratore la scheda S4 non è ammessa a fronte di una S2 confermata, l'unica scheda S consentita è la S3.</p>

<p>L'errore riscontrato è quindi coerente per l'azione intrapresa.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
