### ISSUE TITLE
Consip] Rettifica schede post-pubblicazione

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1659]
Salve,
è confermato che si possano rettificare (rettifica-avviso) le schede di post-pubblicazione che prevedono l'avviso?

ovvero le seguenti schede (estratte dall'orchestratore filtrando a "SI" la colonna N):

- A1_29
- A1_30
- A1_31
- A1_32
- A1_33
- A1_34
- A1_35
- A1_36
- A1_37
- A2_29
- A2_30
- A2_31
- A2_32
- A2_33
- A2_34
- A2_35
- A2_36
- A2_37
- A3_4
- A3_5
- A4_1
- A4_2
- A4_3
- A4_4
- A4_5
- A4_6
- A7_1_1
- A7_1_2
- NAG
- M1
- M1_40
- M2
- M2_40

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>si il rettifica avviso funziona solo su avvisi pubblicabili ed è possibile se lo stato del flusso dell'appalto è coerente. Inoltre, la rettifica è possibile se la scheda che si vuole rettificare è l'utlima confermata.</p>

<p>Non si può rettificare una scheda invece, se in un bando di gara si è arrivati ad una fase conclusiva.</p>

<p>Restiamo a disposizione per eventuali chiariementi.</p>

<p>Cordiali saluti</p>
