### ISSUE TITLE
Servizio Verifica Scheda

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#166]
Sulla base di quanto riportato al paragrafo 9 del documento documento-specifiche-servizi-npa.md:

_conferma-scheda: il servizio serve a confermare i dati della Scheda e per poter essere invocato è necessario che questa sia in stato “IN LAVORAZIONE” dopo la creazione o modifica di una scheda in bozza. Il sistema, attraverso l’invocazione del servizio verifica-scheda, provvede alla validazione dei dati della scheda. Tale validazione è orchestrata da un Workflow Engine che, tramite il suo motore di regole effettua le seguenti operazioni:  1) verifica se la scheda dati è coerente con lo stato dell’Appalto /  2) effettua una validazione sintattica dei dati di input._

Confermate che:

1) Nel momento in cui la SA triggera il **conferma scheda**, PCP per fornire il riscontro necessario provvederà ad invocare autonomamente ed internamente il servizio **verifica scheda**?

2) Qualora la risposta al punto 1) sia affermativa, possiamo considerare che il **conferma appalto** e **verifica appalto** funzionano allo stesso modo?

**Comment by supportoAnac** [comment]
1) Il servizio /conferma-scheda invoca il servizio /verifica-scheda prima di attivare la propria funzionalità.
2) Si conferma che /verifica-appalto e /conferma-appalto funzionano analogamente a /verifica-scheda e /conferma-scheda: /verifica-scheda e /verifica-appalto non incidono sullo stato dell'appalto, mentre le operazioni di conferma successivamente all'esito positivo della verifica consentono all'appalto di proseguire allo stato successivo.
