### ISSUE TITLE
Impossibilità invio CM1 dopo invio SC1

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#1662]
Buongiorno, in funzione delle analisi svolte sulle procedure svolte in SATER avremmo necessità di poter inviare la scheda CM1 anche a valle dell'invio della SC1 e in generale anche durante la fase di esecuzione del contratto, infatti gli errori o le omissioni sono anche di molti mesi fa ed evidentemente allo stato su molti di quegli affidamenti il contratto è già stato stipulato ed è in esecuzione.

**Comment by obigno77** [comment]
La scheda CM1 può essere inviata una sola volta e non dopo che sono state già inviate schede di esecuzione. Si prega di invitare le stazioni appaltanti a fare attenzione agli errori commessi prima di procedere oltre.
