### ISSUE TITLE
[CONSIP] Issue 1574 -  I campi non compilati ( di conseguenza null) devono essere inclusi nel payload ?

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1663]
Salve,
dalla risposta ricevuta alla issue #1574 si evince che la regola non scatta in quanto l’attributo appalto.motivazioneCIG non è presente nel payload della scheda, mentre la regola vuole che sia presente e pari a null. 
Il dato non è presente nel payload in quanto non è stato compilato dall'utente. In diversi meeting ci fu indicato che i campi non compilati ( e di conseguenza null) non devono essere inclusi nel payload inoltrato al richiamo dei vari servizi esposti da ANAC in quanto potrebbero far applicare validazioni non coerenti. 

Vi chiediamo pertanto una conferma. I campi non compilati dall'utente (e di conseguenza null) devono essere inclusi o meno nel payload ?

Grazie mille

**Comment by supportoAnac** [comment]
Gentile utente,

ci teniamo a informarla che l'attributo _appalto.motivazioneCIG_ non è obbligatorio e, pertanto, non è necessario inserirlo nel payload. Tuttavia, anche se tutte le altre condizioni fossero state soddisfatte, l'assenza di _motivazioneCIG_ comporta che la regola non possa essere attivata. Di conseguenza, affinché la regola possa essere attivata, è necessario inserire il campo _motivazioneCIG_, anche se con valore _null_.

Restiamo a disposizione per eventuali chiarimenti.

Cordiali saluti.

**Comment by anac-uscp** [comment]
<p>Gentile utente,<br>
<br>
Con riferimento alla vostra richiesta, confermiamo che i campi non compilati dall'utente (e di conseguenza con valore <code>null</code>) <strong>non devono essere inclusi</strong> nel payload inviato ai servizi esposti da ANAC.</p>

<p>Nel caso specifico della proprietà <code>motivazioneCIG</code>, la regola attualmente prevede che il campo sia definito nel payload e che abbia un valore pari a <code>null</code> per poter essere considerato. Tuttavia, alla luce della conferma fornita, procederemo con una correzione della regola, in modo che il comportamento sia coerente.</p>

<p>Restiamo a disposizione per eventuali ulteriori chiarimenti.</p>

<p>Cordiali saluti</p>
