### ISSUE TITLE
[Maggioli] Tempi di adozione delle nuove specifiche

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1664]
Nei [Tempi di adozione delle nuove specifiche](https://github.com/anticorruzione/npa#tempi-di-adozione-delle-nuove-specifiche) si fa riferimento al **rilascio della specifica** per conteggiare i termini di giorni concessi per l'adeguamento alle PAD.

Qual'è la data di rilascio della specifica?

1. E' la data di "Rilascio in Qualificazione" della nuova versione?
2. E' la data di "Pubblicazione contenuti su GitHub" delle specifiche (schede yaml, dmn, xlsx orchestratore...)?

Nel caso 2 potete taggare le specifiche quando le pubblicate su GitHub in modo da poterle identificare facilmente ed averne una versione e data di effettivo rilascio chiaramente definita?

Grazie

**Comment by obigno77** [comment]
Confermiamo che si tratta della data di pubblicazione dei contenuti aggiornati su github e prendiamo in carico la richiesta

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Si procede alla chiusura del ticket.</p>

<p>Saluti.</p>
