### ISSUE TITLE
Nuove schede CM1/CM2/ANN a seguito di issue 1622

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#1665]
Riporto la risposta che avete fornito all'issue 1622.
"Considerato che le schede CM1, CM2 e ANN sono previste per le schede senza oneri di pubblicazione a valore legale, sarà modificato l'orchestratore per la riconduzione delle suddette schede alle aree A2 'affidamento' e A3 'pubblicazione'."

Ma per le piattaforme che gestiscono la fase esecutiva (area A5) ed hanno già implementato queste schede potranno continuare a trasmetterle o avranno problemi?

**Comment by obigno77** [comment]
Per venire incontro a questa esigenza stiamo valutando di inserirle in entrambe le aree
