### ISSUE TITLE
Centri di costo associati ad un RP

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1666]

**Comment by AFSOLUZIONI** [comment]
come discusso diverse volte su vari tavoli, sarebbe utile (in alcuni casi ad elevata numerosità indispensabile) avere un servizio ulteriore in quello relativo alle anagrafiche AUSA che permetta di circoscrivere l'insieme dei centri di costo a tutti e soli quelli per i quali un determinato RP è censito. 
Infatti in sede di indizione di un Appalto, definito l'RP responsabile, le piattaforme di acquisto non hanno la possibilità di avere l'elenco dei centri di costo relativi allo specifico RP, ma solo l'elenco di quelli relativi alla SA che, in determinati casi, possono essere anche molte decine.

**Comment by gianlucacuomo** [comment]
Anche da Studio Amica ci associamo alla richiesta già avanzata in altre occasioni

**Comment by mariottiDPA** [comment]
ci associamo anche da DigitalPA

**Comment by obigno77** [comment]
La richiesta è già stata presa in carico ed è in attesa del rilascio in esercizio del nuovo servizio di user provisioning ANAC previsto entro la fine dell'anno corrente.
