### ISSUE TITLE
[Maggioli] Valore "other" nella tipologica motiviModifica

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#1668]
Buongiorno, ci siamo accorti che non c'è più il valore "other" nella tipologica motiviModifica, ma non troviamo traccia della modifica nel changeLog.
La modifica è documentata?

Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Nel changelo del 22/09/2023 sono state apportate delle modifiche alla tipologica, e dal 24/11/2023 il campo "other" è stato eliminato.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
