### ISSUE TITLE
Errore FVX48 su richiesta tipo documento 00038

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1669]
Stiamo implementando il servizio post per la richiesta dei documenti nel FVOE.
Come da specifiche per i "Tipi documenti richiedibili" (https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md), per il documento in questione "00038 - DURC inarcassa professionista" non è previsto nessun modello dati.

Però, quando effettuiamo la chiamata per la richiesta del documento riceviamo l'errore "FVX48 - Codice Fiscale Professionistra non valido"

govway-message-id: b62d5201-db58-4382-9228-4767f7877c15
govway-transaction-id: 2958770c-6aab-11ef-bd08-0050568e9679

Potreste fare una verifica per capire dove sta il problema?

**Comment by obigno77** [comment]
Il sistema tratta esclusivamente codici fiscali. Per i professionisti va indicato un codice fiscale di persona fisica.

**Comment by Gestore-Venicecom** [comment]
@supportoAnac @obigno77 @anac-uscp 

vi chiediamo cortesemente di aggiornare la documentazione relativa al servizio, poiché al momento risulta non allineata con le ultime versioni.

Inoltre, vi saremmo grati se poteste fornirci un esempio del payload corretto da utilizzare, poiché non riusciamo a far funzionare il servizio nonostante i tentativi effettuati.

Abbiamo già aperto diversi ticket per segnalare il problema, ma non abbiamo ricevuto risposte. Pertanto, vi sollecitiamo gentilmente a fornirci supporto con la massima urgenza.

Rimaniamo a disposizione per ulteriori dettagli o chiarimenti.

Grazie per la collaborazione.

Cordiali saluti,
