### ISSUE TITLE
Gestione della pubblicazione su TED e PPL-ANAC

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#167]
si presume che, a valle della chiamata del servizio "pubblica-avviso", per conoscere lo stato di avanzamento della pubblicazione sia da invocare il servizio "stato-avviso" il quale dovrebbe evidenziare se l'avviso è stato pubblicato. Alcuni quesiti:

1. se la pubblicazione deve essere fatta su entrambi i sistemi (TED e PPL-ANAC) come si fa a capire lo stato restituito a quale dei due si riferisce?
2. nel caso di stato "pubblicato" (almeno per il TED) vengono restituiti anche i dati di pubblicazione (numero, data e url di pubblicazione) che non si capisce dove debbano essere reperiti

Grazie.

**Comment by supportoAnac** [comment]
/stato-avviso indica unicamente lo stato dell'avviso in un dato momento. Per avere maggiori informazioni è possibile invocare il servizio /esito-operazione. La verifica specifica su uno dei due sistemi di pubblicazione può essere eseguita solo con /esito-operazione. 
I dati di pubblicazione forniti dal TED sono consultabili mediante il servizio /consulta-avviso che restituisce il dettaglio dell' avviso.
