### ISSUE TITLE
[CONSIP] - A4.4 - Err94 alla trasmissione scheda A4.4

### ISSUE THREAD

**Issue by alessiopera** [anticorruzione/npa#1670]
Salve, abbiamo effettuato questo test:
**Precondizione**: A seguito della trasmissione della scheda A4.4, riscontriamo errore 94: 
Stessa problematica a seguito di trasmissione delle schede A4.3, A4.5, A4.6, A2.29, A2.30

"codice":"ERR94",
    "descrizione": {
    "it": "errore generico durante la comunicazione con PVL",
    "en": "errore generico durante la comunicazione con PVL"
  },
    "dataInizio":null,
    "dataFine":null

**Di seguito la Response:**

{
    "result": {
        "exitCode": "400",
        "text": "Servizio momentaneamente non disponibile"
    },
    "payload": {
        "code": 400,
        "responseData": null,
        "errors": [
            {
                "errorCode": "400 KO",
                "shortDescription": "{\"instance\":null,\"status\":400,\"title\":\"KO\",\"detail\":\"Errore\",\"type\":\"about:blank\",\"errori\":[{\"idTipologica\":\"errori\",\"codice\":\"ERR94\",\"dettaglio\":\"[500] during [POST] to [
http://pcp-qlf-codelist-ms.pcp-qlf.svc:8080/recupera-valore-tipologiche]
[CodelistMsClient#recuperaValoreTipologiche(Map)]: [{\\\"timestamp\\\":\\\"2024-09-04T13:12:02.183+00:00\\\",\\\"status\\\":500,\\\"error\\\":\\\"Internal Server Error\\\",\\\"path\\\":\\\"/recupera-valore-tipologiche\\\"}]\"}]}",
                "keyMessage": ""
            }
        ]
    }

potete verificare?

**Comment by anac-uscp** [comment]
<p>Gentile Utente,</p>

<p>La problematica da Lei segnalata è stata risolta con una fix il giorno 20/09.</p>

<p>La invitiamo pertanto a riprovare. </p>

<p>Qualora dovesse ripresentarsi l'errore, La invitiamo ad aprire una nuova issue mandandoci l'idAppalto.</p>

<p> </p>

<p>Restiamo a disposizione.</p>

<p> </p>

<p>Cordiali Saluti</p>
