### ISSUE TITLE
[TOSCANA/BOLZANO] - Richiesta chiarimenti per nuove schede AOC, RSOC, COOC

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1671]
Salve,
potreste fornire il dettaglio degli acronimi per le nuove schede AOC, RSOC e COOC?

Non riusciamo a identificarne il flusso di appartenenza.

Grazie.

**Comment by anac-uscp** [comment]
<p>Buongiorno,<br>
<br>
Trattasi di schede specifiche per gli Organi Costituzionali (OOCC).<br>
<br>
Rispettivamente indizione, subappalto, conclusione.<br>
<br>
Saluti,</p>
