### ISSUE TITLE
Annullamento aggiudicazione

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1674]
Buongiorno,

riprendo la risposta fornita alla issue #1395 per un chiarimento.

in caso si debba revocare l'aggiudicatario indicato con la scheda A per aggiudicare ad un altro è stato dato riscontro che si invia la scheda CO1 per revocare l'aggiudicazione definitiva e poi si può procedere anche a sottoscrivere il contratto con altro soggetto. Tuttavia, dall'orchestratore non risulta possibile inviare una scheda SC1 (sottoscrizione contratto) dopo la scheda CO1.
Come si può procedere?

da altre indicazioni fornite nelle varie riunioni, era emerso che per aggiudicare ad altro soggetto (non quello indicato come 1 graduatoria e aggiudicatario nella scheda A) era sufficiente sottoscrivere il contratto con un OE inviato con la scheda A. Questa indicazione è ancora valida?

Grazie

**Comment by anac-uscp** [comment]
<p>Il comportamento suggerito è corretto. L'orchestratore sarà modificato nel primo changelog utile</p>
