### ISSUE TITLE
[Consip][P1*] - response stato-avviso incongruente 

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1675]
è stata effettuata una richiesta di pubblicazione (pubblica-avviso) su una scheda P1_17.

risulta una response incongruente tra i servizi esito-operazione e stato-avviso tale per cui nel primo caso la richiesta risulta **IN_ATT_PUBB** e nel secondo caso **PUBB**.

tentando di inviare una scheda di post-pubblicazione otteniamo **ERR2 - scheda non ammessa in questa fase dell'appalto**, nonostante lo stato dell'avviso sia **PUBB**.

**stato-avviso**

{
  "status": 200,
  "title": "OK",
  "detail": "Operazione Effettuata",
  "type": "about:blank",
  "statoAvviso": {
    "idAvviso": "0d71e17c-b20d-4bc0-9f58-004f1765f55f",
    "idAppalto": "ed635a19-48ef-46b0-bfec-07c86f04c007",
    "dataControllo": "2024-09-05T16:15:12.506+00:00",
    "stato": {
      "idTipologica": "statoAvviso",
      "codice": "PUBB"
    }
  }
}

**esito-operazione**

{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "ed635a19-48ef-46b0-bfec-07c86f04c007",
      "idScheda": "1273ce40-5602-488c-8777-2c27ae84792c",
      "codiceScheda": "P1_17",
      "idAvviso": "0d71e17c-b20d-4bc0-9f58-004f1765f55f",
      "esito": {
        "idTipologica": "esito",
        "codice": "OK"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AV_PUBB"
      },
      "dataControllo": "2024-09-04T15:48:22.507+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AV_IN_PUBB"
      }
    }
  ]
}

**Comment by alessiopera** [comment]
La stessa problematica si rileva anche per le schede P1_14 e P1_19

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p> </p>

<p>è stata effettuata una bonifica sui nostri sistemi per risolvere la problematica.</p>

<p>Pertanto la invitiamo a proseguire con la gara.</p>

<p> </p>

<p>Restiamo a disposizione.</p>

<p> </p>

<p>Cordiali saluti</p>
