### ISSUE TITLE
ESPD per schede P3_1 e P3_2

### ISSUE THREAD

**Issue by FabioCassanelli** [anticorruzione/npa#1676]
Si prende atto che con l'ultimo aggiornamento il campo "includeESPD" per la scheda P3_1 è stato modificato da SI a NO.
Lo stesso non è stato fatto per la scheda P3_2.
In considerazione del fatto che le stazioni appaltanti sono interessate a scegliere, anche di volta in volta, se richiedere o meno il DGUE, si chiede che per entrambe le schede il campo sia valorizzato a "SI, NO", come già avviene per le schede P6_1, P6_2, P4_1, P4_2, P4_3, P4_4, P4_5, P4_6, P7_2, AD3, AD4, AD5.

Grazie

**Comment by obigno77** [comment]
In uno dei prossimi changelog il tag sarà aggiunto nuovamente nella P3_1 come facoltativo e reso facoltativo per la scheda P3_2

**Comment by FabioCassanelli** [comment]
Si chiede cortesemente quando è prevista la modifica delle schede P3_X per rendere facoltativo il DGUE, grazie
