### ISSUE TITLE
[TOSCANA/BOLZANO] Richiesta chiarimenti Flusso 72

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1677]
Salve, 
in riferimento alla risposta fornita alla issue: https://github.com/anticorruzione/npa/issues/1414

Chiedo spiegazioni in merito a quanto affermato:
<img width="408" alt="image" src="https://github.com/user-attachments/assets/bdd1af3f-87bf-4dad-959a-ed7a4451a06b">

In base all'orchestratore, i contratti esclusi, indipendentemente da settore, regime o soglia, vengono trasmessi tramite la scheda P3_1 (e quindi seguono il flusso 31).
Tuttavia, dalla risposta alla issue sopra citata, sembrerebbe che i contratti esclusi relativi alle negoziate senza bando debbano essere trasmessi:

- Inviando la **scheda P7_2**

- Inviando **l’eform 27** - Avviso volontario per la trasparenza ex ante – previsto per il **settore della difesa.**

Chiedo gentilmente ulteriori chiarimenti in merito.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Per quanto riguarda i contratti esclusi, è necessario fare una distinzione tra i diversi ambiti di applicazione:</p>

<ol>
	<li>
<strong>Contratti esclusi in generale</strong>:

	<ul>
		<li>L'orchestratore prevede che questi contratti, indipendentemente dal settore, regime o soglia, siano trasmessi tramite la scheda <strong>P3_1</strong>, seguendo il flusso 31.</li>
	</ul>
	</li>
	<li>
<strong>Contratti esclusi relativi al settore della difesa e sicurezza</strong>:
	<ul>
		<li>Per i contratti esclusi nel settore della difesa e sicurezza, in base all'orchestratore e alle disposizioni normative (art. 52 del <strong>D.Lgs. 208/2011</strong>), il flusso prevede:
		<ul>
			<li>L'invio della scheda <strong>P7_2</strong>, specifica per la gestione delle negoziate senza bando in questo settore.</li>
			<li>La trasmissione dell’<strong>eForm 27 – Avviso volontario per la trasparenza ex ante</strong>, richiesto per garantire la trasparenza e la tracciabilità delle procedure nel settore della difesa.</li>
		</ul>
		</li>
	</ul>
	</li>
	<li>
<strong>Distinzione tra schede P3_1 e P7_2</strong>:
	<ul>
		<li>La scheda <strong>P3_1</strong> è utilizzata per contratti esclusi che non richiedono particolari obblighi di trasparenza aggiuntiva.</li>
		<li>La scheda <strong>P7_2</strong> è obbligatoria per le procedure negoziate senza bando nel settore della difesa e sicurezza, dove la normativa impone anche l'invio dell'eForm 27 come ulteriore misura di trasparenza.</li>
	</ul>
	</li>
</ol>

<p>In sintesi, per i contratti esclusi nel settore della difesa/sicurezza, è corretto seguire il flusso <strong>P7_2 + eForm 27</strong>. Per altri settori o tipologie di contratti esclusi, è sufficiente utilizzare la scheda <strong>P3_1</strong>.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
