### ISSUE TITLE
Discrepanze tra i servizi del contesto pubblicaAvviso ed il diagramma di stato degli avvisi

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#168]
i servizi presenti nella documentazione sono 8:

1. pubblica-avviso
2. modifica-avviso
3. rettifica-avviso
4. cancella-avviso
5. ricerca-avviso
6. consulta-avviso
7. consulta-rendering-avviso
8. stato-avviso

Sarebbe utile comprendere il significato del servizio crea-avviso: si può presupporre che sia un servizio (non esposto) che viene invocato al termine con esito positivo del processo di conferma-appalto, ma sarebbe gradita una precisazione in tal senso.
E' importante comprendere la differenza tra il servizio "stato-avviso" nel contesto pubblicaAvviso e quello di "esito-operazione"  del contesto serviziComuni. Dalla documentazione sembra che gli stati dell'avviso debbano essere recuperati tramite il servizio "stato-avviso", mentre il diagramma di stato fa riferimento al servizio "esito-operazione": qual è l'interpretazione giusta??
Infine dal servizio pubblica-avviso si desume che viene attivata la pubblicazione sia su TED sia su PPL-ANAC. Non è chiaro come avviene tale pubblicazione:

1. Implicitamente vengono avviate entrambe le pubblicazioni?
    in questo caso come è possibile seguire la pubblicazione TED e quella PPL-ANAC che,
    ovviamente hanno tempi diversi??
2. Se l'avvio in pubblicazione non è implicito, qual è il parametro da utilizzare per richiedere l'uno o l'altro??
3. Nei servizi successivi (e.g. modifica, cancella, rettifica) come si fa ad individuare a quale delle pubblicazioni fanno riferimento??

Grazie

Grazie

**Comment by supportoAnac** [comment]
La differenza tra stato-avviso ed esito-operazione: 
- /stato-Avviso restituisce lo stato corrente in cui si trova l'avviso.
-  /esito-Operazione restituisce l'esito di ogni operazione asincrona e l'avanzamento dell'attività di backend quando possibile, con indicazione dell'avanzamento e di eventuali errori riscontrati.
/esito-operazione consente di avere informazioni sugli stati intermedi del processo invocato e nello stato finale riporta informazioni utili per l'avanzamento della gestione da parte della piattaforma. idAvviso viene restituito con questo servizio. 

Vedere anche  https://github.com/anticorruzione/npa/issues/167 .

**Comment by FRASCA57** [comment]
Per quanto concerne il servizio crea-avviso??
E' possibile avere una risposta sull'argomento?
