### ISSUE TITLE
Richiesta chiarimenti scheda SA1 - Importo SAL

### ISSUE THREAD

**Issue by dellattiDPA** [anticorruzione/npa#1680]
Gent.mi, 
al fine di poter gestire correttamente i dati in Piattaforma chiediamo con la presente necessari chiarimenti circa la più corretta modalità di compilazione della scheda SA1.
In particolare è necessario ottenere chiarimento circa la corretta implementazione del campo “imp sal”. Nello specifico, si chiede se, in caso di più schede SA1, il campo “imp sal”:
•	OPZIONE 1: dovrà contenere l’importo CUMULATIVO e progressivo dei pagamenti. Ad esempio, 
-	prima liquidazione € 100 – scheda SA1 con campo imp sal “100”
-	seconda liquidazione altri € 100 – scheda SA1 campo imp sal “200”
oppure se
•	OPZIONE 2: dovrà contenere ogni volta l’importo riferibile all’ultima liquidazione eseguita. Ad esempio, 
-	prima liquidazione € 100 – scheda SA1 con campo imp sal “100”
-	seconda liquidazione altri € 100 – scheda SA1 campo imp sal “100”

Ciò chiarito, si chiede altresì conferma che, come presumibile, detta scheda, sebbene descritta nell’Orchestratore “Stato Avanzamento lavori per qualunque procedura”, sia da svolgere tanto in caso lavori che di servizi e forniture e se conseguentemente la modalità di compilazione che verrà indicata come corretta debba intendersi comune a lavori servizi e forniture.

**Comment by anac-uscp** [comment]
<p>Buongiorno,<br>
<br>
In relazione ai vostri quesiti:<br>
<br>
- Vale l'Opzione 1, come indicato al punto D1 delle Faq sugli "Obblighi informativi", disponibili all'indirizzo https://www.anticorruzione.it/-/obblighi-informativi-verso-l-autorità<br>
- Le indicazioni valgono anche per Servizi e Forniture<br>
<br>
Saluti,</p>
