### ISSUE TITLE
[SISGAP][BLK] A2_29 - errore ERR94 su esito-operazione

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1683]
Stiamo riscontrando il seguente errore su esito-operazione della A2_29 per l'aggiudicazione di una P7_2:

errore generico durante la comunicazione con PVL: [500] during [POST] to [
http://pcp-qlf-codelist-ms.pcp-qlf.svc:8080/recupera-valore-tipologiche]
[CodelistMsClient#recuperaValoreTipologiche(Map)]: [{"timestamp":"2024-09-13T08:48:44.004+00:00","status":500,"error":"Internal Server Error","path":"/recupera-valore-tipologiche"}].

Test fatto in ambiente di QUALIFICAZIONE
govway-message-id: 997b1250-7482-4558-8da4-36aa89a54aca
govway-transaction-id: 348fcb83-71ab-11ef-988f-0050568e08b3
idAppalto: 645b728b-3174-4831-809b-907dbc3a2084

Abbiamo una gara negoziata in produzione che presto arriverà alla fase di aggiudicazione.
Potreste darci un veloce riscontro?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>si chiede gentilmente la request completa che è stata inviata per la scheda, in modo da poter analizzare al meglio la casistica.</p>

<p>Restiamo in attesa di un suo riscontro.</p>

<p>Cordiali saluti.</p>

<p> </p>
