### ISSUE TITLE
Scheda P7_3 - Informazioni sui lotti

### ISSUE THREAD

**Issue by CecereAnto** [anticorruzione/npa#1684]
Buongiorno,

la seguente issue per chiedere se è corretto che ci siano informazioni relative ai lotti per la scheda P7_3 . 

Ci spiegate il motivo della presenza dei lotti nella scheda p73?

Vi ringrazio.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style="line-height:107%;"><span style='font-family:"system-ui",serif;'>la presenza delle informazioni sui lotti nella scheda P7_3 è corretta perché questa scheda è progettata per gestire procedure che possono includere lotti. I campi relativi ai lotti servono a specificare oggetti, importi e criteri di aggiudicazione per ciascun lotto. </span></span></span></span></span></span></p>

<p><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style="line-height:107%;"><span style='font-family:"system-ui",serif;'>Restiamo a disposizione per eventuali chiarimenti.</span></span></span></span></span></span></p>

<p><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style="line-height:107%;"><span style='font-family:"system-ui",serif;'>Cordiali saluti.</span></span></span></span></span></span></p>
