### ISSUE TITLE
CHANGELOG-2 Gestione della regole REG113 (Se il campo condizioniNegoziata.codice=46(SDA) allora il campo idSDA rilasciato da ISDA1 e ISDA2 deve essere obbligatoriamente valorizzato.)

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1686]
Con il changelog in oggetto entra in funzione la regola di controllo di presenza del riferimento allo SDA per il quale si sta inserendo un Appalto Specifico.
Non è chiaro come si debba gestire il caso di Appalti Specifici il cui SDA sia stato pubblicato prima dell'entrata in produzione della relativa scheda di censimento.

**Comment by paolo-urbanetto** [comment]
Ci aggiungiamo anche noi [Maggioli] alla richiesta. Grazie

**Comment by obigno77** [comment]
La regola sarà smontata prima del rilascio
