### ISSUE TITLE
AD3 - Valorizzazione campi "valore base d'asta" ed "importo complessivo a base di gara" 

### ISSUE THREAD

**Issue by dellattiDPA** [anticorruzione/npa#1688]
Si richiedono chiarimenti in merito alla valorizzazione dei campi "**valore base d'asta**" ed "**importo complessivo a base di gara**" che 

vengono pubblicati in BDNCP relativamente alle schede AD3.

Nelle AD3 l'unico campo  relativo  all'importo è quello del partecipante che valorizza il campo "valore aggiudicazione". 

 Sembrerebbe che il valore inserito in questo campo venga replicato sui campi "valore base d'asta" e "importo complessivo a base di gara" su BANCA DATI , ma questi campi non esistono nella scheda e non vengono in alcun modo valorizzati.

Si richiede pertanto di:

1. Indicare in che modo questi campi vengono valorizzati.
2. Nel caso in cui il funzionamento attuale è quello indicato, se sono previste modifiche a a questa scheda

Link di esempio: https://dati.anticorruzione.it/superset/dashboard/dettaglio_cig/?cig=B199B585B0&standalone=2

**Comment by obigno77** [comment]
Nel caso di affidamenti diretti AD entrambi i campi del template di BDNCP/analytics sono valorizzati con l'importo di aggiudicazione. Abbiamo preso in carico la segnalazione e nasconderemo il valore a base d'asta negli affidamenti diretti perchè non è gestito il caso di acquisizione di più preventivi con definizione di una base d'asta
