### ISSUE TITLE
Errore Produzione 400

### ISSUE THREAD

**Issue by petromanco** [anticorruzione/npa#1689]
Buongiorno,
richiamando l'e-service consulta-appalto il sistema mi ritorna il seguente errore:
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "0b8d64d6-798d-11ef-852e-005056844885"
}
È possibile ricevere il dettaglio?

Grazie

**Comment by obigno77** [comment]
Questo non è il canale di supporto per i sistemi in esercizio.
L'errore è che il token JWS è arrivato 4 minuti dopo la sua generazione. La durata di validità del token JWS è di 10 secondi.
