### ISSUE TITLE
Contesto gestioneUtenti

### ISSUE THREAD

**Issue by ferdinandjmaddela** [anticorruzione/npa#169]
Avremo bisogno di chiarimenti sui seguenti punti.

1) questo contesto serve a gestire le procedure in delega oppure le procedure normali?
2) Ai fini della pubblicazione di una gara (per invocare il servizio _crea-appalto_ ) occorre fornire alla PDND un codice fiscale associato ad un utente della piattaforma fruitrice che risulta anche come RUP/RP su ANAC (vedere punto 4 della issue #4) . Confermate?
3) Qual è la differenza principale tra _aggiungi-soggetto_ e _presa-carico_? è corretta la nostra interpretazione nell esempio di seguito?

- aggiungi-soggetto: permette ad _utente1RP_ (che ha già invocato il 'crea-appalto' per l'appalto X) di delegare ad _utente2RP_ la possibilità di invocare uno dei servizi presenti nella tabella indicata al paragrafo **4.5 Servizi e ruoli** del file documento-specifiche-servizi-npa.md. per l'appalto X;
- presa-carico: permette ad _utente3RP_ di associare l'appalto X a se stesso in autonomia.

**Comment by supportoAnac** [comment]
Il servizio è rivolto ai soli utenti RUP e delegato del RUP previsti dall'art. 15 del codice; non fa nessun riferimento alla procedure in delega gestite dalle Stazioni Appaltanti. Il RUP titolare dell'appalto è colui che invoca il servizio crea-appalto e può essere sostituito da un diverso RUP attraverso il servizio presa-carico. I servizi aggiungi-soggetto ed elimina-soggetto hanno lo scopo di affiancare al RUP titolare dell'appalto i responsabili delegati alle singole fasi previsti dal comma 4 dell'art.15.
