### ISSUE TITLE
Reperimento codici piattaforma

### ISSUE THREAD

**Issue by petromanco** [anticorruzione/npa#1690]
Vorrei sapere come e dove poter reperire i dati per valorizzare le proprietà **regCodicePiattaforma** e **regCodiceComponente** da indicare nel token per invocare gli e-service dalla piattaforma in produzione.

Grazie

**Comment by obigno77** [comment]
Gli UUID sono pubblicati su https://dati.anticorruzione.it/#/regpiacert
