### ISSUE TITLE
Utente non autorizzato SEC05

### ISSUE THREAD

**Issue by petromanco** [anticorruzione/npa#1691]
{
    "RESPONSE-MESSAGE": {
        "status": 401,
        "title": "KO",
        "detail": "Non Autorizzato",
        "type": "about:blank",
        "errori": [
            {
                "idTipologica": "errori",
                "codice": "SEC05"
            }
        ]
    }
}

"GovWay-Message-ID": "2789ebfb-ae42-4c74-aa4d-79e056612661",
"GovWay-Transaction-ID": "36eb9c42-79a5-11ef-a2a9-00505684399c",

Richiamando l'e-service **consulta-appalto** mi ritorna quest'errore posso avere il dettaglio?

**Comment by obigno77** [comment]
Questa è una transazione di esercizio. Si ricorda che questo canale è di supporto ai test in ambiente di qualificazione chiedendo di utilizzare la casella mail dedicata al supporto in esercizio: supporto.pcp@anticorruzione.it
Nel caso specifico l'utente non è profilato su ANAC come RUP della stazione appaltante con il codice AUSA indicato.
