### ISSUE TITLE
rinnovo schede AD e aggiornamento CUP

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1692]
Buongiorno,

è stata fornita indicazione in altre issue che per i rinnovi si usa la scheda di modifica contrattuale (M1*) ma dai flussi di appartenenza nell'orchestratore ad es. per la scheda AD3 le schede M1* è utilizzabile per il flusso della AD3 (flusso 30). Come può un'utente dare evidenza che sta applicando il rinnovo al contratto scaturito da una AD3?

inoltre, è con le schede di modifica contrattuale che l'utente potrebbe aggiornare i CUP associati all'appalto? in particolare, alcuni utenti ci hanno segnalato che potrebbe rendersi necessario aggiungere un CUP in fase di rinnovo contrattuale, come potrebbero fare tramite i servizi?

Grazie

**Comment by anac-uscp** [comment]
<p>Per la modifica contrattuale delle schede AD_3, l’orchestratore è già stato modificato per prevedere l’invio della scheda M2 nel flusso 30. Il riferimento alla M1 è errato per la scheda AD_3. <br>
 </p>
