### ISSUE TITLE
[BOLZANO/TOSCANA] - Richiesta Accesso FVOE - "Persona giuridica" 

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1693]
Salve,
all'interno del servizio /RichiestaAccessoFVOE ho notato che la voce **"Persona giuridica"** non è stata più rimossa. 

<img width="436" alt="image" src="https://github.com/user-attachments/assets/c2c5270a-2dff-4546-82ab-7593c3153e5a">

È possibile specificare il **tipo di dato** da inserire in questo campo?

**Comment by stalex1** [comment]
Gentile Utente,

Per quanto riguarda il servizio /RichiestaAccessoFVOE, la struttura è sempre la stessa, con la sola variazione dei dati in base al servizio richiesto.

I campi obbligatori da inserire sono:

IdAppalto: l’identificativo dell’appalto;
CF OE: il codice fiscale dell’Operatore Economico (OE);
Data inizio Autorizzazione: la data da cui parte l’autorizzazione.
Per ulteriori dettagli, puoi consultare la documentazione ufficiale ai seguenti link:

- [npa/docs/scenari-di-esempio/gestione_fascicolo.md at main · anticorruzione/npa · GitHub](https://github.com/anticorruzione/npa/blob/main/docs/scenari-di-esempio/gestione_fascicolo.md)
- [npa/docs/specifiche-interfacce/specifiche-servizi-fvoe-fva.yaml at main · anticorruzione/npa · GitHub](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/specifiche-servizi-fvoe-fva.yaml)

Restiamo a disposizione



Cordiali Saluti
