### ISSUE TITLE
[Consip][INFO] changelog-2 schede SDA

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1694]
salve,
le date di rilascio del changelog-2 risultano essere le seguenti:
Pubblicazione contenuti su GitHub: 12/09/2024
Rilascio in Qualificazione: 24/09/2024
Rilascio in Esercizio: 24/10/2024

all'interno dell'orchestratore si vede che la data di inizio validità scheda è gennaio 2025.

**ci confermate che le schede potranno essere testate in qualificazione dal 24/09/2024 ma che in esercizio potranno essere adoperate solo dal 2025?** 
grazie

![image](https://github.com/user-attachments/assets/ef494348-6251-4b57-8517-c9dfd880e890)

**Comment by obigno77** [comment]
Le date indicate nei changelog e la conclusione delle attività pianificate vengono costantemente aggiornate sul changelog stesso

**Comment by anac-uscp** [comment]
<p>Le date indicate nei changelog e la conclusione delle attività pianificate vengono costantemente aggiornate sul changelog stesso</p>
