### ISSUE TITLE
[Consip][INFO] aggiudicazione ed esecuzione schede SDA

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1695]
salve,
da orchestratore il flusso per le schede SDA sembra essere il seguente:

- ISDA1, S0, CSDA1
- ISDA2, S0, CSDA2

non è prevista nessuna scheda di aggiudicazione per lo SDA?
le schede di esecuzione (SC1, SA1, SO1, ecc) non sono previste nei flussi dello SDA?

grazie

**Comment by obigno77** [comment]
No
