### ISSUE TITLE
[ARIA SpA] "ERR94: errore generico durante la comunicazione con PVL" in fase di aggiudicazione #1621

### ISSUE THREAD

**Issue by lmanc77** [anticorruzione/npa#1696]
Buongiorno,

a valle di ulteriori test eseguiti in data 17/09/24, si segnala che il problema persiste, nonostante la risposta in chiusura della issue #1621

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>la fix per la problematica é andata online, pertanto si invita a riprovare.<br>
<br>
Restiamo a disposizione.<br>
<br>
Cordiali saluti</p>
