### ISSUE TITLE
[CONSIP][BLK] REG98 e REG99 su P1_23

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1698]
Salve,
a seguito dell'ultimo rilascio (changelog) risulta impossibile trasmettere la scheda P1_23.
al crea appalto otteniamo REG98 e REG99.
abbiamo visto che le due regole erano state rimosse dal DMN ma sono state reinserite con l'ultima versione.
potete verificare?

![image](https://github.com/user-attachments/assets/279fa604-f7ec-45b1-abc8-e5c7e22424e3)

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Per errore erano state reintrodotte le REG98 e REG99 per le schede P1_23 e P1_24. Con l'ultimo rilascio sono state rimosse, per cui si prega di riprovare la procedura.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p> </p>

<p>Cordiali saluti.</p>
