### ISSUE TITLE
[BLK] [Maggioli] Scheda P6_2 - Incoerenza regola 67 e modello scheda

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1699]
Buongiorno,
segnalo che il problema di cui alla precedente issue [1194](https://github.com/anticorruzione/npa/issues/1194) non pare risolto.
Se la procedura "Negoziata senza previa indizione di gara" non è accelerata, non dovrebbe richiedere obbligatoriamente la giustificazione della procedura accelerata.

In pratica andrebbe aggiunto nella regola:
and "proceduraAccelerata": true

Grazie

**Comment by anac-uscp** [comment]
<p><strong>Gentile utente,</strong></p>

<p>la correzione è stata rilasciata in esercizio in data <strong>17-12-2024</strong>. La invitiamo a verificare nuovamente.<br>
<br>
Restiamo a disposizione.</p>

<p>Cordiali saluti</p>
