### ISSUE TITLE
Pubblicità Programmazione

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#17]
Come da **documento-specifiche-servizi-npa.md**:

Il sistema concentra i servizi erogati in precedenza da diversi soggetti/sistemi in particolare:
Il Servizio Contratti Pubblici (SCP) del MIT per la pubblicità della programmazione e di bandi e avvisi

All'interno del documento non vi è poi alcun riferimento ai servizi per la pubblicazione dei piani biennali/triennali. Attualmente disponiamo di un integrazione funzionante con i servizi di SCP MIT, **nell'ambito di NPA rientra anche la gestione della pubblicazione dei piani biennali/triennali o avranno un altro servizio appositamente dedicato o non sarà più necessario inoltrarli**

**Comment by supportoAnac** [comment]
Nel contesto pianificazioneAppalto sono inclusi i servizi utili alla gestione della prima fase di pianificazione e programmazione mediante la creazione e la conferma dell’Avviso di Preinformazione.
Potranno essere utilizzati anche per la comunicazione dei piani biennali/triennali.
