### ISSUE TITLE
Orario disponibilità servizi

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#170]
Se esiste un tempo giornaliero di fine (h.18), quale è l'ora di inizio?

Con riferimento alla isssue #142 è possibile conoscere l'elenco dei servizi non richiamabili dopo le 18.
Tale informazione è necessaria per definire la cadenza di alunci batch e valutare organizzativamente cosa gli utenti in piattaforma potranno fare o meno.

**Comment by supportoAnac** [comment]
Nella configurazione iniziale tutti i servizi sono richiamabili in qualsiasi momento. Le richieste di pubblicazione ricevute dopo le 18.00 vengono considerate come ricevute il giorno successivo.
