### ISSUE TITLE
Area A_1 Pianificazione

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#1700]
Buongiorno,

Stiamo collaudando il servizi per l'area funzionale di pianificazione (A_1). Rispetto a questa mattina, con i medesimi parametri, non riusciamo più ad ottentere un token di autenticazione valido. Come descritto sotto:
- chiamata in POST effettuata il 2024-09-24 alle ore 08:46:26
https://auth.uat.interop.pagopa.it/token.oauth2
con questi parametri (i tre asterischi sono per non diffondere informazioni riservate)

client_id=a36157b4-e15b-45***&client_assertion=eyJraWQiOiJ***&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=client_credentials

mi restituisce la seguente risposta
{
      "correlationId": "d24a1cb4-10a3-493b-a1e1-e990e9cccb56",
      "errors": [
            {
                  "code": "015-0008",
                  "detail": "Unable to generate a token for the given request"
            }
      ],
      "status": 400,
      "title": "The request contains bad syntax or cannot be fulfilled.",
      "type": "about:blank"
}

Saluti e grazie

**Comment by obigno77** [comment]
Non è un problema di ANAC ma di PagoPa. Probabilmente l'errore si è verificato durante la finestra di disservizio programmato di PDND
