### ISSUE TITLE
ISDA1 - eForm da utilizzare per la pubblicazione TED

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1704]
si richiede conferma di quanto emerge dall'orchestratore:
gli eForm da utilizzare sono in alternativa:
1. CN10 - Avviso pre-informazione settore ordinario
2. CN11 - Avviso di pre-informazione settori speciali
3. CN16 - Bando Gara sopra soglia comunitaria settore ordinario
4. CN17 -Bando Gara sopra soglia comunitaria settori speciali

si chiede ulteriormente perchè la scelta non è caduta sulla eForm CN15 che sembra essere più attinente a sistemi di qualificazione dei fornitori.
Si sottolinea altresì la complessità di compilazione di tali eForm a fronte delle informazioni a disposizione al momento della pubblicazione dello SDA.

**Comment by anac-uscp** [comment]
<p>Si evidenzia che il proposto eForm CN15 è relativo all’ Avviso sull'esistenza di un sistema di qualificazione, tipico dei settori speciali. Quindi non sarebbe confacente alle caratteristiche di uno SDA.</p>
