### ISSUE TITLE
Scheda S0 - modalità di utilizzo

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1706]
Si chiede conferma delle modalità di utilizzo della scheda S0:

1. La scheda può essere inviata più volte per lo stesso SDA
2. Il contenuto della scheda rappresenta un aggiornamento degli Operatori Economici iscritti e non una completa riproposizione degli stessi
3. la scheda S0 confermata consente l'apertura dell'FVOE degli OE in essa contenuti
4. descrivere meglio il significato dei valori presenti nella tipologica operazioneSDA.json

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">La scheda S0 è utilizzata per comunicare all'ANAC l'elenco degli Operatori Economici (OE) iscritti a un Sistema Dinamico di Acquisizione (SDA). Di seguito, le modalità di utilizzo e le specifiche relative alla scheda S0:</span></span></p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">Invio multiplo della scheda S0 per lo stesso SDA:</span></span></p>

<p><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style="line-height:107%;">È possibile inviare la scheda S0 più volte per lo stesso SDA. Ogni invio successivo rappresenta un aggiornamento dell'elenco degli OE iscritti.</span></span></span></span></span></p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">Contenuto della scheda S0:</span></span></p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">La scheda S0 non richiede la riproposizione completa dell'elenco degli OE iscritti. Ogni invio deve contenere solo le variazioni intervenute, come nuove iscrizioni o cancellazioni.</span></span></p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">Apertura del Fascicolo Virtuale dell'Operatore Economico (FVOE):</span></span></p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">La conferma della scheda S0 consente l'apertura del FVOE per gli OE in essa contenuti. Questo facilita la verifica dei requisiti degli operatori da parte delle stazioni appaltanti.</span></span></p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">Significato dei valori presenti in "operazioneSDA.json":</span></span></p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">Il file "operazioneSDA.json" contiene i codici che identificano le operazioni relative agli OE nel contesto dell'SDA. I principali valori sono:</span></span></p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">01: Iscrizione di un nuovo OE all'SDA.</span></span></p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">02: Aggiornamento dei dati di un OE già iscritto.</span></span></p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">03: Cancellazione di un OE dall'SDA.</span></span></p>

<p><span style="font-size:10.0pt;"><span style="line-height:107%;">04: Sospensione temporanea di un OE all'interno dell'SDA.</span></span></p>

<p><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style="line-height:107%;">05: Riattivazione di un OE precedentemente sospeso.</span></span></span></span></span></p>

<p><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style="line-height:107%;">Restiamo a disposizione per eventuali chiarimenti.</span></span></span></span></span></p>

<p><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;"><span style="font-size:10.0pt;"><span style="line-height:107%;">Cordiali saluti.</span></span></span></span></span></p>

**Comment by obigno77** [comment]
Verifica la coerenza della tipologica (02) e della risposta

**Comment by anac-uscp** [comment]
<p>Gentile utente</p>

<p>La scheda S0 non richiede l'invio completo dell'elenco degli OE iscritti. Ogni trasmissione deve includere solo le variazioni avvenute, come nuovi inserimenti, iscrizioni, modifiche o cancellazioni.</p>

<p>Di seguito la logica della tipologica operazioni SDA:</p>

<p>Inserimento (01): Il partecipante ha lo stato "in valutazione" e non è ancora iscritto. È stato solo inserito nell'elenco.<br>
Conferma (02): Il partecipante viene confermato con lo stato "iscritto".<br>
Cancellazione (03): Il partecipante viene rimosso dall'elenco con lo stato "cancellato".<br>
Modifica (04): Consente la modifica delle informazioni del partecipante, che mantiene il suo stato attuale.<br>
Rivalutazione (05): Simile alla modifica, ma possibile solo se il partecipante ha lo stato "iscritto". Dopo l'operazione, lo stato del partecipante diventa "in valutazione"</p>

<p> </p>

<p>Restiamo a disposizione.</p>

<p> </p>

<p>Cordiali Saluti</p>
