### ISSUE TITLE
[Toscana/Bolzano] - P7_2 - aggiornamenti Changelog 2: ERR4

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1707]
Buongiorno,
stiamo eseguendo i test sull'aggiornamento relativo al Changelog 2 e stiamo riscontrando diversi errori ERR4 durante la creazione dell'appalto per una scheda P7_2, impattata dalle modifiche introdotte dal Changelog 2.

Nello specifico, abbiamo riscontrato i seguenti errori:
-  ERR4 - errore nella conversione della scheda secondo il json schema definito: $.anacForm.appalto.strumentiSvolgimentoProcedure: is missing but it is required
-  ERR4 - errore nella conversione della scheda secondo il json schema definito: $.anacForm.lotti[0].iniziativeNonSoddisfacenti: is missing but it is required
-  ERR4 - errore nella conversione della scheda secondo il json schema definito $.anacForm.lotti[0].saNonSoggettaObblighi24Dicembre2015: is missing but it is required

Di seguito vi allego json di input e output: 

[changelog2 - P7_2 jsonOutput.txt](https://github.com/user-attachments/files/17162218/changelog2.-.P7_2.jsonOutput.txt)
[changelog2 - P7_2 jsonInput.txt](https://github.com/user-attachments/files/17162217/changelog2.-.P7_2.jsonInput.txt)

Visto che non riusciamo a proseguire con la creazione di una P7_2 ci potreste dare supporto?
Grazie .

**Comment by sfala** [comment]
Riscontratoo il medesimo problema.

**Comment by obigno77** [comment]
Il problema è in via di risoluzione. Ad avvenuto rilascio della fix si provvederà alla chiusura del ticket.

**Comment by obigno77** [comment]
Bug fixato con rilascio di questa mattina
