### ISSUE TITLE
changelog2 - rilascio qualificazione

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1709]
Buongiorno,

a seguito di test segnaliamo che in ambiente di qualificazione si riscontrano i seguenti disallineamenti rispetto al changelog2 (segnalato rilascio in qualifciazione il 24/09/2024):

- scheda AD2_28: obbligatorietà campo "Quadroeconomicostanbdard" 
- P2_23: obbligatorietà campo ""contrattidisposizioniparticolari"
- AD5: obbligatorietà campi""ccnl", "categoria" ""datiBaseDocumenti"
- regole DMN (REG34/35/36) per le schede P2_28 e A2_28
- P7_2 obbliagorietà campi "StrumentiSvolgimentoProcedura" "IniziativeNonSoddisfacenti" "SANonSoggettaObblighi24Dicembre2015"

Se il rilascio non è stato effettivamente completato sarebbe opportuno darne evidenza nella pagina del changelog aggiornando anche la data del rilascio in qualificazione.

Grazie

**Comment by obigno77** [comment]
Bug fixato con rilascio di questa mattina
