### ISSUE TITLE
Integrazione con IMPORTA CIG da SIMOG

### ISSUE THREAD

**Issue by ferdinandjmaddela** [anticorruzione/npa#171]
La nostra piattaforma di eprocurement ha un' apposita funzionalità per importare il CIG (e relative informazioni) dalla piattaforma attuale di SIMOG [https://simog.anticorruzione.it/AVCP-SimogWeb/checkAuthentication](https://simog.anticorruzione.it/AVCP-SimogWeb/checkAuthentication). Al fine di poter mantenere attiva l'attuale funzionalità, pongo le seguenti domande:

1) Dopo il rilascio della nuova piattaforma PCP, sarà ancora possibile utilizzare la piattaforma SIMOG per lo stacco dei CIG?
2) In caso positivo, sarà possibile, tramite il 'consulta-appalto' e 'recupera-cig', recuperare tutte informazioni create su SIMOG ed eventualmente continuare il ciclo dell'appalto attraverso i servizi di NPA.
3) In caso negativo, verrà creato/gestito una nuova piattaforma per staccare i CIG senza l'utilizzo dei servizi PCP?

**Comment by supportoAnac** [comment]
1) No, i servizi per il rilascio del CIG chiuderanno il 31/12/2023.
2) Come conseguenza a 1), non è al momento possibile.
3) No, il CIG verrà attribuito unicamente attraverso la piattaforma PCP e scomparirà la distinzione tra CIG e Smart CIG.
