### ISSUE TITLE
[Consip] Richiesta Conferma Rilascio in Qualificazione Changelog-2

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#1710]
Buongiorno chiedo la cortese conferma che il rilascio del changelog-2 in ambiente di qualificazione previsto per il 24/09/2024 sia stato effettuato e completato.

Attendo un riscontro

Grazie

**Comment by obigno77** [comment]
Il rilascio è stato completato il 27/09 determinando uno slittamento della data prevista per il rilascio in produzione. E' in corso il bugfixing delle anomalie segnalate nei giorni successivi
