### ISSUE TITLE
[Toscana/Bolzano] - Changelog2 - ERR4: modalitaAcquisizione obbligatoria per P_20 e 21

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1711]
Salve,
segnaliamo che stiamo riscontrando errori anche per le schede P_20 e P_21. Nonostante l'aggiornamento del Changelog 2 renda facoltativa la "modalità acquisizione", ci viene restituito un errore ERR4 che indica la "modalità acquisizione" come obbligatoria.

In allegato i json di input e output: 

- [data (3) (1).json](https://github.com/user-attachments/files/17164523/data.3.1.json)
- [data (4).json](https://github.com/user-attachments/files/17164524/data.4.json)

Grazie.

**Comment by sfala** [comment]
Problema riscontrato anche da noi.

**Comment by obigno77** [comment]
Bug in corso di risoluzione, il ticket sarà chiuso ad esito del rilascio delle fix
