### ISSUE TITLE
[DIGITALPA]  - SCHEDA M2 NON CONFERMATA - ERR94  - errore generico durante la comunicazione con PVL

### ISSUE THREAD

**Issue by dellattiDPA** [anticorruzione/npa#1712]
Segnaliamo da mesi una problematica riguardante le schede M2 attraverso i canali preposti, ma senza risultati. 

Ci è stato comunicato recentemente che la problematica è stata risolta e di riprovare, ma il problema persiste.

Proviamo a segnalare qui l'ultima segnalazione pervenuta, con la speranza che la problematica venga risolta o che 

comunque venga  individuata la causa di questo errore e risolto nel più breve tempo possibile.

Di seguito i dati per eseguire le verifiche:

- **ID APPALTO:** 12df80cb-0215-4960-8447-3830615b8acc
- **ID SCHEDA M2**: dcfaa65c-1907-44f7-8bac-a4bd1b6ab359
- **ID CONTRATTO**:  7325fba2-ad64-48fe-8ee7-b7d1af23822e
- **STATO SCHEDA**: SC_N_CONF
- **ERRORE ESITO OPERAZIONE**: ERR94 - errore generico durante la comunicazione con PVL
- **DETTAGLIO ERRORE**: Index 2 out of bounds for lenght 1.

Attendiamo riscontro.

**Comment by supportoAnac** [comment]
Gentile utente,

Desideriamo informarla che, a seguito delle verifiche effettuate, non sono state riscontrate le anomalie da lei segnalate. Le ricordiamo che è stata recentemente rilasciata una fix che potrebbe risolvere eventuali problematiche. Pertanto, le consigliamo di riprovare a effettuare l'operazione.

Restiamo a disposizione per eventuali chiarimenti.

Cordiali saluti.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>ci scusiamo per il disagio. Siamo a conoscenza della problematica e stiamo lavorando ad una fix integrativa che verrà rilasciata nella prima settimana di Dicembre. </p>

<p>Da giorno 9-12 si prega quindi di riprovare ad invocare il servizio in questione.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p> </p>

<p>Cordiali saluti.</p>
