### ISSUE TITLE
(ARIA spa) ISDA e S0 - chiarimenti necessari

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1714]
Buongiorno,

non risultano chiare alcuni temi rispetto alle nuove schede di indizione dei Sistemi dinamici di acquisizione- bando istitutivo e S0:

1) l'id restituito dal servizio all'invio della scheda di istituzione SDA (campo "idSDA*" come obbligatorio nella scheda S0) è un ID che sostituisce l'IDAppalto per le altre schede di indizione? o sono previsti entrambi gli ID?
rispetto a questa tematica, non essendo stato aggiornato il file yaml "specifiche-servizi-appalto" dove si possono visualizzare le response all'invio delle schede?

2) la scheda S0 inviata n volte successive sostituisce in toto la precedente o è inviata solo come aggiornamento dei dati precedenti? (ad es per comunicare una nuova richiesta di ammissione è sufficiente inserire nella nuova S0 solo i dati del nuovo richiedente o va ritrasmesso tutto lo storico della S0)

3) per il campo "Azione richiesta dal partecipante" andrebbero approfondite le voci disponibili. ad es: che differenza c'è fra "Modifica" e "rivalutazione"? se un OE fa una richiesta di ammissione ma la ritira prima che venga comunicata la richiesta andrebbe indicata come "Cancellazione" saltando per quel OE l'"inserimento"? "Cancellazione" deve essere intesa anche come SA che rifiuta la richiesta di ammissione di un OE o che lo rimuove in seguito dagli abilitati per x motivi?

**Comment by anac-uscp** [comment]
<p>Il termine delle attività trova risoluzione in quanto segue:<br>
<br>
1- L'id che viene restituito dalla scheda di indizione non sostituisce l'idAppalto sono previsti entrambi per la creazione di una S0, per recuperare l'idSDA e sufficiente chiamare il servizio di recupera-scheda, l'idScheda della ISDA restituito è l'idSDA da usare per la S0(questo procedimento non è necessario se si utilizza il servizio pcp-ui)</p>

<p>2- Le S0 successivamente inviate vanno ad aggiornare l'elenco dei partecipanti, non è necessario reinserire il partecipante a meno che non si voglia eseguire una operazione che cambia lo stato del partecipante all'interno dell'elenco</p>

<p>3- La differenza tra modifica e rivalutazione è che la Modifica si puo effettuare su un utente con stato 'In valutazione' ma non ancora confermato, mentre la Rivaltuzione puo essere eseguita solo su un utente 'Iscritto'</p>
