### ISSUE TITLE
Scheda CSDA2 - campo dataFine

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1717]
nella documentazione in campo dataFine ha per descrizione:

La data (stimata) alla quale ha fine l'appalto, l'accordo quadro, il sistema dinamico di acquisizione o il sistema di qualificazione. - nei casi in cui la scheda preveda un eform, corrisponde al campo bt-537 - Duration End Date del TED

Si chiede conferma che la data richiesta sia **quella di fine effettiva** dello SDA e non quella stimata, visto che la scheda riguarda proprio la chiusura dello SDA.

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="color:#000000;"><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;">La scheda si riferisce alla conclusione effettiva dello SDA, che coincide con il campo bt 537.<br>
Sussiste un obbligo di informare la Commissione europea di qualsiasi variazione del periodo di validità indicato nell’indizione della procedura, con la pubblicazione di un nuovo avviso in caso di modifica (art. 32 comma 12).</span></span></span></span><br>
 </p>
