### ISSUE TITLE
RIF. issue 1683 [SISGAP][BLK] A2_29 - errore ERR94 su esito-operazione

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1718]
Facciamo riferimento alla issue https://github.com/anticorruzione/npa/issues/1683 per la quale è stato fornito quanto richiesto via mail in quanto questa è stata chiusa.
Notiamo che il problema è stato segnalato anche in altra issue https://github.com/anticorruzione/npa/issues/1696

E' stato fatto il rilascio che sistema il problema?
Ci sono novità in merito?

**Comment by supportoAnac** [comment]
Gentile utente,

In riferimento alla issue [#1696](https://github.com/anticorruzione/npa/issues/1696) la problematica è stata risolta, si invita pertanto a riprovare.

Restiamo a disposizione per eventuali chiarimenti.

Cordiali saluti.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>La problematica è stata risolta tramite un fix relativo al recupero delle tipologiche, rilasciato a settembre.</p>

<p>Restiamo a disposizione per eventuali ulteriori chiarimenti.</p>

<p>Cordiali saluti</p>
