### ISSUE TITLE
[Consip][INFO] changelog-2 Schede SDA  e gestione del pregresso

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1719]
Salve,
in merito alle nuove schede per la pubblicazione dei bandi SDAPA  (ISDA, CSDA, S0), vorremmo informazioni su come è stato previsto di gestire il pregresso. 
Nel dettaglio, i bandi ancora in vigore (e con data pubblicazione precedente al rilascio delle schede) dovranno essere comunicati tramite la trasmissione di queste schede oppure potranno continuare il loro flusso senza la trasmissione delle schede?

**Comment by obigno77** [comment]
Potranno continuare il loro flusso senza la comunicazione di queste schede
