### ISSUE TITLE
Procedure non gestite dalla piattaforma eprocurement

### ISSUE THREAD

**Issue by ferdinandjmaddela** [anticorruzione/npa#172]
Attualmente qualora una SA debba procedere con gli adempimenti previsti da legge, se la procedura non è gestita da una piattaforma telematica di eprocurement, procedono in autonomia sugli applicativi messi a disposizione dagli enti centrali (eg. SIMOG per stacco CIG e invio schede). 
Le stesso discorso vale per una residuale parte delle procedure che potrebbero essere svolte in modalità tradizionale.

Questo sottoinsieme di procedure come verrà gestito nell'ambito dell'integrazione PCP che prevede uno svolgimento telematico delle procedure??

**Comment by supportoAnac** [comment]
Non è possibile procedere alle procedure di affidamento senza l'adozione di una piattaforma di approvvigionamento digitale. 

Il Codice dei contratti esclude la possibilità di procedere.
