### ISSUE TITLE
[Consip][INFO] changelog-2 Correlazione tra schede per il bando SDA (isda,csda,p0) e schede per la pubblicazione di appalti SDA (es. P7_2)

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1720]
salve,
si chiede conferma sull'assenza di correlazione tra le schede per il bando sda (isda,csda,p0) e le schede per la pubblicazione di appalti SDA (es. P7_2).

1. Sulla scheda p7_2 è stato introdotto il campo id_sda che viene rilasciato a seguito della pubblicazione del bando. Tale campo è attualmente facoltativo, si prevede di renderlo obbligatorio?

2. Sulla scheda p0 è previsto il campo id_partecipante. Tale campo deve essere in qualche modo collegatI con gli id partecipanti che vengono comunicati nell'ambito del flusso di una scheda P7_2 (con la S2 per esempio)?

**Comment by obigno77** [comment]
Al momento quanto richiesto non può essere implementato per garantire la retrocompatibilità con i bandi istituitivi non pubblicati su PCP. Si raccomanda alle PAD di implementare tutti i controlli possibili e necessari a garantire la coerenza dei dati trasmessi all'Autorità
