### ISSUE TITLE
[Toscana/ Bolzano] - incongruenza REG1: categoria merceologica

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1721]
Buongiorno,
stiamo procedendo con la conferma dell'appalto relativo alla scheda P2_16, ma stiamo riscontrando il seguente errore:

- REG1: La categoria merceologica indicata nei lotti non è compresa tra quelle specificate nell'appalto.

Tuttavia, dai nostri controlli, la categoria merceologica indicata nei lotti risulta corrispondere a quella prevista nell'appalto.

In allegato vi inviamo il file JSON di input per una vostra verifica.
[jsonInput P2_16 - REG1.txt](https://github.com/user-attachments/files/17188465/jsonInput.P2_16.-.REG1.txt)

Restiamo in attesa di un riscontro.
Grazie.

**Comment by masko82** [comment]
Ci uniamo alla issue in quanto noi otteniamo lo stesso errore.
Per noi il problema si verifica in ambiente di QUALIFICAZIONE in fase di creazione di una P1_16!

Alleghiamo il json della request
[Request.txt](https://github.com/user-attachments/files/17188622/Request.txt)

**Comment by medionovarese** [comment]
Ci uniamo anche noi alla issue in quanto otteniamo un errore simile e più precisamente:
REG1: categoria merceologica: controllo di coerenza tra quelle indicate nei lotti e quelle indicate nell'appalto.
In realtà le categorie indicate nei lotti e nell'appalto sono le medesime e non c'è nessun problema di "coerenza"

**Comment by claudiocarotenuto** [comment]
Buongiorno
Riscontriamo anche noi la problematica sia in ambiente di qualificazione che di produzione
Restiamo in attesa di celere riscontro

**Comment by Gestore-Venicecom** [comment]
Salve 
anche noi abbiamo lo stesso problema 
Venicecom

**Comment by mariottiDPA** [comment]
confermiamo anche da DigitalPA

**Comment by gianlucacuomo** [comment]
Da TUTTOGARE abbiamo aperto anche due segnalazioni al canale di produzione sull'argomento

**Comment by obigno77** [comment]
Problema risolto in ambiente di qualificazione. Appena possibile la fix sarà portata anche in esercizio

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>è stata rilasciata una fix risolutiva per la problematica riscontrata.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p> </p>

<p>Cordiali saluti.</p>
