### ISSUE TITLE
[CONSIP] - P1_23/P2_23 - ERR4 - $.anacForm.appalto.contrattiDisposizioniParticolari: is missing but it is required

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1722]
Buongiorno,
abbiamo effettuato il seguente test:
A seguito della trasmissione delle schede P1_23/P2_23, riscontriamo il seguente errore
''ERR4 - $.anacForm.appalto.contrattiDisposizioniParticolari: is missing but it is required''

Riscontriamo dall'errore che il campo contrattiDisposizioniParticolari venga recuperato dall' oggetto Appalto ma attualmente si trova all'interno dell' oggetto Lotti (come da aggiornamento del changelog) per cui non potrà mai essere popolato in quanto il campo si trova in oggetto differente.

**Comment by obigno77** [comment]
Il bug sarà risolto asap

**Comment by obigno77** [comment]
Bug fixato con rilascio di questa mattina
