### ISSUE TITLE
[CONSIP] - Scheda P7.2 - ERR4 per campi non più presenti

### ISSUE THREAD

**Issue by alessiopera** [anticorruzione/npa#1723]
Cliccando su RICHIEDI CIG, il sistema mostra una serie di ERR4:

ERR4 - $.anacForm.appalto.strumentiSvolgimentoProcedure: is missing but it is required

ERR4 - $.anacForm.lotti[0].iniziativeNonSoddisfacenti: is missing but it is required

ERR4 - $.anacForm.lotti[0].saNonSoggettaObblighi24Dicembre2015: is missing but it is required

i campi strumentiSvolgimentoProcedure, * iniziativeNonSoddisfacenti, *saNonSoggettaObblighi24Dicembre2015 sono stati rimossi coerentemente con il modello dati attuale.
La sezione datiBaseStrumentiProcedura indicata * nel test non presenta anomalie in quanto non è citata negli errori ERR4, erroneamente confusa con il campo *strumentiSvolgimentoProcedure.
Pertanto si richiede un' analisi dell'errore lato ANAC.

Grazie

**Comment by supportoAnac** [comment]
Gentile Utente,

Al fine di poterla assistere nel migliore dei modi, la invitiamo cortesemente a fornirci maggiori dettagli riguardanti l'operazione che sta cercando di effettuare.

Desideriamo inoltre informarla che è stata recentemente rilasciata una fix che ha risolto una serie di problematiche riscontrate. Pertanto, le consigliamo di riprovare a effettuare l'operazione.

Ogni informazione aggiuntiva sarà utile per comprendere meglio la sua richiesta e offrirle una soluzione adeguata.

Restiamo a sua completa disposizione per ulteriori chiarimenti.

Cordiali saluti

**Comment by anac-uscp** [comment]
<p>Gentile Utente,</p>

<p>Al fine di poterla assistere nel migliore dei modi, la invitiamo cortesemente a fornirci maggiori dettagli riguardanti l'operazione che sta cercando di effettuare.</p>

<p>Desideriamo inoltre informarla che è stata recentemente rilasciata una fix che ha risolto una serie di problematiche riscontrate. Pertanto, le consigliamo di riprovare a effettuare l'operazione.</p>

<p>Ogni informazione aggiuntiva sarà utile per comprendere meglio la sua richiesta e offrirle una soluzione adeguata.</p>

<p>Restiamo a sua completa disposizione per ulteriori chiarimenti.</p>

<p>Cordiali saluti</p>
