### ISSUE TITLE
[A2A] - Chiarimenti rettifica-avviso: sistema qualificazione P1_15_1

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1724]
Buongiorno,
Stiamo procedendo ad effettuare dei test in collaudo, relativi alla **rettifica** della scheda di pianificazione P1_15_1 (eForm) ma riscontriamo "ERR9999: errore generico" 

L'errore si riscontra durante la rettifica del formulario, la quale avviene tramite il servizio rettifica-avviso.
[P1_15_1 1.json](https://github.com/user-attachments/files/17203010/P1_15_1.1.json)

ID pianificazione: 90c1b075-9517-44db-bd41-6ce2792a3a10

Ci potreste indicare se è corretto trasmettere una rettifica della P1_15_1 ?

**Comment by obigno77** [comment]
Premesso che l'idPianificazione indicato non risulta esistere in ambiente di qualificazione.
L'avviso di rettifica per le schede di pianificazione è supportato ma, come per tutti gli avvisi di rettifica, può essere trasmesso solo per avvisi già pubblicati.
