### ISSUE TITLE
Richiesta pubblicazione avviso per appalti non pubblicati P2_16

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#1725]
Buonasera,

abbiamo urgente necessità di avere pubblicati in TEST i seguenti appalti per poter concludere il collaudo del processo:

Di seguito gli idAppalto relativi ad appalti creati senza ricevere alcun errore:
- fd9caebe-2caa-4221-a668-6d1987e13d9a
- c371cd4c-6f18-4867-9a43-c8bbbf0c062e
- 9605fcca-695a-4e20-81fb-fec4c82761aa
- 975c87c8-c091-479b-b9f6-e381926f0607
- 183f2566-63f5-4ed6-93b6-66330885a5bf
- ae1a3617-0189-4d5a-aa02-46b48a9c932d

Attendiamo un cortese riscontro.

Grazie anticipatamente per il supporto.

**Comment by obigno77** [comment]
I tempi di pubblicazione sono gli stessi dell'esercizio. E' stato verificato il primo idAppalto e risulta correttamente pubblicato
