### ISSUE TITLE
Richiesta pubblicazione appalto in lavorazione (collaudo) P1_16

### ISSUE THREAD

**Issue by LDAV** [anticorruzione/npa#1726]
Abbiamo necessità di avere pubblicato in ambiente di collaudo il seguente appalto per poter concludere il test di pubblicazione avviso:
idAppalto = a4bce646-23f7-497a-8e31-dc750c779ea2
Attualmente risulta in lavorazione (IN_LAV) e senza un CIG assegnato.
La verifica non riporta errori.

Il processo automatico di conferma è valido anche in fase di collaudo? O richiede un intervento manuale?
Grazie per il supporto.

**Comment by obigno77** [comment]
La conferma-appalto deve essere eseguita esplicitamente così come anche la pubblicazione
