### ISSUE TITLE
[Venicecom] Errore REG1

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#1728]
Salve,

Non riusciamo a confermare o verificare un appalto già inviato alla banca dati. La banca dati restituisce l'errore REG 1. Vorremmo sottolineare che questo problema è nuovo, in quanto abbiamo inviato schede in passato con la stessa compilazione senza alcun errore, mentre ora riscontriamo difficoltà.

Il problema si verifica anche in ambiente di produzione, e abbiamo clienti che rischiano di perdere fondi pubblici a causa di questa problematica.

Chiediamo gentilmente un riscontro urgente.

•	Piattaforma: ProQ
•	Tipologia di gara: P2_19
•	Valore Economico dell’Appalto: N/A
•	idAppalto: abd0a9b9-079d-4e78-855f-3a82eef73119
•	Fase Gara/Scheda: esito verifica P2_19
•	Errore riscontrato: REG1
•	GovWay-Transaction-ID  = "43d8aa79-8001-11ef-bd08-0050568e9679"

**Comment by carlalavorgna** [comment]
mi unisco alla segnalazione
noi da oggi abbiamo lo stesso errore anche su gare con scheda P1_16
