### ISSUE TITLE
[CONSIP] - Scheda AD1_25 - AD1_26 - AD1_27 errore per REG68_1

### ISSUE THREAD

**Issue by alessiopera** [anticorruzione/npa#1730]
trasmettendo le schede AD1_25 - AD1_26 - AD1_27 riscontriamo un Err REG68_1:

{
    "result": {
        "exitCode": "400",
        "text": "Servizio momentaneamente non disponibile"
    },
    "payload": {
        "code": 400,
        "responseData": null,
        "errors": [
            {
                "errorCode": "400 KO",
                "shortDescription": "{\"instance\":null,\"status\":400,\"title\":\"KO\",\"detail\":\"Errore\",\"type\":\"about:blank\",\"errori\":[{\"idTipologica\":\"errori\",\"codice\":\"REG68_1\",\"dettaglio\":\"\"}]}",
                "keyMessage": ""
            }
        ]
    }
}

**Comment by obigno77** [comment]
Il problema è in via di risoluzione. Segue aggiornamento

**Comment by obigno77** [comment]
Bug fixato con rilascio di questa mattina

**Comment by lauralu1993** [comment]
il problema persiste. si aggiunge che è stato riscontrato anche sulla scheda A1_31
