### ISSUE TITLE
Gestione Fase esecutiva a seguito delle schede:A3_6 affidamenti in house

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#1732]
Analizzando l'orchestratore per gli affidamenti in house gestiti con la scheda A3_6 il flusso della fase esecutiva sembra essere analogo alle altre procedure prevedendo tutte le schede. E' corretto? 
Se non è così per gli affidamenti in house c'è un flusso semplificato per cui sono previste solo alcune schede o non sono previste alcune schede specifiche?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Nel caso degli affidamenti in house gestiti con la scheda A3_6, il flusso della fase esecutiva può apparire simile a quello delle altre procedure, ma in realtà può essere semplificato. Per gli affidamenti in house, alcune schede potrebbero non essere necessarie o il flusso potrebbe essere ridotto, specialmente se l'affidamento riguarda contratti diretti o con importi ridotti. La semplificazione dipende dalla tipologia dell'affidamento e dalle specifiche normative che regolano la procedura, con il sistema che adatta automaticamente i passaggi richiesti. Pertanto, non tutte le schede previste nelle altre procedure sono obbligatorie per gli affidamenti in house.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
