### ISSUE TITLE
Schede di modifica contrattuale per le schede P7_x e P7_x_x

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1733]
Leggendo nell'orchestratore la colonna flussoAppartenenza sembrerebbe che per le schede in oggetto non sono previste le schede di modifica contrattuale M1/ M2 e M1_40/M2_40.
Si tratta di un refuso dell'orchestratore oppure è necessario utilizzare altre schede per comunicare le eventuali modifiche contrattuali??

**Comment by anac-uscp** [comment]
<p>Abbiamo in carico la segnalazione. In un prossimo utile changelog sarà inserito il flusso, per le schede indicate, nelle relative schede di modifica contrattuale.</p>
