### ISSUE TITLE
[Consip] - AD2_28 - REG 34  Non è stato indicato il valore dell’importo componente lavori

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1734]
Buongiorno,
abbiamo effettuato il seguente test:
A seguito della trasmissione della scheda AD2_28 riscontriamo il seguente errore 
''REG 34 Non è stato indicato il valore dell’importo componente lavori''
Da modello dati per la scheda AD2_28 non è previsto il campo ''quadro economico standard'' all'interno del quale è presente il valore dell'importo componente lavori. Di conseguenza è un errore bloccate al fine della trasmissione della scheda.

**Comment by obigno77** [comment]
Il problema sarà risolto entro oggi
