### ISSUE TITLE
[Consip] AD2_28 - REG69 Non è stato indicato il valore dell’importo componente lavori nel quadro economico delle concessioni

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1735]
Buongiorno,
abbiamo effettuato il seguente test:
A seguito della trasmissione della scheda AD2_28 riscontriamo il seguente errore
''REG69 Non è stato indicato il valore dell’importo componente lavori nel quadro economico delle concessioni''
Da modello dati per la scheda AD2_28 ci risulta che il campo quadro economico delle concessioni è facoltativo. 
Invece la sua compilazione risulta propedeutica per la trasmissione della scheda.

**Comment by obigno77** [comment]
Il problema sarà risolto entro oggi
