### ISSUE TITLE
[Consip] - AD3 -REG34 - Non è stato indicato il valore dell’importo componente lavori

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1736]
Buongiorno,
abbiamo effettuato il seguente test:
A seguito della trasmissione della scheda AD3 riscontriamo il seguente errore
''REG 34 Non è stato indicato il valore dell’importo componente lavori''
Da modello dati per la scheda AD3 ci risulta che il campo quadro economico standard è facoltativo.
Invece la sua compilazione risulta propedeutica per la trasmissione della scheda.

**Comment by obigno77** [comment]
Il problema sarà risolto entro oggi

**Comment by Antoluimaridand** [comment]
Buongiorno, riscontriamo ancora il problema sulla AD3
REG34/35/36
