### ISSUE TITLE
[Consip] AD5 - obbligatorietà dell'oggetto datiBaseDocumenti e del campo url  - ERR4 - $.anacForm.aggiudicazioni[0].datiBaseDocumenti: is missing but it is required

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1737]
Buongiorno,
abbiamo effettuato il seguente test:
Da modello dati per la scheda AD5 l'oggetto datiBaseDocumenti e il campo url sono facoltativi, a seguito della trasmissione della scheda AD5 riscontriamo il seguente errore: 
''ERR4 - $.anacForm.aggiudicazioni[0].datiBaseDocumenti: is missing but it is required''

**Comment by obigno77** [comment]
Il problema sarà risolto entro oggi
