### ISSUE TITLE
[Consip] - AD5 - ERR4 - Campo ccnl e categoria

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1738]
Buongiorno,
abbiamo effettuato il seguente test:
A seguito della trasmissione della scheda AD5 riscontriamo i seguenti errori:
ERR4 - $.anacForm.aggiudicazioni[0].categoria: is missing but it is required
ERR4 - $.anacForm.aggiudicazioni[0].ccnl: is missing but it is required
 
Da modello dati per la scheda AD5 non sono previsti i campi ''ccnl'' e ''categoria''. Di conseguenza è un errore bloccate al fine della trasmissione della scheda.

**Comment by obigno77** [comment]
Il problema sarà risolto entro oggi
