### ISSUE TITLE
[Consip] - AD5/CM1/CM2 - campo CUP - ERR4 - $.anacForm.aggiudicazioni[0].cup: array found, string expected

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1739]
Buongiorno,
abbiamo effettuato il seguente test:
A seguito della trasmissione delle schede AD5/CM1/CM2 popolate con una cardinalità del campo ''CUP'' maggiori di uno, riscontriamo il seguente errore:
''ERR4 - $.anacForm.aggiudicazioni[0].cup: array found, string expected''
Da modelli dati il campo ''CUP'' per tutte le schede citate è un Array che prevede più valori.

**Comment by obigno77** [comment]
Il problema sarà risolto entro oggi
