### ISSUE TITLE
 [Toscana/ Bolzano] - AD5 - ERR4 campi categoria e ccnl richiesti

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1741]
Buongiorno,
stiamo procedendo con la conferma dell'appalto relativo alla scheda AD5, ma stiamo riscontrando il seguente errore ERR4 che chiede come obbligatori i campi ccnl e categoria

Tuttavia, dai nostri controlli, la categoria e ccnl non sono più presenti nella struttura dati della scheda AD5

In allegato vi inviamo il file JSON di input per una vostra verifica.
[changelog2 AD5 [categoria-ccnl] - jsonOuput.txt](https://github.com/user-attachments/files/17232802/changelog2.AD5.categoria-ccnl.-.jsonOuput.txt)
[changelog2 AD5 [categoria-ccnl] - jsonInput.txt](https://github.com/user-attachments/files/17232803/changelog2.AD5.categoria-ccnl.-.jsonInput.txt)

**Comment by obigno77** [comment]
Buongiorno, il problema sarà risolto entro oggi
