### ISSUE TITLE
eForms SDK aggiornata

### ISSUE THREAD

**Issue by LDAV** [anticorruzione/npa#1742]
La procedura non accetta eForm con sdk eforms-sdk-1.12. che è il formato attualmente prodotto e verificato da TED, 
ERR12: versione sdk eForm errata.
Esistono alternative praticabili? Oppure è ipotizzabile un aggiornamento della procedura?
Grazie

**Comment by obigno77** [comment]
La procedura supporta la sdk1.9 che va in end of life a fine febbraio 25.
L'aggiornamento alla versione 1.12 sarà nel prossimo changelog.
