### ISSUE TITLE
[TEAMSYSTEM] - err40 su P1_16

### ISSUE THREAD

**Issue by carlalavorgna** [anticorruzione/npa#1744]
buongiorno da oggi pomeriggio stiamo ricevendo un ERR40 sul Conferma scheda

esempio:
idAppalto:567537a4-cf26-46b8-b715-b3ba04bbae1f
ERR40: errore generico durante l'estrazione dei dati della scheda\nGovWay-Transaction-ID: 896043c8-8187-11ef-852e-005056844885

Grazie

**Comment by obigno77** [comment]
Il bug sembra riguardare solo le schede P1_16. E' stato preso in carico ed è in fase di risoluzione. Si ricorda di utilizzare la casella supporto.pcp@anticorruzione per i case in esercizio

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>richiediamo gentilemente il payload della request utilizzata per inviare la scheda , in formato JSON, per poterci permettere una analisi approfondita del caso.<br>
<br>
Restiamo in attesa.<br>
<br>
Cordilai saluti</p>
