### ISSUE TITLE
modifica-appalto InteroperabilityInvalidRequest

### ISSUE THREAD

**Issue by LDAV** [anticorruzione/npa#1746]
È possibile avere qualche delucidazione rispetto a questo codice di errore, 
il tentativo di accesso è al servizio ComunicaAppalto/v2/modifica-appalto (ambiente collaudo)
grazie.

{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"74919fed-8197-11ef-988f-0050568e08b3"}

**Comment by obigno77** [comment]
Gli errori di interoperabilità derivano dal mancato rispetto delle specifiche del profilo di interoperabilità che si ricorda essere AUTH_REST_01 e/o dall'invalidità dei token. Nel caso di specie il token jws che da specifica ha una durata di 10 secondi era  già scaduto quando è stata aperta la transazione

Verifica ModI della richiesta fallita: [GOVWAY-661] [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2024-10-03_17:19:52.000')

**Comment by LDAV** [comment]
Queste richieste non vengono effetuate manualmente, e l'invio è praticamente contestuale alla creazione del token.
È possibile che ci sia un disallineamento fra i time dei server che genera questo tipo di errore? Esiste un modo per verificare data e ora del server PDND (o ANAC) ?
