### ISSUE TITLE
[toscana/bolzano] - Schede P1 - ERR9999 - errore generico

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1747]
Buongiorno,
Volevamo segnalare che stiamo riscontrando errore generico anche alla conferma dell'appalto per le schede P1* 

Vi allego i json del test eseguito su P1_19:

- [data (9).json](https://github.com/user-attachments/files/17256945/data.9.json)
- [data (10).json](https://github.com/user-attachments/files/17256946/data.10.json)

Potreste darci supporto?

Nb: Lo stesso errore lo stiamo riscontrando anche con l'invio di una scheda di aggiudicazione sopra soglia

**Comment by supportoAnac** [comment]
Gentile utente,

Desideriamo inoltre informarla che è stata recentemente rilasciata una fix che ha risolto una serie di problematiche riscontrate. Pertanto, le consigliamo di riprovare a effettuare l'operazione.

Restiamo a disposizione per eventuali chiarimenti.

Cordiali saluti.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Desideriamo informarla che è stata recentemente rilasciata una fix che ha risolto una serie di problematiche riscontrate. Pertanto, le consigliamo di riprovare a effettuare l'operazione.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
