### ISSUE TITLE
[ARIA] Changelog 2 - Rilascio in Qualificazione

### ISSUE THREAD

**Issue by sfala** [anticorruzione/npa#1748]
Buongiorno,
segnaliamo che in ambiente di qualificazione si riscontrano disallineamenti rispetto a quanto indicato nel Changelog 2. In particolare per le schede P7_1_2 e P7_1_3, nonostante nelle note siano dati per eliminati, i seguenti campi continuano ad essere richiesti come OBBLIGATORI:
 -  $.anacForm.lotti[0].iniziativeNonSoddisfacenti
 -  $.anacForm.lotti[0].saNonSoggettaObblighi24Dicembre2015

Grazie

**Comment by obigno77** [comment]
Problema risolto
