### ISSUE TITLE
[BLK] - Timeout - Produzione e Collaudo

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#1749]
Da questa mattina tutti i servizi risultano irraggiungibili, è problema nostro o diffuso a tutti gli utilizzatori?

**Comment by mariottiDPA** [comment]
Temo che sia un problema diffuso, lo stesso sito ANAC risulta inaccessibile https://www.anticorruzione.it/

**Comment by masko82** [comment]
Buongiorno, stiamo notando irraggiungibilità per i servizi ANAC su tutti gli ambienti.

Qualificazione: ETIMEDOUT 93.43.119.96:443
Attestazione:  ETIMEDOUT 93.43.119.65:443
Produzione:  ETIMEDOUT 93.43.119.116:443
