### ISSUE TITLE
Response del servizio esito-operazione

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#175]
Sarebbe utile comprendere le diverse modalità di risposta ed i relativi contenuti a fronte delle diverse richieste. I servizi ASINCRONI sono 10:

1.	verifica-piano
2.	conferma-piano
3.	verifica-appalto
4.	conferma-appalto
5.	pubblica-avviso
6.	modifica-avviso
7.	rettifica-avviso
8.	cancella-avviso
9.	verifica-scheda
10.	conferma-scheda

per ciascuno di questi ci si aspetterebbe una risposta di errore che collezioni i diversi errori rilevati (ed è quanto sembra gestito dalla struttura della risposta presente in documentazione), ma anche nel caso di esito positivi è necessario avere informazioni relative a codici e classificazioni assegnate. A titolo di esempio non esaustivo, il servizio pubblica-avviso dovrebbe ricevere le informazioni di pubblicazione sia su TED sia su PPL-ANAC (vedi quesito precedente), il conferma-appalto dovrebbe restituire l’idAvviso per procedere con la fase di pubblicazione etc. etc.
Nella documentazione tale eventualità non sembra essere contemplata.

**Comment by supportoAnac** [comment]
È il servizio /esito-operazione a restituire la risposta ai servizi asincroni.
