### ISSUE TITLE
[CONSIP] Changelog 3 - Pubblicazione contenuti su Ghit

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1750]
Salva,
da nota di rilasio il 2/10 era prevista la pubblicazione dei contenuti relativi al changelog03. Tuttavia ad oggi non abbiamo ancora nessuna evidenza dell’avvenuta pubblicazione su GitHub della nota di rilascio in merito al changelog-03.

Per quando è prevista la pubblicazione dei contenuti? 
Grazie

![image](https://github.com/user-attachments/assets/2855dc89-8b8e-426e-8ec1-a11453e24144)

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Il changelog 03 dovrebbe essere pubblicato martedì 15-10.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
