### ISSUE TITLE
[Toscana/bolzano] - Rettifica avviso scheda P1* - ERR9999- errore generico

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1751]
Salve,

Stiamo riscontrando problemi invocando il servizio di rettifica-avviso per una procedura sopra soglia P1*.
L'errore mostrato è ERR9999 - errore generico

Di seguito i Json:
[p117creappalto output.json](https://github.com/user-attachments/files/17276033/p117creappalto.output.json)
[p117creaappalto.json](https://github.com/user-attachments/files/17276034/p117creaappalto.json)
[p117 rettifica input.json](https://github.com/user-attachments/files/17276035/p117.rettifica.input.json)
[p117 output.json](https://github.com/user-attachments/files/17276036/p117.output.json)

Grazie.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>da controlli effettuati sui nostri sistemi, risulta che l'ultimo tentativo di rettifica-avviso ha restituito la regola REG105, che cita: "La data inserita nel campo datiBaseTerminiInvio.oraScadenzaPresentazioneOfferte non può essere antecedente o uguale ad oggi. In presenza di eForm verificare il campo EndDate (BT-131)."<br>
<br>
Pertanto la invitiamo a ritentetare la rettifica dell'avviso, rispettando tale regola.</p>

<p>Restiamo a disposizione.<br>
<br>
Cordiali saluti</p>
