### ISSUE TITLE
modifica importo di aggiudicazione

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1752]
Buongiorno,

in caso di errata comunicazione del valore dell'importo di aggiudicazione in una scheda A... è possibile procedere con una rettifica?  è dato rettificabile tramite la funzionalità di Rettifica avviso (sia per schede sopra che sotto soglia)?

Grazie

**Comment by obigno77** [comment]
Al momento sembra supportato solo per gli avvisi soprasoglia

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>procediamo alla chiusura del ticket dando come risposta valida quella fornita dall'Ing. Obino.</p>

<p>Cordiali saluti.</p>
