### ISSUE TITLE
[Toscana/Bolzano] - Disallineamento struttura dati nella response del servizio consulta-appalto per AD5 - modifiche changelog2

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1753]
Buongiorno,

In seguito al rilascio del changelog2, la response del servizio consulta-appalto dovrebbe essere aggiornata per rispecchiare la nuova struttura dati definita dalla documentazione. 

![immagine](https://github.com/user-attachments/assets/12863885-799c-4a9e-887d-18c43102c816)

Tuttavia, effettuando una richiesta consulta-appalto per un AD5 creato prima del rilascio del changelog2, la response continua a presentare la vecchia struttura dati, risultando disallineata rispetto a quanto specificato nelle nuove modifiche.

[consulta-appalto - old AD5.txt](https://github.com/user-attachments/files/17291480/consulta-appalto.-.old.AD5.txt)

La nostra necessità è quella di importare un CIG (AD5) tramite il servizio consulta-appalto, per appalti che sono stati creati sulla piattaforma ANAC. Attualmente, questo non è possibile a causa del disallineamento della struttura della response.

**Comment by obigno77** [comment]
I dati acquisiti prima del changelog vengono restituiti come tali
