### ISSUE TITLE
[BLK] [Maggioli] Ambiente di attestazione: appalti bloccati in attesa pubblicazione

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1755]
Buongiorno,
abbiamo necessità di effettuare dei test sull'ambiente di attestazione per sfruttare l'allineamento di versione a quello di produzione.
Purtroppo gli appalti che prevedono pubblicazione su PVL rimangono sempre in stato attesa pubblicazione.

Vi lascio sotto gli estremi di un caso specifico per le vostre verifiche.

idAvviso: 3b411ded-5496-4b17-879b-9c7ddd181ed9
idAppalto: c02a519d-bb38-4d31-8405-fdfb614e8ec4
govwayTransactionId: db67d69a-855e-11ef-b339-0050568e7535

Potete sbloccare la situazione?

Non solo per l'appalto specifico, ma in generale consentendo la pubblicazione in questo ambiente.

Grazie

**Comment by paolo-urbanetto** [comment]
Preciso che dobbiamo fare dei test sulle rettifiche, quindi senza avere la pubblicazione fatta siamo bloccati

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>ricercando con l'idAppalto fornito sull'ambiente di qualificazione non é stato restituito alcun risultato.</p>

<p>La invitiamo a verificare e nel caso fornire il corretto idAppalto o codiceAppalto specifico.</p>

<p>Restiamo a disposizione.</p>

<p>Cordiali saluti</p>
