### ISSUE TITLE
ERR9999 su conferma scheda A1_29

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1756]
Abbiamo invocato correttamente il servizio di crea scheda per l'invio di una A1_29 con il seguente payload
[Payload_A1_29.json](https://github.com/user-attachments/files/17293511/Payload_A1_29.json)

La chiamata successiva all'api conferma-scheda ci ha restituito un errore
{"status":400,"title":"KO","detail":"SC_N_CONF","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}

Di seguito i riferimenti della chiamata di conferma
govway message id : e6cf1981-6b51-492c-a5b9-da2bf66ed927
govway transaction id: 295ccfde-8554-11ef-bd08-0050568e9679
idAppalto: 19a3aec9-162d-44e0-b2e8-82f2584b82e7

Potremmo sapere quale sia stato il problema che ha provocato l'errore?

**Comment by supportoAnac** [comment]
Gentile utente,

a seguito della segnalazione da lei effettuata, abbiamo eseguito i controlli e abbiamo riscontrato che la versione SDK inserita nell'eForm non coincide con la versione attesa, motivo per cui si è generato l'errore. Tuttavia, abbiamo anche constatato che, dopo una serie di modifiche apportate dall'utente che ha effettuato l'inserimento, la scheda è stata comunque confermata con successo senza ulteriori errori.

Restiamo a disposizione per eventuali chiarimenti.

Cordiali saluti.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>da una verifica sui nostri sistemi, risulta che a seguito della chiamata in errore é stata effettuata una modifica della scheda che ha risolto ERR9999. In data 08/10 alle ore 16:22, la scheda A1_29 sia stata correttamente confermata.  <br>
 </p>

<p>Successivamente l'utente é riuscito a continuare la procedura.<br>
<br>
Restiamo a disposizione.</p>

<p><br>
<br>
Cordiali saluti<br>
<br>
 </p>
