### ISSUE TITLE
ERR9999 su crea scheda SC1 per un contratto da stipulare su una P7_2

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1757]
Invocando il servizio crea-scheda in ambiente di qualificazione con il seguente payload otteniamo il codice errore ERR9999

Payload_request:
{"idAppalto":"10f07c96-7854-47a9-94f1-693394c517f4","scheda":{"body":{"anacForm":{"datiContratto":{"codiceAusa":["9000000039"],"idPartecipante":"12fc190a-edc4-17ed-e063-020011acf7a6","cig":["I00617B8EF"],"dataDecorrenza":"2024-10-07T00:00:00+02:00","dataScadenza":"2024-11-08T00:00:00+01:00","importoCauzione":1.0}}},"codice":{"idTipologica":"codiceScheda","codice":"SC1"},"versione":"1.0"}}

Errore:
{"status":400,"title":"KO","detail":"SC_N_CRE","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}

govway message id: da7e93a1-f332-4724-9571-57a9095d98a0
govway transaction id: 98406bb8-856e-11ef-988f-0050568e08b3
idAppalto: 10f07c96-7854-47a9-94f1-693394c517f4

Potreste aiutarci a capire qual è il problema?

**Comment by anac-uscp** [comment]
<p>Salve,</p>

<p>da controlli effettuati sui nostri sistemi é emerso che l'ultima scheda confermata si tratta di una NAG, quest'ultima é stata creata e confermata in data 2024-06-11. Pertanto a segutio di una NAG non é possibile inviare una SC1 o altre schede, é ammesso lo "STATO FINALE".<br>
<br>
Saluti</p>
