### ISSUE TITLE
[Toscana/Bolzano] - P_20 e 21 - esito operazione: REG29 modalità acquisizione obbligatorio se S / F

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1759]
Buongiorno,

Vi segnalo un problema con l’esito-operazione per le schede P20 e P21. 
Dal changelog 2, il campo "modalità acquisizione" è stato reso facoltativo per gli appalti di tipo S/F su queste schede. 
Tuttavia, richiamando l’esito operazione dopo la creazione dell'appalto, viene ancora applicata la regola REG29, che segnala il campo "modalità acquisizione" come obbligatorio.
[data (11).json](https://github.com/user-attachments/files/17294271/data.11.json)

Riuscite a darci supporto?
Grazie.

**Comment by obigno77** [comment]
Il problema risulta fixato lo stesso giorno della segnalazione. Attendo a chiudere la issue in attesa di un feedback

**Comment by mariannagracco** [comment]
Buongiorno, @obigno77 

segnalo che riscontriamo sempre lo stesso problema indicato sopra.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>la informiamo che la regola REG29 non è più applicata alle schede P20 e P21. Pertanto la invitiamo a riprovare.<br>
<br>
Restiamo a disposizione per ulteriori verifiche.</p>

<p>Cordiali saluti</p>
