### ISSUE TITLE
Gestione delle tipologiche

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#176]

**Comment by FRASCA57** [comment]
nella gestione delle tipologiche si fa riferimento ad un codice tipologica, il cui elenco non è presente nella documentazione. E' possibile avere tale elenco ovvero la sua posizione nella documentazione?
Grazie.

**Comment by supportoAnac** [comment]
L'elenco non è presente in documentazione in quanto per ottenerlo si chiama il servizio apposito.

**Comment by FRASCA57** [comment]
Il contenuto della response non corrisponde a quanto presente in documentazione vedi issue #190
