### ISSUE TITLE
(ARIA SPA) ulteoriori chiarimenti SDA

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1760]
Buongiorno,

in riferimento a quanto richiesto nella issue #1714, aggiungo che dai test che stiamo effettuando riscontriamo errori generici nell'invio delle schede ISDA1 e ISDA2 (potrebbero essere legati ai bug generici del changelog2?) per cui non siamo riusciti ancora a confermare alcuna scheda.
inoltre, nel foglio lotti sembra possibile inserire più lotti compilando la scheda (dato che si tratta di un array). come ci si dovrebbe comportare se una SA compila più lotti? dovrebbe prevedere la nostra piattaforma di controllo o è già stato previsto lato ANAC?

Dato che queste nuove schede rientrano nel servizio di tutte le altre schede ci aspettiamo che a seguito di creazione di un appalto venga restituto l'IDAppalto, l'IDSDA viene restituito sempre in questo frangente o è un dato da recuperare con qualche altro servizio? 
dato che lo SDA non assegna dei CIG è la piattaforma che deve inibire la funzionalità di recupera CIG per queste schede particolari? (essendo il servizio di crea appalto uguale per tutte le schede in teoria dovrebbe essere invocabile anche il servizio di recupera CIG se non imponiamo dei vincoli) (ISDA1 e ISDA2 ad oggi dovrebbero essere le uniche schede sotto il "Crea Appalto" che non prevedono dei CIG)

**Comment by LucaMaggioni1** [comment]
rispetto agli errori citati nella creazione delle schede:

ISDA1 viene restituito l'errore sulla creazione dell'appalto ERR4: $.anacForm.lotti[0].
lottoSDATypeLotIdentifier
: is missing but it is required
ma questo campo non risulta previsto nel modello dati della ISDA1.

ISDA2 viene restituito l'errore alla conferma dell'appalto ERR40: errore generico durante l'estrazione dei dati della scheda

in allegato zip coon request e response dei test effettuati
[test_ISDA_Request-Response.zip](https://github.com/user-attachments/files/17309339/test_ISDA_Request-Response.zip)

**Comment by anac-uscp** [comment]
<p>Il termine delle attività trova risoluzione in quanto segue:<br>
<br>
E' previsto che le ISDA possano avere più lotti.<br>
Per recuperare l'idSDA e sufficiente chiamare il servizio di recupera-scheda, l'idScheda della ISDA restituito è l'idSDA da usare per la S0(questo procedimento non è necessario se si utilizza il servizio pcp-ui).<br>
Le schede ISDA sono già gestite per non rilasciare il CIG non dovrebbe essere necessario inibire questa funzionalità<br>
Il campo lottoSDATypeLotIdentifier è stato inserito per errore, è già stato rimosso, questo errore non dovrebbe piu riprensetarsi</p>
