### ISSUE TITLE
PRO-Q [Venicecom] – Errore nell'invio della scheda di aggiudicazione "ERR15"

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#1762]
Spett.le ANAC

Si richiede supporto sulla seguente procedura:

- 	Piattaforma: PRO-Q  
- 	Tipologia di gara: Procedura APERTA
- 	Fase Gara/Scheda: Affidamento scheda A1_29
- 	Errore riscontrato: ERR 15 "lotIdentifier non coerenti tra eForm ed anacForm".

 La procedura indetta con scheda P1_16 risulta avere 6 lotti: 

	5 aggiudicati 
	1 deserto

Da orchestratore risulta prevista la trasmissione della scheda A1_29. 
Comunicando la scheda, abbiamo riscontrato ERR15   "lotIdentifier non coerenti tra eForm ed anacForm".
Tale errore è stato causato dall’impossibilità di inserimento nell’anacForm dei dati relativi al lotto deserto (senza aggiudicatari). 
Mentre, nell’eForm, è stato possibile inserire i dati di tutti i 6 lotti, compreso quello deserto.
Questa discrasia non ci permette di completare la trasmissione della scheda, bloccando la procedura.

Si attende riscontro

**Comment by obigno77** [comment]
La trasmissione deve essere coerente tra anacForm e eform. Il Ted consente di inviare più avvisi di aggiudicazione in relazione ai diversi lotti.

**Comment by Gestore-Venicecom** [comment]
Gentile cliente,

ci troviamo di fronte a una problematica con il form ANAC, che richiede l'inserimento obbligatorio delle informazioni relative agli aggiudicatari per i lotti deserti, nonostante non vi siano offerte per tali lotti. Questo comportamento risulta incoerente con la realtà della procedura di gara.

Inoltre, il sistema TED richiede coerenza tra i lotti presenti nel form ANAC e l'eForm, il che ci impedisce di procedere correttamente.

La risposta che ci è stata fornita finora non risolve il problema, e di conseguenza siamo bloccati.

Richiediamo un riscontro urgente su come procedere per risolvere la questione e sbloccare la situazione.

Cordiali saluti.

**Comment by obigno77** [comment]
Con il rilascio del changelo-03 sarà possibile bypassare la scheda S2
