### ISSUE TITLE
FVOE Gestione nuovi tipoDocumento CHANGELOG-02

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1763]
Nel fare dei test in ambiente di certificazione si riscontra l'errore "FVX56 - Tipo documento non valido" per i nuovi tipo documento

1.  00008 - Durc in corso di Validità
2.  00042 - Carichi fiscali pendenti

Si richiede conferma dell'anomalia e riscontro della sua rimozione.

**Comment by anac-uscp** [comment]
<p>Gentile Utente,<br>
 </p>

<p>l'errore segnalato si verifica quando, nel servizio <strong>/richiedi-documenti</strong>, viene passato un tipo documento non censito.<br>
Si fornisce la documentazione pubblicata per verificare la lista dei tipi di documenti validi:<br>
<a href="https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md" rel="noopener" target="_new">https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md</a>.</p>

<p>A seguito di un'analisi della configurazione, è emerso che in ambiente di <strong>PRE-ESERCIZIO</strong> erano mancanti le configurazioni dei documenti <strong>00042</strong>, <strong>00008</strong> e <strong>00007</strong>.<br>
L'allineamento è stato effettuato in data <strong>25/11</strong>.</p>

<p>Si invita a effettuare un'ulteriore tentativo.</p>

<p><br>
Restiamo a disposizione<br>
<br>
<br>
Cordiali Saluti </p>
