### ISSUE TITLE
FVOE - Anomalia Tipo documento - addendum

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1764]
da una verifica a tappeto dei tipo documenti presenti nella tipologica, si sono riscontrati ulteriori tipo documento per i quali viene proposto l'errore FVX56 - Tipo documento non valido. Si riporta la lista completa dei casi in cui si riceve l'errore FVX56:

1. 00008 - già segnalato
2. 00009 - Sanzioni sicurezza sul lavoro
3. 00024 - DURC
4. 00040 - DURC inarcassa professionisti
5. 00042 - già segnalato

Si attende riscontro

**Comment by anac-uscp** [comment]
<p>Gentile Utente,<br>
 </p>

<p>Per i tipi documento 00008 e 00042, l'errore riscontrato era dovuto a un mancato allineamento, che è stato risolto in data 18/10.<br>
<br>
Per il tipo documento 00009, l'errore è correttamente segnalato, poiché è attualmente in fase di sviluppo e quindi non pubblicabile in QLF.<br>
I tipi di documento utilizzabili sono solo quelli riportati nella documentazione pubblicata all'indirizzo: <a href="https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md" rel="noopener" target="_new">https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md</a>.</p>

<p>Per i tipi documento 00024 e 00040, l'errore è correttamente segnalato perché non è previsto l’utilizzo del servizio <em>richiedi-documenti</em> per questa tipologia, come indicato nella documentazione precedentemente segnalata.</p>

<p>Restiamo a disposizione per ulteriori chiarimenti.</p>

<p>Cordiali saluti</p>
