### ISSUE TITLE
[CONSIP] - P7_1_3 - Controllo sul campo "motivazione CIG" fallito

### ISSUE THREAD

**Issue by alessiopera** [anticorruzione/npa#1765]
Notiamo un errore all'interno della struttura del file DMN per la scheda P7_1_3.

Infatti nel tag output non viene definto l'attributo "name" che funge da chiave per la restituzione della mappa di errori prodotta dal rule engine. Al posto dell'attributo "name" è stato inserito l'attributo "label". Non essendoci l'attributo name l'errore viene riconosciuto ma non restituito, poichè non mappato.

Abbiamo notato che anche altre schede soffrono dello stesso problema (P7_1_1 e P7_1_2).

allego lo screen della definizione errata per la scheda P7_1_3:

(tra l'altro notiamo anche un refuso sulla definizione dell'id che porta AD1_10 e non P7_1_3)

![image](https://github.com/user-attachments/assets/31781639-1b9a-466a-8c05-a3b63a1b8117)

E quello della definizione corretta (prendendo ad esempio la P2_11): 

![image2](https://github.com/user-attachments/assets/4a677be1-5bff-4390-afe9-d1c0b894901a)

Vi chiederei di verificare l'errore
Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>la segnalazione è corretta, le regole P7_1_1.dmn,P7_1_2.dmn,P7_1_3.dmn,P7_2.dmn saranno corrette inserendo "Errore" come Output name e non come label.</p>

<p>La problematica verrà risolta con il prossimo rilascio previsto entro la fine di questa settimana.</p>

<p>Grazie per la collaborazione.</p>

<p>Cordiali saluti.</p>
