### ISSUE TITLE
[CONSIP] - Scheda AD1_25 - AD1_26 - AD1_27 errore per REG68_1

### ISSUE THREAD

**Issue by alessiopera** [anticorruzione/npa#1766]
trasmettendo le schede AD1_25 - AD1_26 - AD1_27 riscontriamo un Err REG68_1:

Secondo la seguente condizione appalto.datiBaseProcedura.tipoProcedura.codice ! = "neg-wo-call" , il campo eform BT-105-Procedure deve essere diverso da "Negoziata senza previa indizione di gara". Questa condizione va in contrapposizione con l'errore 46. Infatti aggiornando il valore del campo  BT-105-Procedure con un valore diverso da "neg-wo-call" e caricando l'xml nella sezione eform, nella sezione "COMUNICA CON PCP" la regola 68 non viene più mostrata e subentra l'errore 46:
ERR46 - Se 'Tipo di avviso' (BT-02) Ã¨ 'Avviso volontario per la trasparenza ex ante', allora 'Tipo di procedura' (BT-105) deve essere 'Negoziata senza previa indizione di gara'

{
"result": {
"exitCode": "400",
"text": "Servizio momentaneamente non disponibile"
},
"payload": {
"code": 400,
"responseData": null,
"errors": [
{
"errorCode": "400 KO",
"shortDescription": "{"instance":null,"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","codice":"REG68_1","dettaglio":""}]}",
"keyMessage": ""
}
]
}
}

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>la REG68_1 cita: il campo giustificazione aggiudicazione diretta è obbligatorio se il tipo di procedura è Negoziata senza previa indizione di gara<br>
 <br>
come indicato nella scheda é stato indicato "appalto.datiBaseProcedura.tipoProcedura" con il codice "neg-wo-call", quindi é necessario inserire anche il campo "appalto.datiBaseProcedura.giustificazioniAggiudicazioneDiretta".</p>

<p>Nel caso del TED i campi interessati sono:</p>

<p>giustificazione aggiudicazione diretta -&gt; bt-136 - Direct Award Justification Code<br>
tipo procedura: -&gt;bt-105 - Procedure Type</p>

<p>occorre quindi verificare di aver correttamente inserito il primo campo: BT-136</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
