### ISSUE TITLE
[Venicecom] -Richiesta urgente di assistenza per rettifica e aggiunta codice AUSA e Centro di Costo su ANACform

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#1767]
Gentile,

con la presente, chiediamo assistenza urgente riguardo alla necessità di aggiungere un codice AUSA e un secondo Centro di Costo nell'array della stazione appaltante all'interno del modulo ANACform.

Attualmente, questa problematica sta bloccando il nostro flusso di lavoro e risulta essenziale trovare una soluzione per poter procedere con la rettifica necessaria.

Abbiamo già aperto ticket sia per l'ambiente di produzione che per quello di collaudo, ma purtroppo non abbiamo ancora ricevuto alcuna risposta dal supporto ANAC @anac-uscp  @supportoAnac  . Dato l'impatto significativo, chiediamo cortesemente un intervento tempestivo.

Restiamo in attesa di un vostro riscontro e vi ringraziamo anticipatamente per l'attenzione.

Cordiali saluti,

**Comment by obigno77** [comment]
Il dato delle stazioni appaltanti coinvolte è al momento ritenuto elemento essenziale e non rettificabile a posteriori del bando, soprattutto se questo ha avuto evidenza pubblica. Sono in corso ulteriori valutazioni sul piano giuridico.
