### ISSUE TITLE
[CONSIP][ATTESTAZIONE] richieste di pubblicazione pending

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1768]
salve,
abbiamo effettuato una richiesta di pubblicazione (pubblica-avviso) per una AD3.
la richiesta rimane perennemente in WT:

{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"9625c8e9-65e3-49f4-9d09-c1f043260a29","idScheda":"2e9a95fd-5d1b-4c97-bd91-ff60104b885f","codiceScheda":"AD3","idAvviso":"b2aee403-3070-415f-9afd-d1f7f546dcec","esito":{"idTipologica":"esito","codice":"WT"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AV_PUBB"},"dataControllo":"2024-10-15T17:16:32.086+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AV_RICHIESTA_PUBB_IN_CORSO"}}]}

potete verificare?
idAppalto=9625c8e9-65e3-49f4-9d09-c1f043260a29
GovWay-Message-ID=586036fd-0f9c-413d-a140-05c2a1b9dd41
GovWay-Transaction-ID=3f9c1f48-8b08-11ef-b339-0050568e7535

**Comment by obigno77** [comment]
L'ambiente di attestazione al momento non sta pubblicando. CI stiamo lavorando

**Comment by mariannagracco** [comment]
Ciao @obigno77 , segnalo che riscontriamo lo stesso problema anche per l'ambiente di collaudo.

**Comment by obigno77** [comment]
Il problema è stato risolto
