### ISSUE TITLE
Apertura FVOE per soggetti presenti in una scheda S0

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1769]
In seguito alla conferma di una scheda S0 dovrebbe essere accessibile l'FVOE dei soggetti in essa indicati.
Nella richiesta-accesso-fvoe è obbligatorio l'indicazione del campo appalto che non è nella disponibilità nel caso di partecipante a Sistema Dinamico di Acquisizione. E' necessario comprendere come superare il problema.

**Comment by obigno77** [comment]
A quale campo appalto si fa riferimento? L'idAppalto viene rilasciato anche per ISDA

**Comment by AFSOLUZIONI** [comment]
OK. Ho bisogno di un chiarimento:
la documentazione del campo appalto nell'ISDA1 e nell'ISDA2 è la seguente:
![image](https://github.com/user-attachments/assets/71dd37bb-63dd-427f-aaef-323ae9a4267c)
E' evidente che il campo idAppalto è stato sostituito dall'idSDA.
Al momento non ho ancora eseguito un crea-appalto nè per ISDA1 nè per ISDA2 ma presupponevo che la response del crea-appalto contenesse il campo idSDA attribuito da ANAC in luogo dell'idAppalto che di consueto viene rilasciato.
es.
    {
              "detail": "Creazione eseguita con successo",
              "errori": null,
              "GovWayMessageId": " d05e2793-5c44-48f0-809e-c5ed1c10c149",
              "GovWayTransactionId": " 17ec310a-8c97-11ef-bd08-0050568e9679",

              **"idSDA": "6d83e6b4-9ac2-432e-9264-86d81401a35b",**
               invece di
              **"idAppalto": "6d83e6b4-9ac2-432e-9264-86d81401a35b",**

              "status": 200,
              "title": "Operazione Effettuata",
              "type": "about:blank"
          }   
Ora la domanda è d'obbligo:

che cosa c'è nella response di un crea-appalto per le schede ISDA1 e ISDA2?? idAppalto, idSDA o entrambi???
La domanda originale riguardava la necessità di comprendere cosa inserire nel campo appalto della richiesta-accesso-fvoe, partendo dalla considerazione (intuitiva) che il crea-appalto restituiva un idSDA invece di un idAppalto.

Ultima considerazione: ma l'idSDA è forse un idAppalto a cui è stato cambiato solo il nome?? Questo risolverebbe comletamente il quesito.

**Comment by supportoAnac** [comment]
Gentile utente,

il campo _idSDA_ rappresenta l'ID della scheda SDA generata in seguito alla chiamata _crea-appalto_. È possibile recuperare l'ID della scheda eseguendo la chiamata _ricerca-scheda_. Pertanto, nel campo _idSDA_ va inserito l'_idScheda_ della scheda restituita.

Restiamo a disposizione per eventuali chiarimenti.

Cordiali saluti.
