### ISSUE TITLE
Quesito tecnico sulle tipologiche

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#177]
in realtà i quesiti sono due:

1. per quasi tutte le tipologiche il campo è un campo complesso (idTipologica + codice). ho notato che in alcuni casi questo approccio non viene rispettato e non è riportato neanche il type del campo (si presume "string"). E' un refuso oppure è voluto che il comportamento non sia omogeneo per tutte le tipologiche?? In realtà in qualche caso (es. codiceIstat in LottoP2_16Type e LottoP_23Type) in un caso non c'è (nel primo) e nell'altro non c'è (nel secondo.
2. dove è possibile reperire l'elenco dei codici tipologiche?? Sembra che il servizio recupera-tipologiche li renda disponibili, ma non c'è in documentazione tale elenco??

**Comment by supportoAnac** [comment]
1. Per il quesito 1, si richiede di effettuare una nuova verifica a seguito dell’ultimo rilascio, e riformulare eventualmente  la segnalazione portando degli esempi. 
Quelli citati, LottoP2_16Type e LottoP_23Type, hanno la struttura corretta (idTipologica + codice). 

2 . L'elenco non è presente in documentazione in quanto per ottenerlo si chiama il servizio apposito.
