### ISSUE TITLE
sollecito per issue #1743 - [Venicecom] servizio "recupero-anagrafica-oe" restituisce errore 404 errore generico

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#1770]
Salve,

 ci risulta che avete bloccato l'issue aperta #1743  potete dari indicazione in quanto siamo bloccati

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>stiamo analizzando la problematica, la risposta verrá fornita nella issue di riferimento (https://github.com/anticorruzione/npa/issues/1743).<br>
<br>
Restiamo a disposizione.<br>
<br>
Cordiali saluti</p>
