### ISSUE TITLE
[CONSIP] Incongruenza stato avviso su testpubblicitalegale.anticorruzione.it

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1771]
Salve,
a seguito dell'invio di una scheda che prevede pubblicazione nazionale (PVL), è emerso quanto segue:

Su https://testpubblicitalegale.anticorruzione.it/bandi/ l'avviso risulta pubblicato in data **15/10/2024**
![image](https://github.com/user-attachments/assets/3475059b-1474-4720-ae0c-94c040fe015e)

Mentre, ad oggi,  chiamando i servizi di stato-avviso e esito-operazione l'avviso risulta ancora in attesa di pubblicazione:

**stato-avviso**
GovWay-Message-ID
[3775376d-5ba1-4b6a-b6a1-873f4788b1ee]
GovWay-Transaction-ID
[9bf858f1-8baa-11ef-bd08-0050568e9679]
{
  "status": 200,
  "title": "OK",
  "detail": "Operazione Effettuata",
  "type": "about:blank",
  "statoAvviso": {
    "idAvviso": "efc32ae4-e856-4306-a65f-f09760966382",
    "idAppalto": "15def76c-c29e-45cb-ba26-c5a9c74f8d95",
    "dataControllo": "2024-10-14T15:43:59.580+00:00",
    "stato": {
      "idTipologica": "statoAvviso",
      "codice": "IN_ATT_PUBB"
    }
  }
}

**esito-operazione**
GovWay-Message-ID
[f543a4b4-febc-4df8-8141-864dcc4e6ab9]
GovWay-Transaction-ID
[01bee227-8bab-11ef-988f-0050568e08b3]
{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "15def76c-c29e-45cb-ba26-c5a9c74f8d95",
      "idScheda": "d795f81d-02d9-47c1-a368-c7621089a38e",
      "codiceScheda": "P3_4",
      "idAvviso": "efc32ae4-e856-4306-a65f-f09760966382",
      "esito": {
        "idTipologica": "esito",
        "codice": "OK"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AV_PUBB"
      },
      "dataControllo": "2024-10-14T15:43:59.892+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AV_IN_PUBB"
      }
    }
  ]

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>dai controlli effettuati sui nostri sistemi risultano due avvisi: uno relativo alla scheda di indizione (P3_4) e uno relativo alla scheda di aggiudicazione (A3_4). Entrambi risultano correttamente in stato "Pubblicato", rispettivamente in data 15/10/2024 e 29/10/2024.</p>

<p>Rimaniamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti</p>
