### ISSUE TITLE
[CONSIP] - Scheda AD1_25 - AD1_26 - AD1_27 - AD1_28 errore per REG68_1

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1774]
Salve,
in riferimento alla issue #1730, si fa presente che per le schede in oggetto la problematica non risulta risolta in quanto la regola REG68_1 referenzia dei campi non previsti dalle schede pertanto andrebbe rimossa dai relativi file dmn.

Restiamo a disposizione per eventuali chiarimenti.

Cordiali saluti.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>La regola REG68_1 applica il controllo di obbligatorietà del ted sul campo BT-136. I campi considerati nella regola sono il BT-136 e il BT-105, entrambi presenti nell'eform delle AD1_25, AD1_26, AD1_27, AD1_28.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>

<p> </p>
