### ISSUE TITLE
[CONSIP] - P6_2 - ''ERR9999 - errore generico'' - Ambiente di Attestazione

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1775]
Buongiorno,
abbiamo effettuato il seguente test:
A seguito della richiesta Cig della scheda P6_2, riscontriamo il seguente errore:
'ERR9999 - errore generico''

Indipendentemente dai dati che precompiliamo, riceviamo ERR9999

Di seguito i dettagli della scheda:
[P6.2 - ERR9999.txt](https://github.com/user-attachments/files/17409317/P6.2.-.ERR9999.txt)

id_appalto: eb6e7242-60ae-40ba-9a35-341d30621249

**Comment by supportoAnac** [comment]
Gentile utente,

abbiamo verificato che sulla scheda da lei cercato di confermare in ambiente di attestazione non sono presenti irregolarità. Pertanto, le consigliamo di riprovare a eseguire l'operazione.

Restiamo a disposizione per eventuali ulteriori chiarimenti.

Cordiali saluti.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>abbiamo verificato che sulla scheda da lei cercato di confermare in ambiente di attestazione non sono presenti irregolarità. Pertanto, le consigliamo di riprovare a eseguire l'operazione.</p>

<p>Restiamo a disposizione per eventuali ulteriori chiarimenti.</p>

<p>Cordiali saluti.</p>
