### ISSUE TITLE
[ARIA SPA] eDGUE 4.0 - date di Rilascio per l'ecosistema italiano

### ISSUE THREAD

**Issue by lmanc77** [anticorruzione/npa#1776]
Buongiorno,
risultano pubblicate al link https://github.com/OP-TED/ESPD-EDM/releases/tag/v4.0.0 le specifiche relative alla versione 4.0 dell'eDGUE, ma non si fa menzione di alcuna data di rilascio, nè per gli ambienti di test, nè per quello di produzione.

Quando saranno rese disponibili maggiori informazioni lato ANAC, per quanto riguarda l'ecosistema italiano?

Grazie

**Comment by obigno77** [comment]
Le informazioni dovrebbero arrivare in primis da Agid. Al momento ANAC non pone vincoli sulla versione del dgue trasmesso alla PCP
