### ISSUE TITLE
[BLK ]Errore crea appalto scheda P7_2

### ISSUE THREAD

**Issue by Silvio1970** [anticorruzione/npa#1777]
Quando cerco di confermare la scheda P7_2
ricevo questo errore
{"status":400,"title":"KO","detail":"Errore Validazione Tipologiche","type":"about:blank","errori":[{"idTipologica":"errori","dettaglio":"'condizioniNegoziata' : {'condizioniNegoziata' : '1'}","codice":"ERR63"},{"idTipologica":"errori","dettaglio":"'settore' : {'settore' : '1'}","codice":"ERR63"}]}
ma i codici delle enum relative sono esattamente quelle indicate

"condizioniNegoziata":[{
                        "idTipologica":"condizioniNegoziata",
                        "codice":"1"
                     }],
"settore":{
                  "idTipologica":"settore",
                  "codice":"1"
               },

avendo una certa urgenza gradirei una risposta celere

**Comment by obigno77** [comment]
E' possibile avere l'idAppalto?

**Comment by Silvio1970** [comment]
l'errore mi viene restituito nella crezione dell'appalto e quindi non ho
nessu id appalto da indicare

Cordiali Saluti
_______________
=========================
Silvio Auciello

mob.: +393313206852
***@***.***


=========================


La presente comunicazione ed i suoi allegati e' destinata esclusivamente
ai destinatari. Qualsiasi suo utilizzo, comunicazione o diffusione non
autorizzata
e' proibita. Se ha ricevuto questa comunicazione per errore, la preghiamo
di darne
immediata comunicazione al mittente e di cancellare tutte le informazioni
erroneamente acquisite. (Rif. D.Lgs. 196/2003). Grazie

This message and its attachments are intended only for use by the
addressees. Any use,
re-transmission or dissemination not authorized of it is prohibited. If you
received
this e-mail in error, please inform the sender immediately and delete all
the material.
(Rif. D.Lgs. 196/2003). Thank you.

Il giorno ven 18 ott 2024 alle ore 06:09 Alessandro Obino <
***@***.***> ha scritto:

**Comment by Silvio1970** [comment]
Buongiorno, non ho avuto più nessuna risposta in merito al mio quesito a parte la richiesta di un id appalto che non posso fornire se l'errore viene da un crea appalto 
resto ancora in attesa ma ripeto la risposta è abbastanza urgente visto che mi blocca la procedura grazie

**Comment by Silvio1970** [comment]
non capisco cosa sia la busta se è il json della scheda p7_2 eccola

Cordiali Saluti
_______________
=========================
Silvio Auciello

mob.: +393313206852
***@***.***


=========================


La presente comunicazione ed i suoi allegati e' destinata esclusivamente
ai destinatari. Qualsiasi suo utilizzo, comunicazione o diffusione non
autorizzata
e' proibita. Se ha ricevuto questa comunicazione per errore, la preghiamo
di darne
immediata comunicazione al mittente e di cancellare tutte le informazioni
erroneamente acquisite. (Rif. D.Lgs. 196/2003). Grazie

This message and its attachments are intended only for use by the
addressees. Any use,
re-transmission or dissemination not authorized of it is prohibited. If you
received
this e-mail in error, please inform the sender immediately and delete all
the material.
(Rif. D.Lgs. 196/2003). Thank you.

Il giorno mer 23 ott 2024 alle ore 10:26 Alessandro Obino <
***@***.***> ha scritto:

**Comment by Silvio1970** [comment]
Buongiorno chiedo se possibile un feedback alla mia richiesta aperta ben 2 settimane fa
ho provato a modificare il codice condizioniNegoziata inserendo codice 46, ovviamente preso da vs. tipologica, ma anche se come errore scompare ritorna il settore che da tipologica è 1 -Ordinario 2- Speciale 
{"status":400,"title":"KO","detail":"Errore Validazione Tipologiche","type":"about:blank","errori":[{"idTipologica":"errori","dettaglio":"'settore' : {'settore' : '1'}","codice":"ERR63"}]}

come posso risolvere in breve tempo ?
allego json inviato per la conferma
[SchedaP7_2_2246.json](https://github.com/user-attachments/files/17567941/SchedaP7_2_2246.json)

**Comment by obigno77** [comment]
Si prega di riprovare

**Comment by Silvio1970** [comment]
Provato sembra tutto a posto la ringrazio e mi scuso per l'insistenza
