### ISSUE TITLE
Rettifica avviso scheda P1_16 - ERR9999- errore generico

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1780]
Stiamo riscontrando problemi invocando il servizio di rettifica-avviso in ambiente di attestazione per una procedura sopra soglia P1_16.
L'errore mostrato è ERR9999 - errore generico

IdAppalto: 7a3b5f71-ffa0-488b-a8e3-7c89c27861c9
govway message id: 8a586d38-1dc4-4c01-b3b9-4c6d1849de66
govway transaction id: b771faf9-8c74-11ef-b339-0050568e7535

[payload_request_rettifica.json](https://github.com/user-attachments/files/17414114/payload_request_rettifica.json)

Essendo prossimi a dover effettuare una rettifica avviso in ambiente di esercizio, potreste darci un riscontro?

**Comment by mariottiDPA** [comment]
Se si tratta della nostra stessa casistica, il problema è legato al fatto che va modificato il campo versionID nell'eform: anziché 01 (ad esempio) dovrebbe essere 02, se si tratta della prima rettifica.

**Comment by masko82** [comment]
Io ricordo che la modifica della versione deve essere fatta in caso di "modifica-avviso".
In caso di rettifica-avviso queste specifiche sono state cambiate di recente?
