### ISSUE TITLE
Scheda A2_29 - Errore codice REG68_1

### ISSUE THREAD

**Issue by CUCAssisi** [anticorruzione/npa#1783]
Buongiorno, 
in fase di conferma della Scheda relativa all'aggiudicazione A2_29 compare un nuovo errore non identificato (codice REG68_1).

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>la REG68_1 cita: il campo giustificazione aggiudicazione diretta è obbligatorio se il tipo di procedura è Negoziata senza previa indizione di gara,</p>

<p>probabilmente nella scheda é stato indicato "appalto.datiBaseProcedura.tipoProcedura" con il codice "neg-wo-call".</p>

<p>quindi é necessario inserire anche il campo "appalto.datiBaseProcedura.giustificazioniAggiudicazioneDiretta".</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>
