### ISSUE TITLE
 FVOE - Molteplicità risposta a richiedi-documenti per il tipo documento 00001 (certificato antimafia)

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1784]
si richiede conferma che la richiesta espressa per il tipo documento 00001 (in realtà anche per il tipo documento 00004) possa prevedere  una pluralità di soggetti (persone fisiche) da verificare e che la verifica-stato-richiesta-documento mostri sempre la situazione di tutti i soggetti presenti nella richiesta originale. Il tentativo di verificare questo caso non ha avuto effetto in ambiente di qualificazione, anzi la risposta contiene informazioni non coerenti con la richiesta. In sintesi il primo soggetto non ha il suo codice fiscale di PF ma quello dell'OE e del secondo soggetto non c'è traccia. In allegato la response del servizio verifica-stato-documento in parola.

{
    "result": [
        {
            "chiaveAccesso": "5ded1cba-ac4a-47ef-bdda-86c7d5b843f8",
            "idRichiesta": "b65c30fe-eafe-47a2-a1ba-90a864380712",
            "operatoreEconomico": {
                "codiceFiscale": "11111111114"
            },
            "soggetto": {
                "codiceFiscale": "11111111114" **qui non c'è il CF della persona fisica richiesta**
            },
            "stato": {
                "codice": "005",
                "id": "statoRichiestaDocumento"

                         **qui manca il secondo soggetto richiesto**

            },
            "tipoDocumento": {
                "codice": "00001",
                "id": "tipoDocumento"
            }
        }
    ],
    "status": 200,
    "title": "Operazione terminata correttamente"
}

**Comment by anac-uscp** [comment]
<p>Gentile Utente,<br>
<br>
<br>
Per quanto riguarda il tipo di documento 00004, quando viene effettuata la richiesta è possibile inserire più soggetti, ma vengono creati due stati di richiesta distinti.<br>
<br>
Per il documento 00001, è possibile richiedere per più soggetti; tuttavia, nella verifica dello stato del documento, viene mostrato il codice fiscale dell'OE presente nel fascicolo per cui si sta richiedendo la documentazione.<br>
<br>
<br>
Restiamo a disposizione <br>
<br>
<br>
Cordiali Saluti</p>
