### ISSUE TITLE
[Maggioli] Gare a lotti: crea-appalto restituisce timeout dopo 120 secondi

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1785]
Buongiorno,
con riferimento alla precedente issue chiusa n. [1620](https://github.com/anticorruzione/npa/issues/1620), abbiamo riscontrato con esito positivo la creazione di un appalto con 200 lotti.

Abbiamo provato quindi con 400 lotti e dopo 2 minuti abbiamo nuovamente l'errore di timeout.
![image](https://github.com/user-attachments/assets/44b1b2a4-c40e-41ff-891e-a4125d922982)

Allego a seguire il json del pacchetto trasmesso per le vostre verifiche.

NB: abbiamo casi di gare che arrivano a poco meno di 1000 lotti...  

Grazie

**Comment by paolo-urbanetto** [comment]
Dati di test con 400 lotti:
[eForm_400lotti_P1_16_servizi.zip](https://github.com/user-attachments/files/17433758/eForm_400lotti_P1_16_servizi.zip)

**Comment by obigno77** [comment]
Il timeout è sempre possibile se la transazione impiega oltre 2 minuti. In questo caso è possibile reperire l'idAppalto consultando per codiceAppalto.
