### ISSUE TITLE
revoca gara/lotto

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1786]
Buongiorno,

per fare una revoca è corretto che:

- in caso di procedure sottosoglia, l'informazione viene inviata la scheda NAG.
- in caso di procedure soprasoglia, l'informazione viene inviata con la scheda A1_XX.

se quanto sopra è confermato, per il caso sopra soglia, è corretto che l'utente si interrompa con l'invio della scheda A1 (che non è una scheda conclusiva del flusso) o deve procedere con la CO1?

**Comment by obigno77** [comment]
Corretto il sottosoglia.
Nel soprasoglia l'avviso di aggiudicazione può essere inviato solo se è già stato stipulato il contratto in quanto la data di stipula è obbligatoria nell'eform quindi non è attualmente possibile trasmettere una revoca dell'aggiudicazione
