### ISSUE TITLE
ERR9999 su crea scheda SC1 per un contratto da stipulare su una P7_2

### ISSUE THREAD

**Issue by masko82** [anticorruzione/npa#1787]
Invocando il servizio crea-scheda in ambiente di qualificazione con il seguente payload otteniamo il codice errore ERR9999

Payload_request:
{"idAppalto":"ec1cb0af-71ff-451d-858d-9a99e3017d86","scheda":{"body":{"anacForm":{"datiContratto":{"codiceAusa":["9000000039"],"idPartecipante":"166128a8-ae9b-0b17-e063-0806020a67fb","cig":["I00A23963C"],"dataDecorrenza":"2024-10-18T00:00:00+02:00","dataScadenza":"2025-10-30T00:00:00+01:00","importoCauzione":100.0}}},"codice":{"idTipologica":"codiceScheda","codice":"SC1"},"versione":"1.0"}}

Errore:
{"status":400,"title":"KO","detail":"SC_N_CRE","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}

idAppalto :ec1cb0af-71ff-451d-858d-9a99e3017d86
govway message id: 98b82826-10bb-47af-8645-cd14599cb64d
govway transaction id:fa5bd824-8d39-11ef-988f-0050568e08b3

In questo caso, al contrario della issue https://github.com/anticorruzione/npa/issues/1757, l'ultima scheda confermata è una A2_29
[lista esiti SC_CONF.json](https://github.com/user-attachments/files/17434667/lista.esiti.SC_CONF.json)

Potreste aiutarci a capire qual è il problema?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>dai controlli effettuati, risulta che la creazione della scheda è stata avviata prima della pubblicazione completa della scheda precedente, causando l'errore <strong>ERR9999</strong>. Nello specifico, la pubblicazione è stata inoltrata in data 17/10 ed effettivamente pubblicata in data 25/10, mentre la scheda SC1 è stata tentata di creare il 18/10.</p>

<p>Alla luce di ciò, la invitiamo a riprovare la creazione della scheda. Qualora l'errore si ripresentasse, la preghiamo di riaprire la segnalazione.</p>

<p>Cordiali saluti</p>
