### ISSUE TITLE
Swagger Editor - Errore tipoDocumentoEnum

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#179]
Se si utilizza uno swagger editor per indagare il contenuto dei servizi, risulta che la risposta del servizio /ricerca-documenti-fvoe ha tra i suoi parametri  TipoDocumentoEnum, ma il realtà, sempre usando lo swagger editor, il link https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/tipologiche/tipoDocumento.jsoN non punta a nulla (error 404:not found).

Se si usa direttamente GitHub si riesce a reperire la tipologica che comunque ma non ha alcuna attinenza con il servizio in oggetto e con il contenuto atteso

 "codice":"00900",
    "descrizione": {
		"it": "espd-Request - European single procurement document - Request",
		"en": "espd-Request - European single procurement document - Request"
		},
    "dataInizio":null,
    "dataFine":null
},{
    "codice":"00901",
    "descrizione": {
		"it": "eform - Standard di notifica per le procedure di appalto pubblico nell'UE",
		"en": "eForm - Notification standard for public procurement procedures in the EU"
		},
    "dataInizio":null,
    "dataFine":null
},{
    "codice":"00902",
    "descrizione": {
		"it": "anacForm - Dati aggiuntivi richiesti da ANAC",
		"en": "anacForm - Additional data requested by ANAC"
		},
    "dataInizio":null,
    "dataFine":null
},{
    "codice":"00903",
    "descrizione": {
		"it": "scheda ANAC",
		"en": "scheda ANAC"
		},

Per completezza riporto l'esempio di risposta di /ricerca-documenti-fvoe
{
  "status": 200,
  "title": "Operazione terminata correttamente",
  "totRows": 2,
  "totPages": 1,
  "currentPage": 1,
  "elementPage\"": 2,
  "result": [
    {
      "idDocumento": "507f1f77bcf86cd799439011",
      "tipo": {
        "codice": "01",
        "descrizione": {
          "it": "DURC"
        }
      },
      "stato": {
        "codice": "21",
        "descrizione": {
          "it": "IN LAVORAZIONE"
        }
      },
      "oggetto": "",
      "dataInserimento": "2014-02-28T18:07:17Z",
      "fascicoli": {
        "idFascicolo": "878g1j75bcf86cd799439022"
      }
    },
    {
      "idDocumento": "507f1f77bcf86cd799888889",
      "tipo": {
        "codice": "01",
        "descrizione": {
          "it": "DURC"
        }
      },
      "stato": {
        "codice": "01",
        "descrizione": {
          "it": "IN LAVORAZIONE"
        }
      },
      "oggetto": "",
      "dataInserimento": "2014-02-28T18:07:17Z",
      "fascicoli": {
        "idFascicolo": "999f1f77cdf86cd799489011"
      }
    }
  ]
}

**Comment by supportoAnac** [comment]
Superato da versioni successive.
