### ISSUE TITLE
FVOE - Chiarimenti su documenti disponibili nel fascicolo.

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1790]
nel richiedere la chiusura dell'issue 1763 (ricompresa nella #1764 a cui si è già data risposta), si richiedono alcuni chiarimenti:

1. dovendo utilizzare la tipologica dei tipo-documento per rappresentare i documenti richiedibili all'utente della piattaforma, sarebbe opportuno che essa contenesse documenti la cui disponibilità sia o presente per precedenti richieste all'Ente certificante o richiedibile (tramite il servizio richiedi-documenti) nel caso di sua assenza. In alternativa sarebbe utile inserire una data di inizio superiore a quella corrente in maniera da indicare la sua indisponibilità al momento ed eliminarlo da quelli "richiedibili"
2. è corretto che i documenti di tipo 009xx e 007xx non sono nel perimetro dell'FVOE?
3. nella risposta alla issue à1764 il documento 00009 è stato segnalato come di prossima disponibilità, mentre i documenti 00024 e 00040 sono stati segnalati come non richiedibili tramite il servizio richiedi-documenti. C'è differenza ovvero sono tutti e tre in sviluppo?
4. il documento 00007 è correttamente segnalato come "in progress" nella tabella citata: sarebbe possibile inserire anche gli altri tipo documento in questo modo, avendo un perfetto allineamento tra tipologica e documento?
5. il documento con tipo documento 00042 - Carichi fiscali pendenti è presente nel documento indicato (https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md)
con codice 00006 che non è presente nella tipologica. Qual è il codice corretto? Sarebbe opportuno tenere allineate le due strutture.
6. infine che differenza c'è tra il documento 00038 -  DURC inarcassa professionista e il documento 00040 - DURC inarcassa professionisti??

**Comment by anac-uscp** [comment]
<p>Gentile Utente,<br>
<br>
 </p>

<ul>
	<li>
	<p>1. dovendo utilizzare la tipologica dei tipo-documento per rappresentare i documenti richiedibili all'utente della piattaforma, sarebbe opportuno che essa contenesse documenti la cui disponibilità sia o presente per precedenti richieste all'Ente certificante o richiedibile (tramite il servizio richiedi-documenti) nel caso di sua assenza. In alternativa sarebbe utile inserire una data di inizio superiore a quella corrente in maniera da indicare la sua indisponibilità al momento ed eliminarlo da quelli "richiedibili"<br>
	<strong>la tipologica "tipo-documento" contiente tutti i documenti del contesto npa.<br>
	i tipi documenti richidibili sono SOLO quelli riportati nella documentazione <a href="https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md">https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md</a><br>
	Per ogni tipo-documento é presente la data-creazione che corrisponde alla data in cui il documento viene utilizzata dalla funzionalità della npa<br>
	Se la piattaforma deve mostrare i soli tipidocumenti richiedibili estragga il dato dalla tabella riportata <a href="https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md">https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md</a></strong></p>

	<p>2. è corretto che i documenti di tipo 009xx e 007xx non sono nel perimetro dell'FVOE?</p>

	<p><strong>i tipidocumento 009xx sono attualmente utilizzati dal FVA (Fascicolo Virtuale dell'Appalto)<br>
	i tipidocumento 007xx sono attualmente utilizzati dal FVUP (Fascicolo Virtuale del Proflio Utente)<br>
	i restanti tipodocumento sono attualmente utilizzati dal FVOE (Fascicolo Virtuale dell'OE) e dal FVC (Fascicolo Virtuale del Concorrente)</strong></p>

	<p>3. nella risposta alla issue à1764 il documento 00009 è stato segnalato come di prossima disponibilità, mentre i documenti 00024 e 00040 sono stati segnalati come non richiedibili tramite il servizio richiedi-documenti. C'è differenza ovvero sono tutti e tre in sviluppo?<br>
	<br>
	<strong>00009 é in sviluppo<br>
	00024 e 00040 sono in fase di analisi di fattibilità</strong><br>
	 <br>
	4. il documento 00007 è correttamente segnalato come "in progress" nella tabella citata: sarebbe possibile inserire anche gli altri tipo documento in questo modo, avendo un perfetto allineamento tra tipologica e documento?<br>
	<strong>Allineata la tabella con l'inserimento del solo tipo documento 00009</strong></p>

	<p>5. il documento con tipo documento 00042 - Carichi fiscali pendenti è presente nel documento indicato (<a href="https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md">https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md</a>) con codice 00006 che non è presente nella tipologica. Qual è il codice corretto? Sarebbe opportuno tenere allineate le due strutture.<br>
	<strong>Il codice tipo documento per i "carichi fiscali pendenti" é il 42. Nella tipologica "tipo-documnto" é presnte l'elemento con codice 00042 e con descrizione "carichi fiscali pendenti".E' stato allienato il documento <a href="https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md">https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-enticertificanti.md</a></strong><br>
	 <br>
	6. infine che differenza c'è tra il documento 00038 - DURC inarcassa professionista e il documento 00040 - DURC inarcassa professionisti??<strong> si prenda in considerazione solo lo 00038. il documento 00040 é in fase di analisi di fattibilità</strong><br>
	<br>
	<br>
	Restiamo a disposizione <br>
	<br>
	<br>
	Cordiali Saluti </p>
	</li>
</ul>
