### ISSUE TITLE
[BLK] - esiti WT su AD

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#1792]
Stiamo riscontrando da qualche giorno esiti WT su schede di tipo AD in ambiente di produzione ad esempio su operazioni di conferma-appalto.
Gli appalti restano in lavorazione.
Chiedo agli altri gestori se anche loro stanno riscontrando quest'anomalia.
Stiamo procedendo ad inviare mail al supporto pcp, ma le segnalazioni da parte dei nostri clienti sono molteplici.

**Comment by paolo-urbanetto** [comment]
Buongiorno,
si anche noi [Maggioli] da alcuni giorni abbiamo lo stesso problema e abbiamo anche casi di errore generico ERR999 randomico.
Abbiamo aperto ticket e stiamo attendendo la risoluzione.

**Comment by Gestore-Venicecom** [comment]
ci accodiamo anche noi Venicecom

**Comment by paolo-urbanetto** [comment]
Buongiorno, 
ANAC nel tardo pomeriggio di ieri ci ha risposto ai ticket di produzione indicando che i problemi relativi agli errori generici e di sincronizzazione delle schede in attesa si sono risolti.  Lato nostro [Maggioli] possiamo confermare che da ieri sera la situazione sembra essere effettivamente risolta e tornata a regime.
Anche per voi la situazione è risolta?

**Comment by matteolaltrelli** [comment]
Anche per noi sembra essere tutto ok, chiudo l'issue. Grazie @paolo-urbanetto per il feedback.
