### ISSUE TITLE
[PRODUZIONE] - Errori generale nella gestione degli esiti

### ISSUE THREAD

**Issue by gianlucacuomo** [anticorruzione/npa#1793]
Scusate se uso anche questo canale ma stiamo ricevendo decine di segnalazioni, in produzione, da parte degli utenti circa l'impossibilità di confermare gli esiti delle operazioni di conferma o pubblicazione.

**Comment by obigno77** [comment]
Il problema è stato risolto. Per le segnalazioni in produzione si ricorda che l'unico canale supportato è la casella mail dedicata
