### ISSUE TITLE
[Venicecom] - Impossibile confermare scheda AD5 e AD3

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#1795]
Salve,  

non riusciamo a confermare la scheda AD5 e AD3, in ambiente in produzione e anche in collaudo   
Potete verificare ? 
Saluti

**Comment by obigno77** [comment]
Se la transazione di AP_CONF è rimasta in stato WT il problema in produzione è stato risolto.
Si chiede di indicare eventuali esempi di casi in qualificazione.
