### ISSUE TITLE
ISDA2 - anomalie nel servizio crea-appalto 

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1797]
nel verificare l'invio di una scheda ISDA2 (servizio crea-appalto), sono state notate le seguenti anomalie di cui si chiede chiarimenti:

1. Non è presente alcun campo importo per inserire il valore stimato dello SDA
2. E' presente il campo "lottoSDATypeLotIdentifier" non citato in documentazione di cui non si conosce la semantica e la tipologia
3. i valori del dominio "settore" hanno entrambi "dataInizio":"2024-11-15T00:00:00Z" rendendo impossibile inviare la scheda.

si richiede un rapido riscontro per consentire il prosieguo dei test.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>in riferimento alle anomalie segnalate per l'invio della scheda ISDA2 (servizio crea-appalto), vi informiamo quanto segue:</p>

<ol>
	<li>
<strong>Campo importo per il valore stimato dello SDA:</strong><br>
	È stata introdotta una fix per includere il campo destinato all'inserimento del valore stimato sui lotti, sia sopra che sotto soglia. Attualmente il campo è facoltativo, ma verrà successivamente associata una regola che ne richiederà la valorizzazione con un importo maggiore di 0.</li>
	<li>
<strong>Campo "lottoSDATypeLotIdentifier":</strong><br>
	È stato chiarito che il campo fa riferimento a identificativi interni relativi al lotto SDA. Tale campo non è utilizzato per l'emissione del CIG, dato che gli SDA non rilasciano CIG. La documentazione verrà aggiornata per riflettere questa semantica.</li>
	<li>
<strong>Dominio "settore" con data inizio:</strong><br>
	Il problema è stato risolto aggiornando il dominio con una tipologica senza data inizio, consentendo così l'uso corretto della scheda. Questa modifica è parte del changelog 03 e sarà in esercizio a partire dalla prossima settimana.</li>
</ol>

<p>Restiamo a disposizione per eventuali ulteriori chiarimenti o supporto.</p>

<p>Cordiali saluti</p>
