### ISSUE TITLE
[Bolzano] - Changelog-02: Segnalazione su obbligatorietà degli importi in schede modifiche contrattuali M1 e M2

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1798]
Salve,
Stiamo procedendo con i test sulle schede relative alle modifiche contrattuali aggiornate (M1 e M2), abbiamo visto che gli importi che elenco di seguito sono stati resi obbligatori contemporaneamente, quindi riceviamo errore per l'obbligatorietà:

- Importo contrattuale componente forniture in € (al netto dell’IVA e degli oneri di sicurezza)
- Importo contrattuale componente servizi in € (al netto dell’IVA e degli oneri di sicurezza)
- Importo contrattuale componente lavori in € (al netto dell’IVA e degli oneri di sicurezza)

[M1 output.json](https://github.com/user-attachments/files/17477564/M1.output.json)
[M1 input.json](https://github.com/user-attachments/files/17477565/M1.input.json)

Potete chiarire la ragione per cui tutti e tre gli importi risultano obbligatori ? 
Inoltre, in attesa di una vostra risposta, è corretto considerare come workaround l'inserimento del valore "0,00" per i tipi di appalto non pertinenti?

Grazie.

**Comment by anac-uscp** [comment]
<p>Gentile utente,<br>
<br>
gli importi indicati sono obbligatori come da requisito ANAC. Per ora, l'obbligatorietà sul JSON non impedisce l'inserimento di "0,00" come valore per gli importi non pertinenti.</p>

<p>Si conferma pertanto che è corretto utilizzare il valore "0,00" per i tipi di appalto non rilevanti.</p>

<p>Restiamo a disposizione per eventuali ulteriori chiarimenti.</p>

<p>Cordiali saluti</p>
