### ISSUE TITLE
[CONSIP] Scheda AD3 - REG53 In caso di ditta mandante l'importo non è previsto

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1799]
Buongiorno, in caso di affidamento diretto ad un raggruppamento con più operatori in fase di invio della scheda AD3, si verifica questo errore bloccante:

"REG53 In caso di ditta mandante l'importo non è previsto".

Da vari controlli effettuati, sembra che la causa del problema sia la presenza del campo "importo" obbligatorio anche sulle mandanti (non solo sul mandatario).

Si resta in attesa di un gentile riscontro
Grazie

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Si prega di provare ad inserire il valore 0 nell'importo e riprovare.</p>

<p>E' stato fatto un test in qualificazione e in caso di ditta mandante, indicando 0 come importo la regola non è scattata e l'appalto è stato confermato.</p>

<p>Cordiali saluti.</p>
