### ISSUE TITLE
Scheda P4.1 - oggetto datiBaseTerminiInvio

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#180]
i campi scadenzaPresentazioneInvito e oraScadenzaPresentazioneOfferte si riferiscono entrambi al termine di ricevimento delle domande di partecipazione con la differenza che il primo campo contiene la data e il secondo contiene l'ora?

**Comment by supportoAnac** [comment]
oraScadenzaPresentazioneOfferte è di tipo datetime e contiene data e ora.
