### ISSUE TITLE
REG53 | Differenze descrizione errore fra scheda AD3 e AD4

### ISSUE THREAD

**Issue by iacopus** [anticorruzione/npa#1800]
Buongiorno,
ci siamo resi conto che la REG53 fa riferimento a due tipologie di errori di validazione diversi a seconda che la scheda di indizione prescelta sia la AD3 piuttosto che la AD4.

E' normale che a fronte dello stesso codice di errore ci siano errori di compilazione di diversa natura?

Vi allego le evidenze che abbiamo raccolto.

Grazie e buon lavoro
![ad3_reg53](https://github.com/user-attachments/assets/2e078795-4eb8-4e4c-9551-42cfd2fd612d)
![ad4_reg53](https://github.com/user-attachments/assets/9e98b70a-b43c-4afe-bbed-4648af1d90d6)

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>grazie per la segnalazione, la regola REG53 per AD3.dmn e AD4.dmn sarà corretta uniformando la sintassi tra tutte le schede in cui è presente.</p>

<p><br>
La risoluzione della problematica sará inclusa nel prossimo rilascio.</p>

<p><br>
Restiamo a disposizione.</p>

<p> </p>

<p>Cordiali saluti</p>
