### ISSUE TITLE
Accesso a FVOE per verifiche su fornitori iscritti ad Elenchi

### ISSUE THREAD

**Issue by lucabonazza** [anticorruzione/npa#1801]
La scheda SIM (che sarà rilasciata in futuro) consentirà, senza attribuzione del CIG, di effettuare i controlli dei requisiti tramite accesso al FVOE. Sarà possibile prevedere modalità simili per le verifiche a campione su soggetti iscritti ad Elenchi fornitori?

**Comment by obigno77** [comment]
Per il momento no
