### ISSUE TITLE
(ARIA SPA) Rettifica avviso di aggiudicazione

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1805]
Buongiorno,

per la rettifica dell'avviso di una scheda A1_29, continuiamo a ricevere a distanza di giorni l'errore "Operazione non consentita per lo stato dell'avviso sulla PVL". 
dato i diversi tentativi svolti, tutti con stessoesito, si chiede riscontro se ci siano delle problematiche in merito alla rettifica degli avvisi di aggiudicazione delle schede A1_29?

in particolare, il nostro tentativo riguarda la rettifica dei dati dell'aggiudicatario di un lotto di un appalto multilotto. Preciso che è stata pertanto sottomessa la richiesta di rettifica di un solo lotto di quelli che compongono l'appalto (dato che l'aggiudicazione è possibile farla per singoli lotti anche la rettifica ci aspettiamo possa essere fatta ugualmente).

Grazie,
Luca

**Comment by obigno77** [comment]
Si chiede di inserire almeno i riferimenti dell'appalto interessato dal problema

**Comment by LucaMaggioni1** [comment]
scheda utilizzata per indizione: P1_16
ID appalto: 04f60fd0-dde0-40c3-908a-32968c638338
Codice appalto: P1_16_AggiudicaizonepiùFasi
IDavviso di aggiudicazione per cui si è fatto il tentativo di rettifica: 4a2dc45f-9ad2-4adc-8909-30a21848741f

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Da un controllo sui nostri sistemi è emerso che si stava tentando di effettuare una richiesta di rettifica avviso mentre che questo era in fase di pubblicazione. </p>

<p>In data 25-10 l'avviso è stato pubblicato per cui si può ora procedere alla rettifica.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>

<p> </p>
