### ISSUE TITLE
[Teamsystem] - Nuova tipologica SettoreEnum

### ISSUE THREAD

**Issue by mcgirone** [anticorruzione/npa#1807]
Buongiorno,

leggendo la documentazione relativamente alla nuova tipologica ho notato che il campo sarà presente obbligatoriamente solo per AD3, AD5, A3_6, P1_19, P7* . 
Non trovo la presenza di questo campo in altre schede come P1_16, P2_16.... E' voluto o si tratta di un mancato aggiornamento della documentazione schede?

**Comment by obigno77** [comment]
Le schede P sono già personalizzate in base al settore come da direttiva
