### ISSUE TITLE
[BLK] - Errore nell'ottenimento del voucher PCP-FVC

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#1809]
Buongiorno,

abbiamo collaudato i servizi PCP-FVC e abbiamo attivato la finalità anche nell'ambiente di produzione.
Utilizzando la medesima procedura già consolidata per la creazione del client_assertion_id in produzione quando lo creiamo per l'invocazione dei servizi PCP-FVC otteniamo un errore.
Debuggando con lo strumento 'Debug client assertion' di PDND postando il client_assertion_id l'errore ritornato è il seguente:

_Il claim AUD (audience) non contiene l'audience corretta_

l'audience utilizzato è quello indicato nel servizio ossia:  https://apigw.anticorruzione.it/modi/rest/FVC/v2

![image](https://github.com/user-attachments/assets/2dfe10b2-6632-4431-9af8-15955078a416)

Grazie

**Comment by obigno77** [comment]
Si prega di inserire il govway transaction id della risposta

**Comment by dpagliari** [comment]
l'errore che otteniamo è Forbidden
Di seguito I dati richiesti:

IdAppalto c352dd13-a673-4a09-9bfe-85fd311a6e7d 
{"type":"[https://govway.org/handling-errors/403/Authorization.html","title":"Authorization","status":403,"detail":"Authorization](https://govway.org/handling-errors/403/Authorization.html%22,%22title%22:%22Authorization%22,%22status%22:403,%22detail%22:%22Authorization) failed","govway_id":"43e99c8a-96cd-11ef-a2a9-00505684399c"}

Grazie

**Comment by dpagliari** [comment]
Buongiorno 
sollecito riscontro in quanto provando ancora con altro scenario riceviamo sempre lo stesso errore. Di seguito i dati dei nuovi test eseguiti in produzione con diversi codici fiscali di OE:

{
   "idAlbo":2,
   "codiceFiscaleOE":"xxxxxxxxxxxxxx",
   "uuidAppalto": "c9c90ece-c9e6-4450-b77a-5d26fb2a5159",
   "utente":{
      "codiceFiscaleUtente":"xxxxxxxxxxxxx",
      "ruolo":"RUP",
      "loa":"3",
      "idp":"SPID",
      "codiceFiscaleSa":"xxxxxxxxxxxx",
      "codiceAusa":"xxxxxxxx"
   },
   "piattaforma":{
      "codicePiattaforma":"0000001",
      "codiceComponente":"0000001"
   },
  "traceId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}
 
e il 

{"type":"
[https://govway.org/handling-errors/403/Authorization.html","title":"Authorization","status":403,"detail":"Authorization](https://govway.org/handling-errors/403/Authorization.html%22,%22title%22:%22Authorization%22,%22status%22:403,%22detail%22:%22Authorization)
failed","govway_id":"9b4582f7-9c2d-11ef-852e-005056844885"}

Grazie

**Comment by dpagliari** [comment]
Potete darci cortesemente riscontro?

**Comment by dpagliari** [comment]
Buongiorno si sollecita riscontro
Grazie

**Comment by obigno77** [comment]
In ambiente di qualificazione non esiste questo identificativo transazione.
Puoi mandare una mail a uscp@anticorruzione.it e fissiamo una breve call
