### ISSUE TITLE
Anomalie servizi ComunicaAppalto

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#181]
a seguite delle chiamate al servizio crea-appalto sono state riscontrate le seguenti anomalie.

1) gestione errata degli errori:
-se l'eform è diverso da quello previsto per la scheda il sistema restituisce ERR2 (scheda non ammessa in questa fase dell'appalto);
-se l'eform (obbligatorio) non è presente il sistema restituisce ERR2 (scheda non ammessa in questa fase dell'appalto);
-in assenza dell'eform, laddove facoltativo (es. P4.1), il sistema restituisce ERR2;

2) controllo campi:
-in assenza di alcuni campi obbligatori la scheda il servizio ha restituito 200 (es. P1.10 -> categorieMerceologiche e lotto.contrattiDispoiszioniParticolari)
--all'interno delle tipologiche, i campi idTipologica e codice accettano qualsiasi valore.

3) incrongurenza con lo swagger:
-per le schede AD4 e AD5 il servizio restituisce No anacForm or stazioniAppaltanti in input. Se si aggiunge l'oggetto StazioniAppaltanti (non previsto nello swagger restituisce 200)

**Comment by supportoAnac** [comment]
La gestione degli errori è stata migliorata con l'ultimo rilascio del 22/09/2023.
