### ISSUE TITLE
(ARIA SPA) schede con Strumento procedura "Sistema dinamico di acquisizione"

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1810]
Buongiorno,

in diverse schede (es. P2_16) è presente  come "StrumentiSvolgimentoProcedura" il campo "Sistema Dinamico di acquisizione".

Data l'introduzione delle nuove schede ISDA come devono essere interpretati questi campi?

**Comment by anac-uscp** [comment]
<p>La scheda ISDA è specifica per la creazione di un Sistema Dinamico di Acquisizione, a cui attingere per i contratti operativi discendenti dallo SDA. <br>
Il campo  StrumentiSvolgimentoProcedura specifica invece quali strumenti sono stati eventualmente utilizzati per lo svolgimento delle procedure.<br>
Si segnala, come da specifica sulle schede interessate, che l’uso di tale campo è stato recentemente deprecato.  <br>
 </p>
