### ISSUE TITLE
Scheda CO1 e liquidazione importo di affidamento in unica soluzione

### ISSUE THREAD

**Issue by Michele-83** [anticorruzione/npa#1811]
Gentilissimi,
si richiedono delucidazioni riguardo la scheda di chiusura CO1 successiva a una AD3. 
In caso di pagamento unico dell’importo di affidamento è possibile compilare direttamente la CO1 popolando il campo "Importo" oppure bisogna trasmettere prima una SA1 con l’importo totale pagato?

Grazie

**Comment by obigno77** [comment]
Nel caso della AD3 andata a buon fine vanno inviate tutte le schede di esecuzione previste
