### ISSUE TITLE
Switch da SDK 1.9 al 1.12

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#1812]
Buongiorno,
come anticipato entro il 28 Febbraio 25 è previsto il passaggio dal SDK1.9 al SDK1.12
A tal proposito è stato riportato che non esisterà un periodo di coesistenza di entrambi i tracciati.

Chiedo gentilmente se la soluzione pensata e che verrà rilasciata consentirà la gestione della seguente fattispecie:

- Invio dei bandi di rettifica/modifica e aggiudicazione con SDK1.12 a fronte di bandi di pubblicazione con SDK1.9

Grazie

**Comment by obigno77** [comment]
Si questa funzionalità sarà supportata

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>si conferma che sarà possibile l'invio dei bandi di rettifica/modifica e aggiudicazione con SDK1.12 a fronte di bandi di pubblicazione con SDK1.9</p>

<p>Cordiali saluti.</p>
