### ISSUE TITLE
[TOSCANA/BOLZANO] - REG68_1 per AD1_25

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1814]
Ciao,
ci colleghiamo alla issue: https://github.com/anticorruzione/npa/issues/1774, poichè anche noi stiamo riscontrando lo stesso **errore bloccante.**

**Comment by laurapavan** [comment]
Ci uniamo alla segnalazione, in quanto abbiamo rilevato lo stesso errore.

**Comment by obigno77** [comment]
Risolto
