### ISSUE TITLE
modello-dati-tipologiche : file YAML non aggiornato

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#1817]
Buongiorno, come mai il file modello-dati-tipologiche non risulta aggiornato anche se ci sono tipologiche aggiornate ed alcune tipologiche sono state inserite (ad es, motivoDerogaQlf)?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>in merito alla vostra segnalazione, vi informiamo che il file <strong>modello-dati-tipologiche</strong> elenca esclusivamente le tipologiche utilizzate nelle <strong>request</strong> o <strong>response</strong> dei servizi PCP.</p>

<p>Le tipologiche relative all'oggetto <strong>anacForm</strong> delle schede, come ad esempio <strong>motivoDerogaQlf</strong>, sono invece presenti nel file dedicato disponibile al seguente link: <a href="https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml">https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/schede/modello-dati-schede-dati-comuni.yaml</a></p>

<p>Rimaniamo a disposizione per ulteriori chiarimenti o necessità.</p>

<p>Cordiali saluti</p>
