### ISSUE TITLE
Oggetti AggiudicazioneBaseSopraSogliaType e AggiudicazioneCompletaSopraSogliaType

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#1818]
Buongiorno, si chiede di valutare l'opportunità di inserire nel changelog solo gli aspetti rilevanti sulla struttura delle schede. In questo changelog03 di fatto la modifica è che l'oggetto offertePresentate è diventato facoltativo laddove presente, se questo viene attenuto aggiungendo due oggetti al modello dati Schede dati comuni è secondario e fa perdere di vista quali siano le modifcihe da apportare a quale scheda che è il vero oggetto dell'analisi degli implementatori.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>la nota di rilascio viene compilata con il dettaglio delle modifiche effettuate. Nei prossimi rilasci, comunque, cercheremo di aggiungere una breve descrizione dell'intervento, in modo da rendere le modifiche più chiare e immediatamente comprensibili.</p>

<p>Grazie per il riscontro e rimaniamo a disposizione per eventuali chiarimenti.<br>
<br>
Cordiali saluti</p>
