### ISSUE TITLE
parametri del servizio ESITO-OPERAZIONE

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#182]
dopo aver invocato il servizio RETTIFICA-AVVISO si vuole verificare l'esito dell'operazione. 
il parametro tipoOperazione prevede 3 possibilità in questo caso:
- AV_RETT
- AV_RETT_ITA
- AV_RETT_EU

qual è la differenza e come determiniamo il tipo di operazione da usare?

**Comment by supportoAnac** [comment]
AV_RETT è il tipo operazione da utilizzare per conoscere l'esito del processo di rettifica. 
AV_RETT_IT, AV_RETT_EU indicano l'esito di dettaglio dei singoli sotto-processi governati da PCP.
