### ISSUE TITLE
[eForms] chiarimenti - negoziata senza bando: flusso informativo eForms

### ISSUE THREAD

**Issue by GGr8l** [anticorruzione/npa#1820]
Buongiorno,

sono emersi dei quesiti in merito al flusso informativo (eForms e schede) per procedure negoziate senza bando.

Elenco la necessità:
1. inviare avviso volontario per la trasparenza ex-ante (direttive: settori ordinari 2014/24/EU, settori speciali2014/25/EU, concessioni 2014/23/EU)
2. rettificare tale avviso
3. procedere con avviso di aggiudicazione
4. inviare l'avviso di modifica creato a seguito dell'avviso di aggiudicazione

Qual è il flusso corretto da seguire nel file orchestratore?

è giusto iniziare il flusso con la scheda P7_2 (flusso 72)? e poi come si prosegue? Ho trovato molti flussi diversi nel file orchestratore, ma ma non collegati tra loro e perciò chiedo vostro supporto.

Grazie

Questo quesito è un'integrazione al quesito #1808

**Comment by anac-uscp** [comment]
<p>Il flusso delle procedure negoziate con invito inizia con la P7_2.  <br>
Di seguito, è previsto l’invio di una S2, e, come scheda di aggiudicazione, in via transitoria è ammesso l’invio di una A2_29. <br>
Per la pubblicazione sul TED, allo stato attuale è previsto l’invio dell’eForm 25,26,27 o 28, a secondo del settore di appartenenza della procedura. </p>
