### ISSUE TITLE
[CONSIP] Scheda P2_20 - ERR48 - Operazione non consentita per la tipologia di avviso nazionale- "Cancella Avviso non disponibile"

### ISSUE THREAD

**Issue by Antoluimaridand** [anticorruzione/npa#1825]
Buongiorno,
per la creazione di una gara è stata selezionata una P2_20 che prevede la pubblicazione nazionale tuttavia; 
dopo la chiamata del servizio di "cancella avviso" appare il seguente errore :

"ERR48 - Operazione non consentita per la tipologia di avviso nazionale" 

Di seguito i dettagli recuperati dai log per la scheda P2_20 con i seguenti dati:

GovWay-Transaction-ID=[f5a5afba-9a8c-11ef-988f-0050568e08b3]
GovWay-Message-ID=[5c78e9af-7b87-4013-8c2e-c50e78456f9f]
"idAvviso":"21a9c81e-0b29-4d04-9de5-627404d2a34f"
"idAppalto":"da026ed9-09c2-4125-a9d6-1603ab9edea3"

Grazie in anticipo

Saluti

**Comment by obigno77** [comment]
Non è ammessa la cancellazione degli avvisi nazionali perchè non esiste soluzione di continuità tra la presa in carico dell'avviso e l'avvio della pubblicazione come nel Ted

**Comment by lauralu1993** [comment]
salve,
vorrei far presente che è presente un'inconguenza sulla documentazione:
![image](https://github.com/user-attachments/assets/592111d8-3bed-42d2-88c8-e727f54e4213)
oltetutto, nella issue https://github.com/anticorruzione/npa/issues/1659 non era stato esplicitato che il servizio fosse richiamabile solo per le schede con pubblicazione europea
