### ISSUE TITLE
[CONSIP] SCHEDA AD3- "Pubblicazione Completata" ma non visibile su " https://testpubblicitalegale.anticorruzione.it"

### ISSUE THREAD

**Issue by Antoluimaridand** [anticorruzione/npa#1826]
Buongiorno, 
è stata compilata, trasmessa e pubbicata una gara avente scheda AD3. 
Invocando il servizio esito-operazione ( AV_PUBB ) l'appalto risulta in stato PUBB, 
tuttavia la suddetta non appare su " https://testpubblicitalegale.anticorruzione.it"
Di seguito i dati della negoziazione: 

NR_Gara: 93349
Id Appalto: b56edaa7-387b-4d13-8cb9-931a1748b18e
Id Avviso: 9d22d29f-7636-48f2-be06-725bdc2715dd
CIG:  I00A458655

Grazie 

Saluti

**Comment by obigno77** [comment]
L'avviso risulta pubblicato
https://testpubblicitalegale.anticorruzione.it/esiti/996ebca1-4672-4623-8f8a-fde3984cd598?ricercaArchivio=false
