### ISSUE TITLE
accesso ambienti di test

### ISSUE THREAD

**Issue by GiovanniSom** [anticorruzione/npa#183]
Buongiorno,
in  qualità di produttore privato di piattaforma di e-procurement a supporto delle PA, già censito come RPNT e in futuro da certificare come titolare secondo il N.C.A. D.LGS. 36/2023, avremmo necessità di qualche chiarimento su come accedere ad un ambiente di test dei servizi dei nuovi NPA, FVOE e FVA. Ad oggi non siamo riusciti ad identificare un ambiente di test accessibile ad aziende private dalla documentazione disponibile, potreste dare indicazioni su come accedere e dove?
grazie e buona giornata

**Comment by mladuDPA** [comment]
Salve,
ha ricevuto qualche informazione relativa al problema?
Sono in una situazione analoga.
Grazie e buona giornata

**Comment by GiovanniSom** [comment]
> 

non ho ricevuto aggiornamenti o risposte in merito a questa situazione

**Comment by supportoAnac** [comment]
Il servizio è disponibile a tutti i soggetti che possono accedere tramite PDND, abilitati secondo la normativa AgID.
