### ISSUE TITLE
Dialogo competitivo e procedura competitiva con negoziazione

### ISSUE THREAD

**Issue by lucabonazza** [anticorruzione/npa#1830]
Quali sono le schede PCP ANAC previste per il Il dialogo competitivo (art. 74 D.lgs. 36 del 2023) e per la procedura competitiva con negoziazione (art. 73 D.lgs. 36 del 2023)? Da orchestratore ANAC non sembra sia previsto espresso riferimento a schede specifiche. In tal senso possono essere utilizzate le schede previste per le procedure ristrette (P1_16, S1, S2, A1_29, etc), valorizzando adeguatamente il campo Tipo Procedura BT-105, con il corretto valore tra i previsti in tipologica "tipoProcedura"?

**Comment by anac-uscp** [comment]
<p>Buongiorno,</p>

<p>Confermiamo l'interpretazione proposta.</p>

<p> </p>
