### ISSUE TITLE
[BLK][URGENTE] Yaml coerente per changelog 02

### ISSUE THREAD

**Issue by ctav8** [anticorruzione/npa#1831]
Buongiorno,
mi ricollego alla issue [#1829](https://github.com/anticorruzione/npa/issues/1829) chiedendo se è corretto interpretare per il changelog 02 come commit di aggiornamento della documentazione finale il commit 6c999781f54a352da7b6d47c36b0ab532477a03a del 13/09/2024 (visto che nel changelog è indicata come data di pubblicazione finale dei contenuti il 12/09/2024 e non ci sono commit il 12/09/2024)?

In più, si richiede urgentemente un riscontro in quanto gli yaml dei modelli contengono tutti i riferimenti sempre a `https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/`, quindi all'ultima versione, rendendo impossibile utilizzare lo yaml del commit indicato per generare le classi in modo automatico coerentemente con il changelog 02.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>può consultare la documentazione al seguente link: <a href="https://github.com/anticorruzione/npa/blob/main/CHANGELOG.md" rel="noopener" target="_new">https://github.com/anticorruzione/npa/blob/main/CHANGELOG.md</a>. Scorrendo fino alla sezione "Note di rilascio del 06/08/2024 (Changelog-02)", troverà tutte le modifiche apportate per il changelog 2.</p>

<p>Di seguito, le fornisco il commit contenente tutte le modifiche apportate al modello dati per il changelog 2: <strong>4b2929ef7fbba6751b4244afe0e4a5576659c45f</strong>.</p>

<p>Rimaniamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti,</p>
