### ISSUE TITLE
Gare in delega - elenco deleganti

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#1833]
Buongiorno,
ad oggi da swagger è possibile indicare più di una SA delegante a livello di gara.
Essendo però il CIG a livello di lotto, è in programma un adeguamento che consenta di indicare a livello di lotto sia la funzione delegata che la/le SA deleganti.

**Comment by obigno77** [comment]
Non sono previste nè saranno supportate le deleghe a livello di lotto
