### ISSUE TITLE
[CONSIP] - Scheda AD1_25 - AD1_26 - AD1_27 - AD1_28 - REG68_1 Persiste anche con eForm compilato correttamente

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1835]
Salve,
come indicato nella nota di chiusura della issue **#1774**, al fine di risolvere la regola in oggetto (REG68_1) si è proceduto a compilare il BT-136 e il BT-105. Tuttavia, la REG68_1 persiste. Vi chiediamo, gentilmente, un aiuto sulla compilazione dell'eForm al fine di superare le regola. Grazie

Di seguito i dettagli del test eseguito:
<img width="652" alt="image" src="https://github.com/user-attachments/assets/3f446c7f-b140-4cdf-9cdf-1b8bbb1930e9">
<img width="658" alt="image" src="https://github.com/user-attachments/assets/e7e02d97-a9bc-463f-8d51-6eabd2bff35f">

[Scheda AD1_25.txt](https://github.com/user-attachments/files/17676036/Scheda.AD1_25.txt)

GovWay-Message-ID
[8ca4a058-d2c7-43ff-bf1e-7e1251c60d11]

GovWay-Transaction-ID
[38bdf989-9daa-11ef-a9cd-0050568e08b3]
{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "b022b92b-e0dd-46ad-9353-b58a5fff8b64",
      "idScheda": "3307ae9c-455e-47d4-b7d7-7873a7f2b7c1",
      "codiceScheda": "AD1_25",
      "esito": {
        "idTipologica": "esito",
        "codice": "KO"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AP_CONF"
      },
      "dataControllo": "2024-11-08T09:55:31.828+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AP_N_CONF"
      },
      "errori": [
        {
          "idTipologica": "errori",
          "dettaglio": "",
          "codice": "REG68_1"
        }
      ]
    }
  ]
}

Grazie
Cordiali saluti

**Comment by anac-uscp** [comment]
<p>Gentile utente</p>

<p>La segnalazione è corretta.</p>

<p>La fix verrà inclusa nel prossimo rilascio.</p>

<p> </p>

<p>Restiamo a disposizione.</p>

<p> </p>

<p>Cordiali Saluti</p>
