### ISSUE TITLE
FVOE richiedi documento - impossibile richiedere i documenti senza modello dati

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#1837]
Ecco la comunicazione rielaborata e organizzata con la tabella corretta per essere pubblicata su Git:

---

**Salve,**

non riusciamo a far funzionare i documenti con modello dati "-".

Di seguito riportiamo l'elenco dei documenti che non siamo riusciti a richiedere, indicando il payload e il GovWay ID relativo a ogni chiamata. Chiediamo gentilmente un riscontro su cosa non stia funzionando.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/MBENJA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/MBENJA~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/MBENJA~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-GB style='tab-interval:36.0pt;word-wrap:break-word'>

Document Code | Document Name | URL | Request | Response | GovWay Message Id
-- | -- | -- | -- | -- | --
"00033" | Estratto   del casellario informatico ANAC | https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti | {"chiaveAccesso":   "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento":   {"codice": "00033"} | {"detail":"JSON parse error:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name; nested exception is   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}'   (code 125)): was expecting double-quote to start field name\n at [Source:   (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1,   column: 96]","status":500,"title":"Operazione   terminata con errore","errori":[{"id":"errori","codice":"ERR9999"}]} | 2288c708-4541-4608-964e-15092c7806fd
"00021" | Comunicazione regolarità   fiscale | https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti | {"chiaveAccesso":   "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento":   {"codice": "00021"} | {"detail":"JSON parse error:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name; nested exception is   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}'   (code 125)): was expecting double-quote to start field name\n at [Source:   (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1,   column: 96]","status":500,"title":"Operazione   terminata con errore","errori":[{"id":"errori","codice":"ERR9999"}]} | a094f8aa-d591-4c60-aac8-d0d306e45440
"00034" | Visura   al registo delle imprese | https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti | {"chiaveAccesso":   "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento":   {"codice": "00034"} | {"detail":"JSON parse error:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name; nested exception is   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}'   (code 125)): was expecting double-quote to start field name\n at [Source:   (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1,   column: 96]","status":500,"title":"Operazione   terminata con errore","errori":[{"id":"errori","codice":"ERR9999"}]} | 85896b49-2dfc-4e4c-ace6-5bba1a23a269
"00038" | DURC inarcassa   professionista | https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti | {"chiaveAccesso":   "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento":   {"codice": "00038"} | {"detail":"JSON parse error:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name; nested exception is   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}'   (code 125)): was expecting double-quote to start field name\n at [Source:   (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1,   column: 96]","status":500,"title":"Operazione   terminata con errore","errori":[{"id":"errori","codice":"ERR9999"}]} | b07e4a98-dcb7-429a-b004-23bd15042dab
"00039" | DURC inarcassa impresa | https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti | {"chiaveAccesso":   "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento":   {"codice": "00039"} | {"detail":"JSON parse error:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name; nested exception is   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}'   (code 125)): was expecting double-quote to start field name\n at [Source:   (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1,   column: 96]","status":500,"title":"Operazione   terminata con   errore","errori":[{"id":"errori","codice":"ERR9999"}]} | 6052fd9e-b6f5-4988-ae8a-ed13c643ea51
"00042" | Carichi Fiscali Pendenti | https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti | {"chiaveAccesso":   "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento":   {"codice": "00042"} | {"detail":"JSON parse error:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name; nested exception is   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}'   (code 125)): was expecting double-quote to start field name\n at [Source:   (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1,   column: 96]","status":500,"title":"Operazione   terminata con errore","errori":[{"id":"errori","codice":"ERR9999"}]} | 45788242-4c73-4e45-a8ee-7fcfda7470b7
"00007" | Iscrizione WhiteList   antimafia | https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti | {"chiaveAccesso":   "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento":   {"codice": "00007"} | {"detail":"JSON parse error:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name; nested exception is   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}'   (code 125)): was expecting double-quote to start field name\n at [Source:   (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1,   column: 96]","status":500,"title":"Operazione   terminata con   errore","errori":[{"id":"errori","codice":"ERR9999"}]} | 8df4f0ce-6d7a-4eff-8165-c0616b570c8a
"00008" | DURC   emesso in corso di validità | https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti | {"chiaveAccesso":   "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento":   {"codice": "00008"} | {"detail":"JSON parse error:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name; nested exception is   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}'   (code 125)): was expecting double-quote to start field name\n at [Source:   (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1,   column: 96]","status":500,"title":"Operazione   terminata con errore","errori":[{"id":"errori","codice":"ERR9999"}]} | c1699f7f-7a4f-449e-8edb-be917e8a60e6
"00010" | Verifica   esistenza prospetto informativo disabili | https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti | {"chiaveAccesso":   "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento":   {"codice": "00010"} | {"detail":"JSON parse error:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name; nested exception is   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}'   (code 125)): was expecting double-quote to start field name\n at [Source:   (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1,   column: 96]","status":500,"title":"Operazione   terminata con errore","errori":[{"id":"errori","codice":"ERR9999"}]} | cb5eb7e2-2d1d-43e1-b9fa-c5aaa289d842
"00011" | Verifica   esistenza rapporto parità di genere | https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti | {"chiaveAccesso":   "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento":   {"codice": "00011"} | {"detail":"JSON parse error:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name; nested exception is   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}'   (code 125)): was expecting double-quote to start field name\n at [Source:   (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1,   column: 96]","status":500,"title":"Operazione   terminata con errore","errori":[{"id":"errori","codice":"ERR9999"}]} | e9fcfaa4-5d08-4823-9a7e-3dd825cc88a9
"00009" | Sanzioni Ispettorato del   lavoro | https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documenti | {"chiaveAccesso":   "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento":   {"codice": "00009"} | {"detail":"JSON parse error:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name; nested exception is   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}'   (code 125)): was expecting double-quote to start field name\n at [Source:   (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1,   column: 96]","status":500,"title":"Operazione   terminata con errore","errori":[{"id":"errori","codice":"ERR9999"}]} | 7f31f917-45f5-4775-8af6-4bad89e4a36a

</body>

</html>

**Comment by anac-uscp** [comment]
<p>Gentile Utente,</p>

<p><br>
<br>
Negli esempi riportati, manca una parentesi di chiusura <code>}</code> nel JSON passato nella request:<br>
<br>
<strong>{"chiaveAccesso": "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento": {"codice": "00033"}}</strong><br>
<br>
Durante i test eseguiti in locale, si è verificato che l’errore segnalato (<code>'}</code> (code 125)) può verificarsi anche quando viene inserita una virgola <code>,</code> dopo l'ultimo valore:<br>
<br>
<strong>{"chiaveAccesso": "202F7B3E-AA37-4C2B-8109-196B584806D7","tipoDocumento": {"codice": "00033"},}</strong><br>
<br>
Questa virgola finale è considerata non valida in JSON, causando l'errore.<br>
<br>
<br>
Restiamo a disposizione,</p>

<p><br>
<br>
Cordiali Saluti <br>
<br>
 </p>
