### ISSUE TITLE
orario di aggiornamento in esercizio changelog02

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#1838]
Qualora lo aveste già comunicato e mi fosse sfuggito, mi scuso anticipatamente; se così non fosse, a che ora verrà effettuato l'aggiornamento in esercizio previsto per il 14/11/2024? Grazie

**Comment by obigno77** [comment]
L'orario di aggiornamento è sempre da considerare alle 13.30 ove non specificato diversamente
