### ISSUE TITLE
Richiesta utilizzo ambiente di Attestazione per certificazione e dichiarazione di conformità

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#1839]
Buongiorno,
come segnalato nel corso del tavolo tecnico del 23/10/24 richiediamo di poter utilizzare l'ambiente di Attestazione in luogo a quello di Qualificazione per le attività inerenti la certificazione di nuove componenti, ma soprattutto per i test di integrazione relativi alle dichiarazioni di conformità di nuove piattaforme.

La ragione è ovviamente legata al fatto che l'ambiente di Qualificazione è un ambiente di sviluppo, più aggiornato di quello di Esercizio con normali problemi di stabilità e dove non come Titolari non possiamo istantaneamente avere versioni di componenti allineate già pronte per i test.
Anche allineandosi, si testerebbero componenti e piattaforme su versioni in sviluppo non ancora rilasciate in esercizio.
Non è corretto.

Attendiamo cortese riscontro sulla volontà a procedere in tal senso e relativi tempi.
Grazie

**Comment by obigno77** [comment]
Risolto
