### ISSUE TITLE
Servizio Modifica-Avviso -  Rettifica del eDGUE

### ISSUE THREAD

**Issue by lmanc77** [anticorruzione/npa#184]
Essendo il CIG campo obbligatorio da inserire nel eDGUE, ed essendo l'eDGUE propedeutico alla pubblicazione dell'appalto, presumendo la necessità di rettificare l'eDGUE Request a valle della conferma dell'appalto stesso (per inserire il CIG staccato con la conferma della gara), si richiede se con il servizio “MODIFICA AVVISO” sia possibile aggiornare il DGUE allo scopo di avere coerenza con tutte le informazioni pubblicate (per la creazione del eDGUE viene inizialmente inserito un CIG fittizio, essendo il dato non disponibile fino ad una fase successiva ed essendo il CIG dato obbligatorio).

Grazie

**Comment by mpizziconi** [comment]
AgID ha modificato la disciplina del DGUE eliminando il riferimento al CIG
