### ISSUE TITLE
Tipologia motivoEsclusioneOrdinarioSpeciale

### ISSUE THREAD

**Issue by Silvio1970** [anticorruzione/npa#1840]
nella elezione della tipologica motivoEsclusioneOrdinarioSpeciale  Acquisto o locazione di beni immobili come da delibera DELIBERA N. 584 del 19 dicembre 2023 cosa si potrebbe selezionare o perchè manca nella tipologica

**Comment by obigno77** [comment]
L'acquisto o locazione di beni immobili è una fattispecie contrattuale che ricade nell'ambito esclusivo della tracciabilità. Per queste esiste la scheda P5 che prevede la voce 16 della tipologica fattispecieTracciabilita
