### ISSUE TITLE
Passaggio al SDK 1.12 per Eform

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#1842]
Entro quale data le piattaforme dovranno aggiornare l'SDK alla versione 1.12 per non bloccare la trasmissione delle schede che prevedono eForm?

**Comment by obigno77** [comment]
Il rilascio in esercizio è previsto entro la metà di febbraio perchè il 28/02/2025 finisce il supporto. 
A partire dal rilascio in esercizio non saranno più accettati eForm sdk 1.9.
