### ISSUE TITLE
Flusso 72

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#1848]
Buonasera,
in cotrasto con quanto citato nella issue https://github.com/anticorruzione/npa/issues/1414 rileviamo che è stato aggiornato come segue l'orchestratore

![image](https://github.com/user-attachments/assets/8a9ed407-f282-43f7-a5fd-88d0ac63e035)

![image](https://github.com/user-attachments/assets/583d51f6-4b4c-4461-95f5-615adddc8ce2)

A questo punto le P72 a partire dal rilascio in esercizio del changelo2 disporanno solo del A2_29 come scheda di aggiudicazione?
In caso affermativo si tratta di una soluzione definitiva o temporanea?

Grazie

**Comment by pietropalermoIT** [comment]
Evidenzio che ANAC aveva dato risposta alla issue #801 prevedendo quale scheda di aggiudicazione della P7_2 la scheda A2_29 come attualmente evidenziato dall'orchestratore.

**Comment by obigno77** [comment]
L'orchestratore è stato ripristinato come da risposta a issue #801 in attesa di soluzioni più efficaci
