### ISSUE TITLE
SchedaSQ1 (Superamento del  quarto del tempo  contrattuale)

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#185]
Buongiorno,
nel file Excel "schema-cronologia-schede.xlsx" è presente la scheda SQ1 "Superamento del  quarto del tempo  contrattuale" in oggetto, ma non mi risulta essere presente in /modello-dati/schede/

Si tratta di una nuova scheda ancora non definita?

**Comment by supportoAnac** [comment]
È una nuova scheda che verrà inserita nel prossimo rilascio, previsto per settembre.
