### ISSUE TITLE
(ARIA SpA) FVOE  - ERRORE Servizio Ricerca Documento

### ISSUE THREAD

**Issue by paolomariobardi** [anticorruzione/npa#1850]
Buongiorno,
interrogando il servizio "ricerca-documenti-fvoe", utilizzando i filtri TIPO e STATO e formattando la richiesta come da specifiche, otteniamo sempre la seguente risposta:

{
    "error": "Bad Request",
    "message": "Errore nella chiamata rest http://172.16.4.75:8994/api/public/ricerca-documenti-fvoe",
    "status": "400",
    "errorsValidation": [
        "Filtro Stato non formattato correttamente"
    ],
    "warningValidation": []
}

Potete verificare se si tratta di un malfunzionamento oppure una errata formattazione della richiesta.

Grazie

**Comment by anac-uscp** [comment]
<p>Gentile Utente,<br>
<br>
<br>
I campi <strong>"stato"</strong> e <strong>"tipo"</strong> sono di tipo stringa e devono contenere un JSON conforme al formato specificato.</p>

<p>Per entrambi i campi, il JSON deve rispettare la seguente struttura:<br>
<code>{"codice": "Valore preso dalla tipologia di riferimento"}</code></p>

<p>Il dominio dei valori da utilizzare per il campo <strong>"stato"</strong> deve essere ricavato dalla tipologia <strong>"statoDocumento"</strong>, mentre per il campo <strong>"tipo"</strong> deve essere ricavato dalla tipologia <strong>"tipoDocumento"</strong>.<br>
<br>
Di seguito si riporta un esempio di valorizzazione delle chiavi eseguita in swagger:<br>
<br>
stato del documento:<br>
<strong>{"codice":"1"}</strong><br>
<br>
tipo del documento:<br>
<strong>{"codice":"00900"} </strong><br>
<br>
<br>
Restiamo a disposizione.<br>
<br>
<br>
Distinti Saluti </p>
