### ISSUE TITLE
(ARIA SpA) - FVOE - Filtro "Dati Aggiuntivi"

### ISSUE THREAD

**Issue by paolomariobardi** [anticorruzione/npa#1851]
Buongiorno,
nella richiesta del servizio "Ricerca Documenti"  vorremmo avere informazioni su quali sono  e come devono essere formattati i dati per il filtro "Dati Aggiuntivi".

Allego quanto riportato da specifica:

![image](https://github.com/user-attachments/assets/63985884-f365-4d69-9068-a0519a3cf073)

**Comment by anac-uscp** [comment]
<p>Gentile Utente,<br>
<br>
<br>
il campo "Dati Aggiuntivi" viene utiizzato come ulteriore filtro di ricerca lato SA.</p>

<p>Questo campo è stato progettato per memorizzare informazioni proprietarie dell'utente che ha inserito il documento.<br>
<br>
Deve essere fornito in formato JSON e inserito attraverso il servizio <strong>inserisci-documento</strong>.</p>

<p>In fase di ricerca, il campo deve essere valorizzato con l'esatto valore precedentemente inserito.</p>

<p>Tuttavia, attualmente il servizio di inserimento del documento con i dati aggiuntivi non è esposto. Di conseguenza, non è possibile effettuare la ricerca dei documenti utilizzando il filtro "Dati Aggiuntivi".</p>

<p><br>
<br>
<br>
Restiamo a disposizione,<br>
<br>
<br>
Cordiali Saluti </p>
