### ISSUE TITLE
Base di calcolo contributo ANAC

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#1853]
Buongiorno, si chiede come venga calcolato l'importo utilizzato come base di calcolo del contributo ANAC a partire dai dati contenuti nel quadro economico standard e ci siano differenze tra gli affidamenti diretti (schede AD*) e le altre schede (vedi anche issue #1846 ).

**Comment by obigno77** [comment]
I dati del quadro economico non sono utilizzati ai fini del calcolo del contributo ANAC che agisce unicamente sull'importo complessivo
