### ISSUE TITLE
[CONSIP - FVOE] Documenti richiedibili senza busta

### ISSUE THREAD

**Issue by Randazzo75** [anticorruzione/npa#1857]
Buongiorno,
volendo estendere la lista dei documenti richiedibili attraverso integrazione, abbiamo necessità di una conferma rispetto alle tipologie di documenti richiedibili "senza busta".
Facendo riferimento alla tipologica tipoDocumento.json i documenti ed i relativi documenti richiedibili senza Issue sono:

codice: "00008", "Durc in corso di Validita"
codice: "00010", "Verifica esistenza prospetto informativo disabili"
codice: "00011, "Verifica esistenza rapporto parità di genere"
codice: "00021", "Certificato regolarità fiscale violazioni definitive"
codice: "00024", "DURC"
codice: "00033", "Estratto del casellario informatico ANAC"
codice: "00034", "Visura al registo delle imprese"
codice: "00038", "DURC inarcassa professionista
codice: "00039", "DURC inarcassa impresa"
codice: "00040", "DURC inarcassa professionisti"
codice: "00042", "Carichi fiscali pendenti"

Confermate, inoltre, che per questi documenti è possibile procedere alla richiesta limitandosi all'invio della chiaveAccesso e tipoDocumento?
Grazie 
Buona giornata

**Comment by obigno77** [comment]
Si conferma
