### ISSUE TITLE
ISDA2- Problema scheda S0 conseguente.

### ISSUE THREAD

**Issue by AFSOLUZIONI** [anticorruzione/npa#1858]
è stato correttamente pubblicato uno SDA sotto soglia comunitaria eseguendo rispettivamente:

1. creaAppalto per la scheda ISDA2
2. confermaAppalto per la scheda ISDA2
3. esitoOperazione per confermaAppalto per la scheda ISDA2
4. pubblicaAvviso per la scheda ISDA2
5. esitoOperazione per il pubblicaAvviso per la scheda ISDA2
6. consultaAvviso per l'idAvviso relativo alla scheda ISDA2
7. creaScheda per la scheda S0

quest'ultima operazione ha dato esito negativo con la seguente motivazione:

GovWay-Message-ID: 7c3ec3ee-a018-4068-9aeb-722239e7d83a,
GovWay-Transaction-ID: a157bfda-9b86-11ef-988f-0050568e08b3#=#
{
    "detail": "Errore",
    "errori": [
        {
            "codice": "ERR2", - scheda non ammessa in questa fase dell'appalto -
            "idTipologica": "errori"
        }
    ],
    "status": 400,
    "title": "KO",
    "type": "about:blank"
}
Mi sembra che la sequenza di operazioni sia corretta. Mi sfugge qualcosa??

Grazie.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>La invitiamo a creare una nuova issue fornendo un idAppalto o un CIG per poter esaminare la problematica.</p>

<p> </p>

<p>Restiamo a disposizione.</p>

<p> </p>

<p>Cordiali Saluti</p>

<p> </p>
