### ISSUE TITLE
Gestione pianificazione - Scheda PL1_2 [BLK]

### ISSUE THREAD

**Issue by Silvio1970** [anticorruzione/npa#1859]
errore ERR43 errore durante la validazione dei dati della scheda: tabella DMN non trovata
di cosa stiamo parlando ?
come ovviare all'errore ?

{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idScheda":"ecfe3432-3d3b-43cb-a153-ec1757112486","codiceScheda":"PL1_2","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"PI_CONF"},"dataControllo":"2024-11-19T11:16:41.986+01:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"PI_N_CONF"},"errori":[{"idTipologica":"errori","dettaglio":"","codice":"ERR43"}]}]}

**Comment by Silvio1970** [comment]
risolto il problema del ERR43 adesso è comparso il fantomatico ERR9999 come da risposta
{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idScheda":"0bdef5bc-f015-426e-90fa-3af715cc17b5","codiceScheda":"PL1_2","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"PI_CONF"},"dataControllo":"2024-11-25T18:18:24.745+01:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"PI_N_CONF"},"errori":[{"idTipologica":"errori","codice":"ERR9999"}]}]}
che a meno di non avere una palla di vetro sarà difficile intercettare

**Comment by anac-uscp** [comment]
<p>Gentile utente</p>

<p>L'errore che si presenta risulta essere l'errore 46 - La Notice Dispatch Date deve essere compresa tra le 0 e le 24 ore rispetto alla data di pubblicazione.</p>

<p>La invitiamo pertanto a modificare la IssueDate all'interno dell'eForm.</p>

<p> </p>

<p>Restiamo a disposizione.</p>

<p> </p>

<p>Cordiali Saluti</p>
