### ISSUE TITLE
Schede P6.3, P6.4, P6.5 e P66

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#186]
Buongiorno,
in /modello-dati/schede sono presenti le seguenti schede:
- Scheda P6.3 - Scheda di Contratto di disponibilità
- Scheda P6.4 - Scheda di Contratto EPC
- Scheda P6.5 - Scheda di Concessione di servizi e costruzione e gestione
- Scheda P6.6 - Scheda di Contratti di parternariato sociale

Delle suddette schede non trovo traccia nel file Excel "schema-cronologia-schede.xlsx" e nemmeno nel "modello-dati-npa.yaml".

Sembrano analoghe alle rispettive P4* (quest'ultime però comprendono la pubblicazione TED).

Vanno considerate in ambito nazionale (senza pubblicazione TED)?

**Comment by FRASCA57** [comment]
credo ci sia stata, nella modifica dell'08 Agosto 2023, una inversione tra 4 e 6.
io ho avuto lo stesso problema sulla P4.1 e P4.2 che sono diventate P6.1 e P6.2.
vedi issue #191

**Comment by supportoAnac** [comment]
Le schede inizialmente pubblicate come P6.3, P6.4, P6.5, P6.6 sono state sostituite dalle schede P4.3,P4.4,P4.5,P4.6, come correttamente riportato nel file Excel. 
Le schede P6.3, P6.4, P6.5, P6.6 verranno eliminate nel prossimo rilascio, previsto per settembre.
