### ISSUE TITLE
[Consip][A1*] ERRORE 99999

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1860]
salve, 
da venerdi non riusciamo piu a trasmettere correttamente le schede A1*. 
al crea-scheda otteniamo ERR 9999.
potete verificare?
le modifiche del changelog3 sono state recepite. 

GovWay-Message-ID:"5c089af0-aaf0-415e-bf93-936e61e8810c"
 GovWay-Transaction-ID:"9b966c55-a5cd-11ef-b5b7-0050568e9679"

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>per poter procedere con le opportune analisi, avremmo bisogno dell'ID Appalto, del Codice Appalto o del CIG.</p>

<p> </p>

<p>Rimaniamo a disposizione per ogni ulteriore chiarimento.</p>

<p>Cordiali saluti,</p>
