### ISSUE TITLE
(ARIA SPA) Campi  "importo del finanziamento"

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#1864]
Buongiorno, 

in riferimento al campo  "importo del finanziamento" reso obbligatorio con il changelog2 ad es nella scheda P1_16. 
- l'importo deve essere considerato al netto IVA?
- ci sono dei vincoli/controlli fra l'importo del finanziamento e l'importo a base di gara gestito nel quadro economico?

**Comment by anac-uscp** [comment]
<p>Buongiorno,<br>
<br>
In relazione alle domande poste:<br>
<br>
1) l'importo del finanziamento deve coprire tutti le uscite economiche relative al contratto d'appalto e non solo l'importo a base di gara. Pertanto, lo stesso è comprensivo anche degli importi relativi alle "somme a disposizione" del quadro economico, fra cui sono ricomprese l'IVA ed altre eventuali imposte e tasse.<br>
<br>
2) Allo stato non sono presenti controlli fra l'importo del finanziamento e l'importo deducibile dal quadro economico.<br>
<br>
<br>
 </p>
