### ISSUE TITLE
[CONSIP] ERR41-errore generico durante la validazione dei dati della scheda. P7_2 , P5, P1_16, P2_16

### ISSUE THREAD

**Issue by Antoluimaridand** [anticorruzione/npa#1865]
Salve, 
Al fine di verificare la "REG120 : Non è possibile inserire il codice 3 nel campo derogaQualificazione se l'oggetto principale del contratto è diverso da lavori o l'importo è superiore a 1 milione di euro."

Compilo una P2_20 e cerco si trasmetterla. Dopo la chiamata esito-operazione, riceviamo il seguente errore:

ERR41- errore generico durante la validazione dei dati della scheda.

-  GovWay-Message-ID":["2c976936-a0a6-443b-a9cc-757d6da6632d"]
-  GovWay-Transaction-ID":["ac79a56d-a720-11ef-b5b7-0050568e9679"]

Di seguito i govWay per la chiamata di esito-operazione che ha restituito come ultimo esito ERR41:

- GovWay-Message-ID":["5154c48e-671a-4d84-801b-75c4aa277c78"]
- GovWay-Transaction-ID":["b4972171-a720-11ef-b5b7-0050568e9679"]

Riscontriamo il seguente errore su una P5. (la quale non ha il campo derogaQualificazione in anacform)
Riscontriamo il seguente errore su una P1_16 e P2_16 e P1_20; P1_12; AD1_28; P1_17

**Comment by anac-uscp** [comment]
<p>Gentile Utente,</p>

<p>La informiamo che è stata rilasciata la fix per la risoluzione della problematica riscontrata.</p>

<p>La invitiamo a effettuare un nuovo tentativo</p>

<p>. Restiamo a disposizione per eventuali necessità.</p>

<p>Cordiali saluti</p>
