### ISSUE TITLE
[CONSIP] REG120; REG121; REG122. REGOLE NON INTERCETTATE 

### ISSUE THREAD

**Issue by Antoluimaridand** [anticorruzione/npa#1866]
Salve,
Voglio far scattare le REG 120 e 121 ma il sistema non mostra gli errori:

 * REG120: Non è possibile inserire il codice 3 nel campo derogaQualificazione se l'oggetto principale del contratto è diverso da lavori o l'importo è superiore a 1 milione di euro.
 
 * REG121: Non è possibile inserire il codice 4 nel campo derogaQualificazione se l'oggetto principale del contratto è diverso da servizi o l'importo è superiore a 750000 €.
 
Le regole indicate non scattano per via di un'incongruenza sui file DMN.
In particolare alle regole REG120, REG121, REG122 indicate all'interno del tag text, sotto riportato: 

Versione:
<text>"{\"idTipologica\":\"errori\",\"codice\":\"REG120\"}</text>
<text>"{\"idTipologica\":\"errori\",\"codice\":\"REG121\"}</text>
<text>"{\"idTipologica\":\"errori\",\"codice\":\"REG122\"}</text>

Notiamo questa problematica anche per queste schede:

P1_10.dmn;  P1_11.dmn; P1_12.dmn;  P1_13.dmn; P1_14.dmn; P1_16.dmn; P1_17.dmn; P1_19.dmn; P1_20.dmn; P1_21.dmn; P2_10.dmn; P2_11.dmn; P2_12.dmn; P2_13.dmn; P2_14.dmn; P2_16.dmn; P2_17.dmn; P2_19.dmn; P2_20.dmn; P2_21.dmn; P3_4.dmn; P3_5.dmn; P4_1.dmn; P4_2.dmn; P4_3.dmn; P4_4.dmn; P4_5.dmn; P4_6.dmn; P6_1.dmn; P6_2.dmn; P7_2.dmn; P7_1_1.dmn; P7_1_2.dmn; P7_1_3.dmn;

Grazie 
Saluti

**Comment by anac-uscp** [comment]
<p><strong>Gentile Utente,</strong></p>

<p>La informiamo che è stata rilasciata la fix per la risoluzione della problematica riscontrata.</p>

<p>La invitiamo a effettuare un nuovo tentativo. Restiamo a disposizione per eventuali necessità.</p>

<p>Cordiali saluti</p>
