### ISSUE TITLE
[CONSIP] P7_2;  P7_1_1; P7_1_2; P7_1_3. REG118 E REG119 - DMN ERRATI

### ISSUE THREAD

**Issue by Antoluimaridand** [anticorruzione/npa#1869]
Salve
le regole non vengono recepite perchè all'interno della struttura del file DMN per la scheda P7_2 c'è un incongruenza.

La stessa era stata segnalata con una issue #1765,  relativo al Changelog2 per le schede P7_1_1, P7_1_2 e  P7_1_3 e notiamo essere ancora presente anche per queste schede.

Nel tag output non viene definto l'attributo "name" che funge da chiave per la restituzione della mappa di errori prodotta dal rule engine. Al posto dell'attributo "name" è stato inserito l'attributo "label". Non essendoci l'attributo name l'errore viene riconosciuto ma non restituito, poichè non mappato. (anche in questo caso notiamo anche un refuso sulla definizione dell'id che porta AD1_10 e non il corretto codice scheda)

Potreste verificare?

Grazie in anticipo
Saluti

**Comment by anac-uscp** [comment]
<p>Gentile utente</p>

<p>Le regole delle schede P7_1_1, P7_1_2, P7_1_3, P7_2 sono state tutte corrette aggiungendo l'attributo name e risultano tutte aggiornate.</p>

<p>In qualificazione è stato fatto un test di una P7_1_1 con dati errati e correttamente è scattata la REG118.</p>

<p> </p>

<p>Restiamo a disposizione.</p>

<p> </p>

<p>Cordiali Saluti</p>
