### ISSUE TITLE
[TOSCANA/BOLZANO] BLK ERR4 - errore nella conversione della scheda 

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#1871]
Salve,
con il **changelog-03**, rilasciato in Qualificazione: 15/11/2024, all'interno del "modello-dati-schede-dati-comuni.yaml:" è stato indicato:
**deprecato il campo strumentiSvolgimentoProcedura**.

Tuttavia all'invio di una scheda P7_1_2 riscontriamo il seguente errore:

**ERR4 - Errore nella conversione della scheda secondo il json scheda definito:
$.anacForm.appalto.strumentiSvolgimentoProcedure:is missing but it is required.**

Di seguito il json di riferimento:
[P712.json](https://github.com/user-attachments/files/17844847/P712.json)

Ci potete indicare se si tratta di un errore oppure tale campo è deprecato solo per alcune schede?

**Comment by anac-uscp** [comment]
<p>fix inviata con ticket #63382.</p>
