### ISSUE TITLE
[CONSIP] P7_1_1; P7_1_2; P7_1_3. "ERR4 - $.anacForm.appalto.strumentiSvolgimentoProcedure: is missing but it is required"

### ISSUE THREAD

**Issue by Antoluimaridand** [anticorruzione/npa#1872]
Salve, 
Durante la trasmissione di negoziazioni aventi le seguenti schede: P7_1_1 , P7_1_2, P7_1_3, riceviamo il seguente errore:
"ERR4 - $.anacForm.appalto.strumentiSvolgimentoProcedure: is missing but it is required"
Tuttavia il campo "STRUMENTI SVOLGIMENTO PROCEDURE" da Swagger è FACOLTATIVO.

Potreste controllare? 

Grazie in anticipo 
Saluti

**Comment by anac-uscp** [comment]
<p><strong>Gentile Utente,</strong></p>

<p>La informiamo che è stata rilasciata la fix per la risoluzione della problematica riscontrata.</p>

<p>La invitiamo a effettuare un nuovo tentativo. Restiamo a disposizione per eventuali necessità.</p>

<p>Cordiali saluti</p>
