### ISSUE TITLE
[CONSIP] AD2_28 - REG118, REG119, REG120, REG121, REG122 non intercettate

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1878]
salve,
sulla scheda AD2_28 le regole REG118, REG119, REG120, REG121, REG122 non scattano e CIG vengono restituiti correttamente.
potete verificare?

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>la problematica segnalata è stata analizzata e risolta. La fix è stata testata in ambiente di sviluppo e verrà rilasciata in <strong>ambiente di qualificazione</strong> oggi pomeriggio.</p>

<p>Restiamo a disposizione per ulteriori chiarimenti o verifiche dopo il rilascio.</p>

<p>Cordiali saluti</p>
