### ISSUE TITLE
[CONSIP] GESTIONE PIANIFICAZIONE PCP- ERR43- Errore durante la validazione dei dati della scheda: tabella DMN non trovata

### ISSUE THREAD

**Issue by Antoluimaridand** [anticorruzione/npa#1882]
Buon pomeriggio, 
in riferimento alla issue che è stata chiusa:
https://github.com/anticorruzione/npa/issues/1856
Vi informo che il problema persiste ancora nonostante sia stato dichiarato che il problema è stato transitorio durante il rilascio dell'aggiornamento del changelog-02 di giovedi scorso. 

Grazie in anticipo

**Comment by obigno77** [comment]
Il ticket viene chiuso a seguito di conferma errore superato via mail di Volpentesta
