### ISSUE TITLE
Scheda PL1_7 | Problematiche bloccanti in fase di creazione pianificazione

### ISSUE THREAD

**Issue by iacopus** [anticorruzione/npa#1883]
Buongiorno,
in riferimento all'issue #1882 sembra che l’errore sia stato superato (ERR43) ma adesso riscontriamo purtroppo un altro errore relativo ad una regola:
“REG99 L'importo indicato nell'oggetto lotti.datiBase.importo deve essere > 0. In presenza di eForm verificare l'importo inserito nel campo EstimatedOverallContractAmount (BT-27).”
 
Ma purtroppo nella PL1.7 non esiste l’oggetto lotti.datiBase.importo mentre il BT-27 è stato compilato e sottomesso correttamente nella farte dell’eform, quindi presumo che sia da eliminare\correggere la regola nel DMN.

ID pianificazione ambiente di test : 97c754c2-e6ba-411b-a319-26537aaa428f
![pl1_7](https://github.com/user-attachments/assets/15bf2e89-3bc3-4d75-8aad-3596b0cd28fd)

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>La fix è stata rilasciata in esercizio il 27 Novembre.</p>

<p>Cordiali saluti.</p>
