### ISSUE TITLE
[CONSIP] Note di rilascio del 13/11/2024 - chiarimenti su RSU1

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#1887]
nelle Note di rilascio del 13/11/2024 viene riportato "corretto il riferimento alla scheda RSU1 per la scheda IR1" ma non abbiamo individuato modifiche all'interno dell'orchestratore.
è possibile avere un chiarimento?
Grazie

**Comment by anac-uscp** [comment]
<p><strong>Gentile utente,</strong></p>

<p>La informiamo che quanto riportato nel changelog si riferisce alla correzione relativa alla scheda <em>IR1</em>. Nell'elenco delle possibili schede successive (colonna R), era erroneamente indicata la scheda <em>SU1</em>, che non esiste.</p>

<p>Pertanto, la scheda successiva (<em>SU1</em>) è stata corretta in <em>RSU1</em>. La modifica era già stata apportata nel software, ma mancava l'aggiornamento del file Excel su GitHub. Ora il file è stato aggiornato correttamente.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p><strong>Cordiali saluti</strong></p>
