### ISSUE TITLE
esito pubblica-avviso

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#189]
quali sono i casi in cui una pubblicazione (pubblica-avviso) non va a buon fine? 
si tratta solo di errori di sistema e/o interruzioni del servizio? 
dobbiamo prevedere situazioni in cui potrebbe essere necessario tentare la pubblicazione più di una volta?

**Comment by supportoAnac** [comment]
Non è necessario tentare la pubblicazione più di una volta. Una volta che PCP ha garantito una risposta, eventuali problemi di servizio sono gestiti da sistema fino a pubblicazione avvenuta.
