### ISSUE TITLE
[Consip][A1*] ERRORE 99999

### ISSUE THREAD

**Issue by Antoluimaridand** [anticorruzione/npa#1891]
Buon pomeriggio, 
riscontriamo ancora l'ERR99999 sulle A1.
Nello specifico abbiamo provato a trasmettere una A1_36. Di seguito i dati della negoziazione:

ID APPALTO: 55700926-02a6-44f9-a31e-5234f8c60062

GovWay-Message-ID=[0ad4a3af-cd65-4e6c-b435-6f2130e1afe2], x-frame-options=[DENY],
GovWay-Transaction-ID=[9ecb5c14-acaa-11ef-a9cd-0050568e08b3], vary=[Access-Control-Request-Headers, Access-Control-Request-Method, Origin], x-content-type-options=[nosniff], strict-transport-security=[max-age=31536000 ; includeSubDomains, max-age=63072000], } -

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>E' necessario ricevere evidenza del payload completo della richiesta, senza cui non è possibile procedere ad analisi e test approfonditi.</p>

<p>Restiamo in attesa di aggiornamenti.</p>

<p>Cordiali saluti.</p>
