### ISSUE TITLE
[Consip][AD1_28] ERR41  

### ISSUE THREAD

**Issue by Antoluimaridand** [anticorruzione/npa#1893]
Buongiorno, 
vi segnalo che, la trasmissione della AD1_28 fallisce con il seguente errore: 

ERR41 - errore generico durante la validazione dei dati della scheda

Di seguito l'ID APPALTO della negoziazione: 
23b8c711-d80f-442b-8790-de1cf7efd284

"GovWay-Message-ID":["219101e7-1ca0-4162-a6f3-c3f734417df7"],"x-frame-options":["DENY"],
"GovWay-Transaction-ID":["a2cce8eb-ad63-11ef-a9cd-0050568e08b3"],"vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]

Saluti

**Comment by anac-uscp** [comment]
<p>Risolta con rilascio del 13/12</p>
