### ISSUE TITLE
[Bolzano] - Segnalazione obbligatorietà: dataSottoscrizione per M2 e M2_40 (Changelog 03)

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#1898]
Buongiorno,

Stiamo procedendo con i test relativi alle modifiche apportare con il changelog 03 e vi segnalo che nelle schede M2 e M2_40 il campo "Data sottoscrizione" è stato reso facoltativo con il changelog 03 tuttavia, provando ad inviare la scheda ci viene restituito il seguente errore:
- ERR4 - errore nella conversione della scheda secondo il json schema definito: $.anacForm.modificaContrattuale.datiBaseModificaContrattuale.dataSottoscrizione: is missing but it is required
 
Quindi viene ancora applicata l'obbligatorietà.

Riuscite a darci supporto?
Grazie.

**Comment by anac-uscp** [comment]
<p><strong>Gentile Utente,</strong></p>

<p>La informiamo che è stata rilasciata la fix per la risoluzione della problematica riscontrata.</p>

<p>La invitiamo a effettuare un nuovo tentativo. Restiamo a disposizione per eventuali necessità.</p>

<p>Cordiali saluti</p>
