### ISSUE TITLE
Servizi Anac Esistenti - TED

### ISSUE THREAD

**Issue by ferdinandjmaddela** [anticorruzione/npa#19]
Con la dismissione dei servizi TED dovuti all'introduzione degli eForms, come verranno mappati i servizi e gli oggetti? 
In che modo cambieranno il flusso di invio a TED?
Le modifiche ed aggiornamenti sull sdk degli eForms, quanto impatteranno sul nuovo flusso?

**Comment by supportoAnac** [comment]
A partire da ottobre 2023 ANAC svolge il ruolo di eSender nazionale, pertanto le piattaforme dovranno usare i servizi ANAC descritti nel presente documento per effetttuare la pubblicazione delle sForm su TED (vedi servizio pubblica-avviso).  ANAC svolge la verifica sintattico/semantica delle eForm ricevute utilizzando l'ultima versione disponibile del SDK rilasciato dal TED alla data di avvio in esercizio del sistema e pubblicata nella sezione "Termini di servizio". L'upgrade delle versiona del SDK utilizzato è pubblicato con 90 giorni di anticipo.
