### ISSUE TITLE
Elenco delle tipologiche

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#190]
Nell'effettuare un confronto tra le tipologiche presente nella cartella relativa ed il risultato del servizio elenco-tipologiche è risultato che:

1. nell'elenco prodotto dal servizio sono presenti 3 tipologiche non presenti nella directory della documentazione:
            "idTipologica": "statoRichiesta"
            "idTipologica": "tipoContenuto"
            "idTipologica": "tipoScheda"
2. mentre nella directory di documentazione sono presenti 3 tipologiche che non sono presenti nella risposta del servizio elenco-tipologiche:
             codIstat.json
             codNUTS.json
             erroriEform.json

è possibile uniformare il contenuto della documentazione a quello prodotto come response dei servizi resi  disponibili?
Grazie.

**Comment by supportoAnac** [comment]
1) L'adeguamento sarà presente nel prossimo rilascio, previsto per settembre.
2) Nel prossimo rilascio le tipologiche codIstat.json e codNUTS.json saranno popolate mentre il file erroriEform.json sarà rimosso in quanto è necessario fare riferimento alla gestione degli errori del TED
