### ISSUE TITLE
[Consip][M1] ERR9999 durante rettifica-avviso

### ISSUE THREAD

**Issue by Antoluimaridand** [anticorruzione/npa#1902]
Ciao, 
abbiamo provato ad effettuare la rettifica sulla scheda M1, tuttavia invocando il servizio Rettifica-Avviso, otteniamo ERR9999.
Potete verificare? 

ID APPALTO: b3c3065f-acb6-4552-ac90-38a069670b44
Rettifica-avviso - Request
RequestBody = {"idAvviso":"b05e464a-07ab-47d8-8c24-50ff8b62f3d9","idAppalto":"b3c3065f-acb6-4552-ac90-38a069670b44","scheda":{"type":"SchedaPostPubblicazioneType","codice":{"idTipologica":"codiceScheda","codice":"M1"},"versione":"1.0","body":{"type":"SchedaM1Type","anacForm":{"idContratto":"12362e6b-9a52-4200-82a9-1db6b1855d6f","modificaContrattuale":{"quadroEconomicoStandardRideterminato":{"impLavori":1.0,"impServizi":1.0,"impForniture":1.0}}},
 
Rettifica-avviso - Response
StatusCode =  - 400 - ResponseFoundFromException =  - {"status":400,"title":"KO","detail":"AV_N_PUBB","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]} - ResponseHeaders - {Server=[nginx], Date=[Mon, 02 Dec 2024 09:31:57 GMT]

GovWay-Message-ID=[1a591bf8-1c05-4241-8003-0461f052ac08]
GovWay-Transaction-ID=[8e22e246-b08e-11ef-a9cd-0050568e08b3]

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>E' necessario ricevere evidenza del payload completo della richiesta, senza cui non è possibile procedere ad analisi e test approfonditi.</p>

<p>Restiamo in attesa di aggiornamenti.</p>

<p>Cordiali saluti.</p>

<ul>
</ul>
