### ISSUE TITLE
[Consip] - scheda M1 -  REG54, REG55, REG56, REG61, REG62, REG63   

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1905]
Buongiorno,
le seguenti regole REG54, REG55, REG56, REG61, REG62, REG63 non possono essere intercettate per la scheda M1 in quanto all'interno del modello dati non sono presenti i campi motiviModifica, causaModifica.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>in caso di eForm, i campi <code>motiviModifica</code> e <code>causaModifica</code> corrispondono rispettivamente ai seguenti campi del modello dati:</p>

<ul>
	<li>
<code>motiviModifica</code>: <strong>bt-200 - Modification Reason Code</strong>
</li>
	<li>
<code>causaModifica</code>: <strong>bt-201 - Modification Reason Description</strong>
</li>
</ul>

<p>Restiamo a disposizione per eventuali ulteriori chiarimenti.</p>

<p>Cordiali saluti</p>
