### ISSUE TITLE
[Consip] - scheda M1_40 - REG54, REG55, REG56, REG61, REG62

### ISSUE THREAD

**Issue by cosmin1ursache** [anticorruzione/npa#1907]
Buongiorno,
le seguenti regole REG54, REG55, REG56, REG61, REG62 non possono essere intercettate per la scheda M1.40 in quanto all'interno del modello dati non sono presenti i campi motiviModifica, causaModifica

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>- REG54 - I campi datiBaseModificaContrattuale.motiviModifica e datiBaseModificaContrattuale.causaModifica in caso di eform, fanno riferimento ai campi <br>
BT-200 - Modification Reason Code e BT-201 - Modification Reason Description <br>
- REG55 - La voce "other" è stata eliminata dalla tipologica con il passaggio alla versione sdk1.9 del TED. Da verificare con il gruppo dati ANAC se la voce "proroga tecnica" inizialmente mappata nel codice "other" può corrispondere ad un'altra voce tra quelle ancora presenti nella tipologica, in modo da aggiornare la regola. Oppure se la regola deve essere eliminata <br>
- REG56 - La voce "other" è stata eliminata dalla tipologica con il passaggio alla versione sdk1.9 del TED. Da verificare con il gruppo dati ANAC se la voce "proroga tecnica" inizialmente mappata nel codice "other" può corrispondere ad un'altra voce tra quelle ancora presenti nella tipologica, in modo da aggiornare la regola. Oppure se la regola deve essere eliminata<br>
- REG61 - I campi datiBaseModificaContrattuale.motiviModifica e datiBaseModificaContrattuale.causaModifica in caso di eform, fanno riferimento ai campi <br>
BT-200 - Modification Reason Code e BT-201 - Modification Reason Description<br>
- REG62 - I campi datiBaseModificaContrattuale.motiviModifica e datiBaseModificaContrattuale.causaModifica in caso di eform, fanno riferimento ai campi <br>
BT-200 - Modification Reason Code e BT-201 - Modification Reason Description</p>

<p>Cordiali saluti.</p>
