### ISSUE TITLE
Modifica documentazione scheda NAGx

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#191]
in una importante modifica alla documentazione, avvenuta in data 08 Agosto 2023 (si auspica che tali modifiche non si verifichino più e, in alternativa, vengono opportunamente notificate ai team di sviluppo, visto anche l'approssimarsi della scadenza del 01.01.2024, tramite e-mail e "release notes" cosa che del resto nel SIMOG veniva fatto costantemente), tra le altre cose (inversione dei codici di scheda, soppressioni di schede, modifica della codifica delle stesse, etc. etc.), sono state eliminate le schede NAG1 e NAG2 relative alla non aggiudicazione di un appalto rispettivamente sopra e sotto soglia ed è stata inserita una sola scheda NAG riferita al solo sotto soglia.
Si richiede come possa essere gestista la segnalazione al TED dell’appalto “non aggiudicato” che prevede, ad esempio nell’eForm CAN29, la compilazione dei campi il BT-142 “Winner chosen” e, in caso di non aggiudicazione, il campo BT-144 “Not Awarded Reason”.
Grazie

**Comment by supportoAnac** [comment]
NAG1 è stata eliminata in quanto incompatibile con la gestione delle eForm sopra soglia.
NAG2 è stata rinominata in NAG e gestisce il sotto soglia.
