### ISSUE TITLE
Aggiudicazioni di gare multilotto effettuate da CUC

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#1911]
In relazione a quanto indicato nella chiusura del ticket [Gare in delega - elenco deleganti · Issue #1833 · anticorruzione/npa · GitHub](https://github.com/anticorruzione/npa/issues/1833), vi chiediamo indicazioni operative da fornire alle stazioni appaltanti deleganti in fase di esecuzione.

Ci ritroviamo diverse richieste da parte di Stazioni appaltanti che devono procedere con la "presa in carico" per la gestione della fase esecutiva a seguito di aggiudicazioni di gare multilotto effettuate da CUC.

Visto che la "presa in carico" è a livello d'appalto, come può la singola Stazione Appaltante prendere in carico la fase di esecuzione per il solo lotto di propria competenza e procedere con la gestione delle schede dalla sottoscrizione al collaudo?

**Comment by obigno77** [comment]
E' stata precisata la risposta alla issue #1833
