### ISSUE TITLE
Scheda A1_29 Procedura sopra soglia con Lotto deserto

### ISSUE THREAD

**Issue by AMProma** [anticorruzione/npa#1913]
Spett.le ANAC

Si richiede supporto sulla seguente problematica:

Tipologia di gara: Procedura APERTA
- Fase Gara/Scheda: Affidamento scheda A1_29
- Errore riscontrato: AnacForm - proprietà "OffertePresentate" non trovata.
La procedura indetta con scheda P1_16 risulta avere 2 lotti:
Lotto 1 aggiudicato
Lotto 2 deserto

Da orchestratore risulta prevista la trasmissione della scheda S2 e A1_29.
Abbiamo prioritarimente inviato la scheda S2 dalla quale è stato possibile evidenziare che per il Lotto 2 non abbiamo ricevuto offerte, purtroppo però nell'invio della scheda A1_29  abbiamo riscontrato proprietà "OffertePresentate" non trovata.
Questo errore non ci permette di completare la trasmissione della scheda, bloccando la procedura con evidenti ripercussioni sulla fase di esecuzione.

Si attende riscontro urgente.

**Comment by AMProma** [comment]
Si chiede inoltre di conoscere i tempi di risoluzione della problematica di cui al ticket #1913

**Comment by obigno77** [comment]
La fix è compresa nel changelog-03
