### ISSUE TITLE
Scheda A1_32 Aggiudicazione Concessioni sopra soglia

### ISSUE THREAD

**Issue by AMProma** [anticorruzione/npa#1914]
Spettabile ANAC,
si chiede supporto nella pubblicazione della scheda A1_32 relativa alla comunicazione di aggiudicazione di una Concessione sopra soglia regime ordinario.

Dopo diversi tentativi è risultato impossibile procedere con l'invio della scheda per errori bloccanti rilevati da ANAC.
La problematica riveste carattere di urgenza poichè senza l'invio di tale scheda siamo impossibilitati a procedere con la scheda di esesecuzione.

Si resta in attesa di un vostro riscontro.

**Comment by obigno77** [comment]
Si chiede di inserire maggiori dettagli sull'errore e il contenuto della chiamata

**Comment by gianlucacuomo** [comment]
Abbiamo riscontrato anche noi l'errore però era legato al fatto che ora da orchestratore quella scheda può essere inviata anche senza una preventiva S2. Sembra che sia questo a scatenare l'errore

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Chiediamo cortesemente di fornire delle informazioni più precise per risalire all'appalto in modo tale da poter effettuare analisi approfondite.</p>

<p>Cordiali saluti.</p>
