### ISSUE TITLE
[CONSIP] Scheda PL1_7 | Problematiche bloccanti in fase di creazione pianificazione

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1915]
Buongiorno,
in riferimento all'issue https://github.com/anticorruzione/npa/issues/1883, in ambiente di qualificazione riscontriamo ancora errore relativo alla regola:
“REG99 L'importo indicato nell'oggetto lotti.datiBase.importo deve essere > 0. In presenza di eForm verificare l'importo inserito nel campo EstimatedOverallContractAmount (BT-27).”

Nella PL1.7 non esiste l’oggetto lotti.datiBase.importo mentre il BT-27 è stato compilato e sottomesso correttamente nella parte dell’eform, quindi presumo che sia da eliminare\correggere la regola nel DMN.

ID pianificazione ambiente di test : de4ad3b6-9072-4bdc-9d1f-9e823890a74b

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>in riferimento all’issue segnalato (<a href="https://github.com/anticorruzione/npa/issues/1883" rel="noopener" target="_new">https://github.com/anticorruzione/npa/issues/1883</a>), desideriamo informarvi che è stata rilasciata una fix per il problema indicato. Potete procedere con una nuova verifica in ambiente di qualificazione.</p>

<p>Rimaniamo a disposizione per ulteriori chiarimenti o aggiornamenti in merito.</p>

<p>Cordiali saluti</p>
