### ISSUE TITLE
[DPA] Chiarimenti valorizzazione Campo Importo Partecipanti  Schede AD* ed A* 

### ISSUE THREAD

**Issue by dellattiDPA** [anticorruzione/npa#1918]
Buongiorno,

si richiedono chiarimenti in merito al campo IMPORTO presente nella sezione Partecipanti ed in particolare se per i partecipanti 

(no aggiudicatari) occorra valorizzare il campo importo con solo  l'importo offerto del fornitore o se debbano essere sommati

anche oneri della sicurezza  e/o eventuali opzioni, rinnovi etc. etc

Si richiede inoltre conferma che per l'aggiudicatario debba essere valorizzato il campo importo con l'importo di aggiudicazione 

con solo gli  oneri o se debbano essere sommate anche eventuali opzioni e rinnovi.

**Comment by anac-uscp** [comment]
<p>E’ necessario valorizzare il campo IMPORTO presente nella sezione Partecipanti (per tutti i partecipanti anche se non aggiudicatari) con l'importo offerto dal fornitore comprensivo dell’importo degli oneri della sicurezza (impTotaleSicurezza ) e di eventuali altre somme non soggette a ribasso (ulterioriSommeNoRibasso). </p>

<p>In caso di appalto integrato l’importo offerto deve essere, altresì, comprensivo dell’ importo della progettazione (impProgettazione). In conclusione, l'importo nella sezione 'partecipante' corrisponde alle voci del quadro economico al netto di opzioni, rinnovi e ripetizioni eventualmente ribassate come da offerta dell’Operatore Economico. </p>
