### ISSUE TITLE
[CONSIP] - ERR9999- errore generico- Rettifica Avviso A7_1_1

### ISSUE THREAD

**Issue by Antoluimaridand** [anticorruzione/npa#1919]
Salve, 
abbiamo provato ad effettuare la rettifica sulla scheda A7_1_1, tuttavia invocando il servizio Rettifica-Avviso, otteniamo il seguente errore:

ERR9999- errore generico

ID APPALTO: 45037e59-d7c9-4bef-91f0-fab9eede402b
ID AVVISO: 0ea86690-3459-41ba-b6b5-1e58391bafe5

GovWay-Message-ID=[0023c3a7-1bbc-4b0a-a938-215b4863ba5b]
GovWay-Transaction-ID=[b38ffdda-b3b7-11ef-a9cd-0050568e08b3]

Lo stesso errore si è presentato sul servizio Rettifica-Avviso di una M1, già segnalato in un'altra issue (1902).

Grazie in anticipo.

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Per la casistica riportata in oggetto, sono stati effettuati dei test con esito positivo. La invitiamo pertanto a riprovare.<br>
<br>
Restiamo a disposizione.<br>
<br>
Cordiali saluti</p>
