### ISSUE TITLE
Consultazione FVOE - Conferma possibilità di utilizzare interfaccia utente messa a disposizione da ANAC

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#192]
Nella documentazione del contesto di FVOE è riportato la seguente frase: L’FVOE prevede sia l’esposizione di servizi API per l’integrazione con le piattaforme esterne, sia funzionalità con interfaccia Web per consentire l’accesso e le operazioni sul Fascicolo agli Operatori Economici.
Si chiede conferma che si possa utilizzare l’interfaccia utente messa a disposizione da ANAC per la consultazione del FVOE anche dopo il 1/1/2024

**Comment by supportoAnac** [comment]
ANAC consentirà la fruizione delle funzionalità del FVOE tramite una interfaccia web che sarà a disposizione degli operatori economici. Una analoga interfaccia web per le Stazioni Appaltanti, sebbene sia in corso di realizzazione, non deve considerarsi sostitutiva delle funzionalità che dovranno essere disponibili tramite le piattaforme digitali delle stazioni appaltanti ai sensi della vigente normativa.
