### ISSUE TITLE
[BLK] - [PRODUZIONE] - ERR9999 

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#1924]
Stiamo ricevendo in ambiente di produzione, su diverse schede ad es. AD5 e AD3,
l'errore: ERR9999 con descrizione: errore generico
Abbiamo già inviato diverse segnalazioni al canale di supporto pcp.
Gli altri gestori stanno riscontrando questa problematica?
Grazie in anticipo

**Comment by dellattiDPA** [comment]
Confermiamo la stessa problematica. Abbiamo inviato anche noi diverse segnalazioni e siamo in attesa di risposta.

**Comment by paolo-urbanetto** [comment]
Confermiamo anche noi [Maggioli]

**Comment by matteolaltrelli** [comment]
Presumo che il problema sia questo:
https://www.anticorruzione.it/en/-/avviso.10.12.24
Chiudo la segnalazione su questo canale, ringrazio sempre i colleghi delle altre piattaforme che hanno confermato la problematica.
