### ISSUE TITLE
[ARIA SPA] Gestione passaggio ad SDK 1.12 - TED

### ISSUE THREAD

**Issue by AnrivaDeloitte** [anticorruzione/npa#1925]
Buongiorno,

a seguito di verifica al link https://docs.ted.europa.eu/eforms-common/active-versions/index.html, si evidenzia il print in allegato, dal quale si evince che la versione SDK 1.9 dovrebbe essere supportata dal TED fino al **30 aprile 2025** (differentemente da quanto riportato in precedenza).

Pertanto, si chiede se tale posticipo verrà preso in considerazione lato ANAC o se sarà comunque necessario gestire gli EFORMS con SDK 1.12 già a partire da febbraio 2025.

Grazie.

![image](https://github.com/user-attachments/assets/a4eaf916-ece3-4bba-a386-95c40249c90c)
<img width="540" alt="Capture" src="https://github.com/user-attachments/assets/f2909907-99ef-410e-b54e-0dec751bf9da">

**Comment by GGr8l** [comment]
Buongiorno,

ci uniamo alla richiesta per capire quando verrà effettuato il passaggio.

Grazie.

Saluti,

**Comment by paolo-urbanetto** [comment]
Buongiorno,
sottoscriviamo anche noi [Maggioli] la richiesta.
Grazie

**Comment by mariottiDPA** [comment]
Buongiorno, ci uniamo anche noi (DigitalPA). Grazie

**Comment by dpagliari** [comment]
Anche noi attendiamo la conferma della data del passaggio.
Grazie

**Comment by federicodemarco** [comment]
Ciao a tutti,
vi segnalo che ieri è stato pubblicato il changelog4.
Se lo interpreto correttamente le date sono le seguenti:

- Pubblicazione contenuti su GitHub: 10/12/2024
- Rilascio in Qualificazione: 17/01/2025
- Rilascio in Esercizio: 17/02/2025

Spero di poter essere stato utile

**Comment by obigno77** [comment]
Si è deciso di mantenere la scadenza perchè è arrivato il momento di innalzare la versione e alternativamente si rischia di non avere tempo sufficiente per pianificare lo switch alla major 1.13. ANAC è comunque disponibile a rivedere la data di esercizio del changelog-04.
