### ISSUE TITLE
SDK 1.12 e changelog04

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#1929]
Buongiorno, dato che il passaggio all’SDK 1.12 ha tempi un po’ più rilassati di quanto prospettato a novembre, dal momento che dal changelog04 non si evince chiaramente l’obbligo di utilizzo della SDK 1.12 ma solo il fatto che alcune codelist sono state aggiornate a tale versione, si deve dedurne che il changelog04 non implichi il passaggio alla SDK 1.12?

**Comment by AnrivaDeloitte** [comment]
Buongiorno, anche lato ARIA S.p.A. ci agganciamo alla issue e segnaliamo il thread aperto alla issue #1925 .

Grazie

**Comment by mariottiDPA** [comment]
Buongiorno, ci aggreghiamo anche noi (DigitalPA), grazie

**Comment by dpagliari** [comment]
Buongiorno,

anche noi chiediamo chiarimenti in merito

Grazie

**Comment by Gestore-Venicecom** [comment]
Salve anche noi ci accodiamo alla segnalazione 

Grazie

**Comment by paolo-urbanetto** [comment]
Sottoscriviamo anche noi [Maggioli].
Grazie

**Comment by obigno77** [comment]
La data pianificata prevede lo switch da v1.9 a v1.12 senza sovrapposizioni. ANAC è disponibile a rivedere la pianificazione tenuto conto che il TeD ha dilazionato la validità della 1.9
