### ISSUE TITLE
FVOE-Vincoli di accesso in base alla fase del processo

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#194]
si chiede se l'accesso ai servizi di FVOE è vincolato alla fase d processo legato alla data di fine presentazione offerte

**Comment by supportoAnac** [comment]
L'accesso al FVOE é successivo alla fase di pubblicazione dell'appalto. Sarà possibile accedere al FVOE anche dopo la presentazione delle offerte.
