### ISSUE TITLE
FVOE - Gestione chiave di accesso per Aziende non residenti in Italia

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#195]
Si chiede come gestire il caso di aziende non residenti in Italia: con quale chiave di accesso si può accedere al fascicolo?

**Comment by supportoAnac** [comment]
Non si tratta di un quesito tecnico. Per la comprova dei requisiti vale la normativa nazionale e comunitaria. Come già previsto dall’attuale versione del FVOE, un operatore economico privo di sede legale in Italia può accedere e inserire nel fascicolo documentazione utile alla comprova dei requisiti posseduti.
