### ISSUE TITLE
Differenza schede P7_1_1 e P7_1_2

### ISSUE THREAD

**Issue by collaudo5** [anticorruzione/npa#196]
Salve,

sarebbe possibile avere un chiarimento in merito alla differenza tra le schede P7_1_1 e P7_1_2?
Dal file _Schema-cronologia-schede_ non si riesce ad individuare la fattispecie di utilizzo di una o dell'altra scheda.

Grazie.

**Comment by anac-uscp** [comment]
Le schede P_7_1_1 e P_7_1_2 non presentano differenze, ma sono state distinte perché i relativi flussi presentano differenze in fase di aggiudicazione (cfr. A_7_1_1 e A_7_1_2)
Le stazioni appaltanti devono usare il flusso 711 se, in aggiudicazione, intendono pubblicare sulla GUUE uno degli eform 25,26,27,28 (v. scheda A_7_1_1), mentre devono usare il flusso 712 se non intendono pubblicare alcun eform (v. scheda A_7_1_2)
Questo perché la pubblicazione degli eform 25, 26, 27, 28 (relativi all’avviso volontario per la trasparenza preventiva di cui all’art. 86 del codice) non è obbligatoria per cui le stazioni appaltanti hanno la facoltà di decidere se pubblicarli o meno.
