### ISSUE TITLE
Scheda P7 - Definizione flusso operativo

### ISSUE THREAD

**Issue by collaudo5** [anticorruzione/npa#197]
Salve,

all'interno di un flusso gara quando deve essere previsto l'utilizzo delle schede P7_1_x ?

Grazie.

**Comment by anac-uscp** [comment]
Con tali schede le stazioni appaltanti rendono noto l’avvio di un’indagine di mercato volta a ricevere richieste di invito, al fine di individuare gli operatori economici da invitare alla successiva procedura negoziata senza bando.
Le P_7_1_1 e P_7_1_2 riguardano l’avvio di un’indagine di mercato finalizzata ad una procedura negoziata senza bando di valore pari o superiore alla soglia (per le differenze tra le due schede vedere risposta a issue 196).
La scheda P_7_1_3 riguarda l’avvio dell’indagine di mercato finalizzata ad una procedura negoziata senza bando sottosoglia.
