### ISSUE TITLE
FVOE-per gare con CIG Derivato

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#198]
si chiede conferma che il FVOE debba essere disponibile anche in caso di accordi quadro o per convenzioni con CIG derivato

**Comment by supportoAnac** [comment]
Il FVOE è disponibile per ogni procedura di affidamento o fase di esecuzione di un contratto nel momento in cui sia necessaria la comprova dei requisiti ai sensi del codice vigente degli operatori economici affidatari o esecutori, ai sensi del codice vigente.
