### ISSUE TITLE
Servizi Anac Esistenti - Richiesta Cig

### ISSUE THREAD

**Issue by ferdinandjmaddela** [anticorruzione/npa#20]
I servizi attuali esistenti per la richiesta di Cig/SmartCig (inserisciGara, inserisciLotto, pubblica ecc.) sono stati integrati dal contesto **comunicaAppalto** ? In caso positivo, è possibile avere maggiori informazioni su come verrano gestiti i nuovi servizi rispetto agli attuali?

**Comment by supportoAnac** [comment]
I nuovi servizi sostituiscono integralmente le funzioni espostee da SIMOG, è previsto un periodo di sovrapposizione del sistema con i servizi Simog mentre Smartcig verrà definitivamente sostituito. Le modalità di esercizio contemporaneo dei servizi SImog e NPA verrà disciplinato da ANAC con proprio provvedimento.
