### ISSUE TITLE
FVOE - dati richiesta

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#202]
•Quali sono gli attributi del jason che può essere passato nel campo “datiRichiesta” per il servizio Richiedi documento?

**Comment by supportoAnac** [comment]
La descrizione dei json contenente gli attributi da passare in base al tipo documento è in fase di definizione con i singoli enti certificanti. Quando terminato il documento sarà pubblicato sul sito https://github.com/anticorruzione/npa .
