### ISSUE TITLE
eForms - Validazione Avvisi 

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#204]
Dal momento che le specifiche tecniche di ANAC riportano che la versione dell'SDK utilizzata per la validazione degli avvisi è la 1.7, confermate che potremo basarci su tale versione? Secondo quanto riportato alla risposta ISSUE 14 e 19 su Github, ANAC riporta con 90 giorni di anticipo la versione aggiornata. Tramite quale canale avviene questa comunicazione?

**Comment by supportoAnac** [comment]
Col rilascio di settembre è stato adottato come standard dalla piattaforma di esercizio la versione di eForms SDK 1.8.0.
Vedere anche:
https://github.com/anticorruzione/npa/blob/main/README.md
https://github.com/anticorruzione/npa/issues/156
