### ISSUE TITLE
Delibera n. 264 ANAC del 20 giugno 2023 - Provvedimento art. 28 - Trasparenza - Requisiti di trasparenza

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#206]
Si chiede conferma che i dati trasmessi alla BDNCP siano sufficienti a garantire i requisiti di trasparenza per alimentare la “Piattaforma unica per la Trasparenza” gestita da ANAC. Inoltre, si chiede conferma che rimanga l’obbligo per gli enti di garantire la trasparenza dei dati degli appalti anche tramite le “Amministrazioni Trasparenti” dei propri siti istituzionali.

**Comment by supportoAnac** [comment]
Si rimanda a https://www.anticorruzione.it/-/pubblicazione-dei-dati-relativi-ai-contratti-pubblici-di-lavori-servizi-e-forniture-art.-37-
