### ISSUE TITLE
Discrimine Schede

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#21]
Nell'elenco delle tipologiche il json tipoSchede aiuta a discriminare la scelta della scheda da passare nel payload della chiamata del servizio NPA? In caso la discriminante della scheda da utilizzare è la colonna E dell'orchestratore e la successiva colonna K che definisce la scheda successiva.
Grazie mille

**Comment by supportoAnac** [comment]
Si esatto. Come discriminante della scheda può essere utilizzaro lo schema delle regole di orchestrazione delle schede consultando la colonna "schedaDescrizione".
