### ISSUE TITLE
PROGETTI PER LA CERTIFICAZIONE DELLE PIATTAFORME DI APPROVVIGIONAMENTO - PCP e PDND

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#213]
nell'invocazione dei servizi di ANAC, come si fa ad identificare e trasmettere l'identità della SA? Come si fa a trasmettere l'identità dell'utente o dell'operatore?

**Comment by mpizziconi** [comment]
le informazioni di identità della Stazione Appaltante e dell'Utente connesso sono contenute nel token JWS previsto dallo standard di interoperabilità e definito qui https://github.com/anticorruzione/npa/blob/main/docs/specifiche-jws/jws.yaml
