### ISSUE TITLE
Schede S - Chiamate al servizio

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#215]
Dato che le schede S riportano di inserire un solo CIG nella scheda, è corretto che si debba fare una chiamata al servizio per ogni lotto della procedure?

**Comment by supportoAnac** [comment]
Sì, è corretto.

**Comment by sfala** [comment]
Buigiorno,
la risposta ricevuta alla presente è i ncontrasto con quanto spegato nella riunione tecnica del 16/11/2023.

**Comment by supportoAnac** [comment]
Confermiamo che il campo idPartecipante va generato in fase di creazione della chiamata dalla stazione appaltante, quando si invia la scheda S2 o quando si inviano le schede di affidamento diretto con l’elenco dei partecipanti.
