### ISSUE TITLE
Eforms 1.7 - Retrocompatibilità

### ISSUE THREAD

**Issue by jmf330** [anticorruzione/npa#216]
In merito alla issue #156 , come enotices2, gestirete la retrocompatibilità? 

un eforms compilato con la 1.7 sarà valido e utilizzabile per i servizi NPA/PCP?

**Comment by mpizziconi** [comment]
il modello dati SDK 1.7 è stato abbandonato in favore della versione 1.9.
PCP non è retrocompatibile con la versione 1.7 che cesserà di essere supportata anche dal TED ad aprile 2024
