### ISSUE TITLE
Schede e File Ochestratore

### ISSUE THREAD

**Issue by pb40527** [anticorruzione/npa#217]
1. Le schede P6_3; P6_4;  P6_5;    P6_6; non sono presenti nel file orchestratore ma sono state caricate nella cartella in GitHub "Modello Dati"
2. La scheda SQ1 è presente invece nel file orchestratore ma non state caricate nella cartella in GitHub "Modello Dati"

è possibile allineare i dati?

**Comment by supportoAnac** [comment]
Le schede inizialmente pubblicate come P6.3,P6.4,P6.5,P6.6 sono state sostituite dalle schede P4.3,P4.4,P4.5,P4.6, come correttamente riportato nel file Excel. 
Le schede  P6.3,P6.4,P6.5,P6.6 sono state eliminate nell'ultimo rilascio ( https://github.com/anticorruzione/npa/issues/186 )
SQ1 è una nuova scheda che è stata  inserita nell'ultimo rilascio ( https://github.com/anticorruzione/npa/issues/185 )
