### ISSUE TITLE
Response error conferma-appalto

### ISSUE THREAD

**Issue by evalentip** [anticorruzione/npa#218]
il servizio conferma-appalto produce diverse response error se eseguiamo il test con un thread 80/80 . In seguito le response:

{"status":400,"title":"KO","detail":"AP_N_CONF","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}
<html><body><h1>504 Gateway Time-out</h1>The server didn't respond in time.</body></html>
java.net.SocketException: Connection reset

 Lo stesso script se lanciato con un thread 10/10 non produce errori.

**Comment by supportoAnac** [comment]
Gli eService PCP esposti da ANAC hanno la finalità di favorire lo sviluppo delle piattaforme digitali di approvvigionamento nella loro componente di integrazione con BDNCP. L’ambiente è dunque attualmente dedicato all’esecuzione di test funzionali e non di performance.
Come noto, per semplificare l’accesso agli sviluppatori, al momento la configurazione dei servizi non è definitiva e ciò non consente di distinguere gli utenti chiamanti, inoltre i servizi sono esposti su un endpoint pubblico, quindi ANAC implementa policy di sicurezza perimetrale e limitazione degli accessi anomali, pertanto l’esecuzione di test di performance non coordinati con ANAC è un’attività del tutto priva di utilità che può incidere negativamente sui test di altri utenti.
