### ISSUE TITLE
Utilizzo complementare all'interoperabilità delle "interfacce web a supporto delle Amministrazioni" 

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#219]
Buongiorno.
Dalle Regole Tecniche si desume che la piattaforma digitale di approvvigionamento non deve obbligatoriamente integrare tutte le schede previste (ad esempio potrebbero non essere di interesse le schede della fase di esecuzione, oppure quelle legate al settore della "difesa", ecc.).
Con riferimento al "documento-specifiche-servizi-npa.md", in particolare al capitolo ["3 Architettura generale" ](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md#3architettura-generale) dove si cita che sono previste anche "interfacce web a supporto delle Amministrazioni", si chiede: queste interfacce potranno essere usate in maniera complementare alla piattaforma digitale di approvvigionamento?

Ad esempio, se la piattaforma digitale di approvvigionamento per qualche ragione non supporta la scheda "A7.1.1 - aggiudicazione procedura negoziata senza bando pari o sopra soglia", la Stazione Appaltante potrà utilizzare le "interfacce web a supporto delle Amministrazioni" per compilare e trasmettere questa scheda?

Se si, queste interfacce saranno disponibili già dal 25 ottobre?

**Comment by supportoAnac** [comment]
La UI prodotta da ANAC è integrabile con le API e consente di adottare nel medesimo processo indifferentemente l’una o l’altra modalità per l’invio dei dati.
Le piattaforme, tuttavia, non possono fare affidamento sulla effettiva presenza della nostra UI, in quanto, sebbene in sviluppo, non è garantito che le interfacce verranno portate in esercizio.
