### ISSUE TITLE
profilo RP e stazione appaltante

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#22]
Nel caso di piattaforma aggregatrici sarà quest'ultima ad accreditarsi sul PDND per fruire dei servizi a catalogo esposti dall'NPA, la stazione appaltante fruirà dei servizi NPA per il tramite della piattaforma aggregatrice (si conferma questa affermazione?). In questo caso i dati della stazione appaltante nel metodo crea-appalto sono passati tramite apposito claim riportato di seguito:
"stazioniAppaltanti": [
        {
          "codiceFiscale": "string",
          "codiceAusa": "string",
          "codiceCentroCosto": "string",
          "funzioniSvolte": [
            {
              "codice": "string",
              "descrizione": "string"
            }
          ],
          "saTitolare": true
        }
      ],

In questo caso la figura dell'RP come viene indicata?

Grazie mille

**Comment by supportoAnac** [comment]
Corretto, si precisa tuttavia che il modello dati riportato nella domanda è stato aggiornato con il rilascio dell' 8/6/2023. Il RP che ha in carico la data è implicitamente l'utente che effettua la chiamata al servizio creaAppalto.
