### ISSUE TITLE
Gestione pregresso bandi europei

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#220]
Buongiorno,
con riferimento alla https://github.com/anticorruzione/npa/issues/140:

Se il bando SF02 è stato pubblicato non con la PCP sarà impossibile pubblicare l'avviso di aggiudicazione.

Qualora invece il bando SF02 sia stato pubblicato (entro il 31/12/2023) mediante una piattaforma qualificata come esender, sarà poi possibile pubblicare sempre attraverso la medesima piattaforma (a quel punto integrata con PCP) l'avviso di aggiudicazione?

Chiediamo gentile riscontro

**Comment by federicodemarco** [comment]
Si sollecita un riscontro

**Comment by federicodemarco** [comment]
si sollecita un riscontro

**Comment by mpizziconi** [comment]
Il periodo transitorio sarà disciplinato da un provvedimento congiunto ANAC-MIT
