### ISSUE TITLE
Flusso pubblicazione bando europeo

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#221]
Buongiorno, 
con riferimento alla issue https://github.com/anticorruzione/npa/issues/165

La risposta fornita rimane ad un livello troppo alto. il quesito posto chiede di esplicitare un flusso tra quelli documentati nella documentazione fornita.
Il quesito è di tipo funzionale, pertanto chiedo cortesemente un riscontro dello stesso tipo.
Occorre conoscere la sequenza delle attività per essere in grado di verificare gli impatti che l'integrazione con la PCP avrà sugli attuali flussi in essere sulle piattaforme di eproc

**Comment by anac-uscp** [comment]
Risposta alle domande:
Confermate che:
1 - Per 'invio al TED dell'avviso di aggiudicazione è necessario inviare a PCP la scheda di aggiudicazione?
2 - l'invio della scheda aggiudicazione deve essere obbligatoriamente preceduto dall' invio della scheda acquisizione partecipanti?
1 - Si, si conferma che è necessario inviare una scheda di aggiudicazione preceduta da una scheda S2 ed eventualmente, nei casi previsti, anche da una S1
2 - Si, deve essere preceduto dalla scheda S2, come sopra
