### ISSUE TITLE
Pubblicazione avvisi

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#228]
Siamo concessionari della pubblicazione sia su GURI che su GUUE e svolgiamo questo servizio anche per clienti che svolgono procedure di acquisto su altre piattaforme 
telematiche. Dal diagramma degli stati dell'appalto, presente nel documento npa_documento-specifiche-servizi.pdf pare evidente il legame forte tra appalto (procedura di gara) e pubblicazione (totalmente a carico della BDNCP). 
Sarà quindi possibile pubblicare bandi/avvisi solo per procedure di gara che si svolgono sulla stessa piattaforma?

**Comment by dpagliari** [comment]
E' possibile avere cortesemente una risposta?

**Comment by mpizziconi** [comment]
Per la pubblicità in ambito nazionale ed europeo le stazioni appaltanti devono necessariamente utilizzare i servizi PCP
