### ISSUE TITLE
Finalità Gestione Utenti - API presa-carico

### ISSUE THREAD

**Issue by spanoannalisa** [anticorruzione/npa#229]
Buongiorno,

da specifiche tecniche sullo yaml condiviso risulta che l'API get presa-carico, utile per l'associazione di un responsabile di progetto, abbia una request così definita:

{
  "idAppalto": "f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
  "cig": "9050626CD6"
}

mentre ci aspettiamo che si debba passare in request almeno il CF del responsabile di progetto che dovrà essere associato all'idAppalto. 
E' possibile sapere se le specifiche relative alla presente API sono complete o sono in fase di lavorazione e se si quando potremo avere a disposizione la versione definitiva dell'API con la quale dobbiamo comunicare? 

Grazie

**Comment by supportoAnac** [comment]
L'operation presa-carico associa come responsabile di progetto il codice fiscale del soggetto autenticato che sta eseguendo la chiamata al servizio.
