### ISSUE TITLE
Diagramma a stati Appalto - Creazione scheda Aggiudicazione 

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#23]
Sarebbe utile tracciare che la creazione scheda Aggiudicazione è possibile quando l'appalto è in stato pubblicato e non cambia lo stato dell'appalto fintanto che non viene confermata, altrimenti il conferma-scheda non si capisce dove si appoggi non essendo chiaro quando la scheda stessa sia stata creata. Oppure è da intendersi che la scheda aggiudicazione è creata automaticamente e deve solo essere confermata?

**Comment by supportoAnac** [comment]
L'operation crea-scheda permette di inviare una scheda tra quelle ammesse nelle fasi di post pubblicazione. La scheda rimane in stato di in lavorazione finchè non sarà invocato per la stessa scheda il metodo conferma-scheda. Questo provvederà a confermare i dati inviati e, qualora il tipo di scheda lo preveda, avviare la fase di pubblicazione.
