### ISSUE TITLE
CIG codificati con i servizi in dismissione

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#230]
Salve,
Di seguito vi elenco alcuni dubbi:

- Nel caso in cui viene codificato un CIG prima del 1 gennaio 2024, il perfezionamento verrà gestito dopo tale data?
- Nel caso in cui la risposta al precedente dubbio è affermativa, il CIG perfezionato successivamente è valido/utilizzabile per concludere il ciclo dell'appalto in piattaforme certificate ?
- Nel caso contrario, come procedono le SA ?

**Comment by mpizziconi** [comment]
vedi https://github.com/anticorruzione/npa/issues/162
