### ISSUE TITLE
Rettifica Avviso

### ISSUE THREAD

**Issue by evalentip** [anticorruzione/npa#231]
Si chiede conferma che il rettifica avviso può essere richiamato solo prima della scadenza della presentazione offerte
Se la gara scade e tale data viene prorogata, è possibile chiamare il rettifica avviso oppure vale la data di scadenza inviata nel primo invio di scheda di indizione?

**Comment by federicodemarco** [comment]
vedi anche https://github.com/anticorruzione/npa/issues/224

**Comment by mpizziconi** [comment]
La rettifica di un avviso di gara è un'azione amministrativa che segue le norme del codice dei Contratti e del diritto amministrativo.
La PCP non pone nessun termine alla possibilità di invocare il servizio
