### ISSUE TITLE
Servizio Modifica-avviso

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#235]
Salve, 
Nel caso in cui ho invocato il servizio "pubblica-avviso" e il servizio ci ritorna un KO, quindi l'avviso non risulta pubblicato, il formulario modificato deve essere inviato tramite il servizio "modifica-avviso" e non più con il servizio "pubblica-avviso"?

**Comment by supportoAnac** [comment]
Se il servizio di pubblica-avviso ritorna direttamente un errore nell’invocazione, allora può essere richiamato. Se invece il KO è della verifica asincrona effettuata in backend (e quindi il pubblica-avviso ha dato un ack ok ma il ko si rileva dal servizio di esito-operazione), allora è necessario chiamare il modifica-avviso per aggiornare la scheda.
