### ISSUE TITLE
Servizio aggiungi-soggetto - Gestione Utenti

### ISSUE THREAD

**Issue by spanoannalisa** [anticorruzione/npa#236]
Buon pomeriggio,

chiamando il servizio aggiungi-soggetto (host apigw-test.anticorruzione.it/modi/rest/GestioneUtenti/v1), passando in request il seguente json:

 {
  "codiceFiscale": "PLLPLN80A01H501M",
  "idAppalto": "192aa7f5-eecf-4b74-b2b1-df0304804dc9",
  "cig": "65019108-ad8d-4acb-bf40-bcb13e361b6e1694534146936",
  "ruolo": {
    "idTipologica": "tipoRuolo",
    "codice": "DRP"
  },
  "servizio": {
    "idTipologica": "tipoServizioSoggetto",
    "codice": "POST_PUB"
  },
  "operazione": {
    "idTipologica": "tipoOperazioneSoggetto",
    "codice": "CONSULTA_SC"
  },
  "dataInizio": "2022-01-23T12:02:05Z",
  "dataFine": "2024-01-23T12:02:05Z"
}

il servizio restituisce l'errore generico di seguito riportato:

{
    "status": 500,
    "title": "KO",
    "detail": "Errore Generico",
    "type": "about:blank",
    "errori": [
        {
            "idTipologica": "errori",
            "codice": "ERR9999"
        }
    ]
}

che non ci consente di capire per quale motivo non si riesca ad aggiungere un delegato associandolo ad un idAppalto creato precedentemente.

**Comment by supportoAnac** [comment]
È necessario eliminare il CIG dalla request in quanto l’autorizzazione non è gestita a livello di lotto ma solo di appalto.
