### ISSUE TITLE
modello dati-schede

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#24]
Attualmente risultano mancanti le informazioni legate alle seguenti schede:
- AD2.25
- AD2.26
- AD2.27
- AD2.28
- AD3
- AD4
- AD5
- P1.15
Quando saranno disponibili tali dati?

**Comment by supportoAnac** [comment]
Il modello dati è stato aggiornato con il rilascio dell' 8/6/2023.
