### ISSUE TITLE
Servizio esito-operazione - parametro idAppalto

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#241]
Il servizio esito-operzione richiede come parametro un idAppalto, è inteso l'identificativo della tipologia di servizio ad esempio può essere indicato un idPiano, idAppalto, idAvviso, idScheda e ricevere le relative informazioni?

Questo perchè come da descrizione verrà restituito un eventuale idAvviso
> identificativo univoco dell'Avviso generato da ANAC, qualora il tipo di scheda lo consente, durante l'invocazione delle operazioni dispositive conferma-piano, conferma-appalto, conferma-scheda, modifica-avviso, rettifica-avviso.

**Comment by mladuDPA** [comment]
Attualmente è possibile usare anche l'idPianificazione oltre l'idAppalto come parametro.
Sarebbe molto utile poter specificare anche un idScheda per indicare una scheda di post pubblicazione così da poter identificare univocamente gli esiti della scheda richiesta, senza dover filtrare su tutte le schede di un appalto.

**Comment by supportoAnac** [comment]
Sì. Esito-operazione restituisce il dettaglio delle operazioni di verifica delle principali entità, tramite identificativo (IdAppalto, IdAvviso).
