### ISSUE TITLE
Pubblicazione E-Form - Feedback esito negativo 

### ISSUE THREAD

**Issue by collaudo5** [anticorruzione/npa#246]
Dalle specifiche presenti su GIT è previsto il servizio “STATO-AVVISO” tramite il quale sarà possibile verificare lo stato di pubblicazione di un bando europeo

In caso di esito negativo della pubblicazione del bando, cosa restituirà il servizio “STATO-AVVISO”?  Verrà restituito un codice errore e relativa descrizione restituita da TED o solo lo stato “Non pubblicato”?

Grazie.

**Comment by collaudo5** [comment]
Salve,
si richiede un riscontro.

Grazie.

**Comment by supportoAnac** [comment]
Lo stato-avviso non restituisce informazioni dei processi specifici. Per conoscere il dettaglio di una operazione OCCORRE invocare esito-operazione, dove ad esempio si può impostare nel tipo operazione AV_PUBB, AV_PUBB_IT o AV_PUBB_EU, oppure tramite il servizio consulta-avviso.
