### ISSUE TITLE
Procedura troubleshooting ANAC - analisi e risoluzione KO pubblicazione e-form

### ISSUE THREAD

**Issue by collaudo5** [anticorruzione/npa#247]
In relazione alla issue #246,  qualora la risposta o il codice di errore restituito alla pubblicazione di un e-form non sia sufficiente all’individuazione della soluzione per sbloccare la pubblicazione quale sarà la procedura di troubleshooting prevista da ANAC? E' previsto un tool di apertura ticket con cui richiedere delle verifiche?

Grazie.

**Comment by collaudo5** [comment]
Salve,
si richiede un riscontro.

Grazie.

**Comment by supportoAnac** [comment]
La modalità con cui richiedere assistenza tecnica sarà oggetto di successive comunicazioni.
