### ISSUE TITLE
Servizio Cancella Appalto - Info aggiuntive

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#248]
Buongiorno,
con riferimento alla issue https://github.com/anticorruzione/npa/issues/161 chiedo un ulteriore dettaglio.
Sulla base della documentazione disponibile il **"Cancella Appalto"** passa alla PCP l'**ID appalto**. Essendo l'**ID appalto** unico per una procedura, in caso di procedura multilotto cancella tutti i lotti? In caso di risposta negativa, quale è il metodo per cancellare un singolo lotto?

Inoltre chiedo gentilmente di fare chiarezza in merito alle seguenti issue: https://github.com/anticorruzione/npa/issues/161 e https://github.com/anticorruzione/npa/issues/6.
1) Quando può essere utilizzato il servizio **"Cancella Appalto**"?
2) può essere utilizzato anche dopo che il CIG è stato assegnato mediante il **conferma appalto**?
3) Può essere utilizzato anche dopo il "**Pubblica avviso**"?

**Comment by federicodemarco** [comment]
Si sollecita un riscontro

**Comment by mpizziconi** [comment]
Il servizio può essere utilizzato dopo la conferma dei dati e prima della pubblicazione dell'avviso

**Comment by federicodemarco** [comment]
Grazie per il riscontro @mpizziconi le chiedo cortesemente un riscontro/conferma

1) **Cancella appalto** può essere utilizzato da dopo **Crea appalto** fino a prima del **pubblica avviso**
2) In caso di procedura multilotto, il servizio **Cancella appalto** cancella tutti i lotti

**Comment by mpizziconi** [comment]
1 confermo 
2 si
