### ISSUE TITLE
cronologia inoltro anac-form

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#25]
Seguendo il flusso dell'orchestratore vediamo che la scheda P1.10 può essere seguita dalle schede S1 ed S2. Tutte e 3 le schede possono essere richiamate da crea-appalto e da modifica-appalto. 
Significa che va prima chiamato il crea-appalto passando la scheda P1.10, poi per passare la S1 ad esempio va chiamato il modifica-appalto? Oppure possono essere passate anche due schede nello stesso servizio?

**Comment by supportoAnac** [comment]
Con l'aggiornamento del modello dati rilasciato in data 8/6/2023, le schede S1, S2 dovranno essere passate in input al servizio di crea-scheda che permette di inviare una scheda tra quelle ammesse nelle fasi di post pubblicazione. Pertanto, il crea-appalto accetterà ad esempio in input la scheda P1.10 e, dopo la sua conferma e pubblicazione, le successive schede dovranno trasmesse tramite il crea-scheda.
