### ISSUE TITLE
Scheda S4 - variazioni all'interno dei flussi

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#250]
la S4 già presente, ha subito una variazione all’interno dei flussi: prima rientrava solo nel flusso della scheda di indizione P1.19, mentre adesso è una scheda cross (quindi può essere richiamata per tutte le schede di indizione). Come si pone verso le altre schede S1,S2,S3 in ordine coronologico?

**Comment by supportoAnac** [comment]
La scheda S4 intercetta i dati anagrafici del soggetto costituito ad esito dell'aggiudicazione dell'appalto.
