### ISSUE TITLE
Schede - Utilizzo informazione "subappalto" con diversi valori

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#251]
dalla documentazione il campo
datiBaseAggiudicazioneSubappalto.subappalto viene utilizzato:

1. nella scheda A2_29 come codelist (subappalto.json) riferito al campo TED BT-733
2. nelle schede A2_32, A2_33, etc. come boolean in risposta al quesito "L'affidatario ha richiesto in sede di offerta la possibilità di subappaltare parte delle prestazioni?"

si ritiene utile uniformare il campo ovvero creare un nuovo campo per diversificare la richiesta.

**Comment by supportoAnac** [comment]
La segnalazione è corretta. È un errore che verrà corretto al prossimo rilascio.
