### ISSUE TITLE
Schede - Gestione Idcontratto

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#253]
Abbiamo riscontrato che nell'ultimo aggiornamento del 22 settembre è stato rimosso il campo idcontratto dall'oggetto DatiContrattoType nel modello dati della scheda SC1

Tale valore risulta essere obbligatorio nelle successive schede come ad esempio nella scheda RSU1, si prega di chiarire se tale variazione sia dovuta ad un refuso oppure nel caso in cui non lo sia, dove recuperare tale informazione.

**Comment by supportoAnac** [comment]
L’idContratto viene restituito dal servizio chiamando il metodo EsitoOperazione, dopo aver inviato la scheda di sottoscrizione del contratto.
