### ISSUE TITLE
Struttura CIG

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#254]
Buongiorno,

a seguito dei test effettuati sulla piattaforma, i CIG restituiti ad oggi sono stringhe alfanumeriche di 49 caratteri (es. b29ef0b1-91c0-437a-80ea-5421397238381695162608925). Si chiede conferma che la struttura del CIG attuale di 10 caratteri NON verrà modificata dal 01 Gennaio 2024.

Grazie

**Comment by paolo-urbanetto** [comment]
Perdonate, ma così ci imponete di modificare la nostra struttura dati, adeguare i controlli sul valore del CIG... e solo per una fase temporanea dello sviluppo, per poi ripristinare tutto...
Capisco che così accelerare gli sviluppi lato vostro, ma li rallentate/complicate a tutti i fruitori.
Propongo un compromesso: generate una stringa generica da 10 caratteri o un numero con padding... almeno così non dobbiamo ridimensionare il campo.
Grazie
