### ISSUE TITLE
Scheda non aggiudicazione

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#255]
Buongiorno,

la scheda NAG per la non aggiudicazione di un lotto è disponibile solo per gare sottosoglia. Con che scheda è possibile comunicare la NON aggiudicazione di un lotto in caso di procedura soprasoglia? Ad es. nel file orchestratore, per il flusso di appartenenza della scheda P1.16 non risulta richiamabile la scheda NAG.

Grazie

**Comment by supportoAnac** [comment]
La comunicazione delle Non Aggiudicazioni per gli appalti sopra soglia segue le regole previste dal TED per le eForms. In particolare la stessa eForm viene utilizzata per la comunicazione dei lotti aggiudicati e di quelli non aggiudicati.
