### ISSUE TITLE
Funzionalità "Rettifica avviso"

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#256]
Buongiorno,

Non risulta chiaro dalle specifiche se la funzionalità di rettifica avviso generi un nuovo ID Avviso. In caso venga generato un nuovo ID Avviso in stato “in fase di pubblicazione”, L’avviso Rettificato subisce un cambiamento nello stato o rimane “pubblicato”? 

In caso siano necessarie ulteriori rettifiche dell’avviso, si deve utilizzare il servizio di “Rettifica avviso” sull’avviso rettificato o sull’avviso di rettifica?

Nel caso in cui l’avviso di rettifica vada in stato “Non pubblicato” l’utente dovrà invocare nuovamente il servizio di “Rettifica avviso” sull’avviso rettificato in precedenza?

Grazie

**Comment by supportoAnac** [comment]
Il flusso di rettifica segue le specifiche previste dal TED.
