### ISSUE TITLE
file diagrammi e servizi

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#257]
Buongiorno,

a seguito delle ultime modifiche di questi mesi nelle specifiche, non risulta essere stato aggiornato il file contenente il diagramma dei flussi e le descrizioni dei vari servizi. Sarebbe utile avere il file aggiornato per stabilire il corretto funzionamento dei flussi e dei servizi.

Grazie

**Comment by supportoAnac** [comment]
Non è chiaro a quale file si faccia riferimento per il “diagramma dei flussi”.
