### ISSUE TITLE
Gestione utenti: errore 401 "UnauthorizedException"

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#259]
Buongiorno,
provando i servizi di Gestione utenti otteniamo sempre errore 401.
Abbiamo visto che gli altri servizi ignorano il token JWS e supponiamo venga ignorato anche da questi.
Abbiamo anche provato ad inviare un token JWS (composto sulla base delle poche specifiche disponibili), ma l'errore è sempre 401.

Se ad esempio invochiamo il servizio di ricerca con una chiamata quale la seguente:
https://apigw-test.anticorruzione.it/modi/rest/GestioneUtenti/v1/ricerca-soggetti?idAppalto=f81d4fae-7dec-11d0-a765-00a0c91e6bf6

con Token: eyJ0eXAiOiJhdCtq********************55r4A

e Agid-JWT-TrackingEvidence: ZXlKcmFXUWlPa********************xNZw==

La risposta è sempre:

{
    "status": 401,
    "title": "KO",
    "detail": "AUT01, ",
    "type": "about:blank",
    "errori": [
        {
            "idTipologica": "it.anticorruzione.ms.pcp.pcpms.exception.UnauthorizedException",
            "codice": "AUT01, "
        }
    ]
}

Stiamo sbagliando qualcosa?
Se si, è possibile avere un esempio?

**Comment by mpizziconi** [comment]
vedi 
https://github.com/anticorruzione/npa/issues/322
e
https://github.com/anticorruzione/npa/issues/310
