### ISSUE TITLE
Servizi consulta-appalto - Idpartecipante e aggiudicatario

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#261]
Dall'analisi effettuata abbiamo riscontrato che risulta assente l'informazione relativa all'idpartecipante e aggiudicatario nei servizi generali di consulta-appalto e FVA,.

Riteniamo pertanto utile e necessario richiedere l'integrazione di tale informazione nei servizi  appena descritti.

**Comment by mpizziconi** [comment]
CR acquisita ma non schedulata
