### ISSUE TITLE
Schede - Relazione tra contratto e relativo subappalto/Operatore Economico

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#262]
Si riscontra che nelle schede successive alla RSU1 (ad esempio CS1) non è presente un legame tra il contratto e il relativo subappalto/Operatore Economico oggetto di una eventuale chiusura.
I valori richiesti nella schede di tipo CS1 sono idcontratto e l’oggetto subappalto ma non sono presenti riferimenti all’operatore economico.
Si prega di chiarire come determinare la relazione tra questi oggetti.

**Comment by supportoAnac** [comment]
Nelle schede successive alla RSU1 è stato modificato l’identificativo. Il dato richiesto non è più l’idContratto ma l’idScheda, che permette di tenere traccia delle informazioni inviate.
Per la scheda ES1, successiva alla RSU1, viene richiesto l’idScheda restituito dal servizio all’invio della scheda di richiesta di subappalto.
Per la scheda CS1, successiva alla ES1, viene richiesto l’idScheda restituito dal servizio all’invio della scheda di esito subappalto.
