### ISSUE TITLE
Schede di esecuzione - Pubblicazione Regole

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#264]
Al momento non sono ancora disponibili le regole per le schede previste per la fase di esecuzione, ad eccezione di quelle per la modifica contrattuale (sebbene riferite a schede non più esistenti, come M1_38 e M1_39).
Quando è prevista la pubblicazione di tali regole?

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 24/11/2023.
