### ISSUE TITLE
Schede - Servizio consulta-avviso

### ISSUE THREAD

**Issue by davideorsi-bit** [anticorruzione/npa#266]
Buonasera, 
ho notato una differenza nel json ritornato dall'api /PubblicaAvviso/v1/consulta-avviso, il json ritornato ha una struttura diversa rispetto a quella descritta nello schema ConsultaAvvisoResponse, i due oggetti "Appalto" ed "Scheda" non sono contenuti nell'oggetto "Avviso" ma sono allo stesso livello.
Inoltre nel Json di risposta l'elemento scheda è definito come oneOf-> DatiPianoType, DatiAppaltoType e SchedaPostPubblicazioneType, non contiene un attributo di tipo "type" per capire di quale tipo di scheda si tratta.
Grazie
Cordiali saluti

**Comment by supportoAnac** [comment]
Con la versione v2 il modello dati è stato aggiornato. Il tipo scheda è derivabile dal codice scheda e dalle logiche di orchestrazione definite nel file npa/docs/orchestratore/schema-cronologia-schede.xlsx

**Comment by davideorsi-bit** [comment]
Scusate ma non mi torna la risposta, il json di interfaccia dice chiaramente che l'attributo scheda deve essere come di seguito. 
Ci deve essere una property type valorizzata con i tre possibili valori "DatiPianoType","DatiAppaltoType","SchedaPostPubblicazioneType"  altrimenti deserializzando l'oggetto non si capisce quale oggetto costruire.

/**
* OneOfAvvisoTypeScheda
*/
@JsonTypeInfo(
  use = JsonTypeInfo.Id.NAME,
  include = JsonTypeInfo.As.PROPERTY,
  property = "type")
@JsonSubTypes({
  @JsonSubTypes.Type(value = DatiPianoType.class, name = "DatiPianoType"),
  @JsonSubTypes.Type(value = DatiAppaltoType.class, name = "DatiAppaltoType"),
  @JsonSubTypes.Type(value = SchedaPostPubblicazioneType.class, name = "SchedaPostPubblicazioneType")
})
public interface OneOfAvvisoTypeScheda {

}
