### ISSUE TITLE
Schede - Invio post-pubblicazione

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#267]
Buongiorno,

È possibile inviare una scheda di post-pubblicazione più di una volta? Ad es. la Scheda S2 per un lotto è inviabile solo una volta dopo che la scheda viene confermata? 
n caso l’Ente per errore non abbia indicato un partecipante, per indicarlo deve utilizzare la funzionalità di rettifica dell’avviso generato alla conferma della Scheda S2?

Grazie

**Comment by mpizziconi** [comment]
La successione di schede ammessa da PCP viene verificata secondo le specifiche contenute nel file di orchestrazione https://github.com/anticorruzione/npa/blob/main/docs/orchestratore

La possibilità di modificare il contenuto di una scheda non è ammessa in tutti i casi e l'operazione di rettifica è prevista in coincidenza con l'equivalente azione amministrativa.
Nel caso delle schede S* l'errore di trasmissione dell'elenco dei partecipanti non è ammesso da parte di una piattaforma certificata per la fase di affidamento, che in quanto tale deve essere in grado gestire l'elenco dei partecipanti e di ricevere le offerte.
