### ISSUE TITLE
Certificazione stesso ente con più piattaforme

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#268]
Ci confermate che da piattaforme differenti (dello stesso codice AUSA) si possono interrogare schede e dati generate in fasi precedenti da altro RUP/piattaforma?

**Comment by mpizziconi** [comment]
L'accesso ai servizi è consentito al RUP che ha in carico la procedura, indipendentemente dalla piattaforma utilizzata.
Il requisito richiesto alla piattaforma è di essere inserita nel registro delle piattaforme certificate per la fase di appalto che intende gestire. 
Si precisa che il RUP, Responsabile Unico del Progetto, è appunto Unico. L'accesso di un diverso utente con il ruolo RUP ai dati/servizi relativi ad una procedura può avvenire solo dopo il passaggio di responsabilità dal RUP precedente mediante l'invocazione del servizio gestioneUtenti.presa-carico. Il RUP subentrante deve avere un profilo valido associato ad una delle amministrazioni indicate nella scheda di indizione della procedura.
