### ISSUE TITLE
Servizio conferma-appalto: transazionalità e possibili inconsistenze

### ISSUE THREAD

**Issue by sfala** [anticorruzione/npa#27]
Essendo previsto l'invio dei lotti in un'unica scheda, vorremmo sapere se il servizio "conferma-appalto" gestisce lo stacco dei CIG in maniera transazionale (tutti o nessuno) e cosa verrebbe restituito nel caso non venisse staccato il CIG per qualcuno dei lotti (es. fallisce la validazione dei dati del lotto). 
Vengono staccati i CIG fino al primo errore e, nel caso, posso mandare una scheda in cui compaiono nuovamente anche i lotti per cui ho ottenuto i CIG (rischio di duplicazioni?) o gestisco l'inconsistenza in qualche altro modo? Oppure lo stacco dei CIG è una transazione unica con roll-back? Dovrebbe forse venire in aiuto il servizio di "verifica-appalto" per prevenire l'errore?

**Comment by supportoAnac** [comment]
La gestione dei lotti è "transazionale": l'assegnazione dei CIG avviene per tutti i lotti o per nessuno. Il processo del comunica-appalto implicitamente chiama il verifica-appalto prima della conferma in blocco dei lotti.
