### ISSUE TITLE
Delegato dal Responsabile del progetto (DRP) e Responsabile del Progetto (RP) - Contesto Gestione utenti

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#270]
Buongiorno,
faccio riferimento al documento disponibile su https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md e nello specifico al paragrafo 4.4. Il testo riporta: "**_I servizi di NPA e dei componenti FVA e FVOE sono erogati B2B alle piattaforme di negoziazione e gestione dell'appalto. Gli utenti finali del sistema sono identificati dalla piattaforma fruitrice dei servizi (si faccia riferimento al paragrafo [Contesto di sicurezza](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md#14contesto-di-sicurezza) per i dettagli tecnici), tuttavia tali soggetti devono essere registrati sui sistemi ANAC e dotati di un ruolo opportuno per poter accedere ai servizi NPA. Il ruoli previsti sono i seguenti:

1) RP, responsabile del progetto
2) DRP, delegato dal responsabile del progetto_**"

Al fine di garantire l'operatività di RP e DRP sulle piattaforme di eprocurement e consentire la corretta integrazione, su quale piattaforma ANAC dovranno essere registrati gli utenti? Quando sarà disponibile tale piattaforma?

**Comment by federicodemarco** [comment]
Si sollecita un riscontro

**Comment by mpizziconi** [comment]
Gli utenti devono essere accreditati sui sistemi ANAC. Per l'accreditamento e la profilazione è necessario utilizzare il servizio di registrazione ai sistemi ANAC disponibile dal 2004
