### ISSUE TITLE
Flusso avvisi preinformazione con riduzione termini - Comportamento anomalo 

### ISSUE THREAD

**Issue by GGr8l** [anticorruzione/npa#272]
File: npa/docs /orchestratore/schema-cronologia-schede.xlsx

Buongiorno,

Vorrei segnalare una incongruenza relativa al flusso di alcuni eForms.

I seguenti avvisi sono stati inseriti nel flusso a cui dovrebbero seguire i bandi di gara (Colonna "Elenco delle schede successive ammesse o non ammesse (le schede non ammesse sono precedute dal carattere !)"):
- Avviso di preinformazione utilizzato per abbreviare i termini per la ricezione delle offerte — direttiva generale (eForm n. 7) (scheda PL1_7)
- Avviso di preinformazione utilizzato per abbreviare i termini per la ricezione delle offerte — direttiva settoriale (eForm n. 8) (scheda PL1_8)

Non si capisce perché a tali formulari segue un bando di gara, mentre agli altri avvisi di preinformazione usati a solo titolo informativo (eForm n.4 e eForm n.5) questo non avviene.

Si richiedono gentilmente spiegazioni.

Grazie.

**Comment by anac-uscp** [comment]
Gli avvisi di pre-informazione di cui ai formulari n. 7 e 8 sono utilizzati per abbreviare i termini di ricezione delle offerte nel bando successivo,  è pertanto necessario che vengano strettamente riconnessi l’uno all’altro, per verificare la legittimità del tempo ridotto indicato nel bando stesso. In sostanza, il bando che riduce i termini deve essere necessariamente preceduto da tale avviso.
Gli avviso di pre-informazione a titolo informativo recano informazioni generali al mercato e possono riguardare diversi tipi di procedure, pertanto non è necessario imporre ulteriori vincoli.
