### ISSUE TITLE
Messa in esercizio PCP

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#273]
Buongiorno,
riporto quanto disponibile in documentazione (https://github.com/anticorruzione/npa/blob/main/roadmap.md):

**Ottobre 2023: piattaforma in ambiente di produzione**

Confermate il go live dei servizi **PCP** in ambiente di produzione nel corso di Ottobre?

Grazie

**Comment by mpizziconi** [comment]
i servizi PCP sono esposti in ambiente di qualificazione PDND e disponibili ai gestori per la certificazione delle piattaforme a far data dal 9 ottobre 2023. L'esercizio effettivo della piattaforma segue l'entrata in vigore definitiva del codice dei contratti a far data dal 1 gennaio 2024
