### ISSUE TITLE
Utenti e Ruoli - Delucidazioni sulla figura del Delegato dal Responsabile di Progetto (DRP)

### ISSUE THREAD

**Issue by pb14702** [anticorruzione/npa#274]
Con riferimento alla issue https://github.com/anticorruzione/npa/issues/270 chiedo gentilmente di descrivere cosa si intende per DRP, delegato dal responsabile di progetto, visto che ai sensi del Dlgs 36/2023 i nuovi ruoli nominati dal RUP sono il Responsabili di fase di affidamento e Responsabile di fase di programmazione, progettazione ed eseccuzione. Piú precisamente il DRP indicato nel documento riportato in https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md 
coincide con i responsabili di fase o è un soggetto diverso?

**Comment by mpizziconi** [comment]
DRP è il codice ruolo assegnato ai responsabili di fase previsti dall'art 15 comma 4 del codice.
RP è il codice ruolo assegnato al Responsabile Unico del Progetto definito nello stesso articolo
