### ISSUE TITLE
Dubbi servizi recupera cig ed esito operazione

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#279]
Sono sorti dei dubbi sull'utilizzo dei servizi di recupera cig ed esito operazione.
Infatti entrambi potrebbero essere automatizzati, in modo tale da avere queste informazioni senza interazione diretta dell'utente.
Data però la natura del sistema di auth jws, che richiede ad esempio le informazioni di login del soggetto autorizzato, non è possibile interrogare questi servizi se non in modo diretto, creando quindi ulteriori step che il rup ad esempio dovrà svolgere obbligatoriamente.
Prevedete di agevolare questo flow ad esempio cambiando il sistema di auth di questi servizi?

**Comment by mpizziconi** [comment]
PCP non è progettata per l'interazione diretta con l'utente né come backend di una UI ad uso dell'utentente.
L'interazione con PCP è effettuata da una piattaforma certificata che a sua volta eroga servizi agli utenti finali.
Il token jws trasporta, tra le altre, le informazioni sull'identità dell'utente finalizzate ai requisiti di integrità, non ripudio e tracciatura delle attività e non è connesso in senso stretto alla login
In questo contesto la proposta non può essere accolta
