### ISSUE TITLE
Errore di interpretazione swagger - modello-dati-npa.yaml

### ISSUE THREAD

**Issue by ferdinandjmaddela** [anticorruzione/npa#28]
Nel **modello-dati-npa.yaml**, le righe 195 e 198 puntano al file _'modello-dati-common.yaml'_ non esistente. 
Da correggere con _'modello-dati-tipologiche.yaml'_

**Comment by supportoAnac** [comment]
Il modello dati è stato aggiornato con il rilascio del 13/06/2023.
