### ISSUE TITLE
Con CreaAppalto non sempre viene richiesto l'oggetto dell'appalto e dei lotti

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#284]
Abbiamo notato che con CreaAppalto non sempre viene richiesto l'oggetto dell'appalto e dei lotti.
Nelle schede di tipo P2 l'oggetto c'è, ed è all'interno di DatiBase.

Con altre schede però, ad esempio le P1 e le AD, l'oggetto non è previsto.

Si richiede di includere DatiBase in ogni scheda prevista per la creazione dell'appalto.

**Comment by supportoAnac** [comment]
L’oggetto DatiBase è un oggetto che contiene dati in comune con il TED. Viene pertanto esplicitamente richiesto in anacForm per tutte le schede, come le P2, che non prevedono pubblicazione su TED e quindi non hanno l’eForm nel modello dati. Nelle schede dove è presente l’eForm tale dato è contenuto in esso.
