### ISSUE TITLE
AREA FUNZIONALE: Schede relative alle "Procedure di avvio di indagine di mercato e RDO da elenco fornitori"

### ISSUE THREAD

**Issue by mirellaricca** [anticorruzione/npa#286]
Buongiorno, 
in merito alla fattispecie **"Procedure di avvio di indagine di mercato e RDO da elenco fornitori"**, quali sono le relative schede da gestire?

Grazie

**Comment by anac-uscp** [comment]
Le schede da gestire relativamente alla fattispecie "Procedure di avvio di indagine di mercato e RDO da elenco fornitori" sono le  schede: P7_1_1, P7_1_2, P7_1_3, P7_2
