### ISSUE TITLE
AREA FUNZIONALE: Schede relative alle "Procedure soggette a sola tracciabilità"

### ISSUE THREAD

**Issue by mirellaricca** [anticorruzione/npa#287]
Buongiorno,
in merito alla fattispecie **"Procedure soggette a sola tracciabilità"**, quali sono le relative schede da gestire?

Grazie

**Comment by anac-uscp** [comment]
L'unica scheda relativa alla fattispecie "Procedure soggette a sola tracciabilità" è la scheda P5 'appalti soggetti a sola tracciabilità'
