### ISSUE TITLE
DMN regole di validazione scheda P1_16

### ISSUE THREAD

**Issue by SorSil** [anticorruzione/npa#288]
Buongiorno,
per la scheda **P1_16** troviamo nel **DMN** (P1_16.dmn) delle incongruenze per le seguenti regole di validazione:

- appalto.datiBaseProcedura.tipoProcedura.codice = "neg-wo-call" and some lotto in lotti satisfies lotto.condizioniNegoziata=null
- appalto.datiBaseProcedura.tipoProcedura.codice != "neg-wo-call" and some lotto in lotti satisfies lotto.condizioniNegoziata != null
la prima condizione delle regole fanno riferimento all'oggetto _datiBaseProcedura_ di _appalto_ che sembra non essere presente nella scheda P1_16.
E' corretto che ci siano queste 2 regole per la P1_16?

- appalto.motivoUrgenza.codice = "2"  
La regola indica che quando motivoUrgenza è 'Somma urgenza e protezione civile' restituisca l'errore _"E' stata selezionata la voce 'Somma urgenza e protezione civile' di cui all'art. 140 co. 10 D. Lgs. 36/2023. E' necessario valorizzare il 'link ai documenti relativi all'affidamento diretto in somma urgenza e protezione civile' con la URL della sezione 'Bandi e Contratti' dove sono pubblicati i documenti previsti dal regolamento di vigilanza ANAC"_
E' corretta questa regola o manca una condizione che verifichi la presenza di "link ai documenti"? 

Grazie

**Comment by supportoAnac** [comment]
L'oggetto _datiBaseProcedura di appalto_ è un dato in comune con il TED: nei sottosoglia è contenuto nell’anacForm, mentre nei soprasoglia, come nel caso della scheda P1_16, è un dato presente nell’eForm. Poichè è necessario anche per la pubblicazione nazionale viene estratto dall’eForm e vengono applicate le due regole citate.
Come suggerito, manca una condizione alla regola che riguarda la presenza del campo "link ai documenti", verrà corretto nei prossimi rilasci.
