### ISSUE TITLE
modifiche dell'appalto post rilascio CIG_bis

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#29]
In relazione alla issue # 5 (modifiche dell'appalto post rilascio CIG) attualmente in stato closed si chiede rispetto al terzo punto della risposta ("Per le sole procedure che prevedono la pubblicazione TED, dopo il confermaAppalto e dopo il pubblicaAvviso è possibile inviare un avviso di modifica (modifica-avviso) se la richiesta di pubblicazione non è ancora avvenuta. In questa fase è permessa anche la modifica dei lotti. Invece, se la pubblicazione è già avvenuta è possibile solo inviare un avviso di rettifica (rettifica-avviso) con le sole informazioni rettificabili"):

1. Significa che per le procedure per cui non è prevista la pubblicazione\invio al TED (es: ordini) NON sono possibili modifiche né dopo il conferma-appalto né dopo il pubblica-avviso?

**Comment by supportoAnac** [comment]
NO.
