### ISSUE TITLE
Errori parlanti per ogni id_lotto a seguito di invio della scheda ANAC

### ISSUE THREAD

**Issue by evalentip** [anticorruzione/npa#290]
Si chiede se gli errori ricevuti a seguito di invio della scheda ANAC saranno puntuali nell'indicare il punto in cui si verifica l'errore e/o verrà specificato ogni errore per singolo id_lotto

**Comment by supportoAnac** [comment]
Il servizio esito-operazione riporta gli errori di validazione di una scheda.
