### ISSUE TITLE
Schede di indizione P6.1 e P6.2: verifica cigAccordoQuadro?

### ISSUE THREAD

**Issue by giulia-droid** [anticorruzione/npa#291]
Nella scheda di indizione P6.1 e P6.2 c'è un cigAccordoQuadro obbligatorio cui l'AS AQ aderisce.
Ci sarà un controllo sulla veridicità di tale Cig?

**Comment by anac-uscp** [comment]
Si, il sistema verifica che il CIG AQ indicato corrisponda effettivamente a un Accordo Quadro
