### ISSUE TITLE
Scheda P2.16 - Motivo urgenza per contratti non di somma urgenza

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#293]
Se un contratto non ha somma urgenza, nella scheda P2.16 mettiamo MotivoUrgenza=7 (=Non Applicabile)
Se in questo caso non indichiamo il link documenti somma urgenza (LinkDocumenti) ci viene restituito l'errore REG8 ( Link ai documenti relativi all’affidamento diretto in somma urgenza e protezione civile: deve essere una url valida e quindi iniziare con http o http).

Per ovviare abbiamo dovuto valorizzare con una URL fittizia.

Si chiede se la procedura che abbiamo seguito sia corretta, e nel caso modificare il controllo

**Comment by supportoAnac** [comment]
Segnalazione corretta, la regola verrà modificata per permettere di non indicare il campo link documenti quando non obbligatorio.
