### ISSUE TITLE
Tipologica esito in response di EsitoOperazione e codice "WT"

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#295]
Nella response di EsitoOperazione riceviamo all'interno del payload:

"esito": {
    "idTipologica": "esito",
    "codice": "WT"
}

Nella tipologica esito non esiste però il valore WT. A cosa corrisponde?

**Comment by matteolaltrelli** [comment]
Io ho lo stesso stato su un esito operazione di un conferma-appalto. 
Abbiamo avuto qualche news a riguardo che mi sono perso?
Grazie!

**Comment by supportoAnac** [comment]
La tipologica esito.json è stata aggiornata nel rilascio del 24 Novembre. Ora il campo WT è presente e descritto.
