### ISSUE TITLE
Attivazione verifiche avanzate JWS sui servizi PDND

### ISSUE THREAD

**Issue by sfala** [anticorruzione/npa#297]
Buongiorno,
tenendo conto di quanto previsto dalla roadmap per l'adozione del JWS (docs/specifiche-jws](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-jws/roadmap.md) vorremmo capire a partire dal 16/10/2023 come sarà possibile proseguire con i test in ambiente di collaudo da parte dei team di sviluppo. Ci occorre sapere:
- con quale utente e quale stazione appaltante sarà possibile richiamare i servizi ANAC esposti su PDND? Per quella data verranno migrate le anagrafiche di SIMOG o ci indicherete voi delle utenze da usare?
- potremo impostatre il LoA arbitrariamente per simulare le diverse circostanze?
- con quali ruoli (RP e RDP) saranno censiti gli utenti presenti in PCP di Collaudo?

Infine anticiparci se pubblicherete informazioni ulteriori su questo stesso canale?

Grazie

**Comment by mpizziconi** [comment]
ref https://github.com/anticorruzione/npa/issues/214
