### ISSUE TITLE
Scheda "Incarichi tecnici e prestazioni progettuali"

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#298]
Buongiorno, a cosa si riferisce nello specifico la scheda in oggetto? a quali soggetti? a quelli interni o a quelli esterni alla SA?

**Comment by supportoAnac** [comment]
La scheda S3 relativa agli incarichi e prestazioni progettuali si riferisce a entrambi i soggetti, sia interni che esterni alla SA. 
La distinzione può essere indicata nei seguenti oggetti:
- prestazioni, che richiede il campo “progettazioneInternaEsterna”, che permette di specificare tale informazione.
- incarichi, che richiede il campo "tipoIncarico”, che permette di specificare tale informazione.
