### ISSUE TITLE
Gestione dei servizi esisteni post rilascio della NPA

### ISSUE THREAD

**Issue by Mgrassi21** [anticorruzione/npa#3]
Con riferimento al seguente paragrafo contenuto nel documento [documento-specifiche-servizi-npa.md](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) :

"Il sistema concentra i servizi erogati in precedenza da diversi soggetti/sistemi in particolare:

1) Il Servizio Contratti Pubblici (SCP) del MIT per la pubblicità della programmazione e di bandi e avvisi
2) la Gazzetta Ufficiale della Repubblica Italiana (GURI) come strumento per la pubblicità legale nazionale degli appalti pubblici
3) Simog e SmartCig, per l'erogazione del CIG e il monitoraggio del ciclo di vita dei contratti"

Si richiede le modalità di gestione dei suddetti servizi in concomitanza con il rilascio della NPA. E' previsto un periodo in cui i servizi potranno coesistere ? Ad esempio sarà possibile continuare "staccare il cig" attraverso le piattaforme integrate con SIMOG senza passare dalla NPA / PDND?

**Comment by supportoAnac** [comment]
I nuovi servizi sostituiscono integralmente le funzioni espostee da SIMOG, è previsto un periodo di sovrapposizione del sistema con i servizi Simog mentre Smartcig verrà definitivamente sostituito. Le modalità di esercizio contemporaneo dei servizi SImog e NPA verrà disciplinato da ANAC con proprio provvedimento.
