### ISSUE TITLE
Classificazione erronea fasi eForms - avviso di indizione di gara

### ISSUE THREAD

**Issue by GGr8l** [anticorruzione/npa#30]
File: npa/docs /orchestratore/schema-cronologia-schede.xlsx

Buongiorno,

Vorrei segnalare una incongruenza relativa alla classificazione di alcuni eForms.

I seguenti avvisi sono stati identificati da tempo (2 anni e mezzo almeno) dall'Ufficio Pubblicazioni dell'UE come avvisi facenti parte della **fase di gara (competition)**:
- Avviso di preinformazione utilizzato come avviso di indizione di gara (diversi eForms)
- Avviso periodico indicativo utilizzato come avviso di indizione di gara (diversi eForms)

Ho notato tuttavia che nel file sopra riportato tali avvisi sono stati erroneamente inseriti nella fase di pianificazione.

Quando è previsto l'aggiornamento?

Grazie.

**Comment by supportoAnac** [comment]
Si richiede di effettuare una segnalazione più specifica.

**Comment by GGr8l** [comment]
Buongiorno,

cosa non è chiaro?

Saluti
