### ISSUE TITLE
ESPD e schede AD3 e AD5

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#300]
Buongiorno,
come noto l'art. 52. (Controllo sul possesso dei requisiti) comma 1 recita"
Nelle procedure di affidamento di cui all’[articolo 50, comma 1, lettere a) e b) di importo inferiore a 40.000 euro, gli operatori economici attestano con dichiarazione sostitutiva di atto di notorietà il possesso dei requisiti di partecipazione e di qualificazione richiesti. La stazione appaltante verifica le dichiarazioni, anche previo sorteggio di un campione individuato con modalità predeterminate ogni anno" .Sulla documentazione dei servizi questo appare gestito correttamente (è opzionale per AD3 e non presente per AD5
![immagine](https://github.com/anticorruzione/npa/assets/61240268/d33bcf1e-f0b7-4081-be09-78753c325a3b), mentre non è corretto quanto appare nell'orchestratore alla riga riferita alla'AD5 dove includeESPD è a SI.

**Comment by anac-uscp** [comment]
L’ESPD è obbligatorio perché serve a consentire l’accesso al FVOE per le verifiche.

**Comment by pietropalermoIT** [comment]
Quindi stiamo obbligando gli OE a compilare l'ESPD sotto i 40.000 euro anche se la normativa primaria dice che la SA può chiedere una dichiarazione sostitutiva? ANAC ha deciso per tutti?
