### ISSUE TITLE
Pubblicazione avviso - L'avviso rimane in stato "creato"

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#301]
Dopo avere correttamente creato e confermato un appalto, abbiamo provato a chiamare l'api "pubblica-avviso".
L'operazione è andata a buon fine, ma l'avviso rimane in stato "creato", senza passare agli stati successivi.
Ribadisco che non c'è nessuna evidenza di errore

Questi i riferimenti:
```
idAppalto: 050169b1-7e96-4e83-a190-37a39a862b90
CIG:	   468ffb9a-b246-4882-a56a-3cfb942465d31696324987501
idAvviso:  ca255241-c520-4939-a789-42b9428aad30
```

**Comment by davideorsi-bit** [comment]
Confermo la presenza dello stesso identifico problema anche nelle chiamate fatte da ARIA verso i servizi.

"idAppalto": "ceda010b-7f8c-47c8-8695-eeada9293e41",
 "idScheda": "6c52c3ea-21f9-4d6d-9fa7-c5a8c6e735d3",
 "idAvviso": "026d8c62-0dda-4301-950d-05ddb39454c6",
