### ISSUE TITLE
FVOE - errore documentazione attributo "tipo"

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#302]
Buongiorno, nei servizi di FVOE è citato l'attributo "`tipo`" che si riferisce alla tipologica "`tipoDocumento`", al di là del fatto che consultando la documentazione con uno SWAGGER il link è rotto 
![immagine](https://github.com/anticorruzione/npa/assets/61240268/9939865a-dbdc-4e33-86de-eae145dc95a6)
![immagine](https://github.com/anticorruzione/npa/assets/61240268/a253beaf-ff94-4bec-95d0-49047a3bfdaa)
ma il punto è che la tipologica ha 4 valori solamente (https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/tipologiche/tipoDocumento.json) che nulla hanno a che fare con il FVOE: se ne deve dedurre che il FVOE è attualmente vuoto e quindi non utilizzabile per i controlli in fase di aggiudicazione?

**Comment by supportoAnac** [comment]
È presente un errore nell'url del file che verrà corretto nel prossimo rilascio. l'FVOE é attualmente vuoto.
