### ISSUE TITLE
Scheda I1 - Consegna frazionata ed avvio esecuzione per fasi

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#303]
In Simog, nella scheda Inizio esecuzione contratto, se il contratto è per lavori c'è il campo "Consegna frazionata", se è per forniture o servizi c'è "L'avvio dell'esecuzione del contratto è per fasi"
Nella scheda I1 entrambi i campi sono obbligatori. E' corretto così, oppure il primo sarà obbligatorio per lavori, ed il secondo per forniture/servizi?

**Comment by lelio-raffaelli** [comment]
Chiedo cortesemente un riscontro.

**Comment by lelio-raffaelli** [comment]
Sollecito la risposta, grazie

**Comment by supportoAnac** [comment]
Risolta con il rilascio del 24 Novembre. I campi sono stati resi opzionali nella scheda I1. L’obbligatorietà sarà condizionata dall’oggetto del contratto.
