### ISSUE TITLE
FVOE per Aziende non residenti in Italia 

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#305]
in riferimento alla #195,  considerato che per le stazioni appaltanti la chiave di accesso al fvoe degli operatori economici residenti in Italia è il “codice fiscale impresa”, quale è il codice di accesso per gli operatori economici che non sono residenti in Italia e non hanno quindi un codice fiscale impresa?

**Comment by mpizziconi** [comment]
Può essere utilizzato un identificativo univoco nel paese di residenza, ad es il VAT number, come già previsto dall’attuale versione del FVOE
