### ISSUE TITLE
Accesso al FVOE in caso di contratti derivati da Accordo Quadro

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#306]
in riferimento alla #198, in caso di appalti specifici di AQ con rilancio del confronto competitivo, il CIG al quale fare riferimento per accedere al FVOE è quello dell’appalto specifico oppure quello dell’accordo quadro a cui fa riferimento? 
In caso di ordini diretti su Convenzioni/AQ sarà possibile per la PA (prima della richiesta del CIG) accedere al contenuto del FVOE relativo alla Convenzione/AQ di origine?

**Comment by anac-uscp** [comment]
In caso di appalti specifici di AQ con rilancio del confronto competitivo, il CIG al quale fare riferimento per accedere al FVOE è quello dell’appalto o dell’affidamento specifico.
Non è previsto che la stazione appaltante aderente possa accedere al contenuto del FVOE della Convenzione/AQ di origine. Il fascicolo dell'appalto specifico viene popolato non appena necessario con la documentazione più aggiornata disponibile sull'operatore economico, eventualmente proveniente dal fascicolo dell'accordo quadro/convenzione, che in linea generale potrebbe essere di scarsa o nulla utilità per l'aderente.
