### ISSUE TITLE
Scheda RSU1: Subappalti a raggruppamenti di imprese e CF ditta subappaltatrice

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#308]
Nella scheda RSU1 c'è Codice fiscale ditta subappaltatrice
Come bisogna comportarsi nel caso di subappalto a raggruppamento di imprese? Va indicato il c.f. della mandataria, senza nessun riferimento alle mandanti?

**Comment by lelio-raffaelli** [comment]
E' possibile avere una risposta a questa issue aperta 70 giorni fa, per favore?

**Comment by anac-uscp** [comment]
Al momento è possibile indicare un unico codice fiscale (mandataria). Il modello dati sarà rettificato per consentire l'inserimento di più codici fiscali con un nuovo rilascio non ancora programmato
