### ISSUE TITLE
DMN regole di validazione - Scheda P1_16

### ISSUE THREAD

**Issue by sfala** [anticorruzione/npa#311]
Facendo riferimento alla issue #288 vorrei conferma che il DMN per la scheda in oggetto è scritto per il server ANAC che elabora la richiesta e non per il client (piattaforma) che invia la scheda. Questo giustificherebbe la presenza nel DMN di regole di validazione per _appalto.datiBaseProcedura_ all'interno del _anacForm_ ( tipo AnacFormP1_16Type), nonostante nella struttura non sia presente _appalto.datiBaseProcedura_ perchè gli stessi dati sono già presenti nel _eform_ (in cui si allega un eForm che viene comunque validato secondo sue regole).

Grazie

**Comment by supportoAnac** [comment]
Si conferma che sono regole che vengono applicate da ANAC per la validazione dei dati. Servono però anche al client come documentazione di riferimento per l’inserimento corretto dei dati di input. È vero che l’eForm viene validato secondo sue regole, ma in caso di pubblicazione nazionale vengono comunque applicate le regole di validazione dati ANAC per i dati comuni presenti nell’eForm.
