### ISSUE TITLE
Schede di tipologia AD - Crea-appalto e affidamenti diretti: CIG ottenuto dopo l'aggiudicazione

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#316]
La domanda è relativa a tutte le schede di tipologia AD. Il servizio crea-appalto, per quanto riguarda gli affidamenti diretti e diversamente da tutte le altre tipologie, richiede l'invio (se pur non obbligatorio) dei dati relativi ai partecipanti. 
**Scenario 1**: invio il crea-appalto di un AD quando so già quali sono i partecipanti; ne consegue che otterrò il CIG solo a procedura di affidamento già conclusa/affidata. **È corretto?**
**Scenario 2**: essendo l'invio dei partecipanti opzionale, potrei decidere di non inviarli con la scheda AD, ottenendo in questo modo il CIG a procedura ancora in corso. Se però procedessi in questo modo, sarei impossibilitato all'invio della successiva scheda (come da orchestratore) SC1, che mi richiede l'invio dell'id partecipante, che ad ANAC non ho mai inviato. **Come devo comportarmi a questo punto?**

**Comment by supportoAnac** [comment]
Nell’ultima versione rilasciata i partecipanti sono obbligatori per tutte le schede AD*.
Si ritiene dunque di confermare lo scenario 1 proposto.
