### ISSUE TITLE
Schede AD - Informazioni sui lotti

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#318]
Nelle schede di tipo AD, come mai non sono definite le informazioni dei lotti? Anche se si trattasse di un affidamento diretto a singolo lotto, in ogni caso la scheda non comprende informazioni come lottoIdentifier (che viene chiesto nei dati di aggiudicazione), categoria, categorieMerceologiche, CCNL, oggetto, importo, ecc.

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 24/11/2023.
