### ISSUE TITLE
PCP - Utilizzo PassOE

### ISSUE THREAD

**Issue by mariottola** [anticorruzione/npa#319]
Dopo l’introduzione della piattaforma PCP, come verrà utilizzato il PassOE? I campi idPartecipante e idGruppo inseriti nelle schede relativamente ai dati dei partecipanti sono relativi a dati già in possesso di ANAC perché relativi ai fornitori che hanno generato un PassOE per il determinato CIG? E se sì, come è possibile ottenere queste informazioni (che in alcuni casi possono servire anche prima dello stacco del CIG, come nelle schede AD)?

**Comment by mpizziconi** [comment]
PCP non prevede l'uso del PassOE.
Gli identificativi idPartecipante e idGruppo sono stabiliti dalla piattaforma chiamante secondo la semantica prevista dalle specifiche.
