### ISSUE TITLE
Policy di sicurezza - Restrizioni token JWS

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#321]
Le web api rispondono unautorized, immagino che siano state pubblicate le restrizioni sulle policy di sciurezza del token JWS.
Si potrebbero avere i set di dati per procedere con i test 

	userCodiceFiscale 
	cod fiscale della SA
	cod ausa della SA
o	regCodicePiattaforma
o	regCodiceComponente

nonchè identificativo dell'header aggiuntivo ( JWT-TrackingEvidence????)per il token JWS come definito nelle specifiche di pagopa https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher (paragrafo 6).

**Comment by sfala** [comment]
Ci aspettiamo che, come da roadmap, i controlli siano contenuti fino al 16/10/2023 ma intanto anche noi riceviamo "401 Unauthorized".

**Comment by FedericaSicchiero** [comment]
Grazie della segnalazione, lato PDND controlliamo e torniamo con una risposta

**Comment by FedericaSicchiero** [comment]
con quale ente state provando a staccare il token?

**Comment by FedericaSicchiero** [comment]
Allora lato PagoPA risulta che tutte le chiamate sono lecite e quindi l'errore 401 è una cosa che deve chiarire ANAC. Ho messo quella label alla issue in modo che possano rispondere.

**Comment by FedericaSicchiero** [comment]
Buongiorno,
mi potete confermare se avete fatto richiesta di certificazione ad AgID con esito positivo per poter accedere a PDND? Perchè l'assegnazione dell'attributo necessario all'accesso per il servizio erogato da ANAC avviene solo a valle della richiesta di certificazione ad AgID e della iscrizione al registro dei gestori delle piattaforme di ANAC.
PDND riceve l'autorizzazione ad assegnare questo attributo solo a conclusione, con successo, di questo processo.
