### ISSUE TITLE
JWS - Verifiche di base sui servizi PDND: Status 401 Unauthorized

### ISSUE THREAD

**Issue by stefanodabbrunzo** [anticorruzione/npa#322]
Salve,
come da roadmap abbiamo ultimato l'implementazione ed integrazione del token addizionale JWS, come da specifica.
Nella giornata odierna abbiamo eseguito vari test di integrazione ma riscontriamo che i servizi richiamati, nello specifico "**crea appalto**", ritorna sempre lo status "**401 Unauthorized**".

In calce vi riporto gli step che abbiamo eseguito:

**1.** **Generazione JWS come da specifica condivisa** : in calce l'ultimo jws generato per il test delle 20:24
`eyJraWQiOiJNTExadVF1TnlkaFQyZDdrU3lyUzVhWFo4amtER2pWS3NfRGs4aHpXRTRrIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2OTY3ODkyNjcsIm5iZiI6MTY5Njc4OTI2NzI2OCwiZXhwIjoxNjk2NzkyODY3LCJqdGkiOiJhZmJhZjAyNS0yYzlkLTQ0NGQtODk2YS0xODc3NTdlYTk3N2YiLCJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L0NvbXVuaWNhQXBwYWx0by92MSIsInVzZXJDb2RpY2VGaXNjYWxlIjoiQUFBQUFBMDBBMDFINTAxWiIsInVzZXJSb2xlIjoiUlAiLCJ1c2VyTG9hIjoiMyIsInVzZXJJZHBUeXBlIjoiU1BJRCIsIlNBQ29kaWNlRmlzY2FsZSI6IjExMTExMTExMTE1IiwiU0Fjb2RpY2VBVVNBIjoiMDAwMDAwMDAwIiwicmVnQ29kaWNlUGlhdHRhZm9ybWEiOiIwMDAwMDAxIiwicmVnQ29kaWNlQ29tcG9uZW50ZSI6IjAwMDAwMDEiLCJidXNpbmVzc0Zsb3dJRCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMCIsInRyYWNlSUQiOiJkMDQzMDE1Ny00ZjY1LTQxYWYtYmM4ZC1lMGNkZTVkOGVkMjIiLCJzcGFuSUQiOiIyZTIyMDE5Zi1kMjUxLTQ4NmMtYmEzNy01YmIxZGMxNDYwZjAifQ.fp9If3dQSytYpbdQ_Ktbbo9w1df6JaHELdFpIr6pBv384xXYsocWQqeh1kZoCN8oTYi9YwtG890m7YmxqHEzNrYs-GhUlynfJtk_4EKA4sE2NyT1ky7vY8wAgjfABN95TzfI1fHn_1cnhRL0AMxOoJGysVT8pBfLLSVf9yLthrXwAS4qUW2YWmtz3flslPQBHn1Ow0VE9s-FCsTZ62JTjBbe_5Yn7uyvBvOSeOlNk9_QsMYh0DlS6iEipgaeSuofKHvlswDWxOe_i-fu0v4QBPmDxKmZZ7zaa7ZjZmDsPlw6HuX-S3K2JXKR4NAOrSqosSDljZec1JawFh2A32iXog`

**2.** **Hashing del jws token generato**
`4b00e78aed1e1a0d6b2269155e50e4a84c1116c7a130b7731b713f40cdf20b5fd`

**3.** **Generazione client assertion per la finalità "Comunica Appalto"**
`eyJraWQiOiJNTExadVF1TnlkaFQyZDdrU3lyUzVhWFo4amtER2pWS3NfRGs4aHpXRTRrIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJjYzcwZjczNC04YTY3LTQyMGQtOGQwYi04MjEyZWYxZTkzYzEiLCJzdWIiOiJjYzcwZjczNC04YTY3LTQyMGQtOGQwYi04MjEyZWYxZTkzYzEiLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwicHVycG9zZUlkIjoiOGVjMWNiMWQtZGQ4Mi00OGZkLThhM2MtNDhkNzlmZTM1MTRjIiwianRpIjoiN2MyYjI3N2ItMTU2YS00N2ZlLTkyZGMtMDE0NzgwN2UxMGU0IiwiaWF0IjoxNjk2Nzg5MzEzLCJleHAiOjE2OTY3OTI5MTMsImRpZ2VzdCI6eyJhbGciOiJTSEEyNTYiLCJ2YWx1ZSI6IjRiMDBlNzhhZWQxZTFhMGQ2YjIyNjkxNTVlNTBlNGE4NGMxMTE2YzdhMTMwYjc3MzFiNzEzZjQwY2RmMjBiNWYifX0.Lneho3ZZLbbIVrIt0W7Rbf7z5Z1DHcdslpZMbgObFyjKJO-5KIQx_e1t1_bigjrhuMCtFg1wJdXsyiX1tUcoqqHhPVL71J-8ntmufu_jEyTJZFB6OxPFnQO_P7tuZxQKHxQyNrnwi-EyaDKyQib0-IqYuuJ0B38D-uEbTCABZg2hcz9vXPmg8msJ-bPE0U3UkE2WIw2G18APd-R3_QGl0t-ZIg3IwEq6No1qo-uumRjF2cKSMiVL8Vj6Us5ulpmVGpNrCDWIziKpJ-O48o34lnIdNh7wbJACtu7NEnZ_DpzGrVNY3lPv2jDQdy5QgDxP-KQtLEAUNK11xp8LdwgsWg
`
**4.**  **Richiesta voucher a PDND**: Access token generato correttamente da PDND
`eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L0NvbXVuaWNhQXBwYWx0by92MSIsInN1YiI6ImNjNzBmNzM0LThhNjctNDIwZC04ZDBiLTgyMTJlZjFlOTNjMSIsIm5iZiI6MTY5Njc4OTI4NCwiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiNGIwMGU3OGFlZDFlMWEwZDZiMjI2OTE1NWU1MGU0YTg0YzExMTZjN2ExMzBiNzczMWI3MTNmNDBjZGYyMGI1ZiJ9LCJwdXJwb3NlSWQiOiI4ZWMxY2IxZC1kZDgyLTQ4ZmQtOGEzYy00OGQ3OWZlMzUxNGMiLCJpc3MiOiJ1YXQuaW50ZXJvcC5wYWdvcGEuaXQiLCJleHAiOjE2OTY3OTI4ODQsImlhdCI6MTY5Njc4OTI4NCwiY2xpZW50X2lkIjoiY2M3MGY3MzQtOGE2Ny00MjBkLThkMGItODIxMmVmMWU5M2MxIiwianRpIjoiNzgxM2JkMGUtN2MwOC00Nzg5LWIxNTItYjU0YzY4YzkwMTQ5In0.xyhiUmZiYNbS_KnYKovpKYTc6NHsFTQALzH_T2_rUPoMBvN_ydFum-vGt-A_qVWerBSMy5fdUz-sBSfkDbvxPNQga1r1oWt3ltOoMTfcW3iDkUKKdtcR8YXB8QwcTM_MuV-TX7QskGEBYeFgUpZuSbDC3_McwFdVQuvLTjpb6MStsmlXzIEg_65mTOsDNxjWRqVLOgyS7XGRCHy7sToKmdHemFUnr4M9JT3wKbyOj7O0Rh0vFGMFovg3LC3mW-Nkun7MxLhWUOZ36lx9b3zSICqCFoY0tzX8UVV2kkvjrQzZQ2GKegVbdp5yuLBw8LcnGyhRHDWsfyp_QE5upTCsjw`

**5.**  **Sottomissione richiesta "Crea Appalto"** : nellheader della request abbiamo popolato il tag "**Authorizazion**" con il **"Bearer + access token generato da PDND"** ed il tag **"Agid-JWT-TrackingEvidence"** con il valore del jws token generato e postato al punto 1.

Il risultato che otteniamo nel sottomettere la suddetta request è "401 Unauthorized":
![image](https://github.com/anticorruzione/npa/assets/147341480/599235b4-46bc-43d5-b9dc-da48653b857c)

Vi inoltro in allegato la request sottomessa a livello di codice + i vari token generati decodificati dove si evince che i campi previsti dalla specifica risultano popolati.

Restiamo in attesa di un vostro riscontro quanto prima in merito  e delucidazione di come mai riscontriamo tale errore.

[jsw.txt](https://github.com/anticorruzione/npa/files/12841459/jsw.txt)

[client_assertion.txt](https://github.com/anticorruzione/npa/files/12841488/client_assertion.txt)

[access_token.txt](https://github.com/anticorruzione/npa/files/12841456/access_token.txt)

[request.txt](https://github.com/anticorruzione/npa/files/12841460/request.txt)

**Comment by sfala** [comment]
Anche noi riceviamo in risposta  "401 Unauthorized"

**Comment by stefanodabbrunzo** [comment]
Salve,
in aggiunta alle evidenza riportate sopra, vi inoltro screenshot della lista dei campi valorizzati come da specifica:
Da specifica i campi obbligatori del body risultano:
<img width="194" alt="image" src="https://github.com/anticorruzione/npa/assets/147341480/7b28464a-804b-4878-bc29-8448270bdb6d">

Di seguito vi riporto gli attributi valorizzati nella generazione del body.
<img width="529" alt="image" src="https://github.com/anticorruzione/npa/assets/147341480/c7369640-3742-472b-97ea-4f9ebddb0364">

**Comment by paolo-urbanetto** [comment]
Confermiamo che anche noi riceviamo in risposta "401 Unauthorized"

**Comment by FedericaSicchiero** [comment]
Grazie della segnalazione, lato PDND controlliamo e torniamo con una risposta.

**Comment by FedericaSicchiero** [comment]
Con quale ente state provando a staccare il token?
Faccio presente che per questioni di sicurezza non si dovrebbero pubblicare in una repository pubblica client assertion, digest, richieste di token potenzialmente valide

**Comment by labruno** [comment]
Ciao 
 Cortesemente potete confermarci (oppure correggere )  i punti sotto  ?

1)	EndPont AGID da richiamare per staccare il voucher è **https://auth.uat.interop.pagopa.it/token.oauth2**
2)	Endpoit dell’e-service “PCP - Comunica appalto” è  https://apigw-**test.anticorruzione.it/modi/rest/ComunicaAppalto/v2**
3)	Claims del JWS sono  :
a.	**Header**

> i.	Kid
> ii.	Alg
> iii.	Typ


**b.	Body**

> i.	iat
> ii.	nbf
> iii.	exp
> iv.	jti
> v.	aud
> vi.	userCodiceFiscale
> vii.	userRole
> viii.	userLoa
> ix.	userIdpType
> x.	SACodiceFiscale
> xi.	SAcodiceAUSA
> xii.	regCodicePiattaforma
> xiii.	regCodiceComponente
> xiv.	businessFlowID
> xv.	traceID
> xvi.	spanID


4)	l’Hashing sha256  del JWS ( opportunamente firmato con chiave privata con Encoding RS252  ) deve essere inserito nel campo **“digest”** del JWT firmato sempre con la medesima chiave privata con Encoding RS252.  
5)	Nell’header della chiamata “crea-appalto”, in aggiunta alla chiave  authorization bearer valorizzata con il voucher di AGID, va inserita una seconda **“Agid-JWT-TrackingEvidence”** il cui valore è il  JWS.

**Comment by FedericaSicchiero** [comment]
@labruno :

1. sì, ricordo che però noi siamo PagoPA e le conferme lato AGID bisognerebbe chiederle a loro
2. a questo deve rispondere ANAC
3. anche qui deve rispondere ANAC; i claim richiesti dovrebbero essere inseriti nella documentazione dell'e-service che hanno messo in collaudo
4 e 5. sì, per sicurezza noi abbiamo messo a disposizione una [guida dedicata](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#trasmettere-e-tracciare-dati-complementari-alla-richiesta) all'integrazione del digest

**Comment by FedericaSicchiero** [comment]
In ogni caso lato PagoPA risulta che tutte le chiamate sono lecite e quindi l'errore 401 è una cosa che deve chiarire ANAC. Ho messo quella label alla issue in modo che possano rispondere.

**Comment by stefanodabbrunzo** [comment]
Salve,
abbiamo conferma lato ANAC che i claims del JWS sono corretti e che l'endpoint di ANAC è quello indicato al punto 2.

Sbagliavamo l'endpoint ANAC.

Adesso, riceviamo da ANAC 400 
<img width="415" alt="image" src="https://github.com/anticorruzione/npa/assets/147341480/6ee6d352-9f1f-449a-abb1-910f1b65cc10">

Come mai?

**Comment by mpizziconi** [comment]
buon pomeriggio,
gli eService per la certificazione delle piattaforme possono essere acceduti solo dai gestori iscritti nel registro delle piattaforme certificate.

**Comment by mpizziconi** [comment]
vedi anche 
https://github.com/anticorruzione/npa/issues/310

**Comment by paolo-urbanetto** [comment]
Quindi è necessario presentare istanza ad AgID come da "schema operativo", attendere l'iter e fino ad allora non si accede più?

**Comment by mpizziconi** [comment]
> Quindi è necessario presentare istanza ad AgID come da "schema operativo", attendere l'iter e fino ad allora non si accede più?

Corretto
