### ISSUE TITLE
Dettaglio schede relative alle IDM

### ISSUE THREAD

**Issue by mirellaricca** [anticorruzione/npa#323]
Buongiorno,
quali sono le schede relative alle IDM (Indagine di mercato)? 
L'orchestratore presente su github: https://github.com/anticorruzione/npa/blob/main/docs/orchestratore/schema-cronologia-schede.xlsx
**non** fornisce questo dettaglio. 

Grazie

**Comment by anac-uscp** [comment]
Le schede relative alle IDM sono: P7.1.1, P7.1.2, P7.1.3, P7.2
