### ISSUE TITLE
DGUE obbligatorio per le schede relative alle IDM 

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#325]
Salve,
rispetto alla risposta fornita nella issue #128 è da considerare obbligatorio il DGUE anche per le schede relative all'indagine di mercato?

Grazie

**Comment by supportoAnac** [comment]
Le schede relative all’avvio dell’indagine di mercato, ovvero P7_1_1, P7_1_2, P7_1_3, non prevedono ESPD.
