### ISSUE TITLE
Scheda p2_12 e p2_20 - Aggiornamento nomenclatura

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#326]
Salve,

All'interno di github : https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/schede/modello-dati-schede-P2.20.yaml
https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/schede/modello-dati-schede-P2.12.yaml
sono state aggiornate queste due schede:

 **PRIMA:** 

Scheda P2_12 - Scheda di pubblicazione avviso per un bando di gara sottosoglia maggiore di 5K - **Avviso di preinformazione utilizzato come avviso di indizione di gara** — direttiva generale, regime alleggerito. Articolo 75, paragrafo 1, lettera b), della direttiva 2014/24/UE.

 

Scheda P2_20- Scheda di pubblicazione avviso per un bando di gara sottosoglia maggiore di 5K - **Bando di gara** — direttiva generale, regime alleggerito. Articolo 75, paragrafo 1, lettera a), della direttiva 2014/24/UE.

 

**ADESSO:**

 Scheda P2_12 - **Scheda di pubblicazione avviso per un bando di gara sottosoglia.**

 Scheda P2_20- **Scheda di pubblicazione avviso per un bando di gara sottosoglia.**

Trattasi di un duplicato?
In caso contrario, quali sono le discriminanti/peculiarità tra le due schede?

**Comment by mirellaricca** [comment]
Si sollecita un riscontro

**Comment by mirellaricca** [comment]
Si sollecita un riscontro

**Comment by supportoAnac** [comment]
La descrizione e la normativa di riferimento sono state allineate con quanto indicato nel file di cronologia schede e si trovano come description nell’oggetto SchedaP2_12Type (_Avviso di preinformazione utilizzato come avviso di indizione di gara — settori ordinari, regime alleggerito. Articolo 127 decreto legislativo 36/2023. Articolo 128 comma 8 decreto legislativo 36/2023._) e SchedaP2_20Type (_Bando di gara — settori ordinari, regime alleggerito. Articolo 127 decreto legislativo 36/2023. Articolo 128 comma 8 decreto legislativo 36/2023._)
