### ISSUE TITLE
Abilitazione PDND - Tempistiche onboarding per gestori privati

### ISSUE THREAD

**Issue by collaudo5** [anticorruzione/npa#327]
Buongiorno,
segnaliamo che abbiamo effettuato diversi tentativi di **accesso alla PDND come gestori privati di Piattaforma E-Procurement** al seguente indirizzo: https://selfcare.pagopa.it/auth/login e che, nonostante fosse stata comunicata la possibilità di effettuare l’accesso come privati a PDND a partire dal 02/10/2023, e l’accesso agli ambienti di Collaudo a partire dal 09/10/2023, **ad oggi il portale PagoPA non consente di effettuare l’onboarding per tale categoria di utente ma esclusivamente per PA e Gestore di Servizi Pubblici** (print 1) e non come da “Guida all’Adesione”  (print 2 in calce).
 
Segnalo la priorità alta della tematica indispensabile per eseguire le attività necessarie di Test e Collaudo, soprattutto alla luce dei termini indicati dalla normativa AGID di 60gg a partire dalla ricezione dell’esito positivo della verifica dei requisiti per effettuare l’onboarding su PDND per l’esecuzione dei test di Interoperabilità.

**Chiediamo gentilmente di comunicare entro quando sarà possibile effettuare l’accesso come privati.** 

Grazie.

<img width="240" alt="image" src="https://github.com/anticorruzione/npa/assets/123168895/7fae0d58-9eb0-4864-8509-1de251d5fc83">

<img width="182" alt="image" src="https://github.com/anticorruzione/npa/assets/123168895/b8825f01-39f9-435c-bb8f-ade363b33bdb">

**Comment by FedericaSicchiero** [comment]
Buongiorno, lato PDND Interoperabilità siamo in attesa che ANAC ci comunichi la lista delle imprese private abilitate all'onboarding. Una volta che avremo la lista sarà possibile procedere con l'onboarding.

**Comment by mariottola** [comment]
Buongiorno, anche noi ci ritroviamo nella stessa situazione, ma la risposta che ci è stata data dall'assistenza di PagoPA è diversa da quella qui indicata:
"al momento non è ancora aperta l'adesione a PDND e-Procurement, lo sarà a breve ma non siamo a conoscenza di una data precisa. Suggeriamo di verificare nei prossimi giorni sul sito di onboarding di SelfCare questa possibilità."
Attendiamo comunque comunicazioni per poter procedere oltre e accedere ai servizi di test nel minor tempo possibile.

**Comment by FedericaSicchiero** [comment]
Buongiorno, si la risposta è un po' diversa ma il motivo è lo stesso. L'adesione non è ancora aperta perchè ci serve la lista fornita da ANAC per poterla aprire e come detto da Assistenza non siamo a conoscenza di una data precisa. Vi avviseremo appena sarà disponibile.

**Comment by dpagliari** [comment]
Buonasera,

purtroppo anche noi abbiamo lo stesso problema. Stiamo provando dal 9 Ottobre a fare il self onboarding alla PDND, Agid il 9 ottobre ha inviato la PEC per confermarci la verifica positiva dell'istanza di certificazione del componente con la checklist compilata, quindi sinceramente non capiamo che cosa manca e soprattutto quali sono i tempi previsti.
In questo modo si continua a perdere tempo a danno delle imprese private che devono sviluppare 'al buio' senza disporre di una piattaforma di test/collaudo e senza garantire parità di trattamento con le aziende della PA.

**Comment by marcocipri-pagopa** [comment]
l'abilitazione all'adesione su PDND avviene solo a valle della richiesta di certificazione ad AgID e della iscrizione al registro dei gestori delle piattaforme di ANAC.
PDND riceve l'autorizzazione all'adesione delle imprese solo a conclusione, con successo, di questo processo.
Vi invitiamo a accertarvi che la richiesta di certificazione ad AgID abbia esito positivo.

**Comment by dpagliari** [comment]
Buongiorno,
è esattamente ciò che sto sostenendo. Da lunedì 9 ottobre Agid ha comunicato via PEC la positiva verifica dell'istanza di certificazione e ad oggi non possiamo ancora abilitarci alla PDND.
Vedete un po' voi dove sta il problema

**Comment by FedericaSicchiero** [comment]
@dpagliari Agid vi ha confermato che la procedura è completata ma a noi manca il passaggio con ANAC (cioè la lista degli enti abilitati da Agid) e conseguenza abilitazione lato nostro. Finchè non riceviamo la lista non abbiamo la possibilità di farlo e quindi siete bloccati anche voi come enti. Stiamo sentendo chi di dovere per sbloccare la situazione.

**Comment by dpagliari** [comment]
Grazie per la risposta, possiamo sollecitare AGID in tal senso?

**Comment by FedericaSicchiero** [comment]
No perchè Agid il suo l'ha fatto, appena ANAC conclude la sua parte allora sarà tutto a posto.

**Comment by FedericaSicchiero** [comment]
Buongiorno,
lato PDND abbiamo abilitato le 5 piattaforme di e-procurement che hanno fatto richiesta ad Agid. Se voi siete tra quelle avete la possibilità ora di fare onboarding e fruire dei servizi.

**Comment by collaudo5** [comment]
Buongiorno,

abbiamo provveduto a fare l'onbording per fruire dei servizio PDND.

Grazie.
