### ISSUE TITLE
Scheda S1 - Richiesta CIG per pubblicazione indagine di mercato

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#328]
Buongiorno,
esaminando i dati da inviare con questa scheda rileviamo che il CIG è obbligatorio.
Tale informazione è gestibile per le procedure bifasiche (ad esempio procedura ristretta e competiva con negoziazione) in quanto il CIG viene staccato sin da subito.
Diverso è il caso in cui una SA proceda a pubblicare una Indagine di mercato. In quel caso, fino ad oggi non è stato necessario richiedere preventivamente un CIG. 
Se la scheda S1 deve gestire anche le indagine di mercato, allora la SA deve richiedere un CIG per pubblicare una indagine di mercato?

**Comment by anac-uscp** [comment]
Per le schede 7.1 (ossia 7.1.1, 7.1.2, 7.1.3) e 7.2, la risposta è sì, l’avvio dell’indagine di mercato prevede il rilascio del CIG.
