### ISSUE TITLE
Schede P2_10 e P2_16 - Parametro di distinzione 

### ISSUE THREAD

**Issue by mirellaricca** [anticorruzione/npa#329]
Nell'orchestratore, per la tipologia : OR/SS/RO :

- Scheda P2_10 - Scheda di pubblicazione avviso per un bando di gara sottosoglia. Avviso di preinformazione utilizzato come avviso di indizione di gara — settori ordinari. Articolo 50,  decreto legislativo 36/2023. Articolo 81 comma 2 decreto legislativo 36/2023.

-  Scheda P2_16 - Scheda di pubblicazione avviso per un bando di gara sottosoglia.Bando di gara — settori ordinari. Articolo 50 comma 1 lettera d) decreto legislativo 36/2023.

e' possibile avere un parametro funzionale che ci permetta di distinguere le due schede?

Grazie

**Comment by mirellaricca** [comment]
Si sollecita un riscontro

**Comment by anac-uscp** [comment]
Cosa si intende per 'parametro funzionale'?
Sebbene il contesto normativo sia il medesimo, una scheda riguarda l'avviso di preinformazione utilizzato come avviso di indizione di gara, l'altra invece riguarda il bando di gara.
