### ISSUE TITLE
ESPD per schede AD e obbligo DGUE

### ISSUE THREAD

**Issue by mirellaricca** [anticorruzione/npa#332]
Salve,
dalle schede presenti su github, relative agli Affidamenti diretti (nello specifico: AD1_25 - AD1_26 - AD1_28 - AD2_25 -AD2_26 - AD2_28 e AD_5) **non** risulta obbligatorio il DGUE.

E' possibile avere conferma?

Grazie

**Comment by anac-uscp** [comment]
Il DGUE dovrebbe essere usato da 40.000 euro in su anche se il Codice non ne impone espressamente l’uso negli affidamenti diretti.
Sono le linee guida del MIT sul DGUE (pubblicate il 30 giugno 2023) che stabiliscono che, per gli affidamenti diretti di importo inferiore a 40.000 euro, la stazione appaltante ha facoltà di scegliere se predisporre un modello semplificato di dichiarazione oppure se adottare il DGUE. Per importi superiori bisogna usare il DGUE.  Del resto, in futuro il DGUE sarà l’unico strumento con cui verrà attivato il FVOE per le verifiche, per questo ha senso prevederne l’uso in modo ampio.

**Comment by SoricchioHRS** [comment]
Al momento quando carico la AD5 oppure una AD3 il DGUE, sebbene facoltativo, dovrebbe consentirmi di l'accesso al FVOE. Tuttavia, quando lo inserisco, l'autorizzazione alla visione del FVOE aggiudicatario mi viene negata.
La PCP\FVOE 2.0 rilascia il seguente messaggio: "STATO NON UTILIZZABILE".
I colleghi che non hanno caricato alcun DGUE, invece, riescono a ad avere l'autorizzazione, salco impossibilità di effettaure i controlli.
