### ISSUE TITLE
Schede A4 - Nome property `DatiBaseAggiudicazioneAppalto` post rilascio

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#333]
Vorrei segnalare che nelle schede A4 la property `DatiBaseAggiudicazioneAppalto` è definita in modo errato, ad esempio `datibaseAggiudicazioneAppalto` (non camel case). Nelle schede A2 ad esempio è in camel case (usano comunque lo stesso type)

**Comment by supportoAnac** [comment]
Segnalazione corretta, verrà modificata la label secondo il camel case.
