### ISSUE TITLE
SCHEDE P2_11 E P2_17 - Parametro di distinzione

### ISSUE THREAD

**Issue by mirellaricca** [anticorruzione/npa#334]
Per le Schede :

- Scheda P2_11 - Scheda di pubblicazione avviso per un bando di gara sottosoglia. Avviso periodico indicativo utilizzato come avviso di indizione di gara — settori speciali. Articolo 50 decreto legislativo 36/2023. Articolo 50 comma 5 decreto legislativo 36/2023.
- Scheda P2_17 - Scheda di pubblicazione avviso per un bando di gara sottosoglia. Bando di gara — settori speciali. Articolo 50 decreto legislativo 36/2023. Articolo 50 comma 5 decreto legislativo 36/2023

e' possibile avere un parametro funzionale che ci permetta di distinguere le due schede?

**Comment by anac-uscp** [comment]
Cosa si intende per 'parametro funzionale'?
Sebbene il contesto normativo sia il medesimo, una scheda riguarda l'avviso periodico indicativo; l'altra il bando di gara.
