### ISSUE TITLE
PCP codeList - Attributi richiesti per la fruizione 

### ISSUE THREAD

**Issue by vbeneduce** [anticorruzione/npa#335]
Salve,
come ente "Regione Lazio" richiedendo, dalla piattaforma PDND, la fruizione del contesto "PCP – codeList" si viene bloccati dal messaggio “Il tuo Ente non ha gli attributi certificati necessari per iscriversi” (allego screenshot del messaggio)

Per gli altri contesti della piattaforma PCP il processo si è concluso con la conferma di fruizione. Potreste verificare il motivo di tale differenza di comportamento?

![image](https://github.com/anticorruzione/npa/assets/147526851/508c0747-5740-442f-a4e1-971fcd5b0757)

grazie.

**Comment by marcocipri-pagopa** [comment]
l'assegnazione dell'attributo necessario all'accesso per il servizio erogato da ANAC avviene solo a valle della richiesta di certificazione ad AgID e della iscrizione al registro dei gestori delle  piattaforme di ANAC.
PDND riceve l'autorizzazione ad assegnare questo attributo solo a conclusione, con successo, di questo processo.
Al Momento la vostra amministrazione non ci risulta iscritta al registro dei gestori delle  piattaforme di ANAC.
Vi invitiamo a accertarvi che la richiesta di certificazione ad AgID abbia esito positivo.
