### ISSUE TITLE
CIG e Campi `idContratto` per accordo quadro e `idPartecipante` con più aggiudicatari

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#338]
Nella struttura di una scheda il campo `cig` è un array e il campo `idContratto` è una stringa, quindi, esiste  una relazione tra i due campi, molti ad uno ovvero per ogni `idContratto` possono essere presenti diversi `cig`. Come viene tracciato il caso di accordo quadro?

Se per uno stesso `cig` possono esserci più aggiudicatari, perché il campo `idPartecipante` è una stringa piuttosto che un array?

**Comment by anac-uscp** [comment]
L'AQ viene tracciato considerando le specifiche schede di adesione ad AQ/convenzione dove viene indicato il CIG dell'AQ a monte.
A ogni idcontratto possono corrispondere più CIG ma la sottoscrizione del contratto viene effettuata con un solo partecipante. In caso di più aggiudicatari, ci sarà un contratto per ogni aggiudicatario.
