### ISSUE TITLE
SPID / CIE - Ambito di utilizzo (obbligatorietà)

### ISSUE THREAD

**Issue by teslb** [anticorruzione/npa#339]
Si chiede conferma circa l'obbligatorietà di utilizzo dei sistemi di identificazione elettronica (SPID/CIE) sia per gli utenti interni (es: Buyer SA) sia esterni (es: OE).

Si chiede altresì conferma se per quanto riguarda lo SPID si debba trattare esclusivamente di SPID associato a persona giuridica oppure sia a persona giuridica sia a persona fisica.  

Questo in considerazione del fatto che l'utilizzo della CIE sia al momento disponibile per sole persone fisiche

**Comment by mpizziconi** [comment]
Il level of assurance adottato dalla piattaforma per l'identificazione dell'utente deve essere di livello 3 o 4.
L'utente è il soggetto fisico che interagisce con PCP, gli utenti che partecipano al flusso di business della piattaforma e non interagiscono con PCP non rispondono al requisito

Il tipo di identity provider utilizzato per stabilire l'identità dell'utente può essere:
            - "SPID"
            - "CIE"
            - "CNS"
            - "EIDAS"
            - "CUSTOM" # sistema interno al gestore della piattaforma certificata

**Comment by teslb** [comment]
@mpizziconi SPID e CIE risultavano comunque dover essere obbligatori mentre dalla risposta sopra appaiono come opzionali a patto che anche una soluzione CUSTOM fintanto che permetta un grado di sicurezza pari a livello 3 o 4.  E' corretta tale interpretazione?

**Comment by mariottola** [comment]
si conferma perciò che i fornitori - che non interagiscono con PCP - non sono obbligati ad accedere con SPID, CIE o altro identity provider non custom?

**Comment by mpizziconi** [comment]
la soluzione CUSTOM deve essere certificata nell'ambito del processo di certificazione della piattaforma come aderente ai requisiti LOA 3 e 4

**Comment by mpizziconi** [comment]
Gli OE accedono alla PCP per il tramite della UI esposta per la gestione del FVOE, le modalità di accesso in base al livello di sicurezza e certezza dell'identità associato alle azioni compiute sulla piattaforma e possono richiedere l'uso di strumenti di LOA 3

**Comment by mpizziconi** [comment]
Annotazione di metodo
le risposte alle issue vengono fornite da diversi soggetti appartenenti a gruppi/amministrazioni differenti che si concentrano su quelle in stato Open e che possono utilizzare utenze istituzionali condivise.
è opportuno non commentare issue già chiuse ma riproporre quesiti di approfondimento come nuove istanze, preferibilmente citando quella chiusa
