### ISSUE TITLE
Orchestratore - Scheda S1

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#341]
La scheda S1 si riferisce all'elenco invitati/partecipanti alla prima fase di una gara in due fasi.
Al termine della prima fase si procede con la pubblicazione dell'invito a tutti i soggetti ritenuti idonei.
Nell'orchestratore viene indicata, come scheda successiva, la S2 che, invece, si ritiene debba essere utilizzata a valle della scadenza dei termini dell'invito.
E' possibile avere un chiarimento in merito?
Inoltre è corretto considerare sempre la scheda S1 per la prima fase e la S2 per la seconda fase e per le gare monofasiche??

Grazie

**Comment by paolo-urbanetto** [comment]
Mi permetto di aggiungere: la trasmissione delle schede S1 e S2 deve essere tempestiva o può essere fatta prima dell'aggiudicazione?

**Comment by anac-uscp** [comment]
Nelle gare a due fasi va inviata prima la scheda S1 e successivamente la S2.
A valle della scadenza dei termini della manifestazione di interesse deve essere inviata la scheda S1 con l'elenco dei soggetti che hanno manifestato interesse.
Successivamente, con la scheda S2, si fornisce l’elenco dei soggetti effettivamente invitati e la data di scadenza per la presentazione delle offerte.
Nelle gare a fase unica va inviata prima la sola scheda S2 con l’indicazione dei partecipanti e la data di scadenza per la presentazione delle offerte.
Entrambe le schede devono essere trasmesse prima dell’aggiudicazione.
