### ISSUE TITLE
Endpoint Flow Schede

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#342]
Ricordo che tempo fa si parlò dell'implementazione di un endpoint che restituisse i dati contenuti dentro l' [xlsx](https://github.com/anticorruzione/npa/blob/main/docs/orchestratore/schema-cronologia-schede.xlsx) elaborati in modo tale da esporre il flow delle schede.

Sarebbe molto utile un endpoint di questo tipo, che magari preso in input un codice scheda esponga la lista delle possibile schede successive.
Ipotizzando l'implementazione di una state machine (sempre che non esista già) con le varie transizioni di stato e i vari controlli su di esse, e l'implementazione di un endpoint che restituisca appunto le transizioni ammesse si potrebbe creare un layer di validazione per una user experience e una dev experience migliore.

Se non fosse possibile l'implementazione di un endpoint di questo tipo, sarebbe comodo almeno avere il flow delle varie schede descritto con una sintassi language-agnostic

**Comment by mpizziconi** [comment]
Lo sviluppo del servizio è stato preso in carico ma non non schedulato; non ne è previsto il rilascio prima di giugno 2024
