### ISSUE TITLE
Scheda S3 - Tempistiche trasmissione

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#343]
La scheda S3 contiene gli incarichi tecnici e le prestazioni progettuali.
Questi possono essere nominati in diverse fasi dell'appalto, fino al collaudo.

Quando va trasmessa la scheda? 
Ne va trasmessa una ogni volta che c'è una variazione? E nel caso di nuove nomine, vanno comunicati solo i nominativi aggiunti?

**Comment by lelio-raffaelli** [comment]
Chiedo cortesemente un riscontro, grazie

**Comment by anac-uscp** [comment]
La scheda S3 'Incarichi tecnici e prestazioni progettuali' raccoglie i dati relativi ai progettisti e agli incaricati tecnici e può essere inviata in qualsiasi momento. 
La scheda va trasmessa ogni volta che c'è una variazione e deve contenere l'elenco esaustivo degli incarichi fino a quel momento.
