### ISSUE TITLE
OE - Livello autorizzativo richiesto

### ISSUE THREAD

**Issue by teslb** [anticorruzione/npa#346]
Per quali figure (Ruoli) e in quali operazioni è necessario obbligatoriamente l'accesso da parte degli OE (Fornitori) attraverso SPID?

**Comment by teslb** [comment]
si sollecita un riscontro

**Comment by teslb** [comment]
si sollecita un riscontro

**Comment by teslb** [comment]
si sollecita un riscontro

**Comment by mpizziconi** [comment]
La issue è fuori contesto: la PCP non è mediata dalle piattaforme per l'erogazione dei servizi agli operatori economici.
