### ISSUE TITLE
Buyer - Livello autorizzativo richiesto

### ISSUE THREAD

**Issue by teslb** [anticorruzione/npa#347]
Per quali figure (Ruoli) e in quali operazioni è necessario obbligatoriamente l'accesso da parte dei Buyer attraverso SPID?

**Comment by teslb** [comment]
si sollecita un riscontro

**Comment by teslb** [comment]
si sollecita un riscontro

**Comment by teslb** [comment]
si sollecita un riscontro

**Comment by mpizziconi** [comment]
Gli utenti delle stazioni appaltanti per accedere ai servizi PCP devono avere un livello di autenticazione (verificato dalle piattaforme) pari a LOA 3. Per alcuni servizi può essere richiesto LOA 4 quando richiesto dalla normativa di settore (ad es. accesso alle informazioni antimafia)
