### ISSUE TITLE
Scheda 2.10 - Area e famiglia di appartenenza

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#348]
Buongiorno,

a seguito di visualizzazione della checklist certificazione dei componenti, non risulta chiaro a quale Area e famiglia bisogna ricondurre la scheda P2_10 "Avviso di preinformazione utilizzato come avviso di indizione di gara — settori ordinari" per la verifica del componente. Trattandosi di una preinformazione sottoglia va ricondotta nell'Area 1 famiglia 2 "Pianificazione Procedure (tutti i settori, sopra e sottosoglia)"?

**Comment by anac-uscp** [comment]
Area funzionale A_3, Famiglia di funzionalità P2
