### ISSUE TITLE
JWS &  : Richiesta di conferma delle specifiche e della  formattazione di  Header e Footer  JWT

### ISSUE THREAD

**Issue by labruno** [anticorruzione/npa#353]
1) Potreste confermarci che  le informazioni complementari da fornire **SONO TUTTE E SOLE** quelle inserite nell'header e nel body del JWT d'esempio sotto ?

```java
{
   "header":{
      "alg":"RS256",
      "typ":"JWT",
      "kid":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" // La chiave pubblica corrispondente a quella privata che userai per firmare l’asserzione
   },
   "payload":{
      "traceID":"eproc-2",// valore di esempio 
      "userIdpType":"SPID",// valore di esempio 
      "regCodiceComponente":"0000001",// valore di esempio 
      "userLoa":"3",// valore di esempio 
      "regCodicePiattaforma":"0000001",// valore di esempio 
      "SACodiceFiscale":"11111111115",// valore di esempio 
      "spanID":"npa.1",// valore di esempio 
      "aud":"auth.uat.interop.pagopa.it/client-assertion",// L'audience come descitto nel client e-service e come per specifica RFC7519
      "nbf":1697233784643,// come per specifica RFC7519
      "businessFlowID":"00000000-0000-0000-0000-000000000000",// valore di esempio 
      "exp":1697237383,// come per specifica RFC7519
      "userRole":"RP",// valore di esempio 
      "iat":1697233783,// come per specifica RFC7519
      "SAcodiceAUSA":"226120",
      "jti":"646d03b8-719d-45f4-854b-866e9a27d9eb",// come per specifica RFC7519
      "userCodiceFiscale":"BRNLCU76P02xxxxx"// valore di esempio 
   }
}
``` 
2) Il descrittore del body contenuto nel JWS ANAC per l'accesso ai servizi della piattaforma dei Contratti Pubblici via PDND,[specifiche NPA](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-jws/jws.yaml),  secondo lo standard [MODI audit_rest_01](https://govway.org/documentazione/console/profiloModIPA/messaggio/audit/audit01/audit_schema/index.html) recita che " _Le Linee Guida indicano che l’erogatore e il fruitore devono individuare i claim da includere nel JWT di audit “Agid-JWT-TrackingEvidence” e suggeriscono i seguenti dati che dovranno essere presenti nel token generato dal fruitore, per ogni richiesta effettuata:

- userID, un identificativo univoco dell’utente interno al dominio del fruitore che ha determinato l’esigenza della request di accesso all’e-service dell’erogatore;
- userLocation, un identificativo univoco della postazione interna al dominio del fruitore da cui è avviata l’esigenza della request di accesso all’e-service dell’erogatore;
- LoA, livello di sicurezza o di garanzia adottato nel processo di autenticazione informatica nel dominio del fruitore."

I valori per le chiavi userID,userLocation,LoA vanno quindi inseriti  ?

**Comment by supportoAnac** [comment]
Issue superata dalle successive specifiche pubblicate.
