### ISSUE TITLE
PDND Interoperabilità e JWS : richiesta chiarimenti sull'utilizzo dell'header Agid-JWT-TrackingEvidence

### ISSUE THREAD

**Issue by labruno** [anticorruzione/npa#354]
Potete confermarci che in quanto fruitori  dei servizi ANAC dobbiamo inserire il JWS che contiene le informazioni complementari all'interno di un secondo header denominato Agid-JWT-TrackingEvidence e che  il JWS dovrà essere inserito nell'header dopo essere stato codificato in base64  ?

Così come descritto allo [STEP 6](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#6.-il-fruitore-fa-una-richiesta-di-dati-allerogatore) del "flusso di dettaglio" del capitolo "Utilizzare i Voucher" delle  funzionalità descritte nelle [linee guida di AgID](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher)

**Comment by mpizziconi** [comment]
la chiave in header è corretta: Agid-JWT-TrackingEvidence
il contenuto NON deve essere codificato (di nuovo) in base64
la guida citata è stata aggiornata
