### ISSUE TITLE
Scheda S2 - Dati richiesti

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#356]
Buongiorno,
attualmente (SIMOG) la compilazione della scheda partecipanti prevede che i seguenti campi vengano compilati solo per l'aggiudicatario:

- avvalimento
- tipologiaAvvalimento
- impreseAusiliarie

Dall'analisi della scheda S2 appare che con l'introduzione della PCP, tali campi vengano richiesti per tutti i partecipanti. Confermate ?

**Comment by federicodemarco** [comment]
Buongiorno, chiediamo un riscontro uregente

**Comment by federicodemarco** [comment]
Si sollecita un riscontro

**Comment by anac-uscp** [comment]
Corretto. sulla PCP le informazioni sono richieste per tutti i partecipanti
