### ISSUE TITLE
CIG prelevati entro 31/12/2023 - Modalità di gestione del perfezionamento

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#357]
Confermiamo che sulla base della issue https://github.com/anticorruzione/npa/issues/162 il perfezionamento è compreso nel conferma appalto. Pertanto sembrebbe una sorta di perfezionamento automatico.

Rimaniamo però in atteda di capire come venga perfezionato un CIG prelevato prima del 01/01/2024. Vedi punto 1 della issue https://github.com/anticorruzione/npa/issues/230.
Dalle vostre risposte non si desume la modalità di gestione del perfezionamento dei CIG di questo tipo (prelevato prima del 01/01/2024).

Non ufficialmente ma nel corso dei vari incontri, mi pare che sul tavolo ci sia anche l'ipotesi per la quale un CIG prelevato prima del 01/01/2024 non possa essere perfezionato dopo tale data, in quanto l'indicazione è stata quella di utilizzarli tutti entro il 31/12/2023.

Vi chiediamo quale lo scenario che è stato configurato a partire dal 01/01/2024

**Comment by r-dm123** [comment]
Attenersi a provvedimento ANAC MIT in corso di emissione
