### ISSUE TITLE
Schede Fase Esecuzione (ad es. SA1)

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#358]
Trasmissione delle schede relative alla fase di esecuzione.
Es. Conclusione
Una volta trasmesse in inserimento - potranno essere trasmesse in modifica? 
Vale per tutte le schede?
Se non la modifica qual'è l'iter per modificare/aggiornare/correggere un dato?

**Comment by supportoAnac** [comment]
Per tutte le schede, comprese quelle di esecuzione, possono essere modificate fintanto che non vengono confermate.
