### ISSUE TITLE
Schede P1 - Informazioni su "Importo Lotto"

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#359]
Le schede P6.1 e P6.2 contengono l'oggetto datiBase con all'interno oggetto e importo del lotto.
Le schede P1 hanno un campo corrispettivo in cui inserire l'importo del lotto o non è previsto?

**Comment by anac-uscp** [comment]
Le schede P1 prevedono l'invio dell'eForm, tali informazioni (BT-24 oggetto, BT-27 importo) sono contenute nell'eform stesso.
Le schede P6 non prevedono l'eForm per cui le informazioni sono contenute nell'oggetto 'datiBase'.
