### ISSUE TITLE
Oggetto vuoto nello Swagger

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#360]
abbiamo riscontrato nello swagger la presenza di alcuni oggetti senza alcun campo all'interno 
(ad es., P6.1 ->lotto.datiBaseAggiudicazione).
Si tratta di un errore dello swagger? prevedete di eliminare questi oggetti dalla scheda?
<img width="304" alt="image" src="https://github.com/anticorruzione/npa/assets/142924847/4c2f8b1e-be76-4d5f-806d-4c3e1da4e446">

**Comment by mpizziconi** [comment]
Probabilmente è un difetto dell'editor che in visualizzazione non supporta troppi livelli di reference tra classi. 
Aprendo direttamente il file della scheda, senza passare dal servizio, il campo è visibile. Mentre il passaggio dal servizio aggiunge un livello ulteriore che non fa visualizzare il campo. Abbiamo verificato che le classi generate contengono correttamente i campi, ma in caso di molteplici livelli di reference può capitare che lo swagger non li visualizzi.
Il dato è visibile aprendo la scheda alla url 
https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-P6.1.yaml#/components/schemas/SchedaP6_1Type
