### ISSUE TITLE
Invio dati procedure prima e dopo il 01/01/2024

### ISSUE THREAD

**Issue by mfortini** [anticorruzione/npa#361]
Ad opera del nuovo codice dei contratti pubblici, dal 1° luglio 2023 l’art. 1, comma 32 della L. 190 è stato abrogato.

Allo stato attuale la norma di riferimento è l’art. 28 del D.lgs. n. 36/2023 ai sensi del quale è stata emanata una delibera dell’ANAC recante “individuazione delle informazioni e dei dati relativi alla programmazione di lavori, servizi e forniture, nonché alle procedure del ciclo di vita dei contratti pubblici che rilevano ai fini dell’assolvimento degli obblighi di pubblicazione di cui al decreto legislativo 14 marzo 2013, n. 33”. La suddetta delibera acquisterà efficacia dal 1° gennaio 2024.

Sulla scorta di quanto sopra, necessitiamo conoscere:

* se sia corretto intendere che dal 01/01/2024 la trasmissione non avverrà più tramite il formato .xml, ma attraverso le integrazioni con BDNCP;
* come verranno gestiti i dati delle procedure avviate prima del 01/01/2024, svolte e/o aggiudicate poi.

**Comment by MZN4M** [comment]
E' possibile avere riscontro?
Ns clienti chiedono informazioni su come verrà gestito il servizio di trasmissione dati.
Necessitiamo avere descrizione delle modalità.

**Comment by dpagliari** [comment]
Buongiorno,
potete rispondere e chiudere questa issue?

**Comment by collaudo5** [comment]
Buongiorno,

si richiede un riscontro in merito.

Grazie.

**Comment by dpagliari** [comment]
Buongiorno,

scusate l'insistenza ma i nostri clienti ci stanno chiamando per sapere cosa devono fare. Potete rispondere e chiudere l'issue e quelle collegate #551, #552
Grazie

**Comment by r-dm123** [comment]
- Corretto
- Attenersi a provvedimento ANAC MIT in corso di emissione
