### ISSUE TITLE
Scheda RSU1 - Gestione delle richieste di autorizzazione per il subappalto a cascata

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#362]
La composizione della scheda non consente l’invio di informazioni utili alla gestione delle richieste di autorizzazione per il subappalto a cascata, al momento nell’invio della richiesta di autorizzazione non è possibile indicare che la stessa è legata ad una richiesta già autorizzata in precedenza.

**Comment by anac-uscp** [comment]
Le modifiche relative al subappalto a cascata saranno inserite nel prossimo rilascio
