### ISSUE TITLE
Scheda ES1 - Gestione eventi revoca autorizzazione e annullamento autotutela

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#363]
Sulla scheda esito ES1 non sono presenti nel campo motivo del mancato subappalto le informazioni relative a due eventi: revoca autorizzazione e annullamento in autotutela, potete cortesemente aggiungere queste motivazioni nella tipologica?

**Comment by anac-uscp** [comment]
Nel prossimo rilascio sarà introdotto, nella scheda CS1 'conclusione subappalto',  il campo motivoMancataEsecuzioneSubappalto con la corrispondente tipologica motivoMancataEsecuzioneSubappalto.json contenente le voci 'revoca autorizzazione' e 'annullamento in autotutela'
