### ISSUE TITLE
S1 e S2: trasmissione singola o multipla

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#364]
le schede S1 e S2 prendono in input come dato obbligatorio il CIG. 
queste schede si riferiscono all'intera gara per cui vanno inviate una sola volta (in tal caso ci saremmo aspettati di trovare all'interno della stessa scheda una lista di oggetti per poter inserire le informazioni per più di un lotto) oppure è necessario inviare la S1/S2 per ciascun lotto? 

<img width="459" alt="image" src="https://github.com/anticorruzione/npa/assets/142924847/7b8f2865-9cfd-4104-95ed-a9827747f589">

**Comment by lauralu1993** [comment]
a valle di uno degli ultimi incontri ci è stato detto che le schede di selezione vanno inviate una sola volta. E che, nello specifico, potrebbe trattarsi di un errore dello swagger il fatto che il servizio non prende in input una lista. Chiediamo conferma e, eventualmente, sollecitiamo la risoluzione.

**Comment by supportoAnac** [comment]
Si rimanda alle issues  [#215](https://github.com/anticorruzione/npa/issues/215) e alla [#731](https://github.com/anticorruzione/npa/issues/731)
