### ISSUE TITLE
Errore 400 in chiamata crea-appalto

### ISSUE THREAD

**Issue by cragazzi** [anticorruzione/npa#365]
Buongiorno,
stiamo cercando di effettuare una chiamata crea-appalto, ma riceviamo errore 400. 
Riporto l'ultimo errore ricevuto (chiamata effettuata alle 12:14 circa):
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "79d16c50-6d90-11ee-b4a0-0050568e08b3"
}
L'errore è abbastanza generico. Potreste indicarci più in dettaglio che errore contiene la nostra chiamata?

Vi ringrazio.

**Comment by mpizziconi** [comment]
la richiesta è troppo generica per poter essere trattata. si richiede di fornire maggiori dettagli sulle modalità con cui viene effettuata la chiamata, contenuto del JWS 
Nel frattempo può essere utile quanto riportato nella https://github.com/anticorruzione/npa/issues/352
in particolare nel commento 
https://github.com/anticorruzione/npa/issues/352#issuecomment-1765975709

**Comment by cragazzi** [comment]
@mladuDPA 
Buonasera,
la ringrazio moltissimo di aver condiviso la sua soluzione con noi.
Ho rifatto una prova come da lei indicato:

- inserito il jws senza codifica base64;
- aggiunto il purposeId;
- lasciato il claim nbf, senza fare modifiche.

Non ho più ricevuto l'errore "InteroperabilityInvalidRequest", ma il nuovo errore "Argomenti di input non validi".

@supportoAnac @mpizziconi  
Vi chiedo se l'errore "Argomenti di input non validi" è dovuto agli errori contenuti nella scheda inviata nella chiamata crea-appalto. È così? Se sì, non vengono restituiti errori più dettagliati per individuare i problemi contenuti nella scheda?

Vi ringrazio.

**Comment by ferdinandjmaddela** [comment]
@mladuDPA e @cragazzi 
Buongiorno, 

Ho seguito le soluzioni condivise, ma purtroppo continuo a ricevere

```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "a7e2400a-7304-11ee-b4a0-0050568e08b3"
}
```

Utilizzando il debug client assertion di PDND, riscontro che il JWS del client assertion è corretto e di conseguenza anche il voucher, quindi il problema è il JWT da inserire poi nel Agid-JWT-TrackingEvidence.

Qual è la corretta struttura del payload del JWT?

**Comment by mladuDPA** [comment]
@ferdinandjmaddela Salve, se intende che l'errore persiste a seguito dell'invio del payload riportato qui #466 mi sembra di notare che manchi il campo `SACodiceFiscale` che dovrebbero averle comunicato come a noi tramite mail.
Vorrei cogliere l'occasione per chiederle se vuole nel caso di problemi intraprendere uno scambio di informazioni e darci una mano a vicenda per dei problemi comuni a cui ipotizzo andremo incontro (se possibile mi piacerebbe rimanere in contatto con un referente del team tecnico).
Le lascio qui la mia email m.ladu@digitalpa.it
Le chiedo di inviare appena possibile una mail anche vuota così da ottenere il suo indirizzo e poter togliere da questa issue il mio contatto.

**Comment by cragazzi** [comment]
@mladuDPA 
Buongiorno,
la ringrazio per l'offerta, ma per direttive aziendali non posso mandarle il mio indirizzo email.
Comunque provvederò a taggarla nei miei ticket, nel caso in cui le risposte ricevute da Anac possano essere utili per risolvere i problemi segnalati da lei.

**Comment by mpizziconi** [comment]
Validazione security token ModI 'AUDIT' della richiesta fallita: [GOVWAY-1355] [Header 'Agid-JWT-TrackingEvidence'] Signature verification failed: [COMPACT] INVALID_COMPACT_JWS: INVALID_COMPACT_JWS
