### ISSUE TITLE
JWT - Dati mancanti, accesso ambiente di test

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#368]
Come scritto nell' [issue ](https://github.com/anticorruzione/npa/issues/352) (aperto il 13 ottobre) abbiamo completato la richiesta di certificazione AGID, e siamo iscritti ai gestori delle piattaforme ANAC. Attualmente riceviamo ancora il 400 descritto nell'issue qui linkato.
Abbiamo ricevuto una mail in cui ci vengono fornite delle credenziali con i seguenti dati forniti:
`cfSoggetto` `cfPersonaGiuridica` `codiceAusa` `denominazione` `codiceSAML ` `descrizioneProfilo`
Abbiamo provveduto ad aggiornare i dati all'interno del jwt in modo tale da essere autenticati, ma riceviamo ancora il 400.
Rimangono non esposti invece i dati relativi dei campi `regCodicePiattaforma` `regCodiceComponente` (dove possiamo reperire tali informazioni?)
Serve con urgenza un feedback data l'impossibilità di continuare il lavoro.

Vorrei anche esprimere una lamentela verso l'indifferenza dimostrata ai diversi issue di errore 400 per l'accesso alle api degli e-service, a scapito sopratutto dei gestori privati, i quali non solo hanno avuto accesso all'ambiente di test a meno di 2 mesi dalla data di rilascio in più non gli si da risposta nemmeno per la presa in carico dell'issue.

Se l'obbiettivo era l'interoperabilità dei sistemi, si è perso completamente il focus sui soggetti che dovranno implementare quei sistemi.

**Comment by dpagliari** [comment]
Buongiorno,
Mi associo alle lamentele sopra esposte in quanto riteniamo non adeguato il servizio di supporto e le tempistiche di presa in carico e risoluzione.
Nello specifico, anche noi abbiamo aperto l'issue #365 e siamo in attesa che venga presa in carico.
Diverse sono le issue che riportano al medesimo errore che è BLOCCANTE per chi sta sviluppando le integrazioni.

**Comment by mpizziconi** [comment]
vedi https://github.com/anticorruzione/npa/issues/352
