### ISSUE TITLE
Certificazione per soggetti non identificati come SP Pubblici ai fini SPID

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#369]
In base al requesito 3.3.1.1-1 "La piattaforma deve consentire l’identificazione degli utenti tramite i meccanismi di identificazione elettronica SPID e CIE."
Inoltre con Avviso n.28 del 21/07/2020 Agid chiarisce quali sono i soggetti che "..possono aderire a SPID in qualità di Pubbliche Amministrazioni (SP pubblici)"
Si richiede di chiarire come comportarsi con quei soggetti che, pur dovendo procedere al processo di certificazione della piattaforma di eProcurement, non figurano nella lista degli SP Pubblici ai fini SPID. 
Esempi di questi enti sono Consorzi di Bonifica, srl/spa gestori di servizi pubblici, GAL, ecc...
Abbiamo notato che da qualche giorno il problema della mancata attribuzione del codice IPA è stato risolto aggiungendo una apposita categoria "Stazione Appaltante" nel sistema Indice PA.
Pensate di usare lo stesso approccio per identificare chi puo aderire a SPID in qualità di SP Pubblico?
Inutile sottolineare che il mancato riconoscimento di SP Pubblico, e quindi l'obbligo di adesione a SPID in qualità di SP Privato, comporterebbe non pochi problemi a questi soggetti, oltre che un costo da sostenere annualmente non trascurabile (e tra l'altro non preventivamente determinabile).
Grazie

**Comment by pakozack** [comment]
si sollecita un riscontro

**Comment by mfortini** [comment]
Riportiamo quanto ricevuto da AgID

In base all’[Avviso SPID 28](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n28-le_pa_nella_federazione_spid.pdf)  “Le Pubbliche Amministrazioni che intendono aderire a SPID o essere aggregate da Aggregatori di servizi pubblici di cui all’ Avviso SPID №19[ Avviso SPID №19 v2.0 (agid.gov.it)](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n19v2-regole_tecniche_aggregatori.pdf)  devono essere iscritte all’indice dei domicili digitali delle Pubbliche Amministrazioni e dei gestori di pubblici servizi (IPA) in qualità di “Pubbliche Amministrazioni” o di “Enti Nazionali di Previdenza ed Assistenza Sociale in Conto Economico Consolidato.”

Gli Aggregatori di servizi pubblici che intendono erogare l’attività di Gestori di cui ai punti 5 e 6 del paragrafo ‘Attività degli Aggregatori’ del suddetto Avviso SPID №19, devono essere iscritte all’IPA in una delle tipologie residuali rispetto a quelle indicate per le Pubbliche Amministrazioni”.

 

Si precisa che per SPID le “PA” sono solo gli enti iscritti in IPA come “Pubbliche Amministrazioni” o di “Enti Nazionali di Previdenza ed Assistenza Sociale in Conto Economico Consolidato (art. 2, co. 2, let. a))”.

Questi soggetti possono aderire in SPID come “SP pubblici”.

Mentre i soggetti iscritti in IPA nelle categorie residuali (art. 2, co. 2, let. b) e c)), non sono “PA”, ma “Gestori di servizio pubblico” e possono aderire in SPID come “Aggregatori di servizi pubblici”.


Pertanto, i soggetti iscritti in IPA  come “Stazioni appaltanti” possono aderire a SPID come “Aggregatori di servizi pubblici” per l’erogazione on line, mediante autentica SPID, dei propri servizi pubblici connessi all’attività di stazione appaltante.

Anche per questi soggetti, erogando servizi pubblici, l’uso di SPID è a titolo gratuito.

**Comment by pakozack** [comment]
La risposta ricevuta non ha risolto i nostri dubbi.
Proviamo a riformulare il quesito con maggiore dettaglio.
La nostra azienda, privata, è qualificata come "Soggetto Aggregatore di servizi pubblici", è attualmente attiva ed ha circa 150 enti aggregati.
E' nata (per procedere alla qualificazione delle piattaforme) l'esigenza da parte di alcuni enti, attualmente non nostri aggregati, di attivare gli accessi in piattaforma con SPID e CIE.
Questi enti però, anche avendo un codice IPA e quindi iscritti regolarmente all’indice dei domicili digitali delle Pubbliche Amministrazioni e dei gestori di pubblici servizi, secondo quanto indicato nell'Avviso SPID 28, non risultano identificati come SP Pubblici, quindi teoricamente da noi non "aggregabili".
Il punto della domanda è proprio questo: un ente come Consorzio di Bonifica, GAL, ecc..., dotato di codice IPA, ma a quel che ci risulta non identificato come SP Pubblico, si puo aggregare ad un "Soggetto Aggregatore di servizi pubblici"?

Dalla vostra risposta ci è sembrato di capire che questi enti (Consorzio di Bonifica, GAL, ecc...,) dovrebbero essere a loro volta soggetti aggregatori. Ma la cosa ci risulta abbastanza anomala.

Ribadiamo la nostra richiesta di avere contatti diretti con AGID in modo da velocizzare l'interlocuzione.

**Comment by pakozack** [comment]
Si sollecita un riscontro

**Comment by pakozack** [comment]
Attendiamo

**Comment by pakozack** [comment]
Come sempre... attendiamo
