### ISSUE TITLE
Gestione CIG perfezionati entro il 31/12/2023

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#375]
Si chiede conferma che per tutti i CIG perfezionati entro il 31/12/2023 e per tutte le fasi dell’appalto, la modalità di comunicazione dati con la ANAC rimane quella attuale tramite Simog.

**Comment by federicodemarco** [comment]
Buongiorno,
penso che le due richieste possano andare in parallelo https://github.com/anticorruzione/npa/issues/357

**Comment by r-dm123** [comment]
Attenersi a provvedimento ANAC MIT in corso di emissione
