### ISSUE TITLE
Chiarimenti compilazione Scheda S4 e RTI

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#376]
Si chiede di chiarire se nella scheda S4 devono essere inserite solamente le informazioni relative al soggetto che cambia oppure in caso di RTI bisogna inviare nuovamente il dettaglio di tutti i componenti

**Comment by anac-uscp** [comment]
In caso di RTI bisogna inviare nuovamente il dettaglio di tutti i componenti.
