### ISSUE TITLE
[Reopened] CodeList - Errore 400 

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#377]
Apro un nuovo issue dato che il [precedente ](https://github.com/anticorruzione/npa/issues/352) è stato chiuso (chiederei anche che sino a conferma della risoluzione del problema non venissero chiusi gli issue).

Nel [commento](https://github.com/anticorruzione/npa/issues/352#issuecomment-1770493280) si parla di iscrizione al registro dei gestori, vorrei capire se avendo l'accesso alla pdnd, e avendo potuto sottoscrivere le varie finalità per i servizi io sia ancora "**non presente nel registro dei gestori**" perchè l'issue è stato aperto dopo aver effettuato quelle operazioni (quindi mi aspetto ad iscrizione avvenuta). Se non fosse così vi prego di linkare una guida con gli step da fare.

Per quanto riguarda invece l'ipotesi di non aver completato la fruizione della versione 2 dei servizi, le finalità sono state richieste per le ultime versioni attive dei vari e-service (che sono quelle attualmente online) infatti l'aud esposto contiene la v2. Ad esempio per quanto riguarda l'e-service Codelist, finalità richiesta con versione 4 e aud `https://apigw-test.anticorruzione.it/modi/rest/CodeList/v2`

Per quanto riguarda l'ipotesi dell'errato base64 encode la [guida punto 6](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#6.-il-fruitore-fa-una-richiesta-di-dati-allerogatore) dice esplicitamente encodare in base64 il jws con le informazioni complementari.
In ogni caso sono state fatte diverse prove con base64_encode, senza e con sha256 quindi questa ipotesi è da scartare.

![immagine](https://github.com/anticorruzione/npa/assets/137039656/2d7a86fc-4fe2-4d01-b447-1e83ce45c457)

Dato che non è possibile inviare dati sensibili nelle issue, chiedo che venga esposto un sistema di supporto per questa operazione (visti i diversi issue di errori di questo tipo), ad esempio un contatto con un tecnico o perlomeno del codice funzionante che replichi un accesso ad un eservice compreso di payload.

Nel mentre allego 2 richieste andate in 400
Richiesta A con `Agid-JWT-TrackingEvidence` senza base64encode
```json
{
	"type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
	"title": "InteroperabilityInvalidRequest",
	"status": 400,
	"detail": "Received request is not conform to the required interoperability profile",
	"govway_id": "a3b962e8-6e62-11ee-a061-0050568e9679"
}
```

Richiesta B con `Agid-JWT-TrackingEvidence` con base64encode
```json
{
	"type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
	"title": "InteroperabilityInvalidRequest",
	"status": 400,
	"detail": "Received request is not conform to the required interoperability profile",
	"govway_id": "f001bcf4-6e62-11ee-b4a0-0050568e08b3"
}
```

**Comment by FedericaSicchiero** [comment]
Salve, io posso dare le risposte solo lato PDND e per quanto riguarda il commento sul registro dei gestori immagino si riferissero a questa [checklist](https://www.agid.gov.it/it/piattaforme/procurement/certificazione-componenti-piattaforme) di AgID, in quanto noi riceviamo una lista di enti che hanno completato il processo in modo da dare loro gli attributi necessari per iscriversi agli e-service di ANAC e completare la procedura. Se non si è completato quel processo non si può staccare il token su PDND perchè l'ente non risulta abilitato.

**Comment by mladuDPA** [comment]
@FedericaSicchiero Grazie ma il voucher pdnd è staccato correttamente, infatti il problema sicuramente è di un altra natura.
Non si capisce però se sia un errore all'interno del jws dei dati complementari, o se ci sia un errore nel servizio.
Attualmente il jws è stato creato seguendo la procedura, ma con questi risultati, quindi servirebbero delucidazioni da parte dell'anac sugli errori che noi e altri stanno ricevendo.

**Comment by FedericaSicchiero** [comment]
@mladuDPA effettivamente grazie alla vostra segnalazione ci siamo accorti di non aver aggiornato totalmente la documentazione e abbiamo tolto la parte come in vostro screen dell'obbligo di encodare il jws. Detto questo il fatto che riceviate errore comunque conferma il fatto che servano indicazioni da ANAC.

**Comment by mpizziconi** [comment]
Per rintracciare la chiamata è necessario fornire il clientId della fruizione

**Comment by mladuDPA** [comment]
Il clientId è considerato un dato sensibile?
Posso inoltrarlo in altro modo fuori dalle issue pubbliche?

**Comment by mpizziconi** [comment]
può scrivere a m.pizziconi@anticorruzione.it
