### ISSUE TITLE
modello di accounting e di validazione del token di autenticazione

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#4]
Ci servirebbero maggiori dettagli sulle seguenti tematiche in ambito autenticazione:
•	contesto di sicurezza (header, payload, uso del voucher) 
•	conferma sul soggetto fruitore (piattaforma di eProc Consip e non le singole AS), 
•	dettaglio sul processo di autenticazione utenti e assegnazione ruoli (RP, DRP) 
•	conferma modello di fruizione servizi (e-service o M2M)

**Comment by supportoAnac** [comment]
L’identità degli utenti segue le regole stabilite da Agid (OND) e prevede che l’identità sia accertata tramite spid (livello 2 o 3) o sistemi equivalenti. 
 L’identità si trova all’interno del jws. 
 L’utente deve essere già pre-registrato. 
 Come si passano queste informazioni all’interno del file? STANNO VALUTANDO. Si assocerà il profilo di rdp agli attuali Rup. E verrà aggiunto anche il profilo del rpd + delegato di responsabile di progetto.
