### ISSUE TITLE
PCP codeList - Attributi richiesti per la fruizione per gestore privato abilitato da Agid

### ISSUE THREAD

**Issue by collaudo5** [anticorruzione/npa#408]
Buongiorno,

abbiamo effettuato come Titolare e Gestore privato i seguenti step necessari alla qualifica:

1. Invio istanza e checklist verso AGID - **Esito positivo ricevito da AGID**
2. Iscrizione registro piattaforma per accedere alla PDND come privato - **Esito positivo**
3. Caricamento del contratto di adesione per Onboarding PDND - **Esito positivo**

Stiamo oggi provando ad effettuare l'accesso all'ambiente di collaudo con fruizione dei servizi messi a disposizione da ANAC ma non risultiamo in possesso degli attributi validi per tale fruizione (come si evince dalla pagina in allegato).

E' possibile sapere:

1.  quali sono gli ulteriori step necessari 
2. a chi sono in carico questi ulteriori steps.
3. quali sono le tempistiche di attribuzione degli attributi necessari per iniziare la fase di test.
4. I 60 gg di decorrenza per l'esecuzione dei test è da considerarsi in stand-by in attesa di questa ulteriore abilitazione.

Grazie.

<img width="926" alt="image" src="https://github.com/anticorruzione/npa/assets/123168895/4ed69230-5569-453b-b1db-18e8d1bab5ad">

**Comment by FedericaSicchiero** [comment]
Buon pomeriggio, lato PDND risulta che dalla vostra anagrafica ente ora siate in possesso di uno dei tre requisiti richiesti dalle-service. Vi chiedo gentilmente di riprovare e vedere se si ripresenta l'errore. In quel caso vediamo di approfondire la questione.

**Comment by collaudo5** [comment]
Buonasera,
siamo riusciti ad effettuare con successo la richiesta di friuzione degli e-service di interesse.

Grazie mille per il supporto.
