### ISSUE TITLE
Scheda AD4: settore, soglie e regimi. Concessioni?

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#417]
a quale settore, soglie e regime si applica la scheda AD4? Si applica alle concessioni?

**Comment by anac-uscp** [comment]
La scheda AD4 si applica ad appalti e concessioni, in tutti i settori  e per
tutti i regimi. È stata aggiornata la descrizione della scheda nella colonna C nell'orchestratore
