### ISSUE TITLE
Scheda AD5: settore, soglie e regime

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#418]
a quale settore, soglie e regime si applica la scheda AD5? Si applica alle concessioni?

**Comment by anac-uscp** [comment]
La scheda AD5 si applica a tutti i settori e a tutti i regimi. Non si applica alle concessioni
L’affidamento diretto delle concessioni sottosoglia deve essere comunicato con la scheda AD_28.
