### ISSUE TITLE
Scheda A3_6: quali settori, soglie regimi. In house

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#428]
la scheda A3_6 vale per tutti i settori, soglie e regimi? Per gli affidamenti in House non sono presenti altre schede con lo stesso flusso di appartenenza, il ciclo di vita dell'appalto inizia con questa scheda?

**Comment by anac-uscp** [comment]
La A3_6 vale per tutti i settori così come riportato nell'orchestratore.
Si, il ciclo di vita dell'appalto inizia con la scheda A3_6.
