### ISSUE TITLE
Schede A7_1_1 e A7_1_2 e indagine di mercato

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#435]
le schede A7_1_1 e A7_1_2 corrispondo al flusso delle rispettive P che sono indicate come avvio dell'indagine di mercato. È corretto che si debba indicare un ggiudicatario per l'indagine di mercato? Inoltre, in queste schede nelle schede A non si fa alcun riferimento all'indagine di mercato

**Comment by anac-uscp** [comment]
Le schede P_7_1_1 e P_7_1_2 non presentano differenze, ma sono state distinte perché i relativi flussi presentano differenze in fase di aggiudicazione (cfr. A_7_1_1 e A_7_1_2)
Le stazioni appaltanti devono usare il flusso 711 se, in aggiudicazione, intendono pubblicare sul TED uno degli eform 25,26,27,28 (v. scheda A_7_1_1), mentre devono usare il flusso 712 se non intendono pubblicare alcun eform (v. scheda A_7_1_2)
Questo perché la pubblicazione degli eform 25, 26, 27, 28 (relativi all’avviso volontario per la trasparenza preventiva di cui all’art. 86 del codice) non è obbligatoria per cui le stazioni appaltanti hanno la facoltà di decidere se pubblicarli o meno.
