### ISSUE TITLE
Tipologica motivoCollegamento.json

### ISSUE THREAD

**Issue by pb40527** [anticorruzione/npa#438]
L´appalto pre-commerciale deve essere svolto in modalità interamente digitale?

"codice": "11",
    "descrizione": {
      "it": "Affidamento a seguito di appalto pre-commerciale",
      "en": "Affidamento a seguito di appalto pre-commerciale"
    },
    "dataInizio": "2021-05-19T00:00:00Z",

**Comment by anac-uscp** [comment]
L'appalto pre-commerciale rientra tra i contratti esclusi e può essere gestito tramite piattaforme certificate utilizzando gli appositi flussi oppure si può acquisire il CIG mediante interfaccia web (vedi comunicato d'intesa col MIT di cui alla delibera ANAC n. 582 del 13 dicembre 2023)
