### ISSUE TITLE
Scheda S1 - utilizzo per Sistemi Dinamici di Acquisizione e Sistemi di Qualificazione per settori speciali

### ISSUE THREAD

**Issue by GiovanniSom** [anticorruzione/npa#439]
La scheda S1 - "Elenco dei soggetti che hanno manifestato interesse nelle procedure a due fasi" deve essere inviata anche per indicare la lista di Fornitori che abbiano completato i percorsi di iscrizione ad uno degli elenchi in oggetto?

per l'indizione di un Sistema Dinamico di Acquisizione non risulta prevista alcuna scheda particolare da trasmettere, è corretto?

attendiamo riscontro, grazie e buon lavoro.

**Comment by anac-uscp** [comment]
No, la S1 non deve essere inviata per indicare la lista di Fornitori che abbiano completato i percorsi di iscrizione ad uno degli elenchi in oggetto. La scheda S1 si usa per le procedure a 2 fasi (ad es. procedura ristretta).
Per indicare che si tratta di un SDA è necessario compilare il campo BT 766  Dynamic Purchasing System.
