### ISSUE TITLE
Schede AD - Chiarimenti dati

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#440]
**1)** In relazione alle schede AD (AD1_X e AD2_X) riguardanti l'affidamento diretto, abbiamo notato che alcuni campi obbligatori previsti dall'Anac Form riguardano la parte di aggiudicazione. Esempio:

- dataAggiudicazione
- dati del partecipante in caso di aggiudicazione diretta

E' corretto inviare i dati sopra indicati in fase di creazione appalto, e quindi ad aggiudicazione non ancora avvenuta?

**2)** Per le schede AD1 in cui è prevista l'obbligatorietà dell'eForm (subtype 25,26,28) quest'ultimo deve essere inviato nel momento della creazione appalto?

**Comment by anac-uscp** [comment]
1) L'affidamento diretto prevede la comunicazione contestuale dei dati per la creazione dell'appalto e dei dati dell'aggiudicatario perchè noti fin dall'inizio.
2) si, le eForm AD1 vengono inviate per la pubblicazione sul TED.

**Comment by federicodemarco** [comment]
Buonasera @anac-uscp  e @mpizziconi, a questo punto mi sorge un dubbio. Per gli affidamenti diretti le schede vanno inviate al momento della aggiudicazione? 
In caso di risposta affermativa al precedente quesito, un AD svolto in piattaforma sarebbe privo del CIG fino al momento della aggiudicazione, quando si passano alla PCP tutte le info necessarie per poter staccare un CIG?

**Comment by mpizziconi** [comment]
se rimangono dubbi sulle issue è opportuno aprire una nuova issue citando quella chiusa.
Lascio la risposta ai colleghi del gruppo dati

**Comment by federicodemarco** [comment]
si sollecita riscontro per piacere

**Comment by anac-uscp** [comment]
1) Negli affidamenti diretti i dati vanno inviati al momento dell’aggiudicazione e il CIG viene rilasciato in questa fase
2) Sì, l’eform deve essere inviato nel momento della creazione appalto e il CIG viene rilasciato in questa fase
