### ISSUE TITLE
Servizio Pubblica Avviso - Conferma piano e pubblica avviso senza idAppalto

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#441]
Buongiorno, diverse schede afferenti alla pianificazione richiedono la successiva pubblicazione di un avviso. Per la pubblicazione successiva di un avviso, tramite il servizio pubblica-avviso, è obbligatorio inviare ad ANAC l'idAppalto, che nel caso delle schede di pianificazione non è possibile ottenere. Tra l'altro, lo stesso servizio esito-operazione, tramite il quale si può recuperare l'idAvviso, richiede l'idAppalto. Come si può procedere per la pubblicazione di queste tipologie di avviso?

**Comment by mariottiDPA** [comment]
superato con l'ultimo rilascio

**Comment by pakozack** [comment]
è possibile condividere come è stato superato?

**Comment by mariottiDPA** [comment]
@pakozack diversamente dalle schede di appalto, gli avvisi relativi alle schede di pianificazione non necessitano di una chiamata esplicita al servizio pubblica-avviso, ma non appena creati vanno in stato IN_ATT_PUBB (come per le schede di post pubblicazione)

**Comment by pakozack** [comment]
Grazie milleInviato da iPhoneIl giorno 14 dic 2023, alle ore 18:13, mariottiDPA ***@***.***> ha scritto:﻿
@pakozack diversamente dalle schede di appalto, gli avvisi relativi alle schede di pianificazione non necessitano di una chiamata esplicita al servizio pubblica-avviso, ma non appena creati vanno in stato IN_ATT_PUBB (come per le schede di post pubblicazione)

**Comment by ffinpaa** [comment]
Buongiorno, potete darmi supporto nel capire quali sono le schede di pianificazione (area A_1) che prevedono la pubblicazione di un avviso e in che modo è possibile intercettare questa specifica?
