### ISSUE TITLE
FVC - Tipologica tipoFascicolo.json

### ISSUE THREAD

**Issue by pb40527** [anticorruzione/npa#442]
Si chiedono chiarimenti per quanto riguarda il FVC

"codice":"FVC",
    "descrizione": {
		"it": "Fascicolo Virtuale del Concorrente",
		"en": "Fascicolo Virtuale del Concorrente"
		},
    "dataInizio":null,
    "dataFine":null

**Comment by supportoAnac** [comment]
Per approfondimenti sull’FVC si rimanda alla documentazione di progetto pubblicata.
