### ISSUE TITLE
Tempistiche per onboarding PDND

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#443]
Abbiamo inviato istanza di certificazione ad Agid e ricevuto esito positivo. Abbiamo naturalmente urgenza di effettuare l'onboarding su PDND. 
E' possibile sapere quando ci verrà concessa la possibilità di farlo?

**Comment by FedericaSicchiero** [comment]
Buongiorno, con quale ente state facendo la procedura? Perchè noi come PDND riceviamo ogni 2/3 giorni la lista degli enti abilitati all'onboarding e posso controllare se siete già dentro.

**Comment by pakozack** [comment]
L&G Solution srl

**Comment by pakozack** [comment]
@FedericaSicchiero ad ora ancora non risultiamo nella lista. Posso avere una sua mail per fornirle i dettagli della nostra richiesta?

**Comment by FedericaSicchiero** [comment]
@pakozack la mia mail è federica.sicchiero@pagopa.it ma ricordo che l'abilitazione all'adesione su PDND avviene solo a valle della richiesta di certificazione ad AgID e della iscrizione al registro dei gestori delle piattaforme di ANAC.
PDND riceve l'autorizzazione all'adesione delle imprese solo a conclusione, con successo, di questo processo.
Ho visto che avete ricevuto esito positivo da AgID ma se il processo non è concluso totalmente non abbiamo possibilità di abilitarvi a PDND Interoperabilità.

**Comment by pakozack** [comment]
@mpizziconi ci sa dire quando saremo attivati su PDND? Inutile ribadire l'urgenza che abbiamo vista la scadenza del 31/12

**Comment by mpizziconi** [comment]
il trasferimento dell'iscrizione nel registro per l'abilitazione PDND è immediata.
Qual è il soggetto iscritto?

**Comment by pakozack** [comment]
L&G Solution srl

**Comment by mpizziconi** [comment]
L&G Solution srl
risulta abilitata e trasferita a PDND
è stata inviata un'email con un set di utenze di test da utilizzare nel token JWS

**Comment by pakozack** [comment]
@mpizziconi confermo che adesso è arrivata la mail con le utenze di test. 

Continuo però a non trovare la nostra anagrafica su onboarding PDND.
<img width="850" alt="Schermata 2023-10-25 alle 15 03 38" src="https://github.com/anticorruzione/npa/assets/2580458/d9e11f55-6bfd-45e8-99cf-efa4d51a2388">

Cosa sto sbagliando?

**Comment by FedericaSicchiero** [comment]
@pakozack sto sentendo il team che si occupa di abilitare gli enti di questo tipo per capire dov'è il blocco

**Comment by FedericaSicchiero** [comment]
@pakozack a noi risulta che come ente non siate ancora presenti sulla lista che esportiamo da ANAC

**Comment by pakozack** [comment]
@mpizziconi come possiamo procedere?

**Comment by mpizziconi** [comment]
Lato ANAC gli utenti sono attivi.
Stiamo verificando la trasmissione a PagoPA

**Comment by pakozack** [comment]
@mpizziconi siamo riusciti ad entrare su PDND ma abbiamo ulteriori problemai.
@FedericaSicchiero abbiamo inserito i dati, ci è arrivato l'accordo da firmare p7m, accediamo al link per caricarlo. Selezionando il file il sistema errore e non procede all'upload. Cosa dobbiamo fare?

**Comment by FedericaSicchiero** [comment]
@pakozack il file non deve essere protocollato per essere letto correttamente dal sistema e abbiamo notato come ogni tanto vengano succeda che vengano protocollati in automatico quando si firmano. Se l'errore è questo basta rifirmarlo facendo attenzione a quel dettaglio e il sistema non dovrebbe dare errori. Chi firma deve essere il Legale Rappresentante altrimenti anche lì da errore. Se è tutto corretto e ricevete errore comunque vi chiedo di mandarmi via mail l'accordo e chiedo al team di onboarding di caricarlo a mano se possibile.

**Comment by pakozack** [comment]
@FedericaSicchiero il p7m generato è fatto dal pdf senza alcuna modifica. Lo ha firmato il rappresentante legale. Ad ogni modo ti sto inviando mail con il file p7m

**Comment by pakozack** [comment]
@FedericaSicchiero risolto, il problema era il nome file e la "à" di interoperabilità che dike aveva trasformato in "a"

**Comment by FedericaSicchiero** [comment]
@pakozack ottimo allora vi lascio procedere col percorso standard di onboarding!

**Comment by pakozack** [comment]
@FedericaSicchiero è normale?
<img width="1746" alt="Schermata 2023-10-27 alle 12 31 06" src="https://github.com/anticorruzione/npa/assets/2580458/894c7689-f7fa-4751-9acb-a83b1304dcb4">

**Comment by FedericaSicchiero** [comment]
Si confermo che è normale, gli attributi al momento vengono ancora associati manualmente perchè stiamo lavorando al loro rilascio automatico una volta completato l'onboarding. Sto già contattando chi di dovere in modo che sappiano che siete iscritti e che quindi si possono dare gli attributi richiesti da ANAC.

**Comment by pakozack** [comment]
@FedericaSicchiero grazie mille. come al solito raccomando tempestività

**Comment by FedericaSicchiero** [comment]
@pakozack sono stati aggiunti gli attributi per iscriversi ai servizi ANAC
