### ISSUE TITLE
PDND E-service - Stima di carico

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#444]
Salve mi servirebbero delle informazioni sulle stime di carico delle diverse finalità.
Attualmente abbiamo generato una finalità con un numero di 5000 chiamate API/giorno per fruitore.

Il fruitore è inteso come client e-service? Quindi generando più client e-service possiamo superare il limite delle 5000 chiamate al giorno?

**Comment by FedericaSicchiero** [comment]
Buongiorno, le chiamate per fruitore vanno a comprendere tutte quelle che i client di quel fruitore vanno a fare, quindi si sommano tra di loro e vanno a formare il totale per fruitore che viene stabilito nella finalità.
Grazie della segnalazione, aggiungo quella parte nella nostra documentazione per chiarirla meglio.

**Comment by mladuDPA** [comment]
@FedericaSicchiero Grazie per il chiarimento.
Giusto un altra domanda, in produzione ci sarà un limite massimo identico?
Chiedo perchè a seconda dell'e-service (ad esempio https://apigw-test.anticorruzione.it/modi/rest/ServiziComuni/v2) e a seconda della tipologia di fruitore (per esempio un fruitore che gestisce più SA) si potrebbe arrivare al rate massimo di richieste.
Avete dei consigli sullo scaling per queste casistiche del rate massimo di chiamate?

**Comment by FedericaSicchiero** [comment]
Il limite viene sempre deciso dall'erogatore, quindi magari in collaudo mettono un numero e in produzione un altro, non possiamo prevederlo noi di PDND. Al momento non abbiamo consigli perchè appunto dipende tutto dai server dell'erogatore e da quanto possono sopportare, non dal sistema nostro.

**Comment by mladuDPA** [comment]
Perfetto la ringrazio.
Vorrei allora porre la domanda agli erogatori degli e-service @mpizziconi @supportoAnac .
Si ha un idea del limite di richieste che verrà gestito in ambiente di produzione?
Chiedo più che altro per gli e-service di interrogazione, come ad esempio 

- https://apigw-test.anticorruzione.it/modi/rest/ServiziComuni/v2
- https://apigw-test.anticorruzione.it/modi/rest/CodeList/v2

**Comment by mladuDPA** [comment]
Ricevuta risposta in una call.
I limiti esposti sono validi solo per l'ambiente di collaudo.
