### ISSUE TITLE
"ERR67" -  stazione appaltante

### ISSUE THREAD

**Issue by evalentip** [anticorruzione/npa#445]
[p6.1.txt](https://github.com/anticorruzione/npa/files/13060369/p6.1.txt)
[ad3.txt](https://github.com/anticorruzione/npa/files/13060370/ad3.txt)
Si chiede chiarimento sul seguente errore bloccante riscontrato sull'oggetto stazioni appaltanti: 
"ERR67"
Tale errore non risulta riportato nel file errori.json.

Session ID: 01e2efc4-f2cd-40f4-bac1-05e7c6dcefba
schede AD3- P6.1

**Comment by mpizziconi** [comment]
abbiamo verificato il log dei servizi, l’errore dipende dal mancato riscontro del codice centro di costo presente nella richiesta con quello presente in anagrafe ausa di test (ambiente qualificazione).
Ausa è consultabile tramite un servizio esposto su PDND ma esterno a PCP, erogazione "AUSA - Anagrafe Unica delle Stazioni Appaltanti
