### ISSUE TITLE
Schede AD5 e C02 - Affidamento diretto < 5K | Campo idContratto

### ISSUE THREAD

**Issue by PietroChiappini67** [anticorruzione/npa#448]
Buongiorno,
Per un affidamento diretto il cui importo è inferiore a 5K dovremmo inviare due schede: 

1) **AD5** - per la fase di Afffidamento (comunicaAppalto);
2) **C02** - come scheda conclusiva (comunicaPostPubblicazione)

Analizzando il punto 2, lo schema della **AnacFormCO2Type** prevede il campo **idContratto**  come **obbigatorio**. 
Se non abbiamo capito male è la stessa l'api **/crea-scheda** che restituisce idContratto (_identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto_).

**Comment by PietroChiappini67** [comment]
Buongiorno, sono più di tre settimane che attendiamo un riscontro.

**Comment by supportoAnac** [comment]
La CO2 è sospesa fino a modifica del modello dati.
