### ISSUE TITLE
Scheda AD5 - CUP

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#451]
Il CUP nella scheda AD5 attualmente è messo come obbligatorio, ma ovviamente non è giusto che lo sia.
Inoltre, è una stringa libera, mentre in altre schede ha un pattern `(^[a-zA-Z0-9]{15}$])`

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 24/11/2023.
