### ISSUE TITLE
Compilazione dell'attributo linkDocumenti per tutte le procedure d'appalto

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#454]
Ci viene data evidenza da alcune SA che nel "Comunicato del Presidente ANAC del 19 settembre 2023" - che ha per oggetto "Assolvimento obblighi informativi degli affidamenti eseguiti tramite procedure di somma urgenza e protezione civile, ai sensi dell’articolo 140 del Codice (già articolo 163 del decreto legislativo n. 50/2016)." - a pagina 2 viene precisato:
"A decorrere dal 1° gennaio 2024, **la modalità semplificata di trasmissione verrà estesa a tutti gli affidamenti di importo pari o superiore a 5.000 euro**. Le stazioni appaltanti, pertanto, all’atto della richiesta del CIG, dovranno indicare nell’apposito campo il **link alla pagina del proprio sito istituzionale** dove sono pubblicati i documenti."

Possiamo assumere che l'attuale campo **linkDocumenti** "Link ai documenti relativi all’affidamento diretto in somma urgenza e protezione civile (co 10, art 140 nuovo codice)"  (es. scheda P1.16) venga usato per tutti gli affidamenti?
Oppure prevedete un altro campo?

Abbiamo necessità di comprenderlo in funzione della gestione dei dati e dei controlli di compilazione a livello di piattaforma.
Grazie

**Comment by anac-uscp** [comment]
I campi 'Motivo somma/estrema urgenza' e i 'Link ai documenti relativi all’affidamento diretto in somma urgenza e protezione civile (co 10, art 140 nuovo codice)' devono essere compilati per tutte le schede dove lo yaml prevede questi campi.
Il link ai documenti va inserito esclusivamente se si verifica la condizione associata al campo 'Motivo somma/estrema urgenza': il campo è obbligatorio solo se motivoUrgenza.codice = "2" ovvero "Somma urgenza e protezione civile"
