### ISSUE TITLE
[BLK] Catalogo e-service PDND - Servizi pianificazioneAppalto (ad es. crea-piano)

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#456]
Buongiorno,
nel catalogo e-service filtrato per quelli di ANAC non troviamo quelli relativi alle operazioni "pianificazioneAppalto"
previste dalle specifiche specifiche-servizi-appalto.yaml e documentati in documento-specifiche-servizi-npa.md

Con la nostra utenza di "Titolare e gestore privato" vediamo questi servizi (interoperabilità collaudo):

1. PCP - codeList
2. PCP - Comunica appalto
3. PCP - Comunica post pubblicazione
4. PCP - FVA
5. PCP - FVC
6. PCP - Gestione utenti
7. PCP - Pubblica avviso
8. PCP - Servizi comuni

E questi altri di ANAC:

- ApiCIG
- ApiCIG - prova attributo dichiarato
- AUSA - Anagrafe Unica delle Stazioni Appaltanti
- Ecertis
- Ecertis - prova attributo dichiarato
- ESPD-Multidominio
- OCDS Open Contracting Data Standard
- Simog schede successive
- SimogFaseIniziale
- SimogWSTED
- SmartCIG

Potete darci qualche indicazione a riguardo?
Grazie

**Comment by paolo-urbanetto** [comment]
[BLK] i servizi non sono ancora presenti su PDND

**Comment by paolo-urbanetto** [comment]
Buongiorno, ho visto che ora è disponibile l'e-service PCP Pianificazione appalto.
Riesco a sottoscrivere il servizio, ma poi quando provo a creare la Finalità il portale va in errore 404.

![image](https://github.com/anticorruzione/npa/assets/88787715/af44c6dd-fe09-4dc5-a13c-92c5557db8d3)

**Comment by GiovanniSom** [comment]
riscontro lo stesso problema, attendiamo un riscontro. grazie e buona giornata

**Comment by FedericaSicchiero** [comment]
Buonasera, mi scuso per il ritardo della risposta. Potreste fornirci il correlationID in modo da controllare? Grazie

**Comment by gaetanololli** [comment]
Buongiorno, anche io ad oggi riscontro lo stesso problema: non è possibile associare un client o inviare la bozza.

<img width="1316" alt="image" src="https://github.com/anticorruzione/npa/assets/42801336/543d5f52-ed3f-4ead-86e8-d342b1b954e8">

**Comment by paolo-urbanetto** [comment]
Per quanto riguarda noi (Maggioli) il problema si è risolto dopo aver forzato più volte l'operazione di salvataggio della finalità.
