### ISSUE TITLE
Crea-appalto - Errore 400 ERR4

### ISSUE THREAD

**Issue by cragazzi** [anticorruzione/npa#457]
Buongiorno,
stiamo cercando di effettuare una chiamata crea-appalto con la scheda P2_16.
Ci viene restituito  "status":400 con errori ERR4 aventi i seguenti dettagli:

         "dettaglio":"$.anacForm.appalto.appaltoP216TypeCategorieMerceologiche: is missing but it is required",
       
         "dettaglio":"$.anacForm.appalto.appaltoP216TypeCodiceAppalto: is missing but it is required",
    
         "dettaglio":"$.anacForm.lotti[0].lottoP216TypeAfferenteInvestimentiPNRR: is missing but it is required",
        
         "dettaglio":"$.anacForm.lotti[0].lottoP216TypeCategorieMerceologiche: is missing but it is required",
      
         "dettaglio":"$.anacForm.lotti[0].lottoP216TypeCodIstat: is missing but it is required",
        
         "dettaglio":"$.anacForm.lotti[0].lottoP216TypeContrattiDisposizioniParticolari: is missing but it is required",
        
         "dettaglio":"$.anacForm.lotti[0].lottoP216TypeLotIdentifier: is missing but it is required",

In realtà il json inviato contiene tutti questi campi. 
L'ultimo errore ricevuto ha i seguenti ID:
GovWay-Message-ID: 40a70b5f-8759-4cc4-b1d5-a7cc66edab6f
GovWay-Transaction-ID: 66179aac-725a-11ee-a061-0050568e9679

Potete verificare ed indicarci qual è il problema?

Vi ringrazio

**Comment by supportoAnac** [comment]
Sarà corretto con il prossimo rilascio.
