### ISSUE TITLE
Procedura negoziata senza bando - Scheda di riferimento

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#458]
Buongiorno,

Per aprire una procedura negoziata senza previa pubblicazione di un bando di gara o senza previa indizione di gara, è necessario partire da una scheda P7 ovvero sia da una indagine di mercato o richiesta di offerta da elenco? Se non necessario da quale scheda bisogna partire?

Grazie

**Comment by anac-uscp** [comment]
Le schede P_7_1_1 e P_7_1_2 non presentano differenze, ma sono state distinte perché i relativi flussi presentano differenze in fase di aggiudicazione (cfr. A_7_1_1 e A_7_1_2)
Le stazioni appaltanti devono usare il flusso 711 se, in aggiudicazione, intendono pubblicare sulla GUUE uno degli eform 25,26,27,28 (v. scheda A_7_1_1), mentre devono usare il flusso 712 se non intendono pubblicare alcun eform (v. scheda A_7_1_2)
Questo perché la pubblicazione degli eform 25, 26, 27, 28 (relativi all’avviso volontario per la trasparenza preventiva di cui all’art. 86 del codice) non è obbligatoria per cui le stazioni appaltanti hanno la facoltà di decidere se pubblicarli o meno.

Con le schede P7_1_X, le stazioni appaltanti rendono noto l’avvio di un’indagine di mercato volta a ricevere richieste di invito, al fine di individuare gli operatori economici da invitare alla successiva procedura negoziata senza bando.
Le P_7_1_1 e P_7_1_2 riguardano l’avvio di un’indagine di mercato finalizzata ad una procedura negoziata senza bando di valore pari o superiore alla soglia (per le differenze tra le due schede vedere risposta a issue 196).
La scheda P_7_1_3 riguarda l’avvio dell’indagine di mercato finalizzata ad una procedura negoziata senza bando sottosoglia.

**Comment by OperatoreIT** [comment]
<p>Gentile Utente, <br>
<br>
In riferimento alla segnalazione in oggetto, si richiedono maggiori dettagli al fine di consentire le opportune verifiche.</p>

<p>In particolare, la problematica descritta non risulta, allo stato attuale, sufficientemente chiara; si chiede pertanto di fornire i seguenti elementi informativi:</p>

<ul data-spread="false">
	<li>un esempio puntuale di annotazione per la quale risultino mancanti le informazioni indicate (es. identificativo dell’annotazione e/o codice fiscale dell’Operatore Economico);</li>
	<li>evidenza comparativa tra quanto visualizzato su FVOE (web/API) e quanto restituito dalla procedura storica, eventualmente mediante screenshot o tracciati di risposta;</li>
	<li>eventuali chiamate API utilizzate (endpoint e payload), nel caso di utilizzo tramite integrazione.</li>
</ul>

<p>Le informazioni sopra richieste risultano necessarie al fine di riprodurre il comportamento segnalato e procedere con le opportune analisi tecniche.</p>

<p>Restiamo a disposizione<br>
<br>
Cordiali Saluti </p>
