### ISSUE TITLE
Schede CIG derivato

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#459]
Buongiorno, 

Le schede per staccare i CIG derivati (P3_3, P6_1, P6_2, AD4) indicano nell’orchestratore che è previsto l’ESPD. Se si sta aderendo ad una convenzione di altro soggetto è necessario inviare l’ESPD della gara di riferimento? Inoltre, è corretto che nell’orchestratore sia indicato che si di procedere con la scheda S2 per indicare i partecipanti / invitati?

Grazie

**Comment by anac-uscp** [comment]
La domanda non è chiara. Si prega di chiarire meglio la issue. Grazie
