### ISSUE TITLE
RP/DRP - Codifica CIG al conferma appalto

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#461]
Salve,
in base a quanto descritto dall'Allegato I.2 art. 6 c. 2 lett. L _"il Rup “ provvede all’acquisizione del CIG nel caso in cui non sia nominato un responsabile per la fase di affidamento”._

1. Nel caso in cui, dopo la fase di crea-appalto, venga nominato (mediante aggiungi-soggetto) il responsabile per la fase di affidamento (DRP) deve essere quest'ultimo obbligatoriamente e in via esclusiva a richiamare il conferma-appalto e quindi a codificare i CIG?

**Comment by mpizziconi** [comment]
Corretto: se il RUP delega e funzioni ad un DRP allora le attività sono in carico a quest'ultimo
