### ISSUE TITLE
Servizi NPA, FVOE e FVA - Gestione dell'ambiente di test

### ISSUE THREAD

**Issue by GiovanniSom** [anticorruzione/npa#462]
Buongiorno,
relativamente all'ambiente di test da utilizzare per la certificazione delle piattaforme vorremmo sapere
1) l'ambiente rimarrà acessibile in generale anche dopo il 31/12/2023?
2) l'ambiente rimarrà acessibile in generale anche dopo il rilascio di nuovi servizi FVOE previsto per giugno 2024?
3) le credenziali ricevute per il percorso di certificazione rimarranno valide anche al termine del percorso di certificazione iniziale, per consentire nuovi test in corrispondenza all'evoluzione delle piattaforme o per certificare nuove versioni sarà necessario chiedere nuove credenziali?

grazie e buona giornata

**Comment by mpizziconi** [comment]
L'operatività e le modalità di gestione/accesso previste l'ambiente di certificazione rimangono stabili per tutto il ciclo di vita in esercizio di PCP.
