### ISSUE TITLE
P6.1 - ESITO_OPERAZIONE non restituisce  l'idAvviso

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#464]
dopo aver creato e confermato un appalto non si riesce a chiamare il servizio pubblica-avviso perché non c'è modo di ottenere l'ID AVVISO (non viene restituito in output dal servizio esito-operazione).
è un errore o significa che per le schede che non prevedono l'EFORM non va chiamato il pubblica-avviso?
[P6ErrNoIDAvviso.txt](https://github.com/anticorruzione/npa/files/13121161/P6ErrNoIDAvviso.txt)

**Comment by obigno77** [comment]
La P6_1 è una scheda di adesione ad accordo quadro che non prevede alcuna pubblicazione e quindi correttamente non viene generato l'id_avviso

**Comment by obigno77** [comment]
La scheda P6_1 non prevede pubblicazione nè europea nè nazionale. Per questo motivo non è rilasciato alcun id_avviso

**Comment by lauralu1993** [comment]
Ci sono altre schede di indizione per cui non è prevista nessuna pubblicazione?

**Comment by mpizziconi** [comment]
Si faccia riferimento alle colonne I ed M della tabella di orchestrazione

https://github.com/anticorruzione/npa#:~:text=consultabile%20nella%20cartella-,orchestratore,-.%20Le%20piattaforme%20fruitrici

**Comment by mpizziconi** [comment]
Per le procedure che non prevedono la pubblicazione la conferma equivale all'operazione pubblica-avviso. Dopo l'operazione di conferma è possibile procedere con le attività successive. 
Aggiorniamo il diagramma

**Comment by lauralu1993** [comment]
dopo aver CONFERMATO l'appalto con la P6.1 abbiamo inviato la scheda S2 come riportato nell'orchestratore.
l'esito è ERR2 -  scheda non ammessa in questa fase dell'appalto

<img width="702" alt="image" src="https://github.com/anticorruzione/npa/assets/142924847/fdc4de2c-1887-42d6-8a7d-e711278ce02e">

**Comment by mpizziconi** [comment]
ripostata in https://github.com/anticorruzione/npa/issues/486

**Comment by jmf330** [comment]
@lauralu1993 

Come è riuscita a ovviare al problema che si riscontra in molteplici issue (#500 , #501) ??

```
"datiBaseCPV": {
    "tipoClassificazione": {
        "idTipologica": "tipoClassificazione",
        "codice": "cpv"
    },
    "cpvPrevalente": {
        "idTipologica": "CPV",
        "codice": "98910000"
    },
    "cpvSecondarie": []
},
```

**Comment by lauralu1993** [comment]
@jmf330 
1) il campo datiBaseCPV è facoltativo. pertanto nel nostro JSON non è presente e quindi riusciamo ad andare avanti
2) stiamo mettendo nei JSON l'oggetto stazioniAppaltanti anche se non è presente nello swagger perche in altra occasione ci è stato detto che trattava di un errore
