### ISSUE TITLE
Scheda P1.16 - Esito di errore su PUBBLICA-AVVISO

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#465]
dopo aver creato e confermato correttamente un appalto proviamo a pubblicare senza successo. 
verificando l'esito della pubblicazione riscontriamo il seguente errore:

{
   "idTipologica":"errori",
   "dettaglio":"[400] during [POST] to 
   [
http://pcp-qlf-ted-ms.pcp-qlf.svc:8080/submit?language\u003dit\u0026authorEmail\u003dufficio.uscp%40anticorruzione.itt
   ] 
   [TedMsClient#submit(String,String,String)]: 
   [
   {
   "code":400,
   "status":"400 BAD_REQUEST",
   "title":"Error",
   "detail":"403 Forbidden from POST [http://uaa.teden2.reception.internal.op.aws.cloud.tech.ec.europa.eu/auth/internal"](http://uaa.teden2.reception.internal.op.aws.cloud.tech.ec.europa.eu/auth/internal%22),
   "links":null
}
   ]",
   "codice":"ERR64"
}

**Comment by supportoAnac** [comment]
Le Api Key utilizzate sono in fase di validazione dal TED.
