### ISSUE TITLE
Sistema Dinamico di Acquisizione (Scheda S1)

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#467]
Buongiorno,

Per il lancio di un Sistema Dinamico di Acquisizione – Bando Istitutivo è corretto che non si debba inviare alcuna scheda ma dovranno essere utilizzate solo le schede P1_16,P1_17,P1_18, etc, a seconda delle caratteristiche dell’appalto, per comunicare il Sistema Dinamico di Acquisizione - Appalto Specifico? Successivamente si dovrà usare la scheda S1 per comunicare i partecipanti al Sistema Dinamico di Acquisizione - Bando Istitutivo? 

Grazie

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;"><span style="font-family:Titillium;">Per l’istituzione del sistema dinamico di acquisizione ai sensi dell’art. 32 , si devono utilizzare le schede ISDA1/ISDA2 con i relativi flussi di appartenenza (S0, CSDA1/CSDA2).<br>
Per le procedure a valle del Sistema Dinamico, si utilizzeranno le schede relative a tali procedure con il corrispondente flusso (vedi art. 32 comma 2).</span></span></span></span></p>

<p style="margin-bottom:11px;"> </p>

<p>Per la gestione del Bando Istitutivo dello SDA, sono state previste 2 schede: </p>

<ol start="1">
	<li data-aria-level="1" data-aria-posinset="1" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="1">
	<p>Una scheda (ISDA1) con eForm che prevede anche l’invio al TED (10 ,11 ,16 o 17). Tali eForm contengono uno specifico campo obbligatorio, il BT-766 ‘Sistema dinamico d’acquisizione’ da valorizzare indicando che si tratta di uno SDA. </p>
	</li>
</ol>

<ol start="2">
	<li data-aria-level="1" data-aria-posinset="2" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":2,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="2">
	<p>una scheda solo per la pubblicazione nazionale, (ISDA2) senza invio al TED e quindi senza eForm in cui nell’oggetto ‘DatiBaseStrumentoProcedura’ è necessario indicare obbligatoriamente che si tratta di uno SDA. </p>
	</li>
</ol>

<p>Ciascuna di queste schede (ISDA1 e ISDA2) sarà seguita da una nuova scheda S0 (usata per l’acquisizione dei partecipanti allo SDA) che può prevedere 3 tipi di ‘operazioni’: </p>

<ol start="1">
	<li data-aria-level="1" data-aria-posinset="1" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="3">
	<p>‘Richiesta di iscrizione’: comunicazione degli OE che hanno fatto richiesta di iscrizione e per cui si presume possa servire la verifica dei requisiti; </p>
	</li>
</ol>

<ol start="2">
	<li data-aria-level="1" data-aria-posinset="2" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="3">
	<p>‘Iscritto’: comunicazione degli OE già iscritti; </p>
	</li>
</ol>

<ol start="3">
	<li data-aria-level="1" data-aria-posinset="3" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="3">
	<p>‘cancellato’: comunicazione degli OE che chiedono di essere cancellati dall’elenco; </p>
	</li>
</ol>

<ol start="4">
	<li data-aria-level="1" data-aria-posinset="4" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="3">
	<p>‘variazione’: comunicazione variazione della composizione dell’RTI oppure variazione della ragione sociale; </p>
	</li>
</ol>

<p>Per la terminazione dello SDA sono state previste 2 nuove schede: </p>

<ol start="1">
	<li data-aria-level="1" data-aria-posinset="1" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="4">
	<p>Conclusione SDA con invio al TED (CSDA1) con rispettivo eForm (29, 30); </p>
	</li>
</ol>

<ol start="2">
	<li data-aria-level="1" data-aria-posinset="2" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="4">
	<p>Conclusione SDA senza invio al TED (CSDA2) senza eForm. </p>
	</li>
</ol>

<p>I bandi esecutivi degli SDA devono essere trasmessi attraverso la scheda P7_2. Nella stessa scheda, a livello di lotto, è necessario valorizzare il campo ‘condizione negoziata’ specificando la voce ‘appalto specifico nel Sistema Dinamico di Acquisizione’  <br>
Dopo la P7_2 segue il flusso ordinario. </p>
