### ISSUE TITLE
Schede P1_10 e P1_16 | P2_10 e P2_16 - Contesto di invio

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#469]
Salve @anac-uscp,

**TIPOLOGIA:  OR/PS/RO**

- **P1_16** - Scheda di pubblicazione avviso per un bando di gara **sopra la soglia europea e sotto soglia con invio al TED dell'eform16.** Bando di gara — direttiva generale, regime ordinario. Articolo 49 della direttiva 2014/24/UE. Articolo 84 decreto legislativo 36/2023. Articolo 85 decreto legislativo 36/2023.

- **P1_10**  Scheda di pubblicazione avviso per un bando di gara sopra la **soglia europea e sotto soglia con invio al TED dell'eform10.** Avviso di preinformazione utilizzato come avviso di indizione di gara — direttiva generale, regime ordinario. Articolo 48, paragrafo 2, della direttiva 2014/24/UE Articolo 81 comma 2 decreto legislativo 36/2023.

**TIPOLOGIA: OR/SS/RO**
-  **P2_10** Scheda di pubblicazione avviso per un bando di gara **sottosoglia maggiore di 5K** - Avviso di preinformazione utilizzato come avviso di indizione di gara — direttiva generale, regime ordinario. Articolo 48, paragrafo 2, della direttiva 2014/24/UE.

- **P2_16** - Scheda di pubblicazione avviso per un bando di gara **sottosoglia maggiore di 5K** - Bando di gara — direttiva generale, regime ordinario. Articolo 49 della direttiva 2014/24/UE

1. La descrizione delle schede P1 riporta sia "sopra" che "sotto" soglia, quindi tali schede sono da inviare **ANCHE** in caso nel caso di SS qualora si dovesse inviare il formulario?
2. Se si, allora quando devono essere inviate le P2, avendo la stessa tipologica delle P1?

**Comment by anac-uscp** [comment]
Le schede P1 devono essere utilizzate necessariamente nel caso di sopra soglia per la pubblicazione al TED.
Opzionalmente possono essere utilizzate anche sotto soglia qualora si voglia comunque procedere alla pubblicazione sul TED.
Nel caso di sotto soglia senza pubblicazione al TED devono essere utilizzate le P2 che non includono un eForm ma solo l'ANAC Form.
