### ISSUE TITLE
Scheda P3_1 - Contesto per invio

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#470]
Salve @anac-uscp,
la scheda:
P3_1 - Scheda di pubblicazione relativa ai contratti esclusi (generale o di tipo accordo quadro).

all'interno dell'orchestratore ha come tipologica solo R * , è possibile sapere qual è la condizione per cui tale scheda deve essere scelta?

**Comment by anac-uscp** [comment]
La scheda va utilizzata per comunicare gli affidamenti che rientrano nell'articolo 10 della direttiva 2014/24/UE e nell'articolo 21 della direttiva 2014/25/UE
