### ISSUE TITLE
Schede gruppo AD - ERR41 su esito conferma-appalto

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#472]
l'esito di conferma dell'appalto restituisce ERR41 -> errore generico durante la validazione dei dati della scheda
siamo bloccati su tutte le schede del gruppo AD.
JSON in allegato della AD2.25
[AD2_25.json](https://github.com/anticorruzione/npa/files/13164733/AD2_25.json)

**Comment by supportoAnac** [comment]
Il modello dati sarà aggiornato nel prossimo rilascio.

**Comment by labruno** [comment]
Quando è previsto il prossimo rilascio ?
