### ISSUE TITLE
CDC stazioni appaltanti - Informazioni mancanti

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#474]
Inviando una richiesta AD2_25, prendendo come spunto il payload inserito nell'issue #472 
Si riceve il seguente errore:
```json
{
	"status": 400,
	"title": "KO",
	"detail": "Errore",
	"type": "about:blank",
	"errori": [
		{
			"idTipologica": "errori",
			"dettaglio": "Codice Fiscale: XXXXXX- Codice Ausa: XXXXXX- Codice Centro di Costo: XXXXXXXXX",
			"codice": "ERR69"
		}
	]
}
```

Per quanto riguarda i valori `codiceFiscale` e `codiceAusa` abbiamo utilizzato quelli che ci sono stati recapitati nella mail.
Il campo `codiceCentroCosto` esattamente dove si può reperire?

**Comment by lauralu1993** [comment]
https://github.com/anticorruzione/npa/issues/445

**Comment by mladuDPA** [comment]
@lauralu1993 grazie mille
vorrei segnalare però che l'openapi fornito nella documentazione dell'e-service è incompleto.
Mancano i parametri della chiamata get.
[Specifica API Ausa.txt](https://github.com/anticorruzione/npa/files/13174861/Specifica.API.Ausa.txt)

Come da immagine
![immagine](https://github.com/anticorruzione/npa/assets/137039656/d6fcc0a5-abe6-41a9-a24b-8cba29d630a3)

**Comment by mpizziconi** [comment]
aggiorniamo la documentazione per l'eService ausaMS, nel frattempo inserisco qui una sintesi

/getBy?codiceFiscale=xxxxxxxxxxx&codiceAusa=xxxxxxxxxx

codiceFiscale e codiceAusa sono chiavi di ricerca alternative
possono essere utilizzati anche insieme ma il risultato è lo stesso (se coerenti: la query viene eseguita in "and")
