### ISSUE TITLE
Schede - Stato "In lavorazione" e "Confermata" (servizi conferma-scheda)

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#475]
Buongiorno,

è corretto che per lo stato delle schede siano previsti solo gli stati "In lavorazione" e "Confermata"? i controlli sulla correttezza dei dati inviati avvengono tutti prima di recepire la scheda da parte di ANAC?

Grazie

**Comment by supportoAnac** [comment]
Gli stati previsti per le schede non sono solo quelli citati. L’elenco completo è disponibile nella tipologica statoScheda.json. I controlli avvengono tutti prima di passare la scheda in stato confermata.
