### ISSUE TITLE
Scheda AD4 - Chiarimenti contesto di invio

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#476]
Salve @anac-uscp,

la scheda Scheda AD4 - Scheda di adesione AQ/convenzione senza successivo confronto competitivo, senza invio al TED, dovrà essere inviata per gli affidamenti diretti discententi da AQ e per gli ordini da negozio elettronico?

SI richiede chiarimento sul contesto di invio di tale scheda.

**Comment by anac-uscp** [comment]
La scheda AD4 viene usata dalle stazioni appaltanti che aderiscono ad un accordo quadro/convenzione stipulata da una centrale di committenza, situazione che comporta la generazione di un CIG padre e di uno o più CIG figli.
Se per “negozio elettronico” si intende il contenitore di tutti gli accordi quadro/convenzioni stipulate da una centrale di committenza allora sì, bisogna usare la scheda AD4 (quando non c’è rilancio competitivo) per aderire ad una singola convenzione ad un singolo accordo quadro contenuto nel negozio elettronico, generando dal CIG padre della singola convenzione/accordo i vari CIG figli.
Se per “negozio elettronico” si intende una sorta di elenco fornitori, da usare per gli affidamenti sottosoglia allora bisogna usare:
1)	la scheda P7_2 in caso di procedura negoziata in cui gli invitati sono stati selezionati tra gli iscritti all’elenco
2)	La scheda AD3 in caso di affidamento diretto ad un operatore iscritto all’elenco
