### ISSUE TITLE
Scheda AD5 - Error 400 in crea-appalto

### ISSUE THREAD

**Issue by cragazzi** [anticorruzione/npa#477]
Buongiorno,
quando inviamo una scheda AD5 con la chiamata crea-appalto, riceviamo il seguente errore:
{
   "status":400,
   "title":"KO",
   "detail":"Errore",
   "type":"about:blank",
   "errori":[
      {
         "idTipologica":"errori",
         "codice":"No anacForm or stazioniAppaltanti in input"
      }
   ]
}
Però l'anacForm è presente nel json inviato, mentre il blocco stazioni appaltanti non è previsto dalle specifiche per la scheda AD5.
Potete verificare ed indicarci qual è il problema?

Grazie

**Comment by supportoAnac** [comment]
Il modello dati sarà aggiornato nel prossimo rilascio.

**Comment by lelio-raffaelli** [comment]
Mi inserisco qua, perché anche noi abbiamo lo stesso problema: quando è previsto il prossimo rilascio?
