### ISSUE TITLE
Servizio Consulta-Scheda - Richiesta integrazione schema dati schede AD (ad es. AD1_25)

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#478]
Al fine di poter recuperare in fase esecutiva le informazioni relative all'aggiudicatario si è proceduti ad analizzare all’interno dei servizi esposti da FVA la sezione dati aggiuntivi dove sono riportate tutte le schede istanziate dalla precedente fase:

datiAggiuntivi  string
example: {appalto : {idAppalto: 35553535K}, schede:[{ id:566eb3c704c7b31facbb0007, nome:P1.10, dataInserimento:2015-05-28T14:07:17Z, idAppalto:35553535K, espd:54495ad94c934721ede76d90, eform:566eb3c704c7b31facbb0007}]}

Dall’esito di questa response si può dunque ricavare l’idScheda relativo alle schede di aggiudicazione.

Attraverso l’interrogazione del servizio consulta-scheda si ha dunque la possibilità di accedere al dettaglio della scheda e dunque all’idpartecipante e aggiudicatario.

Si fa però presente che nell’output del servizio consulta-scheda sono assenti le tipologie “AD” e pertanto le informazioni relativamente a queste schede non risulterebbero recuperabili.

Poichè da tali tipologie di schede si ha la necessità di avviare successivamente il contratto con una scheda di tipo “SC1” si richiede di integrare lo schema dati all'interno del servizio di consultazione scheda

**Comment by supportoAnac** [comment]
La richiesta verrà valutata.
