### ISSUE TITLE
Cartella "Regole" - Schede previste per Esecuzione (ad es. SC1)

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#479]
Nella cartella “Regole” contenuta nel modello dati in github, non sono presenti i file di regole relativi a gran parte delle schede previste nella fase di esecuzione:
SC1, I1, M1, M2, SA1, RSU1, ES1, CS1, SO1, SQ1, RI1, AC1, IR1, S4

Si richiede l’integrazione delle schede mancanti

**Comment by supportoAnac** [comment]
Le regole sono state pubblicate con l'ultimo changelog.
https://github.com/anticorruzione/npa/blob/main/CHANGELOG.md
