### ISSUE TITLE
Prossimi rilasci

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#480]
Buongiorno,
anche alla luce della risposta fornita in https://github.com/anticorruzione/npa/issues/457 e https://github.com/anticorruzione/npa/issues/460
E' possibile conoscere in anticipo la data del rilascio?
In alternativa è possibile riceverne notifica mediante issue specifica sul canale github?

Grazie

**Comment by mpizziconi** [comment]
il rilascio è previsto per la settimana 6-10 novembre
