### ISSUE TITLE
Invio Scheda p3_1

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#482]
Salve,
 in relazione alla #470 all'interno dell'orchestratore l'eform è indicato come "NON previsto". 

Nel caso di una procedura con contratto escluso e bando compilato, questa scheda va mandaa DOPO la scheda contenente l'eform?

**Comment by anac-uscp** [comment]
Per i contratti escluso non è previsto l'eForm. Tali tipi di contratti non vanno pubblicati sul TED.
