### ISSUE TITLE
Appalto SDAPA - Schede da adoperare

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#484]
Per la pubblicazione di un appalto specifico SDAPA (no bando istitutivo) quale/i scheda/e di indizione è opportuno adoperare? Sull'orchestratore non sembra essere presente alcuna scheda "dedicata" e alcun riferimento normativo al Sistema dinamico di acquisizione (art. 32 del codice dei contratti pubblici).

**Comment by anac-uscp** [comment]
Il tipo di scheda da inviare dipende dal tipo di appalto. Le eForm contengono il campo BT-766 ‘Dynamic Purchasing System’ per indicare che si tratta di un sistema dinamico di acquisizione.
