### ISSUE TITLE
Post pubblicazione - Flusso pubblicazione bando

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#485]
Salve,
In merito alla issues #221

Chiedo conferma che il flusso che permette poi  la pubblicazione al TED di un bando di aggiudicazione avviene in questo modo:

- Invio Scheda S1 o S2
- Invio tramite "CREA-SCHEDA" --> Scheda A1_XX (che necessariamente contiene l'eForm). 

In questo caso l'eForm di aggiudicazione deve essere già compilato ma non ancora pubblicato al TED? 
O può essere pubblicato anche dopo il Conferma-scheda?

**Comment by mpizziconi** [comment]
l'espressione "bando di aggiudicazione" è ambigua.
se ci si riferisce ad un "avviso di avvenuta aggiudicazione" allora si, corretta la corretta sequenza di invii è:
S1 e/o S2
A1_xx contenente eForm

la pubblicazione su TED avviene ad esito positivo dell'operazione conferma-scheda (A1_xx) del contesto comunicaPostPubblicazione. L'invocazione del servizio pubblica-avviso è eseguita in back-end e non deve essere ripetuta dall'utente
