### ISSUE TITLE
Servizi conferma-appalto | Scheda S2 - ERRORE  invio dopo aver CONFERMATO l'appalto con la P6.1

### ISSUE THREAD

**Issue by mpizziconi** [anticorruzione/npa#486]
dopo aver CONFERMATO l'appalto con la P6.1 abbiamo inviato la scheda S2 come riportato nell'orchestratore.
l'esito è ERR2 -  scheda non ammessa in questa fase dell'appalto

<img width="702" alt="image" src="https://github.com/anticorruzione/npa/assets/142924847/fdc4de2c-1887-42d6-8a7d-e711278ce02e">

_Originally posted by @lauralu1993 in https://github.com/anticorruzione/npa/issues/464#issuecomment-1781735468_

**Comment by mpizziconi** [comment]
per seguire il log abbiamo bisogno dei riferimenti di tracciatura contenuti nel JWS e idAppalto

**Comment by lauralu1993** [comment]
CLIENT ID = 01e2efc4-f2cd-40f4-bac1-05e7c6dcefba
ID APPALTO= d272fbd2-e3fe-4104-a83a-0773e51855c6

**Comment by supportoAnac** [comment]
Anomalia superata da rilasci successivi.
