### ISSUE TITLE
URGENTE: Contatto AGID

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#488]
Non so se qui c'è qualcuno di Agid che legge e può darci una risposta.
Sono settimane che proviamo a contattarvi con ogni canale a disposizione, email, pec, telefonate.
Abbiamo aperto ticket per problemi su eIDAS da 14 giorni, ad oggi nemmeno presi in carico.

Come possiamo fare per parlare con qualcuno? 
Non è concepibile questo modo di "fornire supporto" a 30 giorni lavorativi dalla scadenza per la certificazione.

Chiedo anche ad altri di intervenire per capire se il problema è solo nostro

**Comment by mfortini** [comment]
Related #370

**Comment by mfortini** [comment]
Riporto quanto ricevuto da AgID:

> la issue non ha i dettagli necessari ad una individuazione del problema, e quindi ad una sua soluzione.
> 
> Il nodo eIDAS italiano di qualificazione funziona. Essendo stato aggiornato una decina di giorni fa, è possibile che, nelle fasi di passaggio, ci sia stato un breve intervallo di tempo durante il quale il nodo risultava irraggiungibile.
> 
> Quanto al fatto che il servizio di help desk non risponde, sarebbe meglio indicare il numero di ticket che ha ricevuto e lo esamineremo.
>

**Comment by pakozack** [comment]
ticket YNJ-QJ2-73JM

**Comment by pakozack** [comment]
Ad oggi ancora niente...

**Comment by pakozack** [comment]
Si sollecita un riscontro

**Comment by fvabra89** [comment]
Il problema relativo al ticket in questione risulta essere stato risolto e chiuso su richiesta dello stesso utente che lo ha aperto.

**Comment by pakozack** [comment]
Questa issue è stata chiusa ma intanto noi non siamo riusciti ad avere un contatto con AGID.
