### ISSUE TITLE
Scheda NAG per procedure con stato "Non aggiudicata" e "Deserta"

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#490]
Salve @anac-uscp,
la Scheda **NAG - Scheda di mancata aggiudicazione della gara,** nell' esitoProceduraAnnullata sono presenti solo:

[{
    "codice":"6",
    "descrizione": {
		"it": "annullata/revocata prima dell’avvio della procedura di selezione",
		"en": "annullata/revocata prima dell’avvio della procedura di selezione"
		},
    "dataInizio":null,
    "dataFine":null
},
{
    "codice":"7",
    "descrizione": {
		"it": "annullata/revocata dopo l’avvio della procedura di selezione",
		"en": "annullata/revocata dopo l’avvio della procedura di selezione"
		},
    "dataInizio":null,
    "dataFine":null
}]

**Quale scheda mandiamo per le procedure con stato "NON aggiudicata" e "Deserta"?**

**Comment by UserM21** [comment]
@supportoAnac si richiede un riscontro

**Comment by anac-uscp** [comment]
Per le procedure che prevedono la trasmissione dell'efom bisogna compilare i cambi BT-142 e BT-144 nella scheda di aggiudicazione.
Per le procedure che non prevedono la trasmissione dell'efom bisogna inviare la scheda NAG e compilare il campo "datiBaseRisultatoProcedura.giustificazione" che contiene i valori della tipologica del TED  ‘Non Award  Justification’ relativa al campo BT-144. 
La tipologica citata nella issue serve solamente all'ANAC per valutare i casi in cui deve rimborsare all'operatore economico il contributo che quest'ultimo ha pagato.
