### ISSUE TITLE
Scheda P6.2 - Errori incoerenti su esito conferma appalto

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#491]
abbiamo provato a confermare un appalto creato con la scheda P6.2.
il servizio riporta i seguenti errori:
1) ERR15 - lotIdentifier non coerenti tra eForm ed anacForm
2) ERR37 - codiceAppalto obbligatorio
3) ERR38 - codiceAppalto già presente

il primo errore è incoerente con la scheda, la quale non prevede EFORM.
gli errori 2 e 3 sono in contrasto tra loro (oltretutto, se l'idappalto esiste gia viene rilevato dal crea-appalto)

**Comment by mpizziconi** [comment]
è necessario specificare un id di tracciatura per recuperare il log della transazione.

PS
codiceAppalto e idAppalto sono due oggetti differenti

**Comment by lauralu1993** [comment]
trattasi di refuso (se il codiceAppalto è già presente il servizio restituisce errore su crea-appalto).
idAppalto=e7cf0cac-0bd1-4c8e-a0a6-1611f62f30b8 
clientId=01e2efc4-f2cd-40f4-bac1-05e7c6dcefba
