### ISSUE TITLE
Versione SDK 1.7 vs 1.9

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#492]
Buongiorno,
prendo atto della risposta fornita nella issue https://github.com/anticorruzione/npa/issues/216.
Tuttavia chiedo di indicarmi i motivi per i quali non può essere gestito la versione sdk secondo le tempistiche indicate da TED.

Provo a spiegarmi meglio.
Oggi il TED, continua a recepire la versione 1.7
Se Anac si limita a passare l'eform a TED, il quale si occupa di validarne il contenuto, dovrebbe essere logico supportare le versioni supportate dal TED.
In caso contrario vi chiedo gentilmente di esplicitare quali sono i motivi o le info dell'SDK per i quali non è possibili supportare versioni precendenti la 1.9 
Aggiungo che la versione 1.9 non risulta stabile pertanto si corre il rischio che venga richiesto di utilizzare una ulteriore versione. Vedi appuntoquanto riportato nella issue https://github.com/anticorruzione/npa/issues/489

**Comment by mpizziconi** [comment]
I serrvizi PCP non sono limitati all'invio delle eNotices a TED
