### ISSUE TITLE
AnacForm: campi non contrassegnati con l'asterisco

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#493]
Salve,

Stiamo procedendo ad effettuare i test per alcune schede, nello specifico P2_16.
Il servizio crea-appalto però ci restituisce il seguente errore per i campi facoltativi.

_$.anacForm.lotti[0].modalitaAcquisizione: null found, object expected_
 oppure 
 _$.anacForm.lotti[0].modalitaAcquisizione.codice: null found, string expected
 $.anacForm.lotti[0].modalitaAcquisizione.idTipologica: null found, string expected_

![immagine](https://github.com/anticorruzione/npa/assets/144692462/37c351b8-5836-4df1-9727-f03c90a99b2e)

- Come da immagine allegata, lo swagger non contrassegna con l'asterisco il campo in questione "modalitaAcquisizione" pertanto, essendo un campo facoltativo non mi aspetto tale errore.
- Come ci dobbiamo comportare con i campi identificati come "facoltativi" nello swagger, dato che questo errore emerge anche con altri campi "facoltativi"

**Comment by supportoAnac** [comment]
modalitaAcquisizione è un campo la cui obbligatorietà è condizionata da una regola (REG29: Modalità Acquisizione: il campo è obbligatorio se l'oggetto del contratto è 'Servizi' o 'Forniture'.) quindi non esplicitamente obbligatorio sullo yaml.
Si richiede di verificare i dati inviati e confrontarli con i requisiti della regola.
