### ISSUE TITLE
Scheda P1.16 - Obbligatorietà del campo linkDocumenti

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#495]
inviando una scheda P1.16 senza il campo linkDocumenti il servizio restituisce:
 REG8 - Il campo deve essere una url valida e iniziare per http oppure per https.
aggiungendo il campo si ottiene la conferma dell'appalto.
facciamo notare che il campo linkDocumenti  non è indicato come obbligatorio nello swagger.

**Comment by anac-uscp** [comment]
L'errore sarà corretto nel prossimo rilascio
