### ISSUE TITLE
Scheda P7_2 - Flusso appartenenza

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#496]
Buongiorno,

dal flusso di appartenenza nel file Orchestratore, risulta che per la scheda P7_2 (RDO da Elenco) che dà avvio alla negoziata senza bando non è prevista alcuna scheda di aggiudicazione, è corretto?

Grazie,
Luca

**Comment by paolo-urbanetto** [comment]
Buongiorno, mi aggiungo.
Per la mancata aggiudicazione è prevista la NAG, per l'aggiudicazione? La A2_29 forse?
Non c'è il numero flusso su nessuna aggiudicazione...

**Comment by anac-uscp** [comment]
Dopo l'invio della schedap P7_2 per una procedura negoziata sotto soglia bisogna inviare  una delle schede di aggiudicazione di  appalto, sopra o sotto soglia, settore ordinario, settore speciale, settore difesa e sicurezza. Al momento il flusso 72 non è stato inserito nelle schede di aggiudicazione. L'orchestratore verrà aggiornato al primo rilascio utile che non avverrà prima dell’esercizio della piattaforma.

**Comment by simonacoppari** [comment]
Ad oggi non risulta ancora aggiornato, abbiamo inviato a che PEC ad ANAC per sollevare la criticità
