### ISSUE TITLE
Scheda P1_16 - Specifica di più stazioni appaltanti

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#497]
Nelle schede di pubblicazione avviso, ad esempio P1.16, c'è la possibilità di specificare più stazioni appaltanti.
In quali casi va specificata più di una stazione appaltante? Solo nel caso di delega 1-1? Oppure anche nel caso in cui la titolare agisca per conto di diverse amministrazioni?

**Comment by anac-uscp** [comment]
La possibilità di specificare più stazioni appaltanti si usa quando la  titolare agisce per conto di diverse amministrazioni
