### ISSUE TITLE
Schede pubblicazione avviso (ad es. P1_16) - Funzioni svolte dalla stazione appaltante (servizi pubblica-avviso)

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#499]
Nelle schede di pubblicazione avviso, ad esempio P1.16, nel caso di compilazione nell'oggetto StazioneAppaltanteType del  campo funzioniSvolte, è obbligatorio che sia inserita (almeno) una stazione appaltante non titolare?

**Comment by anac-uscp** [comment]
Il campo "funzioniSvolte" non è obbligatorio. Il campo va compilato se c'è una stazione appaltante non titolare.
