### ISSUE TITLE
modifiche dell'appalto post rilascio CIG

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#5]
Occorre chiarire se l'appalto può subire modifiche (ed in caso quali) in fase successiva all’invocazione del servizio conferma-appalto (evento che crea i CIG per l'appalto in questione).  In questo momento il flusso NPA non sembra permettere modifiche e il servizio conferma-appalto può essere richiamato UNA sola volta. In questo caso come si può aggiungere/eliminare/modificare lotti?

**Comment by supportoAnac** [comment]
1. Prima del confermaAppalto il servizio modifica-appalto permette la sostituzione della precedente istanza dell’Appalto in lavorazione.
2. Dopo il confermaAppalto e prima del pubblicaAvviso non è possibile effettuare modifiche.  Eventualmente è permessa solo la cancellazione.
3. Per le sole procedure che prevedono la pubblicazione TED, dopo il confermaAppalto e dopo il pubblicaAvviso è possibile inviare un avviso di modifica (modifica-avviso) se la richiesta di pubblicazione non è ancora avvenuta. In questa fase è permessa anche la modifica dei lotti. Invece, se la pubblicazione è già avvenuta è possibile solo inviare un avviso di rettifica (rettifica-avviso) con le sole informazioni rettificabili.

**Comment by pg-volpentesta** [comment]
Rispetto al terzo punto: significa che per le procedure per cui non è prevista la pubblicazione\invio al TED (es: ordini) NON sono possibili modifiche né dopo il conferma-appalto né dopo il pubblica-avviso?

**Comment by federicodemarco** [comment]
@pg-volpentesta ti ritrovi con i dubbi esposti nella issue: https://github.com/anticorruzione/npa/issues/529
