### ISSUE TITLE
ComunicaAppalto - Chiarimenti processo

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#503]
Buongiorno,

Con riferimento al diagramma degli stati presente nel documento npa_documento-specifiche-servizi.pdf:

L'appalto in stato 'confermato':

- può essere soggetto ad una cancellazione automatica se non viene invocato il servizio 'pubblicaAvviso' si chiede di specificare l'intervallo di tempo che intercorre tra la conferma e questo automatismo;

- nelle documento orchestratore schema-cronologia-schede.xls la colonna M 'E' possibile pubblicare sulla piattaforma di pubblicità legale di ANAC' la presenza del valore 'SI' è da intendersi che obbligatoriamente bisogna invocare il servizio 'pubblicaAvviso' e attendere che lo stato dell'appalto passi in 'pubblicato'?

- in questo stato tutte le informazioni inviate dalla creaAppalto (e successive modificaAppalto) sono da intendersi non più modificabili? Quindi in caso di errori riscontrati sulla gara dopo la conferma l'unica possibilità, prima della pubblicazione, è il cancellaAppalto

**Comment by mpizziconi** [comment]
1 - la cancellazione di appalti confermati ma non pubblicati al momento è prevista trascorsi 90 giorni dalla conferma. La specifica può cambiare nell'interazione con PCP delle piattaforme.
2 - l'instradamento dell'avviso sul canale PVL (piattaforma a valore legale) o sul TED avviene in automatico ove previsto dallo schema di orchestrazione. L'invocazione del servizio di pubblicazione è richiesta solo per le schede di indizione (ovvero che assegnano il CIG ai lotti) negli altri casi è automatica dopo l'operazione di conferma
3 - la modifica delle informazioni è possibile con le operazioni modifica o rettifica avviso utilizzabili a seconda dei casi: se l'avviso non è stato schedulato per la pubblicazione può essere modificato, altrimenti verrà pubblicato ed è necessaria la rettifica

**Comment by federicodemarco** [comment]
Ciao @dpagliari per cancellazione automatica cosa intendi? Intendi una cancellazione effettuata dalla PCP sulla base del fatto che il CIG non sia stato usato dopo 90 giorni dal suo prelevamento?
In caso affermativo allora la piattaforma di eproc, mediante apposito servizio, dovrebbe consultare la PCP per importare lo stato "cancellato".

Grazie
