### ISSUE TITLE
Repository schede

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#506]
Buongiorno,

potete mettere a disposizione un repository di schede relative ai diversi contesti (comunicaAppalto, pubblicaAvviso,...) con dati significativi e corretti?

**Comment by anac-uscp** [comment]
è stato messo a disposizine un unico flusso di esempio per raggiungere la fase di esecuzione e al momento non è prevsita l'estensione con ulteriori casi/scenari di esempio
