### ISSUE TITLE
Scheda P2_10  - Errore

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#508]
Stiamo testando crea-appalto con scheda P2_10

Inviamo il seguente
<details>
  <summary>payload</summary>

```json
{
  "anacForm": {
    "stazioniAppaltanti": [
      {
        "codiceFiscale": "1",
        "codiceAusa": "2",
        "codiceCentroCosto": "3",
        "saTitolare": true
      }
    ],
    "appalto": {
      "codiceAppalto": "tender1",
      "motivoUrgenza": {
        "idTipologica": "motivoUrgenza",
        "codice": "7"
      },
      "categorieMerceologiche": [
        {
          "idTipologica": "CategorieMerceol",
          "codice": "2"
        }
      ]
    },
    "lotti": [
      {
        "lotIdentifier": "LOT-12",
        "categorieMerceologiche": [
          {
            "idTipologica": "CategorieMerceologiche",
            "codice": "2"
          }
        ],
        "contrattiDisposizioniParticolari": {
          "idTipologica": "contrattiDisposizioniParticolari",
          "codice": "1"
        },
        "codIstat": {
          "idTipologica": "codIstat",
          "codice": "1001003"
        },
        "afferenteInvestimentiPNRR": false,
        "prestazioniComprese": {
          "idTipologica": "prestazioniComprese",
          "codice": "1"
        },
        "ripetizioniEConsegneComplementari": false,
        "ccnl": "non applicabile",
        "tipologiaLavoro": [
          {
            "idTipologica": "tipologiaLavoro",
            "codice": "6"
          }
        ],
        "opzioniRinnovi": true,
        "categoria": {
          "idTipologica": "categoria",
          "codice": "999"
        }
      }
    ]
  },
  "espd": "TG9yZW0gSXBzdW0gw6ggdW4gdGVzdG8gc2VnbmFwb3N0byB1dGlsaXp6YXRvIG5lbCBzZXR0b3JlIGRlbGxhIHRpcG9ncmFmaWEgZSBkZWxsYSBzdGFtcGEuIExvcmVtIElwc3VtIMOoIGNvbnNpZGVyYXRvIGlsIHRlc3RvIHNlZ25hcG9zdG8gc3RhbmRhcmQgc2luIGRhbCBzZWRpY2VzaW1vIHNlY29sbywgcXVhbmRvIHVuIGFub25pbW8gdGlwb2dyYWZvIHByZXNlIHVuYSBjYXNzZXR0YSBkaSBjYXJhdHRlcmkgZSBsaSBhc3NlbWJsw7IgcGVyIHByZXBhcmFyZSB1biB0ZXN0byBjYW1waW9uZS4gw4ggc29wcmF2dmlzc3V0byBub24gc29sbyBhIHBpw7kgZGkgY2lucXVlIHNlY29saSwgbWEgYW5jaGUgYWwgcGFzc2FnZ2lvIGFsbGEgdmlkZW9pbXBhZ2luYXppb25lLCBwZXJ2ZW5lbmRvY2kgc29zdGFuemlhbG1lbnRlIGluYWx0ZXJhdG8uIEZ1IHJlc28gcG9wb2xhcmUsIG5lZ2xpIGFubmkg4oCZNjAsIGNvbiBsYSBkaWZmdXNpb25lIGRlaSBmb2dsaSBkaSBjYXJhdHRlcmkgdHJhc2ZlcmliaWxpIOKAnExldHJhc2V04oCdLCBjaGUgY29udGVuZXZhbm8gcGFzc2FnZ2kgZGVsIExvcmVtIElwc3VtLCBlIHBpw7kgcmVjZW50ZW1lbnRlIGRhIHNvZnR3YXJlIGRpIGltcGFnaW5hemlvbmUgY29tZSBBbGR1cyBQYWdlTWFrZXIsIGNoZSBpbmNsdWRldmEgdmVyc2lvbmkgZGVsIExvcmVtIElwc3VtLg"
}
```
</details>

ed otteniamo

<details>
  <summary> l'errore</summary>

{"status"=>400, "title"=>"KO", "detail"=>"Errore Validazione JSON Schema", "type"=>"about:blank", "errori"=>[{"idTipologica"=>"errori", "dettaglio"=>"$.anacForm.lotti[0].lottoP210TypeAfferenteInvestimentiPNRR: is missing but it is required", "codice"=>"ERR4"}, {"idTipologica"=>"errori", "dettaglio"=>"$.anacForm.lotti[0].lottoP210TypeCategorieMerceologiche: is missing but it is required", "codice"=>"ERR4"}, {"idTipologica"=>"errori", "dettaglio"=>"$.anacForm.lotti[0].lottoP210TypeCodIstat: is missing but it is required", "codice"=>"ERR4"}, {"idTipologica"=>"errori", "dettaglio"=>"$.anacForm.lotti[0].lottoP210TypeContrattiDisposizioniParticolari: is missing but it is required", "codice"=>"ERR4"}, {"idTipologica"=>"errori", "dettaglio"=>"$.anacForm.lotti[0].lottoP210TypeLotIdentifier: is missing but it is required", "codice"=>"ERR4"}]}

</details>

Abbiamo inoltre provato ad inviare un dato sbagliato nel campo "afferenteInvestimentiPNRR", vedi 

<details>
  <summary>payload</summary>

```json
{
  "anacForm": {
    "stazioniAppaltanti": [
      {
        "codiceFiscale": "1",
        "codiceAusa": "2",
        "codiceCentroCosto": "3",
        "saTitolare": true
      }
    ],
    "appalto": {
      "codiceAppalto": "tender1",
      "motivoUrgenza": {
        "idTipologica": "motivoUrgenza",
        "codice": "7"
      },
      "categorieMerceologiche": [
        {
          "idTipologica": "CategorieMerceol",
          "codice": "2"
        }
      ]
    },
    "lotti": [
      {
        "lotIdentifier": "LOT-12",
        "categorieMerceologiche": [
          {
            "idTipologica": "CategorieMerceologiche",
            "codice": "2"
          }
        ],
        "contrattiDisposizioniParticolari": {
          "idTipologica": "contrattiDisposizioniParticolari",
          "codice": "1"
        },
        "codIstat": {
          "idTipologica": "codIstat",
          "codice": "1001003"
        },
        "afferenteInvestimentiPNRR": "SBAGLIATOXXXXXX",
        "prestazioniComprese": {
          "idTipologica": "prestazioniComprese",
          "codice": "1"
        },
        "ripetizioniEConsegneComplementari": false,
        "ccnl": "non applicabile",
        "tipologiaLavoro": [
          {
            "idTipologica": "tipologiaLavoro",
            "codice": "6"
          }
        ],
        "opzioniRinnovi": true,
        "categoria": {
          "idTipologica": "categoria",
          "codice": "999"
        }
      }
    ]
  },
  "espd": "TG9yZW0gSXBzdW0gw6ggdW4gdGVzdG8gc2VnbmFwb3N0byB1dGlsaXp6YXRvIG5lbCBzZXR0b3JlIGRlbGxhIHRpcG9ncmFmaWEgZSBkZWxsYSBzdGFtcGEuIExvcmVtIElwc3VtIMOoIGNvbnNpZGVyYXRvIGlsIHRlc3RvIHNlZ25hcG9zdG8gc3RhbmRhcmQgc2luIGRhbCBzZWRpY2VzaW1vIHNlY29sbywgcXVhbmRvIHVuIGFub25pbW8gdGlwb2dyYWZvIHByZXNlIHVuYSBjYXNzZXR0YSBkaSBjYXJhdHRlcmkgZSBsaSBhc3NlbWJsw7IgcGVyIHByZXBhcmFyZSB1biB0ZXN0byBjYW1waW9uZS4gw4ggc29wcmF2dmlzc3V0byBub24gc29sbyBhIHBpw7kgZGkgY2lucXVlIHNlY29saSwgbWEgYW5jaGUgYWwgcGFzc2FnZ2lvIGFsbGEgdmlkZW9pbXBhZ2luYXppb25lLCBwZXJ2ZW5lbmRvY2kgc29zdGFuemlhbG1lbnRlIGluYWx0ZXJhdG8uIEZ1IHJlc28gcG9wb2xhcmUsIG5lZ2xpIGFubmkg4oCZNjAsIGNvbiBsYSBkaWZmdXNpb25lIGRlaSBmb2dsaSBkaSBjYXJhdHRlcmkgdHJhc2ZlcmliaWxpIOKAnExldHJhc2V04oCdLCBjaGUgY29udGVuZXZhbm8gcGFzc2FnZ2kgZGVsIExvcmVtIElwc3VtLCBlIHBpw7kgcmVjZW50ZW1lbnRlIGRhIHNvZnR3YXJlIGRpIGltcGFnaW5hemlvbmUgY29tZSBBbGR1cyBQYWdlTWFrZXIsIGNoZSBpbmNsdWRldmEgdmVyc2lvbmkgZGVsIExvcmVtIElwc3VtLg"
}
```
</details>

ed otteniamo il seguente errore

<details>
  <summary>errore</summary>

{"status"=>400, "title"=>"KO", "detail"=>"Errore Validazione JSON Schema", "type"=>"about:blank", "errori"=>[{"idTipologica"=>"errori", "dettaglio"=>"$.anacForm.lotti[0].lottoP210TypeAfferenteInvestimentiPNRR: is missing but it is required", "codice"=>"ERR4"}, {"idTipologica"=>"errori", "dettaglio"=>"$.anacForm.lotti[0].lottoP210TypeCategorieMerceologiche: is missing but it is required", "codice"=>"ERR4"}, {"idTipologica"=>"errori", "dettaglio"=>"$.anacForm.lotti[0].lottoP210TypeCodIstat: is missing but it is required", "codice"=>"ERR4"}, {"idTipologica"=>"errori", "dettaglio"=>"$.anacForm.lotti[0].lottoP210TypeContrattiDisposizioniParticolari: is missing but it is required", "codice"=>"ERR4"}, {"idTipologica"=>"errori", "dettaglio"=>"$.anacForm.lotti[0].lottoP210TypeLotIdentifier: is missing but it is required", "codice"=>"ERR4"}, {"idTipologica"=>"errori", "dettaglio"=>"$.anacForm.lotti[0].afferenteInvestimentiPNRR: string found, boolean expected", "codice"=>"ERR4"}]}

</details>

A quanto pare effettivamente il campo viene in qualche modo letto. Sulla richiesta errata infatti l'errore è  string found, boolean expected.

Potete fornirci supporto?

**Comment by pakozack** [comment]
Si sollecita un riscontro

**Comment by mariottiDPA** [comment]
@mpizziconi mi accodo alla issue perché anche a noi la creazione della P2_10 dà gli stessi errori (e anche quasi tutte le altre della famiglia P2). Ci confermate che il problema sarà risolto con il prossimo rilascio? Ci sono delle tempistiche su quando questo avverrà?

**Comment by pakozack** [comment]
Dopo 2 settimane aggiornamento effettuato. Adesso errore 401

**Comment by pakozack** [comment]
L'errore sembra essere risolto
