### ISSUE TITLE
Fruizione PCP - CODELIST - error 400

### ISSUE THREAD

**Issue by cbaldo** [anticorruzione/npa#517]
Riceviamo l'error 400 lamentato da altri ma non riusciamo a capire la causa dell'errore. Questa la risposta ricevuta dopo aver fatto altro tentativi che portano sempre allo stesso esito:
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "373a9f7c-77a2-11ee-b4a0-0050568e08b3"
}

è possibile avere un chiarimento sui motivi dell'errore. Se necessario per una migliore diagnosi possiamo inviare i dati scambiati

**Comment by mpizziconi** [comment]
questo l'errore legato al JWS

Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
[GOVWAY-661] [Header 'Agid-JWT-TrackingEvidence'] Token scaduto in data '2023-10-31_06:55:37.000'
[GOVWAY-661] [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2023-10-31_06:45:37.000')
