### ISSUE TITLE
Scheda AD5 - Crea Appalto - Errore "anacForm"

### ISSUE THREAD

**Issue by cristiano-perin** [anticorruzione/npa#518]
Buongiorno,

Inviando il seguente payload all'API crea-appalto otteniamo l'errore riportato sotto

```
{
   "scheda":{
      "type":"SchedaComunicaAppaltoType",
      "codice":{
         "idTipologica":"codiceScheda",
         "codice":"AD5"
      },
      "versione":"1.0",
      "body":{
         "type":"SchedaAD5Type",
         "anacForm":{
            "appalto":{
               "codiceAppalto":"c28a20cf-7266-463d-a3ad-4d10140bbd8e",
               "codiceFiscaleSA":"01386030488",
               "denominazioneSA":"Regione Toscana"
            },
            "aggiudicazioni":[
               {
                  "lotIdentifier":"48077d5b-99b8-4910-8549-678d0b975607",
                  "oggettoPrincipaleContratto":{
                     "idTipologica":"oggettoPrincipaleContratto",
                     "codice":"L"
                  },
                  "cup":"C99H19000370003",
                  "aggiudicatario":{
                     "codiceFiscale":"PRNCSTXXXXX",
                     "denominazione":"Cristiano Perin",
                     "importo":1000.0
                  }
               }
            ]
         }
      }
   }
}
```
risposta:

```
{
   "errori":[
      {
         "idTipologica":"errori",
         "codice":"No anacForm or stazioniAppaltanti in input"
      }
   ],
   "detail":"Errore",
   "title":"KO",
   "type":"about:blank",
   "status":400
}
```

Avete qualche info a riguardo?
Ci sembra che il payload inviato, a meno di dati di test, sia corretto.

Grazie

**Comment by davideorsi-bit** [comment]
Buongiorno lo stesso problema lo riscontriamo chiamando da client ARIA (MIAP) di seguito payload :
{
	"scheda": {
		"type": "SchedaComunicaAppaltoType",
		 "codice": {
			"idTipologica": "codiceScheda",
			"codice": "AD5"
		},
		"versione": "1.0",
		
		"body": {
			"type": "SchedaAD5Type",
			"anacForm": {
				"appalto": {
					"idAppalto": "appaltoid1",
					"codiceAppalto": "codappalto1",
					"codiceFiscaleSA": "5017630152",
					"denominazioneSA": "ARIA"
				}
				
			}
		}
	}
}

e risposta : 
{
    "status": 400,
    "error": "BAD_REQUEST",
    "type": "",
    "code": 0,
    "timestamp": "2023-11-08T13:12:50.340+00:00",
    "title": "Bad Request",
    "details": "Invalid or missing parameter(s)",
    "subErrors": [
        {
            "subErrorType": "ApiValidationSubError",
            "parameter": "Bad Request",
            "reason": "{\"status\":400,\"title\":\"KO\",\"detail\":\"Errore\",\"type\":\"about:blank\",\"errori\":[{\"idTipologica\":\"errori\",\"codice\":\"No anacForm or stazioniAppaltanti in input\"}]}"
        }
    ]
}

**Comment by paolo-urbanetto** [comment]
@mpizziconi  [BLK] abbiamo provato anche oggi: stesso risultato: "No anacForm or stazioniAppaltanti in input".

Ma ieri è stato aggiornato il servizio?
Non vedo commit su github.

Questo il payload:
```
{
    "body": {
        "anacForm": {
            "appalto": {
		"idAppalto": null,
                "codiceAppalto": "G00001",
                "codiceFiscaleSA": "06188330150",
                "denominazioneSA": "Maggioli S.p.A."
            },
            "aggiudicazioni": [
                {
                    "lotIdentifier": "LOT-0001",
                    "oggettoPrincipaleContratto": {
                        "codice": "F",
                        "idTipologica": "oggettoPrincipaleContratto"
                    },
                    "cup": "C99H19000370003",
                    "aggiudicatario": {
                        "codiceFiscale": "03481380263",
                        "denominazione": "TEST SPA",
                        "importo": 1000
                    }
                }
            ]
        }
    }
}
```

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 24/11/2023.
