### ISSUE TITLE
Scheda P1_16 - Utilizzo DMN 

### ISSUE THREAD

**Issue by davideorsi-bit** [anticorruzione/npa#521]
Buongiorno,
stiamo tentando di validare il JSON relativo alla scheda P1_16 costruito seguendo il modello dati modello-dati-schede-P1.16.yaml 
con il DMN P1_16.dmn in tale dmn è indicata la regola seguente : 
  appalto.datiBaseProcedura.tipoProcedura.codice = "neg-wo-call" 

Nel Json della scheda P1_16 che stiamo costruendo per invocare l'API "creaAppalto" questa attributo non è presente.

Rileggendo anche l'ISSUE 288 leggo nella vostra risposta che:
 "L'oggetto datiBaseProcedura di appalto è un dato in comune con il TED: nei sottosoglia è contenuto nell’anacForm, mentre nei soprasoglia, come nel caso della scheda P1_16, è un dato presente nell’eForm".

Essendo nel modello dati della scheda P1_16 l'attributo "eform" definito come: 
  "EformTypestringEform codificato Base64 nel formato XML definito da TED"

E' corretto affermare che, di fatto le regole di questo DMN non sono applicabili al modello dati di NPA Appalto?
Per validare il json della scheda P1_16 dovrei in qualche modo recuperare  l'attributo appalto.datiBaseProcedura.tipoProcedura.codice 
 dall'XML inserito nell'attributo  "eform"  e trasformarlo in  formato JSON ?
Grazie

**Comment by mpizziconi** [comment]
In linea generale, in caso di schede che includono eForms le regole DMN possono essere riferite a valori inclusi nella eForm (se ANAC ha definito scenari più restrittivi) In questo caso l'engine estrae i campi direttamente dalla eform rappresentata in xml.
La issue viene mantenuta aperta e assegnata al gruppo dati per la verifica della corretta implementazione della regola citata nello specifico caso
