### ISSUE TITLE
lotto.lotIdentifier - corrispondenza con BT-137

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#522]
chiediamo conferma che è richiesto di inserire in lotIdentifier il valore presente in BT-137.
il valore è generato automaticamente dal ted a valle della generazione del documento EFORM (si tratta di un campo tecnico progressivo [LOT-001; LOT-002; LOT-003; ecc]).

invece, BT-22 è il campo contenente l'identificativo interno del lotto ed è un campo editato dall'utente nella compilazione dell'eform
<img width="621" alt="MicrosoftTeams-image (68)" src="https://github.com/anticorruzione/npa/assets/142924847/2582ae2b-c87a-4768-a7ff-de39fbe22570">

**Comment by mpizziconi** [comment]
chiusa perché tratta lo stesso argomento della https://github.com/anticorruzione/npa/issues/309
