### ISSUE TITLE
P6.1 - Eform assente - corrispondenza lotIdentifier con BT-137 TED 

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#523]
salve, 
mi si chiede per la scheda P6.1 di popolare il campo anacform.lotto.lotIdentifier con il valore corrispondente al campo BT-137 del TED.
se confermato, vorremmo capire come prendere il dato visto che la scheda P6.1 non prevede l'eform.

<img width="631" alt="image" src="https://github.com/anticorruzione/npa/assets/142924847/ba68423a-b118-48d1-a2eb-610110d2bf35">

<img width="596" alt="MicrosoftTeams-image (70)" src="https://github.com/anticorruzione/npa/assets/142924847/0894b52d-1186-45dd-a055-c7c7f954e729">

**Comment by mpizziconi** [comment]
Il campo lotIdentifier costituisce il collegamento tra identificativo del lotto interno alla SA e CIG.
Per le schede sprovviste di eForm il campo può assumere un valore di tipo stringa non vincolato a nessuna grammatica.
L'unico requisito richiesto in questo caso è che il valore sia univo nell'ambito della scheda di indizione
