### ISSUE TITLE
Scheda procedure AQ/convenzione Soprasoglia - Obbligatorietà eform

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#525]
Salve,
 
Scheda P6_2 - Scheda relativa alle adesioni AQ/convenzione con successivo confronto competitivo (ordinario/speciale).
**non prevede eform.**

Qual è la scheda relativa alle procedure AQ/convenzione Soprasoglia per cui è obbligatorio l'eform?

**Comment by anac-uscp** [comment]
Esistono diverse eForm che prevedono il campo BT-765 'Framework Agreement' per indicare che si usa la tecnica dell'AQ (vedi ad es. le schede P1.16, P1.17)
