### ISSUE TITLE
Scheda NAG - Appalti soprasoglia

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#526]
Buonasera,
con riferimento alla issue https://github.com/anticorruzione/npa/issues/436, che cosa si applica  in caso di non aggiudicazione di appalti soprasoglia?

Grazie

**Comment by anac-uscp** [comment]
Per appalti soprasoglia il TED ha previsto l'invio di una scheda di aggiudicazione con la valorizzazione dei campi BT-142 ' Winner Chosen' e BT-144 'Not Awarded Reason'
