### ISSUE TITLE
Scheda AD2_26 E AD2_25 - Discriminante per invio

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#527]
Salve,

**TIPOLOGICA**: AF/OR/SS/R*

- Scheda AD2_25 - Scheda di affidamento diretto (EU), valida per i sottoglia > 5K, senza invio al TED. Affidamento diretto sopra la soglia minima e sotto la soglia comunitaria, generale. Articolo 50 comma 1 lettere c) d) e)  decreto legislativo 36/2023. Articolo 50 comma 9 decreto legislativo 36/2023.

- Scheda AD2_26 - Scheda di affidamento diretto (EU), valida per i sottoglia > 5K, senza invio al TED. Affidamento diretto sopra la soglia minima e sotto la soglia comunitaria, settoriale. Articolo 50 comma 9 decreto legislativo 36/2023.

Qual è la discriminante per l'invio delle schede, avendo la stessa tipologica?

**Comment by anac-uscp** [comment]
La discriminante è la direttiva europea: DIR 24 (settori ordinari) per la AD25; DIR 25 (settori speciali) per la AD26;
