### ISSUE TITLE
Servizio Modifica Appalto

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#529]
Buongiorno @mpizziconi,
sulla base della issue **https://github.com/anticorruzione/npa/issues/503**, possiamo confermare che per le procedure con pubblicazione TED il "**modifica appalto**" può essere invocato fino al momento che precede l'invocazione del "**pubblica avviso**"?

Una volta pubblicato il bando, le modifiche potranno essere apportate solo tramite il **rettifica avviso**

Inoltre la risposta fornita parla di **pubblica avviso**, pertanto per le gare dove non è prevista l'invocazione del **pubblica avviso** fino a quanto può essere utilizzato il servizio "**modifica appalto**"

Grazie

**Comment by mpizziconi** [comment]
modifica-appalto può essere invocata fino alla chiamata a conferma-appalto, dopo di che i dati non sono più modificabili e devono essere pubblicati così come inviati.
Dopo l'operazione pubblica-avviso (che nell'unico caso delle schede di indizione è richiesta alla piattaforma, altrimenti viene invocata automaticamente al termine della conferma), se la pubblicazione è prevista sul ted, allora può essere invocata l'operazione di modifica-avviso fino alla schedulazione per la pubblicazione da parte del ted (stato verificabile da esito-operazione). Successivamente alla schedulazione l'unica operazione possibile è la rettifica-avviso perché l'avviso originale viene comunque pubblicato.
Nel contesto di sola pubblicazione nazionale l'operazione modifica-avviso non è consentita perché la schedulazione è contestuale all'operazione pubblica-avviso. Resta disponibile la rettifica

la issue https://github.com/anticorruzione/npa/issues/503 viene aggiornata perché interpretabile non correttamente
