### ISSUE TITLE
Test eService ANAC per la PCP - Invio credenziali

### ISSUE THREAD

**Issue by Angelo030897** [anticorruzione/npa#530]
Per la costruzione del JWS serve valorizzare il campo regCodiceComponente - codice che avrebbe dovuto essere assegnato e comunicato da ANAC con l’esito positivo della richiesta di certificazione - ma non risulta al momento alcun id della componente nel messaggio ricevuto da ANAC stesso.
Cortesemente, sarebbe possibile ricevere il codice da far inserire per i test?

**Comment by mpizziconi** [comment]
è necessario conoscere la denominazione del titolare

**Comment by miandiorio** [comment]
La denominazione del Titolare è "Regione Puglia - Sezione Raccordo al Sistema Regionale - A691E81"

**Comment by miandiorio** [comment]
Se può essere utile: la pratica è la 2023-0013895

**Comment by mpizziconi** [comment]
l'invio è stato effettuato verso il gestore della piattaforma. 
Per celerità si procede all'inoltro al titolare
