### ISSUE TITLE
Servizio crea-appalto - ERR69

### ISSUE THREAD

**Issue by cbaldo** [anticorruzione/npa#531]
Riceviamo l'errore ERR69 chiamando il servizio crea-appalto (scheda P1_16)
Tale errore però non è censito tra quelli presenti in errori.json

cercando di recuperare informazioni relative all'errore riceviamo quanto segue:
{
    "tipologica": {
        "codice": null,
        "descrizione": null,
        "dataInizio": null,
        "dataFine": null
    },
    "instance": null,
    "status": 200,
    "title": "OK",
    "detail": "Operazione effettuata con successo",
    "type": "about:blank"
}
mentre per altri codici di errori riceviamo correttamente le informazioni. Ad esempio per l'ERR66

{
    "tipologica": {
        "codice": "ERR66",
        "descrizione": {
            "it": "mancata coerenza tra idAppalto e cig",
            "en": "mancata coerenza tra idAppalto e cig"
        },
        "dataInizio": null,
        "dataFine": null
    },
    "instance": null,
    "status": 200,
    "title": "OK",
    "detail": "Operazione effettuata con successo",
    "type": "about:blank"
}

Potete aiutarci a capire la causa dell'errore? Grazie

**Comment by mpizziconi** [comment]
per seguire la transazione è necessario il govway_id restituito da PCP
