### ISSUE TITLE
Flussi Affidamenti diretti

### ISSUE THREAD

**Issue by gcardarelli84** [anticorruzione/npa#533]
In riferimento alla cronologia schede dell'Orchestratore, in particolare agli Affidamenti diretti, si richiede conferma del fatto che il flusso di questi ultimi sia monofase e monoscheda.
Nello specifico, analizzando il file Excel abbiamo interpretato che il flusso di una procedura sia determinabile basandosi sul codice presente nella colonna R "flussoAppartenenza", pertanto le schede con il medesimo valore su questa Colonna faranno parte dello stesso flusso. 
E’ corretto?
Prendendo a titolo di esempio la scheda “AD3 - Affidamento diretto >= 5k € e entro i valori ammessi” il flusso di appartenenza risulta essere il numero 30. Tale valore però è presente solo ed esclusivamente su tale riga, pertanto, si deduce che per la trasmissione ad ANAC di questo tipo di procedura sia sufficiente inviare una scheda AD3 e che quindi l’Elenco delle schede successive ammesse (o non ammesse) riportato nella colonna “Q” dell’Orchestratore sia una previsione, e non un obbligo, che deve essere sempre raccordato con il flusso di appartenenza. In questo contesto e in relazione all’obbligo che incombe sull’Anac che deve assicurare la tempestiva pubblicazione dei dati ricevuti, con quale servizio è possibile trasmettere i dati sulle somme liquidate?

**Comment by mpizziconi** [comment]
Non esattamente: è corretta l'interpretazione della R: ogni scheda di indizione inizializza un flusso; le schede successive devono appartenere al flusso inizializzato dalla scheda di indizione
Tuttavia non è stato compreso che le schede che non prevedono una successiva trasmissione sono contrassegnate dal valore STATO FINALE nella colonna Q; se invece nella colonna Q sono riportate una o più schede allora lo stato attuale non è finale e il sistema attende la trasmissione di una di tali schede per la transizione allo stato successivo. 
Nel caso della scheda AD3 sono indicate alcune schede successive e queste ultime nella rispettiva riga della colonna R sono valorizzate con "*" che, come riportato in descrizione (riga 2), significa che la scheda è prevista per qualunque flusso. 
La colonna R è necessaria a disambiguare la successione di schede nel caso in cui nel flusso sia stata inviata una scheda contrassegnata da "*". 
Ad esempio le schede di indizione P1_x inizializzano flussi differenti e sono tutte seguite dalle schede S1 o S2 comuni a qualunque flusso. La scheda di aggiudicazione successiva alla S2 che deve essere inviata è quella che appartiene al flusso dell'appalto ovvero quella contrassegnata nella colonna R dallo stesso valore della scheda di indizione che ha inizializzato il processo.

Chiudo la issue, se qualcosa rimane non chiaro richiedo di aprire una nuova issue citando la presente.
