### ISSUE TITLE
Processo pubblicazione AD

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#534]
Buongiorno, 
con riferimento alla issue https://github.com/anticorruzione/npa/issues/440 non è chiaro quale sia il processo di pubblicazione ed invio dei dati.
La PCP quando si attende la comunicazione dei dati relativi ad un affidamento diretto?
L'analisi di alcune schede pone il dubbio che l'AD vada pubblicato senza CIG e che il CIG venga assegnato dalla PCP solo al momento della aggiudicazione, perchè solo in quel momento sono disponibili alcune info proprie solo della aggiudicazione (vedi ad esempio importo di aggiudicazione e data di aggiudicazione

**Comment by federicodemarco** [comment]
si chiede riscontro urgente. Grazie

**Comment by anac-uscp** [comment]
Le schede Ad sono relative all'affidamento diretto per cui l'attribuzione del CIG e l'affidamento del contratto sono contestuali.
