### ISSUE TITLE
CIG derivato con scheda di indizione AD4

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#537]
Buongiorno,
al 01/01/24 sarà necessario staccare dei CIG che prevedono l'invio della schda AD4.
L'esempio che porto è un ordine da convenzione, la cui gara istitutrice è stata pubblicata ed aggiudicata prima del 01/01/24
Mi aspetto che dal primo di gennaio qualunque ordine di questa convenzione debba essere pubblicato con un CIG prelevato mediante l'interoperabilità con la PCP.
Potete confermare?

**Comment by federicodemarco** [comment]
si sollecita riscontro grazie

**Comment by r-dm123** [comment]
Attenersi a provvedimento ANAC MIT in corso di emissione
