### ISSUE TITLE
Dettaglio Flusso

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#538]
Salve, 
in merito alla issue  #536 , provo a spiegarmi meglio:
oggi nell'incontro è stato detto che il flusso 40 presente nella colonna R (refuso mio) non prevede l'invio delle schede M1 E M1_40.

Da dove si deduce questo? 
Basta vedere quindi la colonna relativa alla "scheda successiva" e così via?
Grazie

**Comment by mpizziconi** [comment]
Nella colonna R, in corrispondenza della riga della scheda M1 sono riportati i valori 110,112, 113,116,120,111,117,121.
 
L'engine di orchestrazione ammette una scheda solo se il processo si trova in uno dei flussi indicati per quella scheda, dato che la scheda AD_4 dà origine al flusso 40 lo scenario non prevede l'invio di una M1 e, se inviata, allo stato attuale, l'orchestratore la rifiuterebbe.
