### ISSUE TITLE
Scheda per IDM Sotto soglia

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#539]
salve,
qual è la scheda relativa all'avvio dell'indagine di mercato per procedura negoziata senza bando sottosoglia ai sensi dell’art 76?

**Comment by UserM21** [comment]
@supportoAnac si richiede un riscontro

**Comment by anac-uscp** [comment]
Nelle procedure negoziate senza bando sottosoglia i soggetti da invitare alla procedura possono essere scelti tramite: 
•	a) indagine di mercato. In questo caso si invia a BDNCP un avviso relativo all’avvio dell’indagine di mercato trasmettendo la scheda P7_1_3; 
•	b) elenchi di operatori economici. In questo caso, una volta individuati gli operatori da invitare tra gli iscritti all’elenco, si invia a BDNCP la richiesta di invito trasmettendo la scheda P7_2
•	la P7_3 vale per tutti i regimi, quindi sia per il regime ordinario sia per il regime alleggerito
