### ISSUE TITLE
Procedura Negoziata senza bando sotto soglia  ai sensi art 76

### ISSUE THREAD

**Issue by MarcoGiovannetti** [anticorruzione/npa#540]
Per aprire una procedura negoziata senza previa pubblicazione di un bando di gara ai sensi dell’art 76 quale scheda deve essere utilizzata ?
Nel configuratore  le schede P7_1_1 e P7_1_2 per le quali nella colonna “Riferimento normativo” si trova il rimando all’art 76 devono essere usate per “Procedura negoziata senza bando pari o sopra soglia” mentre  la scheda P7_1_3 che deve essere usata per “Procedura negoziata senza bando sottosoglia” nella colonna “Riferimento normativo” NON riporta il riferimento all’art 76.
Si tratta di un refuso oppure deve essere utilizzata una scheda diversa ?

**Comment by anac-uscp** [comment]
Negli affidamenti di importo pari o sopra la soglia comunitaria è d’obbligo usare le procedure aperte, ristrette ecc. L’articolo 76 identifica i casi eccezionali in cui si può usare una procedura negoziata senza bando al posto delle predette procedure. Per avviare una negoziata senza bando di importo pari o superiore alla soglia comunitaria bisogna usare le schede P 7_1_1 o P 7_1_2.
Negli affidamenti sottosoglia la procedura negoziata senza bando è la procedura ordinaria da usare ai sensi dell’art. 50 comma 1 lett. c), d) e). Pertanto, nel sottosoglia,  la procedura negoziata non si deve usare solo nei casi dell’art. 76 ma si usa sempre, per questo motivo non è riportato il riferimento dell’art. 76 in questa scheda. Per avviare una negoziata senza bando di importo sottosoglia comunitaria bisogna usare la scheda P7_3.
