### ISSUE TITLE
Procedura Negoziata senza previa pubblicazione del bando (art 76) NON discendente da IDM

### ISSUE THREAD

**Issue by MarcoGiovannetti** [anticorruzione/npa#541]
Quale schede dobbiamo utilizzare per la gestione di una Procedura Negoziata senza previa pubblicazione del bando (art 76) NON discendente da IDM come nel caso di procedura ai sensi del comma 2 lettera b)

**Comment by anac-uscp** [comment]
Il tipo di procedura ' Procedura Negoziata senza previa pubblicazione del bando' è tra le voci della tipologica del campo Procedure Type BT-105. La scheda da utilizzare dipende dal tipo di settore (ordinario o speciale), tipo di contratto (es. concessione) o regime.

**Comment by anac-uscp** [comment]
Ad integrazione di quanto sopra, nelle procedure negoziate senza bando sottosoglia i soggetti da invitare alla procedura possono essere scelti tramite: 
•	a) indagine di mercato. In questo caso si invia a BDNCP un avviso relativo all’avvio dell’indagine di mercato trasmettendo la scheda P7_1_3; 
•	b) elenchi di operatori economici. In questo caso, una volta individuati gli operatori da invitare tra gli iscritti all’elenco, si invia a BDNCP la richiesta di invito trasmettendo la scheda P7_2
•	la P7_3 vale per tutti i regimi, quindi sia per il regime ordinario sia per il regime alleggerito
