### ISSUE TITLE
Scheda S2 "Elenco offerte ricevute/OE invitati" - corretto ordine operazioni in gara

### ISSUE THREAD

**Issue by GiovanniSom** [anticorruzione/npa#542]
Buongiorno,
si conferma che la scheda in oggetto deve essere trasmessa al termine della scadenza della presentazione delle offerte, indicando tutti i partecipanti (ed eventuali invitati) prima dell'avvio della fase di verifica e dell'apertura delle buste virtuali di offerta? esaminando la documentazione e la struttura della scheda in oggetto non risulta una indicazione in tal senso.
E' corretto presupporre che la data minima di apertura delle buste dovrà essere successiva alla data di conferma di questa scheda?
grazie e buon lavoro

**Comment by anac-uscp** [comment]
ovviamente si conferma che la scheda S2 deve essere trasmessa al termine della scadenza della presentazione delle offerte quindi l'apertura delle buste deve essere successiva al termine della scadenza della presentazione delle offerte.
