### ISSUE TITLE
Schede AD senza SC1 - come recuperare l'idContratto

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#543]
1. La scheda AD5, da orchestratore, prevede l'invio come scheda successiva della CO2. Quest'ultima però richiede l'idContratto obbligatoriamente, dato che si ottiene con l'invio della scheda SC1, non prevista in questo caso. Come dobbiamo comportarci?
2. Le schede di tipo AD (ad esclusione della AD5 su menzionata), da orchestratore, prevedono la possibilità di inviare, come scheda successiva, la scheda CO1, anche senza l'invio della scheda SC1. Anche in questo caso, però, è previsto l'idContratto obbligatorio. C'è un errore nell'orchestratore o ci sta sfuggendo qualcosa?

**Comment by ffinpaa** [comment]
PER LA SECONDA DOMANDA è STATA FORNITA RISPOSTA? ALLE SCHEDE AD SEGUE LA SC1 E NON DIRETTAMENTE LA C01? GRAZIE
