### ISSUE TITLE
Abilitazione aggregati SPID

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#544]
Siamo soggetti (privati) aggregatori di servizi pubblici. Inviamo regolarmente metadata via email ad agid per aggiungere tutti i nostri aggregati.
Ma è possibile che metadata inviati 20 e 25 ottobre ad oggi non sono stati ancora attivati? Dobbiamo avere le piattaforme certificate al 31/12 e questi sono i tempi di risposta?
Ma è possibile che su eIDAS i ticket aperti il 13/10 ad oggi non vengono ancora presi in carico?
Cioè mi chiedo, sono tempistiche accettabili viste le scadenze che abbiamo? 
Nessuna risposta a email, PEC e telefonate. Centralino Agid staccato da due mesi.
Avanti così...

**Comment by mfortini** [comment]
Related #488

**Comment by fvabra89** [comment]
Sono stati aperti altri ticket su eIDAS oltre quello fornito nel precedente thread?

**Comment by pakozack** [comment]
SI, abbiamo richiesto la chiusura anche degli altri (6P3-1V9-XW7J). Inoltre abbiamo richiesto un contatto con qualcuno per discutere di alcune cose. Abbiamo inviato email ed aperto il ticket . Nessuna risposta
Anche su 55P-83S-JY7E, nessuna risposta... ma fortunatamente dopo 2 mesi abbiamo risolto da soli. Si puo chiudere anche questo. 
Sarebbe gradito un confronto per trovare una modalità piu rapida per richiedere le federazioni degli enti direttamente in ambiente di produzione, visto che il client utilizzato è per noi sempre lo stesso.

**Comment by pakozack** [comment]
Attendiamo...

**Comment by pakozack** [comment]
Si puo chiudere
