### ISSUE TITLE
A1_29 in errore - "La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata"

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#545]
abbiamo mandato in ordine P1.16 - S1 - S2 (quest'ultima è in stato CONFERMATO).
dopodichè abbiamo provato a mandare la A1.29 ma otteniamo l'errore : ERR2 "La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata".

`ID APPALTO = 1395ac73-e51d-4608-8e7d-a058febe8b2f`

alleghiamo JSON 
[A1_29 .json](https://github.com/anticorruzione/npa/files/13270418/A1_29.json)

**Comment by supportoAnac** [comment]
Anomalia superata da rilasci successivi.
