### ISSUE TITLE
Censimento RUP in PCP

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#546]
Buongiorno,

per il censimento dei RUP delle Stazioni Appaltanti sulla PCP verrà inizialmente recuperata l'anagrafica del SIMOG?

Grazie

**Comment by federicodemarco** [comment]
ciao, se ti può essere utile ho ricevuto questo riscontro https://github.com/anticorruzione/npa/issues/270

**Comment by LucaMaggioni1** [comment]
chiusa dato che risolta per altri canali
