### ISSUE TITLE
Servizi PCP - Servizi generici

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#547]
Buongiorno,

è corretto che i RUP e delegati sono gli unici a poter richiamare i servizi della PCP? 

Per i servizi generici tipo la ricerca di un appalto è sufficiente identificare la Stazione Appaltante che richiama il servizio? Questo agevolerebbe le attività delle strutture di supporto al RUP.

Grazie

**Comment by mpizziconi** [comment]
Non è previsto l'accesso per utente anonimo o privo di ruolo RP o DRP
