### ISSUE TITLE
A1_29 - schede successive flusso orchestratore

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#548]
in base al flusso definito dall'orchestratore dopo la A1.29 è possibile mandare le seguenti schede:
- SC1
- CO1
- S3
- S4

non è chiaro come si possa passare dall'aggiudicazione (A1.29) alla conclusione (CO1) senza aver prima mandato la SC1, dal momento che la CO1 richiede in input l'idContratto (dato che si può ottenere solo con la sottoscrizione contratto). 

lo stesso problema si pone per la scheda di indizione AD5 che prevede come scheda successiva la CO2.

<img width="726" alt="image" src="https://github.com/anticorruzione/npa/assets/142924847/af73b9de-e265-42cf-a849-667ff1f2325d">

**Comment by anac-uscp** [comment]
La CO2 è sospesa fino a modifica del modello dati e la CO1 non può essere usata per la mancata sottoscrizione del contratto dopo l'aggiudicazione.
