### ISSUE TITLE
Errore 400 in chiamata servizio  status

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#549]
Buongiorno abbiamo un errore generico nella chiamata al servizio
https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/status

Response: {"type":"[https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received](https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html%22,%22title%22:%22InteroperabilityInvalidRequest%22,%22status%22:400,%22detail%22:%22Received) request is not conform to the required interoperability profile","govway_id":"5a9c1bdc-7d5b-11ee-b4a0-0050568e08b3"}

è possibile attivare la trace per verificare il motivo dell'errore?

**Comment by mpizziconi** [comment]
Verifica ModI della richiesta fallita: [GOVWAY-814] [Header 'Agid-JWT-TrackingEvidence'] Token contenente un claim 'aud' non valido

**Comment by fpaparoni** [comment]
salve, abbiamo effettuato la chiamata passando il claim aud come singola stringa, anche se la libreria che stiamo utilizzando per default utilizza la collection di stringhe previste dallo standard. Ripetendo la chiamata ora riceviamo sempre un errore che allego

Response: {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"9e9a5262-7edd-11ee-a061-0050568e9679"}

**Comment by mpizziconi** [comment]
in questo caso l'errore deriva dal fatto che il token è scaduto
Verifica ModI della richiesta fallita: [GOVWAY-661] [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2023-11-09_11:18:31.000')

**Comment by fpaparoni** [comment]
Grazie ho verificato e il problema era esattamente quello, proseguo sull'altra issue aperta perchè comunque la chiamata al servizio issue continua a non funzionare
