### ISSUE TITLE
Scheda AD3 - Prelievo CIG

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#550]
Buongiorno, 
sulla base dell'orchestratore la scheda AD3 è una scheda di indizione pertanto ha come obiettivo quello di prelevare il CIG.
Se confermate tale assunto, potete confermarmi che  la scheda AD3 nel suo flusso non è preceduta da un'altra scheda?

In caso non avessi compreso correttamente il flusso, chiedo gentilmente di indicarmi come procedere sul file dell'orchestratore.

vedi anche issue https://github.com/anticorruzione/npa/issues/533 e https://github.com/anticorruzione/npa/issues/536 e https://github.com/anticorruzione/npa/issues/440

**Comment by anac-uscp** [comment]
Si conferma che la scheda AD3 'Affidamento diretto >= 5k € e entro i valori ammessi' non è preceduta da un'altra scheda.
