### ISSUE TITLE
Rendicontazione su BDNCP gare antecedenti Gennaio 2024

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#551]
Ad opera del nuovo codice dei contratti pubblici, dal 1° luglio 2023 l’art. 1, comma 32 della L. 190 è stato abrogato. ANAC, nell'incontro del 31/01/2023 ha comunicato:

_"tutti gli obblighi di trasparenza sono gestiti tramite PDNCP e sta valutando la pubblicazione futura degli XML.  Fino al 31/12/23, i file XML saranno pubblicati ma senza link per la verifica, a causa dell'abrogazione dell'articolo 1 comma 32 dal 01/07."_

E' corretto supporre che i dati di esecuzione delle procedure aggiudicate o in esecuzione prima del 01/01/2024 verranno trasmessi a BDNCP attraverso le schede dell'area funzionale A5 di esecuzione.

**Comment by r-dm123** [comment]
Attenersi a provvedimento ANAC MIT in corso di emissione
