### ISSUE TITLE
Scadenza termine rendicontazione CIG su BDNCP

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#552]
Ad opera del nuovo codice dei contratti pubblici, dal 1° luglio 2023 l’art. 1, comma 32 della L. 190 è stato abrogato.

Sono stati definiti nuovi termini di scadenza per l'invio delle informazioni di rendicontazione relative all'anno precedente o rimane l'attuale termine del 31/01?

**Comment by r-dm123** [comment]
Attenersi a provvedimento ANAC MIT in corso di emissione
