### ISSUE TITLE
Servizio pubblica-avviso - ERR47 avviso non pubblicato

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#554]
abbiamo provato a pubblicare diversi appalti ma tutti hanno prodotto il seguente esito:
ERR47 - errore generico durante la pubblicazione dell'avviso.
si tratta di un'anomalia che verrà risolta con il prossimo rilascio?

**Comment by supportoAnac** [comment]
Anomalia superata da rilasci successivi.
