### ISSUE TITLE
Servizi e ruoli - Contesto Servizi Comuni Tipologiche (ad es. recupera-elenco-tipologiche)

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#556]
Buonasera,
faccio riferimento alla tabella disponibile al paragrafo [4.5 Servizi e ruoli](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md#45servizi-e-ruoli).
Per tutti i servizi vengono indicati i ruoli che possono invocarli.
Fanno eccezzione i seguenti: 

- recupera-elenco-tipologiche
- recupera-tipologica
- recupera-valore-tipologica

Per questi la colonna ruolo è popolata con il valore " * ". Cosa significa?

**Comment by supportoAnac** [comment]
L’***** sta ad indicare che i servizi possono essere invocati da tutti i ruoli.
