### ISSUE TITLE
Base Dati - Numero pubblicazione Nazionale ed Europeo

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#559]
Intercent-ER
Non ho trovato nel modello dati le informazioni relative al al numero di pubblicazione sia nazionale sia europeo. Di seguito le informazioni:

1. Numero pubblicazione sul TED (nella forma XXXXXX-YYYY)
2. Numero della richiesta di pubblicazione al TED (forse è il notice-id ma non so se è quello attribuito per la PCP oppure quello attribuito alla richiesta dal TED.
3. Numero pubblicazione sulla PPL/ANAC (se esiste)

La necessità di averli, oltre a motivazioni informative, risiede nella necessità di poter effettuare attività di rettifica.

**Comment by supportoAnac** [comment]
Le informazioni sono restituite dal servizio consulta-avviso; il payload della response include i campi datiPubblicazioneEU e datiPubblicazioneIT. 
Il servizio consulta-avviso è asincrono e si appoggia a servizi esterni del TED e di ANAC, quindi un task schedulato ogni giorno verifica lo stato dell'avviso attualmente pubblicato, anche se è in coda una modifica o una rettifica più recente.

**Comment by lauralu1993** [comment]
@labruno
