### ISSUE TITLE
Conferma Appalto - Pubblicazione Avviso

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#560]
Buongiorno,

una volta confermato l'appalto, le Stazioni appaltanti avranno 90 giorni per procedere con la pubblicazione dell'avviso, è corretto?
Trascorso questo periodo l'appalto verrà automaticamente cancellato?

Grazie

**Comment by mpizziconi** [comment]
Il termine di 90 giorni è quello stabilito ora ed è stato determinato in base alle attività utente e funzionalità di Simog.
A regime per la PCP questo termine potrà essere molto più ridotto.
(la differenza tra Simog e PCP è nelle attività di pubblicazione/indizione della procedura che per Simog sono esterne mentre la PCP ne diventa lo strumento)
