### ISSUE TITLE
Impatti 36/2023 rispetto a pubblicazione dei dati ai sensi della L190/2012 art.1 comma 32 ed.2023

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#562]
Come disposto dall’articolo n.226 (Abrogazioni e disposizioni finali) comma 1 del d.lsg 36/2023, dal 1* luglio 2023 è stato abrogato l’articolo 1 comma 32 della legge n.190 del 6 novembre 2012, che disponeva l’obbligo di pubblicazione conforme alle disposizioni previste dalla deliberazione ANAC n.39 del 2 gennaio 2016, si chiede quindi conferma che per le procedure di affidamento avviate nel corso del 2023 e per le procedure i cui contratti di affidamento sono in corso di esecuzione o i cui dati hanno subito modifiche e/o aggiornamenti nel periodo indicato (delibera ANAC 39/2016 art.3 comma 2), non si debba procedere alla pubblicazione dei dati in formato xml sul sito istituzionale della SA e alla conseguente comunicazione dell’avvenuta pubblicazione dei dati all’Autorità per le finalità di vigilanza. La presente richiesta si intende con carattere di urgenza per via dell’avvio delle attività propedeutiche alla produzione del file che di consueto vengono avviate ad inizio novembre.

**Comment by anac-uscp** [comment]
No, non si deve più procedere alla pubblicazione dei dati in formato xml sul sito istituzionale della SA e alla conseguente comunicazione dell’avvenuta pubblicazione dei dati all’Autorità per le finalità di vigilanza per le procedure di affidamento avviate nel corso del 2023 e per le procedure i cui contratti di affidamento sono in corso di esecuzione.
