### ISSUE TITLE
Funzioni Ricerca-Piano, Ricerca-Appalto, Ricerca-Avviso e Ricerca-Scheda

### ISSUE THREAD

**Issue by GiovanniSom** [anticorruzione/npa#563]
Buongiorno,
in riferimento alle operazioni sopra definite ed alla logica dei permessi previsti sulle diverse operazioni che associa tutti i casi sopra descritti agli utenti RP e DRP, ed in considerazione della pubblicità delle informazioni previste per i diversi elementi, si chiede conferma del fatto che le operazioni sopra citate NON possano essere eseguite da utenti esterni per effettuare le ricerche e che tali ricerche e relativi dettagli non siano ad esempio da mettere a disposizione degli OO.EE. nelle piattaforme per consentire un accesso diretto alle informazioni pubblicate dalle SA e che pertanto gli OO.EE. possano vedere solo le informazioni messe a disposizione dalle diverse piattaforme. 
grazie della risposta e buon lavoro

**Comment by supportoAnac** [comment]
Si conferma che le operazioni citato possono essere eseguite solo da utenti aventi i profili indicati nella documentazione.
