### ISSUE TITLE
Utilizzo parallelo delle utenze RP

### ISSUE THREAD

**Issue by user6330** [anticorruzione/npa#564]
Salve,

come gestore di piattaforme, ci sono state condivise solo 1 o 2 utenze RP. 
Sarà possibile utilizzare le credenziali condivise per più chiamate paralle in ambiente di collaudo?

**Comment by mpizziconi** [comment]
le utenze sono 2, non ci sono problemi nell'uso contemporaneo della stessa utenza per più procedure
