### ISSUE TITLE
Modello dati - Tipologiche - CPV: JSON duplicato

### ISSUE THREAD

**Issue by cbaldo** [anticorruzione/npa#566]
Solo per avvisare che il contenuto del json è duplicato

**Comment by supportoAnac** [comment]
Risolto con versione del 24/11/2023.

**Comment by GiovanniSom** [comment]
si riscontra il problema di dati duplicati anche per la risposta del servizio recupera-tipologica per la tipologica avente id_tipologica = "CPV". i valori previsti per la tipologica vengono duplicati
