### ISSUE TITLE
[CONSIP]La Scheda AD5 affidamento diretto <5k  va chiusa con  CO2 conclusione affidamento <5k ma richiede idContratto 

### ISSUE THREAD

**Issue by labruno** [anticorruzione/npa#567]
Un "affidamento diretto <5k"  (scheda **AD5** ) va in  "conclusione affidamento <5k" ( scheda CO2 ) chiedendo  idContratto che però dovrebbe essere generato da una scheda di sottoscrizione contratto ( scheda SC1 ).  Dall'orchestratore/schema-cronologia-scheda la scheda successiva prevista è solo la CO2.
Quale valore va quindi inserito in CO2 nel campo idContratto?

<img width="412" alt="image" src="https://github.com/anticorruzione/npa/assets/48831012/848feae7-7532-484a-993f-0f1b19b2d2a9">

@lauralu1993

**Comment by supportoAnac** [comment]
La CO2 è sospesa fino a modifica del modello dati
