### ISSUE TITLE
Verifica Esito Operazione per Schede post pubblicazione.

### ISSUE THREAD

**Issue by labruno** [anticorruzione/npa#568]
Come è possibile verificare l'esito operazione riguardante la crea / conferma  scheda post pubblicazione attraverso il solo uso dell'idAppalto ? Nelle fasi successive alla pubblicazione più soggetti potrebbero aprire parallelamente più schede. In questo scenario sarebbe utile poter far leva anche sull'idScheda e non solo sull'idAppalto.

<img width="423" alt="image" src="https://github.com/anticorruzione/npa/assets/48831012/74d34d77-e2b0-4902-ac53-f34168b552fd">

**Comment by mpizziconi** [comment]
Prendiamo in considerazione la richiesta.
Al momento è possibile ottenere le informazioni richieste filtrando la listaEsiti ottenuta in risposta.

NB
Si condivide lo scenario in cui in uno stato dell'appalto, successivo alla pubblicazione, possano essere trasmesse più schede contemporaneamente, ma in nessuno stato si verifica la molteplicità di soggetti responsabili che possono effettuare trasmissioni.

**Comment by labruno** [comment]
@mpizziconi  è equivalente l'utilizzo di "consulta-scheda" alla verifica esito ultima operazione per quella scheda ?
Grazie.
