### ISSUE TITLE
Scheda AD3 - Soglia importo

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#569]
Buonasera,
la scheda AD3 è per **Affidamento diretto >= 5k € e entro i valori ammessi. Articolo 50 comma 9 decreto legislativo 36/2023.**
Dato che la scheda prevede anche i dati di aggiudicazione, il controllo sull'importo per distinguerla ad sempio dalla AD5 va fatto sulla base d'asta o sull'importo di aggiudicazione. Il 5k si riferiscono alla base d'asta o all'importo di aggiudicazione.

Pongo questo quesito in quanto la scheda AD3, richiede l'invio dei dati di aggiudicazione, pertanto al momento del conferma appalto (aggiudicazione definitiva o pubblicazione esito) le piattaforme dispongono di entrambe le info:

1) Importo a base d'asta
2) Importo di aggiudicazione

Grazie

**Comment by anac-uscp** [comment]
L'importo è unico ed è quello dell'affidamento, non esiste un importo a base d'asta.
