### ISSUE TITLE
Variazione aggiudicatari

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#572]
Buongiorno,
in caso di variazione di un aggiudicatario (scheda A già inviata) attraverso quale scheda va trasmessa l'informazione?

Grazie,

**Comment by anac-uscp** [comment]
n caso di variazione di un aggiudicatario va trasmessa la scheda S4

**Comment by LucaMaggioni1** [comment]
La risposta non è in linea con quanto condiviso negli ultimi GDL di lavoro. Per indicare una variazione di un aggiudicatario (1° in graduatoria) non è sufficiente sottoscrivere il contratto con altro soggetto della graduatoria?

**Comment by anac-uscp** [comment]
> In caso di variazione di un aggiudicatario va trasmessa la scheda S4
Si conferma quanto condiviso nello scorso GdL. 
La risposta citata è stata fornita interpretando la domanda come variazione dell'assetto del medesimo aggiudicatario.

**Comment by pceribelli** [comment]
.
