### ISSUE TITLE
scheda P7_2 - RDO da elenco 

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#573]
Buongiorno,

dal flusso orchestratore, per la scheda P7_2 (RDO da elenco) risultano appartenere al flusso solo la scheda P7_2 e la scheda NAG. non è previsto che anche per il flusso della P7_2 si debba comunicare l'aggiudicazione tramite le varie schede A (come nel caso del flusso della P7_1_3)? in caso contrario, dopo la pubblicazione, si va direttamente sulle schede di esecuzione che valgono per tutti i flussi?

Grazie

**Comment by anac-uscp** [comment]
Dopo l'invio della schedap P7_2 per una procedura negoziata sotto soglia bisogna inviare  una delle schede di aggiudicazione di  appalto, sopra o sotto soglia, settore ordinario, settore speciale, settore difesa e sicurezza. Al momento il flusso 72 non è stato inserito nelle schede di aggiudicazione. L'orchestratore verrà aggiornato al primo rilascio utile che non avverrà prima dell’esercizio della piattaforma.

**Comment by LucaMaggioni1** [comment]
nella risposta è indicato di: "inviare una delle schede di aggiudicazione di appalto, sopra o sotto soglia...". è corretto il riferimento a sopra soglia? 
essendo la P7_2 sotto soglia non dovrebbero essere previste solo le schede di aggiudicazione per sotto soglia?
