### ISSUE TITLE
Accesso tramite SPID

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#574]
Salve,

ho un grosso dubbio in merito al tema SPID. La piattaforma che si va a certificare deve integrare lo SPID reale (Inforcert, Aruba, etc.) o deve solo essere predisposta a livello infrastrutturale? Per capirci, basta lo SPID Demo https://demo.spid.gov.it/ come prova di integrazione? Basta questo a certificarsi o no?

Grazie

**Comment by mpizziconi** [comment]
I requisiti per la certificazione prevedono che la piattaforma in esercizio identifichi gli utenti mediante uno strumento LOA 3 o 4. In fase di certificazione gli utenti sono fittizi, di conseguenza la loro identificazione non può essere essere effettuata.
