### ISSUE TITLE
FVOE-Operatori economici Test

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#575]
Si chiede se sono presenti elenchi contenenti i CF degli Operatori Economici da utilizzare per effettuare i test sui servizi.
Grazie

**Comment by mpizziconi** [comment]
I casi di test per FVOE dipendono dagli analoghi casi di test previsti dagli enti certificanti nel loro ambiente di qualificazione. Al momento non sono disponibili soggetti di prova. al momento PCP non effettua validazione dell’esistenza del concorrente quindi possono essere liberamente utilizzati codici fiscali anche fittizi.
