### ISSUE TITLE
Scheda P7_1_3 - Regimi di validità

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#577]
Salve,
in merito alla risposta #539 :
la P7_3 vale per tutti i regimi, quindi sia per il regime ordinario sia per il regime alleggerito
si fa riferimento alla P7_1_3 ? si tratta di un refuso?

in quanto la P7_3 - scheda relativa alla costituzione elenco fornitori. Avviso per la costituzione elenco. Articolo 50 comma 1 lettere c) d) e)  decreto legislativo 36/2023. Articolo 3 Allegato II.1. Articolo 31 decreto legislativo  208/2011.

**Comment by UserM21** [comment]
@supportoAnac si richiede un riscontro

**Comment by UserM21** [comment]
@supportoAnac è possibile ricevere riscontro entro una data utile ai fini dell'integrazione?

**Comment by anac-uscp** [comment]
No, nessun refuso riguardo alla P7_3.
la P7_1_3 è la scheda di 'Avvio dell'indagine di mercato' per le procedure negoziate sottosoglia ex art. 50 comma 1 lett. c), d), e), e vale per tutti i regimi.
