### ISSUE TITLE
[BLK] Schede AD1_25 e AD1_26 - Obbligatorietà eForms

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#580]
Le schede:
- Scheda AD1_25 - Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform25. Avviso per la trasparenza volontaria ex ante, direttiva generale. Articolo 3 bis della direttiva 89/665/CEE. Articolo 86 decreto legislativo 36/2023.
- Scheda AD1_26 - Scheda di affidamento diretto (EU), valida per i soprasoglia e sottoglia con invio al TED con eform26. Avviso per la trasparenza volontaria ex ante, direttiva settoriale. Articolo 3 bis della direttiva 89/665/CEE. Articolo 86 decreto legislativo 36/2023.

Prevedono l'obbligatorietà dell'invio dei rispetti eForms.

Tuttavia, l'Art. 86. (Avviso volontario per la trasparenza preventiva) dichiara che:
 - c) motivazione della decisione della stazione appaltante di affidare il contratto senza pubblicazione di un bando di gara nella Gazzetta ufficiale dell’Unione europea;

E' corretta l'obbligatorietà degli eforms?

**Comment by UserM21** [comment]
@supportoAnac si richiede un riscontro

**Comment by anac-uscp** [comment]
No. Nelle schede AD1_25/26/27/28 l’eform è facoltativo. Si tratta di un avviso volontario che la stazione appaltante può decidere di trasmettere o meno. 
Si segnala, ad ogni buon conto, che la descrizione delle schede riportata nella issue è sbagliata poiché tali schede non si riferiscono al sotto soglia. Nell’orchestratore queste schede riguardano importi pari o superiori alla soglia comunitaria (cfr. colonna C-settore regime)

**Comment by anac-uscp** [comment]
> No. Nelle schede AD1_25/26/27/28 l’eform è facoltativo. Si tratta di un avviso volontario che la stazione appaltante può decidere di trasmettere o meno. Si segnala, ad ogni buon conto, che la descrizione delle schede riportata nella issue è sbagliata poiché tali schede non si riferiscono al sotto soglia. Nell’orchestratore queste schede riguardano importi pari o superiori alla soglia comunitaria (cfr. colonna C-settore regime)
**RETTIFICA ALLA SUDDETTA RISPOSTA DEL 29/11/2023**
Sì, nelle schede AD1_25/26/27/28 l’eform è obbligatorio. Quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e  b) -  utilizza le schede AD1_25/26/27/28 se ha deciso di pubblicare un avviso per la trasparenza volontaria ex ante.

**Comment by anac-uscp** [comment]
**RETTIFICA ALLA SUDDETTA RISPOSTA DEL 29/11/2023**
Sì, nelle schede AD1_25/26/27/28 l’eform è obbligatorio. Quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e b) - utilizza le schede AD1_25/26/27/28 se ha deciso di pubblicare un avviso per la trasparenza volontaria ex ante.
