### ISSUE TITLE
Servizio AUSA - mancanza di parametri di richiesta su contratto OpenAPI

### ISSUE THREAD

**Issue by cristiano-perin** [anticorruzione/npa#583]
Buongiorno,

abbiamo integrato il servizio AUSA ma otteniamo il seguente errore

```
Codice fiscale e codice Ausa non possono essere null
```

Tuttavia come da foto, il contratto OpenAPI caricato in PDND non prevede parametri in input.

![image](https://github.com/anticorruzione/npa/assets/148866739/3dc16f92-31ad-431d-ba40-30aa3bf15891)

Ci potete indicare quali parametri prevede il servizio?
Grazie

**Comment by mpizziconi** [comment]
si veda https://github.com/anticorruzione/npa/issues/474
