### ISSUE TITLE
Richiesta chiarimenti variazione aggiudicatario: invio scheda S4 e M1/M2 

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#584]
In fase di esecuzione, nel caso di variazione  dell’aggiudicatario di un contratto, si richiede se è sufficiente inviare la sola scheda S4 o in aggiunta anche la scheda di modifica contrattuale M1 o M2 in dipendenza del tipo di contratto, con le seguenti informazioni:
-	Scheda M1 campi della scheda eform: 
        o	  BT-200: mod-repl 
        o	  BT-201: "Modifiche dovute al fatto che un nuovo contraente sostituisce l'aggiudicatario iniziale perché gli succede o perché il 
                  committente si assume gli obblighi del contraente principale nei confronti dei suoi subappaltatori."
-	Scheda M2 il campo motiviModifica valorizzati
       o	  idTipologica: motiviModifica 
       o	  Codice: mod-repl

**Comment by anac-uscp** [comment]
E' sufficiente inviare la sola scheda S4
