### ISSUE TITLE
CONSIP -- ERR2La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata processo orchestratore S2-->A1_29

### ISSUE THREAD

**Issue by spagne** [anticorruzione/npa#586]
Otteniamo ERR2 nonostante il processo dell'orchestratore sia stato seguito correttamente prima dell'aggiudicazione da eseguire con scheda P1_29. La scheda di indizione è la P1_10. Sotto il paylod per la P1_29

SERVICE EXCEPTION: 400 Bad Request: "{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","dettaglio":"La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata","codice":"ERR2"}]}"

CF - RP --> CLNFRC90T41F839I

{
	"idAppalto": "48d91b9c-b0cf-4553-ba62-30692cc50c2c",
	"scheda": {
		"codice": {
			"idTipologica": "codiceScheda",
			"codice": "A1_29"
		},
		"versione": "1.0",
		"_stato": {
			"idTipologica": "string",
			"codice": "string"
		},
		"_dataCreazione": "2022-11-12T12:02:05Z",
		"body": {
			"anacForm": {
				"appalto": {
					"motivoUrgenza": {
						"idTipologica": "motivoUrgenza",
						"codice": "7"
					},
					
					"relazioneUnicaSulleProcedure": false,
					"opereUrbanizzazioneScomputo": false
				},
				"aggiudicazioni": [
					{
						"cig": "C00001C992",
						"numeroOfferteAmmesse": 3
						
					}
				]
			},
            "eform":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPENvbnRyYWN0QXdhcmROb3RpY2UgeG1sbnM9InVybjpvYXNpczpuYW1lczpzcGVjaWZpY2F0aW9uOnVibDpzY2hlbWE6eHNkOkNvbnRyYWN0QXdhcmROb3RpY2UtMiIKICAgICAgICAgICAgICAgICAgICAgIHhtbG5zOmNhYz0idXJuOm9hc2lzOm5hbWVzOnNwZWNpZmljYXRpb246dWJsOnNjaGVtYTp4c2Q6Q29tbW9uQWdncmVnYXRlQ29tcG9uZW50cy0yIgogICAgICAgICAgICAgICAgICAgICAgeG1sbnM6Y2JjPSJ1cm46b2FzaXM6bmFtZXM6c3BlY2lmaWNhdGlvbjp1Ymw6c2NoZW1hOnhzZDpDb21tb25CYXNpY0NvbXBvbmVudHMtMiIKICAgICAgICAgICAgICAgICAgICAgIHhtbG5zOmVmYWM9Imh0dHA6Ly9kYXRhLmV1cm9wYS5ldS9wMjcvZWZvcm1zLXVibC1leHRlbnNpb24tYWdncmVnYXRlLWNvbXBvbmVudHMvMSIKICAgICAgICAgICAgICAgICAgICAgIHhtbG5zOmVmYmM9Imh0dHA6Ly9kYXRhLmV1cm9wYS5ldS9wMjcvZWZvcm1zLXVibC1leHRlbnNpb24tYmFzaWMtY29tcG9uZW50cy8xIgogICAgICAgICAgICAgICAgICAgICAgeG1sbnM6ZWZleHQ9Imh0dHA6Ly9kYXRhLmV1cm9wYS5ldS9wMjcvZWZvcm1zLXVibC1leHRlbnNpb25zLzEiCiAgICAgICAgICAgICAgICAgICAgICB4bWxuczpleHQ9InVybjpvYXNpczpuYW1lczpzcGVjaWZpY2F0aW9uOnVibDpzY2hlbWE6eHNkOkNvbW1vbkV4dGVuc2lvbkNvbXBvbmVudHMtMiIKICAgICAgICAgICAgICAgICAgICAgID4KICAgPGV4dDpVQkxFeHRlbnNpb25zPgogICAgICA8ZXh0OlVCTEV4dGVuc2lvbj4KICAgICAgICAgPGV4dDpFeHRlbnNpb25Db250ZW50PgogICAgICAgICAgICA8ZWZleHQ6RWZvcm1zRXh0ZW5zaW9uPgogICAgICAgICAgICAgICA8ZWZhYzpOb3RpY2VSZXN1bHQ+CiAgICAgICAgICAgICAgICAgIDxlZmFjOkxvdFJlc3VsdD4KICAgICAgICAgICAgICAgICAgICAgPGNiYzpJRD5SRVMtMDAwMTwvY2JjOklEPgogICAgICAgICAgICAgICAgICAgICA8Y2JjOlRlbmRlclJlc3VsdENvZGUgbGlzdE5hbWU9Indpbm5lci1zZWxlY3Rpb24tc3RhdHVzIj5vcGVuLW53PC9jYmM6VGVuZGVyUmVzdWx0Q29kZT4KICAgICAgICAgICAgICAgICAgICAgPGVmYWM6VGVuZGVyTG90PgogICAgICAgICAgICAgICAgICAgICAgICA8Y2JjOklEPkxPVC0wMDAxPC9jYmM6SUQ+CiAgICAgICAgICAgICAgICAgICAgIDwvZWZhYzpUZW5kZXJMb3Q+CiAgICAgICAgICAgICAgICAgIDwvZWZhYzpMb3RSZXN1bHQ+CiAgICAgICAgICAgICAgIDwvZWZhYzpOb3RpY2VSZXN1bHQ+CiAgICAgICAgICAgICAgIDxlZmFjOk5vdGljZVN1YlR5cGU+CiAgICAgICAgICAgICAgICAgIDxjYmM6U3ViVHlwZUNvZGUgbGlzdE5hbWU9Im5vdGljZS1zdWJ0eXBlIj4yOTwvY2JjOlN1YlR5cGVDb2RlPgogICAgICAgICAgICAgICA8L2VmYWM6Tm90aWNlU3ViVHlwZT4KICAgICAgICAgICAgICAgPGVmYWM6T3JnYW5pemF0aW9ucz4KICAgICAgICAgICAgICAgICAgPGVmYWM6T3JnYW5pemF0aW9uPgogICAgICAgICAgICAgICAgICAgICA8ZWZhYzpDb21wYW55PgogICAgICAgICAgICAgICAgICAgICAgICA8Y2FjOlBhcnR5SWRlbnRpZmljYXRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgICAgIDxjYmM6SUQ+T1JHLTAwMDE8L2NiYzpJRD4KICAgICAgICAgICAgICAgICAgICAgICAgPC9jYWM6UGFydHlJZGVudGlmaWNhdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPGNhYzpQYXJ0eU5hbWU+CiAgICAgICAgICAgICAgICAgICAgICAgICAgIDxjYmM6TmFtZSBsYW5ndWFnZUlEPSJJVEEiPmNvbXVuZSBkaSByb21hPC9jYmM6TmFtZT4KICAgICAgICAgICAgICAgICAgICAgICAgPC9jYWM6UGFydHlOYW1lPgogICAgICAgICAgICAgICAgICAgICAgICA8Y2FjOlBvc3RhbEFkZHJlc3M+CiAgICAgICAgICAgICAgICAgICAgICAgICAgIDxjYmM6Q2l0eU5hbWU+cm9tYTwvY2JjOkNpdHlOYW1lPgogICAgICAgICAgICAgICAgICAgICAgICAgICA8Y2FjOkNvdW50cnk+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxjYmM6SWRlbnRpZmljYXRpb25Db2RlIGxpc3ROYW1lPSJjb3VudHJ5Ij5JVEE8L2NiYzpJZGVudGlmaWNhdGlvbkNvZGU+CiAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvY2FjOkNvdW50cnk+CiAgICAgICAgICAgICAgICAgICAgICAgIDwvY2FjOlBvc3RhbEFkZHJlc3M+CiAgICAgICAgICAgICAgICAgICAgICAgIDxjYWM6UGFydHlMZWdhbEVudGl0eT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgPGNiYzpDb21wYW55SUQ+Y29tdW5lIGRpIHJvbWE8L2NiYzpDb21wYW55SUQ+CiAgICAgICAgICAgICAgICAgICAgICAgIDwvY2FjOlBhcnR5TGVnYWxFbnRpdHk+CiAgICAgICAgICAgICAgICAgICAgICAgIDxjYWM6Q29udGFjdD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgPGNiYzpUZWxlcGhvbmU+MzMzMTMwMjE1NjwvY2JjOlRlbGVwaG9uZT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgPGNiYzpFbGVjdHJvbmljTWFpbD50ZXN0QGdtYWlsLmNvbTwvY2JjOkVsZWN0cm9uaWNNYWlsPgogICAgICAgICAgICAgICAgICAgICAgICA8L2NhYzpDb250YWN0PgogICAgICAgICAgICAgICAgICAgICA8L2VmYWM6Q29tcGFueT4KICAgICAgICAgICAgICAgICAgPC9lZmFjOk9yZ2FuaXphdGlvbj4KICAgICAgICAgICAgICAgPC9lZmFjOk9yZ2FuaXphdGlvbnM+CiAgICAgICAgICAgIDwvZWZleHQ6RWZvcm1zRXh0ZW5zaW9uPgogICAgICAgICA8L2V4dDpFeHRlbnNpb25Db250ZW50PgogICAgICA8L2V4dDpVQkxFeHRlbnNpb24+CiAgIDwvZXh0OlVCTEV4dGVuc2lvbnM+CiAgIDxjYmM6VUJMVmVyc2lvbklEPjIuMzwvY2JjOlVCTFZlcnNpb25JRD4KICAgPGNiYzpDdXN0b21pemF0aW9uSUQ+ZWZvcm1zLXNkay0xLjg8L2NiYzpDdXN0b21pemF0aW9uSUQ+CiAgIDxjYmM6SUQgc2NoZW1lTmFtZT0ibm90aWNlLWlkIj42Njg1MjcxMC0xZjMyLTQyOTItYmQ0NC1lYjk5YzM0ZDI1MjA8L2NiYzpJRD4KICAgPGNiYzpDb250cmFjdEZvbGRlcklEPmJhNDY5OTNhLTQwNGEtNGIyNi1hZDkzLTI2ZjNhYzNiNTI3NDwvY2JjOkNvbnRyYWN0Rm9sZGVySUQ+CiAgIDxjYmM6SXNzdWVEYXRlPjIwMjMtMTEtMDZaPC9jYmM6SXNzdWVEYXRlPgogICA8Y2JjOklzc3VlVGltZT4xNjo1OToxMVo8L2NiYzpJc3N1ZVRpbWU+CiAgIDxjYmM6VmVyc2lvbklEPjAxPC9jYmM6VmVyc2lvbklEPgogICA8Y2JjOlJlZ3VsYXRvcnlEb21haW4+MzIwMTRMMDAyNDwvY2JjOlJlZ3VsYXRvcnlEb21haW4+CiAgIDxjYmM6Tm90aWNlVHlwZUNvZGUgbGlzdE5hbWU9InJlc3VsdCI+Y2FuLXN0YW5kYXJkPC9jYmM6Tm90aWNlVHlwZUNvZGU+CiAgIDxjYmM6Tm90aWNlTGFuZ3VhZ2VDb2RlIGxpc3ROYW1lPSJsYW5ndWFnZSI+SVRBPC9jYmM6Tm90aWNlTGFuZ3VhZ2VDb2RlPgogICA8Y2FjOkNvbnRyYWN0aW5nUGFydHk+CiAgICAgIDxjYWM6Q29udHJhY3RpbmdQYXJ0eVR5cGU+CiAgICAgICAgIDxjYmM6UGFydHlUeXBlQ29kZSBsaXN0TmFtZT0iYnV5ZXItbGVnYWwtdHlwZSI+Y2dhPC9jYmM6UGFydHlUeXBlQ29kZT4KICAgICAgPC9jYWM6Q29udHJhY3RpbmdQYXJ0eVR5cGU+CiAgICAgIDxjYWM6Q29udHJhY3RpbmdBY3Rpdml0eT4KICAgICAgICAgPGNiYzpBY3Rpdml0eVR5cGVDb2RlIGxpc3ROYW1lPSJhdXRob3JpdHktYWN0aXZpdHkiPmVkdWNhdGlvbjwvY2JjOkFjdGl2aXR5VHlwZUNvZGU+CiAgICAgIDwvY2FjOkNvbnRyYWN0aW5nQWN0aXZpdHk+CiAgICAgIDxjYWM6UGFydHk+CiAgICAgICAgIDxjYWM6UGFydHlJZGVudGlmaWNhdGlvbj4KICAgICAgICAgICAgPGNiYzpJRD5PUkctMDAwMTwvY2JjOklEPgogICAgICAgICA8L2NhYzpQYXJ0eUlkZW50aWZpY2F0aW9uPgogICAgICA8L2NhYzpQYXJ0eT4KICAgPC9jYWM6Q29udHJhY3RpbmdQYXJ0eT4KICAgPGNhYzpUZW5kZXJpbmdQcm9jZXNzPgogICAgICA8Y2JjOlByb2NlZHVyZUNvZGUgbGlzdE5hbWU9InByb2N1cmVtZW50LXByb2NlZHVyZS10eXBlIj5vcGVuPC9jYmM6UHJvY2VkdXJlQ29kZT4KICAgPC9jYWM6VGVuZGVyaW5nUHJvY2Vzcz4KICAgPGNhYzpQcm9jdXJlbWVudFByb2plY3Q+CiAgICAgIDxjYmM6TmFtZSBsYW5ndWFnZUlEPSJJVEEiPmZvcm5pdHVyZTwvY2JjOk5hbWU+CiAgICAgIDxjYmM6RGVzY3JpcHRpb24gbGFuZ3VhZ2VJRD0iSVRBIj5mb3JuaXR1cmU8L2NiYzpEZXNjcmlwdGlvbj4KICAgICAgPGNiYzpQcm9jdXJlbWVudFR5cGVDb2RlIGxpc3ROYW1lPSJjb250cmFjdC1uYXR1cmUiPnN1cHBsaWVzPC9jYmM6UHJvY3VyZW1lbnRUeXBlQ29kZT4KICAgICAgPGNhYzpNYWluQ29tbW9kaXR5Q2xhc3NpZmljYXRpb24+CiAgICAgICAgIDxjYmM6SXRlbUNsYXNzaWZpY2F0aW9uQ29kZSBsaXN0TmFtZT0iY3B2Ij4zOTE2MDAwMDwvY2JjOkl0ZW1DbGFzc2lmaWNhdGlvbkNvZGU+CiAgICAgIDwvY2FjOk1haW5Db21tb2RpdHlDbGFzc2lmaWNhdGlvbj4KICAgPC9jYWM6UHJvY3VyZW1lbnRQcm9qZWN0PgogICA8Y2FjOlByb2N1cmVtZW50UHJvamVjdExvdD4KICAgICAgPGNiYzpJRCBzY2hlbWVOYW1lPSJMb3QiPkxPVC0wMDAxPC9jYmM6SUQ+CiAgICAgIDxjYWM6VGVuZGVyaW5nVGVybXM+CiAgICAgICAgIDxjYmM6RnVuZGluZ1Byb2dyYW1Db2RlIGxpc3ROYW1lPSJldS1mdW5kZWQiPm5vLWV1LWZ1bmRzPC9jYmM6RnVuZGluZ1Byb2dyYW1Db2RlPgogICAgICAgICA8Y2FjOkF3YXJkaW5nVGVybXM+CiAgICAgICAgICAgIDxjYWM6QXdhcmRpbmdDcml0ZXJpb24+CiAgICAgICAgICAgICAgIDxjYmM6Q2FsY3VsYXRpb25FeHByZXNzaW9uIGxhbmd1YWdlSUQ9IklUQSI+dGVzdDwvY2JjOkNhbGN1bGF0aW9uRXhwcmVzc2lvbj4KICAgICAgICAgICAgICAgPGNhYzpTdWJvcmRpbmF0ZUF3YXJkaW5nQ3JpdGVyaW9uPgogICAgICAgICAgICAgICAgICA8Y2JjOkF3YXJkaW5nQ3JpdGVyaW9uVHlwZUNvZGUgbGlzdE5hbWU9ImF3YXJkLWNyaXRlcmlvbi10eXBlIj5jb3N0PC9jYmM6QXdhcmRpbmdDcml0ZXJpb25UeXBlQ29kZT4KICAgICAgICAgICAgICAgICAgPGNiYzpEZXNjcmlwdGlvbiBsYW5ndWFnZUlEPSJJVEEiPnRlc3Q8L2NiYzpEZXNjcmlwdGlvbj4KICAgICAgICAgICAgICAgPC9jYWM6U3Vib3JkaW5hdGVBd2FyZGluZ0NyaXRlcmlvbj4KICAgICAgICAgICAgPC9jYWM6QXdhcmRpbmdDcml0ZXJpb24+CiAgICAgICAgIDwvY2FjOkF3YXJkaW5nVGVybXM+CiAgICAgICAgIDxjYWM6QXBwZWFsVGVybXM+CiAgICAgICAgICAgIDxjYWM6QXBwZWFsUmVjZWl2ZXJQYXJ0eT4KICAgICAgICAgICAgICAgPGNhYzpQYXJ0eUlkZW50aWZpY2F0aW9uPgogICAgICAgICAgICAgICAgICA8Y2JjOklEPk9SRy0wMDAxPC9jYmM6SUQ+CiAgICAgICAgICAgICAgIDwvY2FjOlBhcnR5SWRlbnRpZmljYXRpb24+CiAgICAgICAgICAgIDwvY2FjOkFwcGVhbFJlY2VpdmVyUGFydHk+CiAgICAgICAgIDwvY2FjOkFwcGVhbFRlcm1zPgogICAgICA8L2NhYzpUZW5kZXJpbmdUZXJtcz4KICAgICAgPGNhYzpUZW5kZXJpbmdQcm9jZXNzPgogICAgICAgICA8Y2JjOkdvdmVybm1lbnRBZ3JlZW1lbnRDb25zdHJhaW50SW5kaWNhdG9yPmZhbHNlPC9jYmM6R292ZXJubWVudEFncmVlbWVudENvbnN0cmFpbnRJbmRpY2F0b3I+CiAgICAgICAgIDxjYWM6QXVjdGlvblRlcm1zPgogICAgICAgICAgICA8Y2JjOkF1Y3Rpb25Db25zdHJhaW50SW5kaWNhdG9yPmZhbHNlPC9jYmM6QXVjdGlvbkNvbnN0cmFpbnRJbmRpY2F0b3I+CiAgICAgICAgIDwvY2FjOkF1Y3Rpb25UZXJtcz4KICAgICAgICAgPGNhYzpDb250cmFjdGluZ1N5c3RlbT4KICAgICAgICAgICAgPGNiYzpDb250cmFjdGluZ1N5c3RlbVR5cGVDb2RlIGxpc3ROYW1lPSJmcmFtZXdvcmstYWdyZWVtZW50Ij5mYS1taXg8L2NiYzpDb250cmFjdGluZ1N5c3RlbVR5cGVDb2RlPgogICAgICAgICA8L2NhYzpDb250cmFjdGluZ1N5c3RlbT4KICAgICAgICAgPGNhYzpDb250cmFjdGluZ1N5c3RlbT4KICAgICAgICAgICAgPGNiYzpDb250cmFjdGluZ1N5c3RlbVR5cGVDb2RlIGxpc3ROYW1lPSJkcHMtdXNhZ2UiPm5vbmU8L2NiYzpDb250cmFjdGluZ1N5c3RlbVR5cGVDb2RlPgogICAgICAgICA8L2NhYzpDb250cmFjdGluZ1N5c3RlbT4KICAgICAgPC9jYWM6VGVuZGVyaW5nUHJvY2Vzcz4KICAgICAgPGNhYzpQcm9jdXJlbWVudFByb2plY3Q+CiAgICAgICAgIDxjYmM6SUQ+SURMb3QyPC9jYmM6SUQ+CiAgICAgICAgIDxjYmM6TmFtZSBsYW5ndWFnZUlEPSJJVEEiPmZvcm5pdHVyZTwvY2JjOk5hbWU+CiAgICAgICAgIDxjYmM6RGVzY3JpcHRpb24gbGFuZ3VhZ2VJRD0iSVRBIj5mb3JuaXR1cmU8L2NiYzpEZXNjcmlwdGlvbj4KICAgICAgICAgPGNiYzpQcm9jdXJlbWVudFR5cGVDb2RlIGxpc3ROYW1lPSJjb250cmFjdC1uYXR1cmUiPnN1cHBsaWVzPC9jYmM6UHJvY3VyZW1lbnRUeXBlQ29kZT4KICAgICAgICAgPGNhYzpNYWluQ29tbW9kaXR5Q2xhc3NpZmljYXRpb24+CiAgICAgICAgICAgIDxjYmM6SXRlbUNsYXNzaWZpY2F0aW9uQ29kZSBsaXN0TmFtZT0iY3B2Ij4zOTE2MDAwMDwvY2JjOkl0ZW1DbGFzc2lmaWNhdGlvbkNvZGU+CiAgICAgICAgIDwvY2FjOk1haW5Db21tb2RpdHlDbGFzc2lmaWNhdGlvbj4KICAgICAgPC9jYWM6UHJvY3VyZW1lbnRQcm9qZWN0PgogICA8L2NhYzpQcm9jdXJlbWVudFByb2plY3RMb3Q+CiAgIDxjYWM6VGVuZGVyUmVzdWx0PgogICAgICA8Y2JjOkF3YXJkRGF0ZT4yMDAwLTAxLTAxWjwvY2JjOkF3YXJkRGF0ZT4KICAgPC9jYWM6VGVuZGVyUmVzdWx0Pgo8L0NvbnRyYWN0QXdhcmROb3RpY2U+"
		}
	}
}

**Comment by lauralu1993** [comment]
abbiamo eseguito lo stesso test con la scheda di indizione P1.11 (inviando P1.11 -> S1 -> S2 ) ma riscontriamo lo stesso errore. 
idAppalto: f07c49e8-5ced-4dae-807b-d3d0c06b27ad.
[A1.30.json](https://github.com/anticorruzione/npa/files/13335186/A1.30.json)

aggiungiamo chiamando il servizio ricerca-schede le schede S1 e S2 risultano in stato CONF mentre il servizio esito-operazione riporta per le stesse schede SC_NON_CONF

**Comment by mpizziconi** [comment]
idAppalto non è sufficiente a rintracciare l'operaizone nel log e fornire assistenza
si ribadisce la necessità di fornire "govway_message_id" o "govway_transaction_id"
