### ISSUE TITLE
Casi d'uso schede AD2_25 e AD2_26

### ISSUE THREAD

**Issue by PhilippGrosslercher** [anticorruzione/npa#587]
Buongiorno,

1. Per la scheda AD2_25 nel file orchestratore come "evento" é indicato l'affidamento diretto. Nella colonna "riferimento normativo" é indicato "Articolo 50 comma 1 lettere c) d) e)  decreto legislativo 36/2023
Articolo 50 comma 9 decreto legislativo 36/2023", quindi le "procedure negoziate senza bando" (nominati anche espressamente nelle nelle Regole di entrambi le schede (REG68)) per le quali il comma 9 prevede che devono essere comunicati anche i partecipanti.

é corretto che la scheda AD2_25 deve essere utilizzata per comunicare lo svolgimento di una procedura negoziata senza bando e per gli affidamenti diretti rispettivamente infra 140.000 e 150.000 Euro nei settori ordinari?

2. Per la scheda AD2_26 nel file orchestratore come "evento" é indicato l'affidamento diretto. Nella colonna "riferimento normativo" é indicato solo "Articolo 50 comma 9 decreto legislativo 36/2023". 

é corretto che la scheda AD2_26 deve essere utilizzata per solo per gli affidamenti diretti rispettivamente infra 140.000 e 150.000 Euro nei settori speciali? 

Grazie

**Comment by anac-uscp** [comment]
Le schede AD2_25 (settori ordinari) e AD26 (settori speciali) vanno usate quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto (il limite massimo per l'affidamento diretto è previsto dall’art 50 comma 1 lett. a) e b) ed è pari a 140.000 per servizi e forniture, 150.000 per lavori) e non intende pubblicare un avviso per la trasparenza volontaria ex ante.

Per le procedure negoziate senza bando sottosoglia ex art. 50, comma 1 lett. c), d), e), bisogna usare le schede P7.1.3 o P.7.2, a seconda del caso.
