### ISSUE TITLE
FVOE Condizioni per esecuzione test

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#588]
Buongiorno,
vi segnaliamo che per testare l'intero processo occorrerebbero degli OOEE con un fascicolo virtuale esistente (e non vuoto) che accettino le richieste di accesso inviate dalla SA di test. Come possiamo simulare le attività degli OOEE, le attività degli Enti Certificatori e le relative risposte? Potete specificarci se è previsto un data preparation o se sono previsti degli automatismi lato ANAC?

**Comment by sfala** [comment]
Buongiorno @mpizziconi, potremmo avere un aggiornamento? Al momento non riusciamo ad avviare la fase di test.

Grazie

**Comment by mariottiDPA** [comment]
buongiorno, ci accodiamo alla issue avendo lo stesso problema @mpizziconi

**Comment by supportoAnac** [comment]
Lo scenario di test è stato reso disponibile alle piattaforme.
