### ISSUE TITLE
[BLK] Aggiornamento crea appalto

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#589]
Buongiorno,

stamattina abbiamo visto che è cambiato il changelog e quindi immaginiamo che è stato completato il rilascio che era previsto la scorsa settimana per la correzione dei diversi bug segnalati.
Chiamando l'e-service 'crea appalto' ora al posto del precedente errore, riportato nella issue #457, ci viene restituito un generico:

401 Unauthorized

Ci potete fornire supporto? Sulla PDND non abbiamo cambiato nulla, client e finalità sono rimaste quelle precedenti.

@mpizziconi 

Grazie

**Comment by dpagliari** [comment]
Dimenticavo, E-service di riferimento

[PCP - Comunica appalto, versione 4]

**Comment by supportoAnac** [comment]
La risposta di errore è stata causata da un disservizio temporaneo. Sporadicamente si notano nel log errori per mancata autorizzazione 401 per i quali l’analisi è in corso.
