### ISSUE TITLE
[BLK] Errore crea-appalto Schede P* e AD*

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#591]
Dopo il nuovo rilascio tutte le chiamate alle schede P* e AD* rispondono con 401 Unauthorized.
Inutile dire che per quanto ci riguarda nulla è stato cambiato nelle chiamate.
Restiamo in attesa di urgente riscontro.
@mpizziconi 
Grazie.

**Comment by supportoAnac** [comment]
La risposta di errore è stata causata da un disservizio temporaneo. Sporadicamente si notano nel log errori per mancata autorizzazione 401 per i quali l’analisi è in corso.
