### ISSUE TITLE
[Consip][BLK] errore 401 unauthorized 

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#593]
a seguito dell'ultimo rilascio ANAC non riusciamo più a invocare i servizi. 
l'errore che otteniamo è il seguente: 
SERVICE EXCEPTION: 401 Unauthorized: "{"status":401,"title":"KO","detail":"Non Autorizzato","type":"about:blank","errori":[{"idTipologica":"errori","codice":"SEC05"}]}"

**Comment by davideorsi-bit** [comment]
Anche il nostro gruppo di sviluppo che segue le implementazioni per le integrazioni di ARIA regione Lombardia, riscontra gli stessi problemi.

**Comment by paolo-urbanetto** [comment]
Idem per Maggioli; riprovato anche in questo momento.

**Comment by supportoAnac** [comment]
La risposta di errore è stata causata da un disservizio temporaneo. Sporadicamente si notano nel log errori per mancata autorizzazione 401 per i quali l’analisi è in corso.
