### ISSUE TITLE
CHANGELOG Orchestratore

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#594]
Sarebbe utile capire effettivamente cosa sia cambiato nella nuova versione dell'orchestratore (file schema-cronologia-schede). E' possibile avere tale informazione?

Nel CHANGELOG -  Note di rilascio del 13/11/2023 - purtroppo viene solo indicata genericamente la dicitura "Aggiornato il file schema-cronologia-schede.xlsx" e non aiuta a capire le effettive modifiche.

Grazie

**Comment by supportoAnac** [comment]
Le modifiche al changelog e all’orchestratore sono indicate nella nota di rilascio.
