### ISSUE TITLE
Attributo "linkDocumenti" - Errore "REG8" in verifica-appalto

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#598]
Con la versione dei servizi di oggi l'attributo linkDocumenti non è più obbligatorio in crea-appalto, tuttavia se non lo si valorizza da verifica-appalto si ottiene KO con codice errore  "REG8" ("Il campo deve essere una url valida e iniziare per http oppure per https.").
Aggiriamo l'errore continuando a valorizzare l'attributo linkDocumenti con una fake url.

Test case:
idAppalto con errore:  `1bc589e1-6548-47bc-b540-af67292b4eaa`
idAppalto con gli stessi dati, ma linkDocumenti valorizzato: `00c78cab-b3a0-4667-83c3-a35f39d37064
`

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 24/11/2023.
