### ISSUE TITLE
schede senza eForm - Campi con riferimento a eForm

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#599]
Abbiamo rilevato che in schede che non richiedono l'eform si fa riferimento al campo eform. Di seguito riportiamo un esempio:
nella SchedaAD3.anacform
in AggiudicazioneAD3Type.datiBaseAggiudicazioneAppaltoType.dataAggiudicazione rileviamo il riferimento al campo bt-1451 ma la scheda AD3 non prevede l'eform.
E' corretto far riferimento al campo eform indicato o è un refuso?

Per completezza si riporta lo screenshot del campo in cui è indicato il campo eform sopraindicato:
![image](https://github.com/anticorruzione/npa/assets/135005848/1a3143c2-942d-4dcb-a316-9c68c2321507)

Grazie

**Comment by supportoAnac** [comment]
In generale, le schede per cui sono presenti le eForm ereditano i dati delle eForm.
Il campo **dataAggiudicazione** equivale al campo **BT1451** dell'eForm.
Quando una scheda non contiene la eForm, vengono acquisiti i campi comuni , e il campo dataAggiudicazione assume il valore che nella eForm è il BT1451.
La descrizione del campo vuole fornire una indicazione di cosa ci aspettiamo di trovare al suo interno, e verrà migliorata nei prossimi rilasci.
