### ISSUE TITLE
Cancellazione appalto (e CIG) dopo periodo temporale prefissato

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#6]
Lato NPA è previsto un servizio di cancella-appalto che scatta dopo un valore temporale prefissato. Si chiede conferma di tale automatismo e quantificazione dell’arco temporale

**Comment by supportoAnac** [comment]
Si, è previsto. Dopo il "confermaAppalto" e prima del "pubblicaAvviso" non è possibile effettuare modifiche; eventualmente è permessa solo la cancellazione. Il tempo attualmente definito è 90 giorni.
