### ISSUE TITLE
[Consip] Invio di più Schede per aggiudicazione di lotti in momenti diversi

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#601]
è possibile trasmettere (crea-scheda, conferma-scheda, pubblica-avviso) più schede A* di aggiudicazione per lo stesso appalto in tempi diversi specificando i lotti / CIG di riferimento?
 ad esempio per un appalto con 5 lotti, si trasmette una prima scheda A1.29 per i lotti 1,2,3 e successivamente una scheda A1.29 per i rimanenti lotti 4 e 5.

infatti, Nel caso di gare a lotti accade spesso che vengano aggiudicati prima alcuni lotti e solo in seguito altri

**Comment by mpizziconi** [comment]
La procedura descritta è consentita
