### ISSUE TITLE
[BLK] Errore 400 AUT01 - Crea appalto

### ISSUE THREAD

**Issue by cragazzi** [anticorruzione/npa#602]
Buongiorno,
abbiamo provato ad eseguire una chiamata crea appalto con scheda P2_16 ed abbiamo ottenuto il seguente errore:

{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","codice":"AUT01"}]}

Secondo la tipologica errori, corrisponde al seguente messaggio: "l'utente non è presente tra le stazioni appaltanti".
Abbiamo utilizzato un'utenza fornita da voi, usata anche nelle chiamate delle scorse settimane. A cosa è dovuto questo errore?

Vi riporto gli ID associati alla chiamata:
GovWay-Message-ID: 7a65b97f-2b9d-42ad-aa71-2b135954f99f
GovWay-Transaction-ID: 7e8098d6-8385-11ee-a061-0050568e9679

Vi ringrazio

**Comment by mpizziconi** [comment]
L'errore evidenziato non corrisponde alla transazione collegata a GovWay-Message-ID: 7a65b97f-2b9d-42ad-aa71-2b135954f99f
Per la transazione indicata l'errore è dovuto al payload non ben formato 
oggetto stazione appaltante:

"stazioniAppaltanti":[
               {
                  "codiceFiscale":"string",
                  "codiceAusa":"string",
                  "funzioniSvolte":[
                     {
                        "idTipologica":"funzioniSvolte",
                        "codice":"1"
                     }
                  ],
                  "saTitolare":true
               }
            ]



Si prega di fornire correttamente le informazioni per consentire un rapido accesso ai log e evitare inutili perdite di tempo
Grazie
