### ISSUE TITLE
idPartecipante - Richiesta informazioni compilazione

### ISSUE THREAD

**Issue by ctav8** [anticorruzione/npa#603]
Buongiorno,
in relazione al campo `idPartecipante`  divenuto dal rilascio del 13/11 obbligatorio (indicato come di formato UUID) presente nei tipi relativi ai partecipanti/aggiudicatari (es. AggiudicatarioAD5Type, PartecipanteADType) si chiede di specificare come compilare il campo. 
Va generato in fase di creazione della chiamata da parte nostra oppure va compilato con uno specifico valore estratto da qualche altro servizio?
Grazie.

**Comment by supportoAnac** [comment]
Confermiamo che va generato in fase di creazione della chiamata dalla stazione appaltante, quando si invia la scheda S2 o quando si inviano le schede di affidamento diretto con l’elenco dei partecipanti.
