### ISSUE TITLE
[BLK][BOLZANO/TOSCANA] Errore 401

### ISSUE THREAD

**Issue by user6330** [anticorruzione/npa#604]
Stiamo riscontrando questo errore a tratti su diverse chiamate

```
{
   "status": 401,
   "title": "KO",
   "detail": "Non Autorizzato",
   "type": "about:blank",
   "errori": [   {
      "idTipologica": "errori",
      "codice": "SEC05"
   }]
}
```

e non riusciamo ad eseguire un flusso concreto poiché riscontriamo questo errore una chiamata si e una no.
Quando sarà stabile l'ambiente di collaudo?

**Comment by mpizziconi** [comment]
senza riferimenti agli ID chiamata non è possibile fare analisi
