### ISSUE TITLE
Tempi medi per risposta ai servizi ASINCRONI

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#605]
INTERCENT-ER
Si richiede se esiste una regola di schedulazione delle attività inerenti i servizi asincroni.
C'è un tempo medio di risposta da considerare "normale"??
Alle 08:30 ho inviato un conferma-appalto ed ad ora (circa 4 ore) non ho ancora ottenuto risposta.
E' un tempo tecnico normale oppure ci sono dei problemi??
Grazie.

**Comment by supportoAnac** [comment]
Salve, non esiste un tempo medio da considerare per i servizi asincroni.
