### ISSUE TITLE
Univocità dell'attributo codiceAppalto

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#607]
Buongiorno,
dalla specifica codiceAppalto (string, maxLength: 64) viene descritto come Identificativo univoco dell'appalto definito dalla Stazione Appaltante.
Come viene gestita l'univocità di codiceAppalto da PCP?

Ovvero è possibile inviare il medesimo codiceAppalto per due diverse Stazioni Appaltanti?

Se la piattaforma X gestisce la gara con  codiceAppalto A0001 per la SA Y, la piattaforma Z può trasmettere dati con  il medesimo codiceAppalto A0001  per la medesima SA Y?

**Comment by paolo-urbanetto** [comment]
Non avendo avuto riscontro da settimane, abbiamo adeguato noi la codifica con un uuid univoco per ogni situazione.
Potete chiudere, grazie.

**Comment by supportoAnac** [comment]
PCP verifica l’univocità del codice appalto sull’intera banca dati. La struttura della stringa non è definita per lasciare alla piattaforma libertà del formato.
Questo codice non è significativo in PCP ma può assumere un significato all’esterno del sistema (al pari di quello che era il codice_gara su Simog viene ad esempio usato nel sistema di riscossione di ANAC). 

Un formato leggibile del codice può essere a titolo di puro esempio
<codiceAUSA>-<progressivo>
