### ISSUE TITLE
[BLK] Servizi Comuni - esito-operazione

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#613]
E' da questa mattina alle 08:30 (da ormai 7 ore) che la funzione di esito-operazione restituisce la lista esiti vuota!!!
E' possibile comprendere cosa sta succedendo?
Allego la risposta più recente.
Grazie 

{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[]}

Server nginx
Date Wed, 15 Nov 2023 14:24:22 GMT
Transfer-Encoding chunked
Connection keep-alive
Cache-Control private
Set-Cookie 48660c0d09a5bc00d558af703a720b6f=f083a79ae70f99ac0f069adb2a0a9caa; path=/; HttpOnly; Secure; SameSite=None
X-XSS-Protection 1; mode=block
GovWay-Message-ID 16e811e9-2640-4bf4-9358-471b491d86b9
X-Frame-Options DENY
GovWay-Transaction-ID c4d18e04-83b9-11ee-a061-0050568e9679
Vary Access-Control-Request-Headers, Access-Control-Request-Method, Origin
X-Content-Type-Options nosniff
Strict-Transport-Security max-age=31536000 ; includeSubDomains, max-age=63072000
La richiesta HTTP ha restituito uno stato non riuscito: OK

**Comment by FRASCA57** [comment]
Ormai siamo a più di 24 ore!!! non ho l'aggettivo giusto per commentare.

**Comment by mariottiDPA** [comment]
se poi aggiungiamo che non si riescono neanche a recuperare i CIG... #612

**Comment by FRASCA57** [comment]
E' possibile sapere cosa si deve fare??? siamo bloccati da 3 giorni, mentre vedo che altri colleghi hanno problemi su servizi successivi!!! Che cosa bisogna fare per una risposta????

**Comment by paolo-urbanetto** [comment]
Mi associo. Siamo tutti in forte criticità. 
Noi non siamo ancora riusciti ad arrivare a chiudere 1 procedimento con tutte le schede.
Abbiamo provato una semplice [AD5](https://github.com/anticorruzione/npa/issues/596) e siamo fermi. 
Siamo arrivati a pubblicare l'avviso di una P2_16, ma non abbiamo in response il [CIG](https://github.com/anticorruzione/npa/issues/612) e lo [stato è incoerente](https://github.com/anticorruzione/npa/issues/619) e bloccato.
Sull'esecuzione non possiamo inviare ancora nulla.
Non vorremo andare a tentativi.
Stiamo lavorando sull'applicazione aspettando che l'ambiente diventi un minimo stabile per poter fare invii di schede, altrimenti perdiamo troppo tempo.

**Sarebbe possibile avere dei payload di esempio di test case di schede che sono andati a buon fine?**
Così potremo replicarli e procedere con i nostri sviluppi senza intralciarci a vicenda:
- voi potreste completare e testare il sistema senza che vi si distragga con decine di issue identiche
- noi sviluppare i nostri prodotti, usando tutti quanti gli stessi test case, arrivando alla fine dei procedimenti

Poi, tra 2-3 settimane, si fanno solo test inviando dati per le varie casistiche.

**Comment by FRASCA57** [comment]
E' passata una settimana, forse bisogna scrivere formalmente per avere una risposta??

**Comment by pakozack** [comment]
Mi associo. Noi siamo bloccati praticamente su tutto!
Le AD non funzionano. 
La P1_16 neanche. 
La P2_10 è l'unica che siamo riusciti a creare ma abbiamo problemi con la conferma. Continua a dare un errore su un campo non presente e non documentato.
Le altre non le abbiamo neanche provate tanto il risultato già si sa...
Qualcuno ha qualche idea di come risolvere? Oggi è 20/11. Quanti giorni lavorativi ci sono fino al 31/12? E in tutto questo dobbiamo sviluppare e soprattutto fare un minimo di test prima di andare in produzione!
Sono senza parole...

**Comment by mariottiDPA** [comment]
e se non riusciamo ad andare avanti con la creazione degli appalti, non oso pensare cosa ci aspetti sulle schede di post pubblicazione!

**Comment by pakozack** [comment]
la butto li... che ne dite di creare un gruppo slack o qualcosa del genere in modo da condividere info? mi rivolgo soprattutto a fornitori privati...

**Comment by collaudo5** [comment]
Ciao come fornitori privati siamo disponibili a qualsiasi cosa possa agevolare il raggiungimento dell'obiettivo comune ma se ANAC non ci fornisce supporto non la portiamo a casa comunque.

**Comment by FRASCA57** [comment]
Buonasera,
ho appena risolto il mio problema ... mancava un "_" nei parametri di chiamata!!!!!!
Sto provando ad andare avanti!!!

**Comment by FRASCA57** [comment]
Risolto
