### ISSUE TITLE
schede aggiudicazione - caso di aggiudicazione parziale

### ISSUE THREAD

**Issue by GiovanniSom** [anticorruzione/npa#614]
Buongiorno,
dalla documentazione ed in particolare dal grafo a stati dell'appalto è indicato che le schede di aggiudicazione conducono l'intero appalto allo stato successivo di aggiudicazione o non aggiudicazione.
Qualora per una gara con più lotti si verifichi una situazione di aggiudicazione parziale, come deve essere gestita?
deve essere trasmessa e confermata la scheda di aggiudicazione per i soli lotti aggiudicati, omettendo i lotti non aggiudicati dalla lista?
grazie e buona giornata

**Comment by mpizziconi** [comment]
E' possibile inviare una sequenza di schede di aggiudicazione, ciascuna con l'indicazione dell'esito dei differenti lotti che compongono la procedura. Si faccia riferimento alle specifiche tecniche delle eForm per una descrizione completa delle modalità di invio
