### ISSUE TITLE
RP e DRP - funzioni

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#622]
Buongiorno,

tramite l'aggiungi soggetto, una volta assegnato un DRP potrà utilizzare tutti i servizi disponibili per la sua fase? nello swagger, per il servizio di aggiungi soggetti sono presenti come dati di input il tipo di operazione e il tipo di servizio, è possibile assegnare al DRP solo una parte della totalità dei servizi che riguardano la sua fase?

Se viene assegnato un DRP di una fase, il RUP può continuare a chiamare i servizi corrispondenti alla fase assegnata ad un DRP?

Grazie

**Comment by mpizziconi** [comment]
Il DRP indicato dal RP è abilitato su tutti i servizi della fase. La maggiore granularità della delega è stata progettata ma non è attualmente attiva.
Il RP che delega un DRP mantiene solo la possibilità di supervisione del procedimento tramite le operazioni di sola lettura
