### ISSUE TITLE
Obblighi di pubblicità a livello nazionale - procedure negoziate senza bando

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#625]
Buongiorno, perché viene indicato S**I su pubblicazione nazionale per le schede della famiglia P7**? l'art. 50 c. 8 recita "8. **I bandi** e gli avvisi di pre-informazione relativi ai contratti di cui alla presente Parte sono pubblicati a livello nazionale con le modalità di cui all’[articolo 85](https://www.bosettiegatti.eu/info/norme/statali/2023_0036.htm#085), con esclusione della trasmissione del bando di gara all’Ufficio delle pubblicazioni dell'Unione europea" ma in questi casi **il bando non c'è**.

**Comment by anac-uscp** [comment]
si veda l'art.2 comma 2 Allegato II.1
"Elenchi degli operatori economici e indagini di mercato per gli affidamenti di contratti di importo inferiore alle soglie di rilevanza europea"
