### ISSUE TITLE
Gestione Tipologiche nelle schede (P1_16)

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#627]
INTERCENT-ER
Non è chiaro a cosa far riferimento per inserire correttamente le informazioni relative a tipologiche all'interno di una scheda.
Facendo riferimento ad una specifica scheda, la P1_16 abbiamo quanto segue:

1. categoriaMerceologica in documentazione senza articolazione ed il servizio la chiede con articolazione idTipologica - codice
2. motivazioneCIG viene richiesto senza l'articolazione in idTipologica e Codice, ma il servizio richiede che venga specificato con l'inserimento dei due campi (peraltro, anche se nel changelog si indica che la tipologica ha cambiato nome da motivazioneCig a motivazioneCIG il servizio riconosce ancora il vecchio valore (motvazioneCig)
3. contrattiDisposizioniParticolari in documentazione senza articolazione ed il servizio la chiede con articolazione idTipologica - codice
4. etc. etc.

sarebbe auspicabile una volta per tutte capire se quando si è in presenza di un dominio è necessario usare la rappresentazione idTipologica - codice oppure no.

Non credo sia utile usare un meccanismo "misto" (come mi è stato risposto in una issue precedente) che complica la vita a chideve sviluppare.

Al momento l'unica strada che abbiamo è try & correct che non mi sembra la più efficiente.

**Comment by supportoAnac** [comment]
Superata da successivi rilasci.
