### ISSUE TITLE
[BLK] Avanzamento stato appalto

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#628]
@mpizziconi 
Siamo riusciti a creare un appalto con scheda P2_10.
Subito dopo abbiamo invocato consulta-appalto abbiamo ottenuto stato "IN_LAV".
Abbiamo invocato (piu volte) il conferma-appalto. Esito positivo, "Richiesta acquisita".
Ci aspettavamo di trovare l'appalto in stato "CONFERMATO", come da diagramma.
In realtà è fermo in questo stato IN_LAV (sono passati una 40 di minuti).
Verifica-appalto risponde anche con successo, "Richiesta acquisita".

idAppalto "93392c9c-5bef-467a-8ed3-087f2c358941"

Cosa sbagliamo?

**Comment by mpizziconi** [comment]
l'operazione esito-operazione dovrebbe restituire l'esito KO per l'operazione di conferma (chiedo riscontro sul fatto che il servizio sia correttamente interrogato e funzionante), con errore REG8: "Il campo deve essere una url valida e iniziare per http oppure per https."

il riferimento dovrebbe essere al campo anacForm.lotti.datiBaseDocumenti.url indicato come obbligatorio.

Si nota che anacForm.lotti.datiBaseDocumenti non è marcato come obbligatorio (l'eventuale refuso è in corso di verifica)

**Comment by pakozack** [comment]
La chiamata esito-operazione non da nessun errore.
Questa la get
https://apigw-test.anticorruzione.it/modi/rest/ServiziComuni/v2/stato-appalto?idAppalto=93392c9c-5bef-467a-8ed3-087f2c358941&tipoOperazione=AP_CONF&tipoRicerca=TUTTI_ESITI

Risposta

```json
{
  "status": 200,
  "title": "OK",
  "detail": "Operazione Effettuata",
  "type": "about:blank",
  "esitoStato": {
    "idAppalto": "93392c9c-5bef-467a-8ed3-087f2c358941",
    "stato": {
      "idTipologica": "statoAppalto",
      "codice": "IN_LAV"
    },
    "dataControllo": "2023-11-16T13:50:18.416+00:00"
  }
}
```

Nel modello dati il campo nacForm.lotti.datiBaseDocumenti non è obbligatorio. E' un errore di documentazione o di validatore?

**Comment by pakozack** [comment]
Perdonatemi c'era un errore sull'url dell'api esito-operazione.
Effettivamente esito-operazione ritorno un errore REG8 (Il campo deve essere una url valida e iniziare per http oppure per https).

```json
{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "93392c9c-5bef-467a-8ed3-087f2c358941",
      "idScheda": "1e4b9da1-4348-4f03-8b62-da6ac89e89fd",
      "esito": {
        "idTipologica": "esito",
        "codice": "KO"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AP_CONF"
      },
      "dataControllo": "2023-11-17T10:44:10.571+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AP_N_CONF"
      },
      "errori": [
        {
          "idTipologica": "errori",
          "dettaglio": "",
          "codice": "REG8"
        }
      ]
    }
  ]
}
```

Segnalo solo di correggere la documentazione. Grazie
