### ISSUE TITLE
[BLK] [CONSIP] Scheda S2 - Scheda non creata - Errore ERR9999

### ISSUE THREAD

**Issue by NicolaOrritos** [anticorruzione/npa#631]
Buongiorno,
Per l'appalto _"3616c27a-3d97-4bc4-8293-d8ebf77bbdc0"_, a seguito di una chiamata al crea-scheda inviando una scheda **S2**, otteniamo la seguente risposta:
```JSON
{
    "status": 400,
    "title": "KO",
    "detail": "SC_N_CRE",
    "type": "about:blank",
    "errori": [
        {
            "idTipologica": "errori",
            "codice": "ERR9999"
        }
    ]
}
```

La scheda inviata il 17/11 alle 09:18, con i dati sensibili oscurati tramite "*":
```JSON
{
   "idAppalto":"3616c27a-3d97-4bc4-8293-d8ebf77bbdc0",
   "scheda":{
      "codice":{
         "idTipologica":"codiceScheda",
         "codice":"S2"
      },
      "versione":"1.0",
      "body":{
         "anacForm": {
             "elencoSoggetti": [
                 {
                     "cig":"D********F",
                    "partecipanti":[
                    {
                        "codiceFiscale":"1*********7",
                        "denominazione":"A*******e",
                        "ruoloOE":{
                            "description":"Mandataria",
                            "idTipologica":"ruoloOE",
                            "codice":"1"
                        },
                        "tipoOE":{
                            "idTipologica":"tipoOE",
                            "codice":"1"
                        },
                        "idPartecipante":"1",
                        "idGruppo":1,
                        "paeseOperatoreEconomico":"Italia",
                        "avvalimento":false,
                        "tipologiaAvvalimento":{
                            "description":"Requisito",
                            "idTipologica":"tipologiaAvvalimento",
                            "codice":"1"
                        }
                    }
                    ],
                    "dataScadenzaPresentazioneOfferta":"2023-11-15T12:02:05Z"
                 }
             ]
         }
      }
   }
}
```

L'errore è bloccante, siamo fermi, impedisce di continuare le attività con **l'invio delle schede successive e con l'aggiudicazione dell'appalto.**

**Comment by mpizziconi** [comment]
l'errore riportato dal sistema è
 Cannot deserialize value of type `java.util.UUID` from String "1": UUID has to be represented by standard 36-char representation
at [Source: (String)"{"cig":"D00002302F","partecipanti":[{"tipologiaAvvalimento":{"codice":"1","description":"Requisito","idTipologica":"tipologiaAvvalimento"},"tipoOE":{"codice":"1","idTipologica":"tipoOE"},"paeseOperatoreEconomico":"Italia","avvalimento":false,"ruoloOE":{"codice":"1","description":"Mandataria","idTipologica":"ruoloOE"},"denominazione":"Accenture","codiceFiscale":"13454210157","idPartecipante":"1","idGruppo":1}],"dataScadenzaPresentazioneOfferta":"2023-11-15T12:02:05Z"}"; line: 1, column: 395] (through reference chain: it.anticorruzione.ms.pcp.pcpms.dto.estrattore.ElencoSoggettiType["partecipanti"]->java.util.ArrayList[0]->it.anticorruzione.ms.pcp.pcpms.dto.estrattore.PartecipanteType["idPartecipante"])


id partecipante viola le regole dello schema json, deve essere nel formato UUID

**Comment by NicolaOrritos** [comment]
Grazie mille per il supporto.
