### ISSUE TITLE
[CONSIP] S2 - scheda non creata - ERR9999

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#632]
dopo aver PUBBLICATO l'appalto 3616c27a-3d97-4bc4-8293-d8ebf77bbdc0 abbiamo provato a mandare la S2 ma otteniamo il seguente errore (N.B. l'appalto è stato creato dopo l'ultimo rilascio):
{
    "idAppalto": "3616c27a-3d97-4bc4-8293-d8ebf77bbdc0",
    "scheda": {
        "codice": {
            "idTipologica": "codiceScheda",
            "codice": "S2"
        },
        "versione": "1.0",
        "body": {
            "anacForm": {
                "elencoSoggetti": [
                    {
                        "cig": "D00002302F",
                        "partecipanti": [
                            {
                                "codiceFiscale": "13454210157",
                                "denominazione": "Accenture",
                                "ruoloOE": {
                                    "description": "Mandataria",
                                    "idTipologica": "ruoloOE",
                                    "codice": "1"
                                },
                                "tipoOE": {
                                    "idTipologica": "tipoOE",
                                    "codice": "1"
                                },
                                "idPartecipante": "1",
                                "paeseOperatoreEconomico": "Italia",
                                "avvalimento": false,
                                "tipologiaAvvalimento": {
                                    "description": "Requisito",
                                    "idTipologica": "tipologiaAvvalimento",
                                    "codice": "1"
                                }
                            }
                        ],
                        "dataScadenzaPresentazioneOfferta": "2023-11-15T12:02:05Z"
                    }
                ]
            }
        }
    }
}

**Comment by mpizziconi** [comment]
è la stessa issue di https://github.com/anticorruzione/npa/issues/632
