### ISSUE TITLE
[Toscana/Bolzano] Recupero 'codiceCentroDiCosto' in ambiente di esercizio

### ISSUE THREAD

**Issue by user6330** [anticorruzione/npa#636]
Vorremmo inserire **idCentroDiCosto** per tutti i centro di costo registrati sulla nostra piattaforma, PRIMA del rilascio in esercizio della PCP, per anticipare eventuali MISMATCH tra informazioni censite su ANAC rispetto alle nostre piattaforme (e viceversa).
 
1) Esiste una piattaforma/sito dove è possibile recuperare il 'codiceCentroDiCosto' delle varie stazioni appaltanti?
2) Se la 1 è no, sarà possibile invocare in ambiente di produzione il servizio AUSA '/getBy?codiceFiscale=xxxxxxxxxxx&codiceAusa=xxxxxxxxxx' anche prima del rilascio in esercizio della PCP?
3) Se la 2 è no, potete fornire VOI in privato gli idCentroDiCosto memorizzate sui vostri sistemi in base alle agli AUSA che condivideremo?
4) Se anche la 3 è no, gli enti pubblici possono ricavare in autonomia da questo link? https://dati.anticorruzione.it/opendata/dataset/centri-di-costo

**Comment by mpizziconi** [comment]
il servizio ausaMS verrà esposto a breve in ambiente di esercizio
