### ISSUE TITLE
Scheda S3 - invio scheda per ogni lotto

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#637]
Buongiorno,

Le schede S3 possono essere inviate più volte per aggiornare gli incaricati alla progettazione ma è possibile inviare schede S3 diverse per ogni lotto?

ad esempio: Se io ho 10 lotti aggiudicati, potrei inviare possibilmente anche 10 schede S3 diverse ognuna che riguarda un lotto diverso? in caso contrario, l'utente deve inviare una scheda S3 che riguarda tutti i lotti aggiudicati fino a quel momento che necessitano la comunicazione degli incaricati?

Grazie

**Comment by anac-uscp** [comment]
Lo scenario previsto è che si manda inizialmente una scheda unica S3 con l'elenco dei CIG. Su tale scheda per ogni CIG si indicano i soggetti. Successivamente è possibile inviare le modifiche inviando una scheda unica di modifica per tutti i lotti oppure una scheda S3 per ogni lotto, per comunicare le modifiche sul singolo lotto. 
La scheda S3 inviata non integra ma sostituisce le informazioni precedentemente trasmesse per il lotto interessato
