### ISSUE TITLE
[CONSIP] GRUPPO SCHEDE AD - errore 500 

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#638]
chiamando il servizio crea-appalto con la scheda AD5 otteniamo l'errore:

SERVICE EXCEPTION: 500 Internal Server Error: "{"status":500,"title":"KO","detail":"Errore Generico","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}"

l'errore si verifica con tutte le schede AD.

JSON
{
	"scheda": {
		"codice": {
			"idTipologica": "codiceScheda",
			"codice": "AD5"
		},
		"versione": "4",
		"body": {
			"anacForm": {
				"stazioniAppaltanti": [
					{
						"codiceFiscale": "053*******",
						"codiceAusa": "900********",
						"codiceCentroCosto": "f237c494-bae6-47e4-************",
						"saTitolare": false
					}
				],
				"appalto": {
					"codiceAppalto": "352574645",
					"codiceFiscaleSA": "05359681003",
					"denominazioneSA": "Consip"
				},
				"aggiudicazioni": [
					{
						"lotIdentifier": "123",
						"oggettoPrincipaleContratto": {
							"idTipologica": "oggettoPrincipaleContratto",
							"codice": "L"
						},
						"cup": "123",
						"partecipanti": [{
							"idPartecipante": "80415740580",
                                                        "codiceFiscale": "05359681002",
							"denominazione": "MEF",
							"importo": 150000
						}]
					}
				]
			}
		}
	}
}

**Comment by mpizziconi** [comment]
la specifica prevede 
idPartecipante di tipo  string ($uuid)
