### ISSUE TITLE
[CONSIP] P1.19 - ERR45

### ISSUE THREAD

**Issue by evalentip** [anticorruzione/npa#640]
chiamando il servizio PUBBLICA AVVISO con la scheda P.19 otteniamo l'errore ERR45:
SERVICE EXCEPTION: 400 Bad Request: "{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR45"}]}"
-- "avviso non ammesso in questa fase dell'appalto"
{
  "idAvviso":"bf92722d-99d0-439f-b4b5-a337121c1a08",
  "idAppalto":"a18411e8-b8f9-45ca-93ca-5e856dcd9509"
}

**Comment by supportoAnac** [comment]
Issue superata da rilasci successivi.
