### ISSUE TITLE
[Intercent-ER] Servizio pubblica-Avviso - Richiesta chiarimento su idNuovoAvviso a seguito di Rettifica-Avviso

### ISSUE THREAD

**Issue by AndreaClerici** [anticorruzione/npa#642]
Buongiorno,
avrei bisogno di un chiarimento riguardo l'utilizzo dell'idNuovoAvviso a seguito dell'esito positivo di una RettificaAvviso.

Nella descrizione di /rettifica-avviso è scritto "Con la successiva chiamata al servizio esito-operazione è possibile recuperare l'idAvviso di rettifica assegnato.".  Andando a vedere la response positiva di /esito-operazione si trova che viene restituito il seguente campo:

- idNuovoAvviso | string($uuid) | identificativo univoco del nuovo Avviso generato da ANAC a seguito delle operazioni di modifica-avviso e rettifica-avviso.

Le mie domande sono:

1. in caso di esito positivo dell'operazione di /rettifica-avviso, questo campo idNuovoAvviso è sempre valorizzato?
2. È corretto dire che, a seguito della valorizzazione di questo campo in caso di Rettifica, tutte le successive comunicazioni devono utilizzare questo nuovo idAvviso mentre il vecchio idAvviso usato in precedenza va dimenticato e mai più utilizzato? A puro titolo di esempio per successive comunicazioni cito il servizio /consulta-avviso che richiede l'invio obbligatorio dell'idAvviso.

Grazie

**Comment by supportoAnac** [comment]
Corretto. Il nuovo idAvviso si riferisce all'avviso rettificato e pertanto è quello in vigore.
