### ISSUE TITLE
[mf] - Informazioni su LoA

### ISSUE THREAD

**Issue by marcofa1985** [anticorruzione/npa#643]
Gentile supporto, 
è possibile conoscere per quali servizi sarà richiesto un accreditamento con LoA3 e per quali servirà invece il LoA4?
Grazie, un saluto

**Comment by mpizziconi** [comment]
Il livello LoA3 è adottato per tutti i servizi PCP. L'accesso ad alcuni documenti del FVOE può richiedere il livello 4 in adempimento alla normativa di settore. Al momento il livello 4 è richiesto esclusivamente per l'accesso o la richiesta di informative antimafia
