### ISSUE TITLE
Indagini di mercato - schede

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#644]
L'invio della scheda P7_1_3 per le procedure negoziate senza bando sottosoglia con un avviso relativo all’avvio dell’indagine di mercato deve essere fatto alla pubblicazione dell'indagine di mercato o dopo, cioè alla pubblicazione della negoziata?

Grazie

**Comment by anac-uscp** [comment]
L'invio della scheda P7_1_3 per le procedure negoziate senza bando sottosoglia con un avviso relativo all’avvio dell’indagine di mercato deve essere fatto alla pubblicazione dell'indagine di mercato
