### ISSUE TITLE
[ENHANCEMENT] Gestione API asincrone - idOperazione

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#645]
@mpizziconi 
Se possibile si potrebbe aggiungere un identificativo per le operazioni sottomesse con API asincrone.
Potrebbe ritornare molto utile per tenet traccia degli invii e effettuati e ricollegarli con gli esiti.
In sostanza sarebbe ottimo avere come risultato di queste api asincrone, tipo conferma-appalto, oltre ad idAppalto, anche un uuid che identifica l'operazione.
Nell'API esito-operazione, oltre ai dati attuali, si potrebbe riportare l'idOperazione, in modo da legare correttamente la richiesta con la risposta. 
Considerando l'ordine cronologico delle richieste adesso si fa lo stesso, ma lo vedo un po meno robusto e sicuro.

Grazie

**Comment by mpizziconi** [comment]
La richiesta può essere accolta, ma non pianificata prima del secondo trimestre 2024
