### ISSUE TITLE
RP e DRP - Utenti, servizi e ruoli

### ISSUE THREAD

**Issue by turchim** [anticorruzione/npa#646]
Salve,
in relazione al "documento specifiche servizi npa" [https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md]
Al paragrafo 4.4 Utenti e Ruoli si dice:

> Il ruolo RP ha accesso a tutti i servizi e in via esclusiva alle operazioni:
presa-carico
aggiungi-soggetto
elimina-soggetto
crea-piano
crea-appalto

Nella tabella al paragrafo 4.5 Ruoli e servizi si rappresenta che tutti i servizi di Pianificazione Appalto (oltre a quelli dell'elenco di cui sopra) sono accessibili al solo RP.

Quale delle due schematizzazioni è da considerarsi corretta?

Grazie

**Comment by supportoAnac** [comment]
Si conferma che al momento i servizi di Pianificazione Appalto possono essere utilizzati unicamente da RP.
