### ISSUE TITLE
Recupero esito-operazione - Richiesta chiarimenti

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#650]
Il recupero degli esiti di operazioni asincrone, potrebbe (per il nostro modo di vedere, dovrebbe) essere una attività di background eseguita dalla piattaforma, in maniera trasparente all'utente che ha invocato il servizio su pdnd.
Nel dettaglio, il rup che ad esempio, mediante la piattaforma di eprocurement, invia i dati a pdnd per mezzo dell'eservice comunica appalto, api conferma-appalto, non dovrebbe preoccuparsi di richiedere l'esito dell'operazione ne tantomeno sapere se si tratta di una operazione sincrona o asincrona. 
Detto ciò la piattaforma potrebbe (dovrebbe) automaticamente recuperare questi esiti. 
L'api esito-operazione però, prevede l'autenticazione dell'utente, in questo caso presumibilmente del RUP.
Non sono quindi consentite attività in background da parte della piattaforma, ne in questo scenario, ne tantomeno in altri.
E' corretta la nostra interpretazione?

**Comment by r-dm123** [comment]
# Si conferma l'interpretazione: Non è possibile eseguire l'attività in background

**Comment by mpizziconi** [comment]
Ad ulteriore chiarimento ed in parziale rettifica: è possibile eseguire attività in background ma esclusivamente nel corso di sessioni utente attive. Le azioni di sola consultazione possono essere eseguite senza attività esplicita dell'utente.
