### ISSUE TITLE
[BLK][TOSCANA/BOLZANO] Campo eForm in AD3

### ISSUE THREAD

**Issue by user6330** [anticorruzione/npa#653]
come nella issue #599

Se il **dataAggiudicazione** è obbligatorio e fa riferimento all'eforms (non presente per quella scheda), significa che va compilato a prescindere, mentre se eforms è presente allora verrà ereditato?
Oppure deve comunque essere compilato?

**Comment by supportoAnac** [comment]
In generale, le schede per cui sono presenti le eForm ereditano i dati delle eForm. 
Il campo **dataAggiudicazione** equivale al campo **BT1451** dell'eForm.
Quando una scheda non contiene la eform, vengono acquisiti i campi comuni , e il campo dataAggiudicazione assume il valore che nella eform è il BT1451. 
La descrizione del campo vuole fornire una indicazione di cosa ci aspettiamo di trovare al suo interno, e verrà migliorata nei prossimi rilasci.
