### ISSUE TITLE
Scheda S1/S2 - Indagine di mercato

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#664]
Non è chiaro alla chiusura della valutazione di una idm se debba essere inviata la S1 (considerando dunque l'indagine come la prima fase di una negoziata senza bando) oppure la S2

Posso avere indicazioni? grazie

**Comment by anac-uscp** [comment]
Deve essere inviata la scheda S1 “Elenco dei soggetti che hanno manifestato interesse nelle procedure a due fasi”
