### ISSUE TITLE
Scheda P6_2 - Appalto specifico AQ

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#666]
Non è chiaro se la P6_2 debba essere inviata anche alla pubblicazione dell'appalto specifico dell'AQ

Posso avere riscontro?

Grazie

**Comment by anac-uscp** [comment]
Per pubblicare un bando per aggiudicare/concludere un accordo quadro bisogna usare la scheda P1_16 (sopra soglia appalti settori ordinari) o P2_16 (sotto soglia appalti settori ordinari). 
L’aggiudicazione della procedura bandita con P1_16 o P2_16 viene comunicata tramite le schede A1_29 o A2_29
L’adesione di una stazione appaltante all’accordo quadro - che avviene in momento successivo all’aggiudicazione dell’accordo quadro - deve essere comunicata con la scheda AD_4 (se senza confronto competitivo) o con la scheda P6_2 (con confronto competitivo)
