### ISSUE TITLE
Scheda P6_2 - Pubblicazione AQ

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#667]
Alla pubblicazione dell'accordo quadro deve essere inviata la scheda P6_2. Nei dati base procedura della scheda è da indicare la tipologia procedura (ad esempio: aperta, negoziata, ecc).

è sufficiente inviare solo la P6_2 oppure a seconda della tipologia di gara occorre inviare alla pubblicazione anche la scheda specifica, quindi oltre P6_2 anche P1_16 o P2_16 ecc?

Grazie

**Comment by anac-uscp** [comment]
Per pubblicare un bando per aggiudicare/concludere un accordo quadro bisogna usare la scheda P1_16 (sopra soglia appalti settori ordinari) o P2_16 (sotto soglia appalti settori ordinari). 
L’aggiudicazione della procedura bandita con P1_16 o P2_16 viene comunicata tramite le schede A1_29 o A2_29
L’adesione di una stazione appaltante all’accordo quadro - che avviene in momento successivo all’aggiudicazione dell’accordo quadro - deve essere comunicata con la scheda AD_4 (se senza confronto competitivo) o con la scheda P6_2 (con confronto competitivo)
