### ISSUE TITLE
[CONSIP] p7_2 - appalto non confermato (ERR41 e ERR43)

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#669]
Non riusciamo più a creare e confermare un appalto per la scheda P7.2 
otteniamo l'errore seguente: 
errori":[{"idTipologica":"errori","dettaglio":"","codice":"ERR43"},{"idTipologica":"errori","dettaglio":"","codice":"ERR41"}]}]}

idAppalto: 088fd05e-84f0-4656-8f86-023aedeb87ce
JSON
{
   "scheda":{
      "_idScheda":"",
      "codice":{
         "idTipologica":"codiceScheda",
         "codice":"P7_2"
      },
      "versione":"1.0",
      "_dataCreazione":"2022-01-23T12:02:05Z",
      "body":{
         "anacForm":{
            "stazioniAppaltanti":[
               {
                  "codiceFiscale":"05359XXXXXX",
                  "codiceAusa":"9000XXXXX",
                  "codiceCentroCosto":"f237c494-bae6-47e4-8c32-XXXXXXXXXX",
                  "saTitolare":true
               }
            ],
            "appalto":{
               "codiceAppalto":"2esgess0dd2310",
               "cigAccordoQuadro":"1234567891",
               "linkDocumenti":"http://www.test.com",
               "categorieMerceologiche":[
                  {
                     "idTipologica":"categorieMerceologiche",
                     "codice":"999"
                  }
               ],
               "motivazioneCIG":{
                  "idTipologica":"motivazioneCIG",
                  "codice":"1"
               },
               "strumentiSvolgimentoProcedure":{
                  "idTipologica":"strumentiSvolgimentoProcedure",
                  "codice":"1"
               }
            },
            "lotti":[
               {
                  "servizioPubblicoLocale":true,
                  "lotIdentifier":"125458",
                  "categorieMerceologiche":[
                     {
                        "idTipologica":"categorieMerceologiche",
                        "codice":"999"
                     }
                  ],
                  "saNonSoggettaObblighi24Dicembre2015":true,
                  "iniziativeNonSoddisfacenti":false,
                  "codIstat":{
                     "idTipologica":"codIstat",
                     "codice":"015146"
                  },
                  "condizioniNegoziata":[{
                     "idTipologica":"condizioniNegoziata",
                     "codice":"1"
                  }],
                  "contrattiDisposizioniParticolari":{
                     "idTipologica":"contrattiDisposizioniParticolari",
                     "codice":"1"
                  },
                  "lavoroOAcquistoPrevistoInProgrammazione":false,
                  "ipotesiCollegamento":{
                     "motivoCollegamento":{
                        "idTipologica":"motivoCollegamento",
                        "codice":"1"
                     }
                  },
                  "opzioniRinnovi":false,
                  "afferenteInvestimentiPNRR":false,
                  "ripetizioniEConsegneComplementari":false,
                  "ccnl":"Non previsto",
                  "prestazioniComprese":{
                     "idTipologica":"prestazioniComprese",
                     "codice":"1"
                  },
                  "tipologiaLavoro":[{
                     "idTipologica":"tipologiaLavoro",
                     "codice":"6"
                  }],
                  "categoria":{
                     "idTipologica":"categoria",
                     "codice":"999"
                  },
                  "finanziamenti":[
                     {
                        "tipoFinanziamento":{
                           "idTipologica":"tipoFinanziamento",
                           "codice":"A"
                        },
                        "importo":120.000
                     }
                  ],
                  "tipoRealizzazione":{
                     "idTipologica":"tipoRealizzazione",
                     "codice":"1"
                  }
               }
            ]
         }
      }
   }
}

**Comment by mpizziconi** [comment]
idAppalto non è sufficiente a rintracciare l'operaizone nel log e fornire assistenza
si ribadisce la necessità di fornire "govway_message_id" o "govway_transaction_id"

**Comment by lauralu1993** [comment]
non esiste "govway_message_id" o "govway_transaction_id".
il servizio esito-operazione restituisce 200 ma non capiamo perche restituisce ERR43 e ERR41.

{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "e2beb438-13f5-4971-b033-ae8c60166de5",
      "idScheda": "a3584bcc-bd04-499b-b187-c676a22733f0",
      "esito": {
        "idTipologica": "esito",
        "codice": "KO"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AP_CONF"
      },
      "dataControllo": "2023-11-20T14:15:06.103+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AP_N_CONF"
      },
      "errori": [
        {
          "idTipologica": "errori",
          "dettaglio": "",
          "codice": "ERR43"
        },
        {
          "idTipologica": "errori",
          "dettaglio": "",
          "codice": "ERR41"
        }
      ]
    }
  ]
}

**Comment by lauralu1993** [comment]
@mpizziconi abbiamo rieseguito lo scenario per fornirvi id-message e id-transaction di tutte le operazioni. 
idAppalto = 8033adbe-569b-4d2f-ba9e-6ff457ede699
clientid= 01e2efc4-f2cd-40f4-bac1-05e7c6dcefba

CREA-APPALTO
GovWay-Message-ID:"060328da-bf58-43af-8eeb-9862ce810e69"
GovWay-Transaction-ID:"c671aa8e-8954-11ee-b4a0-0050568e08b3"

CONFERMA-APPALTO
 GovWay-Message-ID:"c8798b04-86b9-48b5-9ba0-0ac542958301"
 GovWay-Transaction-ID:"015b250f-8955-11ee-b4a0-0050568e08b3"

ESITO OPERAZIONE
 GovWay-Message-ID:"598506bf-c9e1-496e-9790-11935ad87701"
 GovWay-Transaction-ID:"2685000a-8955-11ee-b4a0-0050568e08b3"
