### ISSUE TITLE
Scheda A - Invio graduatoria o aggiudicatario (ad es. A1_29)

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#670]
Buongiorno,

con la scheda A deve essere inviata la graduatoria o solo l'aggiudicatario (1° in graduatoria)?

Grazie

**Comment by LucaMaggioni1** [comment]
Chiusa perchè dai campi aggiornati delle schede A si evince che vada inviata la graduatoria

**Comment by LucaMaggioni1** [comment]
Riapro perchè a seguito di discussione interna servirebbe una conferma da ANAC per dubbio interpretativo dato che molti campi (es posizione in graduatoria, se è aggiudicatario) facoltativi.

**Comment by anac-uscp** [comment]
Con la scheda di aggiudicazione (ad es. A1_29) si deve trasmettere tutta la graduatoria.
