### ISSUE TITLE
Scheda AD_4 - Campi non indicati come obbligatori ma richiesti al click su Richiedi CIG

### ISSUE THREAD

**Issue by evalentip** [anticorruzione/npa#671]
Creando un appalto con scheda AD_4, al click su "conferma Appalto" ricerviamo i seguenti errori:

idAppalto c8029fc4-88ca-49f5-a785-e68c741b2a77

{
    "result":

{         "exitCode": "400",         "text": "Servizio momentaneamente non disponibile"     }
,
    "payload": {
        "errori": [
           

{                 "dettaglio": "$.anacForm.aggiudicazioni[0].partecipanti[0].codiceFiscale: is missing but it is required",                 "codice": "ERR4",                 "idTipologica": "errori"             }
,
           

{                 "dettaglio": "$.anacForm.aggiudicazioni[0].partecipanti[0].denominazione: is missing but it is required",                 "codice": "ERR4",                 "idTipologica": "errori"             }
,
           

{                 "dettaglio": "$.anacForm.aggiudicazioni[0].partecipanti[0].paeseOperatoreEconomico: is missing but it is required",                 "codice": "ERR4",                 "idTipologica": "errori"             }
,
           

{                 "dettaglio": "$.anacForm.aggiudicazioni[0].partecipanti[0].ruoloOE: is missing but it is required",                 "codice": "ERR4",                 "idTipologica": "errori"             }
,
           

{                 "dettaglio": "$.anacForm.aggiudicazioni[0].partecipanti[0].tipoOE: is missing but it is required",                 "codice": "ERR4",                 "idTipologica": "errori"             }
        ],
        "detail": "Errore Validazione JSON Schema",
        "title": "KO",
        "type": "about:blank",
        "status": 400
    }
}
Facendo una verifica sullo swagger i campi risultano non obbligatori.

**Comment by mpizziconi** [comment]
idAppalto non è sufficiente a rintracciare l'operaizone nel log e fornire assistenza
si ribadisce la necessità di fornire "govway_message_id" o "govway_transaction_id"
