### ISSUE TITLE
[CONSIP]  Schede AD2_ 25 - Errore ERR9999 

### ISSUE THREAD

**Issue by evalentip** [anticorruzione/npa#672]
Creando qualsiasi tipo di negoziazione con qualsiasi tipo di scheda AD, al click su "Crea Appalto"  si riscontra errore generico ERR9999 

Payload:
{
   "scheda":{
      "codice":{
         "idTipologica":"codiceScheda",
         "codice":"AD2_25"
      },
      "versione":"1.0",
      "_dataCreazione":"2022-01-23T12:02:05Z",
      "body":{
         "anacForm":{
            "stazioniAppaltanti":[
               {
                  "codiceFiscale":"05******",
                  "codiceAusa":"90****",
                  "codiceCentroCosto":"f237c494-bae6-*********",
                  "saTitolare":true
               }
            ],
            "appalto":{
               "codiceAppalto":"261041",
               "motivoUrgenza":{
                  "idTipologica":"motivoUrgenza",
                  "codice":"1"
               },
               "relazioneUnicaSulleProcedure":false,
               "opereUrbanizzazioneScomputo":false
            },
            "aggiudicazioni":[
               {
                  "lotIdentifier":"LOT-0001",
                  "afferenteInvestimentiPNRR":false,
                  "partecipanti": 
                  [{"idPartecipante": "d0b6c12e-8789-11ee-b9d1-0242ac120002"}]
               }
            ]
         }
      }
   }
}

{
    "result":

{         "exitCode": "500",         "text": "Servizio momentaneamente non disponibile"     }
,
    "payload": {
        "errori": [
           

{                 "codice": "ERR9999",                 "idTipologica": "errori"             }
        ],
        "detail": "Errore Generico",
        "title": "KO",
        "type": "about:blank",
        "status": 500
    }
}

**Comment by mpizziconi** [comment]
idAppalto non è sufficiente a rintracciare l'operaizone nel log e fornire assistenza
si ribadisce la necessità di fornire "govway_message_id" o "govway_transaction_id"

**Comment by lauralu1993** [comment]
non abbiamo un  "govway_message_id" o "govway_transaction_id".
di seguito i dettagli di riferimento:
test.anticorruzione.it/modi/rest/ComunicaAppalto/v2",
  "sub": "01e2efc4-f2cd-40f4-bac1-05e7c6dcefba",
  "nbf": 1700489173,
  "digest": {
    "alg": "SHA256",
    "value": "87bd50dbc970be29e5102836c7ec19f81ed4dbca2e97bff6e0c699d4c44c5525"
  },
  "purposeId": "621838e3-e6de-43d2-bd88-1a0eb0f939d4",
  "iss": "uat.interop.pagopa.it",
  "exp": 1700492773,
  "iat": 1700489173,
  "client_id": "01e2efc4-f2cd-40f4-bac1-05e7c6dcefba",
  "jti": "61e2bfa1-d88e-43d3-8b23-e8a8450592d8"
}

STACK TRACE

org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error: "{"status":500,"title":"KO","detail":"Errore Generico","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}"
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:102)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:915)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:864)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:646)

**Comment by lauralu1993** [comment]
si aggiunge che per le schede del gruppo AD che presentano questo errore siamo riusciti ad aggirare il problema compilando i campi dell'oggetto aggiudicazioni.partecipanti sebbene fossero facoltativi.
Prevedete di fare alcune fix @mpizziconi ?
