### ISSUE TITLE
PDND e-Procurement - Processo di accreditamento agli eService

### ISSUE THREAD

**Issue by Alessandroava** [anticorruzione/npa#673]
Buongiorno, 
A seguito dell’iscrizione della piattaforma da parte di AgID nel Registro delle piattaforme certificate e la ricezione dei dati delle utenze di test assegnate da utilizzare per l’accesso via PDND agli eService della Piattaforma Contratti Pubblici si chiede quale è lo step successivo per l'accreditamento alla PDND tramite PagoPA. Va fatto un'adesione temporanea o questa viene formalizzata con la firma della convenzione solo una volta ottenuta la certificazione da AgID?

Grazie 

Alessandro Ava

**Comment by FedericaSicchiero** [comment]
Buon pomeriggio,
per quale ente volete fare l'adesione a PDND?
Perchè l'abilitazione all'adesione avviene solo a valle della richiesta di certificazione ad AgID e dell'iscrizione al registro dei gestori delle piattaforme di ANAC.
PDND riceve l'autorizzazione all'adesione delle imprese solo a conclusione, con successo, di questo processo.

A quanto avete detto il primo step di certificazione di AgID è avvenuto, quindi appena riceviamo da ANAC gli enti iscritti al registro dei gestori di piattaforma potrete proseguire con l'adesione formale seguendo gli step indicati nella [guida](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/guida-alladesione).

**Comment by Alessandroava** [comment]
Salve, abbiamo avuto esito positivo da parte di AgID alla verifica della check list e le utenze di test assegnate dautilizzare per l’accesso via PDND agli eService della Piattaforma ContrattiPubblici ma non è possibile procedere con l'adesione formale perchè l'ente non compare nell'anagrafica della piattaforma di selfcare onboarding gestita da PagoPA.
Mancano degli step?


    Il lunedì 20 novembre 2023 alle ore 14:50:28 CET, Federica Sicchiero ***@***.***> ha scritto:  
 
 


Buon pomeriggio,
per quale ente volete fare l'adesione a PDND?
Perchè l'abilitazione all'adesione avviene solo a valle della richiesta di certificazione ad AgID e dell'iscrizione al registro dei gestori delle piattaforme di ANAC.
PDND riceve l'autorizzazione all'adesione delle imprese solo a conclusione, con successo, di questo processo.

A quanto avete detto il primo step di certificazione di AgID è avvenuto, quindi appena riceviamo da ANAC gli enti iscritti al registro dei gestori di piattaforma potrete proseguire con l'adesione formale seguendo gli step indicati nella guida.

**Comment by FedericaSicchiero** [comment]
No non manca nessun passaggio, come dicevo sopra appena riceviamo da ANAC la lista aggiornata degli gli enti iscritti al registro dei gestori di piattaforma aggiungeremo il vostro ente e potrete proseguire con l'adesione formale seguendo gli step indicati nella [guida](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/guida-alladesione).
