### ISSUE TITLE
[BLK] Struttura JSON ConsultaAvvisoResponse non conforme a specifica di interfaccia specifiche-servizi-appalto.yaml

### ISSUE THREAD

**Issue by davideorsi-bit** [anticorruzione/npa#675]
Buonasera,
nel chiamare il servizio consulta-avviso:
https://api.integrazione.lispa.it/c/pdndbasic/PCPpubblicaAvviso/fruizione/v1.0.0/consulta-avviso?idAvviso=026d8c62-0dda-4301-950d-05ddb39454c6

ottengo la seguente risposta:
{
	"instance": null,
	"status": 200,
	"title": "OK",
	"detail": "Operazione Effettuata",
	"type": "about:blank",
	"avviso": {
		"idAvviso": "026d8c62-0dda-4301-950d-05ddb39454c6",	"idAppalto": "ceda010b-7f8c-47c8-8695-eeada9293e41",
		"idPianificazione": null,	"dataCreazione": "2023-11-20T14:19:16.941+00:00",	"dataPubblicazione": null,
		"stato": {	"idTipologica": "statoAvviso",	"codice": "CREATO"	},
		"dataControllo": "2023-11-20T14:19:16.941+00:00",
		"azione": {	"idTipologica": "tipoAzioneAvviso","codice": "AZ_PUBB"},
		"datiPubblicazioneEU": null,
		"datiPubblicazioneIT": {	"tipo": {	"idTipologica": "tipoAvviso",	"codice": "IT"	},
			"stato": {	"idTipologica": "statoAvviso",	"codice": "CREATO"	},
			"dataControllo": "2023-11-20T14:19:16.941+00:00",	"dataInoltroPubblicazione": null,"dataPubblicazione": null
		}
	},
	"scheda": { "_idScheda": "6c52c3ea-21f9-4d6d-9fa7-c5a8c6e735d3",
		"stato": {	"idTipologica": "statoScheda","codice": "CONF"},
		"codice": {	"idTipologica": "codiceScheda",	"codice": "AD2_25"},
		"versione": "1.0",
		"dataCreazione": "2023-11-20T14:19:16.147+00:00",
		"body": {
			"type": "SchedaAD225Type",
			"anacForm": {
				"stazioniAppaltanti": [
					{
						"codiceFiscale": "05017630152",
						"codiceAusa": "9000000010",
						"codiceCentroCosto": "f481feb8-2d8f-46be-bb14-a950234559d6",
						"funzioniSvolte": [
							{
								"idTipologica": "funzioniSvolte",
								"codice": "1"
							}
						],
						"saTitolare": true
					}
				],
				"appalto": {
					"codiceAppalto": "326354FHGF_AD225",
					"motivoUrgenza": {
						"idTipologica": "motivoUrgenza",
						"codice": "7"
					},
					"linkDocumenti": "https://www.google.com/",
					"relazioneUnicaSulleProcedure": false,
					"opereUrbanizzazioneScomputo": false,
					"datiBaseProcedura": {
						"tipoProcedura": {
							"idTipologica": "tipoProcedura",
							"codice": "neg-w-call"
						}
					},
					"datiBaseStrumentiProcedura": {
						"accordoQuadro": {
							"idTipologica": "accordoQuadro",
							"codice": "none"
						},
						"sistemaDinamicoAcquisizione": {
							"idTipologica": "sistemaDinamicoAcquisizione",
							"codice": "none"
						}
					},
					"datiBaseSubappalti": {
						"subappalto": {
							"idTipologica": "subappalto",
							"codice": "no"
						}
					}
				},
				"aggiudicazioni": [
					{
						"lotIdentifier": "LOTTO_111",
						"afferenteInvestimentiPNRR": true,
						"oggettoPrincipaleContratto": {
							"idTipologica": "oggettoPrincipaleContratto",
							"codice": "F"
						},
						"quadroEconomicoStandard": {
							"impForniture": 1.0E7,
							"sommeADisposizione": 1100000.0
						},
						"quadroEconomicoConcessioni": {
							"impServizi": 900000.0
						},
						"partecipanti": [
							{
								"codiceFiscale": "RSODVD73H01D600F",
								"denominazione": "Dave Bears",
								"ruoloOE": {
									"idTipologica": "ruoloOE",
									"codice": "1"
								},
								"tipoOE": {
									"idTipologica": "tipoOE",
									"codice": "1"
								},
								"idPartecipante": "433bfd5e-8785-11ee-b9d1-0242ac120002",
								"paeseOperatoreEconomico": "Italia",
								"avvalimento": false
							}
						]
					}
				]
			}
		}
	},
	"appalto": {
		"idAppalto": "ceda010b-7f8c-47c8-8695-eeada9293e41",
		"codiceAppalto": "326354FHGF_AD225",
		"oggetto": "",
		"dataCreazione": "2023-11-20T14:19:16.138+00:00",
		"dataModifica": "2023-11-20T14:19:17.012+00:00",
		"stato": {
			"idTipologica": "statoAppalto",
			"codice": "CONF"
		}
	},
	"piano": null
}

La struttura del JSON restituito non rispetta quanto descritto nel json di specifica di interfaccia "specifiche-servizi-appalto.yaml" , in quanto sia l'oggetto scheda che appalto a livello di root invece di essere dentro l'oggetto avviso.

Grazie

**Comment by mpizziconi** [comment]
l'end point raggiunto è deprecato, è necessario aggiornare la fruizione alla versione 2 dei servizi
