### ISSUE TITLE
DRP fase di affidamento ed esecuzione - servizio Ricerca-Appalto

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#678]
Buongiorno,

a seguito del rilascio del 13/11/2023 in cui sono stati specificati i servizi che possono richiamare i vari responsabili di fase, risulta che il DRP della fase di affidamento e di esecuzione non possono invocare il servizio di ricerca appalto, è corretto?

Non è chiaro il motivo per cui la ricerca di un appalto non dovrebbe essere invocabile da dei responsabili di fasi successive.

Grazie

**Comment by sfala** [comment]
A seguito della differenziazione dei ruoli DRP con il rilascio del 13/11/2023, da quando non esiste più un unico DRP per tutte le fasi ma uno specifico per ogni fase, un DRP di fasi diverse dalla pubblicazione non è più autorizzato a invocare i servizi ricercaAppalto e consultaAppalto che infatti non sono utilizzabili.
Poiché questa modifica comporta la ri-progettazione di una parte degli applicativi già sviluppati, al di là dell'assenza di contingenza per intervenire, vorremmo sapere se è possiile autorizzare all’uso dei servizi in questione anche gli utenti con ruoli DRP2 e DRP3 oltre che DRP1. 
Preciso che gradiremmo una risposta definitiva per quanto, se negativa, avrebbe per noi delle implicazioni significative in quanto dovremmo rifare parte degli applicativi.
@mpizziconi
