### ISSUE TITLE
Scheda Negoziata senza bando sotto soglia (P7_2)

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#684]
Per la pubblicazione di una Negoziata senza bando sotto soglia non "collegata" a un'indagine di mercata è sempre da inviare la scheda P7_2?

Oppure può essere inviata la P2_16 con valorizzazione del valore "Negoziata senza previa indizione di gara" nel campo tipoProcedura? In questo caso qual è la discriminante tra la scelta di P7_2 o P2_16?

Grazie

**Comment by UserM21** [comment]
Ciao, a me hanno risposto così #473 
quindi deduco che escluse queste casistiche la negoziata senza bando vada con la P2_16
