### ISSUE TITLE
Scheda P6_2 - Pubblicazione AQ

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#685]
Alla pubblicazione di un accordo quadro è sempre da inviare la scheda P6_2?

Noi gestiamo gli accordi quadro multifornitore e i relativi appalti specifici. Alla conclusione della procedura di AQ, quindi, è possibile pubblicare un appalto specifico derivante da un precedente AQ.
In particolare non mi è chiaro se e per quale tipologia occorre utilizzare la scheda P6_2 (Adesione AQ/convenzione con successivo confronto competitivo (ordinario/speciale).per la pubblicazione.
Da quanto ho ricostruito, per la pubblicazione dell’AQ occorre utilizzare le schede P1_16 (indicando “Accordo Quadro” nel campo strumentiSvolgimentoProcedure) oppure P2_16 (indicando “Accordo Quadro” nel campo accordoQuadro). È corretta tale ricostruzione?
Poi, per la pubblicazione dell’appalto specifico occorre utilizzare la scheda P6_2, indicando il CIG del precedente AQ nel campo cigAccordoQuadro. È corretta tale ricostruzione oppure occorre utilizzare anche qui P1_16 oppure P2_16?

**Comment by anac-uscp** [comment]
Per pubblicare un bando per aggiudicare/concludere un accordo quadro bisogna usare la scheda P1_16 (sopra soglia appalti settori ordinari) o P2_16 (sotto soglia appalti settori ordinari). 
L’aggiudicazione della procedura bandita con P1_16 o P2_16 viene comunicata tramite le schede A1_29 o A2_29
L’adesione con successivo confronto competitivo di una stazione appaltante all’accordo quadro deve essere comunicata la scheda P6_2 indicando il CIG del precedente AQ nel campo cigAccordoQuadro.
