### ISSUE TITLE
[BLK] [Toscana/Bolzano] Lista codici Ausa Centri di Costo

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#686]
Buongiorno,
sulla base della risposta alla issue https://github.com/anticorruzione/npa/issues/636 pongo i seguenti quesiti:

1) La versione che rilascerete conterrà i dati di produzione? Questo al fine di valutare di prepolare le piattaforme di eproc in vista del go live

2) Per richiamare il servizio è necessario autenticarsi con SPID come RP? Oppure lo si può invocare autonomamente per garantire il corretto censimento dei CdC?

3) Quando rilascerete in esercizio?

4) Una volta andati live, al fine di creare un CdC dentro una SA sarà necessario disporre del codice Ausa del Cdc. Dato che la registrazione richiede tale informazione, gli enti dove potranno recupare liberamente tali codici?

**Comment by mpizziconi** [comment]
1 il servizio di esercizio espone i dati di esercizio
2 il servizio è esposto su PDND in fruizione pubblica
3 la data non è stata ancora pianificata
4 la gestione dei centri di costo delle SA è competenza del sistema AUSA di ANAC, il servizio ausaMs è di sola consultazione
