### ISSUE TITLE
Scheda P2_16 - Obbligatorietà attributo "tipologiaLavoro"

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#687]
Buongiorno,
nella scheda P2_16 l'attributo "tipologiaLavoro" è obbligatorio anche per appalti di forniture e servizi.
Nella tipologica [tipologiaLavoro](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/tipologiche/tipologiaLavoro.json) vediamo valori applicabili ai soli appalti di lavori.

L'attributo è obbligatorio: procediamo inserendo un valore casuale, ma credo vada gestito diversamente, corretto?

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 24/11/2023.
