### ISSUE TITLE
[Maggioli] OfferteType - Valore da inserire in OffertaQualitativa

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#689]
Buongiorno,
non ci è chiaro quale valore inserire nell'attributo OffertaQualitativa (vedi immagine sotto).

Va inserito il punteggio totale in caso di procedura OEPV?

Oppure solo il punteggio qualitativo? In tal caso quello quantitativo non è previsto?

![image](https://github.com/anticorruzione/npa/assets/88787715/8625d2cd-07b0-46a2-966a-99c6bfb6a19b)

**Comment by anac-uscp** [comment]
<p>Confermiamo che, allo stato attuale, nell’attributo “OffertaQualitativa” va inserito solamente il punteggio dell’offerta qualitativa, mentre nell’offerta economica va inserito il ribasso percentuale.</p>
