### ISSUE TITLE
JWS - Campo businessFlowID (servizi crea-appalto)

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#690]
Nella definizione del JWS [link]( https://raw.githubusercontent.com/anticorruzione/npa/main/docs/specifiche-jws/jws.yaml)
viene specificato il campo businessFlowID con la descrizione `coincide con idAppalto. Assume valore "00000000-0000-0000-0000-000000000000" nella prima transazione (che è necessariamente comunicaAppalto.crea-appalto) In tutte le operazioni successive riconduce la transazione all’appalto`

Attualmente noi non stiamo compilando questo campo con il codiceAppalto, ma è sempre come l'example `00000000-0000-0000-0000-000000000000`.

Il campo non viene usato? Possiamo continuare a non inserirlo anche in ambiente di prod?

**Comment by supportoAnac** [comment]
Si conferma che come da specifiche JWS è necessario valorizzare il campo con la idAppalto.
