### ISSUE TITLE
DMN Rules - campi mancanti ed errori

### ISSUE THREAD

**Issue by vtkachenko00** [anticorruzione/npa#691]
Sarebbe utile correrreggere alcuni errori in modo da poter utilizzare i messaggi di errore.

Ci sono alcuni errori nell'outputEntry nei seguenti casi:

| File | Id regola | Versione sbagliata | Versione corretta |
|-----------|-----------|-----------|-----------|
| A1_32.dmn    | DecisionRule_166ze3s | `<text>{\"idTipologica\":\"errori\",\"codice\":\"REG47\"}"</text>` |  `<text>"{\"idTipologica\":\"errori\",\"codice\":\"REG47\"}"</text>`  |
| A1_35.dmn    | DecisionRule_166ze3s | `<text>{\"idTipologica\":\"errori\",\"codice\":\"REG47\"}"</text>`| `<text>"{\"idTipologica\":\"errori\",\"codice\":\"REG47\"}"</text>` |
| A2_32.dmn    | DecisionRule_166ze3s | `<text>{\"idTipologica\":\"errori\",\"codice\":\"REG47\"}"</text>`| `<text>"{\"idTipologica\":\"errori\",\"codice\":\"REG47\"}"</text>`|
| A2_35.dmn    | DecisionRule_166ze3s | `<text>{\"idTipologica\":\"errori\",\"codice\":\"REG47\"}"</text>`| `<text>"{\"idTipologica\":\"errori\",\"codice\":\"REG47\"}"</text>`|
| P1_12.dmn    | DecisionRule_P1_12_0018 | `<text>"{\"idTipologica\":\"errori\",\"codice\":{\"REG1\"}}"</text>`| `<text>"{\"idTipologica\":\"errori\",\"codice\":\"REG1\"}"</text>`|
| P2_12.dmn    | DecisionRule_P1_12_0018 | `<text>"{\"idTipologica\":\"errori\",\"codice\":{\"REG1\"}}"</text>`| `<text>"{\"idTipologica\":\"errori\",\"codice\":\"REG1\"}"</text>`|
| P3_3.dmn    | DecisionRule_P3_3_0037 | `<text>"{\"idTipologica\":\"errori\",\"codice\":\"REG66"}"</text>`| `<text>"{\"idTipologica\":\"errori\",\"codice\":\"REG66\"}"</text>`|

Inoltre, nei seguenti file, la prima regola non include una descrizione dell'errore:

+ A1_37.dmn
+ A2_36.dmn
+ A2_33.dmn
+ A2_31.dmn
+ A4_3.dmn
+ A4_2.dmn
+ A3_1.dmn
+ A2_29.dmn
+ A2_35.dmn
+ A3_2.dmn
+ A3_5.dmn
+ A4_1.dmn
+ A2_30.dmn
+ A4_4.dmn
+ A4_6.dmn
+ A1_29.dmn
+ A1_33.dmn
+ A1_34.dmn
+ A2_37.dmn
+ S1.dmn
+ S2.dmn
+ A1_35.dmn
+ A1_30.dmn
+ A3_4.dmn
+ A2_34.dmn
+ A1_31.dmn
+ A2_32.dmn
+ A4_5.dmn
+ A7_1_1.dmn
+ A7_1_2.dmn
+ A3_3.dmn
+ A1_36.dmn
+ A1_32.dmn

Sarebbe necessario integrare la descrizione dell'errore nella prima regola di questi file.

**Comment by supportoAnac** [comment]
In corso di verifica dopo il rilascio 24/11/2024 e successivi.
