### ISSUE TITLE
scheda NAG - flussi di appartenenza

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#692]
Buongiorno,

visionando la colonna "Flusso Appartenenza" per la scheda NAG risulta inserito il flusso 71 e 73. il flusso 71 non trova riscontro con altre schede e il flusso 73 riguarda la costituzione di un elenco fornitori. 

Sono corretti questi riferimenti come flusso di appartenenza nella scheda NAG? 

inoltre, nella scheda NAG, come flusso di appartenenza non dovrebbe rientrare anche il flusso 713 che riguarda le negoziate senza bando sottosoglia tramite indagine di mercato?

Grazie

**Comment by LucaMaggioni1** [comment]
è possibile avere un riscontro?

**Comment by anac-uscp** [comment]
<p>Come si evince dall’orchestratore,  il problema è stato superato inserendo i corretti flussi delle schede P7_x </p>
