### ISSUE TITLE
Scheda P7 - Indagini di mercato  (ad es. P7_1_1)

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#693]
Buongiorno,

Dal file Orchestratore risulta che per le schede P7 che scaturiscono da indagini di mercato non si debba inviare ESPD. dato che dopo l'invio di queste schede si procede con l'invio delle S e poi dell'aggiudicazione, dove va previsto l'ESPD per i requisiti?

dato che l'ESPD è richiesto per verificare i requisiti anche per le schede AD di affidamento diretto non dovrebbe essere previsto anche per le negoziate senza bando tramite indagine di mercato?

Grazie

**Comment by LucaMaggioni1** [comment]
è possibile avere un riscontro?

**Comment by anac-uscp** [comment]
<p>Secondo i flussi delle P7_1_x l’ESPD attualmente non è prevista. Sarà prevista in un prossimo changelog.</p>
