### ISSUE TITLE
Scheda A1_30 - Segnalazione non obbligatorietà campi  linkdocumenti e aggiudicatario non coerente 

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#694]
Segnaliamo che le indicazioni fornite nel file yaml dedicato sull’obbligatorietà dei campi linkdocumenti e aggiudicatario della scheda A1_30 non sono coerenti con quanto descritto. I campi sono indicati come non obbligatori in realtà se non valorizzati la creazione della scheda non va a buon fine.

**Comment by supportoAnac** [comment]
Verrà aggiornato al primo rilascio utile, che non avverrà prima dell’esercizio della piattaforma.
