### ISSUE TITLE
[BLK] Scheda P7_2 - ERR43 e ERR41 al conferma

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#695]
Non riusciamo a confermare la scheda P7_2 poiché ci vengono restituiti gli errori ERR41 "errore generico durante la validazione dei dati della scheda" e ERR43 "errore durante la validazione dei dati della scheda: tabella DMN non trovata".

idAppalto: 93b888f0-2740-4db5-8322-974a946f204d

dati della chiamata conferma-appalto:

govway-transaction-id:cd0fcb3a-888b-11ee-b4a0-0050568e08b3
govway-message-id:7b6116ef-0809-4946-b9e4-bdf9c3ee4607

**Comment by mariottiDPA** [comment]
stesso errore sulla P7_1_1

idAppalto: 93734f87-99d2-4366-b0a4-af7291280c16

govway-transaction-id:8f6daa29-8928-11ee-a061-0050568e9679
govway-message-id:f63d8a0f-5418-4734-8118-521d3ce4b942

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 24/11/2023.
