### ISSUE TITLE
[BLK] Scheda SC1 a seguito di AD3 - ERR2 al crea-scheda

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#697]
A seguito della creazione e conferma di una AD3, in stato-appalto PUBB, proviamo a creare la successiva SC1, come da orchestratore. Al crea-scheda ci viene però restituito ERR2 "scheda non ammessa in questa fase dell'appalto".

idAppalto: a1804369-3f49-419f-b7cb-8b74cfeccf84
CIG: U00001FAE6

govway-transaction-id:f7abb504-8923-11ee-a061-0050568e9679
govway-message-id:d9981286-83fb-400d-baf6-c363621e7f71

**Comment by mladuDPA** [comment]
Allego il payload richiesto

```json
{
	"idAppalto": "9a5656d4-617a-429c-898f-6b41170ce45a",
	"scheda": {
		"codice": {
			"idTipologica": "codiceScheda",
			"codice": "SC1"
		},
		"versione": "1.0",
		"body": {
			"anacForm": {
				"datiContratto": {
					"codiceAusa": [
						"9000000001"
					],
					"idPartecipante": "77b27462-f84a-4810-876d-9e34bcc0ece1",
					"cig": [
						"O00002AF05"
					],
					"dataDecorrenza": "2023-11-23T09:11:00+00:00",
					"dataScadenza": "2024-11-24T00:00:00+00:00",
					"importoCauzione": 1111.0
				}
			}
		}
	}
}
```

**Comment by supportoAnac** [comment]
Come indicato nel GdL del 01/12/2023, con ogni probabilità è  avvenuta una modifica del modello dati a ridosso delle chiamate, che sono state effettuate nel giorno del rilascio. Si chiede gentilmente di effettuare un nuovo tentativo inviando di nuovo AD3.
