### ISSUE TITLE
[BLK] P4_1 verifica-appalto e conferma-appalto errore 400 con ERR9999

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#698]
Dopo aver creato una P4_1, il verifica-appalto e il conferma-appalto restituiscono un 400 con ERR9999.

idAppalto: 5ee6ae33-468d-4ec5-b318-ec47a809b4d2

govway-transaction-id:07862bfb-8926-11ee-a061-0050568e9679
govway-message-id:52b22320-d1f7-4274-b552-bfed94762d3c

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 24/11/2023.
