### ISSUE TITLE
Pubblicazione effettiva dell'appalto

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#7]
Si chiede conferma dell’asincronicità del servizio pubblica-avviso in quanto impatta direttamente sul processo di pubblicazione dell’appalto. Quindi occorre necessariamente aspettare il feedback del pubblica-avviso per considerare un appalto “pubblicato”?

**Comment by supportoAnac** [comment]
La data di decorrenza di una pubblicazione è stabilita dalla normativa.
