### ISSUE TITLE
[BLK] Gestione tracciati nuovi tracciati dati_Numero gara ANAC

### ISSUE THREAD

**Issue by federicodemarco** [anticorruzione/npa#704]
Buongiorno,
in relazione ai tracciati di SIMOG (3.04.xx), l'attuale Numero gara ANAC (progressivo) ha consentito di poter gestire il passaggio da un tracciato all'altro garantendo anche la gestione dei cig staccati con i vecchi tracciati. Ogni tracciato simog aveva associato l'ultimo numero gara anac staccato per quel tracciato stesso.

 Per tutti i CIG staccati a partire dal 01/01/2024,  il numero gara ANAC è stato sostanzialmente sostituito con l'ID Appalto.  Essendo questo ultimo non un progressivo ma un codice alfanumerico,  potete indicarci un codice progressivo che ci consenta di gestire i cambiamenti dei tracciati/versione dello schema dati. Qualora riteniate che non sia necessario gestire i tracciati nelle differenti versioni, potete indicarci le logiche alla base di tale impostazione e il metodo con il quale intendete gestire CIG di tracciati obsoleti?

**Comment by r-dm123** [comment]
#L’identificativo dell’appalto viene attribuito dalla piattaforma nel campo “appalto.codiceAppalto"
