### ISSUE TITLE
Credenziali di accesso PCP per TEST (ESTAR Toscana) 

### ISSUE THREAD

**Issue by francesantu** [anticorruzione/npa#707]
Buongiorno,
non abbiamo ricevuto le credenziali di accesso per piattaforma START SANITA' (Gestore ESTAR).
La domanda di certificazione è stata trasmessa ed accolta ma le credenziali non sono mai pervenute. Informalmente ci è stato indicato di utilizzare le stesse credenziali dell'altra piattaforma di Regione Toscana (START) ma segnaliamo che sono due piattaforme totalmente diverse, con Gestori diversi.

Come possiamo ricevere credenziali come ESTAR ?

**Comment by r-dm123** [comment]
# la problematica è stata risolta
