### ISSUE TITLE
[ESTAR Toscana] Schede per convenzioni / AQ - Affidamento Diretto (ad es. AD1_25)

### ISSUE THREAD

**Issue by francesantu** [anticorruzione/npa#708]
Buongiorno,
non ci è chiaro quali schede devono essere inviate in PCP per gli affidamenti diretti che però sfociano in contratti di tipo accordo quadro / Convenzione (e che pertanto hanno necessità di acquisizione di relativi CIG Madre e CIG Derivati).

**Comment by anac-uscp** [comment]
<p>Per comunicare un affidamento diretto di tipo Accordo Quadro/Convenzione ed acquisire il CIG Madre, è necessario utilizzare le schede appropriate di affidamento diretto (AD1, AD2, AD3) e valorizzare il campo AQ.</p>

<p>Nelle schede AD1 e AD2 il campo è già presente. Nella scheda AD3 il campo sarà inserito a breve.</p>

<p>Per l'acquisizione dei CIG derivati, dei contratti operativi senza successivo confronto competitivo, dovranno essere inviate una o più schede AD4 'Adesione ad accordo quadro/convenzione senza successivo confronto competitivo' indicando il CIG Madre nell'apposito campo</p>
