### ISSUE TITLE
Scheda S3 - Aggiornamento struttura

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#712]
Nella scheda S3, relativamente alle informazioni della persona giuridica, è ancora presente il campo idGruppo mentre non è presente il campo idPartecipante.
Per coerenza con il modello dati modificato dal 13-11-2023 la struttura andrebbe aggiornata.

![image](https://github.com/anticorruzione/npa/assets/137269683/40fec66c-275e-4cbe-a961-3892547becb4)
Inoltre non è chiara la motivazione della cardinalità 0..n dell'attributo datiPersonaGiuridica (anche perchè il precedente "analogo" attributo (datiPersonaFisica) ha cardinalità 0..1

**Comment by supportoAnac** [comment]
Verrà aggiornato al primo rilascio utile, che non avverrà prima dell’esercizio della piattaforma.
