### ISSUE TITLE
[BLK] Schede AD2_25 e AD2_26 - Contesto d'uso

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#713]
Salve,
AD2_25 --> fase  "Affidamento", evento "Affidamento diretto" per  appalti sotto soglia settori ordinari regime ordinario e alleggerito
AD2_26 --> fase  "Affidamento", evento "Affidamento diretto" per appalti sotto soglia settori speciali regime ordinario e alleggerito
 
**MA**
in base alla normativa indicata nell'orchestratore Articolo 50 comma 1 lettere c) d) e)  decreto legislativo 36/2023
Articolo 50 comma 9 decreto legislativo 36/2023
 
queste due schede dovrebbero essere per :

c) **procedura negoziata senza bando,** previa consultazione di almeno cinque operatori economici, ove esistenti, individuati in base a indagini di mercato o tramite elenchi di operatori economici, per i lavori di importo pari o superiore a 150.000 euro e inferiore a 1 milione di euro;
d) **procedura negoziata senza bando,** previa consultazione di almeno dieci operatori economici, ove esistenti, individuati in base a indagini di mercato o tramite elenchi di operatori economici, per lavori di importo pari o superiore a 1 milione di euro e fino alle soglie di cui all’articolo 14, salva la possibilità di ricorrere alle procedure di scelta del contraente di cui alla Parte IV del presente Libro;
e) **procedura negoziata senza bando,** previa consultazione di almeno cinque operatori economici, ove esistenti, individuati in base ad indagini di mercato o tramite elenchi di operatori economici, per l'affidamento di servizi e forniture, ivi compresi i servizi di ingegneria e architettura e l'attività di progettazione, di importo pari o superiore a 140.000 euro e fino alle soglie di cui all’articolo 14.

Qual è il contesto d'uso per queste schede?

**Comment by anac-uscp** [comment]
No, queste schede vanno usate quando la stazione appaltante, invece di usare una procedura negoziata ex art. 50 comma 1 lett. c), d), e), procede, in via eccezionale, ad un affidamento diretto in quella fascia di importo (ossia pari o superiore al limite massimo ammesso per l’affidamento diretto e inferiore alla soglia comunitaria).
Le procedure negoziate sottosoglia vanno comunicate con le schede P7.1.3 o P.7.2, a seconda del caso.

**Comment by anac-uscp** [comment]
> No, queste schede vanno usate quando la stazione appaltante, invece di usare una procedura negoziata ex art. 50 comma 1 lett. c), d), e), procede, in via eccezionale, ad un affidamento diretto in quella fascia di importo (ossia pari o superiore al limite massimo ammesso per l’affidamento diretto e inferiore alla soglia comunitaria). Le procedure negoziate sottosoglia vanno comunicate con le schede P7.1.3 o P.7.2, a seconda del caso.
**RETTIFICA ALLA SUDDETTA RISPOSTA DEL 29/11/2023**
Le schede AD2_25/26/27/28 vanno usate quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e  b) - e non intende pubblicare un avviso per la trasparenza volontaria ex ante.

**Comment by anac-uscp** [comment]
RETTIFICA ALLA SUDDETTA RISPOSTA DEL 29/11/2023
Le schede AD2_25/26/27/28 vanno usate quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e b) - e non intende pubblicare un avviso per la trasparenza volontaria ex ante.
