### ISSUE TITLE
[BLK] Schede AD1_25 e AD1_26 - Contesto d'uso e soglie

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#714]
Salve, 

AD1_25 --> appalti settori ordinari pari /sopra soglia, fase "Affidamento" evento "affidamento diretto"  
AD1_26 --> appalti settori speciali pari /sopra soglia fase "Affidamento" evento "affidamento diretto" 

quali sono le soglie da rispettare dato che:

- **per lavori =** Importi fino a 150.000 Euro: affidamenti diretti
- **per Servizi e forniture =** Importi fino a 140.000 Euro: affidamenti diretti

**e la normativa indiche che da > 140/150 si parla di negoziate senza bando?**

Qual è il contesto d'uso?

**Comment by anac-uscp** [comment]
Le schede AD1_25/26/27/28 vanno usate quando la stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore soglia comunitaria.
Le schede AD2_25/26/27/28 vanno usate quando la stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite massimo ammesso per l’affidamento diretto e inferiore alla soglia comunitaria (quindi nei casi in cui, secondo l’art 50 comma 1 lett. c), d), e), bisognerebbe usare la procedura negoziata sottosoglia).
La scheda AD_3 vanno usate quando la stazione appaltante procede ad un affidamento diretto di importo superiore a 5000 euro e inferiore ai valori ammessi per l’affidamento diretto ex art 50 comma 1 lett. a), b). 
Per le procedure negoziate senza bando sottosoglia ex art. 50, comma 1 lett. c), d), e), bisogna usare le schede P7.1.3 o P.7.2, a seconda del caso.

**Comment by anac-uscp** [comment]
> Le schede AD1_25/26/27/28 vanno usate quando la stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore soglia comunitaria. Le schede AD2_25/26/27/28 vanno usate quando la stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite massimo ammesso per l’affidamento diretto e inferiore alla soglia comunitaria (quindi nei casi in cui, secondo l’art 50 comma 1 lett. c), d), e), bisognerebbe usare la procedura negoziata sottosoglia). La scheda AD_3 vanno usate quando la stazione appaltante procede ad un affidamento diretto di importo superiore a 5000 euro e inferiore ai valori ammessi per l’affidamento diretto ex art 50 comma 1 lett. a), b). Per le procedure negoziate senza bando sottosoglia ex art. 50, comma 1 lett. c), d), e), bisogna usare le schede P7.1.3 o P.7.2, a seconda del caso.
**RETTIFICA ALLA SUDDETTA RISPOSTA DEL 29/11/2023**
Le schede AD1_25/26/27/28 vanno usate quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e  b) – e intende pubblicare un avviso per la trasparenza volontaria ex ante.
Le schede AD2_25/26/27/28 vanno usate quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e b) - e non intende pubblicare un avviso per la trasparenza volontaria ex ante.
La scheda AD_3 va usata quando la stazione appaltante procede ad un affidamento diretto di importo superiore a 5000 euro e inferiore ai limiti ammessi per l’affidamento diretto ex art 50 comma 1 lett. a), b). 
Per le procedure negoziate senza bando sottosoglia ex art. 50, comma 1 lett. c), d), e), bisogna usare le schede P7.1.3 o P.7.2, a seconda del caso.

**Comment by anac-uscp** [comment]
**RETTIFICA ALLA SUDDETTA RISPOSTA DEL 29/11/2023**
Le schede AD1_25/26/27/28 vanno usate quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e b) – e intende pubblicare un avviso per la trasparenza volontaria ex ante.
Le schede AD2_25/26/27/28 vanno usate quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e b) - e non intende pubblicare un avviso per la trasparenza volontaria ex ante.
La scheda AD_3 va usata quando la stazione appaltante procede ad un affidamento diretto di importo superiore a 5000 euro e inferiore ai limiti ammessi per l’affidamento diretto ex art 50 comma 1 lett. a), b).
Per le procedure negoziate senza bando sottosoglia ex art. 50, comma 1 lett. c), d), e), bisogna usare le schede P7.1.3 o P.7.2, a seconda del caso.

**Comment by AvvGaetano** [comment]
È possibile utilizzare una procedura negoziata senza bando per valore > 5K e minore soglie ex art. 50, comma 1 lett. c), d), e)? Con quale scheda?
