### ISSUE TITLE
[Consip] Scheda M1 - ERR2 

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#715]
inviando la scheda M1, sul conferma-scheda riscontriamo l'errore:

di seguito i dati:
clientid: 01e2efc4-f2cd-40f4-bac1-05e7c6dcefba

 "idScheda": "cc42a125-9a8a-4b07-af9f-6afa7afaf8c6"
 "idAppalto": "e62f08ee-ffce-49c8-a663-a58ca32900b9"

GovWay-Transaction-ID:"6a411148-89e1-11ee-a061-0050568e9679"
GovWay-Message-ID:"1824591e-c84e-4869-ab40-d718675d4422"

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire un nuovo ticket di segnalazione. Grazie per la Sua collaborazione.
