### ISSUE TITLE
[mf] - quadro economico in schede AD1_XX (ad es. AD1_28)

### ISSUE THREAD

**Issue by marcofa1985** [anticorruzione/npa#716]
Gentile supporto, 
controllando le schede della famiglia "AD1_XX" mi sono accorto che solo la AD1_28 è dedicata alle concessioni:

![immagine](https://github.com/anticorruzione/npa/assets/99912157/73a1f241-e53c-4708-bcd8-8d4952d91535)

Ciò nonostante. in tutte le schede AD1_XX (quindi la AD1_25, AD1_26, AD1_27, AD1_28) sono presenti, come campi alimentabili, sia il quadro economico "standard" che il quadro economico "concessioni", con alcune voci di quadro evidentemente ridondanti (es. impLavori compare in entrambi).

Mi verrebbe da dire che forse i due QE siano mutuamente esclusivi fra loro: il QE delle concessioni dovrebbe essere l'unico richiesto nella AD1_28, mentre il QE "standard" l'unico richiesto nelle AD1_25, AD1_26, AD1_27... ma non ho trovato validazioni a sostegno di questa mia tesi

E' quindi un bug lato PCP, oppure è corretto così perchè sono ammessi casi di compresenza di entrambi i QE?

Grazie.

**Comment by anac-uscp** [comment]
<p>La ridondanza segnalata è stata eliminata.</p>
