### ISSUE TITLE
Scheda per affidamento diretto sotto soglia (ad es. AD2_25)

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#717]
In caso di affidamento diretto per importi sotto soglia senza invio a TED non è chiara la differenza rispetto la scheda utilizzare tra:

AD2_25	Affidamento diretto, valida per i sotto soglia e superiori a 5.000 Euro, senza invio al TED
Articolo 50 comma 1 lettere c) d) e)  decreto legislativo 36/2023
Articolo 50 comma 9 decreto legislativo 36/2023
Avviso volontario per la trasparenza ex ante — direttiva generale - Articolo 3 bis della direttiva 89/665/CEE

AD3	Affidamento diretto, valida per affidamento diretto inferiore al limite massimo dell'affidamento diretto, senza invio al TED
Articolo 50 comma 9 decreto legislativo 36/2023

**Comment by anac-uscp** [comment]
Le schede AD2_25/26/27/28 vanno usate quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e b) - e non intende pubblicare un avviso per la trasparenza volontaria ex ante.
La scheda AD_3 va usata quando la stazione appaltante procede ad un affidamento diretto di importo superiore a 5000 euro e inferiore ai limiti ammessi per l’affidamento diretto ex art 50 comma 1 lett. a), b). Per le procedure negoziate senza bando sottosoglia ex art. 50, comma 1 lett. c), d), e), bisogna usare le schede P7.1.3 o P.7.2, a seconda del caso

**Comment by anac-uscp** [comment]
Le schede AD2_25/26/27/28 vanno usate quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e b) - e non intende pubblicare un avviso per la trasparenza volontaria ex ante.
La scheda AD_3 va usata quando la stazione appaltante procede ad un affidamento diretto di importo superiore a 5000 euro e inferiore ai limiti ammessi per l’affidamento diretto ex art 50 comma 1 lett. a), b). Per le procedure negoziate senza bando sottosoglia ex art. 50, comma 1 lett. c), d), e), bisogna usare le schede P7.1.3 o P.7.2, a seconda del caso
