### ISSUE TITLE
Consulta Avviso - Specifiche errate

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#718]
Attualmente il consulta avviso restituisce una response formattata in questo modo:

![immagine](https://github.com/anticorruzione/npa/assets/137039656/018c7ec2-23dc-4d97-8839-0ff081bc6fb2)

Ho compresso le informazioni per omettere i kg di dati contenuti.
Da openapi però i campi scheda, piano e appalto sono contenuti dentro il campo avviso anzichè stare sullo stesso livello.

![immagine](https://github.com/anticorruzione/npa/assets/137039656/a01e47fa-47e5-4d2a-a423-0034e2dfa27c)

**Comment by supportoAnac** [comment]
Il formato della response sarà fixato nel prossimo rilascio.
