### ISSUE TITLE
[BLK] [CONSIP] Scheda S4 - ERR4

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#719]
Dopo avere creato la scheda S4 riceviamo un errore ERR4, di seguito tutte le informazioni:

Errore in crea-scheda di una S4:
{

                "status": 400,

                "title": "KO",

                "detail": "Errore",

                "type": "about:blank",

                "errori": [

                    {

                        "idTipologica": "errori",

                        "codice": "ERR4"

                    }

                ]

            }
 
GovWay-Message-ID: db42fdf5-24d3-4429-a80d-272849167f0d
GovWay-Transaction-ID: 7c3037e4-8a22-11ee-a061-0050568e9679

{
   "idAppalto": "5d846d7b-9b2a-48d2-8701-fcb23fe2e8ea",
   "scheda": {
      "codice": {
         "idTipologica": "codiceScheda",
         "codice": "S4"
      },
      "versione": "1.0",
      "body": {
         "anacForm": {
             "cig": "B0000271D5",
             "partecipante": {
                "codiceFiscale":"13454210157",
                "denominazione":"Accenture",
                "ruoloOE":{
                    "description":"Mandataria",
                    "idTipologica":"ruoloOE",
                    "codice":"1"
                },
                "tipoOE":{
                    "idTipologica":"tipoOE",
                    "codice":"1"
                },
                "idPartecipante": "a5862131-341b-40d7-a60b-bd5b301ffa67",
                "paeseOperatoreEconomico":"Italia",
                "avvalimento": false,
                "tipologiaAvvalimento":{
                    "idTipologica":"tipologiaAvvalimento",
                    "codice":"1"
                },
                "impreseAusiliarie": [
                    {
                        "codiceFiscale":"71345421015",
                        "denominazione":"Erutnecca"
                    }
                ]
             },
             "motivoVariazione": {
                 "idTipologica": "motivoVariazione",
                 "codice": "4"
             }
         }
      }
   }
}

**Comment by lauralu1993** [comment]
è stato effettuato un nuovo test aggiungendo il campo "motivoVariazione" ma l'esito è sempre il medesimo:
400 Bad Request: "{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR4"}]}

**"idAppalto":"e62f08ee-ffce-49c8-a663-a58ca32900b9"
GovWay-Message-ID:"afe21848-7bbc-453a-82f8-64388d356ca8"
GovWay-Transaction-ID:"54d80970-8ed0-11ee-a061-0050568e9679"**


JSON
{
   "idAppalto":"e62f08ee-ffce-49c8-a663-a58ca32900b9",
   "scheda":{
      "codice":{
         "idTipologica":"codiceScheda",
         "codice":"S4"
      },
      "versione":"1.0",
      "body":{
         "anacForm":{
            "cig":"D00002302F",
            "partecipante":{
               "codiceFiscale":"13454210157",
               "denominazione":"Accenture",
               "ruoloOE":{
                  "description":"Mandataria",
                  "idTipologica":"ruoloOE",
                  "codice":"1"
               },
               "tipoOE":{
                  "idTipologica":"tipoOE",
                  "codice":"1"
               },
               "idPartecipante":"dc964299-9653-4032-a971-3ab5eb983091",
               "paeseOperatoreEconomico":"Italia",
               "avvalimento":false,
               "tipologiaAvvalimento":{
                  "description":"Requisito",
                  "idTipologica":"tipologiaAvvalimento",
                  "codice":"1"
               }
            },
            "motivoVariazione":{
               "idTipologica":"motivoVariazione",
               "codice":"1"
            }
         }
      }
   }
}

**Comment by iolferri95** [comment]
è stato effettuato un nuovo test oggi 30/11/2023 aggiungendo il campo "motivoVariazione" il servizio risponde 400.

400 Bad Request: "{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR4"}]}"

**"idAppalto":"e62f08ee-ffce-49c8-a663-a58ca32900b9"
GovWay-Message-ID:"3293824b-7fe7-41d0-ac9a-7a38cf43865f"
GovWay-Transaction-ID:"52e77748-8f5f-11ee-b4a0-0050568e08b3"**


JSON

{
   "idAppalto":"e62f08ee-ffce-49c8-a663-a58ca32900b9",
   "scheda":{
      "codice":{
         "idTipologica":"codiceScheda",
         "codice":"S4"
      },
      "versione":"1.0",
      "body":{
         "anacForm":{
            "cig":"C0000261D5",
            "partecipante":{
               "codiceFiscale":"13454210157",
               "denominazione":"Accenture",
               "ruoloOE":{
                  "description":"Mandataria",
                  "idTipologica":"ruoloOE",
                  "codice":"1"
               },
               "tipoOE":{
                  "idTipologica":"tipoOE",
                  "codice":"1"
               },
               "idPartecipante":"dc964299-9653-4032-a971-3ab5eb983091",
               "paeseOperatoreEconomico":"Italia",
               "avvalimento":false,
               "tipologiaAvvalimento":{
                  "description":"Requisito",
                  "idTipologica":"tipologiaAvvalimento",
                  "codice":"1"
               }
            },
            "motivoVariazione":{
               "idTipologica":"motivoVariazione",
               "codice":"1"
            }
         }
      }
   }
}

**Comment by NicolaOrritos** [comment]
Test ripetuto 30/11 alle 12:01.

GovWay-Message-ID: 52585f94-64cf-497c-a187-1a97b0f9d873
GovWay-Transaction-ID: a5b6cd40-8f6a-11ee-b4a0-0050568e08b3
idAppalto: 5d846d7b-9b2a-48d2-8701-fcb23fe2e8ea

```JSON
400 Bad Request
{
    "status": 400,
    "title": "KO",
    "detail": "Errore",
    "type": "about:blank",
    "errori": [
        {
            "idTipologica": "errori",
            "codice": "ERR4"
        }
    ]
}
```

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire un nuovo ticket di segnalazione. Grazie per la Sua collaborazione.
