### ISSUE TITLE
[CONSIP] Scheda A1.31 - sezione Appalto assente

### ISSUE THREAD

**Issue by evalentip** [anticorruzione/npa#721]
Si chiede informazioni circa la mancanza della sezione Appalto per la scheda A1.31 . 
Per le altre schede di aggiudicazioni (es. A1.32) tale sezione risulta invece prevista.

**Comment by anac-uscp** [comment]
Secondo le delibere 214/2022 e 215/2022 il set di dati raccolti negli appalti della difesa è ridotto
