### ISSUE TITLE
Richiesta esito servizi asincroni - Tempi di risposta

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#722]
Nell'incontro di oggi è stato detto che  in situazione di poco carico la risposta è immediata, credo che sarà una situazione rara.
Dovremmo sapere in una situazione di carico medio i tempi di risposta, è fondamentale anche per dare informazioni agli utenti che devono avere un indicazione di massima su quanto tempo potrebbero dover aspettare per avere risposta

**Comment by r-dm123** [comment]
#I tempi di risposta si conosceranno durante la fase di stress test prevista per i prossimi giorni, verranno date informazioni generali a tutti mediante changelog
