### ISSUE TITLE
Schede AD - Stati appalto

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#723]
Buongiorno,

le schede AD devono essere confermate tramite il conferma appalto. una volta avviata la conferma l'appalto transita direttamente nello stato pubblicato, non è prevista la pubblicazione degli avvisi?

le schede AD3, AD4 e AD5 che non prevedono pubblicazione, l'appalto transita comunque in uno stato pubblicato?

Grazie

**Comment by LucaMaggioni1** [comment]
Chiusa per risposta durante riunione

**Comment by supportoAnac** [comment]
Si esatto, lo stato transita sempre in pubblicato, cosi si possono inserire le schede di post pubblicazioni previste dall'orchestratore.
