### ISSUE TITLE
FVOE - Tipologica FVA

### ISSUE THREAD

**Issue by MarikaLaccarini** [anticorruzione/npa#724]
Ad oggi, viene indicata come tipologica relativa ai documenti dell'FVOE la medesima dell'FVA che non ci sembra coerente. Quando verrà fornita quella corretta?

**Comment by supportoAnac** [comment]
La tipologica dei documenti è comune alle funzionalità dei fascicoli virtuali. L'esposizione del documento sarà filtrata/controllata dall'operazione invocata. In futuro ci riserviamo la possibilità di aggiungere un indicatore nell'attributo della tipologica per indicarne un ambito specializzato.
