### ISSUE TITLE
PartecipanteADType - Errata obbligatorietà ruoloOE

### ISSUE THREAD

**Issue by ctav8** [anticorruzione/npa#725]
Buongiorno,
per segnalare che in seguito all'aggiornamento eseguito in data odierna (24/11) in PartecipanteADType è stato reso obbligatorio anche il campo `ruoloOE`.
Tale obbligatorietà va rimossa, in quanto in caso di tipoOE = 1 il campo ruoloOE non ha ragione di essere compilato.

**Comment by supportoAnac** [comment]
La segnalazione è corretta. Va aggiornata la tipologica con ruoli ulteriori rispetto al solo RTI per i concorrenti composti da più OE. Tale attività è prevista ma non ancora effettuata.
