### ISSUE TITLE
PCP Attributi richiesti per la fruizione per gestore privato abilitato da Agid

### ISSUE THREAD

**Issue by Alessandroava** [anticorruzione/npa#726]
Buongiorno, anche noi come per il ticket 408 [https://github.com/anticorruzione/npa/issues/408](url) non vediamo riconosciuti gli attributi utili ad effettuare le richieste di fruizione in ambiente di collaudo. 
L'ente interessato è SAP Italia S.p.A.

Grazie per l'aiuto.

Alessandro Paoletti

**Comment by FedericaSicchiero** [comment]
Buongiorno, se avete completato la procedura di onboarding su PDND gli attributi verranno associati a breve.
