### ISSUE TITLE
[BLK] CONSIP-FVOE-errore 401-Utente non autorizzato su Richiedi Accesso 

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#727]
Effettuando la chiamata a servizio di Richiedi Accesso con la seguente Request
[17:45] Patrizio Lattanzi

POST

URL = https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiesta-accesso-fvoe

 
HEADER
 
Accept: application/json

Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L0ZWQy92MiIsInN1YiI6Ijk2MzQwNzUxLWI1MmYtNDE5YS1iMDg4LTg3MWY4ZmUwZGZiMCIsIm5iZiI6MTcwMDg0MzY3NywiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiYzU2NmJjNjdlZmY5MDExZDhhMzNjY2I5YmJiMWVmMTE0MzUyMzc4ZTdiZmE3ZTA2YmE4NzVlYzExNjcyODFmZSJ9LCJwdXJwb3NlSWQiOiJlYjdmZWFlZi0wYWMwLTQ0NjAtODRmYS0xZGU1M2FkYjc2NGQiLCJpc3MiOiJ1YXQuaW50ZXJvcC5wYWdvcGEuaXQiLCJleHAiOjE3MDA4NDcyNzcsImlhdCI6MTcwMDg0MzY3NywiY2xpZW50X2lkIjoiOTYzNDA3NTEtYjUyZi00MTlhLWIwODgtODcxZjhmZTBkZmIwIiwianRpIjoiYzFiNDdiMTYtZTkwNS00NzQ3LTg1ZTYtYjUxMDBhMzJmN2QzIn0.bGHutPwlujXjFpyBzlDflkdBUMUGxbF9sfur1y1U24ZbSqAZm17VXQqFu3gP67y2KHUmt5N1j0K2VWtsy0kHQ-lRFqOMs1zgzQrr3KHWfVzdpNEWHws4NeNmR2-aABg7_l02B9Sp-m3bNq14JVKry9MwpW9d3_RrV_WRR2MI1G03D6r-r_-ylJddmEeZ8x_nDilu3heDFx3WW8FTl6uAdNim6fx7vv6QAZmw6sN3JEoZk8nRrM-X5df1pBwUHTA8lQPPlDHjUTZ7tpcTcuRN-NQKi03pqJBhEMj6m0KtIAouKb6tn8Zgi9fKVgEcRwUgAL1SAnrRvnrHrxzHADSQXQ

User-Agent: Swagger-Codegen/1.0.0/java

Agid-JWT-TrackingEvidence: eyJraWQiOiJGbXFlbFpkMS02VS1NNF8tN0VhMFlHWTJzT0lrMUZYcFpCb25oN2tBbnVnIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJ0cmFjZUlEIjoibXlUcmFjZUlkIiwidXNlcklkcFR5cGUiOiJTUElEIiwicmVnQ29kaWNlQ29tcG9uZW50ZSI6IjAwMDAwMTAiLCJwdXJwb3NlSWQiOiJlYjdmZWFlZi0wYWMwLTQ0NjAtODRmYS0xZGU1M2FkYjc2NGQiLCJ1c2VyTG9hIjozLCJyZWdDb2RpY2VQaWF0dGFmb3JtYSI6IjAwMDAwMDkiLCJTQUNvZGljZUZpc2NhbGUiOiIwNTM1OTY4MTAwMyIsInNwYW5JRCI6Im15U3BhbklkIiwiYnVzaW5lc3NGbG93SUQiOiI3YjUzZDY2Zi1hZmEyLTRmMzAtOGVlYS0zOWQyZTg0NjY1YWYiLCJ1c2VyUm9sZSI6IlJQIiwiU0Fjb2RpY2VBVVNBIjoiOTAwMDAwMDAwOSIsImp0aSI6ImQ5NGFkMWRiLTA2YjAtNDJkZi05OTMxLWUzZDFiYWJjYTU1MSIsInVzZXJDb2RpY2VGaXNjYWxlIjoiVVNSUlVQMjZBMDFBMTE2QSIsImF1ZCI6Imh0dHBzOi8vYXBpZ3ctdGVzdC5hbnRpY29ycnV6aW9uZS5pdC9tb2RpL3Jlc3QvRlZDL3YyIiwiaWF0IjoxNzAwODQzNjc0LCJleHAiOjE3MDA4NDcyNzQsIm5iZiI6MTcwMDg0MzY3NH0.bzMAXF3idpeCLzw7cmo5dJby-yVawy200GRJSH6qbXt9ies7WfLh-cho1ux4bDFBkF9B8yJR_YGzcb0kSsb8jyLLpDKw738rYuRKUNbUbmGpR10TCEsrJMsgEoBjZqReFYBoGJcxeYExlcs9qz1_zeqFsAqUhef5SfqtWlxkx5jL0eCB5CKlg3FTlfr-OmK89OGdWwqjInB3uVlk90S-8GE3kbUv5Ct0bh-noXdSYMBJZF_AA_Fdzj8BDbTyzhW7ThHVlJV58jPS7m4n-ukt80u2ygHey5rJi6v2dKnxFMb0r3no3IXx2BB9N4oH-ooGTLodsBnwmVsPO2HtgwpFBQ

Content-Type: application/json; charset=utf-8

Content-Length: 213
 
REQUEST
 
class RichiestaAccessoRequest {

    class RichiestaAccessoType {

        idRichiesta: null

        dataInizioAutorizzazione: 2023-11-10T02:46:18Z

        dataFineAutorizzazione: null

        operatoriEconomici: [class AnagraficaOEType {

            class AnagraficaType {

                codiceFiscale: 5359681003

            }

            personaGiuridica: null

        }]

        appalto: class AppaltoType {

            class AppaltoBaseType {

                idAppalto: 1a11bdfc-1bbb-42e4-96da-e695a176863b

                codiceAppalto: null

                oggetto: null

                dataCreazione: null

                stato: null

            }

            lotti: null

        }

    }

}

con utente USRRUP26A01A116A

il token viene generato con questi parametri attualmente

public static final String SAcodiceAUSA="9000000009";
	public static final String SACodiceFiscale="5359681003";
	public static final String userCodiceFiscale="USRRUP26A01A116A";
	public static final String userRole="RP"; //DRP
	public static final Integer userLoa=3; //4
	public static final String userIdpType="SPID"; //5
	public static final String regCodiceComponente="0000010";
	public static final String regCodicePiattaforma="0000009";

l'errore che viene tornato è 401

si chiede di dare informazioni sul motivo dell'errore

**Comment by r-dm123** [comment]
Issue rientrata
