### ISSUE TITLE
[BLK] [CONSIP] Aggiungi-soggetto: Riscontrato errore tipo "ERR9999"

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#728]
Riscontriamo un errore tipo "ERR9999" richiamando il servizio aggiungi-soggetto di seguito le informazioni della chiamata:

{"codiceFiscale":"USRDR354A01A144A","idAppalto":"c88f5cb1-65ee-4ab4-ae35-d9e55e926697","ruolo":
{"idTipologica":"tipoRuolo","codice":"DRP3"},"dataInizio":"2023-11-23T17:00:04.847Z"}

HTTP response code: 500
HTTP response body: {"status":500,"title":"KO","detail":"Errore Generico","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}

Data, 23 Nov 2023 17:00:06 GMT
govway-message-id=4ec90463-0ace-4d37-ac8a-2dec2d0836cd
govway-transaction-id=3e3bf1b8-8a1b-11ee-b4a0-0050568e08b3

**Comment by paolo-urbanetto** [comment]
Ci aggiungiamo anche noi (Maggioli), stesso problema.
Inoltre sollecito contestualmente anche la issue [736](https://github.com/anticorruzione/npa/issues/736)

**Comment by cmauriello** [comment]
come richiesto effettuato un’altra prova con i seguenti dati:

CF RUP: MAIPTL83R03L628F
idAppalto: 0bf19992-3dce-4018-8bf4-ae26b5636704
CF soggetto: USRDR354A01A144A

Ricevendo come risposta sempre un http 500 con i seguenti dettagli:

govway-message-id=[daf6b928-fbf5-48a1-b9c9-519a994dc218]
govway-transaction-id=[fd771c1d-9902-11ee-9fc8-0050568e08b3]

**Comment by cmauriello** [comment]
21/12 Effettuato test  con esito negativo inserendo date con il formato in millisecondi:

HTTP response code: 500
HTTP response body: {"status":500,"title":"KO","detail":"Errore Generico","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}

govway-message-id=[ef887f75-eda9-4684-8301-47a1a3d45865]
govway-transaction-id=[98d8c921-a017-11ee-9fc8-0050568e08b3]

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire un nuovo ticket di segnalazione. Grazie per la Sua collaborazione.
