### ISSUE TITLE
[CONSIP] - ERR4 su S4

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#729]
Non riusciamo a creare la scheda S4 poichè otteniamo ERR4 - errore nella conversione della scheda secondo il json schema definito.

di seguito i dati:
**"idAppalto": "c9d1f5cd-cab0-45f4-8955-8df17710d7f4"
clientId: 01e2efc4-f2cd-40f4-bac1-05e7c6dcefba
GovWay-Message-ID:"ef4256be-883e-485b-949e-823c7663bd6c"
GovWay-Transaction-ID:"6bc56144-8ae7-11ee-b4a0-0050568e08b3"**

JSON 
{
   "idAppalto": "c9d1f5cd-cab0-45f4-8955-8df17710d7f4",
   "scheda":{
      "codice":{
         "idTipologica":"codiceScheda",
         "codice":"S4"
      },
      "versione":"1.0",
      "body":{
         "anacForm": {
                        "cig": "O000026BB9",
                        "partecipante": 
                            {
                                "codiceFiscale": "13454210157",
                                "denominazione": "Accenture",
                                "ruoloOE": {
                                    "description": "Mandataria",
                                    "idTipologica": "ruoloOE",
                                    "codice": "1"
                                },
                                "tipoOE": {
                                    "idTipologica": "tipoOE",
                                    "codice": "1"
                                },
                                "idPartecipante": "9b45164a-2ae6-425c-b01c-5d3fae74c9b2",
                                "paeseOperatoreEconomico": "Italia",
                                "avvalimento": false,
                                "tipologiaAvvalimento": {
                                    "description": "Requisito",
                                    "idTipologica": "tipologiaAvvalimento",
                                    "codice": "1"
                                }
                            }
         }
      }
   }
}

**Comment by supportoAnac** [comment]
Duplicata di https://github.com/anticorruzione/npa/issues/719 .

**Comment by lauralu1993** [comment]
è stato effettuato un nuovo test aggiungendo il campo "motivoVariazione" ma l'esito è sempre il medesimo:
400 Bad Request: "{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR4"}]}

**"idAppalto":"e62f08ee-ffce-49c8-a663-a58ca32900b9"
GovWay-Message-ID:"afe21848-7bbc-453a-82f8-64388d356ca8"
GovWay-Transaction-ID:"54d80970-8ed0-11ee-a061-0050568e9679"**


JSON
{
   "idAppalto":"e62f08ee-ffce-49c8-a663-a58ca32900b9",
   "scheda":{
      "codice":{
         "idTipologica":"codiceScheda",
         "codice":"S4"
      },
      "versione":"1.0",
      "body":{
         "anacForm":{
            "cig":"D00002302F",
            "partecipante":{
               "codiceFiscale":"13454210157",
               "denominazione":"Accenture",
               "ruoloOE":{
                  "description":"Mandataria",
                  "idTipologica":"ruoloOE",
                  "codice":"1"
               },
               "tipoOE":{
                  "idTipologica":"tipoOE",
                  "codice":"1"
               },
               "idPartecipante":"dc964299-9653-4032-a971-3ab5eb983091",
               "paeseOperatoreEconomico":"Italia",
               "avvalimento":false,
               "tipologiaAvvalimento":{
                  "description":"Requisito",
                  "idTipologica":"tipologiaAvvalimento",
                  "codice":"1"
               }
            },
            "motivoVariazione":{
               "idTipologica":"motivoVariazione",
               "codice":"1"
            }
         }
      }
   }
}
