### ISSUE TITLE
[BLK] Schede S - chiamata per ogni lotto o solo una per ogni appalto?

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#731]
A seguito della riunione tecnica del 16/11/2023, è stato chiarito che le schede S1 ed S2 devono essere trasmesse una sola volta per ogni appalto, raccogliendo al proprio  interno i dati relativi a tutti i lotti, raggruppati per CIG.
Alla issue #215 è stata però risposto l'esatto contrario, ovvero che le schede S1 ed S2 vadano inviate per ogni CIG, quindi anche più volte per lo stesso appalto.
Qual è l'interpretazione corretta?

**Comment by supportoAnac** [comment]
La risposta ambigua è dovuta ad una modifica del modello dati del 13 Novembre: prima, le schede S davano la possibilità di comunicare un solo CIG alla volta. Dal 13 Novembre è cambiata la struttura dati ed è stato reso possibile comunicare più CIG (l’oggetto è diventato array).
Si conferma che nell’attuale modello dati è possibile inviare con le schede S informazioni relative a più CIG.
