### ISSUE TITLE
Scheda per aggiudicazione AQ

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#732]
Assodato che le informazioni sugli appalti specifici derivanti da AQ devono essere trasmessi alla BDNCP ma non al TED, chiedo: per l’aggiudicazione occorre utilizzare sempre la scheda P2_16 sia per importi pari o sopra soglia (dove comunemente si utilizza la P1_16 con eform 16) che sotto soglia?

Per la pubblicazione ho utilizzato la scheda P6_2

Grazie

**Comment by anac-uscp** [comment]
Per pubblicare un bando per aggiudicare/concludere un accordo quadro bisogna usare la scheda P1_16 (sopra soglia appalti settori ordinari) o P2_16 (sotto soglia appalti settori ordinari). 
L’aggiudicazione della procedura bandita con P1_16 o P2_16 viene comunicata tramite le schede A1_29 o A2_29
L’adesione di una stazione appaltante all’accordo quadro - che avviene in momento successivo all’aggiudicazione dell’accordo quadro - deve essere comunicata con la scheda AD_4 (se senza confronto competitivo) o con la scheda P6_2 (con confronto competitivo)
