### ISSUE TITLE
[BLK]  idPartecipante - Richiesta informazioni

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#735]
Salve,
mi aggiungo alla issue #603. 
Si richiede chiarimento in merito perchè è bloccante.

**Comment by supportoAnac** [comment]
Confermiamo che il campo idPartecipante va generato in fase di creazione della chiamata dalla stazione appaltante, quando si invia la scheda S2 o quando si inviano le schede di affidamento diretto con l’elenco dei partecipanti.
