### ISSUE TITLE
[BLK] Aggiornamento documentazione PCP

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#737]
sarebbe utile comprendere quando sarà resa disponibile la nuova documentazione per poter aggiornare tutti i processi e le modifiche alla funzionalità necessarie nel nuovo scenario anticipato da Michele nella riunione di venerdì u.s.

**Comment by supportoAnac** [comment]
Si chiede gentilmente di specificare in modo più preciso a quale nuova documentazione si fa riferimento.

**Comment by FRASCA57** [comment]
Mi sembrava chiara, ma ora lo spiego con un'immagine:

![image](https://github.com/anticorruzione/npa/assets/137269683/5da26ecd-7123-44c4-a28c-6ba2d7736781)

Grazie per il supporto.

**Comment by FRASCA57** [comment]
Buongiorno, stamattina, come per incanto le obbligatorietà sono comparse nelle specifiche dei servizi, che era quanto richiedevo.
Quindi chiudo la issue.
