### ISSUE TITLE
Scheda S2 - Invio in caso di aggiudicazione di lotti in momenti diversi

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#738]
Buongiorno,
in caso di gara a lotti dove inizialmente vengono aggiudicati solo alcuni lotti è stato confermata la possibilità di trasmettere la scheda di aggiudicazione (es. A1.29) più volte, con i relativi lotti aggiudicati (vedi [issue 601](https://github.com/anticorruzione/npa/issues/601))

In tal caso, anche la scheda S2 può o deve essere trasmessa più volte per i rispettivi lotti?

**Comment by supportoAnac** [comment]
Sì.
