### ISSUE TITLE
Validazione P1_16/17 - Regole errate relative a campi inesistenti

### ISSUE THREAD

**Issue by ctav8** [anticorruzione/npa#739]
Buongiorno, segnalo che nel file .dmn relativo alle schede P1_16 e P1_17 le regole relative all'errroe: REG6_1 e REG6_2 fanno riferimento al campo `appalto.datiBaseProcedura.tipoProcedura.codice` ma `datiBaseProcedura` non è un campo previsto nei tipi `AppaltoP16Type` e `AppaltoP17Type`.

**Comment by supportoAnac** [comment]
L’oggetto datiBaseProcedura di appalto è un dato in comune con il TED: nei sottosoglia è contenuto nell’anacForm, mentre nei soprasoglia, come nel caso delle schede P1_16 e P1_17 citate, è un dato presente nell’eForm. Poichè sono dati necessari anche per la pubblicazione nazionale il servizio estrae, per i soprasoglia, questi dati dall’eForm e applica le due regole citate.
Questa considerazione vale per tutti i dati in comune con il TED, che vengono esplicitamente inseriti in anacForm per tutte le schede che non prevedono eForm e nell’eForm per quelle che prevedono pubblicazione TED.
