### ISSUE TITLE
Tipologiche simili - Richiesta Delucidazioni

### ISSUE THREAD

**Issue by GiovanniSom** [anticorruzione/npa#742]
Buongiorno, la lista delle tipologiche presenta due tipologiche simili come denominazione e con gli stessi valori, ossia

- ModalitàRiaggiudicazioneAffidamento
- ModalitàRiaggiudicazioneAffidamento

Quale risulta da utilizzare? Cosa avverrà all'altra?
grazie e buona giornata

**Comment by supportoAnac** [comment]
La tipologica corretta da referenziare è modalitàRiaggiudicazioneAffidamento. La tipologica ModalitàRiaggiudicazioneAffidamento verrà eliminata appena possibile.
