### ISSUE TITLE
[BLK] Scheda P4_1 - ERR9999 al verifica/conferma appalto

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#744]
A seguito del rilascio, si riscontra sempre lo stesso errore precedentemente segnalato con la issue #698 
Di seguito i nuovi dati di invio:

idAppalto: 0f7a3dbc-02b4-459b-bf94-77951252ca8d

govway della chiamata verifica-appalto:

govway-transaction-id:bedb5085-8dcd-11ee-a061-0050568e9679
govway-message-id:1fb6e039-7ee7-4aab-88ae-be8312effb22

govway della chiamata conferma-appalto:

govway-transaction-id:c2893d72-8dcd-11ee-a061-0050568e9679
govway-message-id:ac37757a-7d8a-4af7-9752-7c508df22d54

**Comment by supportoAnac** [comment]
Risulta fixata.
