### ISSUE TITLE
Attributo funzioniSvolte - Valori Tipologica

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#745]
L'attributo "funzioniSvolte" (Ruolo svolto dalla S.A. nell'appalto) in StazioneAppaltanteType è un array.
Tuttavia, i valori della tipologica sono mutuamente esclusivi, per cui credo che debba essere un valore singolo.

**Comment by supportoAnac** [comment]
La struttura prevede una lista per consentire future espansioni senza necessità di aggiornamento software, ma solo intervenendo sulla tipologica.
