### ISSUE TITLE
[Intercent-ER] [Scheda I1] Possibile refuso in DatiInizioType

### ISSUE THREAD

**Issue by AndreaClerici** [anticorruzione/npa#748]
Buongiorno, segnalo che sembra esserci un refuso nella Scheda I1.
Su https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/schede/modello-dati-schede-I1.yaml#/components/schemas/DatiInizioType infatti vedo che in DatiInizioType  è presente l'attributo **dataDisposizioneInzio**.
Immagino che il nome corretto possa essere **dataDisposizioneInizio**.

Vi chiedo di correggere o di confermare la dicitura corrente.

Grazie

**Comment by supportoAnac** [comment]
La problematica segnalata è stata corretta con l'ultimo rilascio.
