### ISSUE TITLE
Schede affidamento (ad es. AD3)

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#749]
Ho un questo da porre in merito all’invio alla BDNCP delle informazioni relative all’affidamento diretto. 

Dalle specifiche dell’orchestratore, rilevo che nel caso di affidamento diretto superiore ai 5.000 euro e inferiore alle soglie comunitarie (quindi 5.382.000 per lavori e 215.000 per servizi e forniture) occorre utilizzare la scheda AD2_25; mentre per affidamento diretto inferiore al limite massimo dell'affidamento diretto (quindi 150.000 per lavori e 140.000 per servizi e forniture) occorre utilizzare la scheda AD3 

A tal proposito, la scheda AD3 mi sembra un sotto gruppo della scheda AD2_25. Mi sembra dunque possibile sempre utilizzare la scheda AD2_25 nel caso di affidamenti superiore ai 5.000 euro e inferiori alle soglie comunitarie anche se gli stessi risultano inferiore alle soglie di affidamento. 

È corretta tale interpretazione, oppure esiste una discriminante di scelta che non comprendo per utilizzare la AD3 solo se l’importo è inferiore alle soglie di affidamento in luogo della AD2_25.

**Comment by anac-uscp** [comment]
Le schede AD2_25/26/27/28 vanno usate quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e b) - e non intende pubblicare un avviso per la trasparenza volontaria ex ante. E' richiesta una giustificazione per questo tipo di affidamento.

La scheda AD_3 va usata quando la stazione appaltante procede ad un affidamento diretto di importo superiore a 5000 euro e inferiore ai limiti ammessi per l’affidamento diretto ex art 50 comma 1 lett. a), b).
Non è richiesta una giustificazione per questo tipo di affidamento.

**Comment by anac-uscp** [comment]
Le schede AD2_25/26/27/28 vanno usate quando una stazione appaltante procede, in via eccezionale, ad un affidamento diretto di importo pari o superiore al limite ammesso per l’affidamento diretto - vedi limiti massimi previsti dall’art 50 comma 1 lett. a) e b) - e non intende pubblicare un avviso per la trasparenza volontaria ex ante. E' richiesta una giustificazione per questo tipo di affidamento.

La scheda AD_3 va usata quando la stazione appaltante procede ad un affidamento diretto di importo superiore a 5000 euro e inferiore ai limiti ammessi per l’affidamento diretto ex art 50 comma 1 lett. a), b).
Non è richiesta una giustificazione per questo tipo di affidamento.
