### ISSUE TITLE
Scheda AD4 - Richiesta chiarimenti "presunta" obbligatorietà DGUE

### ISSUE THREAD

**Issue by DarioLap** [anticorruzione/npa#750]
Buongiorno,
vorremmo capire cosa si intende quando, da orchestratore, per la scheda AD4 (adesione ad AQ/convenzione senza successivo confronto competitivo) si richiede come obbligatoria la presenza del DGUE.
Grazie

**Comment by anac-uscp** [comment]
In esito alla recente riunione sull'obbligatorietà del DGUE, sulla scheda AD4 il DGUE verrà, a breve, reso facoltativo.
