### ISSUE TITLE
[BLK] [Maggioli] FVOE: dati di test per sviluppo e test

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#754]
Buongiorno,
le api dei servizi FVOE non sono al momento fruibili.
A prescindere dall'operazione richiesta-accesso-fvoe che da errore 401 sistematicamente (vedi [issue 753](https://github.com/anticorruzione/npa/issues/753)) serve poi poter eseguire le altre operazioni con dei dati di test verosimili.
Vedo che anche che le tipologie di documento non sono definite (o meglio, non sono coerenti agli use case FVOE).

Si tratta di un servizio per il quale vi è obbligo di certificazione, sia per la fase di aggiudicazione che di esecuzione.

Vorremo avere indicazioni sulla disponibilità reale del servizio per capire se sia fattibile integrarlo nei tempi rimasti, oppure più sensatamente una deroga.

Grazie

**Comment by supportoAnac** [comment]
Superata da versioni successive. Qualora  si presentassero altre problematiche utilizzando l'ultima versione disponibile dei servizi [1.0.2](https://github.com/anticorruzione/npa/releases/tag/v.1.0.2), si prega di aprire una nuova segnalazione.
