### ISSUE TITLE
[Consip] Richiesta inserimento valore in Tipologica RuoloOE

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#758]
Nella tipologica RuoloOE sono presenti i tipo ruoli “Mandataria” e “Mandante”, che non consentono di classificare il Ruolo del soggetto incaricato della prestazione in caso di un’impresa singola, essendo il parametro obbligatorio si richiede di inserire il tipo “Impresa Singola”

**Comment by paolo-urbanetto** [comment]
Salve, mi associo e ricordo che dal GdL era emersa anche la necessità di estendere ruoloOE per gestire le imprese ausiliarie

**Comment by supportoAnac** [comment]
La segnalazione è corretta. Va aggiornata la tipologica con ruoli ulteriori rispetto al solo RTI per i concorrenti composti da più OE. Tale attività è prevista ma non ancora effettuata.
