### ISSUE TITLE
[BLK] [CONSIP] - FVOE - Errore chiamata Richiesta Accesso

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#759]
di seguito l'errore che abbiamo ricevuto nella chiamata al servizio
/richiesta-accesso-fvoe

Response{protocol=http/1.1, code=401, message=Unauthorized, url=[https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiesta-accesso-fvoe](https://urldefense.com/v3/__https:/apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiesta-accesso-fvoe__;!!OrxsNty6D4my!7Ru1WHHm_fyvAm3LmtqKzKpaYu4thjHsPViNwaC4xDABSvwTRJ-ijY5HdK_2WdItrA2IBhpzZDnyGfDIUGR7-MSwLIgKPx7S$)}

GovWay-Message-ID: 9c9434fb-38be-44a8-91ac-f7c44b3b760d

GovWay-Transaction-ID: 86130520-8e08-11ee-b4a0-0050568e08b3

**Comment by EngineeringEProc** [comment]
Appena riprovato con i seguenti dati. confermo errore 401
Request
https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiesta-accesso-fvoe
Response
GovWay-Message-ID
eac46b1f-cc30-4aa1-89de-6fa372b7cddb

GovWay-Transaction-ErrorType
InteroperabilityInvalidRequest

GovWay-Transaction-ID
475ca9ba-8f73-11ee-a061-0050568e9679

**Comment by supportoAnac** [comment]
L’appalto risulta non pubblicato, quindi l’accesso a FVOE non è possibile.
