### ISSUE TITLE
[BLK] Scheda A2_29 - ERR45 al pubblica avviso

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#761]
Abbiamo creato e confermato regolarmente una P2_10, la successiva S2 e la A2_29. Per quest'ultima, viene generato un avviso la cui pubblicazione restituisce: ERR45 "avviso non ammesso in questa fase dell'appalto".

idAppalto: 5590ea02-e785-4143-bda4-068e8fbeba5c
idAvviso: 48a3e661-c3e8-4869-b692-0732754c90fe

stato appalto: PUBB 

govway della chiamata pubblica-avviso:
govway-message-id:879350a0-48e7-48b7-ada2-55ce507b61f5
govway-transaction-id:d5ff78ea-8e88-11ee-a061-0050568e9679

**Comment by mariottiDPA** [comment]
stesso errore per una A2_30.

idAppalto: ac6d4a77-9e74-4bd3-a47b-284d74038062
idAvviso: 4b0716c8-2823-483b-a8f2-f0b509679fe0

govway della chiamata pubblica-avviso:
govway-message-id:c1ba285e-bb6a-406d-9a44-d94f8c461082
govway-transaction-id:b6ad615a-8e8e-11ee-b4a0-0050568e08b3

**Comment by mpizziconi** [comment]
la pubblicazione degli avvisi di post informazione è avviata automaticamente dalla piattaforma, è richiesta esplicitamente solo per le schede di indizione.

ps
i due appalti citati sono stati passati allo stato successivo
