### ISSUE TITLE
[BLK] Scheda A7.1.2 - ERR9999 al crea-scheda

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#763]
La creazione di una A7_1_2 dà ERR9999 al crea-scheda.

idAppalto: 9a9ea936-0610-48d8-9642-813329f5641c
CIG: K000038748

stato appalto: PUBB

govway della chiamata crea-scheda:
govway-message-id:9591441d-10b8-413f-b944-ca98591300d4
govway-transaction-id:77c08af6-8ea1-11ee-a061-0050568e9679

**Comment by mariottiDPA** [comment]
di seguito il payload inviato:
`{
    "idAppalto": "9a9ea936-0610-48d8-9642-813329f5641c",
    "scheda": {
        "codice": {
            "idTipologica": "codiceScheda",
            "codice": "A7_1_2"
        },
        "versione": "1.0",
        "body": {
            "anacForm": {
                "appalto": {
                    "motivoUrgenza": {
                        "idTipologica": "motivoUrgenza",
                        "codice": "7"
                    },
                    "linkDocumenti": "https:\/\/digitalpa.it",
                    "datiBaseProcedura": {
                        "tipoProcedura": {
                            "idTipologica": "tipoProcedura",
                            "codice": "neg-wo-call"
                        }
                    }
                },
                "aggiudicazioni": [
                    {
                        "cig": "K000038748",
                        "afferenteInvestimentiPNRR": false,
                        "acquisizioneCup": false,
                        "quadroEconomicoStandard": {
                            "impForniture": 5000,
                            "sommeOpzioniRinnovi": 0,
                            "sommeRipetizioni": 0,
                            "sommeADisposizione": 5000
                        },
                        "partecipanti": [
                            {
                                "codiceFiscale": "03553050927",
                                "denominazione": "DigitalPA",
                                "ruoloOE": {
                                    "idTipologica": "ruoloOE",
                                    "codice": "1"
                                },
                                "tipoOE": {
                                    "idTipologica": "tipoOE",
                                    "codice": "1"
                                },
                                "idPartecipante": "d0aa1595-cf34-4726-bee2-d403b61adb6a",
                                "paeseOperatoreEconomico": "ITALIA",
                                "avvalimento": false,
                                "importo": 4500
                            }
                        ]
                    }
                ]
            }
        }
    }
}`

@mpizziconi

**Comment by mariottiDPA** [comment]
di seguito il payload inviato @mpizziconi 
```
{
    "idAppalto": "9a9ea936-0610-48d8-9642-813329f5641c",
    "scheda": {
        "codice": {
            "idTipologica": "codiceScheda",
            "codice": "A7_1_2"
        },
        "versione": "1.0",
        "body": {
            "anacForm": {
                "appalto": {
                    "motivoUrgenza": {
                        "idTipologica": "motivoUrgenza",
                        "codice": "7"
                    },
                    "linkDocumenti": "https:\/\/digitalpa.it",
                    "datiBaseProcedura": {
                        "tipoProcedura": {
                            "idTipologica": "tipoProcedura",
                            "codice": "neg-wo-call"
                        }
                    }
                },
                "aggiudicazioni": [
                    {
                        "cig": "K000038748",
                        "afferenteInvestimentiPNRR": false,
                        "acquisizioneCup": false,
                        "quadroEconomicoStandard": {
                            "impForniture": 5000,
                            "sommeOpzioniRinnovi": 0,
                            "sommeRipetizioni": 0,
                            "sommeADisposizione": 5000
                        },
                        "partecipanti": [
                            {
                                "codiceFiscale": "03553050927",
                                "denominazione": "DigitalPA",
                                "ruoloOE": {
                                    "idTipologica": "ruoloOE",
                                    "codice": "1"
                                },
                                "tipoOE": {
                                    "idTipologica": "tipoOE",
                                    "codice": "1"
                                },
                                "idPartecipante": "d0aa1595-cf34-4726-bee2-d403b61adb6a",
                                "paeseOperatoreEconomico": "ITALIA",
                                "avvalimento": false,
                                "importo": 4500
                            }
                        ]
                    }
                ]
            }
        }
    }
}
```

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
