### ISSUE TITLE
Scheda RIPRESA  RI1 - Ripresa Prestazione - campo: superatoTempo

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#766]
Nella scheda RI1 - Ripresa Prestazione c'è li campo
superatoTempo:
          description: E’ stato superato il quarto del tempo contrattuale
          type: boolean  

Si può valorizzare a true senza aver spedito la scheda dedicata: "Superamento del quarto del tempo  contrattuale"	SQ1

**Comment by supportoAnac** [comment]
Si ringrazia della segnalazione, attualmente non c'è un controllo sul campo indicato.
