### ISSUE TITLE
[BLK] [CONSIP] Scheda A1_32 - Richiesta pubblicazione appalti 

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#767]
Si prega di far avanzare i seguenti appalti di tipo A1_32:

- c346a7c9-516f-4518-b999-dcfeb9e2fc62
- 66ec6e2b-7a5a-49f7-b8e8-007448182d1e

per verificare le schede SC1 e M1.40

**Comment by mpizziconi** [comment]
Le procedure sono state avanzate ad esito della pubblicazione da parte del TED
