### ISSUE TITLE
Servizio PDND (recupera-elenco-tipologiche) - Codelist 400

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#769]
Salve,

sto provando a chiamare, seguendo la procedura [qui riportata](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#il-flusso-in-dettaglio), il servizio /recupera-elenco-tipologiche ma ottengo il seguente:

```
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "b9a4630d-8ebf-11ee-a061-0050568e9679"
}
```

Otteniamo correttamente il token, decodificandolo lo sha256 è corretto e l'audience è effettivamente quella del servizio CodeList.

Dove sbagliamo? 

Il JWS è creato partendo da questa [definizione](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-jws/jws.yaml).

**Comment by rossanoros** [comment]
Ciao, sarebbe possibile avere un supporto da qualcuno? Siamo bloccati negli sviluppi.

**Comment by rossanoros** [comment]
Ultimo aggiornamento: 
{
  type: 'https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html',
  title: 'InteroperabilityInvalidRequest',
  status: 400,
  detail: 'Received request is not conform to the required interoperability profile',
  govway_id: '8ecc2c25-9425-11ee-a061-0050568e9679'
}

**Comment by FedericaSicchiero** [comment]
Buongiorno, avete provato ad usare il tool di debug del voucher presente all'interno di interoperabilità? Dovrebbe aiutarvi a capire come mai ricevete quell'errore

**Comment by masko82** [comment]
> Buongiorno, se puo' essere di aiuto, #751
> 
> Noi abbiamo risolto e chiuso la issue.
> 
> Saluti

Buonasera @ddisante , abbiamo il tuo stesso problema. Abbiamo provato seguendo i consigli indicati nella vostra soluzione ma continuiamo ad avere lo stesso problema. 
Ho anche aperto un issue [qui](https://github.com/anticorruzione/npa/issues/978). 
Sapresti darmi maggiori indicazioni in merito alla vostra soluzione?

Grazie mille
