### ISSUE TITLE
Schede successive alla P6_2

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#773]
Premesso quanto esposto alla #732: "L’adesione con successivo confronto competitivo di una stazione appaltante all’accordo quadro deve essere comunicata la scheda P6_2 indicando il CIG del precedente AQ nel campo cigAccordoQuadro.", chiedo se dopo l'invio della scheda P6_2, e il successivo invio della S2 (tracciata come successiva nell'orchestratore), occorrerà inviare altre schede per trasmettere i dati dell'aggiudicazione.

In caso affermativo potete indicarmi quali sono queste schede.

Grazie

**Comment by paolo-urbanetto** [comment]
Buongiorno, mi aggiungo e sollecito riscontro. Grazie

**Comment by ffinpaa** [comment]
Ciao Paolo, mi è stato risposto che le schede successive sono quelle "classiche" di aggiudicazione. Ad esempio A1_29 e A2_29

**Comment by paolo-urbanetto** [comment]
Grazie
