### ISSUE TITLE
[BLK][TOSCANA/BOLZANO] Scheda P2_20 - ERROR 9999 DURANTE CREA-APPALTO

### ISSUE THREAD

**Issue by user6330** [anticorruzione/npa#775]
Come per la #774 ,

riscontriamo lo stesso errore per la P2_20

[JsonP2_20.txt](https://github.com/anticorruzione/npa/files/13503419/JsonP2_20.txt)

**Comment by user6330** [comment]
Riprovato anche stamattina 30/11/2023.

{
  "instance": null,
  "status": 500,
  "title": "KO",
  "detail": "Errore Generico",
  "type": "about:blank",
  "errori": [
    {
      "idTipologica": "errori",
      "codice": "ERR9999",
      "dettaglio": null
    }
  ]
}
Qui il payload della chiamata
[input.json](https://github.com/anticorruzione/npa/files/13510587/input.json)

Qui l'header della chiamata
[header.txt](https://github.com/anticorruzione/npa/files/13510589/header.txt)

**Comment by supportoAnac** [comment]
Risolta con il rilascio del 01/12/2023.
