### ISSUE TITLE
[Consip] Scheda RSU1 - Richiesta chiarimenti

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#778]
Nella scheda RSU1, in caso di richiesta di subappalto inviata da RTI o consorzi stabili (molteplicità di soggetti giuridici), chiediamo chiarimenti su come inviare più DGUE per l’attivazione di controlli sulle società che presentano richiesta di autorizzazione di subappalto.

**Comment by anac-uscp** [comment]
<p>Non è necessario il DGUE per l'esecuzione dei controlli</p>
