### ISSUE TITLE
[CONSIP][BLK] Scheda P1.16 - Esito KO operazione conferma-appalto  

### ISSUE THREAD

**Issue by labruno** [anticorruzione/npa#780]
Si chiedono cortesemente razionali per gli errori riscontrati in risposta alla chiamata di conferma appalto per i dati di riferimento successivi.
La scheda P1.16  non risulta confermata con in risposta gli errori di 

**- ERR36** "il body della scheda non è valorizzato"
**- ERR29** "idScheda obbligatorio"

serviziComuni/esito-operazione idAppalto=**d27a8ade-37f1-459f-b6b5-6b9565f0fe43**&tipoOperazione=AP_CONF&tipoRicerca=ULTIMO_ESITO

HEADER:
[Server:"nginx", Date:"Wed, 29 Nov 2023 22:02:41 GMT", Content-Type:"application/json", Transfer-Encoding:"chunked", Connection:"keep-alive", cache-control:"private", set-cookie:"48660c0d09a5bc00d558af703a720b6f=7dd91a38c7b93649d47f6ea8f2622733; path=/; HttpOnly; Secure; SameSite=None", x-xss-protection:"1; mode=block", **GovWay-Message-ID:"dbe28ae3-b2c2-4f5b-a2fb-6926382e2879"**, x-frame-options:"DENY", **GovWay-Transaction-ID:"f806068b-8ef5-11ee-b4a0-0050568e08b3**", vary:"Access-Control-Request-Headers", "Access-Control-Request-Method", "Origin", x-content-type-options:"nosniff", strict-transport-security:"max-age=31536000 ; includeSubDomains", "max-age=63072000"]

BODY:
{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"d27a8ade-37f1-459f-b6b5-6b9565f0fe43","**idScheda":"3749eb18-5065-4c6a-a14c-c322d5411e53**","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AP_CONF"},"dataControllo":"2023-11-29T21:56:37.041+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AP_N_CONF"},"errori":[**{"idTipologica":"errori","dettaglio":"","codice":"REG29"},{"idTipologica":"errori","dettaglio":"","codice":"REG36"**}]}]}

**Comment by supportoAnac** [comment]
Gli errori indicati non sono ERR36 e ERR29, bensì REG36 e REG29.
L'ultimo esito di conferma-appalto riporta l’errore  REG29 (e non ERR29) - Il campo modalitaAcquisizione è obbligatorio se l'oggetto del contratto è Servizi o Forniture, e REG36 - Non è stato indicato il valore dell’importo componente forniture.
L’errore segnalato è corretto perché nell'eForm il campo oggettoContratto è forniture ma nel json non sono stati indicati.
