### ISSUE TITLE
[BLK]-CONSIP-FVOE-Errore chiamata Verifica Accesso-Errore 401

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#781]
con questa request

https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/verifica-richiesta-accesso-fvoe?codiceFiscale=5359681003&idAppalto=1a11bdfc-1bbb-42e4-96da-e695a176863b

Ottengo questa response
GovWay-Message-ID 7033cae4-8165-454d-b11a-3084644db1da GovWay-Transaction-ID c4d1adff-8f52-11ee-a061-0050568e9679

**Comment by supportoAnac** [comment]
La problematica è risolta.
