### ISSUE TITLE
[BUG] consulta-rendering-avviso ERR9999

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#783]
L'api consulta-rendering-avviso da ERR9999 con
idAppalto=397972d6-2e40-421b-8535-438e8c55b108
idAvviso=df0c35f6-1aed-4dbd-b630-28577ffbd77d

Il consulta-avviso restituisce i dati corretti.

Si può sistemare?

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
