### ISSUE TITLE
[BLK] [Consip] Scheda M1 - Errore9999

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#784]
HTTP response code: 400
HTTP response body: {"status":400,"title":"KO","detail":"SC_N_VERIF","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}

govway-message-id=[b139c9e9-2918-4997-93e6-081b2610bd58], 
govway-transaction-id=[b17c4e6e-8ec1-11ee-b4a0-0050568e08b3],

**Comment by supportoAnac** [comment]
Si chiede gentilmente di specificare il payload della scheda M1 in esame e la tipologia di scheda precedentemente validata.

**Comment by cmauriello** [comment]
REQUEST CREA M1
{
  "idAppalto" : "c88f5cb1-65ee-4ab4-ae35-d9e55e926697",
  "scheda" : {
    "body" : {
      "anacForm" : {
        "idContratto" : "92a2bae9-9b19-454d-a7c4-57942a8bb80f",
        "modificaContrattuale" : {
          "dataApprovazione" : 1700816400000,
          "urlDocumentazione" : null,
          "motivoRevisionePrezzi" : {
            "idTipologica" : "motivoRevisionePrezzi",
            "codice" : "5"
          },
          "cigNuovaProcedura" : null,
          "quadroEconomicoStandardRideterminato" : {
            "impLavori" : null,
            "impServizi" : null,
            "impForniture" : null,
            "impTotaleSicurezza" : null,
            "impProgettazione" : null,
            "ulterioriSommeNoRibasso" : null,
            "sommeADisposizione" : null,
            "numGiorniProroga" : null
          }
        }
      },
"
    },
    "idScheda" : null,
    "codice" : {
      "idTipologica" : "codiceScheda",
      "codice" : "M1"
    },
    "versione" : "1.0",
    "stato" : null,
    "dataCreazione" : null
  }
}
 
 
RESPONSE CREA M1
{
  "idScheda" : "4fe25cf7-6d9c-4b0f-9926-fa046046a7b3",
  "instance" : null,
  "status" : 200,
  "title" : "Operazione Effettuata",
  "detail" : "Creazione eseguita con successo",
  "type" : "about:blank"
}
 
 
request verifica M1
{"idScheda":"4fe25cf7-6d9c-4b0f-9926-fa046046a7b3","idAppalto":"c88f5cb1-65ee-4ab4-ae35-d9e55e926697"}
 
response verifica M1
{"status":400,"title":"KO","detail":"SC_N_VERIF","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}

govway-message-id=[b139c9e9-2918-4997-93e6-081b2610bd58], 
govway-transaction-id=[b17c4e6e-8ec1-11ee-b4a0-0050568e08b3],

**Comment by cmauriello** [comment]
Problema risolto
