### ISSUE TITLE
Schede A1_29 A1_33 - Richiesta chiarimenti

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#788]
Nelle schede di aggiudicazione dalla A1_29 alla A1_33 è previsto l’inserimento delle relative schede eform (obbligatorio). In queste schede risulta essere obbligatorio il campo BT-150 che corrisponde all’identificativo del contratto; quindi, se ne deduce che queste schede di aggiudicazione possano essere inviate solamente a valle della stipula del contratto (che potrebbe avvenire con un importante delay temporale o non concretizzarsi) e non contestualmente all’aggiudicazione.

Si richiedono chiarimenti o conferma di quanto espresso

**Comment by supportoAnac** [comment]
Issue trattata nell’ultima riunione con le piattaforme: le schede di aggiudicazione vengono inviate quando sono note tutte le informazioni che contengono.

**Comment by anac-uscp** [comment]
Ad integrazione della precedente risposta:
ai sensi dell'art. 111 del codice l'avviso sui risultati della procedura di aggiudicazione deve essere trasmesso entro trenta giorni dalla conclusione del contratto o dalla conclusione dell'accordo quadro, pertanto l'aggiudicazione deve essere trasmessa quando sono noti i dati della stipula del contratto.

**Comment by anac-uscp** [comment]
Ad integrazione della precedente risposta:
ai sensi dell'art. 111 del codice l'avviso sui risultati della procedura di aggiudicazione deve essere trasmesso entro trenta giorni dalla conclusione del contratto o dalla conclusione dell'accordo quadro, pertanto l'aggiudicazione deve essere trasmessa quando sono noti i dati della stipula del contratto.
