### ISSUE TITLE
[Riapertura issue 371] Scheda SC1 - Richiesta rettifica invio

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#789]
Riapriamo la issue 371 https://github.com/anticorruzione/npa/issues/371, riteniamo che la richiesta sia ben posta, chiediamo la possibilità di poter rettificare l’invio della scheda SC1 considerando il tipo si informazioni da inserire e la relativa probabilità di trascrivere informazioni sbagliate.

Per comodità riporto il testo della issue 371 chiusa: Si richiede di poter rettificare l’invio della scheda SC1 in considerazione della complessità dei contratti gestiti. Sono stati rilevati spesso casi di errata imputazione nella trasposizione dei valori dai documenti al sistema, per cui risulta necessario intervenire con delle rettifiche.

**Comment by anac-uscp** [comment]
<p>Per poter fornire una risposta esaustiva si chiede di fornire tutti idettagli del caso specifico, ad es. flusso seguito, chiari motivi della richiesta di rettifica della scheda.</p>
