### ISSUE TITLE
[BLK]-CONSIP-FVOE-Recupera documento fvoe -Errore 500

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#791]
Abbiamo testato i servizi anche in mancanza dei servizi precedenti che vanno in 401. di seguito i risultati
Response{protocol=http/1.1, code=500, message=Internal Server Error, url=https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/recupera-documento-fvoe?idDocumento=507f1f77bcf86cd799439011} 

Server: nginx 

Date: Thu, 30 Nov 2023 14:18:57 GMT 

Content-Type: application/json 

Transfer-Encoding: chunked 

Connection: keep-alive 

cache-control: private 

set-cookie: c08731b3614a016fdf8e25f403f6f286=164fbde547495f73fd0ed2854b283541; path=/; HttpOnly; Secure; SameSite=None 

x-xss-protection: 1; mode=block 

GovWay-Message-ID: b469a2f6-eed1-498e-8607-814e84796736 

x-frame-options: DENY 

GovWay-Transaction-ID: 3fcc582c-8f86-11ee-b4a0-0050568e08b3 

vary: Access-Control-Request-Headers 

vary: Access-Control-Request-Method 

vary: Origin 

x-content-type-options: nosniff 

strict-transport-security: max-age=31536000 ; includeSubDomains 

Strict-Transport-Security: max-age=63072000 

OkHttp-Sent-Millis: 1701353934860 

OkHttp-Received-Millis: 1701353937053

**Comment by r-dm123** [comment]
Issue rientrata
