### ISSUE TITLE
[BLK]-CONSIP-FVOE-Richiedi documento - Errore 400 

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#792]
Response{protocol=http/1.1, code=400, message=Bad Request, url=https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiedi-documento?chiaveAccesso=key&tipoDocumento=type&codiceFiscaleSoggetti=cf} 

Server: nginx 

Date: Thu, 30 Nov 2023 14:26:32 GMT 

Content-Type: application/json 

Transfer-Encoding: chunked 

Connection: keep-alive 

cache-control: private 

set-cookie: c08731b3614a016fdf8e25f403f6f286=164fbde547495f73fd0ed2854b283541; path=/; HttpOnly; Secure; SameSite=None 

x-xss-protection: 1; mode=block 

GovWay-Message-ID: d55a41af-fb6f-4131-a53a-ec814f2140fa 

x-frame-options: DENY 

GovWay-Transaction-ID: 137ba10d-8f87-11ee-a061-0050568e9679 

vary: Access-Control-Request-Headers 

vary: Access-Control-Request-Method 

vary: Origin 

x-content-type-options: nosniff 

strict-transport-security: max-age=31536000 ; includeSubDomains 

Strict-Transport-Security: max-age=63072000 

OkHttp-Sent-Millis: 1701354392245 

OkHttp-Received-Millis: 1701354392383

**Comment by r-dm123** [comment]
Issue rientrata
