### ISSUE TITLE
[BLK]-CONSIP-FVOE-verifica-stato-richiesta-documento -errore 404

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#793]
Response{protocol=http/1.1, code=404, message=Not Found, url=https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/verifica-stato-richiesta-documento?idRichiesta=fbd2bc6e-b913-4727-a1b7-e2a3a6862633} 

Server: nginx 

Date: Thu, 30 Nov 2023 14:28:48 GMT 

Content-Type: application/json 

Transfer-Encoding: chunked 

Connection: keep-alive 

cache-control: private 

set-cookie: c08731b3614a016fdf8e25f403f6f286=164fbde547495f73fd0ed2854b283541; path=/; HttpOnly; Secure; SameSite=None 

x-xss-protection: 1; mode=block 

GovWay-Message-ID: b54d4584-1a9a-410e-8d29-e1ddb071ec06 

x-frame-options: DENY 

GovWay-Transaction-ID: 4ce11429-8f87-11ee-b4a0-0050568e08b3 

vary: Access-Control-Request-Headers 

vary: Access-Control-Request-Method 

vary: Origin 

x-content-type-options: nosniff 

strict-transport-security: max-age=31536000 ; includeSubDomains 

Strict-Transport-Security: max-age=63072000 

OkHttp-Sent-Millis: 1701354524995 

OkHttp-Received-Millis: 1701354528239

**Comment by r-dm123** [comment]
Issue rientrata
