### ISSUE TITLE
[Riapertura issue 372] Richiesta rettifica invio della scheda I1

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#794]
Riapriamo la issue 372 https://github.com/anticorruzione/npa/issues/372, riteniamo che essendo PCP progettato per interoperare con piattaforme di gestione è da prevedere il caso di errata interpretazione da parte del DDE e dunque possibilità di poter rettificare a posteriori in caso di primo invio errato.

Per comodità riporto il testo della issue 372 chiusa: Si richiede di poter rettificare l’invio della scheda I1 poiché sono stati spesso rilevati errori sulla data di avvio delle attività, dovuti alle diverse discipline dei contratti e che portano ad interpretazioni non corrette da parte del DDE, per cui risulta necessario intervenire con delle rettifiche.

**Comment by anac-uscp** [comment]
Al momento non è prevista la rettifica per errori. I flussi di rettifica saranno valutati caso per caso. Bisognerà procedere ad una rettifica formale.
