### ISSUE TITLE
[Riapertura issue 373] Richiesta rettifica invio della scheda RSU1

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#795]
Riapriamo la issue 373  https://github.com/anticorruzione/npa/issues/373, riteniamo che essendo PCP progettato per interoperare con piattaforme di gestione è da prevedere il caso di errata interpretazione da parte dell'utente che inserisce i dati e dunque possibilità di poter rettificare a posteriori in caso di primo invio errato.

Per comodità riporto il testo della issue 373 chiusa: Si richiede di poter rettificare l’invio della scheda RSU1 poiché esistono processi interni che prevedono la sottoscrizione di un atto formale, denominato "Provvedimento di rettifica", per cui è necessario intervenire con le rettifiche che potrebbero interessare tutti i campi previsti nella scheda RSU1.

**Comment by anac-uscp** [comment]
<p>Non esiste il servizio per cancellare schede confermate. La comunicazione di richiesta subappalto che arriva non può essere diversa da quella presentata dall'operatore economico alla PAD.</p>

<p>Il caso specifico che denota una non digitalizzazione della fase di esecuzione può essere gestito comunicando l'esito negativo del subappalto e ritrasmettendo la scheda corretta</p>
