### ISSUE TITLE
Scheda A3_6 - Gestione Affidamenti diretti in house

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#796]
Salve,
analizzando le schede relative agli AD, è emerso che il campo "datiBaseRisultatoProcedura" : 
- description (Dato in comune con il Business Group Procedure Lot Result delle eforms)
- esitoProcedura* > description (sito procedura - corrisponde al campo bt-142 - Winner Chosen del TED - fare riferimento ai valori contenuti nel file  esitoProcedura.json)

è presente **SOLO** nella scheda A3_6. Si tratta di un refuso?

**Comment by supportoAnac** [comment]
Verrà aggiornato al primo rilascio utile, che non avverrà prima dell’esercizio della piattaforma.
