### ISSUE TITLE
[CONSIP] Utilizzo del campo saTitolare per elenco stazioni appaltanti in relazione al RP.

### ISSUE THREAD

**Issue by labruno** [anticorruzione/npa#798]
Si richiedono, cortesemente, chiarimenti in merito all'utilizzo del flag **_saTitolare_** di una stazione appaltente in elenco delle **_stazioniAppaltanti_** di una scheda di indizione in relazione al **_SAcodiceAUSA_** associato  all'RP per il JWS.

Un RP autorizzato per una scheda di indizione con più stazioniAppaltanti deve per forza possedere SAcodiceAUSA  ( claims JWS ) di valore pari a quello del codiceAusa della stazione appaltante con _saTitolare_ = true ?
In elenco stazioniAppaltanti possono esserci più stazioni appalatanti con _saTitolare_ = true ?

Un RP deve possedere uno specifico valore SAcodiceAUSA  o può essere uno qualunque tra i valori di codiceAusa delle stazioni appaltanti in elenco? 

![image](https://github.com/anticorruzione/npa/assets/48831012/44e5bf7c-01ff-4297-9e33-b3ae783b7d82)

**Comment by r-dm123** [comment]
#
di seguito le risposte puntuali ai tre quesiti posti:

1. NO
2. SI
3. Uno qualsiasi
