### ISSUE TITLE
Modifiche appalto post pubblicazione

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#8]
L'appalto può subire modifiche (ed in caso quali sono gestite) in fase successiva alla pubblicazione o all'aggiudicazione. In questo momento il flusso NPA non permette modifiche all'oggetto appalto: se questa assunzione viene confermata bisognerà chiarire come gestire le modifiche post pubblicazione e post aggiudicazione.

**Comment by supportoAnac** [comment]
1. Prima del confermaAppalto il servizio modifica-appalto permette la sostituzione della precedente istanza dell’Appalto in lavorazione.
2. Dopo il confermaAppalto e prima del pubblicaAvviso non è possibile effettuare modifiche.  Eventualmente è permessa solo la cancellazione.
3. Dopo il confermaAppalto e dopo il pubblicaAvviso è possibile inviare un avviso di modifica (modifica-avviso) se la richiesta di pubblicazione non è ancora avvenuta. In questa fase è permessa anche la modifica dei lotti. Invece, se la pubblicazione è già avvenuta è possibile solo inviare un avviso di rettifica (rettifica-avviso) con le sole informazioni rettificabili.
