### ISSUE TITLE
[BLK] [CONSIP] Pubblicazione Avviso - ERR64

### ISSUE THREAD

**Issue by labruno** [anticorruzione/npa#803]
Si chiede di fornire dettagli per l'errore. L'avviso non è stato pubblicato su TED.
Inoltre  : Non si sarebbe dovuta ricevere questa informazione alla fase di conferma appalto?
E' possibile procedere alla modifca del eform e riprovare la pubblicazione  ?   ( si ha evidenza che il cambio dell'efrom possa avvenire solo in relazione alla versione e non più la il noticeid )

GovWay-Message-ID
[3fc20844-8f69-4fd4-86a8-56e90e18b447]

GovWay-Transaction-ID
[a1fac39d-903b-11ee-a061-0050568e9679]

idAppalto=d27a8ade-37f1-459f-b6b5-6b9565f0fe43&tipoOperazione=AV_PUBB&tipoRicerca=ULTIMO_ESITO

ERR64 - [400] during [POST] to [http://pcp-qlf-ted-ms.pcp-qlf.svc:8080/submit?language=it&authorEmail=ufficio.uscp%40anticorruzione.it] [TedMsClient#submit(String,String,String)]: [{"code":400,"status":"400 BAD_REQUEST","title":"Error","detail":"{\"code\":\"notice.NOTICE_IMPORT_VALUE_EXCEPTION\",\"message\":\"A notice with the same id and version id already exists.\",\"showDetails\":true}","links":null}]

**Comment by lauralu1993** [comment]
Salve, mi riaggancio. 
dopo aver ottenuto l'errore "A notice with the same id and version id already exists" abbiamo provato 2 strade:
1) chiamare modifica-avviso sottomettendo lo stesso identico eform; otteniamo l'errore **operazione non consentita: la version-id dell'eForm coincide con quella inviata in precedenza**
2) chiamare modifica-avviso sottomettendo un nuovo eform; otteniamo l'errore **operazione non consentita: la notice-id dell'eForm non coincide con quella inviata in precedenza**

come si esce da questo scenario limite considerando che ci si ritrova con questo errore solo dopo aver richiesto e ottenuto i CIG?
Grazie
@labruno
