### ISSUE TITLE
Codifica CIG rilasciati da PCP

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#805]
Che codifica avranno in ambiente di esercizio i CIG rilasciati da PCP? Esiste un modo per distinguerli da quelli staccati da SIMOG?

**Comment by lelio-raffaelli** [comment]
Credo che la risposta sia abbastanza semplice, ed in questa fase ci agevolerebbe gli sviluppi. Chiedo cortesemente un riscontro

**Comment by supportoAnac** [comment]
Vedere https://github.com/anticorruzione/npa/issues/764

**Comment by lelio-raffaelli** [comment]
Questa issue non ha attinenza con la @764, bensì riguarda la codifica dei CIG.
Pertanto la riapro
