### ISSUE TITLE
[Consip] schede di aggiudicazione A1.* (ad es. A1_29) in stato "CONF" - impossibile inviare le schede successive

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#810]
inviando e confermando le schede di aggiudicazione A1.*, queste passano subito nello stato "CONF" (confermato), analogamente a quanto avviene per le altre schede di post-pubblicazione. 
Tuttavia, nonostante le schede di aggiudicazione versino in questo stato, non risulta possibile inviare le schede successive (es. SC1) perché di fatto la pubblicazione dell’avviso di aggiudicazione è ancora sospesa in attesa della risposta del TED (ERR2 - scheda non ammessa in questa fase dell'appalto).
la tipologica statoScheda non sembra restituire uno stato appropriato (otteniamo CONF laddove invece dobbiamo ancora restare in attesa).
E' possibile prevedere l'aggiunta di uno stato opportuto per questo scenario? oppure dovremmo essere noi a verificare l'esito della pubblicazione dell'avviso - tramite il servizio ESITO-OPERAZIONE e tipo operazione AV_PUBB - sebbene non siamo noi a eseguire direttamente la pubblicazione?
Grazie

**Comment by lauralu1993** [comment]
@labruno

**Comment by supportoAnac** [comment]
La richiesta sarà presa in considerazione per le prossime evoluzioni dei servizi.
