### ISSUE TITLE
[Consip][BLK] - errore 400 su RETTIFICA-AVVISO

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#811]
abbiamo provato a invocare il servizio RETTIFICA-AVVISO per un appalto in stato PUBBLICATO.
ma otteniamo l'errore
{"status":400,"title":"KO","detail":"AV_N_RETT","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}"

**idAppalto = 48c5b881-5ee0-453c-9bf8-86c03de95132
GovWay-Message-ID:"994b5f51-b82d-47d4-baef-25d96d41a538"
GovWay-Transaction-ID:"354723f4-91ca-11ee-a061-0050568e9679"**

[P1.10-RETTIFICA.json](https://github.com/anticorruzione/npa/files/13538826/P1.10-RETTIFICA.json)

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
