### ISSUE TITLE
[BLKl] [Consip] Richiesta autorizzazione da parte dell’operatore economico tramite ANAC per accesso FVOE

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#813]
È stato effettuato con successo una richiesta di accesso al fvoe (tramite l’endpoiint /richiesta-accesso-fvoe) con restituzione id richiesta: 50029f42-5a60-4b4d-85a4-b248fb230b37

Per proseguire l’attività è necessaria l’autorizzazione rilasciata dall’operatore economico tramite apposita interfaccia ANAC che risponde all’endpoint ad uso interno /autorizza-accesso-fvoe a cui non è possibile accedere

Si richiede: 
-	l’autorizzazione da parte dell’operatore economico tramite ANAC
-	L’inserimento di qualche documento di demo per continuare tutte le attività da noi previste.
Di seguito le informazioni della richiesta
request di richiesta autorizzazione:
{
"dataInizioAutorizzazione": "2023-11-01T12:00:00Z",
"dataFineAutorizzazione": "2030-11-01T12:00:00Z",
"operatoriEconomici": [
{
"codiceFiscale": "13454210157"
}
],
"appalto": {
"idAppalto": "0bf19992-3dce-4018-8bf4-ae26b5636704"
}
}
 
inviata dal RUP: MAIPTL83R03L628F

**Comment by supportoAnac** [comment]
Lo scenario di test sarà reso noto alle piattaforme a breve.
