### ISSUE TITLE
Aggiornamento orchestratore colonna "Settore-Regime"

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#814]
Salve,
con gli ultimi due aggiornamenti relativi al file "orchestratore" sono stati tolti i riferimenti ai regimi, all'interno della colonna C "Settore-regime".

- Si tratta di un refuso?
- Cosa succede per quelle schede con invio al TED per cui un eForm è strettamente legato al regime?
- Quando verrà reso facoltativo il DGUE per gli AD sottosoglia come indicato nell'ultima riunione?

**Comment by r-dm123** [comment]
#Dalla Verifica dell'ultimo orchestratore risultano presenti nella colonna C i regimi ed indicato quando trattasi di Allegerito o ordinario

**Comment by UserM21** [comment]
Ciao,
non mi torna quanto da te descritto, in quanto le schede legate agli eForms sono tutte prive del dettaglio relativo al regime. 
<img width="956" alt="image" src="https://github.com/anticorruzione/npa/assets/144692899/3ed58b5a-3fa7-4965-a177-3119bbaf7733">
