### ISSUE TITLE
[BLK] - Cancella-appalto ERR9999 

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#815]
Salve, 
Stiamo riscontrando il seguente errore al cancella appalto:

Input:
{"idAppalto":"0184c908-f11e-4aa5-977d-577a8b15b111","motivo":null}

questo è il json di risposta:

{"instance":null,"status":400,"title":"KO","detail":"AP_N_CANC","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999","dettaglio":null}]}

**Comment by supportoAnac** [comment]
Si conferma il corretto funzionamento del servizio cancella-appalto, che è stato testato in ambiente di rilascio.
Per la idAppalto indicata risulta la presenza di un avviso di pubblicazione, che non consente la chiamata al servizio.
