### ISSUE TITLE
[BLK] struttura JSON ConsultaAvvisoResponse non conforme a specifiche-servizi-appalto.yaml

### ISSUE THREAD

**Issue by davideorsi-bit** [anticorruzione/npa#817]
Invocando il servizio  pubblicaAvviso ->  **/consulta-avviso**  con idAvviso 8cd27f3e-fae7-4cac-9a2f-c5d86fd24673, GovWay-Message-ID=[6f80fcf8-fa36-42fa-88a0-6a6b3c8e7bcc]   GovWay-Transaction-ID=[2c80c366-9340-11ee-b4a0-0050568e08b3] ottengo la seguente 
Response:
{
	"instance": null,
	"status": 200,
	"title": "OK",
	"detail": "Operazione Effettuata",
	"type": "about:blank",
	"avviso": {
		"idAvviso": "8cd27f3e-fae7-4cac-9a2f-c5d86fd24673",
		"dataCreazione": "2023-12-05T07:29:50.101+00:00",
		"stato": {
			"idTipologica": "statoAvviso",
			"codice": "CREATO"
		},
		"dataControllo": "2023-12-05T07:29:50.101+00:00",
		"azione": {
			"idTipologica": "tipoAzioneAvviso",
			"codice": "AZ_PUBB"
		},
		"datiPubblicazioneEU": {
			"noticeId": "874aa0e4-77e3-4223-8b43-66d1692270c4",
			"versionId": "01",
			"tipo": {
				"idTipologica": "tipoAvviso",
				"codice": "EU"
			},
			"stato": {
				"idTipologica": "statoAvviso",
				"codice": "CREATO"
			},
			"dataControllo": "2023-12-05T07:29:50.106+00:00",
			"dataInoltroPubblicazione": null,
			"dataRicezionePubblicazione": null,
			"dataPubblicazione": null
		},
		"datiPubblicazioneIT": {
			"tipo": {
				"idTipologica": "tipoAvviso",
				"codice": "IT"
			},
			"stato": null,
			"dataControllo": null,
			"dataInoltroPubblicazione": null,
			"dataPubblicazione": null
		},
		**"scheda": {**
			"_idScheda": "80d80aed-eafb-44de-a75b-e920f095ada4",
			"stato": {
				"idTipologica": "statoScheda",
				"codice": "CONF"
			},
			"codice": {
				"idTipologica": "codiceScheda",
				"codice": "P1_16"
			},
			"versione": "1.0",
			"dataCreazione": "2023-12-05T07:29:48.610+00:00",
			"body": {
				"type": "SchedaP116Type",
				"anacForm": {
					"stazioniAppaltanti": [
						{
							"codiceFiscale": "05017630152",
							"codiceAusa": "9000000010",
							"codiceCentroCosto": "f481feb8-2d8f-46be-bb14-a950234559d6",
							"saTitolare": false
						}
					],
					"appalto": {
						"codiceAppalto": "AppaltoP1_16__3_8_12_2023",
						"categorieMerceologiche": [
							{
								"idTipologica": "categorieMerceologiche",
								"codice": "17"
							}
						],
						"motivoUrgenza": {
							"idTipologica": "motivoUrgenza",
							"codice": "7"
						}
					},
					"lotti": [
						{
							"lotIdentifier": "LOT-0001",
							"categorieMerceologiche": [
								{
									"idTipologica": "categorieMerceologiche",
									"codice": "11"
								}
							],
							"contrattiDisposizioniParticolari": {
								"idTipologica": "contrattiDisposizioniParticolari",
								"codice": "1"
							},
							"codIstat": {
								"idTipologica": "codIstat",
								"codice": "3015146"
							},
							"afferenteInvestimentiPNRR": false,
							"finanziamenti": [
								{
									"tipoFinanziamento": {
										"idTipologica": "tipoFinanziamento",
										"codice": "A"
									},
									"importo": 11000.0
								}
							],
							"prestazioniComprese": {
								"idTipologica": "prestazioni",
								"codice": "1"
							},
							"servizioPubblicoLocale": false,
							"ripetizioniEConsegneComplementari": false,
							"lavoroOAcquistoPrevistoInProgrammazione": false,
							"ccnl": "CCNL",
							"opzioniRinnovi": false,
							"categoria": {
								"idTipologica": "categoria",
								"codice": "FB"
							},
							"modalitaAcquisizione": {
								"idTipologica": "modalitaAcquisizione",
								"codice": "1"
							},
							"quadroEconomicoStandard": {
								"impLavori": 2300.0,
								"impServizi": 2000.0,
								"impForniture": 9000.0,
								"sommeADisposizione": 10000.0
							}
						}
					]
				},
				"eform": "",
				"espd": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjxwaXBwbz5waXBwbzwvcGlwcG8+"
			}
		},
		"appalto": {
			"idAppalto": "8226fc01-5d6c-4096-97c5-20ee22ba020c",
			"codiceAppalto": "AppaltoP1_16__3_8_12_2023",
			"oggetto": "Gara per Vincenzo - E16",
			"dataCreazione": "2023-12-05T07:29:48.609+00:00",
			"stato": {
				"idTipologica": "statoAppalto",
				"codice": "CONF"
			}
		}
	}
}

nell'oggetto scheda manca l'attributo "type": 

@JsonTypeInfo(
  use = JsonTypeInfo.Id.NAME,
  include = JsonTypeInfo.As.PROPERTY,
  **property = "type")**
@JsonSubTypes({
  @JsonSubTypes.Type(value = DatiPianoType.class, name = "DatiPianoType"),
  @JsonSubTypes.Type(value = DatiAppaltoType.class, name = "DatiAppaltoType"),
  @JsonSubTypes.Type(value = SchedaPostPubblicazioneType.class, name = "SchedaPostPubblicazioneType")
 come descitto anche nello yaml: 

![image](https://github.com/anticorruzione/npa/assets/88335388/df6d06e6-d1d9-4006-8634-fbd78b7054d1)

e non é possibile quindi deserializzare il JSON rimappandolo sul tipo corretto fra: 
DatiPianoType, DatiAppaltoType e SchedaPostPubblicazioneType.

Chiedo cortesemete di verificare.

@sfala

**Comment by cristiano-perin** [comment]
Buongiorno,

anche noi incontriamo lo stesso problema con il seguente idAvviso:

6c610c52-5e21-48c0-b4e5-f35d3e1a52b9

Allego anche gli uuid govway
govwayMessageId: 27e1f02d-cd37-4f9f-a36b-27c43e3d9a6a
govwayTransactionId: 807b89be-935f-11ee-a061-0050568e9679

**Comment by davideorsi-bit** [comment]
Chiudo dopo chiarimento fornito in call ristretta ARIA ANAC se può servire @cristiano-perin  il tipo oggetto va capito in funzione della sezione scheda -> "codice": {"idTipologica": "codiceScheda","codice": "P1_16"	}, quindi in questo caso DatiAppaltoType.
L'attributo type non viene ritornato anche se sarebbe più comodo per deserializzare con JAVA SpringBoot.
