### ISSUE TITLE
[BLK] Tempistiche Pubblicazione avvisi

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#818]
Salve,
vorremmo cortesemente avere indicazioni sulle tempistiche di pubblicazione degli avvisi Europei e nazionali. 
Da test effettuati, dopo 4 gg lavorativi ancora non riceviamo l'aggiornamento di stato dell'avviso (risulta sempre con stato "in pubblicazione").

Nell'ultima riunione si parlava di fare degli interventi in merito. Ci sono novità a riguardo?

**Comment by r-dm123** [comment]
#Le tempistiche sono indicate dal TED
