### ISSUE TITLE
Appalto istitutivo SDA e appalti specifici - schede da utilizzare

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#819]
Buongiorno, ci si chiede quali siano le schede corrette da utilizzare in sede di:
- istituzione di uno SDA;
- indizione di un appalto specifico su tale SDA.

Se, secondo le indicazioni rinvenienti dalla issue #484 , per l'**istituzione dello SDA** va utilizzata la scheda corrispondente al settore/regime (ad es. P1_16 o P1_20), se ne deduce che si ottiene il CIG già in sede di bando istitutivo (a differenza di oggi, perché al momento dell'istituzione del bando istitutivo viene solo fatta la pubblicazione su TED e non accade nulla su SIMOG).

Al momento dell'**indizione dell'appalto specifico** quindi non si dovrebbe più chiedere il CIG (altrimenti lo si chiederebbe due volte) e quindi in interoperabilità si potrebbe procedere, trattando la procedura come se fosse una procedura a due fasi, con l'invio delle schede :
- _S1 Elenco dei soggetti che hanno manifestato interesse nelle procedure a due fasi_, al momento dell'indizione dell'appalto specifico
- _S2 Elenco offerte ricevute/OE invitati_, alla scadenza del termine di presentazione dell'offerta.

Alla **stipula del contratto/convenzione** infine si dovrebbe infine procedere con l'invio della scheda corrispondente al settore/regime (ad es. A1_29 o A1_33).

In questo caso appare problematico il primo passaggio per il CIG del bando istitutivo che sarebbe di importo molto elevato e senza alcuna relazione coi lotti di aggiudicazione.

In alternativa, 
- la pubblicità del bando istituivo andrebbe fatta a mezzo eNotice2 (senza quindi ottenere un CIG);
- al momento dell'**indizione dell'appalto specifico** si userebbero le schede delle procedure aperte P1_16 o P1_20) ottenendo il CIG;
- alla stipula del contratto/convenzione infine si dovrebbe infine procedere con l'invio della scheda corrispondente al settore/regime (ad es. A1_29 o A1_33).

O ancora:
- la pubblicità del bando istituivo andrebbe fatta a mezzo eNotice2 (e senza quindi ottenere un CIG);
- l'appalto specifico in sé potrebbe esser trattato come una procedura a due fasi utilizzando (vedi anche issue #520).

**Comment by pietropalermoIT** [comment]
Rimane da chiarire il problema del doppio pagamento del CIG, al momento della P1_16, P2_16 etc ed al momento dell'invio della P7_2

**Comment by anac-uscp** [comment]
<p>Per la gestione del Bando Istitutivo dello SDA, sono state previste 2 schede: </p>

<ol start="1">
	<li data-aria-level="1" data-aria-posinset="1" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="1">
	<p>Una scheda (ISDA1) con eForm che prevede anche l’invio al TED (10 ,11 ,16 o 17). Tali eForm contengono uno specifico campo obbligatorio, il BT-766 ‘Sistema dinamico d’acquisizione’ da valorizzare indicando che si tratta di uno SDA. </p>
	</li>
</ol>

<ol start="2">
	<li data-aria-level="1" data-aria-posinset="2" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":2,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="2">
	<p>una scheda solo per la pubblicazione nazionale, (ISDA2) senza invio al TED e quindi senza eForm in cui nell’oggetto ‘DatiBaseStrumentoProcedura’ è necessario indicare obbligatoriamente che si tratta di uno SDA. </p>
	</li>
</ol>

<p>Ciascuna di queste schede (ISDA1 e ISDA2) sarà seguita da una nuova scheda S0 (usata per l’acquisizione dei partecipanti allo SDA) che può prevedere 3 tipi di ‘operazioni’: </p>

<ol start="1">
	<li data-aria-level="1" data-aria-posinset="1" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="3">
	<p>‘Richiesta di iscrizione’: comunicazione degli OE che hanno fatto richiesta di iscrizione e per cui si presume possa servire la verifica dei requisiti; </p>
	</li>
</ol>

<ol start="2">
	<li data-aria-level="1" data-aria-posinset="2" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="3">
	<p>‘Iscritto’: comunicazione degli OE già iscritti; </p>
	</li>
</ol>

<ol start="3">
	<li data-aria-level="1" data-aria-posinset="3" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="3">
	<p>‘cancellato’: comunicazione degli OE che chiedono di essere cancellati dall’elenco; </p>
	</li>
</ol>

<ol start="4">
	<li data-aria-level="1" data-aria-posinset="4" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="3">
	<p>‘variazione’: comunicazione variazione della composizione dell’RTI oppure variazione della ragione sociale; </p>
	</li>
</ol>

<p>Per la terminazione dello SDA sono state previste 2 nuove schede: </p>

<ol start="1">
	<li data-aria-level="1" data-aria-posinset="1" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="4">
	<p>Conclusione SDA con invio al TED (CSDA1) con rispettivo eForm (29, 30); </p>
	</li>
</ol>

<ol start="2">
	<li data-aria-level="1" data-aria-posinset="2" data-font="Calibri" data-leveltext="%1." data-list-defn-props='{"335551671":1,"335552541":0,"335559683":0,"335559684":-1,"335559685":720,"335559991":360,"469769242":[65533,0,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-listid="4">
	<p>Conclusione SDA senza invio al TED (CSDA2) senza eForm. </p>
	</li>
</ol>

<p>I bandi esecutivi degli SDA devono essere trasmessi attraverso la scheda P7_2. Nella stessa scheda, a livello di lotto, è necessario valorizzare il campo ‘condizione negoziata’ specificando la voce ‘appalto specifico nel Sistema Dinamico di Acquisizione’  <br>
Dopo la P7_2 segue il flusso ordinario. </p>
