### ISSUE TITLE
Variazione aggiudicatari 

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#820]
la presente issue è riferita alla issue #572 che non riesco a riparire. 
La Tematica sulla variazione degli aggiudicatari doveva essere approfondita nel GDL del 01/12/2023 ma non si è riusciti ad approfondire l'argomento.
Sarebbe utile discutere la gestione della variazione aggiudicatari nel GDL del 06/12/2023

**Comment by LucaMaggioni1** [comment]
riprendo la issue in quanto non risulta chiaro come gestire correttamente le casistiche.

- in caso di scheda A già inviato in cui è stato indicato un OE come aggiudicatario, in caso di riaggiudicazione del lotto deve essere rettificata la scheda A o è sufficiente inviare la SC1 con indicazione di un altro OE con cui si è firmato il contratto?

- per le variazioni soggettive di un OE viene trasmessa la scheda S4?

**Comment by anac-uscp** [comment]
<p>Per la risposta alla seguente domanda:</p>

<p style="margin-bottom:20px;"><span style="font-size:12pt;"><span style='font-family:"Times New Roman",serif;'><span style="font-size:11.0pt;"><span style='font-family:"Aptos",sans-serif;'><span style="color:#1f497d;">.</span></span></span> <span style="font-size:11.0pt;"><span style='font-family:"Aptos",sans-serif;'><span style="color:#1f497d;">Per indicare una variazione di un aggiudicatario (1° in graduatoria) non è sufficiente sottoscrivere il contratto con altro soggetto della graduatoria?</span></span></span></span></span></p>

<p style="margin-bottom:20px;">si potrebbe fare riferimento alla risposta della issue #1042.<br>
Nel caso le indicazioni fornite dalla issue non fossero esaustive si prega di aprire una nuova issue inserendo ulteriori elementi di dettaglio.</p>
