### ISSUE TITLE
Invio scheda di aggiudicazione - integrazione o sostituzione

### ISSUE THREAD

**Issue by LucaMaggioni1** [anticorruzione/npa#821]
Buongiorno,

ogni volta che viene inviata una scheda di aggiudicazione, questa integra o sostituisce la precedente?

grazie

**Comment by anac-uscp** [comment]
<p>Per la modifica e la rettifica dei dati di aggiudicazione si rimanda ai corrispondenti Servizi di Modifica e Rettifica Dati</p>
