### ISSUE TITLE
[BLK] Conferma-piano scheda PL1_7 esito PI_N_CONF con errore Generico - ERR9999

### ISSUE THREAD

**Issue by gaetanololli** [anticorruzione/npa#822]
<p>Rileviamo l'errore ERR9999 durante l'invocazione di /conferma-piano, nonostante /verifica-piano restituisca esitoOperazione: PI_VERIF. E' possibile verificare la discrepanza e la causa dell'errore?</p>

<details>
<summary>/verifica-piano</summary>
<p>
> POST /modi/rest/PianificazioneAppalto/v2/verifica-piano HTTP/1.1<br>
GovWay-Message-ID: 6dd4f865-58ca-4348-98cf-53077071312d<br>
Payload: {"idPianificazione":"6e748562-3758-41b8-b27e-f4f439322017"}</p>
<p>
Risposta:<br>{"status":200,"title":"OK","detail":"Richiesta acquisita","type":"about:blank"}
</p>
</details> 
<details>
<summary>/esito-operazione</summary>
<p>
> GET /modi/rest/ServiziComuni/v2/esito-operazione?idPianificazione=6e748562-3758-41b8-b27e-f4f439322017&tipoOperazione=PI_VERIF&tipoRicerca=ULTIMO_ESITO HTTP/1.1<br>
GovWay-Message-ID: cd967bbb-29d5-49c1-9f54-619632bae6b3</p>
<p>
Risposta:<br>{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idScheda":"bac7c5fe-7002-4344-be62-083c69094eaf","esito":{"idTipologica":"esito","codice":"OK"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"PI_VERIF"},"dataControllo":"2023-12-05T16:11:06.282+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"PI_VERIF"}}]}
</p>
</details> 
<details>
<summary>/conferma-piano</summary>
<p>
> POST /modi/rest/PianificazioneAppalto/v2/conferma-piano HTTP/1.1<br>
GovWay-Message-ID: 685c1180-2fff-4007-9066-727c53548178<br>
Payload: { "idPianificazione": "6e748562-3758-41b8-b27e-f4f439322017"}</p>
<p>
Risposta:<br>{"status":200,"title":"OK","detail":"Richiesta acquisita","type":"about:blank"}
</p>
</details> 
<details>
<summary>/esito-operazione</summary>
<p>
> GET /modi/rest/ServiziComuni/v2/esito-operazione?idPianificazione=6e748562-3758-41b8-b27e-f4f439322017&tipoOperazione=PI_CONF&tipoRicerca=ULTIMO_ESITO HTTP/1.1<br>
GovWay-Message-ID: 581bc173-5a98-4574-974d-a6652236007e
</p>
<p>
Risposta:<br>
{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idScheda": "bac7c5fe-7002-4344-be62-083c69094eaf",
      "esito": {
        "idTipologica": "esito",
        "codice": "KO"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "PI_CONF"
      },
      "dataControllo": "2023-12-05T16:01:58.511+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "PI_N_CONF"
      },
      "errori": [
        {
          "idTipologica": "errori",
          "codice": "ERR9999"
        }
      ]
    }
  ]
}
</p>
</details>

**Comment by gaetanololli** [comment]
@mpizziconi In merito a questa issue, vista lo scorso venerdì per la quale c'era un problema di codifica sugli importi, ho provato a trasmettere una scheda con un eForm pubblicato sulla preview di GUUE con id 3d487550-75c1-42fb-8d21-1a0f11ca485b.

<img width="1461" alt="image" src="https://github.com/anticorruzione/npa/assets/42801336/1fa8171c-af84-4d2a-af14-1c9585f8bea0">

Richiedendo la conferma della scheda ricevo sempre un ERR9999.

Riferimenti:
idPianificazione: "168f212b-900c-438f-8654-83d37617b3a0"
_idScheda: "168f212b-900c-438f-8654-83d37617b3a0"
GovWay-Message-ID di trasmissione: 13262553-e875-4cff-8146-294f3fa1701b
GovWay-Transaction-ID di verifica: c44d3116-9e66-11ee-8e81-0050568e9679
GovWay-Message-ID di conferma: 7af0a6a7-bc7f-4082-b0d7-c3c6f920e07d

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
