### ISSUE TITLE
[BLK] - Scheda RSU1 - ERR 999

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#823]
trasmettendo una scheda RSU1 otteniamo errore 999

{
  "idAppalto": "0006b359-6e2e-4bb3-b677-8e1b51af3775",
  "body": {
    "anacForm": {
      "idContratto": "bfce5640-a7d1-494a-a561-53195ca358bb",
      "subappalto": {
        "codiceFiscaleDitta": "...",
        "impresaEstera": false,
        "codiceFiscaleAggiudicatario": "03481380263",
        "codiceFiscaleDittaACascata": null,
        "oggetto": "test",
        "oggettoMl": null,
        "importoPresunto": 150000,
        "categoria": {
          "idTipologica": "categoria",
          "codice": "FB"
        },
        "categoriaScorporabile": null,
        "cpv": [
          {
            "idTipologica": "cpv",
            "codice": "98514000"
          }
        ]
      }
    },
    "espd": "..."
  }
}

    "govwayMessageId": "0c156a38-5187-465b-aab2-6b709e44f17a",
    "govwayTransactionId": "2eb48336-9415-11ee-a061-0050568e9679",

**Comment by lelio-raffaelli** [comment]
Non abbiamo ricevuto, contrariamente a quanto dichiarato nel GdL del 6/12, nessuna risposta a questa issue dichiarata bloccante ed aperta da più di una settimana.
La chiudo perché abbiamo effettuato le trasmissioni con un altro appalto.

**Comment by pakozack** [comment]
Noi invece siamo bloccati su questa. Continua a darci ERR9999 su diversi appalti che abbiamo testato.

**Comment by pakozack** [comment]
@lelio-raffaelli è possibile condividere su che scheda ha funzionato la RSU1? Noi stiamo provando da una  AD3 ma continua a darci errore

**Comment by lelio-raffaelli** [comment]
@pakozack P2_16 e A2_29

**Comment by pakozack** [comment]
grazie @lelio-raffaelli provato anche con quelle. sempre errore generico...

**Comment by lelio-raffaelli** [comment]
Anche noi all'inizio avevamo avito 999, l'abbiamo superato dopo vari tentativi cambiando i dati delle scheda

**Comment by pakozack** [comment]
grazie @lelio-raffaelli, sto facendo mille prove... cambiati tutti i dati ma niente... che poi non è nemmeno una scheda tanto complessa. mica ti ritrovi un payload che ha funzionato? scusa e grazie ancora

**Comment by lelio-raffaelli** [comment]
@pakozack questa l'anac form passata:
{
		"idContratto": "...",
		"subappalto": {
			"codiceFiscaleDitta": "0348...",
			"impresaEstera": false,
			"codiceFiscaleAggiudicatario": "FLP...",
			"codiceFiscaleDittaACascata": null,
			"oggetto": "test 1",
			"oggettoMl": null,
			"importoPresunto": 100.0,
			"categoria": {
				"idTipologica": "categoria",
				"codice": "OG1"
			},
			"categoriaScorporabile": null,
			"cpv": []
		}
	}
