### ISSUE TITLE
[Maggioli] Scheda PL2_8 mancanza attributo scadenzaPresentazioneInvito

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#825]
Buongiorno.
Nella sezione 'lotto.datiBaseTerminiInvio' troviamo un'incoerenza tra la PL2_7 (avviso per riduzione termini) e la corrispondente per settore speciale PL2_8.

Nella PL2_7 sono previste due voci:
scadenzaPresentazioneInvito
oraScadenzaPresentazioneOfferte

Nella PL2_8 c'è una sola voce:
oraScadenzaPresentazioneOfferta.

E' un errore o una dimenticanza?

**Comment by supportoAnac** [comment]
Segnalazione corretta, le schede sono in fase di revisione e verrà aggiornato il dato segnalato.
