### ISSUE TITLE
Riapertura issue #559

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#828]
INTERCENTER
   In relazione alla issue nel titolo che si riporta integralmente:
   Intercent-ER
   Non ho trovato nel modello dati le informazioni relative al al numero di pubblicazione sia nazionale sia europeo. Di seguito le 
   informazioni:

   Numero pubblicazione sul TED (nella forma XXXXXX-YYYY)
   Numero della richiesta di pubblicazione al TED (forse è il notice-id ma non so se è quello attribuito per la PCP oppure quello attribuito 
   alla richiesta dal TED.
   Numero pubblicazione sulla PPL/ANAC (se esiste)
   La necessità di averli, oltre a motivazioni informative, risiede nella necessità di poter effettuare attività di rettifica.
Si ritiene la risposta ASSOLUTAMENTE insufficiente e, tra l'altro ERRATA.
come si evince dall'estratto di swagger per il campo datiPubblicazioneEU
![image](https://github.com/anticorruzione/npa/assets/137269683/fd343be7-9473-49f2-acef-81599c7a6507)
non è presente alcun numero di pubblicazione nel formato del TED (XXXXXX-YYYY) ma c'è solo il campo noticeId che rappresenta, come largamente conosciuto, il numero attribuito alla richiesta di pubblicazione.

Tra l'altro in uno degli incontri avuti con ANAC, Michele Pizziconi ha fatto riferimento ad un pubblicationId del quale non c'è traccia nel servizio di consulta-avviso.

Spero che riusciate a risolvere questo problema che è aperto ormai da più di un mese!!!!!

**Comment by supportoAnac** [comment]
Le informazioni sono restituite dal servizio nella forma dell’esempio seguente. 
La specifica YAML sarà aggiornata con il primo rilascio utile, verrà aggiunto anche il pubblicationURL.
 
 ```
 "datiPubblicazioneEU": {
    "noticeId": {
      "$binary": {
        "base64": "…",
       "subType": "04"
      }
    },
    "versionId": "01",
    "tipo": {
      "idTipologica": "tipoAvviso",
      "codice": "EU"
    },
    "stato": {
      "idTipologica": "statoAvviso",
      "codice": "PUBB"
    },
    "publicationId": "NNNNNN-2023",
    "_dataControllo": {
      "$date": "2023-11-20T15:15:00.679Z"
    },
    "dataInoltroPubblicazione": {
      "$date": "2023-11-18T08:29:20.746Z"
    },
    "dataRicezionePubblicazione": {
      "$date": "2023-11-18T07:28:25.000Z"
    },
    "dataPubblicazione": {
      "$date": "2023-11-20T23:00:00.000Z"
    }
  },
```

**Comment by FRASCA57** [comment]
Grazie per la risposta e chiedo scusa per la "rudezza" della richiesta, ma siamo un po' tutti sotto pressione!!
