### ISSUE TITLE
[BLK]  Scheda P7_2 errore campo "condizioniNegoziata" per RDO

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#829]
Salve,
riscontriamo il seguente errore per l'invio della scheda P7_2 per una RDO:

{"instance":null,"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":**[{"idTipologica":"errori","codice":"ERR4","dettaglio":"$.anacForm.lotti[0].condizioniNegoziata: is missing but it is required"}]}**

**DI seguito il json di input:**
{"scheda":{"codice":{"idTipologica":"codiceScheda","codice":"P7_2"},"versione":"1.0","body":{"anacForm":{"stazioniAppaltanti":[{"codiceFiscale":"11244750961","codiceAusa":"9000000003","codiceCentroCosto":"174a8a58-ef23-46e8-94e3-4c8915317d2a","funzioniSvolte":[{"idTipologica":"funzioniSvolte","codice":"1"}],"saTitolare":true}],"appalto":{"codiceAppalto":"bolzano_001202/2023","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"6"}],"motivazioneCIG":{"idTipologica":"motivazioneCIG","codice":"2"},"strumentiSvolgimentoProcedure":{"idTipologica":"strumentiSvolgimentoProcedure","codice":"3"},"datiBase":{"oggetto":"rdo","importo":6666.0},"datiBaseProcedura":{"tipoProcedura":{"idTipologica":"tipoProcedura","codice":"oth-single"}}},"lotti":[{"lotIdentifier":"LOT-0001","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"6"}],"saNonSoggettaObblighi24Dicembre2015":false,"iniziativeNonSoddisfacenti":false,"codIstat":{"idTipologica":"codIstat","codice":"9049015"},"servizioPubblicoLocale":false,"lavoroOAcquistoPrevistoInProgrammazione":false,"ripetizioniEConsegneComplementari":false,"ipotesiCollegamento":{"motivoCollegamento":{"idTipologica":"motivoCollegamento","codice":"10"}},"opzioniRinnovi":false,"afferenteInvestimentiPNRR":false,"ccnl":"78654665","categoria":{"idTipologica":"categoria","codice":"OG 10"},"prestazioniComprese":{"idTipologica":"prestazioni","codice":"1"},"finanziamenti":[{"tipoFinanziamento":{"idTipologica":"tipoFinanziamento","codice":"C04"},"importo":3333.0}],"tipoRealizzazione":{"idTipologica":"tipoRealizzazione","codice":"1"},"datiBase":{"oggettoContratto":{"idTipologica":"oggettoContratto","codice":"services"},"oggetto":"Listino","importo":6666.0}}]},"espd":""},"stato":null,"dataCreazione":null,"idScheda":null}}

**Tale campo però dallo swagger risulta essere obbligatorio per:** 
"Condizioni che giustificano il ricorso alla procedura negoziata senza previa pubblicazione di un bando oppure senza previa indizione di una gara - fare riferimento ai valori contenuti nel file".
**La procedura non rientra in nessuna delle due condizioni!** ma l'errore lo riceviamo ugualmente.

**Chiediamo un celere riscontro in quanto tale errore è bloccante!!!!!!!**

**Comment by anac-uscp** [comment]
Il campo va inserito e deve essere compilato. La scheda P7_2 potrà essere usata in vari casi pertanto è necessario compilare il campo "condizioni negoziata". Per le procedure sottosoglia bisogna indicare l'apposita voce.
