### ISSUE TITLE
Chiarimenti su gestione delegati

### ISSUE THREAD

**Issue by alexroia** [anticorruzione/npa#830]
1 - C'è un numero massimo di delegati dal RUP per ogni fase o in totale sull'appalto?
2 - Il RUP, una volta nominato un delegato, può continuare ad operare sull'appalto o ha restrizioni rispetto all'insieme delle azioni disponibili?

**Comment by r-dm123** [comment]
# I Delegati sono uno per fase
# una volta nominato un delegato, lavora in esclusiva sulla sua fase
e il rup mantiene la supervisione.
