### ISSUE TITLE
[Consip] ERR53 su Rettifica-avviso 

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#831]
invocando il servizio rettifica avviso riscontriamo ERR53 (operazione non consentita per lo stato dell'avviso sulla PVL).

id appalto = cbf2d1ea-74bd-4e50-81da-68a32edf6428

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
