### ISSUE TITLE
[Consip] Riapertura issue 758 -  Richiesta inserimento valore in Tipologica RuoloOE (FVOE) #758

### ISSUE THREAD

**Issue by cmauriello** [anticorruzione/npa#833]
Riteniamo di riaprire la issue 758 -  https://github.com/anticorruzione/npa/issues/758 richiedendo la previsione di conclusione dell'aggiornamento della tipologica con ruoli ulteriori rispetto al solo RTI per i concorrenti composti da più OE

**Comment by supportoAnac** [comment]
La tipologica è stata aggiornata, per maggiori dettagli si prega di fare riferimento al Changelog.
