### ISSUE TITLE
BT-27 - Addendi di importo

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#835]
Buongiorno, dalla documentazione si evince che importo coincide con il BT-27, non sembra potersi desumere però quali siano gli addendi di _importo_
Sembra prospettabile che si tratti della somma _impLavori_ o _impServizi_ o _ImpForniture_ e _sommeOpzioniRinnovi_

Per risposta vedi anche issue #834

**Comment by anac-uscp** [comment]
<p>Si rimanda alla FAQ A3 <a href="https://secure-web.cisco.com/1OPrkZ2unwldt55CBifnvTRG_SXU66yrmuW96s3Sla4i-WGceHkI2cYuMsvyfYda_Ag-q4OWH2HstB4gYWaYi8Dggmxzqtk3_oZ1c53VeR78fk_ORfq6CWpTFjueyJZFGuhwPI719W9G7gE01P_1Ihukl5VR5QfKONDVmYRI4BtRlLyvVFtkQkbdVy56CbRP-rRNWxtHn_AXrz0egcKf1GRUIOW8gCXf0c9uWULJeezFYO5cOU7wyQrJv0QwwrowV5CQ9dr0Q9vpIukIdFMAiBYtXE4CtYTnQEkeTDTTJv8si0K8wgAL_AyT0H5MrFLzU/https%3A%2F%2Fwww.anticorruzione.it%2F-%2Fcontributi-in-sede-di-gara" rel="noreferrer noopener" target="_blank">https://www.anticorruzione.it/-/contributi-in-sede-di-gara,</a></p>
