### ISSUE TITLE
[BLK] Ricerca-Appalto impostando il parametro dataCreazioneDa restituisce error 500 

### ISSUE THREAD

**Issue by davideorsi-bit** [anticorruzione/npa#838]
Buongiorno, chiamando il servizio di ricerca-appalto con i seguenti parametri:

- /ricerca-appalto?stato=PUBB&dataCreazioneDa=2015-05-28T14:07:17Z&page=1&perPage=100

ricevo un error 500:

```typescript
{"status":500,"title":"KO","detail":"Errore Generico","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR9999"}]}
``` 
 

GovWay-Transaction-ID=[2951965d-9812-11ee-9fc8-0050568e08b3]
 GovWay-Message-ID=[76565350-eef8-4fe6-889e-6e8b46939fd3]

@sfala
@ssorrentino

**Comment by pceribelli** [comment]
@mpizziconi buongiorno, posiamo chiederti se riusciamo ad analizzare questa issue. Grazie

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
