### ISSUE TITLE
Accesso eService AUSA - Errore 401

### ISSUE THREAD

**Issue by teslb** [anticorruzione/npa#843]
Buonasera,

nel chiamare l' e-service **ausa** ci viene restituito un errore 401 in mancanza del token che non possiamo generare in quanto non abbiamo finalità associate all'e-service.

La chiamata che facciamo è la seguente https://apigw-test.anticorruzione.it/modi/rest/AUSA/v1/api/ausa/getBy?codiceAusa=<codice TEST> dove in <codice TEST> usiamo uno dei codici AUSA ricevuti.

Poiché in documentazione troviamo unicamente le indicazioni per la richiesta del token attraverso le informazioni presenti nella finalità i-esima, abbiamo urgentemente la necessità di capire come altrimenti generarlo per questo e-service, che risulta comunque attivo.

Come noto, il CdC è un campo mandatory nella richiesta dei servizi e pertanto l'assenza costituisce un problema bloccante.

Rimaniamo in attesa di un vostro urgente riscontro.
Grazie e saluti

**Comment by AndreaClerici** [comment]
@teslb 
Buongiorno,
scusi il disturbo, ma potrebbe gentilmente spiegarmi come siete riusciti a risolvere questo problema?
Grazie
