### ISSUE TITLE
Scheda per AD (ad es. AD2_25) con stato diverso da aggiudicato

### ISSUE THREAD

**Issue by UserM21** [anticorruzione/npa#844]
Salve,

Per gli Affidamenti diretti in stato deserto/revocato/annullato non è prevista l’integrazione con la PCP? 
In caso contrario, è possibile indicare la scheda di riferimento?

Grazie

**Comment by supportoAnac** [comment]
ANAC non attribuisce valore a procedure che non si sono concretizzate/ a tracciare spese che non si sono realizzate. Non si arriva a staccare il CIG.
