### ISSUE TITLE
[Maggioli] Trasmissione scheda SQ1

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#845]
Dall'orchestratore si desume che la scheda SQ1 si può trasmettere solo dopo la scheda SO1 (ovvero dopo nessuna altra scheda). Questo significa che se dopo la scheda SO1 si trasmette un'altra scheda, ad esempio la SA1, la scheda SQ1 non è più trasmissibile.
Se la mia interpretazione dell'orchestratore è corretta (chiedo conferma) credo che questa cosa sia da rivedere

**Comment by anac-uscp** [comment]
<p style="margin-bottom:11px;"><span style="color:#000000;"><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;">Buongiorno,<br>
<br>
La sequenza delle schede nell’orchestratore è coerente con il codice dei contratti.</span></span></span></span></p>

<p style="margin-bottom:11px;"><span style="color:#000000;"><span style="font-size:11pt;"><span style="line-height:107%;"><span style="font-family:Aptos,sans-serif;">Infatti, a seguito dell’abrogazione dell’art. 141 del DPR 207/10 non è prevista la possibilità di effettuare SAL durante la sospensione dei lavori, dunque logicamente ad un SAL non può conseguire il superamento del quarto né la ripresa dei lavori.</span></span></span></span></p>
