### ISSUE TITLE
[PA33 srl] - Valore centro di costo scheda AD3

### ISSUE THREAD

**Issue by ddisante** [anticorruzione/npa#846]
Buongiorno, 
quale valore bisogna indicare nel campo "codiceCentroCosto" della stazioneAppaltante di una scheda AD3 dal momento che la ricerca delle informazioni nell'anagrafe AUSA con le credenziali che ci sono state assegnate ci restituisce il seguente messaggio:

Risposta: {"code":204,"status":"OK","title":"Richiesta elaborata correttamente, nessun contenuto restituito","items":null}

Abbiamo fatto la prova utilizzando un valore reale di una SA iscritta, restituisce tutti i centri di costo appartenenti alla stessa. Come possiamo creare dei centri di costo fittizi per effettuare le prove legandoli al codice AUSA e CF da Voi fornito?

Saluti

**Comment by r-dm123** [comment]
#fare riferimento alla issue 686.
