### ISSUE TITLE
Problema con DMN P2_11

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#848]
@mpizziconi 
Sul dmn P2_11 c'è qualcosa che non ci torna con la regola REG15.

some lotto in lotti
satisfies (lotto.ripetizioniEConsegneComplementari or lotto.ipotesiCollegamento.motivoCollegamento.codice != "10") and lotto.ipotesiCollegamento.cigCollegato = null

Questa regola sui nostri sistemi scatta sempre quando non valorizziamo ipotesiCollegamento. In particolare con lotto.ripetizioniEConsegneComplementari a false e lotto.ipotesiCollegamento non impostato, la prima condizione risulta semrpe verificata in quanto null è !="10"

E' possibile verificare?

**Comment by pakozack** [comment]
stesso problema su P2_12

**Comment by pakozack** [comment]
stesso problema su P2_13

**Comment by pakozack** [comment]
stesso problema su P2_16

**Comment by supportoAnac** [comment]
Testata sui nostri sistemi mettendo _lotto.ripetizioniEConsegneComplementari_ a _false_ e _lotto.ipotesiCollegamento_ non impostato: la regola non scatta e riusciamo a creare e confermare l'appalto. 
Si chiede gentilmente di fare una nuova chiamata ai nostri sistemi e verificare se il problema è presente.

**Comment by pakozack** [comment]
In realtà la validazione non passa sul nostro sistema. 
Per implementare il controllo stiamo utilizzando la libreria feelin (nodejs)
https://github.com/nikku/feelin

evidentemente ha un comportamento differente rispetto alla soluzione da voi implementata rispetto alla gestione dei null.
@mpizziconi 
Sarebbe utile a questo punto avere a disposizione i sorgenti del validatore utilizzato da voi, così come condiviso nell'ultima riunione, in modo da evitare questi problemi.

**Comment by pakozack** [comment]
@mpizziconi 
Abbiamo effettuato dei test anche utilizzando il playground di camunda.
https://camunda.github.io/feel-scala/docs/playground/

Impostando come espressione

some lotto in lotti
satisfies (lotto.ripetizioniEConsegneComplementari or lotto.ipotesiCollegamento.motivoCollegamento.codice != "10") and lotto.ipotesiCollegamento.cigCollegato = null

e come context 

```json
{"appalto":{"datiBase":{"oggetto":"sb4f9j","importo":17,"is_compiled":false},"datiBaseProcedura":{"tipoProcedura":{"idTipologica":"tipoProcedura","codice":"neg-w-call"},"is_compiled":false},"motivoUrgenza":{"idTipologica":"motivoUrgenza","codice":"7"},"codiceAppalto":"ppa1s","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"16"}],"linkDocumenti":"https://ffani.com","idAppalto":"yjxdn","motivazioneCIG":{"idTipologica":"motivazioneCIG","codice":"6"},"strumentiSvolgimentoProcedure":{"idTipologica":"strumentiSvolgimentoProcedure","codice":"3"},"idPianificazione":"d64aj","termineRidottoAvvisoPreinformazione":true,"is_compiled":false},"lotti":[{"datiBase":{"oggettoContratto":{"idTipologica":"oggettoContratto","codice":"supplies"},"oggetto":"5x0zm","importo":62,"is_compiled":false},"prestazioniComprese":{"idTipologica":"prestazioniComprese","codice":"1"},"ripetizioniEConsegneComplementari":false,"ccnl":"gtqt5","opzioniRinnovi":false,"categoria":{"idTipologica":"categoria","codice":"OS 7"},"quadroEconomicoStandard":{"sommeOpzioniRinnovi":44,"sommeRipetizioni":13,"sommeADisposizione":61,"impLavori":55,"impServizi":27,"impForniture":55,"impTotaleSicurezza":80,"ulterioriSommeNoRibasso":27,"impProgettazione":80,"is_compiled":false},"lotIdentifier":"muelb","categorieMerceologiche":[{"idTipologica":"categorieMerceologiche","codice":"7"}],"contrattiDisposizioniParticolari":{"idTipologica":"contrattiDisposizioniParticolari","codice":"7"},"codIstat":{"idTipologica":"codIstat","codice":"1003062"},"afferenteInvestimentiPNRR":false,"saNonSoggettaObblighi24Dicembre2015":false,"iniziativeNonSoddisfacenti":false,"strumentiElettroniciSpecifici":false,"tipologiaLavoro":[{"idTipologica":"tipologiaLavoro","codice":"13"}],"modalitaAcquisizione":{"idTipologica":"modalitaAcquisizione","codice":"1"},"categoriaScorporabile":[{"idTipologica":"categoria","codice":"OG 2"}],"acquisizioneCup":false,"is_compiled":true}],"stazioniAppaltanti":[{"codiceFiscale":"yx3im","codiceAusa":"ksmyf","codiceCentroCosto":"ed69l","saTitolare":false,"funzioniSvolte":[{"idTipologica":"funzioniSvolte","codice":"2"}],"is_compiled":true}]}
```

abbiamo anche qui come risultato true.


<img width="1589" alt="Schermata 2023-12-13 alle 12 36 01" src="https://github.com/anticorruzione/npa/assets/2580458/d1f83e32-d433-4e51-957b-7c3c5558454e">

**Comment by glastra-digitalpa** [comment]
Abbiamo lo stesso problema per la validazione di @pakozack, stesso risultato testando le regole sul playground linkato

**Comment by pakozack** [comment]
è possibile avere un riscontro anche su questo?

**Comment by supportoAnac** [comment]
La REG15 è stata modificata nel rilascio del 9 Febbraio.
