### ISSUE TITLE
Crea-Scheda - Campi required schede CO1, A1_32

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#849]
Nelle schede CO1 e A1_32 sono stati trovati 2 campi required di tipo object con al loro interno solamente properties non required.
Ad esempio per la scheda A1_32 l'anacForm (`AnacFormA1_32Type`) ha come properties un `AppaltoA1_32Type` (required) al cui interno troviamo solo la property `modalitaRiaggiudicazioneAffidamento` non required.

![immagine](https://github.com/anticorruzione/npa/assets/137039656/29087153-edd4-4029-aab1-d1014d69e957)

Per quanto riguarda la CO1 invece si tratta del campo conclusione all'interno dell' `AnacFormCO1Type`

![immagine](https://github.com/anticorruzione/npa/assets/137039656/0b714e5d-a3fd-46ea-8637-11ebc5256163)

Sarebbe utile esplicitare gli eventuali campi required, o nel caso non ne esistano, rimuovere il required dall'oggetto padre (attualmente sta creando dei problemi con delle lib di validazione)

**Comment by anac-uscp** [comment]
<p>Per quanto riguarda la scheda A1_32 sarà eliminata l’obbligatorietà della sezione AppaltoA1_32Type. </p>

<p>Per quanto riguarda la CO1, la sezione conclusione è correttamente obbligatoria poiché è necessario trasmettere in alternativa le informazioni relative alla conclusione della prestazione (tra i cui dati c’è la data di ultimazione del contratto) oppure le informazioni relative ad una interruzione anticipata (tra i cui dati c’è la data di interruzione anticipata) </p>
