### ISSUE TITLE
Invio scheda I1 - risposta err39 idContratto non trovato 

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#860]
Sto inviando la scheda I1:
{
"idAppalto":"df196874-65ef-4d58-b157-56e371907ecf",
"scheda":{
"codice":{
"idTipologica":"codiceScheda",
"codice":"I1"
},
"versione":"1.0",
"body":{
"anacForm":{
"idContratto":"dc15354a-3f65-4fbd-8c4a-5ec31237a8c2",
"datiInizio":{
"dataDisposizioneInizio":"2024-02-02T12:02:05Z",
"dataApprovazione":"2024-02-01T12:02:05Z",
"consegnaFrazionata":false,
"avvioPerFasi":false,
"dataVerbalePrimaConsegna":"2024-02-02T12:02:05Z",
"dataAvvioPrimaFase":"2024-03-02T12:02:05Z",
"dataVerbaleConsegnaDefinitiva":"2026-12-20T12:02:05Z",
"consegnaSottoRiserva":false,
"dataEffettivoInizio":"2024-01-02T12:02:05Z",
"dataFinePrevista":"2026-12-20T12:02:05Z"
}
}
}
}
}
ANAC mi risponde:
{
   "status": 400,
   "title": "KO",
   "detail": "Errore",
   "type": "about:blank",
   "errori": [   {
      "idTipologica": "errori",
      "codice": "ERR39"
   }]
}

Ma se ricerco scheda la trovo:
      {
         "_idScheda": "dc15354a-3f65-4fbd-8c4a-5ec31237a8c2",
         "stato":          {
            "idTipologica": "statoScheda",
            "codice": "CONF"
         },
         "codice":          {
            "idTipologica": "codiceScheda",
            "codice": "SC1"
         },
         "versione": "1.0",
         "dataCreazione": "2023-12-13T11:13:26.502+00:00",
         "body": {"anacForm": {"datiContratto":          {
            "codiceAusa": ["9000000010"],
            "cig": ["S00005DC69"],
            "idPartecipante": "b62390a8-70f1-4740-adb3-6a416150b777",
            "dataDecorrenza": "2023-12-14T12:02:05Z",
            "dataScadenza": "2026-12-20T12:02:05Z",
            "importoCauzione": 30000
         }}}
      },
Dove sto sbagliando? idScheda è idContratto?

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
