### ISSUE TITLE
[BLK] AD1_28: ERR41 al conferma-scheda

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#862]
Alla conferma della scheda AD1_28 , esito operazione, otteniamo il seguente errore.

```json
{
  "status": 200,
  "title": "OK",
  "detail": "Esecuzione avvenuta con successo",
  "type": "about:blank",
  "listaEsiti": [
    {
      "idAppalto": "b88599ce-36e4-4b1c-8201-df80deabeebb",
      "idScheda": "aa8db831-06b7-45a8-8c6b-5ea6af7cce5b",
      "esito": {
        "idTipologica": "esito",
        "codice": "KO"
      },
      "tipoOperazione": {
        "idTipologica": "tipoOperazione",
        "codice": "AP_CONF"
      },
      "dataControllo": "2023-12-13T15:41:46.876+00:00",
      "dettaglio": {
        "idTipologica": "esitoOperazione",
        "codice": "AP_N_CONF"
      },
      "errori": [
        {
          "idTipologica": "errori",
          "dettaglio": "",
          "codice": "ERR41"
        }
      ]
    }
  ]
}
```

idAppalto: b88599ce-36e4-4b1c-8201-df80deabeebb

**Comment by pakozack** [comment]
si sollecita un riscontro

**Comment by pakozack** [comment]
@mpizziconi 
sempre stesso errore da 2 settimane.
Anche questo discusso nello scorso GdL.

Ultima prova pochi secondi fa

  "govway_message_id": "7783ec5f-dbde-43cd-ab5b-ee0bc206f795",
  "govway_transaction_id": "3e1c1988-a4c7-11ee-8e81-0050568e9679",

**Comment by pakozack** [comment]
Dopo 2 settimane issue bloccante ancora aperta

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
