### ISSUE TITLE
[BLK] modifica-avviso ERR9999

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#864]
Il servizio modifica-avviso ci da errore come di seguito

```json
{
  "status": 400,
  "title": "KO",
  "detail": "AV_N_PUBB",
  "type": "about:blank",
  "errori": [
    {
      "idTipologica": "errori",
      "codice": "ERR9999"
    }
  ]
}
```

"govway_message_id": "c8bd9e23-9b71-473a-b4be-67cd87a7f0da"
"govway_transaction_id": "cde099e0-99d0-11ee-8e81-0050568e9679"
"idAppalto": "3da557b4-7cce-4fd0-b56b-0ec419617164"
"idAvviso": "534500b5-1247-4524-9883-6a7d2b1fbf2f"

**Comment by pakozack** [comment]
passsata una settimana. qualche novità?

**Comment by pakozack** [comment]
@mpizziconi 
Si sollecita un intervento in merito all'errore segnalato. Abbiamo in produzione clienti bloccati a causa di questo errore. 
Non si riesce a fare il modifica-avviso.

Chiedo anche qui ai colleghi di condividere l'anomalia se riscontrata sui loro sistemi.

**Comment by pakozack** [comment]
Aggiornamento di oggi. 
Il nostro caro utente è riuscito a modificare l'avviso. Attenzione però perchè ci è riuscito solo dopo aver richiesto la pubblicazione: la richiesta è fallita (di pubblicazione) e solo da quel mometno in poi ha potuto fare la modifica.
Non solo... a questo punto non si riesce a recuperare l'esito dell'operazione di modifica. L'api recupera-esito, ULTIMO_ESITO AV_MOD, restituisce 200 con corpo nullo!!!
Che si fa???? C'è qualcuno????

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
