### ISSUE TITLE
Incongruenze api consulta-scheda/crea-scheda/modifica-scheda

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#867]
Nelle specifiche i type `SchedaPianificazioneType`, `SchedaComunicaAppaltoType`, `SchedaPostPubblicazioneType` hanno tutti le property `_stato` e `_dataCreazione`.

![immagine](https://github.com/anticorruzione/npa/assets/137039656/1ef373f4-1600-4b9c-991b-33234ded54e3)

I vari e-service di consultazione, invece restituiscono quelle property senza l'underscore.
Servirebbe adeguare l'openapi alla reale risposta degli e-service. Ad esempio un consulta appalto restituisce:

```json
{
	"instance": null,
	"status": 200,
	"title": "OK",
	"detail": "Operazione eseguita con successo",
	"type": "about:blank",
	"scheda": {
		"_idScheda": "f050e75b-cb97-4cdb-a0a2-194615977f44",
		"stato": {
			"idTipologica": "statoScheda",
			"codice": "CONF"
		},
		"codice": {
			"idTipologica": "codiceScheda",
			"codice": "AD3"
		},
		"versione": "1.0",
		"dataCreazione": "2023-11-24T08:47:18.733+00:00",
		"body": {}
```

**Comment by supportoAnac** [comment]
Si ringrazia per il feedback, che è stato preso in carico.
