### ISSUE TITLE
[BLK] [Ente Gestore FVG] Impossibile aggiornare ultima versione e-service PCP-*

### ISSUE THREAD

**Issue by CorradoVersolato** [anticorruzione/npa#868]
Buongiorno
Abbiamo necessità, in qualità di Ente Gestore incaricato dalla Regione Friuli VG, di procedere ad avviare i test degli e-service ANAC esposti tramite PDND in modo da ottenere la Certificazione di una piattaforma di approvvigionamento digitale.
Riferimenti dell’Amministrazione in Ambiente di collaudo
Tipologia
Pubblica Amministrazione
Categoria
Regioni, Province Autonome e loro Consorzi e Associazioni
Area geografica
Friuli-Venezia Giulia - Regione
Ragione sociale
Regione Autonoma Friuli-Venezia Giulia
Codice IPA
r_friuve
Codice Fiscale / P.IVA
80014930327
Indirizzo PEC primario
[regione.friuliveneziagiulia@certregione.fvg.it](mailto:regione.friuliveneziagiulia@certregione.fvg.it)
Sede Legale
Piazza dell'Unita' d'Italia 1 - 34121

Al momento abbiamo creato le finalità, e la maggior parte degli e-service PCP di ANAC sono attivi per la versione v1, abbiamo però necessità di procedere ad aggiornare l’utilizzo dell’e-service alla versione 2, aggiornamento che non ci è consentito in quanto il pulsante di aggiornamento è disabilitato (motivazione: il nostro Ente non possiede gli attributi richiesti). (vedi immagini allegate)
Abbiamo già aperto una issue qui https://github.com/pagopa/pdnd-interop-frontend/issues/668 ma il problema sembra sia che ANAC non ha ancora aggiunto la Regione Friuli Venezia Giulia tra gli enti abilitati, nonostante il documento che trovate in allegato.
E' urgente, grazie.
[Pb_aggiornamento_e-service.pdf](https://github.com/anticorruzione/npa/files/13671681/Pb_aggiornamento_e-service.pdf)
[01a_checklist_certificazione_componenti_piattaforme_ver2_FVG.pdf](https://github.com/anticorruzione/npa/files/13671684/01a_checklist_certificazione_componenti_piattaforme_ver2_FVG.pdf)

**Comment by Angelo030897** [comment]
@marcocipri-pagopa

**Comment by FedericaSicchiero** [comment]
@Angelo030897 ho aperto questa [issue](https://github.com/anticorruzione/npa/issues/922) sul tema.
Noi riceviamo da ANAC la lista degli enti a cui fornire gli attributi. Nel caso di INSIEL Spa serve che ci venga rimandato il documento corretto, mentre per la Regione serve che sia presente nel CSV che ci viene fornito con la lista degli enti da abilitare.

**Comment by CorradoVersolato** [comment]
Questo è stato fatto in data 01.01.2023 ANAC ha risposto positivamente restituendo il documento allegato. Cosa manca ancora?
[2023-0015618-COMUNICAZIONE-ESITO-VERIFICHE-REQ2.pdf](https://github.com/anticorruzione/npa/files/13737637/2023-0015618-COMUNICAZIONE-ESITO-VERIFICHE-REQ2.pdf)

**Comment by FedericaSicchiero** [comment]
Noi come PDND riceviamo solo la lista da ANAC e abilitiamo, non gestiamo la documentazione che ANAC invio con gli esiti o altro tipo di documentazione. Bisogna attendere che siano loro a rispondere e/o rimandarci il file corretto, che però non è quello che ricevono gli enti che fanno richiesta come avete fatto voi.
Chiedo a @mpizziconi se riesce a darci un riscontro gentilmente.

**Comment by CorradoVersolato** [comment]
Nel file excel inviato ad ANAC mancava il codice IPA di INSIEL SPA, necessario per l'abilitazione da parte di ANAC.
Vi invio in calce il codice IPA confidando che possa sbloccare la situazione.
![image](https://github.com/anticorruzione/npa/assets/153733278/a329f4d8-ed60-45fc-8006-3e23046e84dd)
