### ISSUE TITLE
Pubblicazione aggiudicazioni procedure bandite ante 1 gennaio 2024

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#871]
Buongiorno, ci si domanda come si debba dare pubblicità legale alle aggiudicazioni di bandi pubblicati ante 1 dicembre 2024, dal momento che, per come è stato più volte illustrato, l'orchestratore di ANAC funziona solo se sono state inviate tutte le schede previste in un flusso: e allora come si potrà mandare, ad esempio, una scheda A1_29 su un appalto pubblicato nel 2023? deve forse desumersi che la SA debba autonomamente procedere su eNotice2?

**Comment by SoricchioHRS** [comment]
Leggendo il comunicato ANAC l'aggiornamento delle schede relative alle procedure indette prima del 01.01.2024 segue la normativa vigente al tempo della pubblicazione della gara originaria. 
Pertanto, se la procedura prevede la pubblicazione su TED\enotice 1 o 2; GURI, Quotidiani etc, è chiaro che la pubblicazione dell'esito  seguirà le regole vigenti. La piattaforma SIMOG 2.0, infatti, non consente di rilasciare SIMOG per le nuove procedure post 01/01/2024. Le funzionalità precedenti continuano ad essere valide

**Comment by r-dm123** [comment]
Attenersi a provvedimento ANAC MIT in corso di emissione
