### ISSUE TITLE
[BLK] [CONSIP] - FVOE - Errore chiamata richiesta-accesso-fvoe - errore 401

### ISSUE THREAD

**Issue by EngineeringEProc** [anticorruzione/npa#873]
riapro la segnalazione 759 - la gara è pubblicata

class RichiestaAccessoRequest {

    class RichiestaAccessoType {

        idRichiesta: null

        dataInizioAutorizzazione: 2023-11-01T00:00:00Z

        dataFineAutorizzazione: null

        operatoriEconomici: [class AnagraficaOEType {

            class AnagraficaType {

                codiceFiscale: 5359681003

            }

            personaGiuridica: null

        }]

        appalto: class AppaltoType {

            class AppaltoBaseType {

                idAppalto: 029482ec-9c63-4b32-9502-eb0fd926d494

                codiceAppalto: null

                oggetto: null

                dataCreazione: null

                stato: null

            }

            lotti: null

        }

        richiedente: class AnagraficaSAType {

            class AnagraficaType {

                codiceFiscale: null

            }

            codiceAusa: null

        }

    }

}
 
Request{method=POST, url=https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiesta-accesso-fvoe, tag=Request{method=POST, url=https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiesta-accesso-fvoe, tag=null}}
 
Server: nginx

Date: Thu, 14 Dec 2023 12:22:19 GMT

Content-Type: application/json

Transfer-Encoding: chunked

Connection: keep-alive

expires: 0

cache-control: no-cache, no-store, max-age=0, must-revalidate

set-cookie: c08731b3614a016fdf8e25f403f6f286=a347166f29428045e097fbcff9c7064f; path=/; HttpOnly; Secure; SameSite=None

x-xss-protection: 1; mode=block

pragma: no-cache

GovWay-Message-ID: 1464d560-8f91-4f58-a9f0-eb05c7b2e15e

x-frame-options: DENY

GovWay-Transaction-ID: 1e43ce58-9a77-11ee-9fc8-0050568e08b3

vary: Access-Control-Request-Headers

vary: Access-Control-Request-Method

vary: Origin

x-content-type-options: nosniff

strict-transport-security: max-age=31536000 ; includeSubDomains

Strict-Transport-Security: max-age=63072000

OkHttp-Sent-Millis: 1702556539162

OkHttp-Received-Millis: 1702556539349
 
Response{protocol=http/1.1, code=401, message=Unauthorized, url=[https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiesta-accesso-fvoe}](https://apigw-test.anticorruzione.it/modi/rest/FVC/v2/richiesta-accesso-fvoe%7D)

**Comment by r-dm123** [comment]
Issue rientrata
