### ISSUE TITLE
[BLK] [Intercent-ER] Impossibile mandare SC1 dopo S3

### ISSUE THREAD

**Issue by AndreaClerici** [anticorruzione/npa#874]
Buongiorno,
abbiamo un problema, ci risulta impossibile inviare una scheda SC1 dopo aver inviato la S3.

Per prima cosa abbiamo creato un affidamento diretto e abbiamo inviato la scheda AD3. A seguire, abbiamo proceduto a inviare la scheda S3, senza problemi. Questa è un'operazione consentita, come indicato anche dal file schema-cronologia-schede.xlsx (per AD3, la SchedaSuccessiva contiene SC1,S3,CO1). 

Dopo la S3, abbiamo cercato di inviare la SC1. Anche questa operazione dovrebbe essere consentita, dato che nel file schema-cronologia-schede.xlsx come SchedaSuccessiva per la S3 è presente il simbolo *). Tuttavia, in questo caso riceviamo il seguente messaggio:
_{"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","dettaglio":"La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata","codice":"ERR2"}]}_

In un altro test siamo riusciti a inviare la scheda SC1 subito dopo la AD3, senza la S3 in mezzo. Però vorremmo essere comunque in grado di inviare una S3 in questi casi, anche perché risulta consentito, come detto prima.

Potete risolvere o spiegarci il problema?
Grazie

**Comment by supportoAnac** [comment]
Sono in corso verifiche sulle schede ammesse come successive a S3.
