### ISSUE TITLE
[BLK] [Intercent-ER] Impossibile inviare CO2 dopo AD5

### ISSUE THREAD

**Issue by AndreaClerici** [anticorruzione/npa#875]
Buongiorno,
stiamo avendo un problema bloccante col flusso della scheda AD5.

Dal file schema-cronologia-schede.xlsx, si può leggere che, per la scheda AD5, la colonna SchedaSuccessiva contiene solo la scheda CO2.
Tuttavia, la scheda CO2 ha, tra i suoi valori obbligatori, il campo idContratto, che nella descrizione ha _"identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto."_.
Ma la scheda di Sottoscrizione del contratto è la SC1, che infatti restituisce idContratto alla creazione.

Abbiamo provato a inviare una SC1 dopo un'AD5, ma il sistema ritorna errore dicendo "La scheda in ingresso non è ammessa a fronte dell'ultima scheda confermata".

Come è possibile procedere? Dopo l'AD5 non è possibile fare l'SC1, ma l'SC1 è necessaria per avere l'idContratto per la CO2. Potete risolvere o spiegarci come procedere?

Grazie

**Comment by pakozack** [comment]
ci accodiamo anche noi. abbiamo appena sperimentato lo stesso caso bloccante

**Comment by AndreaClerici** [comment]
Chiudo per il seguente motivo:
![ChiusuraTicket875](https://github.com/anticorruzione/npa/assets/17902262/0553085c-d27e-4cc8-ab9e-ce58c9ad82e3)

**Comment by supportoAnac** [comment]
La CO2 è sospesa fino a modifica del modello dati.
Si può fare riferimento a https://www.agid.gov.it/it/agenzia/stampa-e-comunicazione/notizie/2023/11/14/procurement-pubblicata-nuova-versione-dellallegato-2-dello-schema-operativo per l'elenco di schede per le quali è stata prevista una deroga.
