### ISSUE TITLE
[BLK] RSU1 - crea-scheda ERR9999

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#876]
La scheda RSU1 con payload

```json
{
  "scheda": {
    "codice": {
      "idTipologica": "codiceScheda",
      "codice": "RSU1"
    },
    "versione": "1.0",
    "body": {
      "anacForm": {
        "idContratto": "82bc5a15-6f77-4d4e-b00e-e500dbd21154",
        "subappalto": {
          "codiceFiscaleDitta": "AAACCC12D12D123D",
          "impresaEstera": false,
          "importoPresunto": 50.0,
          "categoria": {
            "idTipologica": "categoria",
            "codice": "999"
          },
          "cpv": [
            {
              "idTipologica": "cpv",
              "codice": "24957200"
            }
          ],
          "codiceFiscaleAggiudicatario": "PPDEEW12D12D212X",
          "oggetto": "test lavoro"
        }
      },
      "espd": ",,,,"
    }
  },
  "idAppalto": "4d50b7cc-48a9-43f8-b161-193df3204825"
}
```

ci da ERR9999 sul crea-scheda.

"govway_message_id": "70746c23-3404-4553-b284-5573a20124ed"
"govway_transaction_id": "2445d766-9a97-11ee-9fc8-0050568e08b3"

**Comment by pakozack** [comment]
@mpizziconi 
per promemoria
è una scheda per noi bloccante ai fini della certificazione

**Comment by pakozack** [comment]
si sollecita un riscontro

**Comment by gianlucacuomo** [comment]
Ci uniamo anche noi alla segnalazione, qualsiasi tentativo di invio restituisce un ER9999

**Comment by pakozack** [comment]
Risolto! Se puo servire a qualcuno il nostro problema era la valorizzazione di idTipologica="cpv". Deve essere "CPV", maiuscolo.

**Comment by gianlucacuomo** [comment]
@pakozack secondo me c'è stato qualche fix di ANAC perchè io ho mandato la stessa identica richiesta di qualche giorno fa ed è andata

**Comment by pakozack** [comment]
si @gianlucacuomo mi sembra di aver capito che c'è stato un fix di anac intorno al 18. A noi però continuava a non funzionare per un nostro errore di compilazione della idTipologica
