### ISSUE TITLE
[BLK] Scheda P2_16 e P6_2  - Obbligatorietà dei campi e comportamento schede successive

### ISSUE THREAD

**Issue by pceribelli** [anticorruzione/npa#879]
Buonaseara,  per la scheda P2_16  il campo  lotti > **datiBaseTerminiInvio > scadenzaPresentazioneInvito e oraScadenzaPresentazioneOfferte** non è un dato obbligatorio. Si chiede se la non compilazione del campo comporta un errore in fase di caricamento scheda S1 o S2. Si chiede se l'inserimento di una data all'interno del campo genera un limite temporale e prima di tale termine non è possibile presentare una scheda S1 o S2.

Si chiede quindi di conoscere il comportamento di suddetta scheda qualora il campo non venga popolato e il comportamento delle schede successive al flusso della scheda in questione. (S1, S2). 

Stessa questione riguarda la scheda P6_2 per il campo **oraScadenzaPresentazioneOfferte** il quale risulta obbligatorio mentre il padre "lotti > **datiBaseTerminiInvio**" risulta essere facoltativo.

@mpizziconi

**Comment by supportoAnac** [comment]
Risolta con il rilascio del 31/01/2024.
Aggiunte le regole REG95, REG96, REG97 sulla data di scadenza presentazione offerte e data scadenza presentazione invito.
https://github.com/anticorruzione/npa/blob/main/CHANGELOG.md
