### ISSUE TITLE
[Maggioli] URL pubblicazione Trasparenza (rif. Delibera n. 264 del 20 giugno 2023 - Provvedimento art. 28)

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#880]
Buonasera,
con riferimento alla Delibera n. 264 del 20 giugno 2023 - Provvedimento art. 28 Trasparenza, è possibile sapere come sarà composta la URL per collegare gli appalti al sito di ANAC?

Forse corrisponde alla URL che si può trovare cercando nella BDNCP tipo questa che prevede il CIG come parametro in get, es:
https://dati.anticorruzione.it/superset/dashboard/dettaglio_cig/?cig=A02ED60831&standalone=2

**Comment by paolo-urbanetto** [comment]
Buongiorno,
vedo che avete pubblicato ieri ["Pubblicità legale gare d’appalto, dal 1 gen. piattaforma Anac al posto della G.U. per atti e bandi"](https://www.anticorruzione.it/-/pubblicit%C3%A0-legale-gare-d-appalto-dal-1-gen.-piattaforma-anac-al-posto-della-g.u.-per-atti-e-bandi)  e che la url del servizio è https://pubblicitalegale.anticorruzione.it/

Possiamo sapere se c'è modo di chiamare la URL passando una chiave di ricerca (quale idAppalto, CIG, ecc.)?

**Comment by paolo-urbanetto** [comment]
Visto ora cosa viene pubblicato su https://pubblicitalegale.anticorruzione.it/ posso immaginare che la URL ai fini della trasparenza sia https://dati.anticorruzione.it/superset/dashboard/dettaglio_cig/?cig=<CIG>&standalone=2

E' possibile avere conferma?

**Comment by matteolaltrelli** [comment]
@paolo-urbanetto il link per la trasparenza sembrerebbe essere quello da te indicato [dati.anticoruzzio](https://dati.anticorruzione.it/superset/dashboard/dettaglio_cig/?cig=&standalone=2) ma stiamo facendo delle prove e alcuni cig si visualizzano correttamente mentre su altri la pagina non si apre. 
I CIG su cui ho fatto i test sono entrambi appartenenti allo stesso ente, procedure similari etc.
Non riusciamo a capire come mai questa differenza, a questo punto che facciamo, pubblichiamo il link anche se non funziona??

**Comment by paolo-urbanetto** [comment]
@matteolaltrelli grazie del riscontro; noi abbiamo visto che non ci sono nemmeno i CIG delle procedure presenti nella PVL!
Stiamo valutando se usare la url generica https://dati.anticorruzione.it/superset/dashboard/appalti/ non conforme alla Delibera n. 264  che cita che il "link" è per lo specifico contratto, oppure la url https://dati.anticorruzione.it/superset/dashboard/dettaglio_cig/?cig=>CIG> sperando che prima o poi il servizio di ANAC funzioni e rischiando che poi venga comunicata una URL da usare diversa da questa.

> 3.3 Le stazioni appaltanti e gli enti concedenti inseriscono sul sito istituzionale, nella sezione "Amministrazione
> trasparente", un collegamento ipertestuale che rinvia ai dati relativi all’intero ciclo di vita del contratto
> contenuti nella BDNCP secondo le regole tecniche di cui al provvedimento adottata da ANAC ai sensi
> dell’articolo 23 del codice. Tale collegamento garantisce un **accesso immediato e diretto ai dati da consultare
> riferiti allo specifico contratto** della stazione appaltante e dell’ente concedente ed assicura la trasparenza di
> tutti gli atti di ogni procedura contrattuale, dai primi atti all’esecuzione.

**Comment by paolo-urbanetto** [comment]
Ho trovato la URL ufficiale nella FAQ B.12
Segnalo tuttavia che nel caso di schede senza CIG (ad esempio gli avvisi) la pubblicazione su BDNCP non c'è e non è previsto per questi che venga fatta la pubblicazione dalla SA.
Pensate di integrare la BDNCP anche con queste casistiche?
Nel caso potete documentare quale sarà la URL sul progetto github o rispondendo alle issue?
Grazie
