### ISSUE TITLE
Servizi ricerca-scheda - Risposta con codice stato 202 e mancanza di contenuto

### ISSUE THREAD

**Issue by cmestergiovanni** [anticorruzione/npa#882]
Durante l'invocazione del servizio "ricerca-scheda" di tipo GET all'indirizzo https://api.integrazione.lispa.it/c/pdndbasic/PCPcomunicaPostPubblicazione/fruizione/ricerca-scheda, è comune ricevere una risposta con codice di stato HTTP 202 Accepted. Tuttavia, è importante notare che questa risposta **non contiene alcun dato al suo interno**. 
In altri casi, eseguendo la stessa chiamata con medesimi parametri, possiamo ricevere una risposta HTTP 200 che contiene i risultati richiesti.

Per caso avete qualche riscontro riguardo l'altalenanza dell'esito di risposta da parte di questo servizio?

A conferma di un tentativo riuscito, è allegata un'immagine che mostra una risposta con codice di stato 200:

![ricerca-scheda-response_200](https://github.com/anticorruzione/npa/assets/153851967/e4f7cf2a-a808-400d-b0ff-57c22ae67828)

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova issue. Grazie per la Sua collaborazione.
