### ISSUE TITLE
[BLK] Servizi modifica-avviso - Stato avviso modificato non viene aggiornato dopo la pubblicazione

### ISSUE THREAD

**Issue by matteolaltrelli** [anticorruzione/npa#885]
Dopo aver confermato un appalto e ricevuto l'idavviso, abbiamo effettuato la chiamata del pubblicaAvviso.
L'esito dell'operazione ci ritorna un problema sulla data di pubblicazione presente nell'eform, quindi con la chiamata al modificaAvviso abbiamo aggiornato l'eform con i dati corretti e proceduto nuovamente al pubblicaAvviso.
A questo punto l'operazione va a buon fine e l'appalto passa in stato Pubblicato, mentre l'avviso resta in stato Modificato.
Tale stato non è presente nella macchina a stati documentata in questo repository.
Volendo procedere ad una rettifica dell'avviso il sistema non ci fa effettuare tale operazione.
Ci aspettiamo che anche l'avviso vada in stato Pubblicato per effettuare l'operazione di rettifica.

**Comment by pakozack** [comment]
E' possibile avere un riscontro???

**Comment by supportoAnac** [comment]
Si conferma che lo stato MOD è contemplato. Se l'appalto passa in stato PUBB significa che anche il nuovo avviso è correttamente pubblicato, e si può verificare che anch'esso è passato in stato PUBB richiamando il servizio stato-avviso.
