### ISSUE TITLE
DMN - Controllo coerenza categorie merceologiche (ad es. Scheda P1_10)

### ISSUE THREAD

**Issue by giuliolastra** [anticorruzione/npa#886]
@mpizziconi
come anticipato già nella call della settimana precedente abbiamo problemi con questa regola DMN

 `some lotto in lotti satisfies (some categoria in lotto.categorieMerceologiche satisfies list contains(appalto.categorieMerceologiche, categoria))` 
 
La regola sembra non essere corretta, in quanto se vi è coerenza fra le categorie merceologiche nell'appalto e nei lotti il si attiva la validazione e la scheda non viene quindi validata.

La regola DMN è presente in queste schede:
- P1_10
- P1_11
- P1_12
- P1_13
- P1_14
- P1_17
- P1_19
- P1_20
- P2_10
- P2_11
- P2_12
- P2_13
- P2_14
- P2_16
- P2_16
- P2_17
- P2_19
- P2_20
- P2_21

Grazie mille!

**Comment by pakozack** [comment]
anche noi stesso problema.

**Comment by supportoAnac** [comment]
La regola verrà aggiornata al primo rilascio utile, che non avverrà prima dell’esercizio della piattaforma.

**Comment by pakozack** [comment]
Quindi disabilitiamo le nostre validazioni DMN????

**Comment by giuliolastra** [comment]
Come dobbiamo interpretare la chiusura dell'issue? Le regole sono differenti fra quelle del repository e quelle che utilizzate realmente? Se invece coincidono non sarà quindi possibile validare nessuna delle schede su indicate?

**Comment by pakozack** [comment]
@giuliolastra in realtà se provi quelle schede le riesci a creare. Evidentemente i controlli eseguiti realmente sono leggermente diversi da quanto documentato in questo repo. Questo era stato già evidenziato in altre issue. vedi ad es #848
