### ISSUE TITLE
PDND - eService [PCP - codeList, versione 4] - metodo status - errore 400

### ISSUE THREAD

**Issue by VincenzoISWEB** [anticorruzione/npa#889]
Salve,  

abbiamo provato ad eseguire delle chiamate di tesr al servizio codeList, nello speifico al metodo 'status'.

La procedura seguita è la seguente
1. Generazione del ClientAssertion contenente, come da documentazione [Trasmettere e tracciare dati complementari alla richiesta](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#il-flusso-in-dettaglio) , il parametro "digest" che risulta correttamente validata dal servizio "Debug della client assertion" presente sulla PDND
2. Otteniamo il Voucher dalla chiamata all'endpoint 'https://auth.uat.interop.pagopa.it/token.oauth2' 
3. generiamo l' "Agid-JWT-TrackingEvidence" utilizzando nell'header i parametri del client registrato sulla PDND e nel payload i dati richiesti nelle [specifiche JWS](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-jws/jws.yaml) 
```        
{
   "header":{
      "alg":"RS256",
      "typ":"JWT",
      "kid":"XXXXXXXXXXXXXXXXXXXXXXXXXXX"
   },
   "payload":{
      "jti":"XXXXXXXXXXXX",
      "iat":1702652426,
      "nbf":1702652431,
      "exp":1702652435,
      "aud":"https://apigw-test.anticorruzione.it/modi/rest/CodeList/v2",
      "userCodiceFiscale":"CodiceFiscale comunicato per mezzo mail",
      "userRole":"RP",
      "userLoa":3,
      "userIdpType":"SPID",
      "SAcodiceAUSA":"XXXXXXXXXX",
      "regCodicePiattaforma":"0000001",
      "regCodiceComponente":"0000001",
      "businessFlowID":"00000000-0000-0000-0000-000000000000",
      "traceID":"XXXXXXXXXXXXX",
      "spanID":"XXXXXXXXXXXX",
      "purposeId":"XXXXXXXXXXX"
   }
}
```
4. Effettuiamo la chiamata al servizio https://apigw-test.anticorruzione.it/modi/rest/CodeList/v2/status riscontrando il seguente errore:
```
{
   "type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
   "title":"InteroperabilityInvalidRequest",
   "status":400,
   "detail":"Received request is not conform to the required interoperability profile",
   "govway_id":"f8139594-9b3c-11ee-9fc8-0050568e08b3"
}
```

Da un check effettuato con ANAC è risultato il seguente errore sui loro sistemi:

```
Validazione security token ModI 'AUDIT' della richiesta fallita: [c1355]
[Header 'Agid-JWT-TrackingEvidence'] Signature verification failed: [COMPACT] Signature verification failure: Process 'kid' error: Retrieve remote key 'XXXXXXXXXXXXXXXXXXXXX' failed: Retrieve external resource
```

 Chiediamo gentilmente un chiarimento in merito

**Comment by obigno77** [comment]
chiedo cortesemente di riprovare

**Comment by VincenzoISWEB** [comment]
Purtroppo riscontriamo ancora il problema. Di seguito il messaggio di errore ricevuto :

`
{
   "type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
   "title":"InteroperabilityInvalidRequest",
   "status":400,
   "detail":"Received request is not conform to the required interoperability profile",
   "govway_id":"1e864859-9dcc-11ee-8e81-0050568e9679"
}
`

**Comment by obigno77** [comment]
Ora però abbiamo un problema diverso che riguarda la valorizzazione dei claim sul token
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
 [Header 'Agid-JWT-TrackingEvidence'] Token non utilizzabile prima della data '2023-12-18_19:01:22.000'
[Header 'Agid-JWT-TrackingEvidence'] Token creato nel futuro (data creazione: '2023-12-18_19:01:17.000')
Attenzione all'orologio di sistema

**Comment by VincenzoISWEB** [comment]
Ho aggiornato il Timezone di sistema in Europe/Rome (GMT+1), precedentemente era UTC.

Ho eseguito una nuova chiamata all'endpoint [https://apigw-test.anticorruzione.it/modi/rest/CodeList/v2/recupera-elenco-tipologiche](https://apigw-test.anticorruzione.it/modi/rest/CodeList/v2/recupera-elenco-tipologiche) alle ore "Dec 20 2023 11:14:25".
Ci siamo accorti che il Date all'interno del claim restituito dal Server è in ritardo di 15 secondi circa, per questo motivo abbiamo forzato i parametri 'iat', 'nbf', 'exp' impostando il timestamp con 30 secondi in meno ("Dec 20 2023 11:13:55").

il Payload comunicato all'interno del JWS era così formato:
```
{
   "jti":"e63242db-f47c-40a4-98b8-935d007852ab",
   "iat":1703070835,
   "nbf":1703070835,
   "exp":1703070835,
   "aud":"https://apigw-test.anticorruzione.it/modi/rest/CodeList/v2",
   "userCodiceFiscale":"CodiceFiscale comunicato per mezzo mail",
   "userRole":"RP",
   "userLoa":3,
   "userIdpType":"SPID",
   "SAcodiceAUSA":"XXXXXXXXX",
   "regCodicePiattaforma":"0000001",
   "regCodiceComponente":"0000001",
   "businessFlowID":"00000000-0000-0000-0000-000000000000",
   "traceID":"45277781-e71e-4dce-96a3-bb252867c32b",
   "spanID":"45277781-e71e-4dce-96a3-bb252867c32b",
   "purposeId":"XXXXXXXXXX"
}
```

L'errore restituito è il seguente
```
{
   "type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
   "title":"InteroperabilityInvalidRequest",
   "status":400,
   "detail":"Received request is not conform to the required interoperability profile",
   "govway_id":"683fa8db-9f26-11ee-8e81-0050568e9679"
}
```

mentre i codici di GovWay nella risposta sono:
```
GovWay-Message-ID: 7dd0a744-0aa5-41db-9551-c9d1ecfc2480
GovWay-Transaction-ID: 683fa8db-9f26-11ee-8e81-0050568e9679
```

**Comment by obigno77** [comment]
Verifica ModI della richiesta fallita: Riscontrate 2 eccezioni.
[GOVWAY-661] [Header 'Agid-JWT-TrackingEvidence'] Token scaduto in data '2023-12-20_12:13:55.000'
[GOVWAY-661] [Header 'Agid-JWT-TrackingEvidence'] Token creato da troppo tempo (data creazione: '2023-12-20_12:13:55.000')

**Comment by VincenzoISWEB** [comment]
Il problema era relativo alle date "iat", "nbf", "exp" in quanto risultavano essere successive rispetto all'orario del Server restituito nel header della risposta di errore.
Abbiamo risolto anticipandole di 30 sec .

Chiudo la issue a seguito della risoluzione descritta
