### ISSUE TITLE
Documentazione PCP - Necessità registrazione utenti dal 1 gennaio 2024

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#892]
Buongiorno, 
non si evince dalla documentazione di  PCP se dal 1° gennaio sia obbligatorio o meno iscriversi come RUP utilizzando il servizio

https://www.anticorruzione.it/-/servizio-di-registrazione-e-profilazione-utenti

**Comment by r-dm123** [comment]
Tutti i RUP che erano già censiti automaticamente avranno il profilo di RP. 
Per chi è nuovo si deve censire con il profilo RUP. 
Il profilo RUP sarà attribuito automaticamente dal sistema
