### ISSUE TITLE
[Intercent-ER] Utilizzo codici fiscali fittizi attribuiti da ANAC alle centrali Uniche di Committenza

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#894]
INTERCENTER
Alcuni Enti collegati alla piattaforma SATER ci chiedono se nella PCP resta valida la regola di utilizzo di codici fiscali fittizi assegnati da ANAC alle unioni di Comuni.

**Comment by obigno77** [comment]
Si conferma
