### ISSUE TITLE
[BLK] Servizio aggiungi-soggetto - ERR9999

### ISSUE THREAD

**Issue by scalabrese11** [anticorruzione/npa#895]
Buongiorno,

riceviamo il seguente errore nel chiamare il servizio di aggiungi-soggetto:
ErrorResponse: class ErrorResponse {
    class BaseResponse {
        instance: null
        status: 500
        title: KO
        detail: Errore Generico
        type: about:blank
    }
    errori: [class ErroriEnum {
        class TipologicaSchemaErroriType {
            idTipologica: errori
            codice: ERR9999
            dettaglio: null
        }
    }]
}

GovWay-Transaction-ID:"cccbe776-9d7a-11ee-8e81-0050568e9679"

Purtroppo l'errore è bloccante per continuare i test.

Grazie.

**Comment by scalabrese11** [comment]
Buongiorno,

riscontriamo ancora l'errore segnalato inizialmente.

Di seguito il codice GovWay-Transaction-ID:
"876128d3-a62b-11ee-baaf-0050568e9679"

Grazie.

**Comment by supportoAnac** [comment]
Qualora l'errore dovesse presentarsi nuovamente utilizzando l'ultima versione disponibile dei servizi [1.0.2](https://github.com/anticorruzione/npa/releases/tag/v.1.0.2), si prega di aprire una nuova segnalazione.
