### ISSUE TITLE
[BLK] [Consip] Errore 400 su tutti i servizi (ad es. crea-appalto)

### ISSUE THREAD

**Issue by lauralu1993** [anticorruzione/npa#899]
Salve,
non riusciamo più a invocare correttamente i servizi ANAC poichè otteniamo errore 400.
Abbiamo controllato i valori inoltrati al JWS e ci sembrano corretti e invariati rispetto ad altre richieste sottomesse. Potete dirci se c'è stata qualche variazione? 

di seguito tutti i dati di riferimento (il CF è stato volutamente oscurato):

“**govway_id**":"0a5ad3ab-9d90-11ee-8e81-0050568e9679” 
{
  "jti": "423fa07e-20fc-4985-93a2-91d469569f0e",
  "aud": https://apigw-test.anticorruzione.it/modi/rest/ComunicaAppalto/v2,
  "userCodiceFiscale": "XXXXXXXXXXXX",
  "userRole": "RP",
  "userLoa": "3",
  "userIdpType": "SPID",
  "SACodiceFiscale": "XXXXXXXX",
  "SAcodiceAUSA": "9000000008",
  "regCodicePiattaforma": "0000009",
  "regCodiceComponente": "0000010",
  "businessFlowID": "00000000-0000-0000-0000-000000000000",
  "traceID": "8ea2f805-1bed-4420-a921-b71cce011528",
  "spanID": "c94dbef2-fc0d-4752-8ae9-33f321eb355c",
  "purposeId": "621838e3-e6de-43d2-bd88-1a0eb0f939d4",
  "iat": 1702896985,
  "exp": 1702900585,
  "nbf": 1702896985
}

**Comment by mpizziconi** [comment]
lato ANAC rileviamo un problema nel recupero dei dati da PDND per la verifica del token

Signature verification failure: Process 'kid' error: Retrieve remote key 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' failed

**Comment by FedericaSicchiero** [comment]
@lauralu1993 avete provato ad usare il tool di debug del voucher presente in piattaforma? Prima dei nostri controlli vi riesce già a dire se c'è qualcosa di sbagliato

**Comment by mpizziconi** [comment]
Anomalia risolta
