### ISSUE TITLE
Rilascio specifiche Fascicolo virtuale appalto

### ISSUE THREAD

**Issue by pg-volpentesta** [anticorruzione/npa#9]
Sembra che non ci sia bisogno di chiamate dirette e quindi di integrazione diretta per definire\creare l'oggetto FVA. Dai Sequence Diagram forniti nella documentazione il Fascicolo Virtuale Appalti è manutenuto automaticamente a seguito dell’utilizzo dei servizi del pacchetto NPA (chiamata diretta da parte di NPA). Se ne chiede conferma.

**Comment by supportoAnac** [comment]
Si conferma.
