### ISSUE TITLE
[Intercent-ER] Pubblicazione PVL (già PPL/ANAC)

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#902]
INTERCENTER
abbiamo notato che alcune schede hanno tutte le informazioni di pubblicazione sul TED, ma mancano totalmente quelle su PVL.
Avete una spiegazione??

**Comment by supportoAnac** [comment]
In data di apertura della issue la piattaforma PVL non era ancora stata resa disponibile per i test di integrazione.
