### ISSUE TITLE
Modello-dati-schede-CSU1.yaml - Eliminata perché non utlizzata

### ISSUE THREAD

**Issue by pietropalermoIT** [anticorruzione/npa#903]
Buongiorno, la scheda in oggetto seppure nel changelog del 18 dicembre risulta eliminata è ancora presente nell'orchestratore e nella cartella delle schede https://github.com/anticorruzione/npa/tree/main/docs/modello-dati/schede, come mai?

**Comment by supportoAnac** [comment]
Si conferma che a rilascio effettivo la scheda CSU1 risulta rimossa.
