### ISSUE TITLE
[BLK] [CONSIP] Errore 400 in chiamata ai servizi di PostPubblicazione (crea-scheda)

### ISSUE THREAD

**Issue by NicolaOrritos** [anticorruzione/npa#906]
Riceviamo errore 400 in risposta alle chiamate dei servizi di PostPubblicazione.
Ad esempio, quando chiamiamo un crea-scheda, riceviamo il seguente errore:
_**POST https://apigw-test.anticorruzione.it/modi/rest/ComunicaPostPubblicazione/v2/crea-scheda**_
```JSON
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "127286b7-9db9-11ee-8e81-0050568e9679"
}
```

Di seguito i GovWay ID:
GovWay-Message-ID: 1279b2a9-9db9-11ee-8e81-0050568e9679
GovWay-Transaction-ID: 127286b7-9db9-11ee-8e81-0050568e9679

**Comment by obigno77** [comment]
Risolto

**Comment by NicolaOrritos** [comment]
Ritestata ieri dopo risoluzione della problematica. Confermiamo che le chiamate funzionano nuovamente.
