### ISSUE TITLE
[BLK] Ambiente di produzione PDND - Sottoscrizione richieste di fruizione

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#907]
Abbiamo ricevuto oggi autorizzazione ad andare in ambiente di produzione per cui stavamo replicando richieste, finalità e client e-service sull'ambiente PDND di produzione.
Siamo riusciti a creare la richiesta di fruizione per l'e-service AUSA con il relativo client e finalità ma non riusciamo a creare le richieste di fruizione per gli altri servizi in quando il pulsante "richiedi fruizione" rimane disattivato come mostrato come segue:

![image](https://github.com/anticorruzione/npa/assets/141841131/9f65921e-6a75-401c-be11-686eee6a90c3)

Potete verificare e risolvere
Grazie

**Comment by Angelo030897** [comment]
#901
