### ISSUE TITLE
[BLK] [Maggioli] Schede P7_3 e PL2_* - Errore ERR9999 dopo conferma-piano

### ISSUE THREAD

**Issue by ManuelBridda** [anticorruzione/npa#911]
Segnaliamo una regressione sulle pianificazioni che non prevedono pubblicazione su TED. 
Tramite la chiamata esitoOperazione con tipoOperazione=PI_CONF otteniamo l'errore ERR9999.

P7_3:
govwayMessageId: "1a23123d-f0a4-45e1-8c8d-7f75cbb2e0be"
govwayTransactionId: "d27a8748-9e7d-11ee-9fc8-0050568e08b3"

PL2_1:
govwayMessageId: "ca7a8e38-9458-4e95-b632-dd960b4b3064"
govwayTransactionId: "d84c0d1e-9e7c-11ee-8e81-0050568e9679"

PL2_2:
govwayMessageId: "d7e24a5b-2b30-4801-8669-fbc34f2dad73"
govwayTransactionId: "ff2561fb-9e7b-11ee-9fc8-0050568e08b3"

PL2_7:
govwayMessageId: "a3e8e0f4-6d61-4342-8624-c5bd0535e5a2"
govwayTransactionId: "fb7387d3-9e7c-11ee-8e81-0050568e9679"

PL2_8:
govwayMessageId: "e63c69a3-4bb3-4984-a4f8-a5bf7eb32aca"
govwayTransactionId: "1cdb78fb-9e7d-11ee-8e81-0050568e9679"

**Comment by gianlucacuomo** [comment]
Anche noi riscontriamo questa problematica

**Comment by pakozack** [comment]
anche noi stesso problema su PL2_*

**Comment by GiovanniSom** [comment]
riscontriamo anche noi lo stesso problema, scheda P2_1

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
