### ISSUE TITLE
[BUG] Modello dati scheda A1_31

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#912]
L'oggetto offerte presentate è indicato come facoltativo. Ma da errore non inviandolo.
Si prega di correggere

**Comment by supportoAnac** [comment]
Si conferma l’obbligatorietà del campo offertePresentate. La scheda verrà aggiornata al primo rilascio utile, che non avverrà prima dell’esercizio della piattaforma.

**Comment by Gestore-Venicecom** [comment]
Salve, 

il modello dati della scheda non è stato aggiornato  ,  ci troviamo anche con la dificoltà di inviare i lotti deserti 
potete farci capire come dobbiamo comportarci 

Saluti
