### ISSUE TITLE
 [BLK] [TOSCANA/BOLZANO]- Cancella-appalto ERR16  

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#915]
Salve,
Stiamo riscontrando il seguente errore al cancella appalto per AD5:

ID APPALTO: a6d87ecc-233c-498e-8675-53cd14232ad4

questo è il json di risposta:
{"instance":null,"status":400,"title":"KO","detail":"Errore","type":"about:blank","errori":[{"idTipologica":"errori","codice":"ERR16","dettaglio":null}]}

ERR16 - operazione non consentita per lo stato dell'appalto

Ci potreste indicare qual'è il problema?

**Comment by supportoAnac** [comment]
Le schede AD* fanno riferimento ad eventi già accaduti.
In questo momento non si può utilizzare la revoca appalto in quanto la CO2  è sospesa.
