### ISSUE TITLE
[BLK] Chiamata "failed" per ottenere i centri di costo da AUSA

### ISSUE THREAD

**Issue by stetrevi** [anticorruzione/npa#916]
Buongiorno,
a fronte di questa chiamata 
https://apigw.anticorruzione.it/modi/rest/AUSA/v1/api/ausa/getBy?codiceFiscale=03108560925
(effettuata alle 2023-12-20 09:25:00)  

Ottengo questa risposta:

{"type":"https://govway.org/handling-errors/403/Authorization.html","title":"Authorization","status":403,"detail":"Authorization failed","govway_id":"bca37688-9f0b-11ee-a2a9-00505684399c"}

Non riesco a fare chiamate di questo tipo in produzione (ovviamente l'Authorization Bearer è valorizzato).
Per favore potete dirmi il motivo di questa risposta?
Grazie

**Comment by supportoAnac** [comment]
ANAC non ha ricevuto il clientID. Si chiede di inviarlo, secondo le istruzioni pubblicate sulla PDND, alla casella email indicata nel corso del GdL del 22/12/2023.

**Comment by pakozack** [comment]
@supportoAnac scusate ma queste istruzioni dove sono pubblicate?
