### ISSUE TITLE
[BLK] PCP/PDND down???

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#918]
Si riscontrano problemi di accesso a tutti gli eservice

**Comment by lelio-raffaelli** [comment]
Confermo...anche noi siamo bloccati!

**Comment by ManuelBridda** [comment]
Bloccati anche noi

**Comment by cristiano-perin** [comment]
Confermo, anche noi lo stesso problema

**Comment by lelio-raffaelli** [comment]
Ora i servizi rispondono

**Comment by pakozack** [comment]
confermo, si è ripreso. chiudo
