### ISSUE TITLE
Servizi crea-appalto - Scheda P2_16 | differenze modello dati scheda e modello dati swagger servizi

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#920]
Salve,

nel testare i flussi di integrazione al crea-appalto della scheda P2_16 abbiamo riscontrato errori relativi a campi obbligatori, ma non presenti nello swagger [servizi](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/specifiche-servizi-appalto.yaml). Abbiamo trovato questi campi nel file [modello dati della scheda](https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/schede/modello-dati-schede-P2.16.yaml). 

Potreste chiarire che modalità dobbiamo seguire nell'integrare le schede? Dobbiamo considerare "false" le informazioni riportate nello swagger dei servizi e fare totale affidamento al modello dati della scheda? 

Ci aspettavamo di trovare le stesse informazioni ambo i lati, se così non è bisogna saperlo.

Grazie

**Comment by rossanoros** [comment]
Per inciso, queste le carenze riscontrate nei soli campi obbligatori 

```
[{
        idTipologica: "errori",
        dettaglio: "$.anacForm.appalto.categorieMerceologiche: is missing but it is required",
        codice: "ERR4",
    }, {
        idTipologica: "errori",
        dettaglio: "$.anacForm.appalto.codiceAppalto: is missing but it is required",
        codice: "ERR4",
    }, {
        idTipologica: "errori",
        dettaglio: "$.anacForm.lotti[0].afferenteInvestimentiPNRR: is missing but it is required",
        codice: "ERR4",
    }, {
        idTipologica: "errori",
        dettaglio: "$.anacForm.lotti[0].categorieMerceologiche: is missing but it is required",
        codice: "ERR4",
    }, {
        idTipologica: "errori",
        dettaglio: "$.anacForm.lotti[0].codIstat: is missing but it is required",
        codice: "ERR4",
    }, {
        idTipologica: "errori",
        dettaglio: "$.anacForm.lotti[0].contrattiDisposizioniParticolari: is missing but it is required",
        codice: "ERR4",
    }, {
        idTipologica: "errori",
        dettaglio: "$.anacForm.lotti[0].lotIdentifier: is missing but it is required",
        codice: "ERR4",
    }
]
```

**Comment by supportoAnac** [comment]
È dovuta al problema di rendering dello swagger per l’elemento _allof_.
Si segnala la presenza di issues aperte sul repository GitHub dello swagger che fanno riferimento a questo problema, come ad esempio questa https://github.com/swagger-api/swagger-ui/issues/7437 .
