### ISSUE TITLE
[BLK] [Maggioli] Scheda P3_1 - Incoerenza validazione e modello scheda

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#921]
Il modello LottoP3_1Type richiede obbligatorio l'attributo motivoEsclusioneOrdinarioSpeciale
Pertanto nel json questo attributo viene valorizzato, ad esempio nel seguente modo:
 "motivoEsclusioneOrdinarioSpeciale" : {
      "idTipologica" : "motivoEsclusioneOrdinarioSpeciale",
      "codice" : "12"
 }

Ma al momento della validazione si ottiene il seguente errore:
    "codice":"REG9",
    "descrizione": {
		"it": "Il campo ‘Esclusione o regime speciale’ non è richiesto",
		"en": "Il campo ‘Esclusione o regime speciale’ non è richiesto"
	},

Se invece non viene valorizzato nel json il medesimo attributo, la validazione passa.

Come è possibile se quel campo sul modello suddetto risulta obbligatorio?

**Comment by supportoAnac** [comment]
La REG9 scatta se il campo lotto.motivoEsclusioneOrdinarioSpeciale.codice=”12”. Per tutti gli altri valori la validazione va a buon fine. Si conferma l’obbligatorietà del campo. Abbiamo effettuato un test di controllo e se il campo non è indicato viene mostrato l’errore ERR4: "$.anacForm.lotti[0].motivoEsclusioneOrdinarioSpeciale: is missing but it is required".
