### ISSUE TITLE
[BLK] Errore CSV per abilitazione enti su PDND

### ISSUE THREAD

**Issue by FedericaSicchiero** [anticorruzione/npa#922]
Buongiorno,
quando ci è stato inviato il file CSV per abilitare INSIEL Spa alla PDND non è stato compilato il campo con il loro codice IPA. Al momento l'ente ha fatto l'onboarding ma non può fruire dei servizi perchè mancano gli attributi.
Serve che ci venga gentilmente rimandato il file compilato completamente in modo da forzare il ricaricamento e dare gli attributi necessari.
@mpizziconi

**Comment by FavaroInsiel** [comment]
Per INSIEL questo è il codice IPA
Cod IPA | iiisd

Codice Fiscale | 00118410323

https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente/scheda-ente/12689" href="https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente/scheda-ente/12689
