### ISSUE TITLE
Incoerenza schede in consulta-avviso

### ISSUE THREAD

**Issue by mladuDPA** [anticorruzione/npa#927]
L'api `consulta-avviso` al modello `AvvisoType`, property scheda, espone la scheda relativa all'avviso.
La scheda può essere di tipo `DatiPianoType`, `DatiAppaltoType` o `SchedaPostPubblicazioneType`.

I 3 type hanno un incongruenza sulla loro struttura comune, mentre piano e appalto espongono una property scheda (di tipo `SchedaPianificazioneType` e `SchedaComunicaAppaltoType`) al cui interno è presente la scheda stessa le post pubblicazione invece espongono direttamente il contenuto senza dichiarare una property.

![immagine](https://github.com/anticorruzione/npa/assets/137039656/2a7b5f8b-4a17-4464-8729-d3c327b09e55)

Questo oltre alla problematica della mancanza di un discriminator per capire che tipo è realmente contenuto nel json obbliga chi utilizza la response a cercare i dati in un path diverso.

Sarebbe **_molto molto_** utile che abbiano la stessa struttura

**Comment by supportoAnac** [comment]
Si ringrazia per il feedback, la segnalazione è stata presa in considerazione.
