### ISSUE TITLE
Invio Schede M1_40 - Json di esempio

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#928]
Se non è possibile mettere in piedi tutto lo scenario, sarebbe fondamentale avere i json di esempio delle schede  P1_14 e  A1_35, 
o almeno gli eforms di esempio relativi alle stesse schede per poter provare mettere in piedi in autonomia lo scenario che consente di poter trasmettere le schede  M1_40

**Comment by supportoAnac** [comment]
Si rimanda al modello dati delle schede [P1_14](https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/schede/modello-dati-schede-P1.14.yaml) e [A1_35](https://github.com/anticorruzione/npa/blob/main/docs/modello-dati/schede/modello-dati-schede-A1.35.yaml) .
Per quanto riguarda gli esempi di eforms, si raccomanda di cercare tra gli eNotices già pubblicati sul TED ed esaminarne uno che usa lo stesso subtype, ad esempio il 14 nel caso della P1_14.
