### ISSUE TITLE
Servizi recupera-CIG - Validità SMARTCIG richiesti prima del 31 dicembre 2023

### ISSUE THREAD

**Issue by mariottiDPA** [anticorruzione/npa#929]
Gli smartcig richiesti prima del 31 dicembre 2023 potranno essere ancora utilizzati a partire dal 1 gennaio 2024 o si dovrà procedere con la richiesta CIG tramite PCP?

**Comment by supportoAnac** [comment]
Si rimanda a https://www.anticorruzione.it/-/digitalizzazione-dei-contratti-pubblici , sezione A.6.
