### ISSUE TITLE
[BLK] Scheda PL2_1 - Rimane in stato "in lav"  

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#930]
Ciao  
dopo la conferma della la scheda PL2_1 non cambia stato e rimane in lav e  non possiamo andare avanti  

ricordo che oggi è il nostro ultimo giorno per la certificazione per cui vi chiediamo di darci riscontro il più presto possible  
aggiungo che l'esito  della chiamata  torna con errore generica   

https://apigw-test.anticorruzione.it/modi/rest/ServiziComuni/v2/esito-operazione 
IdPianificazione: 
84964261-9eca-4af9-bba7-ff637ff18a09

 Risposta: {'status': 200, 'title': 'OK', 'detail': 'Esecuzione avvenuta con successo', 'type': 'about:blank', 'listaEsiti': [{'idScheda': 'd3cd4057-e4ad-4081-bae0-119fb38db89d', 'esito': {'idTipologica': 'esito', 'codice': 'KO'}, 'tipoOperazione': {'idTipologica': 'tipoOperazione', 'codice': 'PI_CONF'}, 'dataControllo': '2023-12-21T09:18:10.727+00:00', 'dettaglio': {'idTipologica': 'esitoOperazione', 'codice': 'PI_N_CONF'}, 'errori': [{'idTipologica': 'errori', 'codice': 'ERR9999'}]}]}

Grazie

**Comment by Gestore-Venicecom** [comment]
Aggiorno il transaction ID 

TransactionId | Esito Operazione PL2_1
b2cc7702-a0ab-11ee-8e81-0050568e9679

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
