### ISSUE TITLE
[BLK] scheda A2_29: errore se campo facoltativo 'tipoProcedura' non compilato

### ISSUE THREAD

**Issue by pceribelli** [anticorruzione/npa#932]
In fase di creazione della scheda A2_29 otteniamo l'errore "errore nella conversione della scheda secondo il json schema definito - $.anacForm.appalto.datiBaseProcedura: is missing but it is required"

Se compiliamo il campo facoltativo 'tipoProcedura' non otteniamo l'errore. E' da aggiornare l'obbligatorietà per il campo 'appalto > datiBaseProcedura* > tipoProcedura'?
Grazie

@mpizziconi

**Comment by supportoAnac** [comment]
È una delle modifiche schedulate di aggiornamento del modello dati.  Le obbligatorietà dei campi saranno riviste e corrette laddove incoerenti.
