### ISSUE TITLE
[BLK] conferma flusso schede S2 > A2_29/NAG > S3

### ISSUE THREAD

**Issue by pceribelli** [anticorruzione/npa#934]
Si chiede se, come da orchestratore, per le schede appalto che prevedono le schede post pubblicazione S2 > A2_29/NAG > S3 non dovrebbe essere possibile passare da una S2 ad una S3 senza prima una A2_29 e/o NAG oppure è possibile prevedere un flusso diretto da S2 ad S3.
Abbiamo verificato che per una scheda P2_16 con due lotti, dopo aver inviato S1 ed S2 per entrambi i lotti, viene inviata una A2_29 per uno dei due lotti e, successivamente, una S3 per entrambi i lotti; ci aspettavamo un errore dai controlli di ANAC per il lotto per il quale non abbiamo inviato né una A2_29 né una NAG e, invece, per entrambi i lotti è stata confermata la S3.
Grazie

@mpizziconi

**Comment by supportoAnac** [comment]
S3 può essere inviata in qualsiasi momento; non è specifica solo per gli incarichi di progettazione ma anche per tutti gli altri incarichi tecnici. Può essere inviata anche dopo la S2.
