### ISSUE TITLE
Avviso Scheda P1_10 rimane in attesa pubblicazione 

### ISSUE THREAD

**Issue by Gestore-Venicecom** [anticorruzione/npa#935]
Abbiamo  problema che la scheda P1_10 rimane sempre in attesa di publicazione e di conseguenza non riusciamo a procedere con le altre schede  

abbiamo fatto corretamente la publicazione ma sempre rimane in attesa  

lascio l'esito della chiamata stato avviso  

facendo Chiamata stato avviso P1_10:
response = {'status': 200, 'title': 'OK', 'detail': 'Operazione Effettuata', 'type': 'about:blank', 'statoAvviso': {'idAvviso': '2f2ebcf5-a048-46ac-b806-f85e25ef0164', 'idAppalto': '865e6674-96e7-4582-8d4b-e5df8aff4069', 'idPianificazione': None, 'dataControllo': '2023-12-21T21:21:41.468+00:00', 'stato': {'idTipologica': 'statoAvviso', 'codice': 'IN_ATT_PUBB'}}}

**Comment by supportoAnac** [comment]
TED ha una problematica di presa in carico delle richieste in qualificazione che comporta un  ritardo di pubblicazione. Il batch TED è attivo tutti i giorni dalle 15 alle 16 e TED ha confermato ad ANAC che presenta una problema di riconoscimento della data di pubblicazione. 
ANAC può forzare l'avanzamento della scheda ma questo comporta una incoerenza della base dati. 
Dopo la segnalazione a TED, tutti gli avvisi vengono normalmente pubblicati entro le 16 del giorno successivo.
