### ISSUE TITLE
Scheda P1_14 - crea-scheda in errore

### ISSUE THREAD

**Issue by fabiovenditti** [anticorruzione/npa#936]
Stavo provando a creare la scheda P1_14 e mi restituisce 
{
   "status": 400,
   "title": "KO",
   "detail": "Argomenti di input non validi",
   "type": "about:blank"
}
La stessa scheda (a parte eform) inviata due giorni fa era stata acquisita correttamente
Dove sto sbagliando?
GovWay-Message-ID	7d0643cc-f4ab-4b7d-aaac-b892d300ca52
GovWay-Transaction-ID	9ade459f-a080-11ee-8e81-0050568e9679

Ribadisco che per mandare le M1_40 avremmo bisogno di un esempio di json per la P1_14 e A1_35
Altrimenti dove escludere dalla certificazione questa scheda

**Comment by fabiovenditti** [comment]
[P1_14.json](https://github.com/anticorruzione/npa/files/13749715/P1_14.json)

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
