### ISSUE TITLE
[BLK] Problematiche di multiaggiudicazione per singolo Lotto. Scheda A1_29

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#938]
Abbiamo sperimentato che nel caso di Appalti per i quali sui singoli Lotti è presente una pluralità di aggiudicatari, dovendo inviare la scheda di aggiudicazione (ad es. A1_29) al momento della stipula del contratto / convenzione, abbiamo la necessità di inviare più schede di aggiudicazione per lo stesso Lotto.
Tale sequenza non viene consentita poichè, alla prima scheda di aggiudicazione, lo stato del Lotto si modifica in "aggiudicato" e non vengono più accettate altre schede di aggiudicazione.

**Comment by anac-uscp** [comment]
<p>Le schede di aggiudicazione consentono di individuare più aggiudicatari.<br>
Si rammenta che la tecnica dei multiaggiudicatari è consentita nei casi di Accordi Quadro/Convenzioni quando sono conclusi con più operatori economici.</p>
