### ISSUE TITLE
[BLK] PDND Produzione - Errore 401

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#940]
Invocando PCP in produzione otteniamo il seguente errore.

https://auth.uat.interop.pagopa.it/token.oauth2
{
  "client_id": "fd16d29e-6901-44e9-a047-70445ce224a7",
  "client_assertion": "eyJraWQiOiJuajU1eVpQMlZZSmRNUk1lOExjcFB3Vlk5UmxkaGhnZUY1eHF1a2tzaFRZIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJmZDE2ZDI5ZS02OTAxLTQ0ZTktYTA0Ny03MDQ0NWNlMjI0YTciLCJzdWIiOiJmZDE2ZDI5ZS02OTAxLTQ0ZTktYTA0Ny03MDQ0NWNlMjI0YTciLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwianRpIjoiZTlhNmQ4MmY1Y2IwOWJiNzU3MjA1MGM1NzAxZjY4ZmIiLCJpYXQiOjE3MDMyNjQyMjEsImV4cCI6MTcwMzI3MDIyMSwicHVycG9zZUlkIjoiYjgxMjhlODItM2RkMy00NWQ1LThkNDctYTVjMGNmMTY0ZjQ1IiwiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiNmIxNDQwYWExNzU0MGQ3MDM3NjIzYjY1MzBjNWIzMmFlZGY5NWYyNGJhMjBlMTZmNzFiMWMwMmUwNTNhNTI2NiJ9fQ.dSX5iBKQRdzcb1JWdkCXxhRxKE72Wg5EXd1POJRhCgLLgoG6YbzL95JBdv0e3qXtflHJ6XPI7kOPhnPEeUiPQHYe3tXuCyzfT52sSKMEprD8na1hzspIkGBE7xMLNogEmRV8UOUOf27_EHNm78XdYk6XqKnI_sTaoXREhADV8EOSYdM-WR_EX0Z7E5fwwvKZU_xgW6ugEtUcMh_ilVkJO5PxkOB1np1SKT_sfN459CYFVYRKgODNQr1MNzLV8_0StaDWLEeBElaMk3qi-riDeDuElnomx_1RiXqdvOwAeIAYNE1xHpOe3c3MYQFdhAaxBCLe5cyNKamzb2jWHRZ3Dg",
  "client_assertion_type": "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
  "grant_type": "client_credentials"
}
------------------------------ END GET TOKEN REQUEST ------------------------------
--------------------------- GET TOKEN REQUEST RESPONSE 400 ----------------------------
{
  "date": "Fri, 22 Dec 2023 16:57:01 GMT",
  "content_type": "application/json",
  "content_length": "247",
  "connection": "keep-alive",
  "x_amzn_requestid": "3c79580d-e805-46cf-99b7-1d263759c88f",
  "access_control_allow_origin": "*",
  "access_control_allow_headers": "Authorization, Content-Type, X-Requested-With, Accept-Language",
  "x_amzn_remapped_content_length": "247",
  "x_amzn_remapped_connection": "keep-alive",
  "x_amz_apigw_id": "QWrqoEWJliAEAZg=",
  "x_amzn_remapped_server": "akka-http/10.2.10",
  "x_amzn_remapped_date": "Fri, 22 Dec 2023 16:57:01 GMT",
  "access_control_allow_credentials": "true"
}
{
  "correlationId": "5f199ac6-2045-4322-ac5f-8e1850996015",
  "errors": [
    {
      "code": "015-0008",
      "detail": "Unable to generate a token for the given request"
    }
  ],
  "status": 400,
  "title": "The request contains bad syntax or cannot be fulfilled.",
  "type": "about:blank"
}
------------------------- END GET TOKEN REQUEST RESPONSE --------------------------

Abbiamo inviato questa mattina il client_id configurato su PDND ed utilizzato per le richieste, alla mail supporto.pdnd@anticorruzione.it.

E' possibile avere un riscontro? Dobbiamo solo aspettare o c'è altro che dobbiamo fare?

**Comment by pakozack** [comment]
Potrebbe essere un problema di come valorizziamo i campi regCodiceComponente e regCodicePiattaforma? #908

**Comment by pakozack** [comment]
Risolto. sbagliavamo noi la richiesta, in particolare il campo aud. Consiglio di utilizzare il debugger e il simulatore presente nel backend di PDND.

**Comment by singhibs** [comment]
Ciao a tutti, buongiorno

Qualcuno ha implementato con successo l'api, ho generato con successo il token ma quando cerco di utilizzare il voucher mi appare
errore 401 

Ho anche verificato il token client_assertion che è corretto.

Se qualcuno ha implementato con successo qualche servizio mi dia qualche indicazione.

Sto cercando di implementare l'API INAD PUBBLICHE CONSULTAZIONI

ma anche se ho il token jwt continua a mostrare errore 401
