### ISSUE TITLE
GovWay - Errore 400

### ISSUE THREAD

**Issue by Silvio1970** [anticorruzione/npa#948]
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"49525547-a49c-11ee-8e81-0050568e9679"}

di cosa stiamo parlando ?

**Comment by FedericaSicchiero** [comment]
Buongiorno,
avete provato ad usare il tool di debug del voucher presente in piattaforma? Mentre facciamo i nostri controlli potrebbe già darvi la risposta su cosa si è bloccato

**Comment by Silvio1970** [comment]
Buongiorno,
abbiamo già utilizzato il debug sul voucher e c'è lo segnala come valido

**Comment by FedericaSicchiero** [comment]
Grazie del riscontro, allora vuol dire che lato PDND funziona tutto correttamente e serve riscontro da ANAC @mpizziconi

**Comment by Silvio1970** [comment]
@mpizziconi Vorrei sapere dove è la difficoltà nella risposta datemi un contatto non è possibile che passi così tanto tempo per rispondere devo dedurre che ci siano dei canali preferenziali o altro per decidere a chi dare preferenze nella risposta
