### ISSUE TITLE
[BLK] [Maggioli] Scheda CL1 - ERR40 in conferma-scheda

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#949]
Confermando la scheda CL1 otteniamo sempre
ERR40 - errore generico durante l'estrazione dei dati della scheda

Payload:
{
    "body":{

        "idAppalto":"1660cf98-4988-401b-89f3-4651beb7d48d",
        "anacForm":{
            "idContratto":"382f2395-cde5-4960-945b-8024874048b0",
            "collaudo":{

               "dataCollaudo":null,
               "dataCertificato":null,
               "modoCollaudo":{

                  "idTipologica":"modoCollaudo",
                  "codice":"1"
               },
               "dataNomina":"2023-12-27T01:00:00+01:00",
               "dataInizio":"2023-12-27T01:00:00+01:00",
               "dataRedazioneCertificato":"2023-12-27T01:00:00+01:00",
               "dataDeliberaAmmissibilita":"2023-12-27T01:00:00+01:00",
               "esito":"POSITIVO",
               "quadroEconomicoStandard":{

                  "impLavori":100.0,
                  "impServizi":100.0,
                  "impForniture":100.0,
                  "impTotaleSicurezza":100.0,
                  "ulterioriSommeNoRibasso":100.0,
                  "impProgettazione":100.0,
                  "sommeOpzioniRinnovi":100.0,
                  "sommeRipetizioni":100.0,
                  "sommeADisposizione":100.0
               },
               "quadroEconomicoConcessioni":null,
               "numeroTotaleRiserve":1,
               "oneri":100.0,
               "modalitaDefinizione":[
                  {
                     "ulterioriRiserve":true,
                     "numeroRiserveDefinite":1,
                     "numeroRiserveDaDefinire":1,
                     "impTotaleRichiesto":null,
                     "impTotaleDefinizione":null
                  }
               ]
            }
         }
    }
    
 }

**Comment by lelio-raffaelli** [comment]
Scusate, questa è una issue bloccante inserita 3 settimane fa.
Il canale per ottenere assistenza rimane questo delle issue? 
Se non siete in grado di fornire assistenza, sarebbe utile saperlo.

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.

**Comment by eslaSN** [comment]
Buongiorno, ho avuto lo stesso problema con la scheda CL1. Sembra che ci sia un problema con il campo modalitaDefinizione.
Provate ad escluderlo dal JSON e dovrebbe funzionare
