### ISSUE TITLE
[BLK] Errore 400 su tutti i servizi

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#951]
Da diversi minuti, in ambiente di collaudo, otteniamo errore su tutti i servizi

{
  "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
  "title": "InteroperabilityInvalidRequest",
  "status": 400,
  "detail": "Received request is not conform to the required interoperability profile",
  "govway_id": "8319505e-a4c9-11ee-8e81-0050568e9679"
}

es con richiesta 
https://apigw-test.anticorruzione.it/modi/rest/ServiziComuni/v2/esito-operazione?idAppalto=50f61cae-aea6-4045-937f-e19510f54904&tipoOperazione=SC_CONF&tipoRicerca=ULTIMO_ESITO

  "govway_message_id": "831cabbf-a4c9-11ee-8e81-0050568e9679",
  "govway_transaction_id": "8319505e-a4c9-11ee-8e81-0050568e9679",

**Comment by pakozack** [comment]
SI prega di intervenire con celerità. Abbiamo bloccato tutto lo sviluppo. E' cambiato qualcosa sugli eservice ANAC? Stavamo lavorando ad un certo punto ha iniziato a dare errore.

**Comment by pakozack** [comment]
Si sollecita nuovamente un riscontro. Siamo bloccati!

**Comment by mpizziconi** [comment]
rileviamo sul nostro gateway il seguente errore
[
Riscontrato errore durante l'inoltro del Messaggio di cooperazione con identificativo [xxxxxx-xxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxx] inviato alla parte destinataria [modipa/PDND] mediante connettore [http] (location: https://api.uat.interop.pagopa.it/1.0/keys/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx http-method:GET): errore HTTP 404
]

La issue viene assegnata a PagoPA per verifiche di competenza

@pakozack:
si richiede di verificare se si sta utilizzando la chiave corretta l'ambiente.

**Comment by pakozack** [comment]
si la nostra configurazione non è cambiata. Ieri stavamo inviando delle schede, ad un certo punto ha iniziato a dare errore

**Comment by pakozack** [comment]
vedo che la chiave in ambiente di collaudo è stata generata il 27 ottobre. ieri era 27 dicembre. 2 mesi. una coincidenza?

**Comment by pakozack** [comment]
Ho generato una nuova chiave per l'ambiente di collaudo. Utilizzando questa nuova chiave funziona
