### ISSUE TITLE
[BLK] Servizi esito-operazione - Errore ERR46 eform16

### ISSUE THREAD

**Issue by scalabrese11** [anticorruzione/npa#953]
Buonasera,

dopo la conferma dell'appalto, richiamando il servizio di esito-operazione otteniamo quanto di seguito:

class EsitoOperazioneListaResponse {
    class BaseResponse {
        instance: null
        status: 200
        title: OK
        detail: Esecuzione avvenuta con successo
        type: about:blank
    }
    listaEsiti: [class EsitoOperazioneType {
        idAppalto: 4255e6cb-64d1-4fe1-a8d7-81615d47b5bb
        idPianificazione: null
        idScheda: c1a12162-8c44-40ce-993c-f48d3f15d751
        idNuovaScheda: null
        idAvviso: null
        idNuovoAvviso: null
        idContratto: null
        esito: class EsitoEnum {
            class TipologicaSchemaType {
                idTipologica: esito
                codice: KO
            }
        }
        tipoOperazione: class TipoOperazioneEnum {
            class TipologicaSchemaType {
                idTipologica: tipoOperazione
                codice: AP_CONF
            }
        }
        dettaglio: class DettaglioEsitoOperazioneEnum {
            class TipologicaSchemaType {
                idTipologica: esitoOperazione
                codice: AP_N_CONF
            }
        }
        dataControllo: 2023-12-27T16:29:37.722Z
        errori: [class ErroriEnum2 {
            class TipologicaSchemaErroriType {
                idTipologica: errori
                codice: ERR46
                dettaglio: [400] during [POST] to [http://pcp-qlf-ted-ms.pcp-qlf.svc:8080/validate?language=it] [TedMsClient#validate(String,String)]: [{"code":400,"status":"400 BAD_REQUEST","title":"Error","detail":"400 : \"{\"errorCode\":400,\"message\":\"The notice is an invalid XML against its XSD. See below the full error:\\n[{\\\"line\\\":9,\\\... (19845 bytes)]
            }
        }]
    }]
}

Abbiamo necessità di capire il dettaglio dei campi che vanno in errore e non sono riconosciuti dal TED;
è possibile avere l'intero messaggio di ritorno del TED?

Grazie.

**Comment by scalabrese11** [comment]
Test più recente:

{
    class BaseResponse {
        instance: null
        status: 200
        title: OK
        detail: Esecuzione avvenuta con successo
        type: about:blank
    }
    listaEsiti: [class EsitoOperazioneType {
        idAppalto: 15e8f182-0265-404e-86ab-88131ea22c0b
        idPianificazione: null
        idScheda: 27c3bbcb-86eb-4738-97d5-952bffad05e8
        idNuovaScheda: null
        idAvviso: null
        idNuovoAvviso: null
        idContratto: null
        esito: class EsitoEnum {
            class TipologicaSchemaType {
                idTipologica: esito
                codice: KO
            }
        }
        tipoOperazione: class TipoOperazioneEnum {
            class TipologicaSchemaType {
                idTipologica: tipoOperazione
                codice: AP_VERIF
            }
        }
        dettaglio: class DettaglioEsitoOperazioneEnum {
            class TipologicaSchemaType {
                idTipologica: esitoOperazione
                codice: AP_N_VERIF
            }
        }
        dataControllo: 2024-01-04T09:37:27.899Z
        errori: [class ErroriEnum2 {
            class TipologicaSchemaErroriType {
                idTipologica: errori
                codice: ERR46
                dettaglio: [400] during [POST] to [http://pcp-qlf-ted-ms.pcp-qlf.svc:8080/validate?language=it] [TedMsClient#validate(String,String)]: [{"code":400,"status":"400 BAD_REQUEST","title":"Error","detail":"400 : \"{\"errorCode\":400,\"message\":\"The notice is an invalid XML against its XSD. See below the full error:\\n[{\\\"line\\\":7,\\\... (13900 bytes)]
            }
        }]
    }]
}

**Comment by scalabrese11** [comment]
EsitoOperazioneListaResponse {
    class BaseResponse {
        instance: null
        status: 200
        title: OK
        detail: Esecuzione avvenuta con successo
        type: about:blank
    }
    listaEsiti: [class EsitoOperazioneType {
        idAppalto: 15e8f182-0265-404e-86ab-88131ea22c0b
        idPianificazione: null
        idScheda: 205f9ca2-3ddb-4995-b08b-680bc039bdf0
        idNuovaScheda: null
        idAvviso: null
        idNuovoAvviso: null
        idContratto: null
        esito: class EsitoEnum {
            class TipologicaSchemaType {
                idTipologica: esito
                codice: KO
            }
        }
        tipoOperazione: class TipoOperazioneEnum {
            class TipologicaSchemaType {
                idTipologica: tipoOperazione
                codice: AP_VERIF
            }
        }
        dettaglio: class DettaglioEsitoOperazioneEnum {
            class TipologicaSchemaType {
                idTipologica: esitoOperazione
                codice: AP_N_VERIF
            }
        }
        dataControllo: 2024-01-04T10:28:04.384Z
        errori: [class ErroriEnum2 {
            class TipologicaSchemaErroriType {
                idTipologica: errori
                codice: ERR46
                dettaglio: [400] during [POST] to [http://pcp-qlf-ted-ms.pcp-qlf.svc:8080/validate?language=it] [TedMsClient#validate(String,String)]: [{"code":400,"status":"400 BAD_REQUEST","title":"Error","detail":"400 : \"{\"errorCode\":400,\"message\":\"The notice is an invalid XML against its XSD. See below the full error:\\n[{\\\"line\\\":7,\\\... (13900 bytes)]
            }
        }]
    }]
}

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
