### ISSUE TITLE
Area funzionale A_5 esecuzione

### ISSUE THREAD

**Issue by dpagliari** [anticorruzione/npa#955]
Buongiorno,

relativamente all'area funzionale A_5 di esecuzione, visto che durante uno degli ultimi tavoli tecnici si diceva che le schede di conclusione (CO1, CO2) subiranno a breve (fine gennaio 2024?) modifiche relative al modello dati, si richiede se per la certificazione di quest'area sono ancora obbligatorie tutte le seguenti schede (indicate nel file xls esito_test_interoperabilita_PCP):

SC - Sottoscrizione contratto
I - Inizio esecuzione
M - Modifiche contrattuali
SA - Stato di Avanzamento
RS - Subappalto 
SO - Sospensione 
AC - Contenzioso
CO - Conclusione

Grazie

**Comment by anac-uscp** [comment]
<p>Si, per ottenere la certificazione della fase di esecuzione A_5 ‘esecuzione’, è necessario aver implementato tutte le schede di esecuzione previste nell’area, come indicato nel documento AGID 'Checklist per la certificazione di componenti delle piattaforme di approvvigionamento digitale' Allegato 2 al documento “Schema Operativo a supporto della Certificazione delle Piattaforme di approvvigionamento digitale” al link <a href="https://trasparenza.agid.gov.it/page/9/details/2982/adozione-dello-schema-operativo-a-supporto-della-certificazione-delle-piattaforme-di-approvvigionamento-digitale-di-cui-alle-regole-tecniche-emesse-ai-sensi-dellart-26-del-dl-31-marzo-2023-n-36.html" id="menurhp" rel="noreferrer noopener" target="_blank" title="https://trasparenza.agid.gov.it/page/9/details/2982/adozione-dello-schema-operativo-a-supporto-della-certificazione-delle-piattaforme-di-approvvigionamento-digitale-di-cui-alle-regole-tecniche-emesse-ai-sensi-dellart-26-del-dl-31-marzo-2023-n-36.html">https://trasparenza.agid.gov.it/page/9/details/2982/adozione-dello-schema-operativo-a-supporto-della-certificazione-delle-piattaforme-di-approvvigionamento-digitale-di-cui-alle-regole-tecniche-emesse-ai-sensi-dellart-26-del-dl-31-marzo-2023-n-36.html</a></p>
