### ISSUE TITLE
M1_40 e M2_40

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#956]
per la certificazione dell'area A_5 sono richieste tutte le Famiglie di funzionalità con tutte le relative schede.

Nel caso in cui non fossero pertinenti in quanto non gestite le funzioni relative al settore-regime delle concessioni, quindi le schede di modifica contrattuale M1_40 e M2_40, le stesse devono comunque essere comunque incluse nella checklist di richiesta e attivati i test?

**Comment by anac-uscp** [comment]
<p>Si conferma quanto indicato nel documento AGID 'Checklist per la certificazione di componenti delle piattaforme di approvvigionamento digitale' Allegato 2 al documento “Schema Operativo a supporto della Certificazione delle Piattaforme di approvvigionamento digitale” al link <a href="https://trasparenza.agid.gov.it/page/9/details/2982/adozione-dello-schema-operativo-a-supporto-della-certificazione-delle-piattaforme-di-approvvigionamento-digitale-di-cui-alle-regole-tecniche-emesse-ai-sensi-dellart-26-del-dl-31-marzo-2023-n-36.html" id="menurhp" rel="noreferrer noopener" target="_blank" title="https://trasparenza.agid.gov.it/page/9/details/2982/adozione-dello-schema-operativo-a-supporto-della-certificazione-delle-piattaforme-di-approvvigionamento-digitale-di-cui-alle-regole-tecniche-emesse-ai-sensi-dellart-26-del-dl-31-marzo-2023-n-36.html">https://trasparenza.agid.gov.it/page/9/details/2982/adozione-dello-schema-operativo-a-supporto-della-certificazione-delle-piattaforme-di-approvvigionamento-digitale-di-cui-alle-regole-tecniche-emesse-ai-sensi-dellart-26-del-dl-31-marzo-2023-n-36.html</a></p>
