### ISSUE TITLE
[BLK] [Maggioli] Accesso e-service produzione: errore 403

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#960]
Buongiorno,
abbiamo provato anche oggi passando nel JWS il nostro regCodicePiattaforma, regCodiceComponente a invocare l'e-service codeList...
Abbiamo trasmesso ieri alle 17.56 il nostro client_id a supporto.pdnd@anticorruzione.it (vedi anche issue [952](https://github.com/anticorruzione/npa/issues/952) )
e il risultato è sempre 403:
```

"govwayMessageId": null,
"govwayTransactionId": "22cb2e38-a57d-11ee-852e-005056844885"

{
        instance: null
        status: 403
        title: Authorization
        detail: Authorization failed
        type: https://govway.org/handling-errors/403/Authorization.html
}
```

Stiamo sbagliando qualcosa?

Dobbiamo attendere ancora qualche altra abilitazione?

Manca qualcosa? Non troviamo documentazione a riguardo...

Attendiamo cortese riscontro.

Grazie

**Comment by mpizziconi** [comment]
Per accedere ai servizi di produzione è necessario fornire ad ANAC il clientID della piattaforma nelle modalità riportate sulle note di fruizione dei servizi.
