### ISSUE TITLE
[BLK] [Maggioli] Schede M1 ed M1_40 in stato "WAITING"

### ISSUE THREAD

**Issue by lelio-raffaelli** [anticorruzione/npa#961]
Ieri abbiamo creato e confermato diverse schede M1 ed M1_40.
Ad oggi, dopo più di 24 h, l'esito operazione è WT (WAITING).
E' possibile sapere se ci sono problemi? Si può sbloccare la situazione?

Ecco i dettagli:
"govwayMessageId": "4cacd2e6-578c-4b5f-98ae-8d9e3f3622dd",
"govwayTransactionId": "10bc4a77-a586-11ee-baaf-0050568e9679",
"idAppalto": "e99047f4-f8e3-4a3e-bdd4-a5bd7f8d3dc7",             
"idScheda": "7270d02a-197d-475f-93de-ebe07e471538",
"codiceScheda": "M1_40"
								
"govwayMessageId": "6ab466b1-4dba-431a-a6a6-0edaff1716a6",
"govwayTransactionId": "df968180-a585-11ee-9ec6-0050568e08b3", 
"idAppalto": "c14fcd81-0f1b-46e5-893a-eae26696edd7",
"idScheda": "da39b037-577a-4bc9-bf36-c82d87be017f",
"codiceScheda": "M1"
							
"govwayMessageId": "82d12cf5-4653-4d90-a5ac-0f1d1a9609bc",
"govwayTransactionId": "f4c86100-a585-11ee-9ec6-0050568e08b3",
"idAppalto": "71950626-e136-4846-9b7e-9240f6527306",
"idScheda": "c1c40bea-82f4-474b-b8ed-39229f67f4e7",
"codiceScheda": "M1"
								
"govwayMessageId": "2dfdc380-c034-44e2-a110-2cf03c1e9f2e",
"govwayTransactionId": "4aea172c-a586-11ee-baaf-0050568e9679",
"idAppalto": "0be78efd-40eb-48c9-82ba-95f6ccabfacf",
"idScheda": "b326ae3e-af61-41f3-b477-aefb0cd18fcd",
"codiceScheda": "M1"
				
"govwayMessageId": "59602be0-d359-4921-81e1-c9f261bd68dd",
"govwayTransactionId": "f4fb7ef8-a585-11ee-9ec6-0050568e08b3",
"idAppalto": "1eea726b-9320-4447-b92f-169ebcf855fc",
"idScheda": "fa011206-120b-4f96-86b4-cc5d79295167",
"codiceScheda": "M1_40"

**Comment by lelio-raffaelli** [comment]
Le schede sono sempre in stato  "SC_IN_CONF" (esito="WT"), a 6 giorni dalla trasmissione

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova issue. Grazie per la Sua collaborazione.
