### ISSUE TITLE
[BLK] Delucidazioni su importo CIG

### ISSUE THREAD

**Issue by ctav8** [anticorruzione/npa#962]
Buongiorno,
avremmo bisogno di sapere se i CIG (che verranno staccati ad appalto confermato) fanno riferimento ai valori `importo` (Importo lotto - corrisponde al campo bt-27 - Estimated Value del TED) presente nei vari tipi di `DatiBaseLotto`. Nel caso in cui non sia valorizzato questo campo, il CIG del lotto a quale importo fa riferimento?
Grazie mille.

**Comment by supportoAnac** [comment]
Il campo _importo_ è stato reso obbligatorio, e si conferma che il CIG del lotto fa riferimento a questo campo.
