### ISSUE TITLE
[BLK] Richiesta pubblicazione appalti

### ISSUE THREAD

**Issue by scalabrese11** [anticorruzione/npa#964]
Buonasera,

riscontriamo lentezza nella pubblicazione dei seguenti avvisi/appalti che restano in attesa di pubblicazione e ci impediscono di testare i servizi successivi.

1)
- idAvviso: 2efdd904-3c1c-4f02-b520-662a15bb7a18
- idAppalto: bc6affac-c8a4-44f9-ad4c-91b34ce5879f

2)
- idAvviso: 1a3e08e0-2fae-41cb-bda1-7928f071f7e9
- idAppalto: 62cc5723-1e86-4e15-b7b8-e42dd4b70885

è possibile procedere alla loro pubblicazione?

Grazie.

**Comment by scalabrese11** [comment]
Aggiorno gli appalti bloccati:

idAvviso: bce2ae2f-baf3-4a65-812b-dbea5c8f4bae
idAppalto: ac6989cf-6a72-4d17-a886-17c1e96ebe32

idAvviso: 9113661d-ab6c-4f3f-8b9b-c02afa9fe297
idAppalto: 9f8c6a67-3b45-49ea-8ee2-5f133e6c4801

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova issue. Grazie per la Sua collaborazione.
