### ISSUE TITLE
[BLK] [Maggioli] Accesso e-service produzione: errore 403 (riapro)

### ISSUE THREAD

**Issue by paolo-urbanetto** [anticorruzione/npa#965]
Buongiorno @mpizziconi ,
come indicato nella issue [960](https://github.com/anticorruzione/npa/issues/960) ho già trasmesso il clientID a supporto.pdnd@anticorruzione.it il 27/12/23 alle ore 17:56.

Ma poi risponde qualcuno a questa mail?  Mi aspettavo una mail di risposta del tipo "Abbiamo abilitato il vostro clientID, potete procedere", ma non ho ricevuto nulla.

Abbiamo provato anche ora ad accedere e riceviamo sempre 403.
Il voucher non ha problemi.
Lascio sotto il govwayTransactionId per tracciabilità.

Mi date riscontro? Sbagliamo qualcosa?

```
{
        instance: null
        status: 403
        title: Authorization
        detail: Authorization failed
        type: https://govway.org/handling-errors/403/Authorization.html
    }
"govwayTransactionId": "b579dc80-a62f-11ee-852e-005056844885"
```

**Comment by pakozack** [comment]
@paolo-urbanetto se puo servirti, controlla gli url in audiance e quello del recupero del token. In produzione sono
auth.interop.pagopa.it
e non
auth.uat.interop.pagopa.it

**Comment by paolo-urbanetto** [comment]
Grazie @pakozack , gli url sono corretti 
"jwtAudience": "auth.interop.pagopa.it/client-assertion",
e
https://auth.interop.pagopa.it/token.oauth2

**Comment by paolo-urbanetto** [comment]
Attendo riscontro da ANAC...

**Comment by paolo-urbanetto** [comment]
Problema risolto con abilitazione clientID da ANAC.
Si può chiudere la issue.
Grazie
