### ISSUE TITLE
[SORESA} [BLK] Invio scheda A1_29 - Servizi esito-operazione

### ISSUE THREAD

**Issue by FRASCA57** [anticorruzione/npa#969]
SORESA
dal 27 u.s. non riusciamo ad inviare schede A1_29 poichè l'esito-operazione restituisce lo stato "WT" (Wait).
Prima di questa situazione le A1_29 funzionavano bene. Un'altra cosa particolare è che l'esito-operazione contiene l'idAvviso al valore "null" cosa che in passato non accadeva.
di seguito un esempio di esito-operazione che abbiamo ricevuto:

"idAppalto": "95a47bb9-3e88-423a-985f-adca95c71d2e",
"idScheda": "944cc13f-9cb1-4c76-9888-27c6510866d9",
**"idAvviso": null,**
"esito": {
	      "idTipologica": "esito",
        	"**codice": "WT"**
			},
"tipoOperazione": {
		"idTipologica": "tipoOperazione",
		"codice": "SC_CONF"
			},
"dataControllo": "2023-12-29T18:21:04.46+01:00",
"dettaglio": {
			"idTipologica": "esitoOperazione",
				"codice": "SC_IN_CONF"
			},
			"errori": null
}

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
