### ISSUE TITLE
Scheda P2_17 | Pubblica appalto - Avviso resta in stato IN_ATT_PUBB

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#972]
Salve,

segnaliamo blocco sugli sviluppi in quanto gli appalti restano fermi alla pubblicazione avvisi. Non è, di conseguenza, possibile inviare S1 S2 e le schede di aggiudicazione.

Qui gli idAppalto bloccati in questo momento: 
- 631458b1-e168-4a02-b5e6-0b9e7575060b
- 634a98af-ef6f-45cd-b3e1-ed64dde26604

Parliamo di 2 P2_17.

**Comment by rossanoros** [comment]
Salve,

possiamo avere una qualche risposta alla problematica citata sopra?

Grazie.

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova issue indicando nuovamente le informazioni utili ad identificare l'appalto per effettuare le verifiche necessarie. Grazie per la Sua collaborazione.
