### ISSUE TITLE
[BLK] [Maggioli] Pubblica appalto - Scheda P2_16 resta in attesa di pubblicazione

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#974]
Salve
segnalo il blocco sulla pubblicazione per la scheda P2_16 inviata il 2024-01-02 14:37:16
IdAppalto:1750b0e4-185e-4035-8996-93402efce509
Ciò impedisce l'avanzamento delle schede successive.
Grazie

**Comment by CrisMaggioli** [comment]
Buongiorno oggi riprovando lo stato-avviso per la stessa scheda ottengo:
ERR47: errore generico durante la pubblicazione dell'avviso.
E'possibile sapere la natura di questo errore? grazie

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
