### ISSUE TITLE
Flusso utilizzo schede modifica contrattuale

### ISSUE THREAD

**Issue by ffinpaa** [anticorruzione/npa#976]
Buongiorno, considerata la colonna S "flussoAppartenenza" dell'orchestratore, rilevo che le funzioni M1 e M2 (modifica contrattuale pari/sopra soglia e sotto soglia) non appartengono ai flussi 116, 216, 225, 30, 62 e 72.

Chiedo se per queste tipologie di gare e affidamenti non debbano essere trasmesse le modifiche contrattuali o se si tratta di un refuso.

Grazie

**Comment by anac-uscp** [comment]
<p>Il Changelog - 03 in esercizio dalla prossima settimana completerà l'aggiornamento dei flussi per le schede M1/M2 </p>
