### ISSUE TITLE
[BLK] [Maggioli] Verifica con esito negativo  P1_16 non veritiera

### ISSUE THREAD

**Issue by CrisMaggioli** [anticorruzione/npa#979]
Salve,
per questo IdAppalto: bb48c0b7-0104-425c-b2fa-9cd5bb6bb876
arrivo alla verifica appalto con questo messaggio:
Errori bloccanti:

REG22: il campo quota30PerCento della sezione paritaDiGenereGenerazionale è obbligatorio se il campo afferenteInvestimentiPNRR è valorizzato a SI
La verifica ha avuto esito negativo.

ATTENZIONE: È necessario annullare e ricompilare la scheda correggendo gli errori.

Ma la situazione descritta non e' veritiera in quanto nel json trasmesso sono presenti 2 lotti con il dato popolato.

**Comment by supportoAnac** [comment]
Si chiede gentilmente di verificare i campi presenti nel primo lotto. Da un controllo sul database di qualificazione sembra che il primo dei due (LOT-0001) faccia correttamente scattare la regola perché ha il campo afferenteInvestimentiPNRR a true, ma non è presente il campo paritaDiGenereGenerazionale.quota30PerCento, obbligatorio in questo caso, come richiesto dalla regola. Il secondo lotto è invece corretto.
