### ISSUE TITLE
TokenExpired in modo randomico

### ISSUE THREAD

**Issue by rossanoros** [anticorruzione/npa#982]
Salve,

da stamane, nell'utilizzare i servizi PCP, otteniamo (in modo molto randomico) errori di token expired. Abbiamo provato a modificare **iat** e **nbf** sia anticipandoli che ritardandoli, rispetto all'attuale timestamp, senza successo.

Come possiamo pensare di portare in produzione una soluzione così poco stabile? Non possiamo stare a giocare con quei parametri ogni volta.

**Comment by mpizziconi** [comment]
Il problema è stato risolto
