### ISSUE TITLE
[INFO] [BLK] Avviso su AD3

### ISSUE THREAD

**Issue by pakozack** [anticorruzione/npa#984]
Ma è cambiato qualcosa relativamente alla pubblicazione delle schede di indizione? Appena provata la AD3 in ambiente di collaudo. Adesso genera un avviso che prima non generava.
E' possibile avere informazioni a riguardo e soprattutto essere informati preventivamente dei rilasci e degli aggiornamenti che apportate?

**Comment by pakozack** [comment]
Cosa sta succedendo?? In ambiente di produzione abbiamo comportamenti differenti e imprevedibili.
In dettaglio, AD3 inviata alle 12.23 di oggi, idAppalto: 86b91d06-08ba-455a-82d6-e1d4d73a86b0, ha creato un avviso ed è in stato "in attesa di pubblicazione". Altra AD3, inviata alle 15.52 di oggi, idAppalto: dffa9134-0b7a-49b8-b8ab-b1e7dfd9d856, NON HA GENERATO NESSUN AVVISO.
Vi chiediamo con estrema urgenza di chiarire questo comportamento. 
Stiamo parlando del sistema di produzione!

**Comment by paolo-urbanetto** [comment]
Ci aggiungiamo alla issue. Non capiamo più in quale stato deve andare una AD3 dopo la conferma.
In ambiente di collaudo abbiamo creato una AD3 con idAppalto 0383fe03-9c69-4b2d-ab5f-5399f5e22226
Ci aspettavamo dopo conferma-appalto che andasse in stato PUBB
Per altro, abbiamo "forzato" un pubblica-avviso sulla AD3 e l'ha processato... ci aspettavamo un errore!

**Comment by pakozack** [comment]
@mpizziconi 
ma almeno su questo è possibile avere informazioni? Adesso su AD3 non sta piu generando avvisi. Da orchestratore vedo PubblicazioneNazionale=SI. 
Sbaglio o dovrebbe andare su PVL? Sbaglio o dovrebbe esserci un avviso?
Cosa dobbiamo dire ai nostri clienti quando ci chiedono come fare un affidamento diretto?

**Comment by supportoAnac** [comment]
La Pubblicazione Nazionale per gli avvisi delle AD3 avverrà secondo le modalità e le tempistiche indicate nel changelog.
