### ISSUE TITLE
[Maggioli] Chiamata presa-carico per pianificazione

### ISSUE THREAD

**Issue by ManuelBridda** [anticorruzione/npa#989]
Secondo le specifiche, la chiamata presa-carico richiede come parametro obbligatorio il campo "idAppalto". 

La chiamata crea-piano ci restitutisce però un idPianificazione e non il campo "idAppalto". Pertanto, come dovrebbe funzionare la presa-carico di una pianificazione?

**Comment by supportoAnac** [comment]
Al momento i servizi di Pianificazione Appalto possono essere utilizzati unicamente da RP. 
Presa-carico agisce a livello di Responsabile di Progetto, effettuandone la sostituzione con una diversa utenza della medesima piattaforma, o di una differente piattaforma (ad esempio nel caso in cui la fase di aggiudicazione di un appalto deve essere gestita da una piattaforma diversa da quella del RP che lo ha creato).
PCP effettua su presa-carico un controllo incrociato:
- un controllo a livello di  RP (token di autorizzazione) sul primo soggetto
- il secondo soggetto deve essere RP di una delle SA censite nella scheda di indizione per l'appalto.
