### ISSUE TITLE
[TOSCANA/BOLZANO] - Servizi rettifica-avviso: ERR53

### ISSUE THREAD

**Issue by mariannagracco** [anticorruzione/npa#991]
Salve,

Riscontriamo un errore per la chiamata al servizio rettifica-avviso:
- ERR53 - operazione non consentita per lo stato dell'avviso sulla PVL

L'ID appalto è il seguente: b6eaefec-19ce-4c52-8f3e-7eefe911565f

Potreste indicarci qual'è la natura dell'errore?

**Comment by supportoAnac** [comment]
La ringraziamo per la Sua segnalazione, e desideriamo informarLa che a gennaio è stato rilasciato un aggiornamento dell'applicativo che ha risolto diversi problemi precedentemente segnalati. La invitiamo cortesemente a riprovare il processo con la versione aggiornata. Qualora dovesse riscontrare ulteriori problematiche, La preghiamo di aprire una nuova segnalazione. Grazie per la Sua collaborazione.
