### ISSUE TITLE
Errore REG73 scheda ES1

### ISSUE THREAD

**Issue by lucaCorigliano-SA** [anticorruzione/npa#994]
Salve, con il seguente corpo di richiesta alla scheda `ES1`

```json
{
    "anacForm": {
        "idScheda": "c196e76d-4f43-4205-b7f3-d08e44dab6bd",
        "subappalto": {
            "motivoMancatoSubappalto": {
                "idTipologica": "motivoMancatoSubappalto",
                "codice": "2"
            }
        }
    }
}
```

Si ottiene l'errore `REG73`, ovvero `Valorizzare almeno uno dei due campi: Data di autorizzazione del subappalto, Motivo del mancato subappalto` .

Suppongo ci sia un errore di validazione nel Vs server?

**Comment by supportoAnac** [comment]
Si conferma la correttezza della segnalazione, verrà inclusa una fix nel prossimo rilascio.
