### ISSUE TITLE
Risposta del TED troncata su esito-operazione

### ISSUE THREAD

**Issue by giuseppepace82** [anticorruzione/npa#996]
Il servizio di esito-operazione tronca la risposta del TED rendendo impossibile la visualizzazione e la successiva correzione degli errori:

BODY response:
{"status":200,"title":"OK","detail":"Esecuzione avvenuta con successo","type":"about:blank","listaEsiti":[{"idAppalto":"a6d813e1-db3b-4818-bb2e-919783c97428","idScheda":"9e7e56af-c73f-4c18-964b-4f6fec08b5d3","codiceScheda":"P1_16","esito":{"idTipologica":"esito","codice":"KO"},"tipoOperazione":{"idTipologica":"tipoOperazione","codice":"AP_CONF"},"dataControllo":"2024-01-09T15:10:54.811+00:00","dettaglio":{"idTipologica":"esitoOperazione","codice":"AP_N_CONF"},"errori":[{"idTipologica":"errori","dettaglio":"[400] during [POST] to [http://pcp-qlf-ted-ms.pcp-qlf.svc:8080/validate?language=it] [TedMsClient#validate(String,String)]: [{\"code\":400,\"status\":\"400 BAD_REQUEST\",\"title\":\"Validation Error\",\"errori\":[{\"idTipologica\":\"errori\",\"dettaglio\":\"BT-615-Lot è obbligatorio nel tipo di avviso '16' fatta eccezione per le seguenti cond... (2718 bytes)]","codice":"ERR46"}]}]}

**Comment by giuseppepace82** [comment]
Parametri inviati nella richiesta: idAppalto=a6d813e1-db3b-4818-bb2e-919783c97428&tipoOperazione=AP_CONF&tipoRicerca=ULTIMO_ESITO

**Comment by supportoAnac** [comment]
Anomalia risolta con il rilascio del 12/03/2024.
