### ISSUE TITLE
Schede per aggiudicazione appalti P7_2 e P6_2

### ISSUE THREAD

**Issue by scalabrese11** [anticorruzione/npa#998]
Buongiorno,

avremmo necessità di capire quali schede utilizzare per l'aggiudicazione degli appalti creati mediante le schede P7_2 e P6_2.
Ci confermate che non sono ancora presenti le loro schede di aggiudicazione?
Come bisogna procedere per l'aggiudicazione se si creano ad oggi questi appalti in produzione?

Grazie.

**Comment by mariottiDPA** [comment]
ci uniamo alla domanda.
@supportoAnac si sollecita cortesemente una risposta

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Per arrivare alle schede di aggiudicazione, occore prima comunicare i partecipanti con la scheda S2.</p>

<p>Restiamo a disposizione per eventuali chiarimenti.</p>

<p>Cordiali saluti.</p>

<p> </p>
