### ISSUE TITLE
Delucidazioni utilizzo NAG e A2_29

### ISSUE THREAD

**Issue by scalabrese11** [anticorruzione/npa#999]
Buongiorno,

avremmo bisogno di una conferma:
- la scheda NAG deve essere utilizzata esclusivamente nei casi in cui l'intero appalto viene annullato/non aggiudicato?
- in caso di annullamento di un singolo lotto di un appalto, bisogna comunicare tale annullamento mediante il campo "esitoProcedura" dei "datiBaseRisultatoProcedura" presenti nella scheda A2_29?

Se confermate le due domande precedenti, la scheda NAG e la scheda A2_29 non vanno mai inviate entrambe su uno stesso appalto, è corretto?

Grazie

**Comment by anac-uscp** [comment]
<p>1) No, la scheda NAG contiene tutti i dati relativi alla mancata aggiudicazione di un singolo CIG della gara (e non dell’intera gara), sottosoglia europea. Per le gare sottosoglia europea, è necessario trasmettere la scheda NAG e non la scheda di aggiudicazione per comunicare la mancata aggiudicazione, valorizzando i campi della scheda: GiustificazioneEsitoProcedura e EsitoProceduraAnnullata. </p>

<p>2) Le 2 schede NAG e scheda di aggiudicazione sottosoglia non vanno mai trasmesse insieme. </p>
